let cs = {
  Categories: "Kategorie",
  "Share this event": "Sdílet tuto událost",
  Language: "Jazyk",
  "Show Time Zone": "Zobrazit časové pásmo",
  "Custom Local Settings": "Vlastní místní nastavení",
  "Add and showcase events on your site using a beautiful calendar.":
    "Přidejte a předveďte události na svém webu pomocí krásného kalendáře . ",
  "Week Days": "Týdenní dny",
  "Manage Events": "Spravovat události",
  General: "Všeobecné",
  "Layout Picker": "Výběr rozvržení",
  Month: "Měsíc",
  Monthly: "Měsíční",
  Week: "Týden",
  Weekly: "Týdně",
  Day: "Den",
  Daily: "Denně",
  Agenda: "Denní program",
  "Navigation Buttons": "Navigační tlačítka",
  "Week numbers": "Týdenní čísla",
  "Include Weekends": "Zahrnout víkendy",
  "All-day": "Celý den",
  "All Day": "Celý den",
  Label: "Označení",
  "Fit to Height": "Přizpůsobit výšce",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Chcete-li nastavit App proporce manully tuto možnost zakázat a velikost kalendáře v editoru. ",
  "Default Layout": "Výchozí rozvržení",
  "Monthly view": "Měsíční zobrazení",
  "Weekly and Daily view": "Týdenní a denní zobrazení",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Návštěvníkům můžete poskytnout konzistentnější zážitek tím, že budete zobrazovat stejný počet týdnů ( 6) najednou.",
  "Fixed Weekly Layout": "Opraveno týdenní rozložení",
  back: " zpět ",
  Row: "Řádek",
  "Hours in Weekly View": "Hodiny v týdenním zobrazení",
  "Hours in Daily View": "Hodiny v denním zobrazení",
  Start: "Start",
  End: "Konec",
  "At This Hour": "V tuto hodinu",
  "Add to": "Добави към",
  Button: "Tlačítko",
  Buttons: "Tlačítka",
  Sunday: "Neděle",
  Monday: "Pondělí",
  Tuesday: "Úterý",
  Wednesday: "Středa",
  Thursday: " Čtvrtek ",
  Friday: "Pátek",
  Saturday: "Sobota",
  "Default Date": "Výchozí datum",
  year: " rok ",
  month: " měsíc ",
  mo: " měsíc ",
  days: " dny ",
  ago: " před ",
  ahead: " dopředu ",
  Yesterday: "Včera",
  Today: "Dnes",
  Tomorrow: "Zítra",
  Custom: "Zvyk",
  "Set Daily Rows Limit": "Nastavit denní limit řádků",
  "Set Proportions": "Nastavit proporce",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Povolit návštěvníkovi přidat událost do místních Calnedars , Google, Yahoo, Outlook, ICalendar . ",
  Container: "Kontejner",
  Background: "Pozadí",
  "Container Background": "Pozadí kontejneru",
  "Container Borders": "Hranice kontejneru",
  Calendar: "Kalendář",
  "Event Info Tooltip": "Popis informací o události",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Když se lidé vznášejí nad událostí, uvidí všechny informace o ní v popisku. ",
  "Event Info Window": "Okno s informacemi o události",
  "This is the full information window that opens when someone clicks on the event.":
    "Toto je úplné informační okno, které se otevře, když někdo klikne na událost. ",
  "Use Gradient": "Použít přechod",
  Vertical: "Vertikální",
  Horizontal: "Horizontální",
  First: "První",
  Second: "Druhý",
  diagonal: " diagonální ",
  Radial: "Radiální",
  "Select option": "Vyberte možnost",
  Solid: "Pevný",
  Dotted: "Tečkovaný",
  Dashed: "Dashed",
  Double: "Dvojnásobek",
  "Border Radius": "Hraniční poloměr",
  Padding: "Padding",
  "Date Header": "Záhlaví data",
  "Event Default Color": "Výchozí barva události",
  "Days of Week": "Dny v týdnu",
  "Days of Week Background": "Dny v týdnu na pozadí",
  Date: "datum",
  "Event Title": "Název události",
  "Highlight today": "Zvýrazněte dnes",
  "Highlight Color": "Zvýraznit barvu",
  Hide: "Skrýt",
  "Calendar Border Color": "Barva okraje kalendáře",
  "Calendar Border Width": "Šířka okraje kalendáře",
  "Calendar Border Style": "Styl okraje kalendáře",
  "Font Color": "Barva fontu",
  "Event Background": "Pozadí události",
  "Card Date Color": "Barva data karty",
  "Title Font": "Název písma",
  "Date Font": "Date Font",
  "Description Font": "Popisové písmo",
  "Button Background": "Pozadí tlačítka",
  "Button Text": "Text tlačítka",
  "Border Color": "Border Color",
  "Border Width": "Šířka okraje",
  "Border Type": "Typ ohraničení",
  Title: "Titul",
  Description: "Popis",
  "Background Color": "Barva pozadí",
  Divider: "Oddělovač",
  "Event Details Font": "Písmo podrobností události",
  "Website Link Color": "Barva odkazu na web",
  "Developer Info": "Informace pro vývojáře",
  "User Guide": "Uživatelská příručka",
  "Support e-mail": "Podpora e-mailu",
  "Our Website": "Náš web",
  "App Review": "Recenze aplikace",
  "Enjoying App? Leave us a review in the App Market.":
    "Užíváte si aplikaci? Nechte nás na App App recenzi. ",
  "Review Us": "Recenze nás",
  "Connect With Us": "Spojit se s námi",
  "What's your email?": "Jaký je váš e-mail? ",
  "Invalid email address!": "Neplatná e-mailová adresa! ",
  Comments: "Komentáře",
  "We'd love to hear from you. Send us a message.":
    "Rádi bychom od vás slyšeli. Pošlete nám zprávu. ",
  "Message must be at least 5 characters long":
    "Zpráva musí obsahovat alespoň 5 znaků",
  Send: "Poslat",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Pokud chcete uživateli umožnit přepínání mezi zobrazeními kalendáře, aktivujte tuto možnost a zvolte pohledy, které chcete zobrazit. ",
  Main: "Hlavní",
  Localize: "Lokalizovat",
  Settings: "Nastavení",
  Layouts: "Rozložení",
  Advanced: "Pokročilý",
  Design: "Design",
  Support: "Podpěra, podpora",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Všechna místní nastavení jsou (automaticky) založena na vašem jazyce. Pokud je váš jazyk na seznamu, není třeba tuto sekci upravovat.",
  "Date Format": "Datový formát",
  "Time Format": "Časový formát",
  "Text Direction": "Směr textu",
  "Left to Right": "Zleva do prava",
  "Right to Left": "Zprava doleva",
  "Week Starts On": "Začátek týdne",
  "Agenda Style": "Agenda Styl",
  Classic: "Klasický",
  Modern: "Modern",
  "Agenda Header": "Hlavička agendy",
  "Upcoming Events": "Připravované akce",
  "Agenda Event Limit": "Agenda Limit událostí",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Upgradujte nyní a získejte mnohem více funkcí a užijte si svoji aplikaci v plném rozsahu!",
  "Upgrade Now": "Vylepšit nyní",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Hostit událostí, které trvají celý den? To vám umožní zobrazit je v kalendáři.",
  "24 hours": "24 hodin",
  Sat: "Sobota",
  Sun: "Neděle",
  Mon: "Pondělí",
  Default: "Výchozí",
  "Select custom design style for your calendar.":
    "Vyberte vlastní styl designu pro svůj kalendář.",
  Style: "Styl",
  "Styles and Colors": "Styly a barvy",
  "Calendar Name": "Název kalendáře",
  "Write your Calendar name here": "Sem napište své jméno kalendáře",
  "Enable Search": "Povolit vyhledávání",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Toto není pro vaše uživatele viditelné. Pokud používáte funkci synchronizace kalendáře Boom, nastavte názvy tak, aby se vaše kalendáře odlišovaly.",
  "+ Add Event": "+ Přidat událost",
  "Manage and Sync": "Spravovat a synchronizovat",
  "Show event details as...": "Zobrazit podrobnosti události jako ...",
  Tooltip: "Zobrazit podrobnosti události jako ...",
  Popup: "Informační box",
  None: "Žádný",
  "Show Category": "Zobrazit kategorii",
  "Header Align": "Zarovnat záhlaví",
  "Show Time": "Zobrazit čas",
  "Hours in Weekly/Daily View": "Hodiny v týdenním / denním zobrazení",
  "Share Events": "Sdílet události",
  Shadow: "Stín",
  "Inner Padding": "Vnitřní polstrování",
  Text: "Text",
  "Active Button Border": "Hranice aktivního tlačítka",
  "Light Mode": "Světelný režim",
  "Event Text Color": "Barva textu události",
  Dates: "Termíny",
  Skeleton: "Kostra",
  "Skeleton Color": "Barva kostry",
  Width: "Šířka",
  "Skeleton Style": "Styl kostry",
  Color: "Barva",
  "Section Titles": "Názvy oddílů",
  "Section Content": "Obsah sekce",
  Header: "Záhlaví",
  Map: "Mapa",
  Standard: "Standard",
  Retro: "Retro",
  Silver: "stříbrný",
  Night: "Noc",
  Dark: "Temný",
  Aubergine: "Lilek",
  "Map Header": "Záhlaví mapy",
  "Show Title in mobile": "Zobrazit název v mobilu",
  Card: "Kartu",
  "Card View": "Pohled na kartu",
  "Card background color": "Barva pozadí karty",
  "Title font": "Písmo názvu",
  "Desciption font": "Písmo popisu",
  "Section font": "Sekce písma",
  "Section divider color": "Barva rozdělovače sekcí",
  "General Info": "Obecné informace",
  Venue: "Místo",
  Organizer: "Organizátor",
  Search: "Търсене",
  calendar: "календар",
  "Copy event URL": "Zkopírujte adresu URL události",
  "Copied!": "Копирано!",
  "Add & Share": "Přidat a sdílet",
  "Calendar view": "Zobrazení kalendáře",
  "Add Event": "Přidat událost",
  Uncategorised: "Nezařazeno",
  More: "Více",
  Less: "Méně",
  Register: "Registrovat",
  Guests: "Hosté",
  unlimited: "neomezený",
  "Show more": "Zobrazit více",
  "Add event": "Přidat událost",
  "All Day Event": "Celodenní akce",
  Location: "Umístění",
  "Choose a category": "Vyberte kategorii",
  "Venue name": "Název místa",
  "Venue phone": "Místo telefonu",
  "Venue email": "E-mail místa",
  "Venue website": "Web místa konání",
  "Organizer name": "Název organizátora",
  "Organizer phone": "Telefon organizátora",
  "Organizer email": "E-mail organizátora",
  "Organizer website": "Web organizátora",
  "Personal info": "Osobní informace",
  "First name": "Jméno",
  "Last name": "Příjmení",
  "Email Address": "Emailová adresa",
  "Additional Notes": "Další poznámky",
  Back: "Zadní",
  Save: "Uložit",
  Next: "Další",
  "Your event has been submitted": "Vaše událost byla odeslána",
  "Event submittion has been failed": "Odeslání události se nezdařilo",
  "e.g. Birthday Party": "např. Narozeninová oslava",
  "First Name": "First Name",
  "Last Name": "Příjmení",
  "Phone Number": "Telefonní číslo",
  Address: "Adresa",
  "Your comments": "Vaše připomínky",
  "How many guests?": "Kolik hostů?",
  "Anything else we need to know?": "Ještě něco, co potřebujeme vědět?",
  "Guests:": "Hosté:",
  Submit: "Submit",
  "Go to Calendar": "Přejít na kalendář",
  "Registration completed successfully!": "Registrace byla úspěšně dokončena!",
  "Please check your registered email address":
    "Zkontrolujte prosím svoji registrovanou e-mailovou adresu",
  "Add to Calendar": "Přidat do kalendáře",
  "Share this Event": "Sdílet tuto událost",
  "Sorry something went wrong": "عذرا، هناك خطأ ما",
  "Back to registration": "Zpět k registraci",
  "Date & Location": "Datum a místo",
  "Date & Time": "Čas schůzky",
  home: "Domov",
  "Header align": "Zarovnání záhlaví",
  Footer: "Zápatí",
  "Categories Filter": "kategorie Filtr",
  "Show only upcoming": "Zobrazit pouze nadcházející",
  "Card(s) in a row": "Karty v řadě",
  "Space between cards": "Prostor mezi kartami",
  "Shown events limit": "Shown events limit",
  "Style 1": "Styl 1",
  "Style 2": "Styl 2",
  "Style 3": "Styl 3",
  "Style 4": "Styl 4",
  "Buttons & Links": "Tlačítka a odkazy",
  "Button corner radius": "Poloměr knoflíku",
  "Buttons font": "Tlačítka písmo",
  "Buttons background": "Pozadí tlačítek",
  "Get notified by Email": "Nechte se informovat e-mailem",
  "Review events": "Zkontrolovat události",
  "Click on date": "Klikněte na datum",
  "Add Event button": "Tlačítko Přidat událost",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.",
  connect: "připojit",
  "Synchronized Calendars": "Synchronizované kalendáře",
  "Import events": "Importovat události",
  Disconnect: "Odpojit",
  "Choose calendar": "Vyberte kalendář",
  "Monitor your Wix events through the sync feature":
    "Sledujte své události Wix pomocí funkce synchronizace",
  "Connect all your Boom calendars available on your website":
    "Připojte všechny své kalendáře Boom dostupné na vašem webu",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Plán, připojit a spravovat zoom setkání přímo prostřednictvím našeho kalendáře boom.",
  "Monitor your Event Brite events through the Event Brite sync feature.":
    "Sledujte své události Event Brite pomocí funkce synchronizace Event Brite",
  Email: "E-mailem",
  "Add-ons": "Doplňky",
  "Receive notification emails as soon as users add events to your calendar.":
    "Přijměte e-maily oznámení, jakmile uživatelé přidávají události do kalendáře.",
  "Enable + button on the calendar header":
    "Enable + button on the calendar header",
  "Accept or decline events added by customers before making them public.":
    "Přijmout nebo odmítnout události přidané zákazníky, než je veřejnost.",
  "Switch Add Event": "Přepínač Přidat událost",
  "Enable your browser cookies to connect to your account.":
    "Povolit soubory cookie prohlížeče připojit k vašemu účtu.",
  "Learn more": "Další informace",
  "Print Button": "Tlačítko Print.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Umožnit svým uživatelům vytisknout kalendář události boom v libovolném rozsahu dat.",
  "Show Title on mobile": "Zobrazit titul na mobilu",
  "Show Skeleton on mobile": "Zobrazit kostru na mobil",
  "Start 7-day Business trial": "Začněte svůj 7denní obchodní soud",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Užijte si všechny neomezené funkce, například prodej vstupenek, registrace, doplňky návštěvníků.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Upozornění: Na konci zkušební doby budete vráceni do stávajícího plánu předplatného.",
  "Not Now": "Teď ne",
  "Start free trial": "Začněte zkušební verze zdarma",
  "Congrats!": "Gratuluji!",
  "Your 7-day Business trial has been successfully activated.":
    "Vaše 7denní obchodní zkouška byla úspěšně aktivována.",
  Done: "Hotovo",
  "Title font color": "Barva písma podle názvu",
  "Desciption font color": "Popis Barva písma",
  "Section font color": "Část Barva písma",
  "Card Header": "Záhlaví karty",
  Category: "Kategorie",
  "Display at the": "Zobrazit na.",
  top: "horní",
  bottom: "dno",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Představte filtr kategorie nahoře nebo v dolní části kalendáře.Nastavení se vztahuje pouze na zobrazení programu a karet",
  "Processing your events": "Zpracování vašich událostí",
  "Search for events": "Vyhledávání událostí",
  "There are no events added": "Neexistují žádné přidané události",
  "Location: To be determined": "Umístění: Určeno",
  "No events for selected date": "Žádné události pro vybrané datum",
  Uncategorized: "Nezařazené",
  "Edit event": "Upravit událost",
  "Edit original event": "Upravit původní událost",
  "Copy event": "Kopírovací událost",
  "Copy as new event": "Zkopírujte jako nová událost",
  "Delete event": "Smazat událost",
  "Stop repeating on this date": "Přestaňte opakovat v tomto datu",
  "Exclude this date": "Vyloučit toto datum",
  "Location is going to be announced": "Místo bude oznámeno",
  "Fill your personal information": "Vyplňte své osobní údaje",
  "Check Box": "Zaškrtávací políčko",
  "Single Choice": "Jediná volba",
  Option: "Volba",
  "Share Event": "Sdílet událost",
  "Oops! Something went wrong": "Jejda!Něco se pokazilo",
  "We are sorry this event has already taken place":
    "Je nám líto, že tato akce již proběhla",
  "Back to calendar": "Zpět na kalendář",
  "This field is required": "Toto pole je povinné",
  Phone: "Telefon",
  "Number field": "Pole čísla",
  "Please provide a valid email": "Uveďte prosím platný e -mail",
  "Select at least one option": "Vyberte alespoň jednu možnost",
  "Choose tickets to see total value":
    "Vyberte vstupenky a zobrazíte celkovou hodnotu",
  tickets: "Vstupenky",
  "Choose Tickets": "Vyberte si vstupenky",
  "Choose payment method": "Vyberte způsob platby",
  Pay: "Platit",
  Total: "Celkový",
  Free: "Volný, uvolnit",
  "Buy tickets": "Koupit lístky",
  "Sold Out": "Vyprodáno",
  "Tickets are available": "Vstupenky jsou k dispozici",
  "Sales End": "Prodej",
  "Availible from": "dostupný z",
  "Go to Orders": "Přejít na objednávky",
  "Go to Details": "Přejděte na podrobnosti",
  "Group ticket": "Skupinový lístek",
  Name: "název",
  Price: "Cena",
  "Order by": "Seřadit podle",
  "Order ID": "číslo objednávky",
  Applied: "Aplikovaný",
  Fees: "Poplatky",
  "Enter promo code": "Zadejte promo kód",
  Apply: "Aplikovat",
  "Promo Code": "Promo kód",
  Cash: "Hotovost",
  "You can find your e-tickets attached to your email or download them":
    "Najdete své e-tickety připojené k vašemu e-mailu nebo je stáhněte",
  here: "tady",
  Time: "Čas",
  "Invalid promo code": "Neplatný promo kód",
  "Credit card": "Kreditní karta",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Brzy obdržíte potvrzovací zprávu o úspěšné registraci na vaši e -mailovou adresu.",
  "You can also check your order details below.":
    "Níže můžete také zkontrolovat údaje o vaší objednávce.",
  at: "v",
  Buy: "Koupit",
  Donation: "Sponzorský dar",
  "Enter price": "Podnik",
  Choose: "Vybrat",
  Chosen: "Vybrán",
  "Choose your plan": "Vyberte si svůj plán",
  week: "týden",
  wk: "týden",
  "Choose plan cycle": "Vyberte si cyklus plánu",
  months: "měsíce",
  years: "roky",
  weeks: "týdny",
  "Copy Event Url": "URL kopírování události",
  "You can find your e-tickets attached to your email or print them":
    "Najdete své e-tickety připojené k vašemu e-mailu nebo je vytisknout",
  "Guest Info": "Informace o hostech",
  "Ticket Info": "Informace o lístku",
  "Ticket name": "Název lístku",
  "Ticket price": "Cena lístku",
  "Ticket ID": "ID lístku",
  "If you have any questions contact to organizer":
    "Pokud máte nějaké dotazy, kontaktujte organizátora",
  "As soon as event ends": "Jakmile událost skončí",
  "1 day after event ends": "1 den po skončení akce",
  "7 days after event ends": "7 dní po skončení události",
  "14 days after event ends": "14 dní po skončení události",
  "30 days after event ends": "30 dní po skončení události",
  Menu: "Jídelní lístek",
  "No event for selected date": "Žádná událost pro vybrané datum",
  view: "Pohled",
  List: "Seznam",
  Year: "Rok",
  Yearly: "Roční",
  "Year view header": "Roční záhlaví zobrazení",
  "Yearly Style": "Roční styl",
  "There are no events": "Nejsou žádné události",
  Autotranslation: "Autotranslation.",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Po povolení bude widget kalendáře přeložen na základě jazyka webu.* Všimněte si, že pokud název kalendáře a popisy jsou zadávány texty, které nemohou být přeloženy.",
  "Note on mobile": "Poznámka k mobilu",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Vypnout nebo změnit text panelu 'Žádné události' na mobilní verzi kalendáře",
  Autodeletion: "Autodeletion",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Povolení možnosti automaticky odstraní vaše minulé události z kalendáře.",
  "This does not apply to repeating events!":
    "To se nevztahuje na opakující se události!",
  "Notify event creators about the guest": "Informovat uživatele o hostu",
  "Send event creators notification emails as soon as guests register for their events":
    "Pošlete e-maily s upozorněním tvůrců událostí, jakmile se hosté zaregistrují na své akce",
  "List View Type": "Typ zobrazení seznamu",
  "Description font": "Písmo popisu",
  Connect: "připojit",
  "You have no events": "Du har ingen begivenheder",
  Synchronize: "Synchronizovat",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Google Kalender-synkronisering giver dig mulighed for at integrere dine begivenheder og sessioner med din Boom-kalender.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Outlook Kalender-synkronisering giver dig mulighed for at integrere dine begivenheder og sessioner med din Boom-kalender.",
  "Your message has been sent successfully!":
    "Tvoje zpráva byla úspěšně odeslána!",
  "There are no synchronized calendars":
    "Der er ingen synkroniserede kalendere",
  "to view more than 7 events": "for at se mere end 7 begivenheder",
  "Mobile app": "Mobilní aplikace",
  "Admin Account": "Admin konto",
  Password: "Heslo",
  "Second User": "Druhý uživatel",
  Edit: "Upravit",
  "Guest limit": "Limit hostů",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Všechna místní nastavení jsou (automaticky) na základě vašeho jazyka.Pokud je váš jazyk v seznamu, není třeba tuto část přizpůsobit.",
  available: "k dispozici",
  next: "další",
  Tickets: "Vstupenky",
  Quantity: "Množství",
  "Promo code": "Promo kód",
  "Select a payment method": "Zvolit způsob platby",
  Fee: "Poplatek",
  Book: "Rezervovat",
  "All the tickets have been sold out": "Všechny vstupenky byly vyprodány",
  "Choose at least one ticket": "Vyberte si alespoň jednu letenku",
  "First choose ticket": "Nejprve vyberte lístek",
  "Please fill out your personal information.":
    "Vyplňte prosím své osobní údaje.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "Chcete-li úspěšný nákup, vyberte prosím preferovaný způsob platby a zadejte Promo kód pro zvýhodněné vstupenky.",
  "Credit/Debit card": "Kreditní / Debetní karta",
  "print here.": "Tisk zde.",
  "QR code for all tickets": "QR kód pro všechny vstupenky",
  Duration: "Doba trvání",
  "Full Name": "Celé jméno",
  "Ticket id": "ID vstupenky",
  "Group id": "ID skupiny",
  "Choose your ticket.": "Vyberte si jízdenku.",
  "Fill out your personal information.": "Vyplňte své osobní údaje.",
  "Add the payment details.": "Přidání platebních údajů.",
  "To be determined": "Být odhodlán",
  "You can find your e-tickets attached to the email or":
    "Vaše e-lístky naleznete na e-mailu nebo",
  "print here": "Tisk zde",
  "Full name": "Celé jméno",
  "Group ID": "ID skupiny",
  "to Book": "zarezervovat",
  "Unfortunately, your card has been declined":
    "Bohužel, vaše karta byla odmítnuta",
  "Thank you for your purchase!": "Děkuji za Váš nákup!",
  "Find your printable e-tickets attached to the confirmation email":
    "Najděte své tisknutelné e-tickety připojené k potvrzovacímu e-mailu",
  Confirm: "Potvrdit",

  "Add event": "Přidat událost",
  Events: "Události",
  "Event details": "Podrobnosti o události",
  Registration: "Registrace",
  "Guests list": "Seznam hostů",
  Ticket: "Lístek",
  "General Info": "Obecné informace",
  "Customize the general settings of your event":
    "Přizpůsobte obecné nastavení vaší události",
  "Event Title": "Název události",
  "e.g. Birthday Party": "např. Narozeninová oslava",
  "All Day Event": "Celodenní akce",
  Cross: "Přejít",
  Timeline: "Časová osa",
  "Repeating event": "Opakující se událost",
  Location: "Umístění",
  "Venue name": "Jméno místa konání",
  Description: "Popis",
  Image: "obraz",
  Color: "Barva",
  Category: "Kategorie",
  "Add your events to color categories and let your users classify them easily":
    "Přidejte své události do kategorií barev a nechte své uživatele snadno klasifikovat",
  "Category name": "Název Kategorie",
  "e.g. Birthdays": "např. Narozeniny",
  Venue: "Místo",
  "Where the event takes place": "Kde se událost koná",
  "Venue name": "Jméno místa konání",
  "Venue phone": "Telefon",
  "Venue email": "E -mail v místě konání",
  "Venue website": "Webové stránky místa konání",
  Organizer: "Organizátor",
  "Person who makes the event": "Osoba, která dělá událost",
  "Organizer name": "Jméno organizátoru",
  "Organizer phone": "Pořadatelský telefon",
  "Organizer email": "Organizátor e -mail",
  "Organizer website": "Organizační web",
  Save: "Uložit",
  Cancel: "zrušení",
  Import: "Import",
  Past: "Minulost",
  All: "Všechno",
  Upcoming: "Nadcházející",
  Uncategorised: "Nezařazené",
  "Date Ascending": "Datum vzestupné",
  "Date Descending": "Datum klesá",
  "Title by A-Z": "Název od A-Z",
  "Title by Z-A": "Název od Z-A",
  "There are no events for this period":
    "Pro toto období neexistují žádné události",

  "Auto-Convert Date & Time": "Datum a čas automaticky konvertujte",
  TimeZone: "Časové pásmo",
  Autodeletion: "Autodeletion",
  "Layout Settings": "Nastavení rozvržení",
  "Yeatly view": "Yeatly View",
  "Monthly view header": "Měsíční záhlaví zobrazení",
  "Weekly/Daily view header": "Týdenní/denní záhlaví zobrazení",
  Acendings: "Acendings",
  Descending: "Klesající",
  Standart: "Standarkt",
  Silver: "stříbrný",
  Retro: "Retro",
  Dark: "Temný",
  Night: "Noc",
  Aubergine: "Lilek",
  "List view header": "Záhlaví zobrazení seznamu",
  "Side by Side View": "Pohledu vedle sebe",
  "Customize Proportions": "Přizpůsobte proporce",
  "Card Margins": "Kartové marže",
  "Image opacity (%)": "Opacity obrazu (%)",
  "Side by Side Header": "Bok po boku záhlaví",
  "Text Align": "Zarovnání textu",
  "Timeline View": "Zobrazit časovou osu",
  "Title font color": "Název písma Color",
  "Desciption font color": "Barva písma po desciption",
  "Line color": "Barva linky",
  "Date Font color": "Datum barvy písma",
  "Daily events background": "Pozadí denních událostí",
  Alignment: "Zarovnání",
  Vertical: "Vertikální",
  Horizontal: "Horizontální",
  "Vertical Alignment": "Vertikální zarovnání",
  Right: "Že jo",
  Center: "Centrum",
  "Horizontal Alignment": "Horizontální zarovnání",
  Top: "Horní",
  Center: "Centrum",
  Bottom: "Dno",
  "Dates Circle Design": "Návrh kruhu",
  "Next To The Circle": "Vedle kruhu",
  "In The Circle": "V kruhu",
  "Timeline Header": "Záhlaví časové osy",
  Timeline: "Časová osa",
  "Show only upcoming": "Zobrazit pouze nadcházející",
  "Order by": "Seřadit podle",
  "Timeline Event Limit": "Limit události na časové ose",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Umožněte návštěvníkovi přidat událost na místní calnedars: Google, Yahoo, Outlook, ICalendar.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Umožněte návštěvníkovi sdílet vaši akci s Facebookem, LinkedIn, Twitter atd.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Přidejte možnost vyhledávání do svého kalendáře a nechte lidem hledat vaše události podle názvu, místa konání atd.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Povolte svým uživatelům tisknout kalendář události Boom v libovolném rozsahu.",
  "Click to apply a theme to Calendar":
    "Kliknutím použijete motiv do kalendáře",
  "Date container color": "Datum barvy kontejneru",
  "Daily events background": "Pozadí denních událostí",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Pomocí doplňků nainstalujte pokročilé funkce ve svých kalendářích, takže jsou funkčnější!",
  "Open Add-ons Store": "Otevřený obchod s doplňky",
  Monday: "pondělí",
  Tuesday: "úterý",
  Wednesday: "středa",
  Thursday: "Čtvrtek",
  Friday: "pátek",
  Saturday: "sobota",
  Sunday: "Neděle",
  "Yearly view": "Roční pohled",
  Ascending: "Vzestupné",
  "Show event time next to title": "Zobrazit čas události vedle názvu",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Upravte datum a čas události na místní čas uživatele na základě jejich časového pásma.",
  "Display the time zone alongside the event date.":
    "Zobrazit časové pásmo vedle data události.",
  "Show event time next to title": "Zobrazit čas události vedle názvu",
  "Time Zone": "Časové pásmo",
  "Upload Image": "Nahrát obrázek",
  "Choose a Category": "Vyberte kategorii",
  "Color you have chosen will not be shown as you choose category":
    "Barva, kterou jste vybrali, se při výběru kategorie nezobrazí",
  Website: "webová stránka",
  Next: "další",
  Save: "Uložit",
  "Last Name": "Příjmení",
  "Personal Info": "Osobní informace",
  Back: "Zpět",
  "This field is required": "Toto pole je povinné",
  "Your event has been submitted": "Vaše událost byla předložena",
  "Enter a location": "Zadejte umístění",
  "Display the time zone alongside the event date.":
    "Zobrazit časové pásmo vedle data události.",
  Home: "Domov",
  "Side By Side Event Limit": "Limit událostí vedle sebe",
  "Mobille App": "Aplikace MoBille",
  category: "kategorie",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Snadno sledujte svůj plán importem událostí z Facebooku do kalendáře.",
  "Synchronized Pages": "Synchronizované stránky",
  "There are no synchronized pages": "Neexistují žádné synchronizované stránky",
  "Choose page": "Vyberte stránku",
  "You have no events": "Nemáte žádné události",
};
export default cs;
