let cy = {
  Categories: "Categorïau",
  "Share this event": "Rhannwch y digwyddiad hwn",
  Language: "Iaith",
  "Show Time Zone": "Dangos Parth Amser",
  "Custom Local Settings": "Gosodiadau Lleol Custom",
  "Add and showcase events on your site using a beautiful calendar.":
    "Ychwanegwch ac arddangos digwyddiadau ar eich gwefan gan ddefnyddio calendr hardd.",
  "Week Days": "Diwrnodau Wythnos",
  "Manage Events": "Rheoli Digwyddiadau",
  General: "Gyffredinol",
  "Layout Picker": "Codwr cynllun",
  Month: "Misoedd",
  Monthly: "Misol",
  Week: "Wythnosau",
  Weekly: "Wythnosol",
  Day: "Diwrnod",
  Daily: "Bob dydd",
  Agenda: "Agenda",
  "Navigation Buttons": "Botymau llywio",
  "Week numbers": "Rhifau Wythnosau",
  "Include Weekends": "Cynnwys penwythnosau",
  "All-day": "Trwy'r dydd",
  "All Day": "Trwy'r dydd",
  Label: "Labelith",
  "Fit to Height": "Yn ffit i uchder",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "I osod cyfrannau app analluogi'r opsiwn hwn a newid maint y calendr yn y golygydd.",
  "Default Layout": "Cynllun diofyn",
  "Monthly view": "Golygfa fisol",
  "Weekly and Daily view": "Golygfa wythnosol a dyddiol",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Gallwch roi profiad mwy cyson i ymwelwyr trwy ddangos yr un nifer o wythnosau (6) ar y tro.",
  "Fixed Weekly Layout": "Cynllun wythnosol sefydlog",
  back: "baciwyd",
  Row: "Rhesi",
  "Hours in Weekly View": "Oriau mewn golygfa wythnosol",
  "Hours in Daily View": "Oriau yn y golwg ddyddiol",
  Start: "Dechrau",
  End: "Terfyna ’",
  "At This Hour": "Ar yr awr hon",
  Button: "Fotymon",
  Buttons: "Fotymau",
  Sunday: "Sul",
  Monday: "Dydd Llun",
  Tuesday: "Dydd Mawrth",
  Wednesday: "Dydd Mercher",
  Thursday: "Dydd Iau",
  Friday: "Dydd Gwener",
  Saturday: "Dydd Sadwrn",
  "Default Date": "Dyddiad diofyn",
  year: "blwyddyn",
  month: "misoedd",
  mo: "Mo",
  days: "nyddiau",
  ago: "yn ôl",
  ahead: "o flaen",
  Yesterday: "Ddoe",
  Today: "Heddiw",
  Tomorrow: "Yfory",
  Custom: "Arferol",
  "Set Daily Rows Limit": "Gosod Terfyn rhesi dyddiol",
  "Set Proportions": "Gosod cyfrannau",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Caniatáu i ymwelydd ychwanegu digwyddiad at Caledars lleol: Google, Yahoo, Outlook, ICalendar.",
  Container: "Gynhwysydd",
  Background: "Nghefndir",
  "Container Background": "Cefndir Cynhwysydd",
  "Container Borders": "Ffiniau cynhwysydd",
  Calendar: "Galendr",
  "Event Info Tooltip": "Gwybodaeth Digwyddiad Offer",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Pan fydd pobl yn hofran dros ddigwyddiad byddant yn gweld yr holl wybodaeth amdano mewn cyngor offer.",
  "Event Info Window": "Ffenestr Gwybodaeth Digwyddiad",
  "This is the full information window that opens when someone clicks on the event.":
    "Dyma'r ffenestr wybodaeth lawn sy'n agor pan fydd rhywun yn clicio ar y digwyddiad.",
  "Use Gradient": "Defnyddio graddiant",
  Vertical: "Fertigol",
  Horizontal: "Llorweddol",
  First: "Yn gyntaf",
  Second: "Heiliwn",
  diagonal: "croeslin",
  Radial: "Reiddiol",
  "Select option": "Dewiswch Opsiwn",
  Solid: "Soleb",
  Dotted: "Dotiog",
  Dashed: "Rhugled",
  Double: "Dyblwch",
  "Border Radius": "Radiws ffin",
  Padding: "Padin",
  "Date Header": "Pennawd dyddiad",
  "Event Default Color": "Lliw diofyn digwyddiad",
  "Days of Week": "Dyddiau'r Wythnos",
  "Days of Week Background": "Dyddiau o Gefndir yr Wythnos",
  Date: "Dyddid",
  "Event Title": "Teitl digwyddiad",
  "Highlight today": "Uchafbwyntiwch heddiw",
  "Highlight Color": "Uchafbwynt lliw",
  Hide: "Cwatiff",
  "Calendar Border Color": "Lliw ffin calendr",
  "Calendar Border Width": "Lled ffin calendr",
  "Calendar Border Style": "Arddull ffin calendr",
  "Font Color": "Lliw ffont",
  "Event Background": "Cefndir digwyddiad",
  "Card Date Color": "Lliw dyddiad cerdyn",
  "Title Font": "Ffont teitl",
  "Date Font": "Ffont Dyddiad",
  "Description Font": "Disgrifiad ffont",
  "Button Background": "Cefndir botwm",
  "Button Text": "Testun botwm",
  "Border Color": "Ffiniau",
  "Border Width": "Lled",
  "Border Type": "Math o",
  Title: "Teitl",
  Description: "Ddisgrifiad",
  "Background Color": "Lliw cefndir",
  Divider: "Rannwr",
  "Event Details Font": "Ffont Manylion y Digwyddiad",
  "Website Link Color": "Lliw cyswllt gwefan",
  "Developer Info": "Gwybodaeth Datblygwr",
  "User Guide": "Canllawiau Canllawiau",
  "Support e-mail": "Cefnogi e-bost",
  "Our Website": "Ein Gwefan",
  "App Review": "Adolygiad App",
  "Enjoying App? Leave us a review in the App Market.":
    "Mwynhau ap? Gadewch adolygiad inni yn y farchnad apiau.",
  "Review Us": "Adolygwch ni",
  "Connect With Us": "Cysylltu â Ni",
  "What's your email?": "Beth yw eich e -bost?",
  "Invalid email address!": "Cyfeiriad e -bost annilys!",
  Comments: "Sylwadau",
  "We'd love to hear from you. Send us a message.":
    "Byddem wrth ein bodd yn clywed gennych. Anfonwch neges atom.",
  "Message must be at least 5 characters long":
    "Rhaid i'r neges fod o leiaf 5 nod o hyd",
  Send: "Yrent",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Os ydych chi am ganiatáu i'r defnyddiwr newid rhwng golygfeydd calendr, galluogi'r opsiwn hwn a dewis y golygfeydd rydych chi am eu dangos.",
  Main: "Main",
  Localize: "Lleolo",
  Settings: "Ngosodiadau",
  Layouts: "Gynlluniau",
  Advanced: "Uwch",
  Design: "Llunion",
  Support: "Cefnogith",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Mae'r holl leoliadau lleol (yn awtomatig) yn seiliedig ar eich iaith. Os yw'ch iaith ar y rhestr, nid oes angen addasu'r adran hon.",
  "Date Format": "Fformat dyddiad",
  "Time Format": "Fformat Amser",
  "Text Direction": "Cyfeiriad Testun",
  "Left to Right": "Chwith i'r dde",
  "Right to Left": "Dde i'r chwith",
  "Week Starts On": "Wythnos yn dechrau ymlaen",
  "Agenda Style": "Arddull Agenda",
  Classic: "Clasur",
  Modern: "Fodern",
  "Agenda Header": "Pennawd Agenda",
  "Upcoming Events": "Digwyddiadau i ddod",
  "Agenda Event Limit": "Terfyn Digwyddiad Agenda",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Uwchraddio nawr a chael llawer mwy o nodweddion a mwynhau'ch app yn llawn!",
  "Upgrade Now": "Uwchraddio nawr",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Digwyddiadau cynnal sy'n para trwy'r dydd? Mae hyn yn caniatáu ichi eu dangos ar eich calendr.",
  "24 hours": "24 awr",
  Sat: "Eistedda ’",
  Sun: "Machod",
  Mon: "Mon",
  Default: "Diofyn",
  "Select custom design style for your calendar.":
    "Dewiswch arddull dylunio arfer ar gyfer eich calendr.",
  Style: "Arddull",
  "Styles and Colors": "Arddulliau a lliwiau",
  "Calendar Name": "Enw calendr",
  "Write your Calendar name here": "Ysgrifennwch eich enw calendr yma",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Nid yw hyn yn weladwy i'ch defnyddwyr. Gosodwch enwau i wahaniaethu eich calendrau wrth ddefnyddio'r swyddogaeth cysoni calendr ffyniant.",
  "General Info": "Gwybodaeth Gyffredinol",
  Venue: "Lleoliad",
  Organizer: "Drefnydd",
  Search: "Chwilotau",
  "Add to": "Ychwanega",
  calendar: "galendr",
  "Copy event URL": "Copïwch URL Digwyddiad",
  "Copied!": "Copïo!",
  "Add & Share": "Ychwanegu a Rhannu",
  Map: "Mapiwyd",
  "Calendar view": "Golygfa Calendr",
  "Add Event": "Ychwanegu digwyddiad",
  Uncategorised: "Heb ei gategoreiddio",
  More: "Mwy",
  Less: "Llai",
  Register: "Gofrestrent",
  Card: "Gerdyn",
  Guests: "Gwesteion",
  unlimited: "diderfyn",
  "Show more": "Dangos mwy",
  "Enable Search": "Galluogi chwilio",
  "+ Add Event": " + Ychwanegu digwyddiad",
  "Manage and Sync": "Rheoli a Sync",
  "Show event details as...": "Dangos manylion digwyddiadau fel ...",
  Tooltip: "Tipyn",
  Popup: "Naidlen",
  None: "Neb",
  "Show Category": "Dangos categori",
  "Header Align": "Pennawd Alinio",
  "Show Time": "Amser sioe",
  "Hours in Weekly/Daily View": "Oriau mewn golygfa wythnosol/dyddiol",
  "Share Events": "Rhannu Digwyddiadau",
  Shadow: "Nghysgodion",
  "Inner Padding": "Padin mewnol",
  Text: "Tecstio",
  "Active Button Border": "Ffin botwm gweithredol",
  "Light Mode": "Modd ysgafn",
  "Event Text Color": "Lliw testun digwyddiad",
  Dates: "Dyddiadau",
  Skeleton: "Sgerbydau",
  "Skeleton Color": "Lliw sgerbwd",
  Width: "Lled",
  "Skeleton Style": "Arddull sgerbwd",
  Color: "Lliwiff",
  "Section Titles": "Teitlau adran",
  "Section Content": "Cynnwys adran",
  Header: "Phennawd",
  Standard: "Safonol",
  Retro: "Retro",
  Silver: "Harian",
  Night: "Nos",
  Dark: "Dywyllaf",
  Aubergine: "Aubergine",
  "Map Header": "Pennawd map",
  "Show Title in mobile": "Dangos teitl yn Mobile",
  "Card View": "Golygfa cerdyn",
  "Card background color": "Lliw cefndir cerdyn",
  "Title font": "Ffont teitl",
  "Desciption font": "Ffont desciption",
  "Section font": "Ffont adran",
  "Section divider color": "Lliw rhannwr adran",
  "Add event": "Ychwanegu digwyddiad",
  "All Day Event": "Digwyddiad trwy'r dydd",
  Location: "Lleoliad",
  "Choose a category": "Dewiswch gategori",
  "Venue name": "Enw'r lleoliad",
  "Venue phone": "Ffôn",
  "Venue email": "E -bost lleoliad",
  "Venue website": "Gwefan Lleoliad",
  "Organizer name": "Enw Trefnydd",
  "Organizer phone": "Ffôn Trefnydd",
  "Organizer email": "E -bost trefnydd",
  "Organizer website": "Gwefan Trefnydd",
  "Personal info": "Gwybodaeth Bersonol",
  "First name": "Enw cyntaf",
  "Last name": "Enw olaf",
  "Email Address": "Cyfeiriad ebost",
  "Additional Notes": "Nodiadau Ychwanegol",
  Back: "Baciwyd",
  Save: "Hiachasit",
  Next: "Nesaf",
  "Your event has been submitted": "Mae eich digwyddiad wedi'i gyflwyno",
  "Event submittion has been failed": "Mae cyflwyniad digwyddiadau wedi methu",
  "e.g. Birthday Party": "e.e. Parti Penblwydd",
  "First Name": "Enw cyntaf",
  "Last Name": "Enw olaf",
  "Phone Number": "Rhif ffôn",
  Address: "Cyfeirio",
  "Your comments": "Eich Sylwadau",
  "How many guests?": "Faint o westeion?",
  "Anything else we need to know?":
    "Unrhyw beth arall y mae angen i ni ei wybod?",
  "Guests:": "Gwesteion:",
  Submit: "Chyflwynem",
  "Go to Calendar": "Ewch i Galendr",
  "Registration completed successfully!":
    "Cwblhawyd cofrestru yn llwyddiannus!",
  "Please check your registered email address":
    "Gwiriwch eich cyfeiriad e -bost cofrestredig",
  "Add to Calendar": "Ychwanegu at galendr",
  "Share this Event": "Rhannwch y digwyddiad hwn",
  "Sorry something went wrong":
    "Mae'n ddrwg gennym fod rhywbeth wedi mynd o'i le",
  "Back to registration": "Yn ôl i gofrestru",
  "Date & Location": "Dyddiad a Lleoliad",
  "Date & Time": "Dyddiad ac Amser",
  home: "nghartrefi",
  "Header align": "Pennawd Alinio",
  Footer: "Nhroedyddion",
  "Categories Filter": "Hidlo Categorïau",
  "Show only upcoming": "Dangos yn unig sydd ar ddod",
  "Card(s) in a row": "Cerdyn (au) yn olynol",
  "Space between cards": "Lle rhwng cardiau",
  "Shown events limit": "Terfyn Digwyddiadau Dangos",
  "Style 1": "Arddull 1",
  "Style 2": "Arddull 2",
  "Style 3": "Arddull 3",
  "Style 4": "Arddull 4",
  "Buttons & Links": "Botymau a Dolenni",
  "Button corner radius": "Radiws cornel botwm",
  "Buttons font": "Botymau ffont",
  "Buttons background": "Cefndir botymau",
  "Get notified by Email": "Cael eich hysbysu trwy e -bost",
  "Review events": "Adolygu Digwyddiadau",
  "Click on date": "Cliciwch ar y Dyddiad",
  "Add Event button": "Ychwanegu Botwm Digwyddiad",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Mae cysoni calendr yn caniatáu ichi integreiddio'ch digwyddiadau a'ch sesiynau â'ch calendr ffyniant.",
  connect: "chysyllta ’",
  "Synchronized Calendars": "Calendrau cydamserol",
  "Import events": "Mewnforio digwyddiadau",
  Disconnect: "Ddatgysylltith",
  "Choose calendar": "Dewiswch Galendr",
  "Monitor your Wix events through the sync feature":
    "Monitro'ch digwyddiadau Wix trwy'r nodwedd Sync",
  "Connect all your Boom calendars available on your website":
    "Cysylltwch eich holl galendrau ffyniant sydd ar gael ar eich gwefan",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Amserlen, ymuno, a rheoli cyfarfodydd chwyddo trwy ein calendr ffyniant.",
  "Monitor your Event Brite events through the Event Brite sync feature.":
    "Monitro'ch Digwyddiad Digwyddiadau Brite Trwy'r Digwyddiad Brite Sync Nodwedd",
  Email: "E -bost",
  "Add-ons": "Ychwanegiadau",
  "Receive notification emails as soon as users add events to your calendar.":
    "Derbyn e -byst hysbysu cyn gynted ag y bydd defnyddwyr yn ychwanegu digwyddiadau at eich calendr.",
  "Enable + button on the calendar header":
    "Galluogi + botwm ar y pennawd calendr",
  "Accept or decline events added by customers before making them public.":
    "Derbyn neu wrthod digwyddiadau a ychwanegwyd gan gwsmeriaid cyn eu gwneud yn gyhoeddus.",
  "Switch Add Event": "Switsh ychwanegu digwyddiad",
  "Enable your browser cookies to connect to your account.":
    "Galluogi eich cwcis porwr i gysylltu â'ch cyfrif.",
  "Learn more": "Dysgu mwy",
  "Print Button": "Botwm argraffu",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Caniatáu i'ch defnyddwyr argraffu calendr eich digwyddiadau ffyniant mewn unrhyw ystod dyddiad.",
  "Show Title on mobile": "Dangos teitl ar symudol",
  "Show Skeleton on mobile": "Dangos sgerbwd ar symudol",
  "Start 7-day Business trial": "Dechreuwch dreial busnes 7 diwrnod",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Mwynhewch yr holl nodweddion Unlimiited, megis gwerthu tocynnau, cofrestru, ychwanegiadau digwyddiadau ymwelwyr.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Sylwch: Ar ddiwedd y cyfnod prawf, cewch eich dychwelyd i'ch cynllun tanysgrifio presennol.",
  "Not Now": "Ddim nawr",
  "Start free trial": "Dechreuwch dreial am ddim",
  "Congrats!": "Llongyfarchiadau!",
  "Your 7-day Business trial has been successfully activated.":
    "Mae eich treial busnes 7 diwrnod wedi'i actifadu'n llwyddiannus.",
  Done: "Wedi gwneud",
  "Title font color": "Lliw ffont teitl",
  "Desciption font color": "Lliw ffont desciption",
  "Section font color": "Lliw ffont adran",
  "Card Header": "Pennawd Cerdyn",
  Category: "Categori",
  "Display at the": "Arddangos yn y",
  top: "frigon",
  bottom: "waelod",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Arddangos yr hidlydd categori ar y brig neu ar waelod y calendr. Mae'r gosodiadau yn berthnasol i agenda a golygfeydd cardiau yn unig",
  "Processing your events": "Prosesu'ch digwyddiadau",
  "Search for events": "Chwilio am ddigwyddiadau",
  "There are no events added": "Nid oes unrhyw ddigwyddiadau wedi'u hychwanegu",
  "Location: To be determined": "Lleoliad: I'w bennu",
  "No events for selected date": "Dim digwyddiadau ar gyfer dyddiad dethol",
  Uncategorized: "Heb gategori",
  "Edit event": "Golygu Digwyddiad",
  "Edit original event": "Golygu Digwyddiad Gwreiddiol",
  "Copy event": "Digwyddiad Copïo",
  "Copy as new event": "Copïwch fel digwyddiad newydd",
  "Delete event": "Dileu digwyddiad",
  "Stop repeating on this date": "Stopio ailadrodd ar y dyddiad hwn",
  "Exclude this date": "Eithrio'r dyddiad hwn",
  "Location is going to be announced": "Bydd y lleoliad yn cael ei gyhoeddi",
  "Fill your personal information": "Llenwch eich Gwybodaeth Bersonol",
  "Check Box": "Blwch Gwirio",
  "Single Choice": "Dewis sengl",
  Option: "Opsiwn",
  "Share Event": "Digwyddiad Rhannu",
  "Oops! Something went wrong": "Wps! Aeth rhywbeth o'i le",
  "We are sorry this event has already taken place":
    "Mae'n ddrwg gennym fod y digwyddiad hwn eisoes wedi digwydd",
  "Back to calendar": "Yn ôl i'r Calendr",
  "This field is required": "Mae angen y maes hwn",
  Phone: "Ffoniwch",
  "Number field": "Maes Rhif",
  "Please provide a valid email": "Darparwch e -bost dilys",
  "Select at least one option": "Dewiswch o leiaf un opsiwn",
  "Choose tickets to see total value":
    "Dewiswch docynnau i weld cyfanswm y gwerth",
  tickets: "thocynnau",
  "Choose Tickets": "Dewiswch Docynnau",
  "Choose payment method": "Dewiswch y Dull Talu",
  Pay: "Rhoesent",
  Total: "Cyfanswm",
  Free: "Ryddhaem",
  "Buy tickets": "Prynu tocynnau",
  "Sold Out": "Gwerthu allan",
  "Tickets are available": "Mae tocynnau ar gael",
  "Sales End": "Diwedd Gwerthu",
  "Availible from": "Ar gael o",
  "Go to Orders": "Ewch i Orchmynion",
  "Go to Details": "Manylion",
  "Group ticket": "Tocyn grŵp",
  Name: "Henwem",
  Price: "Phris",
  "Order by": "Gorchymyn gan",
  "Order ID": "Gorchymyn ID",
  Applied: "Cymhwysol",
  Fees: "Ffioedd",
  "Enter promo code": "Rhowch y Cod Promo",
  Apply: "Ymgeisiant",
  "Promo Code": "Cod Promo",
  Cash: "Arian parod",
  "You can find your e-tickets attached to your email or download them":
    "Gallwch ddod o hyd i'ch e-docynnau ynghlwm wrth eich e-bost neu eu lawrlwytho",
  here: "yma",
  Time: "Hamser",
  "Invalid promo code": "Cod promo annilys",
  "Credit card": "Cerdyn credyd",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Cyn bo hir, byddwch yn derbyn neges gadarnhau o gofrestru llwyddiannus i'ch cyfeiriad e -bost.",
  "You can also check your order details below.":
    "Gallwch hefyd wirio manylion eich archeb isod.",
  at: "at",
  Buy: "Phrynu",
  Donation: "Rhoddion",
  "Enter price": "ENTER PRIS",
  Choose: "Ddetholem",
  Chosen: "Newis",
  "Choose your plan": "Dewiswch Eich Cynllun",
  week: "wythnosau",
  wk: "wk",
  "Choose plan cycle": "Dewiswch Gylch y Cynllun",
  months: "misoedd",
  years: "mlynyddoedd",
  weeks: "wythnosau",
  "Copy Event Url": "Copïwch URL Digwyddiad",
  "You can find your e-tickets attached to your email or print them":
    "Gallwch ddod o hyd i'ch e-docynnau ynghlwm wrth eich e-bost neu eu hargraffu",
  "Guest Info": "Gwybodaeth westai",
  "Ticket Info": "Gwybodaeth am docynnau",
  "Ticket name": "Enw Tocyn",
  "Ticket price": "Pris tocyn",
  "Ticket ID": "ID Tocyn",
  "If you have any questions contact to organizer":
    "Os oes gennych unrhyw gwestiynau cyswllt i'r trefnydd",
  "As soon as event ends": "Cyn gynted ag y bydd y digwyddiad yn dod i ben",
  "1 day after event ends": "1 diwrnod ar ôl i'r digwyddiad ddod i ben",
  "7 days after event ends": "7 diwrnod ar ôl i'r digwyddiad ddod i ben",
  "14 days after event ends": "14 diwrnod ar ôl i'r digwyddiad ddod i ben",
  "30 days after event ends": "30 diwrnod ar ôl i'r digwyddiad ddod i ben",
  Menu: "Bwydlen",
  "No event for selected date": "Dim digwyddiad ar gyfer dyddiad dethol",
  view: "golygfa",
  List: "Restraf",
  Year: "Blwyddyn",
  Yearly: "Flynyddol",
  "Year view header": "Pennawd BLWYDDYN",
  "Yearly Style": "Arddull flynyddol",
  "There are no events": "Nid oes unrhyw ddigwyddiadau",
  Autotranslation: "Awtotranslation",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Ar ôl ei alluogi, bydd eich teclyn calendr yn cael ei gyfieithu yn seiliedig ar iaith y wefan. *Sylwch, cyhyd â bod teitl calendr, a disgrifiadau yn destunau mewnbwn na ellir eu cyfieithu.",
  "Note on mobile": "Nodyn ar Symudol",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Diffodd neu newid testun y bar “dim digwyddiadau” ar fersiwn symudol o galendr",
  Autodeletion: "Autodeletion",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Bydd galluogi'r opsiwn, yn tynnu'ch digwyddiadau yn y gorffennol o'r calendr yn awtomatig.",
  "This does not apply to repeating events!":
    "Nid yw hyn yn berthnasol i ailadrodd digwyddiadau!",
  "Notify event creators about the guest":
    "Hysbysu crewyr digwyddiadau am y gwestai",
  "Send event creators notification emails as soon as guests register for their events":
    "Anfonwch e -byst hysbysu crewyr digwyddiadau cyn gynted ag y bydd gwesteion yn cofrestru ar gyfer eu digwyddiadau",
  "List View Type": "Rhestr Gweld Math",
  "Description font": "Disgrifiad ffont",
  Connect: "Chysyllta ’",
  "You have no events": "Nid oes gennych unrhyw ddigwyddiadau",
  Synchronize: "Gydamsera",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Mae Google Calendar Sync yn caniatáu ichi integreiddio'ch digwyddiadau a'ch sesiynau â'ch calendr ffyniant.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Mae Sync Calendr Outlook yn caniatáu ichi integreiddio'ch digwyddiadau a'ch sesiynau â'ch calendr ffyniant.",
  "Your message has been sent successfully!":
    "Mae eich neges wedi'i hanfon yn llwyddiannus!",
  "There are no synchronized calendars": "Nid oes unrhyw galendrau cydamserol",
  "to view more than 7 events": "I weld mwy na 7 digwyddiad",
  "Mobile app": "Ap symudol",
  "Admin Account": "Gyfrif Gweinyddol",
  Password: "Gyfrinair",
  "Second User": "Ail ddefnyddiwr",
  Edit: "Olygwch",
  "Guest limit": "Terfyn gwestai",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Mae'r holl leoliadau lleol (yn awtomatig) yn seiliedig ar eich iaith. Os yw'ch iaith ar y rhestr, nid oes angen addasu'r adran hon.",
  available: "AR GAEL",
  next: "nesaf",
  Tickets: "Thocynnau",
  Quantity: "Feintiau",
  "Promo code": "Cod promo",
  "Select a payment method": "Dewiswch ddull talu",
  Fee: "Ffioedd",
  Book: "Fwciais",
  "All the tickets have been sold out":
    "Mae'r tocynnau i gyd wedi'u gwerthu allan",
  "Choose at least one ticket": "Dewiswch o leiaf un tocyn",
  "First choose ticket": "Dewiswch y tocyn yn gyntaf",
  "Please fill out your personal information.":
    "Llenwch eich gwybodaeth bersonol.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "I brynu'n llwyddiannus, dewiswch eich dull talu a ffefrir a nodwch y cod promo ar gyfer tocynnau gostyngedig.",
  "Credit/Debit card": "Cerdyn Credyd/Debyd",
  "print here.": "Argraffu yma.",
  "QR code for all tickets": "Cod QR ar gyfer pob tocyn",
  Duration: "Hydoedd",
  "Full Name": "Enw llawn",
  "Ticket id": "ID Tocyn",
  "Group id": "ID grŵp",
  "Choose your ticket.": "Dewiswch eich tocyn.",
  "Fill out your personal information.": "Llenwch eich gwybodaeth bersonol.",
  "Add the payment details.": "Ychwanegwch y manylion talu.",
  "To be determined": "I'w benderfynu",
  "You can find your e-tickets attached to the email or":
    "Gallwch ddod o hyd i'ch e-docynnau ynghlwm wrth yr e-bost neu",
  "print here": "Argraffu yma",
  "Full name": "Enw llawn",
  "Group ID": "ID grŵp",
  "to Book": "i archebu",
  "Unfortunately, your card has been declined":
    "Yn anffodus, mae eich cerdyn wedi'i wrthod",
  "Thank you for your purchase!": "Diolch am eich pryniant!",
  "Find your printable e-tickets attached to the confirmation email":
    "Dewch o hyd i'ch e-docynnau y gellir eu hargraffu ynghlwm wrth yr e-bost cadarnhau",
  Confirm: "Chadarnhasoch",

  "Add event": "Ychwanegu digwyddiad",
  Events: "Digwyddiadau",
  "Event details": "Manylion y Digwyddiad",
  Registration: "Gofrestriad",
  "Guests list": "Rhestr Gwesteion",
  Ticket: "Nhocynnau",
  "General Info": "Gwybodaeth Gyffredinol",
  "Customize the general settings of your event":
    "Addasu gosodiadau cyffredinol eich digwyddiad",
  "Event Title": "Teitl digwyddiad",
  "e.g. Birthday Party": "e.e. Parti Penblwydd",
  "All Day Event": "Digwyddiad trwy'r dydd",
  Cross: "Groesen",
  Timeline: "Llinell Amser",
  "Repeating event": "Digwyddiad Ailadrodd",
  Location: "Lleoliad",
  "Venue name": "Enw'r lleoliad",
  Description: "Ddisgrifiad",
  Image: "Nelwedd",
  Color: "Lliwiff",
  Category: "Categori",
  "Add your events to color categories and let your users classify them easily":
    "Ychwanegwch eich digwyddiadau at gategorïau lliw a gadael i'ch defnyddwyr eu dosbarthu'n hawdd",
  "Category name": "Enw'r Categori",
  "e.g. Birthdays": "e.e. Penblwyddi",
  Venue: "Lleoliad",
  "Where the event takes place": "Lle mae'r digwyddiad yn digwydd",
  "Venue name": "Enw'r lleoliad",
  "Venue phone": "Ffôn",
  "Venue email": "E -bost lleoliad",
  "Venue website": "Gwefan Lleoliad",
  Organizer: "Drefnydd",
  "Person who makes the event": "Person sy'n gwneud y digwyddiad",
  "Organizer name": "Enw Trefnydd",
  "Organizer phone": "Ffôn Trefnydd",
  "Organizer email": "E -bost trefnydd",
  "Organizer website": "Gwefan Trefnydd",
  Save: "Hiachasit",
  Cancel: "Chansliff",
  Import: "Mewnforio",
  Past: "Gorffennol",
  All: "I gyd",
  Upcoming: "Ar ddod",
  Uncategorised: "Heb ei gategoreiddio",
  "Date Ascending": "Dyddiad yn esgyn",
  "Date Descending": "Dyddiad yn disgyn",
  "Title by A-Z": "Teitl gan A-Z",
  "Title by Z-A": "Teitl gan z-a",
  "There are no events for this period":
    "Nid oes unrhyw ddigwyddiadau ar gyfer y cyfnod hwn",

  "Auto-Convert Date & Time": "Dyddiad ac Amser Convert Auto-Convert",
  TimeZone: "Amserlenni",
  Autodeletion: "Autodeletion",
  "Layout Settings": "Gosodiadau Cynllun",
  "Yeatly view": "Golygfa Yeatly",
  "Monthly view header": "Pennawd golygfa fisol",
  "Weekly/Daily view header": "Pennawd Golygfa Wythnosol/Dyddiol",
  Acendings: "Afreolau",
  Descending: "Disgynnol",
  Standart: "Standart",
  Silver: "Harian",
  Retro: "Retro",
  Dark: "Dywyllaf",
  Night: "Nos",
  Aubergine: "Aubergine",
  "List view header": "Rhestr Gweld Pennawd",
  "Side by Side View": "Golygfa ochr yn ochr",
  "Customize Proportions": "Addasu cyfrannau",
  "Card Margins": "Ymylon cerdyn",
  "Image opacity (%)": "Delwedd didwylledd (%)",
  "Side by Side Header": "Pennawd ochr yn ochr",
  "Text Align": "Alinio testun",
  "Timeline View": "Golygfa Llinell Amser",
  "Title font color": "Lliw ffont teitl",
  "Desciption font color": "Lliw ffont desciption",
  "Line color": "Lliw Llinell",
  "Date Font color": "Dyddiad Ffont Lliw",
  "Daily events background": "Cefndir digwyddiadau dyddiol",
  Alignment: "Aliniadau",
  Vertical: "Fertigol",
  Horizontal: "Llorweddol",
  "Vertical Alignment": "Aliniad Fertigol",
  Right: "Dde",
  Center: "Nghanolfan",
  "Horizontal Alignment": "Aliniad Llorweddol",
  Top: "Brigant",
  Center: "Nghanolfan",
  Bottom: "Waelod",
  "Dates Circle Design": "Dyluniad Cylch Dyddiadau",
  "Next To The Circle": "Wrth ymyl y cylch",
  "In The Circle": "Yn y cylch",
  "Timeline Header": "Pennawd Llinell Amser",
  Timeline: "Llinell Amser",
  "Show only upcoming": "Dangos yn unig sydd ar ddod",
  "Order by": "Gorchymyn gan",
  "Timeline Event Limit": "Terfyn Digwyddiad Llinell Amser",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Caniatáu i ymwelydd ychwanegu digwyddiad at Caledars lleol: Google, Yahoo, Outlook, ICalendar.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Caniatáu i ymwelydd rannu'ch digwyddiad â Facebook, LinkedIn, Twitter ac ati.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Ychwanegwch opsiwn chwilio ar eich calendr i adael i bobl chwilio'ch digwyddiadau yn ôl teitl, lleoliad, ac ati.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Caniatáu i'ch defnyddwyr argraffu calendr eich digwyddiadau ffyniant mewn unrhyw ystod dyddiad.",
  "Click to apply a theme to Calendar": "Cliciwch i gymhwyso thema i galendr",
  "Date container color": "Lliw Cynhwysydd Dyddiad",
  "Daily events background": "Cefndir digwyddiadau dyddiol",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Defnyddiwch yr ychwanegion i osod nodweddion uwch ar eich calendrau, gan eu gwneud yn fwy swyddogaethol!",
  "Open Add-ons Store": "Siop Ychwanegiadau Agored",
  Monday: "Dydd Llun",
  Tuesday: "Dydd Mawrth",
  Wednesday: "Dydd Mercher",
  Thursday: "Dydd Iau",
  Friday: "Dydd Gwener",
  Saturday: "Dydd Sadwrn",
  Sunday: "Sul",
  Ascending: "Esgynnol",
  "Yearly view": "Golygfa flynyddol",
  "Show event time next to title": "Dangos amser digwyddiad nesaf at y teitl",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Addaswch ddyddiad ac amser y digwyddiad i amser lleol y defnyddiwr yn seiliedig ar eu parth amser.",
  "Display the time zone alongside the event date.":
    "Arddangos y parth amser ochr yn ochr â dyddiad y digwyddiad.",
  "Show event time next to title": "Dangos amser digwyddiad nesaf at y teitl",
  "Time Zone": "Parth Amser",
  "Upload Image": "Llwythwch ddelwedd",
  "Choose a Category": "Dewiswch gategori",
  "Color you have chosen will not be shown as you choose category":
    "Ni fydd lliw rydych chi wedi'i ddewis yn cael ei ddangos wrth i chi ddewis categori",
  Website: "Gwefan",
  Next: "Nesaf",
  Save: "Hiachasit",
  "Last Name": "Enw olaf",
  "Personal Info": "Gwybodaeth Bersonol",
  Back: "Yn ôl",
  "This field is required": "Mae angen y maes hwn",
  "Your event has been submitted": "Mae eich digwyddiad wedi'i gyflwyno",
  "Enter a location": "Mynd i mewn i leoliad",
  "Display the time zone alongside the event date.":
    "Arddangos y parth amser ochr yn ochr â dyddiad y digwyddiad.",
  Home: "Nghartrefi",
  "Side By Side Event Limit": "Terfyn digwyddiad ochr yn ochr",
  "Mobille App": "Ap Mobille",
  category: "Categori",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Cadwch olwg ar eich amserlen yn hawdd trwy fewnforio eich digwyddiadau Facebook i'ch calendr.",
  "Synchronized Pages": "Tudalennau Cydamserol",
  "There are no synchronized pages": "Nid oes unrhyw dudalennau wedi'u cysoni",
  "Choose page": "Dewiswch dudalen",
  "You have no events": "Nid oes gennych unrhyw ddigwyddiadau",
};
export default cy;
