let el = {
  Language: "Γλώσσα",
  "Show Time Zone": "Εμφάνιση ζώνης ώρας",
  "Custom Local Settings": "Προσαρμοσμένες τοπικές ρυθμίσεις",
  "Add and showcase events on your site using a beautiful calendar.":
    "Προσθήκη και εμφάνιση συμβάντων στον ιστότοπό σας χρησιμοποιώντας ένα όμορφο ημερολόγιο . ",
  "Week Days": "Εβδομάδες ημέρες",
  "Manage Events": "Διαχείριση εκδηλώσεων",
  General: "Γενικός",
  "Layout Picker": "Επιλογή διαρρυθμίσεων",
  Month: "Μήνας",
  Monthly: "Μηνιαίος",
  Week: "Εβδομάδα",
  Weekly: "Εβδομαδιαίος",
  Day: "Ημέρα",
  Daily: "Καθημερινά",
  Agenda: "Ημερήσια διάταξη",
  "Navigation Buttons": "Κουμπιά πλοήγησης",
  "Week numbers": "Αριθμοί εβδομάδας",
  "Include Weekends": "Συμπερίληψη Σαββατοκύριακου ",
  "All-day": "Ολη μέρα",
  "All Day": "Ολη μέρα",
  Label: "Επιγραφή",
  "Fit to Height": "Προσαρμογή σε Ύψος",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Για να ρυθμίσετε τις αναλογίες εφαρμογών, απενεργοποιήστε χειροκίνητα αυτή την επιλογή και αλλάξτε το μέγεθος του Ημερολογίου στον επεξεργαστή.",
  "Default Layout": "Προεπιλεγμένη διάταξη",
  "Monthly view": "Μηνιαία προβολή",
  "Weekly and Daily view": "Εβδομαδιαία και ημερήσια προβολή",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Μπορείτε να δώσετε στους επισκέπτες μια πιο συνεπή εμπειρία δείχνοντας τον ίδιο αριθμό εβδομάδων ( 6) κάθε φορά.",
  "Fixed Weekly Layout": "Σταθερή εβδομαδιαία διάταξη",
  back: " πίσω ",
  Row: "Σειρά",
  "Hours in Weekly View": "Ώρες στην εβδομαδιαία προβολή",
  "Hours in Daily View": "Ώρες στην καθημερινή προβολή",
  Start: "Αρχή",
  End: "Τέλος",
  "At This Hour": "Σε αυτήν την ώρα",
  "Add to": "Προσθήκη στο",
  Button: "Κουμπί",
  Buttons: "Κουμπιά",
  Sunday: "Κυριακή",
  Monday: "Δευτέρα",
  Tuesday: "Τρίτη",
  Wednesday: "Τετάρτη",
  Thursday: " Πέμπτη ",
  Friday: "Παρασκευή",
  Saturday: "Σάββατο",
  "Default Date": "Ημερομηνία προεπιλογής",
  year: " έτος ",
  month: " μήνας ",
  mo: " μήνας ",
  days: " ημέρες ",
  ago: " πριν ",
  ahead: " μπροστά ",
  Yesterday: "Εχθές",
  Today: "Σήμερα",
  Tomorrow: "Αύριο",
  Custom: "Εθιμο",
  "Set Daily Rows Limit": "Ορισμός ημερήσιων ορίων γραμμών",
  "Set Proportions": "Ρύθμιση αναλογιών",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Επιτρέψτε στον επισκέπτη να προσθέσει συμβάν στο τοπικό Calnedars , Google, Yahoo, Outlook, ICalendar . ",
  Container: "Δοχείο",
  Background: "Ιστορικό",
  "Container Background": "Ιστορικό κοντέινερ",
  "Container Borders": "Περιοχή δοχείων",
  Calendar: "Ημερολόγιο",
  "Event Info Tooltip": "Πληροφορίες συμβάντος συμβάντων συμβάντων",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Όταν οι άνθρωποι αιωρούνται πάνω από ένα συμβάν, θα δουν όλες τις πληροφορίες σχετικά με αυτό σε μια επεξήγηση εργαλείου ",
  "Event Info Window": "Παράθυρο πληροφοριών συμβάντος",
  "This is the full information window that opens when someone clicks on the event.":
    "Αυτό είναι το πλήρες παράθυρο πληροφοριών που ανοίγει όταν κάποιος κάνει κλικ στο συμβάν. ",
  "Use Gradient": "Χρήση κλίσης",
  Vertical: "Κατακόρυφος",
  Horizontal: "Οριζόντιος",
  First: "Πρώτα",
  Second: "Δεύτερος",
  diagonal: " διαγώνιος ",
  Radial: "Ακτινικός",
  "Select option": "Επιλογή επιλογής",
  Solid: "Στερεός",
  Dotted: "Διάσπαρτος",
  Dashed: "Διακεκομμένη",
  Double: "Διπλό",
  "Border Radius": "Ακτίνα ορίου",
  Padding: "Υλικό παραγεμίσματος",
  "Date Header": "Κεφαλίδα ημερομηνίας",
  "Event Default Color": "Χρώμα προεπιλογής συμβάντος",
  "Days of Week": "Ημέρες της εβδομάδας",
  "Days of Week Background": "Ημέρες της εβδομάδας",
  Date: "Ημερομηνία",
  "Event Title": "Τίτλος εκδήλωσης",
  "Highlight today": "Επισημάνετε σήμερα",
  "Highlight Color": "Επισημάνετε χρώμα",
  Hide: "Κρύβω",
  "Calendar Border Color": "Χρώμα περιθωρίου ημερολογίου",
  "Calendar Border Width": "Πλάτος περιθωρίου ημερολογίου",
  "Calendar Border Style": "Στυλ γραμμής πλαισίου",
  "Font Color": "Χρώμα γραμματοσειράς",
  "Event Background": "Ιστορικό συμβάντων",
  "Card Date Color": "Χρόνος ημερομηνίας κάρτας",
  "Title Font": "Γραμματοσειρά τίτλου",
  "Date Font": "Ημερομηνία γραμματοσειράς",
  "Description Font": "Γραμματοσειρά περιγραφής",
  "Button Background": "Κουμπί Background",
  "Button Text": "Κείμενο κουμπιού",
  "Border Color": "Χρώμα πλαισίου",
  "Border Width": "Πλάτος περιθωρίου",
  "Border Type": "Τύπος περιγράμματος",
  Title: "Τίτλος",
  Description: "Περιγραφή",
  "Background Color": "Χρώμα του φόντου",
  Divider: "Διαιρών",
  "Event Details Font": "Λεπτομέρειες συμβάντος γραμματοσειράς",
  "Website Link Color": "Χρώμα συνδέσμου ιστότοπου",
  "Developer Info": "Πληροφορίες προγραμματιστή",
  "User Guide": "ΟΔΗΓΟΣ ΧΡΗΣΤΗ",
  "Support e-mail": "Υποστήριξη",
  "Our Website": "Η ιστοσελίδα μας",
  "App Review": "Ενημέρωση εφαρμογής",
  "Enjoying App? Leave us a review in the App Market.":
    "Απολαύστε την εφαρμογή; Αφήστε μας μια κριτική στην αγορά εφαρμογών. ",
  "Review Us": "Εξετάστε μας",
  "Connect With Us": "Σύνδεση με εμάς",
  "What's your email?": "Ποιο είναι το email σας; ",
  "Invalid email address!": "Μη έγκυρη διεύθυνση ηλεκτρονικού ταχυδρομείου! ",
  Comments: "Σχόλια",
  "We'd love to hear from you. Send us a message.":
    "Θα θέλαμε να σας ακούσουμε. Στείλτε μας ένα μήνυμα. ",
  "Message must be at least 5 characters long":
    "Μήνυμα πρέπει να έχει μήκος τουλάχιστον 5 χαρακτήρων",
  Send: "Στείλετε",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Αν θέλετε να επιτρέψετε στο χρήστη να αλλάξει τις προβολές ημερολογίου, ενεργοποιήστε αυτήν την επιλογή και επιλέξτε τις προβολές που θέλετε να εμφανίσετε.",
  Main: "Κύριος",
  Localize: "Εντοπίζω",
  Settings: "Ρυθμίσεις",
  Layouts: "Διατάξεις",
  Advanced: "Προχωρημένος",
  Design: "Σχέδιο",
  Support: "Υποστήριξη",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Όλες οι τοπικές ρυθμίσεις βασίζονται (αυτόματα) στη γλώσσα σας. Εάν η γλώσσα σας βρίσκεται στη λίστα, δεν χρειάζεται να προσαρμόσετε αυτήν την ενότητα.",
  "Date Format": "Μορφή ημερομηνίας",
  "Time Format": "Μορφή ώρας",
  "Text Direction": "Κατεύθυνση κειμένου",
  "Left to Right": "Από αριστερά προς τα δεξιά",
  "Right to Left": "Δεξιά προς τα αριστερά",
  "Week Starts On": "Εβδομάδα ξεκινά",
  "Agenda Style": "Ατζέντα στυλ",
  Classic: "Κλασσικός",
  Modern: "Modern",
  "Agenda Header": "Ημερολόγιο ημερήσιας διάταξης",
  "Upcoming Events": "Επερχόμενα γεγονότα",
  "Agenda Event Limit": "Όριο εκδήλωσης ατζέντας",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Αναβαθμίστε τώρα και αποκτήστε περισσότερα χαρακτηριστικά και απολαύστε το APP σας πλήρως!",
  "Upgrade Now": "Αναβάθμισε τώρα",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Φιλοξενία γεγονότων που διαρκούν όλη την ημέρα; Αυτό σας επιτρέπει να τα εμφανίσετε στο ημερολόγιό σας",
  "24 hours": "24 ώρες",
  Sun: "Κυριακή",
  Mon: "Δευτέρα",
  Sat: "Σάββατο",
  Default: "Προκαθορισμένο",
  "Select custom design style for your calendar.":
    "Επιλέξτε το προσαρμοσμένο στυλ σχεδιασμού για το ημερολόγιό σας.",
  Style: "Στυλ",
  "Styles and Colors": "Στυλ και χρώματα",
  "Calendar Name": "Όνομα ημερολογίου",
  "Write your Calendar name here": "Γράψτε το όνομα του ημερολογίου σας εδώ",
  "Enable Search": "Ενεργοποίηση αναζήτησης",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Αυτό δεν είναι ορατό στους χρήστες σας. Ορίστε ονόματα για να διαφοροποιήσετε τα ημερολόγιά σας όταν χρησιμοποιείτε τη λειτουργία Συγχρονισμός ημερολογίου Boom.",
  "+ Add Event": "+ Προσθήκη εκδήλωσης",
  "Manage and Sync": "Διαχείριση και συγχρονισμός",
  "Show event details as...": "Εμφάνιση λεπτομερειών εκδήλωσης ως ...",
  Tooltip: "Επεξήγηση εργαλείου",
  Popup: "Πλαίσιο πληροφοριών",
  None: "Κανένας",
  "Show Category": "Εμφάνιση κατηγορίας",
  "Header Align": "Ευθυγράμμιση κεφαλίδας",
  "Show Time": "Εμφάνιση ώρας",
  "Hours in Weekly/Daily View": "Ώρες σε εβδομαδιαία / καθημερινή προβολή",
  "Share Events": "Κοινοποίηση εκδηλώσεων",
  Shadow: "Σκιά",
  "Inner Padding": "Εσωτερική επένδυση",
  Text: "Κείμενο",
  "Active Button Border": "Περίγραμμα ενεργού κουμπιού",
  "Light Mode": "Λειτουργία φωτισμού",
  "Event Text Color": "Χρώμα κειμένου συμβάντος",
  Dates: "Ημερομηνίες",
  Skeleton: "Σκελετός",
  "Skeleton Color": "Χρώμα σκελετού",
  Width: "Πλάτος",
  "Skeleton Style": "Στυλ σκελετού",
  Color: "Χρώμα",
  "Section Titles": "Τίτλοι Ενότητας",
  "Section Content": "Περιεχόμενο Ενότητας",
  Header: "Επί κεφαλής",
  Map: "Χάρτης",
  Standard: "Πρότυπο",
  Retro: "Ρετρό",
  Silver: "Ασήμι",
  Night: "Νύχτα",
  Dark: "Σκοτάδι",
  Aubergine: "Μελιτζάνα",
  "Map Header": "Κεφαλίδα χάρτη",
  "Show Title in mobile": "Εμφάνιση τίτλου σε κινητό",
  Card: "Κάρτα",
  "Card View": "Προβολή καρτών",
  "Card background color": "Χρώ��α φόντου κάρτας",
  "Title font": "Γραμματοσειρά τίτλου",
  "Desciption font": "Γραμματοσειρά περιγραφής",
  "Section font": "Ενότητα γραμματοσειράς",
  "Section divider color": "Χρώμα διαχωριστικού τμήματος",
  Categories: "Κατηγορίες",
  "Share this event": "Μοιραστείτε αυτήν την εκδήλωση",
  "General Info": "Γενικές πληροφορίες",
  Venue: "Τόπος συναντήσεως",
  Organizer: "Διοργανωτής",
  Search: "Αναζήτηση",
  calendar: "Ημερολόγιο",
  "Copy event URL": "Αντιγραφή διεύθυνσης URL συμβάντος",
  "Copied!": "Αντιγράφηκε!",
  "Add & Share": "Προσθήκη & κοινή χρήση",
  "Calendar view": "Προβολή ημερολογίουم",
  "Add Event": "Προσθήκη εκδήλωσης",
  Uncategorised: "Χωρίς κατηγορία",
  More: "Περισσότερο",
  Less: "Πιο λιγο",
  Register: "Κανω ΕΓΓΡΑΦΗ",
  Guests: "Επισκέπτες",
  unlimited: "απεριόριστος",
  "Show more": "Δείτε περισσότερα",
  "Add event": "Προσθήκη εκδήλωσης",
  "All Day Event": "Ολοήμερο γεγονός",
  Location: "Τοποθεσία",
  "Choose a category": "Επιλέξτε μια κατηγορία",
  "Venue name": "Όνομα χώρου",
  "Venue phone": "Venue phone",
  "Venue email": "Ηλεκτρονικό ταχυδρομείο Venue",
  "Venue website": "Ιστοσελίδα τόπου συναντήσεως",
  "Organizer name": "Όνομα οργανωτή",
  "Organizer phone": "Τηλέφωνο οργανωτή",
  "Organizer email": "Ηλεκτρονικό ταχυδρομείο οργανωτή",
  "Organizer website": "Ιστοσελίδα διοργανωτή",
  "Personal info": "Προσωπικές πληροφορίες",
  "First name": "Ονομα",
  "Last name": "Επίθετο",
  "Email Address": "Διεύθυνση ηλεκτρονικού ταχυδρομείου",
  "Additional Notes": "Επιπρόσθετες σημειώσεις",
  Back: "Πίσω",
  Save: "Σώσει",
  Next: "Επόμενο",
  "Your event has been submitted": "Ηεκδήλωσή σας έχει υποβληθεί",
  "Event submittion has been failed": "Ηυποβολή εκδήλωσης απέτυχε",
  "e.g. Birthday Party": "π.χ. Πάρτι γενεθλίων",
  "First Name": "Ονομα",
  "Last Name": "Επίθετο",
  "Phone Number": "Τηλεφωνικό νούμερο",
  Address: "Διεύθυνση",
  "Your comments": "Τα σχόλια σας",
  "How many guests?": "Πόσους επισκέπτες;",
  "Anything else we need to know?": "Οτιδήποτε άλλο πρέπει να γνωρίζουμε;",
  "Guests:": "Επισκέπτες:",
  Submit: "υποβάλλουν",
  "Go to Calendar": "Μεταβείτε στο Ημερολόγιο",
  "Registration completed successfully!": "Η εγγραφή ολοκληρώθηκε με επιτυχία!",
  "Please check your registered email address":
    "Ελέγξτε την καταχωρισμένη διεύθυνση email σας",
  "Add to Calendar": "Προσθήκη στο Ημερολόγιο",
  "Share this Event": "Μοιραστείτε αυτό το συμβάν",
  "Sorry something went wrong": "Συγνώμη, κάτι πήγε στραβά",
  "Back to registration": "Επιστροφή στην εγγραφή",
  "Date & Location": "Ημερομηνία & τοποθεσία",
  "Date & Time": "Ημερομηνία ώρα",
  home: "Zuhause",
  "Header align": "Ευθυγράμμιση κεφαλίδας",
  Footer: "Fusszeile",
  "Categories Filter": "κατηγορίες Φίλτρο",
  "Show only upcoming": "Show nur in Kürze",
  "Card(s) in a row": "Karte (n) hintereinander",
  "Space between cards": "Abstand zwischen den Karten",
  "Shown events limit": "Limit für angezeigte Ereignisse",
  "Style 1": "Stil 1",
  "Style 2": "Stil 2",
  "Style 3": "Stil 3",
  "Style 4": "Στυλ 4",
  "Buttons & Links": "Buttons & Links.",
  "Button corner radius": "Ακτίνα γωνίας κουμπιού",
  "Buttons font": "Γραμματοσειρά κουμπιών",
  "Buttons background": "Schaltflächen Hintergrund",
  "Get notified by Email": "Lassen Sie sich per E-Mail benachrichtigen",
  "Review events": "Ελέγξτε τις εκδηλώσεις",
  "Click on date": "Κάντε κλικ στην ημερομηνία",
  "Add Event button": "Προσθήκη κουμπιού συμβάντος",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Η συγχρονισμός του ημερολογίου σας επιτρέπει να ενσωματώσετε τα συμβάντα και τις συνεδρίες σας με το ημερολόγιο της έκρηξης.",
  connect: "verbinden",
  "Synchronized Calendars": "Συγχρονισμένα ημερολόγια",
  "Import events": "Ereignisse importieren",
  Disconnect: "Αποσυνδέω",
  "Choose calendar": "Kalender auswählen",
  "Monitor your Wix events through the sync feature":
    "Überwachen Sie Ihre Wix-Ereignisse über die Synchronisierungsfunktion",
  "Connect all your Boom calendars available on your website":
    "Verbinden Sie alle Ihre Auslegerkalender auf Ihrer Website",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Προγραμματίστε, λάβετε μέρος και διαχειριστείτε τις συσκέψεις Zoom μέσω του Ημερολογίου Boom.",
  "Monitor your Event Brite events through the Event Brite sync feature.":
    "Überwachen Sie Ihre Event Brite-Ereignisse mithilfe der Event Brite-Synchronisierungsfunktion",
  Email: "ΗΛΕΚΤΡΟΝΙΚΗ ΔΙΕΥΘΥΝΣΗ",
  "Add-ons": "Πρόσθετα",
  "Receive notification emails as soon as users add events to your calendar.":
    "Λάβετε μηνύματα ειδοποίησης μόλις οι χρήστες προσθέτουν συμβάντα στο ημερολόγιό σας.",
  "Enable + button on the calendar header":
    "Enable + button on the calendar header",
  "Accept or decline events added by customers before making them public.":
    "Να αποδεχθούν ή να απορρίπτονται τα γεγονότα που προστέθηκαν από τους πελάτες προτού τις δημοσιοποιηθούν.",
  "Switch Add Event": "Διακόπτης Προσθήκη συμβάντος",
  "Enable your browser cookies to connect to your account.":
    "Ενεργοποιήστε τα cookies του προγράμματος περιήγησης για να συνδεθείτε με το λογαριασμό σας.",
  "Learn more": "Learn more",
  "Print Button": "Κουμπί εκτύπωσης",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Επιτρέψτε στους χρήστες σας να εκτυπώσουν το ημερολόγιο εκδήλωσης Boom σε οποιοδήποτε εύρος ημερομηνιών.",
  "Show Title on mobile": "Εμφάνιση τίτλου στο κινητό",
  "Show Skeleton on mobile": "Εμφάνιση σκελετού στο κινητό",
  "Start 7-day Business trial": "Ξεκινήστε την επιχείρησή σας 7 ημερών",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Απολαύστε όλα τα απεριόριστα χαρακτηριστικά, όπως πωλούν εισιτήρια, εγγραφή, πρόσθετα συμβάντων επισκεπτών.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Σημείωση: Στο τέλος της δοκιμαστικής περιόδου, θα επιστραφεί στο υπάρχον πρόγραμμα συνδρομής σας.",
  "Not Now": "Οχι τώρα",
  "Start free trial": "Ξεκινήστε τη ΔΩΡΕΑΝ δοκιμή",
  "Congrats!": "Συγχαρητήρια!",
  "Your 7-day Business trial has been successfully activated.":
    "Η επιχειρηματική δοκιμή σας 7 ημερών έχει ενεργοποιηθεί με επιτυχία.",
  Done: "Εγινε",
  "Title font color": "Χρώμα γραμματοσειράς τίτλου",
  "Desciption font color": "Περιγραφή Χρώμα γραμματοσειράς",
  "Section font color": "Χρώμα γραμματοσειράς ενότητας",
  "Card Header": "Κεφαλίδα καρτών",
  Category: "Κατηγορία",
  "Display at the": "Εμφάνιση στο",
  top: "μπλουζα",
  bottom: "κάτω μέρος",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Παρουσιάστε το φίλτρο κατηγορίας στην κορυφή ή στο κάτω μέρος του ημερολογίου.Οι ρυθμίσεις ισχύουν μόνο για την ημερήσια διάταξη και τις προβολές καρτών",
  "Processing your events": "Επεξεργασία των γεγονότών σας",
  "Search for events": "Αναζήτηση για εκδηλώσεις",
  "There are no events added": "Δεν υπάρχουν συμβάντα",
  "Location: To be determined": "Τοποθεσία: Να προσδιοριστεί",
  "No events for selected date":
    "Δεν υπάρχουν συμβάντα για επιλεγμένη ημερομηνία",
  Uncategorized: "Μη ταξινομημένος",
  "Edit event": "Επεξεργασία συμβάντος",
  "Edit original event": "Επεξεργασία πρωτότυπου γεγονότος",
  "Copy event": "Αντιγραφή",
  "Copy as new event": "Αντιγράψτε ως νέο συμβάν",
  "Delete event": "Διαγραφή συμβάντος",
  "Stop repeating on this date":
    "Σταματήστε να επαναλαμβάνετε την ημερομηνία αυτή",
  "Exclude this date": "Εξαιρέστε αυτήν την ημερομηνία",
  "Location is going to be announced": "Η τοποθεσία πρόκειται να ανακοινωθεί",
  "Fill your personal information": "Συμπληρώστε τα προσωπικά σας στοιχεία",
  "Check Box": "Πλαίσιο ελέγχου",
  "Single Choice": "Μεμονωμένη επιλογή",
  Option: "Επιλογή",
  "Share Event": "Εκδήλωση κοινής χρήσης",
  "Oops! Something went wrong": "Ωχ!Κάτι πήγε στραβά",
  "We are sorry this event has already taken place":
    "Λυπούμαστε που αυτό το γεγονός έχει ήδη πραγματοποιηθεί",
  "Back to calendar": "Επιστροφή στο ημερολόγιο",
  "This field is required": "Αυτό το πεδίο απαιτείται",
  Phone: "Τηλέφωνο",
  "Number field": "Πεδίο αριθμού",
  "Please provide a valid email": "Δώστε ένα έγκυρο email",
  "Select at least one option": "Επιλέξτε τουλάχιστον μία επιλογή",
  "Choose tickets to see total value":
    "Επιλέξτε εισιτήρια για να δείτε συνολική αξία",
  tickets: "εισιτήρια",
  "Choose Tickets": "Επιλέξτε εισιτήρια",
  "Choose payment method": "Διαλέξτε μέθοδο πληρωμής",
  Pay: "Πληρωμή",
  Total: "Σύνολο",
  Free: "Ελεύθερος",
  "Buy tickets": "Αγορά εισιτηρίων",
  "Sold Out": "Εξαντλημένα",
  "Tickets are available": "Τα εισιτήρια είναι διαθέσιμα",
  "Sales End": "Λήξη πωλήσεων",
  "Availible from": "διαθέσιμο από",
  "Go to Orders": "Μεταβείτε στις παραγγελίες",
  "Go to Details": "Μεταβείτε στις λεπτομέρειες",
  "Group ticket": "Ομαδικό εισιτήριο",
  Name: "Ονομα",
  Price: "Τιμή",
  "Order by": "Ταξινόμηση κατά",
  "Order ID": "Αριθμός Παραγγελίας",
  Applied: "Εφαρμοσμένος",
  Fees: "Αμοιβές",
  "Enter promo code": "Εισαγάγετε τον κωδικό προώθησης",
  Apply: "Ισχύουν",
  "Promo Code": "Κωδικός προώθησης",
  Cash: "Μετρητά",
  "You can find your e-tickets attached to your email or download them":
    "Μπορείτε να βρείτε τα e-tickets σας συνδεδεμένα με το email σας ή να τα κατεβάσετε",
  here: "εδώ",
  Time: "χρόνος",
  "Invalid promo code": "Μη έγκυρος κωδικός προσφοράς",
  "Credit card": "Πιστωτική κάρτα",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Σύντομα θα λάβετε ένα μήνυμα επιβεβαίωσης επιτυχούς εγγραφής στη διεύθυνση email σας.",
  "You can also check your order details below.":
    "Μπορείτε επίσης να ελέγξετε τα στοιχεία της παραγγελίας σας παρακάτω.",
  at: "στο",
  Buy: "Αγορά",
  Donation: "Δωρεά",
  "Enter price": "Επιχείρηση",
  Choose: "Επιλέγω",
  Chosen: "Εκλεκτός",
  "Choose your plan": "Επιλέξτε το σχέδιό σας",
  week: "εβδομάδα",
  wk: "εβδομάδα",
  "Choose plan cycle": "Επιλέξτε κύκλο σχεδίου",
  months: "μήνες",
  years: "έτη",
  weeks: "εβδομάδες",
  "Copy Event Url": "Αντιγραφή URL συμβάντος",
  "You can find your e-tickets attached to your email or print them":
    "Μπορείτε να βρείτε τα e-tickets σας συνδεδεμένα με το email σας ή να τα εκτυπώσετε",
  "Guest Info": "Πληροφορίες επισκεπτών",
  "Ticket Info": "Πληροφορίες εισιτηρίων",
  "Ticket name": "Όνομα εισιτηρίου",
  "Ticket price": "Τιμή εισιτηρίου",
  "Ticket ID": "Αναγνωριστικό εισιτηρίου",
  "If you have any questions contact to organizer":
    "Εάν έχετε οποιεσδήποτε ερωτήσεις επικοινωνήστε με τον διοργανωτή",
  "As soon as event ends": "Μόλις τελειώσει η εκδήλωση",
  "1 day after event ends": "1 ημέρα μετά το τέλος της εκδήλωσης",
  "7 days after event ends": "7 ημέρες μετά το τέλος της εκδήλωσης",
  "14 days after event ends": "14 ημέρες μετά το τέλος της εκδήλωσης",
  "30 days after event ends": "30 ημέρες μετά το τέλος της εκδήλωσης",
  Menu: "Μενού",
  "No event for selected date": "Δεν υπάρχει συμβάν για επιλεγμένη ημερομηνία",
  view: "θέα",
  List: "Λίστα",
  Year: "Ετος",
  Yearly: "Ετήσια",
  "Year view header": "Κεφαλίδα προβολής έτους",
  "Yearly Style": "Ετήσιο στυλ",
  "There are no events": "Δεν υπάρχουν εκδηλώσεις",
  Autotranslation: "Αυτόματη κατάσταση",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Μόλις ενεργοποιηθεί, το widget του ημερολογίου σας θα μεταφραστεί με βάση τη γλώσσα του ιστότοπου.* Σημειώστε ότι όσο ο τίτλος του Ημερολογίου και οι περιγραφές εισάγονται κείμενα που δεν μπορούν να μεταφραστούν.",
  "Note on mobile": "Σημείωση στο κινητό",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Απενεργοποιήστε ή αλλάξτε το κείμενο του μπαρ 'No Events' στην κινητή έκδοση του ημερολογίου",
  Autodeletion: "Αυτοπεποίθηση",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Η ενεργοποίηση της επιλογής, θα καταργήσει αυτόματα τα παρελθόντα σας συμβάντα από το ημερολόγιο.",
  "This does not apply to repeating events!":
    "Αυτό δεν ισχύει για επαναλαμβανόμενα γεγονότα!",
  "Notify event creators about the guest":
    "Ενημερώστε τους χρήστες για τον επισκέπτη",
  "Send event creators notification emails as soon as guests register for their events":
    "Στείλτε μηνύματα ηλεκτρονικού ταχυδρομείου ειδοποίησης δημιουργών συμβάντων μόλις οι επισκέπτες εγγραφούν στις εκδηλώσεις τους",
  "List View Type": "Τύπος προβολής λίστας",
  "Description font": "Γραμματοσειρά περιγραφής",
  Connect: "verbinden",
  "You have no events": "Δεν έχετε εκδηλώσεις",
  Synchronize: "Συγχρονίζω",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Ο συγχρονισμός Ημερολογίου Google σάς επιτρέπει να ενσωματώσετε τις εκδηλώσεις και τις περιόδους σύνδεσης στο Ημερολόγιο Boom.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Το Outlook Calendar Sync σας επιτρέπει να ενσωματώσετε τα συμβάντα και τις συνεδρίες σας με το ημερολόγιο έκρηξης.",
  "Your message has been sent successfully!":
    "Το μήνυμά σας έχει σταλεί με επιτυχία!",
  "There are no synchronized calendars":
    "Δεν υπάρχουν συγχρονισμένα ημερολόγια",
  "to view more than 7 events": "Um mehr als 7 Ereignisse anzuzeigen",
  "Mobile app": "Εφαρμογή για κινητό",
  "Admin Account": "Admin-Konto",
  Password: "Κωδικός πρόσβασης",
  "Second User": "Δεύτερο χρήστη",
  Edit: "Επεξεργασία",
  "Guest limit": "Όριο επισκεπτών",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Όλες οι τοπικές ρυθμίσεις είναι (αυτόματα) με βάση τη γλώσσα σας.Εάν η γλώσσα σας βρίσκεται στη λίστα, δεν χρειάζεται να προσαρμόσετε αυτήν την ενότητα.",
  available: "διαθέσιμος",
  next: "Επόμενο",
  Tickets: "Εισιτήρια",
  Quantity: "Ποσότητα",
  "Promo code": "Κωδικός προώθησης",
  "Select a payment method": "Επιλέξτε μια μέθοδο πληρωμής",
  Fee: "Τέλη",
  Book: "Βιβλίο",
  "All the tickets have been sold out": "Όλα τα εισιτήρια έχουν εξαντληθεί",
  "Choose at least one ticket": "Επιλέξτε τουλάχιστον ένα εισιτήριο",
  "First choose ticket": "Πρώτα επιλέξτε το εισιτήριο",
  "Please fill out your personal information.":
    "Συμπληρώστε τα προσωπικά σας στοιχεία.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "Για να κάνετε μια επιτυχημένη αγορά, επιλέξτε την προτιμώμενη μέθοδο πληρωμής και εισάγετε τον κωδικό προώθησης για προεξοφλημένα εισιτήρια.",
  "Credit/Debit card": "Πιστωτική / Χρεωστική Κάρτα",
  "print here.": "Εκτυπώστε εδώ.",
  "QR code for all tickets": "QR κώδικα για όλα τα εισιτήρια",
  Duration: "Διάρκεια",
  "Full Name": "Πλήρες όνομα",
  "Ticket id": "Αναγνωριστικό εισιτηρίου",
  "Group id": "Ομαδική ταυτότητα",
  "Choose your ticket.": "Επιλέξτε το εισιτήριό σας.",
  "Fill out your personal information.":
    "Συμπληρώστε τα προσωπικά σας στοιχεία.",
  "Add the payment details.": "Προσθέστε τα στοιχεία πληρωμής.",
  "To be determined": "Να καθοριστεί",
  "You can find your e-tickets attached to the email or":
    "Μπορείτε να βρείτε τα ηλεκτρονικά σας εισιτήρια που συνδέονται με το μήνυμα ηλεκτρονικού ταχυδρομείου ή",
  "print here": "Εκτύπωση εδώ",
  "Full name": "Πλήρες όνομα",
  "Group ID": "Ομαδική ταυτότητα",
  "to Book": "να κάνετε κράτηση",
  "Unfortunately, your card has been declined":
    "Δυστυχώς, η κάρτα σας έχει μειωθεί",
  "Thank you for your purchase!": "Σας ευχαριστούμε για την αγορά σας!",
  "Find your printable e-tickets attached to the confirmation email":
    "Βρείτε τα εκτυπώσιμα e-εισιτήρια που συνδέονται με το email επιβεβαίωσης",
  Confirm: "Επιβεβαιώνω",

  "Add event": "Προσθήκη συμβάντος",
  Events: "Εκδηλώσεις",
  "Event details": "Λεπτομέρειες εκδήλωσης",
  Registration: "Εγγραφή",
  "Guests list": "Λίστα επισκεπτών",
  Ticket: "Εισιτήριο",
  "General Info": "Γενικές πληροφορίες",
  "Customize the general settings of your event":
    "Προσαρμόστε τις γενικές ρυθμίσεις της εκδήλωσής σας",
  "Event Title": "Τίτλος εκδήλωσης",
  "e.g. Birthday Party": "π.χ. Πάρτι γενεθλίων",
  "All Day Event": "Ολοήμερη εκδήλωση",
  Cross: "Σταυρός",
  Timeline: "Χρονοδιάγραμμα",
  "Repeating event": "Επανάληψη συμβάν",
  Location: "Τοποθεσία",
  "Venue name": "Όνομα χώρου",
  Description: "Περιγραφή",
  Image: "Εικόνα",
  Color: "Χρώμα",
  Category: "Κατηγορία",
  "Add your events to color categories and let your users classify them easily":
    "Προσθέστε τα συμβάντα σας σε κατηγορίες χρωμάτων και αφήστε τους χρήστες σας να τα ταξινομούν εύκολα",
  "Category name": "Ονομα κατηγορίας",
  "e.g. Birthdays": "π.χ. Γενέθλια",
  Venue: "Τόπος συναντήσεως",
  "Where the event takes place": "Όπου πραγματοποιείται η εκδήλωση",
  "Venue name": "Όνομα χώρου",
  "Venue phone": "Τηλέφωνο χώρου",
  "Venue email": "EMAIL",
  "Venue website": "Ιστοσελίδα τόπου",
  Organizer: "Διοργανωτής",
  "Person who makes the event": "Άτομο που κάνει την εκδήλωση",
  "Organizer name": "Όνομα διοργανωτή",
  "Organizer phone": "Τηλεφώνου διοργανωτή",
  "Organizer email": "Διοργανωτής",
  "Organizer website": "Ιστοσελίδα διοργανωτή",
  Save: "Αποθηκεύσετε",
  Cancel: "Ματαίωση",
  Import: "Εισαγωγή",
  Past: "Το παρελθόν",
  All: "Ολα",
  Upcoming: "Ανερχόμενος",
  Uncategorised: "Μη ταξινομημένος",
  "Date Ascending": "Ημερομηνία ανερχόμενη",
  "Date Descending": "Φθίνουσα ημερομηνία",
  "Title by A-Z": "Τίτλος από A-Z",
  "Title by Z-A": "Τίτλος από το z-a",
  "There are no events for this period":
    "Δεν υπάρχουν γεγονότα για αυτήν την περίοδο",

  "Auto-Convert Date & Time": "Ημερομηνία και ώρα αυτόματης μετατροπής",
  TimeZone: "Ζώνη ώρας",
  Autodeletion: "Αυτοπεποίθηση",
  "Layout Settings": "Ρυθμίσεις διάταξης",
  "Yeatly view": "Προβολή Yeatly",
  "Monthly view header": "Μηνιαία επικεφαλίδα προβολής",
  "Weekly/Daily view header": "Εβδομαδιαία/Ημερήσια Προβολή κεφαλίδας",
  Acendings: "Εκτοξεύσεις",
  Descending: "Φθίνων",
  Standart: "Διαμέρισμα",
  Silver: "Ασήμι",
  Retro: "Ρετρό",
  Dark: "Σκοτάδι",
  Night: "Νύχτα",
  Aubergine: "Μελιτζάνα",
  "List view header": "Κεφαλίδα προβολής λίστας",
  "Side by Side View": "Πλευρά -δίπλα προβολή",
  "Customize Proportions": "Προσαρμόστε τις αναλογίες",
  "Card Margins": "Περιθώρια καρτών",
  "Image opacity (%)": "Αδιαφάνεια εικόνας (%)",
  "Side by Side Header": "Δίπλα στην κεφαλίδα",
  "Text Align": "Στοίχιση κειμένου",
  "Timeline View": "Προβολή χρονοδιακόπτη",
  "Title font color": "Χρώμα γραμματοσειράς τίτλου",
  "Desciption font color": "Χρώμα γραμματοσειράς αποβάθρας",
  "Line color": "Έγχρωμη γραμμή",
  "Date Font color": "Χρώμα γραμματοσειράς ημερομηνίας",
  "Daily events background": "Ημερήσιες εκδηλώσεις φόντο",
  Alignment: "Ευθυγραμμία",
  Vertical: "Κατακόρυφος",
  Horizontal: "Οριζόντιος",
  "Vertical Alignment": "Κατακόρυφη στοίχιση",
  Right: "σωστά",
  Center: "Κέντρο",
  "Horizontal Alignment": "Οριζόντια ευθυγράμμιση",
  Top: "Μπλουζα",
  Center: "Κέντρο",
  Bottom: "Κάτω μέρος",
  "Dates Circle Design": "Dates Circle Design",
  "Next To The Circle": "Δίπλα στον κύκλο",
  "In The Circle": "Στον κύκλο",
  "Timeline Header": "Κεφαλίδα χρονοδιαγράμματος",
  Timeline: "Χρονοδιάγραμμα",
  "Show only upcoming": "Εμφάνιση μόνο επερχόμενου",
  "Order by": "Ταξινόμηση κατά",
  "Timeline Event Limit": "Όριο συμβάντος χρονοδιαγράμματος",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Επιτρέψτε στον επισκέπτη να προσθέσει συμβάν σε τοπικές ημερολογιακές: Google, Yahoo, Outlook, Icalendar.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Επιτρέψτε στον επισκέπτη να μοιραστεί την εκδήλωσή σας σε Facebook, LinkedIn, Twitter κ.λπ.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Προσθέστε μια επιλογή αναζήτησης στο ημερολόγιό σας για να αφήσετε τους ανθρώπους να αναζητήσουν τις εκδηλώσεις σας με τίτλο, χώρο, κ.λπ.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Επιτρέψτε στους χρήστες σας να εκτυπώσουν το ημερολόγιο συμβάντων έκρηξης σε οποιοδήποτε εύρος ημερομηνιών.",
  "Click to apply a theme to Calendar":
    "Κάντε κλικ για να εφαρμόσετε ένα θέμα στο ημερολόγιο",
  "Date container color": "Χρώμα δοχείου ημερομηνίας",
  "Daily events background": "Ημερήσιες εκδηλώσεις φόντο",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Χρησιμοποιήστε τα πρόσθετα για να εγκαταστήσετε προηγμένες λειτουργίες στα ημερολόγιά σας, καθιστώντας τα πιο λειτουργικά!",
  "Open Add-ons Store": "Ανοίξτε το κατάστημα πρόσθετων",
  Monday: "Δευτέρα",
  Tuesday: "Τρίτη",
  Wednesday: "Τετάρτη",
  Thursday: "Πέμπτη",
  Friday: "Παρασκευή",
  Saturday: "Σάββατο",
  Sunday: "Κυριακή",
  "Yearly view": "Ετήσια άποψη",
  Ascending: "Ανερχόμενος",
  "Show event time next to title": "Εμφάνιση χρόνου εκδήλωσης δίπλα στον τίτλο",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Ρυθμίστε την ημερομηνία και την ώρα του συμβάντος στην τοπική ώρα του χρήστη με βάση τη ζώνη ώρας τους.",
  "Display the time zone alongside the event date.":
    "Εμφανίστε τη ζώνη ώρας παράλληλα με την ημερομηνία της εκδήλωσης.",
  "Show event time next to title": "Εμφάνιση χρόνου εκδήλωσης δίπλα στον τίτλο",
  "Time Zone": "Ζώνη ώρας",
  "Upload Image": "Μεταφορτώστε την εικόνα",
  "Choose a Category": "Επιλέξτε μια κατηγορία",
  "Color you have chosen will not be shown as you choose category":
    "Το χρώμα που έχετε επιλέξει δεν θα εμφανιστεί καθώς επιλέγετε κατηγορία",
  Website: "Δικτυακός τόπος",
  Next: "Επόμενο",
  Save: "Αποθηκεύσετε",
  "Last Name": "Επίθετο",
  "Personal Info": "Προσωπικές πληροφορίες",
  Back: "Πίσω",
  "This field is required": "Αυτό το πεδίο απαιτείται",
  "Your event has been submitted": "Η εκδήλωσή σας έχει υποβληθεί",
  "Enter a location": "Εισαγάγετε μια τοποθεσία",
  "Display the time zone alongside the event date.":
    "Εμφανίστε τη ζώνη ώρας παράλληλα με την ημερομηνία της εκδήλωσης.",
  Home: "Σπίτι",
  "Side By Side Event Limit": "Όριο συμβάντος δίπλα στο πλάι",
  "Mobille App": "Εφαρμογή Mobille",
  category: "κατηγορία",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Παρακολουθήστε εύκολα το πρόγραμμά σας εισάγοντας τα συμβάντα σας στο Facebook στο ημερολόγιό σας.",
  "Synchronized Pages": "Συγχρονισμένες σελίδες",
  "There are no synchronized pages": "Δεν υπάρχουν συγχρονισμένες σελίδες",
  "Choose page": "Επιλέξτε σελίδα",
  "You have no events": "Δεν έχετε γεγονότα",
};
export default el;
