let en = {
  Language: "Language",
  "Show Time Zone": "Show Time Zone",
  "Custom Local Settings": "Custom Local Settings",
  "Add and showcase events on your site using a beautiful calendar.":
    "Add and showcase events on your site using a beautiful calendar.",
  "Week Days": "Week Days",
  "Manage Events": "Manage Events",
  General: "General",
  "Layout Picker": "Layout Picker",
  Month: "Month",
  Monthly: "Monthly",
  Week: "Week",
  Weekly: "Weekly",
  Day: "Day",
  Daily: "Daily",
  Agenda: "Agenda",
  "Navigation Buttons": "Navigation Buttons",
  "Week numbers": "Week numbers",
  "Include Weekends": "Include Weekends",
  "All-day": "All-day",
  "All Day": "All day",
  Label: "Label",
  "Fit to Height": "Fit to Height",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "To set App proportions manually disable this option and resize Calendar in Editor.",
  "Default Layout": "Default Layout",
  "Monthly view": "Monthly view",
  "Weekly and Daily view": "Weekly and Daily view",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.",
  "Fixed Weekly Layout": "Fixed Weekly Layout",
  back: "back",
  Row: "Row",
  "Hours in Weekly View": "Hours in Weekly View",
  "Hours in Daily View": "Hours in Daily View",
  Start: "Start",
  End: "End",
  "At This Hour": "At This Hour",
  "Add to": "Add to",
  Button: "Button",
  Buttons: "Buttons",
  Sunday: "Sunday",
  Monday: "Monday",
  Tuesday: "Tuesday",
  Wednesday: "Wednesday",
  Thursday: "Thursday",
  Friday: "Friday",
  Saturday: "Saturday",
  "Default Date": "Default Date",
  year: "year",
  month: "month",
  mo: "month",
  days: "days",
  ago: "ago",
  ahead: "ahead",
  Yesterday: "Yesterday",
  Today: "Today",
  Tomorrow: "Tomorrow",
  Custom: "Custom",
  "Set Daily Rows Limit": "Set Daily Rows Limit",
  "Set Proportions": "Set Proportions",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Allow visitor to add event to local Calendars: Google, Yahoo, Outlook, ICalendar.",
  Container: "Container",
  Background: "Background",
  "Container Background": "Container Background",
  "Container Borders": "Container Borders",
  Calendar: "Calendar",
  "Event Info Tooltip": "Event Info Tooltip/Popup",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "When people hover over an event they’ll see all the info about it in a tooltip.",
  "Event Info Window": "Event Info Window",
  "This is the full information window that opens when someone clicks on the event.":
    "This is the full information window that opens when someone clicks on the event.",
  "Use Gradient": "Use Gradient",
  Vertical: "Vertical",
  Horizontal: "Horizontal",
  First: "First",
  Second: "Second",
  diagonal: "diagonal",
  Radial: "Radial",
  "Select option": "Select option",
  Solid: "Solid",
  Dotted: "Dotted",
  Dashed: "Dashed",
  Double: "Double",
  "Border Radius": "Border Radius",
  Padding: "Padding",
  "Date Header": "Date Header",
  "Event Default Color": "Event Default Color",
  "Days of Week": "Days of Week",
  "Days of Week Background": "Days of Week Background",
  Date: "Date",
  "Event Title": "Event Title",
  "Highlight today": "Highlight today",
  "Highlight Color": "Highlight Color",
  Hide: "Hide",
  "Calendar Border Color": "Calendar Border Color",
  "Calendar Border Width": "Calendar Border Width",
  "Calendar Border Style": "Calendar Border Style",
  "Section Titles": "Section Titles",
  "Section Content": "Section Content",
  "Event Background": "Event Background",
  "Card Date Color": "Card Date Color",
  "Title Font": "Title Font",
  "Date Font": "Date Font",
  "Description Font": "Description Font",
  "Button Background": "Button Background",
  "Button Text": "Button Text",
  "Border Color": "Border Color",
  "Border Width": "Border Width",
  "Border Type": "Border Type",
  Title: "Title",
  Description: "Description",
  "Background Color": "Background Color",
  Divider: "Divider",
  "Event Details Font": "Event Details Font",
  "Website Link Color": "Link Color",
  "Developer Info": "Developer Info",
  "User Guide": "Guides & Chat",
  "Support e-mail": "Support e-mail",
  "Our Website": "Our Website",
  "App Review": "App Review",
  "Enjoying App? Leave us a review in the App Market.":
    "Enjoying App? Leave us a review in the App Market.",
  "Review Us": "Review Us",
  "Connect With Us": "Connect With Us",
  "What's your email?": "What's your email?",
  "Invalid email address!": "Invalid email address!",
  Comments: "Comments",
  "We'd love to hear from you. Send us a message.":
    "We'd love to hear from you. Send us a message.",
  "Message must be at least 5 characters long":
    "Message must be at least 5 characters long",
  Send: "Send",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.",
  Main: "Main",
  Localize: "Localize",
  Settings: "Settings",
  Layouts: "Layouts",
  Advanced: "Advanced",
  Design: "Design",
  Support: "Support",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.",
  "Date Format": "Date Format",
  "Time Format": "Time Format",
  "Text Direction": "Text Direction",
  "Left to Right": "Left to Right",
  "Right to Left": "Right to Left",
  "Week Starts On": "Week Starts On",
  "Agenda Style": "Agenda Style",
  Classic: "Classic",
  Modern: "Modern",
  "Agenda Header": "Agenda Header",
  "Upcoming Events": "Upcoming Events",
  "Agenda Event Limit": "Agenda Event Limit",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Upgrade now and get a lot more features and enjoy your APP in full!",
  "Upgrade Now": "Upgrade Now",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Hosting events that last all day? This lets you show them on your calendar.",
  "24 hours": "24 hours",
  Sun: "Sun",
  Mon: "Mon",
  Sat: "Sat",
  Default: "Default",
  Style: "Style",
  "Calendar Name": "Calendar Name",
  "Write your Calendar name here": "Write your Calendar name here",
  "Enable Search": "Enable Search",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.",
  "+ Add Event": "+ Add Event",
  "Manage and Sync": "Manage and Sync",
  "Show event details as...": "Show event details as...",
  Tooltip: "Tooltip",
  Popup: "Popup",
  None: "None",
  "Show Category": "Show Category",
  "Header Align": "Header Align",
  "Show Time": "Show Time",
  "Hours in Weekly/Daily View": "Hours in Weekly/Daily View",
  "Share Events": "Share Events",
  Shadow: "Shadow",
  "Inner Padding": "Inner Padding",
  Text: "Text",
  "Active Button Border": "Active Button Border",
  "Light Mode": "Light Mode",
  "Event Text Color": "Event Text Color",
  Dates: "Dates",
  Skeleton: "Skeleton",
  "Skeleton Color": "Skeleton Color",
  Width: "Width",
  "Skeleton Style": "Skeleton Style",
  Color: "Color",
  Header: "Header",
  Map: "Map",
  Standard: "Standard",
  Retro: "Retro",
  Silver: "Silver",
  Night: "Night",
  Dark: "Dark",
  Aubergine: "Aubergine",
  "Map Header": "Map Header",
  "Show Title in mobile": "Show Title in mobile",
  Card: "Card",
  "Card View": "Card View",
  "Card background color": "Card background color",
  "Title font": "Title font",
  "Desciption font": "Description font",
  "Section font": "Font section",
  "Section divider color": "Section divider color",
  "Font Color": "Font Color",
  "General Info": "General Info",
  Venue: "Venue",
  Organizer: "Organizer",
  Search: "Search",
  calendar: "calendar",
  "Share this event": "Share this event",
  "Copy event URL": "Copy event URL",
  "Copied!": "Copied!",
  "Add & Share": "Add & Share",
  "Calendar view": "Calendar view",
  "Add Event": "Add Event",
  Uncategorised: "Uncategorised",
  Categories: "Categories",
  More: "More",
  Less: "Less",
  Register: "Register",
  Guests: "Guests",
  unlimited: "unlimited",
  "Show more": "Show more",
  "Add event": "Add event",
  "All Day Event": "All Day Event",
  Location: "Location",
  "Choose a category": "Choose a category",
  "Venue name": "Venue name",
  "Venue phone": "Venue phone",
  "Venue email": "Venue email",
  "Venue website": "Venue website",
  "Organizer name": "Organizer name",
  "Organizer phone": "Organizer phone",
  "Organizer email": "Organizer email",
  "Organizer website": "Organizer website",
  "Personal info": "Personal info",
  "First name": "First name",
  "Last name": "Last name",
  "Email Address": "Email Address",
  "Additional Notes": "Additional Notes",
  Back: "Back",
  Save: "Save",
  Next: "Next",
  "Your event has been submitted": "Your event has been submitted",
  "Event submittion has been failed": "Event submittion has been failed",
  "e.g. Birthday Party": "e.g. Birthday Party",
  "First Name": "First Name",
  "Last Name": "Last Name",
  "Phone Number": "Phone Number",
  Address: "Address",
  "Your comments": "Your comments",
  "How many guests?": "How many guests?",
  "Anything else we need to know?": "Anything else we need to know?",
  "Guests:": "Guests:",
  Submit: "Submit",
  "Go to Calendar": "Go to Calendar",
  "Registration completed successfully!":
    "Registration completed successfully!",
  "Please check your registered email address":
    "Please check your registered email address",
  "Add to Calendar": "Add to Calendar",
  "Share this Event": "Share this Event",
  "Sorry something went wrong": "Sorry something went wrong",
  "Back to registration": "Back to registration",
  "Date & Location": "Date & Location",
  "Date & Time": "Date & Time",
  home: "home",
  "Header align": "Header align",
  Footer: "Footer",
  "Categories Filter": "Categories Filter",
  "Show only upcoming": "Show only upcoming",
  "Card(s) in a row": "Card(s) in a row",
  "Space between cards": "Space between cards",
  "Shown events limit": "Shown events limit",
  "Style 1": "Style 1",
  "Style 2": "Style 2",
  "Style 3": "Style 3",
  "Style 4": "Style 4",
  "Buttons & Links": "Buttons & Links",
  "Button corner radius": "Button corner radius",
  "Buttons font": "Buttons font",
  "Buttons background": "Buttons background",
  "Get notified by Email": "Get notified by Email",
  "Review events": "Review events",
  "Click on date": "Click on date",
  "Add Event button": "Add Event button",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.",
  connect: "connect",
  "Synchronized Calendars": "Synchronized Calendars",
  "Import events": "Import events",
  Disconnect: "Disconnect",
  "Choose calendar": "Choose calendar",
  "Monitor your Wix events through the sync feature":
    "Monitor your Wix events through the sync feature",
  "Connect all your Boom calendars available on your website":
    "Connect all your Boom calendars available on your website",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Schedule, join, and manage Zoom meetings right through our Boom Calendar.",
  "Monitor your Event Brite events through the Event Brite sync feature.":
    "Monitor your Event Brite events through the Event Brite sync feature.",
  Email: "Email",
  "Add-ons": "Add-ons",
  "Switch Add Event": "Switch Add Event",
  "Enable your browser cookies to connect to your account.":
    "Enable your browser cookies to connect to your account.",
  "Learn more": "Learn more",
  "Print Button": "Print Button",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Permit your users to print your Boom Event Calendar in any date range.",
  "Show Title on mobile": "Show Title on mobile",
  "Show Skeleton on mobile": "Show Skeleton on mobile",
  "Start 7-day Business trial": "Start 7-day Business trial",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Enjoy all the Unlimited features, such as Sell tickets, Registration, Visitor event add-ons.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Please note: At the end of the trial period, you will be returned to your existing subscription plan.",
  "Not Now": "Not Now",
  "Start free trial": "Free trial",
  "Congrats!": "Congrats!",
  "Your 7-day Business trial has been successfully activated.":
    "Your 7-day Business trial has been successfully activated.",
  Done: "Done",
  "Title font color": "Title font color",
  "Desciption font color": "Description font color",
  "Section font color": "Section font color",
  "Card Header": "Card Header",
  Category: "Category",
  "Display at the": "Display at the",
  top: "top",
  bottom: "bottom",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only",
  "Processing your events": "Processing your events",
  "Search for events": "Search for events",
  "There are no events added": "There are no events added",
  "Location: To be determined": "Location: To be determined",
  "No events for selected date": "No events for selected date",
  Uncategorized: "Uncategorized",
  "Edit event": "Edit event",
  "Edit original event": "Edit original event",
  "Copy event": "Copy event",
  "Copy as new event": "Copy as new event",
  "Delete event": "Delete event",
  "Stop repeating on this date": "Stop repeating on this date",
  "Exclude this date": "Exclude this date",
  "Location is going to be announced": "Location is going to be announced",
  "Fill your personal information": "Fill your personal information",
  "Check Box": "Check Box",
  "Single Choice": "Single Choice",
  Option: "Option",
  "Share Event": "Share Event",
  "Oops! Something went wrong": "Oops! Something went wrong",
  "We are sorry this event has already taken place":
    "We are sorry this event has already taken place",
  "Back to calendar": "Back to calendar",
  "This field is required": "This field is required",
  Phone: "Phone",
  "Number field": "Number field",
  "Please provide a valid email": "Please provide a valid email",
  "Select at least one option": "Select at least one option",
  "Choose tickets to see total value": "Choose tickets to see total value",
  tickets: "tickets",
  "Choose Tickets": "Choose Tickets",
  "Choose payment method": "Choose payment method",
  Pay: "Pay",
  Total: "Total",
  Free: "Free",
  "Buy tickets": "Buy tickets",
  "Sold Out": "Sold Out",
  "Tickets are available": "Tickets are available",
  "Sales End": "Sales End",
  "Availible from": "Available from",
  "Go to Orders": "Go to Orders",
  "Go to Details": "Go to Details",
  "Group ticket": "Group ticket",
  Name: "Name",
  Price: "Price",
  "Order by": "Order by",
  "Order ID": "Order ID",
  Applied: "Applied",
  Fees: "Fees",
  "Enter promo code": "Enter promo code",
  Apply: "Apply",
  "Promo Code": "Promo Code",
  Cash: "Cash",
  "You can find your e-tickets attached to your email or download them":
    "You can find your e-tickets attached to your email or download them",
  here: "here",
  Time: "Time",
  "Invalid promo code": "Invalid promo code",
  "Credit card": "Credit card",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "You will soon receive a confirmation message of successful registration to your email address.",
  "You can also check your order details below.":
    "You can also check your order details below.",
  at: "at",
  Buy: "Buy",
  Donation: "Donation",
  "Enter price": "Enter price",
  Choose: "Choose",
  Chosen: "Chosen",
  "Choose your plan": "Choose your plan",
  week: "week",
  wk: "week",
  "Choose plan cycle": "Choose plan cycle",
  months: "months",
  years: "years",
  weeks: "weeks",
  "Copy Event Url": "Copy Event Url",
  "You can find your e-tickets attached to your email or print them":
    "You can find your e-tickets attached to your email or print them",
  "Guest Info": "Guest Info",
  "Ticket Info": "Ticket Info",
  "Ticket name": "Ticket name",
  "Ticket price": "Ticket price",
  "Ticket ID": "Ticket ID",
  "If you have any questions contact to organizer":
    "If you have any questions contact to organizer",
  "As soon as event ends": "As soon as event ends",
  "1 day after event ends": "1 day after event ends",
  "7 days after event ends": "7 days after event ends",
  "14 days after event ends": "14 days after event ends",
  "30 days after event ends": "30 days after event ends",
  Menu: "Menu",
  "No event for selected date": "No event for selected date",
  view: "view",
  List: "List",
  Year: "Year",
  Yearly: "Yearly",
  "Year view header": "Year view header",
  "Yearly Style": "Yearly Style",
  "There are no events": "There are no events",
  Autotranslation: "Autotranslation",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.",
  "Note on mobile": "Note on mobile",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Turn off or change the text of the “No events” bar on mobile version of calendar",
  Autodeletion: "Autodeletion",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Enabling the option, will automatically remove your past events from the calendar.",
  "This does not apply to repeating events!":
    "This does not apply to repeating events!",
  "Notify event creators about the guest":
    "Notify event creators about the guest",
  "Send event creators notification emails as soon as guests register for their events":
    "Send event creators notification emails as soon as guests register for their events",
  "List View Type": "List View Type",
  "Description font": "Description font",
  Connect: "Connect",
  "You have no events": "You have no events",
  Synchronize: "Synchronize",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.",
  "Your message has been sent successfully!":
    "Your message has been sent successfully!",
  "There are no synchronized calendars": "There are no synchronized calendars",
  "to view more than 7 events": "to view more than 7 events",
  "Mobile app": "Mobile app",
  "Admin Account": "Admin Account",
  Password: "Password",
  "Second User": "Second User",
  Edit: "Edit",
  "Guest limit": "Guest limit",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.",
  available: "available",
  next: "next",
  Tickets: "Tickets",
  Quantity: "Quantity",
  "Promo code": "Promo code",
  "Select a payment method": "Select a payment method",
  Fee: "Fee",
  Book: "Book",
  "All the tickets have been sold out": "All the tickets have been sold out",
  "Choose at least one ticket": "Choose at least one ticket",
  "First choose ticket": "First choose ticket",
  "Please fill out your personal information.":
    "Please fill out your personal information.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.",
  "Credit/Debit card": "Credit/Debit card",
  "print here.": "print here.",
  "QR code for all tickets": "QR code for all tickets",
  Duration: "Duration",
  "Full Name": "Full Name",
  "Ticket id": "Ticket id",
  "Group id": "Group id",
  "Choose your ticket.": "Choose your ticket.",
  "Fill out your personal information.": "Fill out your personal information.",
  "Add the payment details.": "Add the payment details.",
  "To be determined": "To be determined",
  "You can find your e-tickets attached to the email or":
    "You can find your e-tickets attached to the email or",
  "print here": "print here",
  "Full name": "Full name",
  "Group ID": "Group ID",
  "to Book": "Book",
  "Unfortunately, your card has been declined":
    "Unfortunately, your card has been declined",
  "Thank you for your purchase!": "Thank you for your purchase!",
  "Find your printable e-tickets attached to the confirmation email":
    "Find your printable e-tickets attached to the confirmation email",
  Confirm: "Confirm",

  "Add event": "Add event",
  Events: "Events",
  "Event details": "Event details",
  Registration: "Registration",
  "Guests list": "Guests list",
  Ticket: "Ticket",
  "General Info": "General Info",
  "Customize the general settings of your event":
    "Customize the general settings of your event",
  "Event Title": "Event Title",
  "e.g. Birthday Party": "e.g. Birthday Party",
  "All Day Event": "All Day Event",
  Cross: "Cross",
  Timeline: "Timeline",
  "Repeating event": "Repeating event",
  Location: "Location",
  "Venue name": "Venue name",
  Description: "Description",
  Image: "Image",
  Color: "Color",
  Category: "Category",
  "Add your events to color categories and let your users classify them easily":
    "Add your events to color categories and let your users classify them easily",
  "Category name": "Category name",
  "e.g. Birthdays": "e.g. Birthdays",
  Venue: "Venue",
  "Where the event takes place": "Where the event takes place",
  "Venue name": "Venue name",
  "Venue phone": "Venue phone",
  "Venue email": "Venue email",
  "Venue website": "Venue website",
  Organizer: "Organizer",
  "Person who makes the event": "Person who makes the event",
  "Organizer name": "Organizer name",
  "Organizer phone": "Organizer phone",
  "Organizer email": "Organizer email",
  "Organizer website": "Organizer website",
  Save: "Save",
  Cancel: "Cancel",
  Import: "Import",
  Past: "Past",
  All: "All",
  Upcoming: "Upcoming",
  Uncategorised: "Uncategorised",
  "Date Ascending": "Date Ascending",
  "Date Descending": "Date Descending",
  "Title by A-Z": "Title by A-Z",
  "Title by Z-A": "Title by Z-A",
  "There are no events for this period": "There are no events for this period",

  "Auto-Convert Date & Time": "Auto-Convert Date & Time",
  TimeZone: "TimeZone",
  Autodeletion: "Autodeletion",
  "Layout Settings": "Layout Settings",
  "Yeatly view": "Yeatly view",
  "Monthly view header": "Monthly view header",
  "Weekly/Daily view header": "Weekly/Daily view header",
  Acendings: "Acendings",
  Descending: "Descending",
  Standart: "Standart",
  Silver: "Silver",
  Retro: "Retro",
  Dark: "Dark",
  Night: "Night",
  Aubergine: "Aubergine",
  "List view header": "List view header",
  "Side by Side View": "Side by Side View",
  "Customize Proportions": "Customize Proportions",
  "Card Margins": "Card Margins",
  "Image opacity (%)": "Image opacity (%)",
  "Side by Side Header": "Side by Side Header",
  "Text Align": "Text Align",
  "Timeline View": "Timeline View",
  "Title font color": "Title font color",
  "Desciption font color": "Desciption font color",
  "Line color": "Line color",
  "Date Font color": "Date Font color",
  "Daily events background": "Daily events background",
  Alignment: "Alignment",
  Vertical: "Vertical",
  Horizontal: "Horizontal",
  "Vertical Alignment": "Vertical Alignment",
  Right: "Right",
  Center: "Center",
  "Horizontal Alignment": "Horizontal Alignment",
  Top: "Top",
  Center: "Center",
  Bottom: "Bottom",
  "Dates Circle Design": "Dates Circle Design",
  "Next To The Circle": "Next To The Circle",
  "In The Circle": "In The Circle",
  "Timeline Header": "Timeline Header",
  Timeline: "Timeline",
  "Show only upcoming": "Show only upcoming",
  "Order by": "Order by",
  "Timeline Event Limit": "Timeline Event Limit",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Add a search option on your calendar to let people search your events by title, venue, etc.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Permit your users to print your Boom Event Calendar in any date range.",
  "Click to apply a theme to Calendar": "Click to apply a theme to Calendar",
  "Date container color": "Date container color",
  "Daily events background": "Daily events background",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Use the Add-ons to install advanced features on your calendars, making them more functional!",
  "Open Add-ons Store": "Open Add-ons Store",
  Monday: "Monday",
  Tuesday: "Tuesday",
  Wednesday: "Wednesday",
  Thursday: "Thursday",
  Friday: "Friday",
  Saturday: "Saturday",
  Sunday: "Sunday",
  "Yearly view": "Yearly view",
  Ascending: "Ascending",
  "Show event time next to title": "Show event time next to title",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Adjust the event date and time to the user's local time based on their time zone.",
  "Display the time zone alongside the event date.":
    "Display the time zone alongside the event date.",
  "Show event time next to title": "Show event time next to title",
  "Time Zone": "Time Zone",
  "Upload Image": "Upload Image",
  "Choose a Category": "Choose a Category",
  "Color you have chosen will not be shown as you choose category":
    "Color you have chosen will not be shown as you choose category",
  Website: "Website",
  Next: "Next",
  Save: "Save",
  "Last Name": "Last Name",
  "Personal Info": "Personal Info",
  Back: "Back ",
  "This field is required": "This field is required",
  "Your event has been submitted": "Your event has been submitted",
  "Enter a location": "Enter a location",
  "Display the time zone alongside the event date.":
    "Display the time zone alongside the event date.",
  Home: "Home",
  "Side By Side Event Limit": "Side By Side Event Limit",
  "Mobille App": "Mobille App",
  category: "category",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Keep track of your schedule easily by importing your Facebook events to your calendar.",
  "Synchronized Pages": "Synchronized Pages",
  "There are no synchronized pages": "There are no synchronized pages",
  "Choose page": "Choose page",
  "You have no events": "You have no events",
};
export default en;
