let es = {
  Categories: "Categorías",
  "Share this event": "Comparte este evento",
  Language: "Idioma",
  "Show Time Zone": "Mostrar zona horaria",
  "Custom Local Settings": "Configuración local personalizada",
  "Add and showcase events on your site using a beautiful calendar.":
    "Agregue y muestre eventos en su sitio usando un calendario hermoso",
  "Week Days": "Días de la semana",
  "Manage Events": "Administrar eventos",
  General: "General",
  "Layout Picker": "Selector de diseño",
  Month: "Mes",
  Monthly: "Mensual",
  Week: "Semana",
  Weekly: "Semanal",
  Day: "Día",
  Daily: "Diario",
  Agenda: "Agenda",
  "Navigation Buttons": "Botones de navegacion",
  "Week numbers": "Números semanales",
  "Include Weekends": "Incluir fines de semana",
  "All-day": "Todo el dia",
  "All Day": "Todo el dia",
  Label: "Etiqueta",
  "Fit to Height": "Ajustar a la altura",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Para establecer proporciones de aplicaciones, desactive esta opción y cambie el tamaño del Calendario en el Editor",
  "Default Layout": "Diseño predeterminado",
  "Monthly view": "Vista mensual",
  "Weekly and Daily view": "Vista semanal y diaria",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Puede brindar a los visitantes una experiencia más consistente mostrando la misma cantidad de semanas (6) a la vez",
  "Fixed Weekly Layout": "Diseño semanal fijo",
  back: "espalda",
  Row: "Fila",
  "Hours in Weekly View": "Horas en vista semanal",
  "Hours in Daily View": "Horas en la vista diaria",
  Start: "Comienzo",
  End: "Fin",
  "At This Hour": "A esta hora",
  "Add to": "añadir",
  Button: "Botón",
  Buttons: "Botones",
  Sunday: "Domingo",
  Monday: "Lunes",
  Tuesday: "Martes",
  Wednesday: "Miércoles",
  Thursday: "Jueves",
  Friday: "Viernes",
  Saturday: "Sábado",
  "Default Date": "Fecha predeterminada",
  year: "año",
  month: "mes",
  mo: "mes",
  days: "dias",
  ago: "hace",
  ahead: "adelante",
  Yesterday: "Ayer",
  Today: "Hoy",
  Tomorrow: "Mañana",
  Custom: "Personalizado",
  "Set Daily Rows Limit": "Establecer límite diario de filas",
  "Set Proportions": "Establecer proporciones",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Permitir al visitante agregar un evento a los Calnedars locales, Google, Yahoo, Outlook, ICalendar",
  Container: "Envase",
  Background: "Fondo",
  "Container Background": "Fondo del contenedor",
  "Container Borders": "Fronteras de contenedores",
  Calendar: "Calendario",
  "Event Info Tooltip":
    "Información sobre herramientas de información del evento",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Cuando las personas se ciernen sobre un evento, verán toda la información al respecto en una descripción emergente",
  "Event Info Window": "Ventana de información del evento",
  "This is the full information window that opens when someone clicks on the event.":
    "Esta es la ventana de información completa que se abre cuando alguien hace clic en el evento",
  "Use Gradient": "Usar degradado",
  Vertical: "Vertical",
  Horizontal: "Horizontal",
  First: "Primero",
  Second: "Segundo",
  diagonal: "diagonal",
  Radial: "Radial",
  "Select option": "Seleccionar opción",
  Solid: "Sólido",
  Dotted: "Punteado",
  Dashed: "Rayado",
  Double: "Doble",
  "Border Radius": "Radio de borde",
  Padding: "Relleno",
  "Date Header": "Encabezado de fecha",
  "Event Default Color": "Color predeterminado del evento",
  "Days of Week": "Días de la semana",
  "Days of Week Background": "Fondo de días de la semana",
  Date: "Fecha",
  "Event Title": "Título del evento",
  "Highlight today": "Destacar hoy",
  "Highlight Color": "Color de resaltado",
  Hide: "Esconder",
  "Calendar Border Color": "Color del borde del calendario",
  "Calendar Border Width": "Ancho del borde del calendario",
  "Calendar Border Style": "Estilo de borde de calendario",
  "Font Color": "Color de fuente",
  "Event Background": "Antecedentes del evento",
  "Card Date Color": "Color de la fecha de la tarjeta",
  "Title Font": "Fuente del titulo",
  "Date Font": "Fuente de fecha",
  "Description Font": "Fuente de descripción",
  "Button Background": "Fondo del botón",
  "Button Text": "Botón de texto",
  "Border Color": "Color del borde",
  "Border Width": "Ancho del borde",
  "Border Type": "Tipo de borde",
  Title: "Título",
  Description: "Descripción",
  "Background Color": "Color de fondo",
  Divider: "Divisor",
  "Event Details Font": "Fuente de detalles del evento",
  "Website Link Color": "Color del enlace del sitio web",
  "Developer Info": "Información del desarrollador",
  "User Guide": "Guía del usuario",
  "Support e-mail": "Correo electrónico de soporte",
  "Our Website": "Nuestra página web",
  "App Review": "Revisión de la aplicación",
  "Enjoying App? Leave us a review in the App Market.":
    "¿Disfrutando de la aplicación? Déjanos un comentario en el App Market",
  "Review Us": "Revisarnos",
  "Connect With Us": "Conectate con nosotros",
  "What's your email?": "¿Cuál es tu correo electrónico?",
  "Invalid email address!": "¡Dirección de correo electrónico no válida!",
  Comments: "Comentarios",
  "We'd love to hear from you. Send us a message.":
    "Nos encantaría saber de usted. Envíenos un mensaje",
  "Message must be at least 5 characters long":
    "El mensaje debe tener al menos 5 caracteres",
  Send: "Enviar",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Si desea permitir que el usuario cambie entre vistas de calendario, habilite esta opción y elija las vistas que desea mostrar",
  Main: "Principal",
  Localize: "Localizar",
  Settings: "Configuraciones",
  Layouts: "Diseños",
  Advanced: "Avanzado",
  Design: "Diseño",
  Support: "Apoyo",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Todas las configuraciones locales se basan (automáticamente) en su idioma. Si su idioma está en la lista, no es necesario personalizar esta sección.",
  "Date Format": "Formato de fecha",
  "Time Format": "Formato de tiempo",
  "Text Direction": "Dirección del texto",
  "Left to Right": "De izquierda a derecha",
  "Right to Left": "De derecha a izquierda",
  "Week Starts On": "La semana empieza el",
  "Agenda Style": "Estilo de agenda",
  Classic: "Classic",
  Modern: "Modern",
  "Agenda Header": "Encabezado de agenda",
  "Upcoming Events": "Próximos Eventos",
  "Agenda Event Limit": "Agenda Eventos Límite",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "¡Actualiza ahora y obtén muchas más funciones y disfruta de tu APLICACIÓN por completo!",
  "Upgrade Now": "Actualizar ahora",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "¿Organizar eventos que duran todo el día? Esto te permite mostrarlos en tu calendario",
  "24 hours": "24 horas",
  Sat: "Sáb",
  Sun: "Dom",
  Mon: "Lun",
  Default: "Defecto",
  "Select custom design style for your calendar.":
    "Seleccione un estilo de diseño personalizado para su calendario.",
  Style: "Estilo",
  "Styles and Colors": "Estilos y colores",
  "Calendar Name": "Nombre del calendario",
  "Write your Calendar name here": "Escriba su nombre de calendario aquí",
  "Enable Search": "Habilitar búsqueda",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Esto no es visible para sus usuarios. Establezca nombres para diferenciar sus calendarios cuando use la función Boom Calendar Sync.",
  "+ Add Event": "+ Agregar evento",
  "Manage and Sync": "Administrar y sincronizar",
  "Show event details as...": "Mostrar detalles del evento como ...",
  Tooltip: "Información sobre herramientasCaja de información",
  Popup: "Caja de información",
  None: "Ninguna",
  "Show Category": "Mostrar categoría",
  "Header Align": "Encabezado Alinear",
  "Show Time": "Tiempo de la funcion",
  "Hours in Weekly/Daily View": "Horas en vista semanal / diaria",
  "Share Events": "Compartir eventos",
  Shadow: "Sombra",
  "Inner Padding": "Acolchado interior",
  Text: "Texto",
  "Active Button Border": "Borde de botón activo",
  "Light Mode": "Modo de luz",
  "Event Text Color": "Color del texto del evento",
  Dates: "fechas",
  Skeleton: "Esqueleto",
  "Skeleton Color": "Esqueleto De Color",
  Width: "Anchura",
  "Skeleton Style": "Estilo esqueleto",
  Color: "Color",
  "Section Titles": "Títulos de sección",
  "Section Content": "Contenido de la sección",
  Header: "Encabezamiento",
  Map: "Mapa",
  Standard: "Estándar",
  Retro: "Retro",
  Silver: "Plata",
  Night: "Noche",
  Dark: "Oscuro",
  Aubergine: "Berenjena",
  "Map Header": "Encabezado del mapa",
  "Show Title in mobile": "Mostrar título en el móvil",
  Card: "Tarjeta",
  "Card View": "Vista de tarjeta",
  "Card background color": "Color de fondo de la tarjeta",
  "Title font": "Fuente del titulo",
  "Desciption font": "Fuente de descripción",
  "Section font": "Sección de fuentes",
  "Section divider color": "Color del divisor de sección",
  "General Info": "Información general",
  Venue: "Lugar de eventos",
  Organizer: "Organizador",
  Search: "Buscar",
  calendar: "calendario",
  "Copy event URL": "Copiar URL del evento",
  "Copied!": "Copiado!",
  "Add & Share": "Agregar y compartir",
  "Calendar view": "Vista de calendario",
  "Add Event": "Vista de calendario",
  Uncategorised: "Sin categoría",
  More: "Más",
  Less: "Menos",
  Register: "Registrarse",
  Guests: "Invitados",
  unlimited: "ilimitado",
  "Show more": "Mostrar más",
  "Add event": "Añadir evento",
  "All Day Event": "Evento de todo el día",
  Location: "Ubicación",
  "Choose a category": "Elige una categoría",
  "Venue name": "Nombre del lugar",
  "Venue phone": "Teléfono del lugar",
  "Venue email": "Correo electrónico del lugar",
  "Venue website": "Sitio web del lugar",
  "Organizer name": "Nombre del organizador",
  "Organizer phone": "Teléfono del organizador",
  "Organizer email": "Correo electrónico del organizador",
  "Organizer website": "Sitio web del organizador",
  "Personal info": "Información personal",
  "First name": "Nombre de pila",
  "Last name": "Apellido",
  "Email Address": "Dirección de correo electrónico",
  "Additional Notes": "Notas adicionales",
  Back: "Atrás",
  Save: "Salvar",
  Next: "Próximo",
  "Your event has been submitted": "Su evento ha sido enviado",
  "Event submittion has been failed": "El envío del evento ha fallado",
  "e.g. Birthday Party": "p.ej. Fiesta de cumpleaños",
  "First Name": "Primer nombre",
  "Last Name": "Apellido",
  "Phone Number": "Número de teléfono",
  Address: "Habla a",
  "Your comments": "Tus comentarios",
  "How many guests?": "How many guests?",
  "Anything else we need to know?": "¿Algo más que necesitemos saber?",
  "Guests:": "Guests:",
  Submit: "Enviar",
  "Go to Calendar": "Ir al calendario",
  "Registration completed successfully!": "¡Registro completado con éxito!",
  "Please check your registered email address":
    "Compruebe su dirección de correo electrónico registrada",
  "Add to Calendar": "Añadir al calendario",
  "Share this Event": "Comparte este evento",
  "Sorry something went wrong": "Perdón, algo salió mal",
  "Back to registration": "بازگشت به ثبت نام",
  "Date & Location": "Fecha y lugar",
  "Date & Time": "Fecha y hora",
  home: "hogar",
  "Header align": "Alineación de encabezado",
  Footer: "Pie de página",
  "Categories Filter": "filtro de categorías",
  "Show only upcoming": "Show only upcoming",
  "Card(s) in a row": "Tarjeta (s) en una fila",
  "Space between cards": "Espacio entre cartas",
  "Shown events limit": "Límite de eventos mostrados",
  "Style 1": "Estilo 1",
  "Style 2": "Estilo 2",
  "Style 3": "Estilo 3",
  "Style 4": "Estilo 4",
  "Buttons & Links": "Botones y enlaces",
  "Button corner radius": "Radio de la esquina del botón",
  "Buttons font": "Fuente de botones",
  "Buttons background": "Fondo de botones",
  "Get notified by Email": "Recibe una notificación por correo electrónico",
  "Review events": "Revisar eventos",
  "Click on date": "Haga clic en la fecha",
  "Add Event button": "Botón Agregar evento",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "La sincronización de calendario le permite integrar sus eventos y sesiones con su Calendario Boom.",
  connect: "conectar",
  "Synchronized Calendars": "Calendarios sincronizados",
  "Import events": "Importar eventos",
  Disconnect: "Desconectar",
  "Choose calendar": "Elige calendario",
  "Monitor your Wix events through the sync feature":
    "Monitorea tus eventos de Wix a través de la función de sincronización",
  "Connect all your Boom calendars available on your website":
    "Conecte todos sus calendarios Boom disponibles en su sitio web",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Programe, únase y administre reuniones de Zoom directamente a través de nuestro Calendario Boom.",
  "Monitor your Event Brite events through the Event Brite sync feature.":
    "Supervise sus eventos de Event Brite a través de la función de sincronización de Event Brite",
  Email: "Correo electrónico",
  "Add-ons": "Complementos",
  "Receive notification emails as soon as users add events to your calendar.":
    "Reciba correos electrónicos de notificación tan pronto como los usuarios agreguen eventos a su calendario.",
  "Enable + button on the calendar header":
    "Habilitar el botón + en el encabezado del calendario",
  "Accept or decline events added by customers before making them public.":
    "Accept or decline events added by customers before making them public.",
  "Switch Add Event": "Cambiar el evento Agregar",
  "Enable your browser cookies to connect to your account.":
    "Habilite las cookies de su navegador para conectarse a su cuenta.",
  "Learn more": "Aprende más",
  "Print Button": "دکمه چاپ",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Permitir a sus usuarios imprimir su calendario de eventos de auge en cualquier rango de fecha.",
  "Show Title on mobile": "Mostrar título en el móvil",
  "Show Skeleton on mobile": "Mostrar esqueleto en el móvil",
  "Start 7-day Business trial": "Comience su prueba de negocios de 7 días",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Disfrute de todas las características ilimitadas, como boletos de venta, registro, complementos de eventos de visitantes.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Tenga en cuenta: Al final del período de prueba, se le devolverá a su plan de suscripción existente.",
  "Not Now": "Ahora no",
  "Start free trial": "Empiza la prueba gratuita",
  "Congrats!": "¡Felicitaciones!",
  "Your 7-day Business trial has been successfully activated.":
    "Su prueba de negocios de 7 días se ha activado con éxito.",
  Done: "Hecho",
  "Title font color": "Color de fuente de título",
  "Desciption font color": "Descripción Color de fuente",
  "Section font color": "Color de fuente de la sección",
  "Card Header": "Encabezado de tarjeta",
  Category: "Categoría",
  "Display at the": "Mostrar en el",
  top: "cima",
  bottom: "fondo",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Muestra el filtro de categoría en la parte superior o en la parte inferior del calendario.La configuración se aplica solo a la agenda y las vistas de la tarjeta solamente",
  "Processing your events": "Procesando tus eventos",
  "Search for events": "Buscar eventos",
  "There are no events added": "No hay eventos añadidos.",
  "Location: To be determined": "Ubicación: para ser determinado",
  "No events for selected date": "No hay eventos para la fecha seleccionada",
  Uncategorized: "Sin categoría",
  "Edit event": "Evento de edición",
  "Edit original event": "Editar evento original",
  "Copy event": "Evento de copia",
  "Copy as new event": "Copiar como nuevo evento",
  "Delete event": "Evento de eliminación",
  "Stop repeating on this date": "Deja de repetir en esta fecha",
  "Exclude this date": "Excluir esta fecha",
  "Location is going to be announced": "La ubicación se anunciará",
  "Fill your personal information": "Complete su información personal",
  "Check Box": "Casilla de verificación",
  "Single Choice": "Elección única",
  Option: "Opción",
  "Share Event": "Evento compartido",
  "Oops! Something went wrong": "¡Ups!Algo salió mal",
  "We are sorry this event has already taken place":
    "Lamentamos que este evento ya haya tenido lugar.",
  "Back to calendar": "Volver al calendario",
  "This field is required": "Este campo es obligatorio",
  Phone: "Teléfono",
  "Number field": "Campo numérico",
  "Please provide a valid email": "Proporcione un correo electrónico válido",
  "Select at least one option": "Seleccione al menos una opción",
  "Choose tickets to see total value": "Elija boletos para ver el valor total",
  tickets: "Entradas",
  "Choose Tickets": "Elija boletos",
  "Choose payment method": "elige el método de pago",
  Pay: "Pagar",
  Total: "Total",
  Free: "Libre",
  "Buy tickets": "Comprar boletos",
  "Sold Out": "Vendido",
  "Tickets are available": "Los boletos están disponibles",
  "Sales End": "Final de ventas",
  "Availible from": "Disponible de",
  "Go to Orders": "Ir a pedidos",
  "Go to Details": "Ir a detalles",
  "Group ticket": "Boleto grupal",
  Name: "Nombre",
  Price: "Precio",
  "Order by": "Ordenar",
  "Order ID": "Solicitar ID",
  Applied: "Aplicado",
  Fees: "Tarifa",
  "Enter promo code": "Introduce el código de promoción",
  Apply: "Solicitar",
  "Promo Code": "Código promocional",
  Cash: "Dinero en efectivo",
  "You can find your e-tickets attached to your email or download them":
    "Puede encontrar sus boletos electrónicos adjuntos a su correo electrónico o descargarlos",
  here: "aquí",
  Time: "Tiempo",
  "Invalid promo code": "Código de promoción no válido",
  "Credit card": "Tarjeta de crédito",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Pronto recibirá un mensaje de confirmación de registro exitoso en su dirección de correo electrónico.",
  "You can also check your order details below.":
    "También puede verificar los detalles de su pedido a continuación.",
  at: "a",
  Buy: "Comprar",
  Donation: "Donación",
  "Enter price": "Empresa",
  Choose: "Elegir",
  Chosen: "Elegido",
  "Choose your plan": "Elige tu plan",
  week: "semana",
  wk: "semana",
  "Choose plan cycle": "Elija el ciclo de plan",
  months: "meses",
  years: "años",
  weeks: "semanas",
  "Copy Event Url": "Copiar URL del evento",
  "You can find your e-tickets attached to your email or print them":
    "Puede encontrar sus boletos electrónicos adjuntos a su correo electrónico o imprimirlos",
  "Guest Info": "Información de invitado",
  "Ticket Info": "Información de boletos",
  "Ticket name": "Nombre de la multa",
  "Ticket price": "Precio del boleto",
  "Ticket ID": "Identificación de entradas",
  "If you have any questions contact to organizer":
    "Si tiene alguna pregunta, contacto con el organizador",
  "As soon as event ends": "Tan pronto como termine el evento",
  "1 day after event ends": "1 día después de que termine el evento",
  "7 days after event ends": "7 días después de que termine el evento",
  "14 days after event ends": "14 días después de que termine el evento",
  "30 days after event ends": "30 días después de que termine el evento",
  Menu: "Menú",
  "No event for selected date": "No hay evento para la fecha seleccionada",
  view: "vista",
  List: "Lista",
  Year: "Año",
  Yearly: "Anual",
  "Year view header": "Encabezado de vista anual",
  "Yearly Style": "Estilo anual",
  "There are no events": "No hay eventos",
  Autotranslation: "Autotranslación",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Una vez habilitado, su widget de calendario se traducirá en función del idioma del sitio web.* Tenga en cuenta que mientras el título del calendario, y las descripciones se ingresen textos ingresados, no se pueden traducir.",
  "Note on mobile": "Nota en Mobile",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Apague o cambie el texto de la barra 'Sin eventos' en la versión móvil del calendario",
  Autodeletion: "Autodeleción",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Habilitar la opción, eliminará automáticamente sus eventos pasados del calendario.",
  "This does not apply to repeating events!":
    "¡Esto no se aplica a los eventos repetidos!",
  "Notify event creators about the guest":
    "Notificar a los usuarios sobre el invitado",
  "Send event creators notification emails as soon as guests register for their events":
    "Envíe correos electrónicos de notificación a los creadores de eventos tan pronto como los invitados se registren para sus eventos",
  "List View Type": "Tipo de vista de lista",
  "Description font": "Fuente de descripción",
  Connect: "conectar",
  "You have no events": "No tienes eventos",
  Synchronize: "Sincronizar",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Google Calendar Sync le permite integrar sus eventos y sesiones con su calendario de auge.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "همگام سازی Outlook Calendar به شما امکان می دهد رویدادها و جلسات خود را با Boom Calendar خود ادغام کنید.",
  "Your message has been sent successfully!":
    "¡Tu mensaje ha sido enviado exitosamente!",
  "There are no synchronized calendars": "هیچ تقویم هماهنگ وجود ندارد",
  "to view more than 7 events": "para ver más de 7 eventos",
  "Mobile app": "Aplicación movil",
  "Admin Account": "Cuenta de administrador",
  Password: "کلمه عبور",
  "Second User": "Segundo usuario",
  Edit: "Editar",
  "Guest limit": "Límite de invitados",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Todas las configuraciones locales están (automáticamente) según su idioma.Si su idioma está en la lista, no hay necesidad de personalizar esta sección.",
  available: "disponible",
  next: "Siguiente",
  Tickets: "Entradas",
  Quantity: "Cantidad",
  "Promo code": "Código promocional",
  "Select a payment method": "Seleccione un método de pago",
  Fee: "Tarifa",
  Book: "Libro",
  "All the tickets have been sold out": "Todos los boletos han sido agotados.",
  "Choose at least one ticket": "Elija al menos un boleto",
  "First choose ticket": "Primero elige boleto",
  "Please fill out your personal information.":
    "Por favor, complete su información personal.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "Para realizar una compra exitosa, seleccione su método de pago preferido e ingrese el código de promoción para boletos con descuento.",
  "Credit/Debit card": "Tarjeta de crédito / débito",
  "print here.": "Imprimir aquí.",
  "QR code for all tickets": "Código QR para todos los boletos",
  Duration: "Duración",
  "Full Name": "Nombre completo",
  "Ticket id": "Identificación de entradas",
  "Group id": "Identificación del grupo",
  "Choose your ticket.": "Elija su boleto.",
  "Fill out your personal information.": "Rellene su información personal.",
  "Add the payment details.": "Añadir los detalles de pago.",
  "To be determined": "Estar determinado",
  "You can find your e-tickets attached to the email or":
    "Puede encontrar sus boletos electrónicos adjuntos al correo electrónico o",
  "print here": "Imprimir aquí",
  "Full name": "Nombre completo",
  "Group ID": "Identificación del grupo",
  "to Book": "reservar",
  "Unfortunately, your card has been declined":
    "Desafortunadamente, su tarjeta ha sido rechazada.",
  "Thank you for your purchase!": "Gracias por su compra!",
  "Find your printable e-tickets attached to the confirmation email":
    "Encuentre sus boletos electrónicos imprimibles adjuntos al correo electrónico de confirmación",
  Confirm: "Confirmar",

  "Add event": "Añadir evento",
  Events: "Eventos",
  "Event details": "Detalles del evento",
  Registration: "Registro",
  "Guests list": "Lista de invitados",
  Ticket: "Boleto",
  "General Info": "Información general",
  "Customize the general settings of your event":
    "Personalizar la configuración general de su evento",
  "Event Title": "Título del evento",
  "e.g. Birthday Party": "p.ej. Fiesta de cumpleaños",
  "All Day Event": "Evento todo el día",
  Cross: "Cruz",
  Timeline: "Línea de tiempo",
  "Repeating event": "Evento de repetición",
  Location: "Ubicación",
  "Venue name": "Nombre del lugar",
  Description: "Descripción",
  Image: "Imagen",
  Color: "Color",
  Category: "Categoría",
  "Add your events to color categories and let your users classify them easily":
    "Agregue sus eventos a las categorías de colores y deje que sus usuarios los clasifiquen fácilmente",
  "Category name": "Nombre de la categoría",
  "e.g. Birthdays": "p.ej. Cumpleaños",
  Venue: "Evento",
  "Where the event takes place": "Donde el evento tiene lugar",
  "Venue name": "Nombre del lugar",
  "Venue phone": "Teléfono",
  "Venue email": "Correo electrónico del lugar",
  "Venue website": "Sitio web del lugar",
  Organizer: "Organizador",
  "Person who makes the event": "Persona que hace el evento",
  "Organizer name": "Nombre del organizador",
  "Organizer phone": "Teléfono organizador",
  "Organizer email": "Correo electrónico del organizador",
  "Organizer website": "Sitio web de organizador",
  Save: "Ahorrar",
  Cancel: "Cancelar",
  Import: "Importar",
  Past: "Pasado",
  All: "Todo",
  Upcoming: "Próximo",
  Uncategorised: "Sin categoría",
  "Date Ascending": "Fecha ascendente",
  "Date Descending": "Fecha descendente",
  "Title by A-Z": "Título de A-Z",
  "Title by Z-A": "Título de Z-A",
  "There are no events for this period": "No hay eventos para este período",

  "Auto-Convert Date & Time": "Fecha y hora de autoconvertido",
  TimeZone: "Zona horaria",
  Autodeletion: "Autodeleción",
  "Layout Settings": "opciones de diseño",
  "Yeatly view": "Vista Yeatly",
  "Monthly view header": "Encabezado de vista mensual",
  "Weekly/Daily view header": "Encabezado semanal/diario",
  Acendings: "Acense",
  Descending: "Descendente",
  Standart: "Estancado",
  Silver: "Plata",
  Retro: "Retro",
  Dark: "Oscuro",
  Night: "Noche",
  Aubergine: "Berenjena",
  "List view header": "Encabezado de vista de lista",
  "Side by Side View": "Vista lado a lado",
  "Customize Proportions": "Personalizar proporciones",
  "Card Margins": "Márgenes de la tarjeta",
  "Image opacity (%)": "Opacidad de imagen (%)",
  "Side by Side Header": "Encabezado lado a lado",
  "Text Align": "Texto alineado",
  "Timeline View": "Vista de línea de tiempo",
  "Title font color": "Color de la fuente del título",
  "Desciption font color": "Color de fuente de descipación",
  "Line color": "Color de linea",
  "Date Font color": "Color de fuente de fecha",
  "Daily events background": "Antecedentes de eventos diarios",
  Alignment: "Alineación",
  Vertical: "Vertical",
  Horizontal: "Horizontal",
  "Vertical Alignment": "Alineamiento vertical",
  Right: "Bien",
  Center: "Centro",
  "Horizontal Alignment": "Alineación horizontal",
  Top: "Arriba",
  Center: "Centro",
  Bottom: "Abajo",
  "Dates Circle Design": "Diseño del círculo de fechas",
  "Next To The Circle": "Al lado del círculo",
  "In The Circle": "En el círculo",
  "Timeline Header": "Encabezado de línea de tiempo",
  Timeline: "Línea de tiempo",
  "Show only upcoming": "Mostrar solo próximamente",
  "Order by": "Ordenar",
  "Timeline Event Limit": "Límite de evento de línea de tiempo",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Permita que el visitante agregue el evento a los calneds locales: Google, Yahoo, Outlook, icalendar.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Permita que los visitantes compartan su evento a Facebook, LinkedIn, Twitter, etc.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Agregue una opción de búsqueda en su calendario para permitir que las personas busquen sus eventos por título, lugar, etc.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Permita que sus usuarios impriman su calendario de eventos de auge en cualquier rango de fechas.",
  "Click to apply a theme to Calendar":
    "Haga clic para aplicar un tema al calendario",
  "Date container color": "Color del contenedor de fecha",
  "Daily events background": "Antecedentes de eventos diarios",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "¡Use los complementos para instalar funciones avanzadas en sus calendarios, haciéndolas más funcionales!",
  "Open Add-ons Store": "Abra la tienda de complementos",
  Monday: "Lunes",
  Tuesday: "Martes",
  Wednesday: "Miércoles",
  Thursday: "Jueves",
  Friday: "Viernes",
  Saturday: "Sábado",
  Sunday: "Domingo",
  "Yearly view": "Vista anual",
  Ascending: "Martes",
  "Show event time next to title": "Mostrar tiempo del evento junto al título",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Ajuste la fecha y hora del evento a la hora local del usuario en función de su zona horaria.",
  "Display the time zone alongside the event date.":
    "Muestre la zona horaria junto con la fecha del evento.",
  "Show event time next to title": "Mostrar tiempo del evento junto al título",
  "Time Zone": "Zona horaria",
  "Upload Image": "Cargar imagen",
  "Choose a Category": "Elige una categoría",
  "Color you have chosen will not be shown as you choose category":
    "El color que ha elegido no se mostrará según elija la categoría",
  Website: "Sitio web",
  Next: "Próximo",
  Save: "Ahorrar",
  "Last Name": "Apellido",
  "Personal Info": "Información personal",
  Back: "Atrás",
  "This field is required": "Este campo es obligatorio",
  "Your event has been submitted": "Su evento ha sido enviado",
  "Enter a location": "Ingrese una ubicación",
  "Display the time zone alongside the event date.":
    "Muestre la zona horaria junto con la fecha del evento.",
  Home: "Hogar",
  "Side By Side Event Limit": "Límite de eventos lado a lado",
  "Mobille App": "Aplicación Mobille",
  category: "categoría",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Realice un seguimiento de su agenda fácilmente importando sus eventos de Facebook a su calendario.",
  "Synchronized Pages": "Páginas sincronizadas",
  "There are no synchronized pages": "No hay páginas sincronizadas.",
  "Choose page": "Elegir página",
  "You have no events": "No tienes eventos",
};
export default es;
