let et = {
  Categories: "Kategooriad",
  "Share this event": "Jaga seda sündmust",
  Language: "Keel",
  "Show Time Zone": "Kuva ajavöönd",
  "Custom Local Settings": "Kohandatud kohalikud seaded",
  "Add and showcase events on your site using a beautiful calendar.":
    "Lisage ja tutvustage oma saidil sündmusi, kasutades kaunist kalendrit.",
  "Week Days": "Nädalapäevad",
  "Manage Events": "Sündmusi haldama",
  General: "Üld-",
  "Layout Picker": "Paigutuse paigutaja",
  Month: "Kuu",
  Monthly: "Igakuine",
  Week: "Nädal",
  Weekly: "Iganädalane",
  Day: "Päev",
  Daily: "Iga päev",
  Agenda: "Päevakord",
  "Navigation Buttons": "Navigeerimisnupud",
  "Week numbers": "Nädalanumbrid",
  "Include Weekends": "Kaasa nädalavahetused",
  "All-day": "Terve päev",
  "All Day": "Terve päev",
  Label: "Silt",
  "Fit to Height": "Sobib kõrgusele",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Rakenduse proportsioonide määramiseks keelake see suvand ja redigeerija kalendri suuruse muutmine.",
  "Default Layout": "Vaikimisi paigutus",
  "Monthly view": "Igakuine vaade",
  "Weekly and Daily view": "Iganädalane ja igapäevane vaade",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Võite anda külastajatele järjepidevama kogemuse, näidates korraga sama arvu (6).",
  "Fixed Weekly Layout": "Fikseeritud iganädalane paigutus",
  back: "tagasi",
  Row: "Rida",
  "Hours in Weekly View": "Tunnid iganädalases vaates",
  "Hours in Daily View": "Tunnid igapäevases vaates",
  Start: "Alustama",
  End: "Lõpp",
  "At This Hour": "Sel tunnil",
  Button: "Nupp",
  Buttons: "Nupud",
  Sunday: "Pühapäev",
  Monday: "Esmaspäev",
  Tuesday: "Teisipäev",
  Wednesday: "Kolmapäev",
  Thursday: "Neljapäev",
  Friday: "Reede",
  Saturday: "Laupäev",
  "Default Date": "Vaikekuupäev",
  year: "aasta",
  month: "kuu",
  mo: "mo",
  days: "päevad",
  ago: "tagasi",
  ahead: "ees",
  Yesterday: "Eile",
  Today: "Täna",
  Tomorrow: "Homme",
  Custom: "Kohandatud",
  "Set Daily Rows Limit": "Seadke igapäevaste ridade piir",
  "Set Proportions": "Portsionid määrake",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Lubage külastajale sündmus lisada kohalikele CalDedaridele: Google, Yahoo, Outlook, iCalendar.",
  Container: "Konteiner",
  Background: "Taust",
  "Container Background": "Konteineri taust",
  "Container Borders": "Konteineripiirid",
  Calendar: "Kalender",
  "Event Info Tooltip": "Sündmuse teabe tööriistakat",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Kui inimesed hõljuvad sündmuse üle, näevad nad kogu teavet selle kohta tööriistakattes.",
  "Event Info Window": "Sündmuse teabe aken",
  "This is the full information window that opens when someone clicks on the event.":
    "See on täielik teabeaken, mis avaneb, kui keegi sündmusele klõpsab.",
  "Use Gradient": "Kasutage gradienti",
  Vertical: "Vertikaalne",
  Horizontal: "Horisontaalne",
  First: "Esimene",
  Second: "Teine",
  diagonal: "diagonaal",
  Radial: "Radiaalne",
  "Select option": "Valige valik",
  Solid: "Tahke",
  Dotted: "Täppidega",
  Dashed: "Kriipsutatud",
  Double: "Kahekordne",
  "Border Radius": "Piiriraadius",
  Padding: "Polsterdamine",
  "Date Header": "Kuupäeva päis",
  "Event Default Color": "Sündmuse vaikevärv",
  "Days of Week": "Nädalapäevad",
  "Days of Week Background": "Nädalapäevad taust",
  Date: "Kuupäev",
  "Event Title": "Ürituse pealkiri",
  "Highlight today": "Tärgige täna esile",
  "Highlight Color": "Esiletõstmine värvi esiletõstmist",
  Hide: "Varjama",
  "Calendar Border Color": "Kalendripiiri värv",
  "Calendar Border Width": "Kalendri piiri laius",
  "Calendar Border Style": "Kalendri piiristiil",
  "Font Color": "Fondi värv",
  "Event Background": "Ürituste taust",
  "Card Date Color": "Kaardi kuupäeva värv",
  "Title Font": "Tiitlivõistlus",
  "Date Font": "Kuupäevafond",
  "Description Font": "Kirjeldusfond",
  "Button Background": "Nupp taust",
  "Button Text": "Nupp tekst",
  "Border Color": "Piirvärv",
  "Border Width": "Piirilaius",
  "Border Type": "Piirtüüp",
  Title: "Tiitel",
  Description: "Kirjeldus",
  "Background Color": "Taustavärv",
  Divider: "Jagaja",
  "Event Details Font": "Sündmuse üksikasjad font",
  "Website Link Color": "Veebisaidi lingi värv",
  "Developer Info": "Arendaja teave",
  "User Guide": "Kasutusjuhend",
  "Support e-mail": "Toetage e-posti",
  "Our Website": "Meie veebisait",
  "App Review": "Rakenduse ülevaade",
  "Enjoying App? Leave us a review in the App Market.":
    "Rakenduse nautimine? Jätke meile rakenduste turul ülevaade.",
  "Review Us": "Vaadake meid üle",
  "Connect With Us": "Võta meiega ühendust",
  "What's your email?": "Mis on Sinu meiliaadress?",
  "Invalid email address!": "Vale emaili aadress!",
  Comments: "Kommentaarid",
  "We'd love to hear from you. Send us a message.":
    "Meile meeldiks sinust kuulda. Saada meile sõnum.",
  "Message must be at least 5 characters long":
    "Sõnum peab olema vähemalt 5 tähemärki pikk",
  Send: "Saada",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Kui soovite lubada kasutajal kalendrivaadete vahel vahetada, lubage see suvand ja valige vaated, mida soovite kuvada.",
  Main: "Peamine",
  Localize: "Lokaliseerima",
  Settings: "Sätted",
  Layouts: "Paigutused",
  Advanced: "Arenenud",
  Design: "Kujundamine",
  Support: "Toetus",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Kõik kohalikud sätted põhinevad (automaatselt) teie keelel. Kui teie keel on nimekirjas, pole seda jaotist vaja kohandada.",
  "Date Format": "Kuupäevavorming",
  "Time Format": "Ajavorm",
  "Text Direction": "Tekstisuund",
  "Left to Right": "Vasakult paremale",
  "Right to Left": "Paremale vasakule",
  "Week Starts On": "Nädal algab",
  "Agenda Style": "Päevakorra stiil",
  Classic: "Klassikaline",
  Modern: "Moodne",
  "Agenda Header": "Päevakava päis",
  "Upcoming Events": "Eesseisvad Sündmused",
  "Agenda Event Limit": "Päevakorraürituse piirmäär",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Uuendage kohe ja hankige palju rohkem funktsioone ning nautige oma rakendust täielikult!",
  "Upgrade Now": "Uuenda nüüd",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Kas korraldate üritusi, mis kestavad terve päeva? See võimaldab teil neid oma kalendris näidata.",
  "24 hours": "24 tundi",
  Sat: "Laup",
  Sun: "Päike",
  Mon: "Esmaspäev",
  Default: "Täitmata jätmine",
  "Select custom design style for your calendar.":
    "Valige kalendri jaoks kohandatud kujundusstiil.",
  Style: "Stiil",
  "Styles and Colors": "Stiilid ja värvid",
  "Calendar Name": "Kalendrimiinimi",
  "Write your Calendar name here": "Kirjutage oma kalendri nimi siia",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "See pole teie kasutajatele nähtav. Seadke nimed oma kalendrite eristamiseks, kui kasutate BOOM -kalendri sünkroonimisfunktsiooni.",
  "General Info": "Üldteave",
  Venue: "Koht",
  Organizer: "Korraldaja",
  Search: "Otsing",
  "Add to": "Lisa",
  calendar: "kalender",
  "Copy event URL": "Kopeeri sündmuse URL",
  "Copied!": "Kopeeritud!",
  "Add & Share": "Lisa ja jaga",
  Map: "Kaardistama",
  "Calendar view": "Kalendrivaade",
  "Add Event": "ADD sündmus",
  Uncategorised: "Kategooriateta",
  More: "Rohkem",
  Less: "Vähem",
  Register: "Registreeri",
  Card: "Kaart",
  Guests: "Külalised",
  unlimited: "piiramatu",
  "Show more": "Näita rohkem",
  "Enable Search": "Luba otsimine",
  "+ Add Event": " + Lisa sündmus",
  "Manage and Sync": "Haldama ja sünkroonima",
  "Show event details as...": "Näita sündmuse üksikasju kui ...",
  Tooltip: "Tööriistakat",
  Popup: "Hüpik",
  None: "Mitte ükski",
  "Show Category": "Näita kategooriat",
  "Header Align": "Päise joondamine",
  "Show Time": "Aega näitama",
  "Hours in Weekly/Daily View": "Tunnid nädalas/igapäevases vaates",
  "Share Events": "Jagama üritusi",
  Shadow: "Vari",
  "Inner Padding": "Sisemine polster",
  Text: "Tekst",
  "Active Button Border": "Aktiivne nupuvalik",
  "Light Mode": "Kerge režiim",
  "Event Text Color": "Sündmuse teksti värv",
  Dates: "Kuupäevad",
  Skeleton: "Luustik",
  "Skeleton Color": "Skeleti värv",
  Width: "Laius",
  "Skeleton Style": "Skeleti stiil",
  Color: "Värvus",
  "Section Titles": "Sektsiooni pealkirjad",
  "Section Content": "Sektsiooni sisu",
  Header: "Päis",
  Standard: "Standard",
  Retro: "Retro",
  Silver: "Hõbedane",
  Night: "Öö",
  Dark: "Tume",
  Aubergine: "Babloot",
  "Map Header": "Kaardipäis",
  "Show Title in mobile": "Kuva mobiilis pealkiri",
  "Card View": "Kaardivaade",
  "Card background color": "Kaardi taustvärv",
  "Title font": "Tiitlifond",
  "Desciption font": "Desciption Font",
  "Section font": "Sektsiooni font",
  "Section divider color": "Sektsioonide jagaja värv",
  "Add event": "ADD sündmus",
  "All Day Event": "Terve päeva üritus",
  Location: "Asukoht",
  "Choose a category": "Valige kategooria",
  "Venue name": "Saali nimi",
  "Venue phone": "Toimumiskoht",
  "Venue email": "Saali e -post",
  "Venue website": "Toimumiskoha veebisait",
  "Organizer name": "Korraldaja nimi",
  "Organizer phone": "Korraldaja telefon",
  "Organizer email": "Korraldaja e -post",
  "Organizer website": "Korraldaja veebisait",
  "Personal info": "Personaalne informatsioon",
  "First name": "Eesnimi",
  "Last name": "Perekonnanimi",
  "Email Address": "E-posti aadress",
  "Additional Notes": "lisamärkmed",
  Back: "tagasi",
  Save: "Kokkuhoid",
  Next: "Järgmine",
  "Your event has been submitted": "Teie üritus on esitatud",
  "Event submittion has been failed": "Ürituse esitamine on ebaõnnestunud",
  "e.g. Birthday Party": "nt Sünnipäevapidu",
  "First Name": "Eesnimi",
  "Last Name": "Perekonnanimi",
  "Phone Number": "Telefoninumber",
  Address: "Aadress",
  "Your comments": "Sinu Kommentaarid",
  "How many guests?": "Mitu külalist?",
  "Anything else we need to know?": "Midagi muud, mida peame teadma?",
  "Guests:": "Külalised:",
  Submit: "Esita",
  "Go to Calendar": "Mine kalendrisse",
  "Registration completed successfully!": "Registreerimine lõpetati edukalt!",
  "Please check your registered email address":
    "Palun kontrollige oma registreeritud e -posti aadressi",
  "Add to Calendar": "Lisage kalendrisse",
  "Share this Event": "Jaga seda sündmust",
  "Sorry something went wrong": "Vabandust, midagi läks valesti",
  "Back to registration": "Tagasi registreerimise juurde",
  "Date & Location": "Kuupäev ja asukoht",
  "Date & Time": "Kuupäev Kellaaeg",
  home: "Kodu",
  "Header align": "Päise joondamine",
  Footer: "Jalus",
  "Categories Filter": "Kategooriate filter",
  "Show only upcoming": "Näita ainult tulevane",
  "Card(s) in a row": "Kaart (d) järjest",
  "Space between cards": "Ruum kaartide vahel",
  "Shown events limit": "Näidatud sündmuste piir",
  "Style 1": "Stiil 1",
  "Style 2": "2. stiil",
  "Style 3": "3. stiil",
  "Style 4": "Stiil 4",
  "Buttons & Links": "Nööbid ja lingid",
  "Button corner radius": "Nupu nurgaraadius",
  "Buttons font": "Nööbid font",
  "Buttons background": "Nuppude taust",
  "Get notified by Email": "Saate teavitada e -posti teel",
  "Review events": "Ülevaade sündmused",
  "Click on date": "Klõpsake kuupäeval",
  "Add Event button": "Lisage sündmuse nupp",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Kalendri sünkroonimine võimaldab teil integreerida oma sündmused ja seansid oma boomikalendriga.",
  connect: "ühendama",
  "Synchronized Calendars": "Sünkroniseeritud kalendrid",
  "Import events": "Impordiüritused",
  Disconnect: "Ühenduse katkestama",
  "Choose calendar": "Valige kalender",
  "Monitor your Wix events through the sync feature":
    "Jälgige oma WIX -i sündmusi sünkroonimisfunktsiooni kaudu",
  "Connect all your Boom calendars available on your website":
    "Ühendage kõik oma veebisaidil saadaolevad buumikalendrid",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Planeerige, liituge ja hallake suumi koosolekuid otse meie boomi kalendri kaudu.",
  "Monitor your Event Brite events through the Event Brite sync feature.":
    "Jälgige oma ürituse Brite sündmusi sündmuse brite sünkroonimise kaudu",
  Email: "E -kiri",
  "Add-ons": "Lisandmoodulid",
  "Receive notification emails as soon as users add events to your calendar.":
    "Saate teatise e -kirju kohe, kui kasutajad lisavad teie kalendrisse sündmusi.",
  "Enable + button on the calendar header": "Luba + nupp kalendri päisel",
  "Accept or decline events added by customers before making them public.":
    "Enne nende avalikustamist nõustuge või lükake klientide poolt lisatud sündmused.",
  "Switch Add Event": "Switch ADD sündmus",
  "Enable your browser cookies to connect to your account.":
    "Luba oma kontoga ühenduse loomiseks oma brauseri küpsised.",
  "Learn more": "Õppige rohkem",
  "Print Button": "Printimisnupp",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Luba oma kasutajatel printida teie boomiürituste kalendrit mis tahes kuupäevavahemikus.",
  "Show Title on mobile": "Kuva mobiili pealkiri",
  "Show Skeleton on mobile": "Näita skeleti mobiilil",
  "Start 7-day Business trial": "Alustage 7-päevast ärikatset",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Nautige kõiki piiramatuid funktsioone, näiteks müüge pileteid, registreerimist, külastajate ürituste lisandmooduleid.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Pange tähele: prooviperioodi lõpus tagastatakse teid olemasolevasse tellimisplaani.",
  "Not Now": "Mitte praegu",
  "Start free trial": "Alustage tasuta prooviversiooni",
  "Congrats!": "Palju õnne!",
  "Your 7-day Business trial has been successfully activated.":
    "Teie 7-päevane ärikatse on edukalt aktiveeritud.",
  Done: "Tehtud",
  "Title font color": "Pealkirja fondi värv",
  "Desciption font color": "Desciption fondi värv",
  "Section font color": "Sektsiooni fondi värv",
  "Card Header": "Kaardipäis",
  Category: "Kategooria",
  "Display at the": "Kuva",
  top: "tipus",
  bottom: "alumine",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Esitage kategooriafilter kalendri ülaosas või allosas. Seaded kehtib ainult päevakorra- ja kaardivaadete kohta",
  "Processing your events": "Oma sündmuste töötlemine",
  "Search for events": "Sündmuste otsimine",
  "There are no events added": "Ühtegi üritust pole lisatud",
  "Location: To be determined": "Asukoht: määrata",
  "No events for selected date": "Valitud kuupäevaks pole üritusi",
  Uncategorized: "Kategooriateta",
  "Edit event": "Redigeerimisüritus",
  "Edit original event": "Redigeeri originaalsündmust",
  "Copy event": "Koopiaüritus",
  "Copy as new event": "Kopeeri uue sündmusena",
  "Delete event": "Kustutusüritus",
  "Stop repeating on this date": "Lõpetage sellel kuupäeval korramine",
  "Exclude this date": "Välistage see kuupäev",
  "Location is going to be announced": "Asukoht kuulutatakse välja",
  "Fill your personal information": "Täitke oma isiklik teave",
  "Check Box": "Märkeruut",
  "Single Choice": "Üksikvalik",
  Option: "Võimalus",
  "Share Event": "Aktsiaüritus",
  "Oops! Something went wrong": "Vabandust! Midagi läks valesti",
  "We are sorry this event has already taken place":
    "Meil on kahju, et see sündmus on juba toimunud",
  "Back to calendar": "Tagasi kalendrisse",
  "This field is required": "Selle välja täitmine on kohustuslik",
  Phone: "Telefon",
  "Number field": "Numbriväli",
  "Please provide a valid email": "Esitage kehtiv e -kiri",
  "Select at least one option": "Valige vähemalt üks võimalus",
  "Choose tickets to see total value": "Valige piletid, et näha koguväärtust",
  tickets: "piletid",
  "Choose Tickets": "Valige piletid",
  "Choose payment method": "Vali maksemeetod",
  Pay: "Maksma",
  Total: "Kogusumma",
  Free: "Vaba",
  "Buy tickets": "Pileteid ostma",
  "Sold Out": "Välja müüdud",
  "Tickets are available": "Piletid on saadaval",
  "Sales End": "Müügi lõpp",
  "Availible from": "Kättesaadav",
  "Go to Orders": "Käske",
  "Go to Details": "Üksikasjade juurde",
  "Group ticket": "Rühmapilet",
  Name: "Nimetus",
  Price: "Hind",
  "Order by": "Tellimus",
  "Order ID": "Tellimuse ID",
  Applied: "Rakendatud",
  Fees: "Tasud",
  "Enter promo code": "Sisestage promokood",
  Apply: "Rakendama",
  "Promo Code": "Promo kood",
  Cash: "Raha",
  "You can find your e-tickets attached to your email or download them":
    "Leiate oma e-piletid oma e-kirja külge või alla laadida",
  here: "siin",
  Time: "Aeg",
  "Invalid promo code": "Kehtetu reklaamikood",
  "Credit card": "Krediitkaart",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Saate peagi oma e -posti aadressile eduka registreerimise kinnitussõnumi.",
  "You can also check your order details below.":
    "Samuti saate oma tellimuse üksikasju kontrollida allpool.",
  at: "juures",
  Buy: "Ostma",
  Donation: "Annetus",
  "Enter price": "Hinnahinda",
  Choose: "Valima",
  Chosen: "Valitud",
  "Choose your plan": "Valige oma plaan",
  week: "nädal",
  wk: "wk",
  "Choose plan cycle": "Valige plaani tsükkel",
  months: "kuud",
  years: "aastaid",
  weeks: "nädalad",
  "Copy Event Url": "Kopeeri sündmuse URL",
  "You can find your e-tickets attached to your email or print them":
    "Leiate oma e-piletid oma e-kirja külge või printida need",
  "Guest Info": "Külaliste teave",
  "Ticket Info": "Piletiinfo",
  "Ticket name": "Piletinimi",
  "Ticket price": "Piletihind",
  "Ticket ID": "Pileti ID",
  "If you have any questions contact to organizer":
    "Kui teil on küsimusi, pöörduge korraldajaga",
  "As soon as event ends": "Niipea kui sündmus lõpeb",
  "1 day after event ends": "1 päev pärast ürituse lõppu",
  "7 days after event ends": "7 päeva pärast sündmuse lõppu",
  "14 days after event ends": "14 päeva pärast sündmuse lõppu",
  "30 days after event ends": "30 päeva pärast sündmuse lõppu",
  Menu: "Menüü",
  "No event for selected date": "Valitud kuupäeva jaoks pole ühtegi sündmust",
  view: "vaade",
  List: "Nimekiri",
  Year: "Aasta",
  Yearly: "Igal aastal",
  "Year view header": "Aastavaate päis",
  "Yearly Style": "Iga -aastane stiil",
  "There are no events": "Üritusi pole",
  Autotranslation: "Autotranslatsioon",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Kui see on lubatud, tõlgitakse teie kalendris vidin veebisaidi keele põhjal. *Pange tähele, et seni, kuni kalendri pealkiri ja kirjeldused on sisestatud tekstid, ei saa neid tõlkida.",
  "Note on mobile": "Märkus mobiiltelefoni kohta",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Lülitage välja või muutke kalendri mobiiliversiooni riba „No Events” teksti",
  Autodeletion: "Autodetimine",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Võimaluse lubamine eemaldab teie varasemad sündmused automaatselt kalendrist.",
  "This does not apply to repeating events!":
    "See ei kehti sündmuste korduvate kohta!",
  "Notify event creators about the guest":
    "Teavitage ürituse loojaid külalise kohta",
  "Send event creators notification emails as soon as guests register for their events":
    "Saatke sündmuste loojad teatamise e -kirjad kohe, kui külalised registreeruvad oma üritustele",
  "List View Type": "Loendi vaade tüüp",
  "Description font": "Kirjeldusfond",
  Connect: "Ühendama",
  "You have no events": "Teil pole üritusi",
  Synchronize: "Sünkroonima",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Google'i kalendri sünkroonimine võimaldab teil integreerida oma sündmused ja seansid oma boomikalendriga.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Outlooki kalendri sünkroonimine võimaldab teil integreerida oma sündmusi ja seansse oma boomikalendriga.",
  "Your message has been sent successfully!": "Sinu sõnum on edukalt saadetud!",
  "There are no synchronized calendars": "Sünkroniseeritud kalendreid pole",
  "to view more than 7 events": "vaadata rohkem kui 7 üritust",
  "Mobile app": "Mobiilirakendus",
  "Admin Account": "Administraatorikonto",
  Password: "Parool",
  "Second User": "Teine kasutaja",
  Edit: "Redigeerima",
  "Guest limit": "Külalislimiit",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Kõik kohalikud sätted põhinevad (automaatselt) teie keelel. Kui teie keel on nimekirjas, pole seda jaotist vaja kohandada.",
  available: "saadav",
  next: "järgmine",
  Tickets: "Piletid",
  Quantity: "Kogus",
  "Promo code": "Promo kood",
  "Select a payment method": "Valige makseviis",
  Fee: "Lõiv",
  Book: "Raamat",
  "All the tickets have been sold out": "Kõik piletid on välja müüdud",
  "Choose at least one ticket": "Valige vähemalt üks pilet",
  "First choose ticket": "Esmalt valige pilet",
  "Please fill out your personal information.":
    "Palun täitke oma isiklik teave.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "Eduka ostu tegemiseks valige palun oma eelistatud makseviis ja sisestage sooduspiletite jaoks reklaamikood.",
  "Credit/Debit card": "Krediidi-/deebetkaart",
  "print here.": "printige siia.",
  "QR code for all tickets": "Kõigi piletite QR -kood",
  Duration: "Kestus",
  "Full Name": "Täisnimi",
  "Ticket id": "Pileti ID",
  "Group id": "Rühma ID",
  "Choose your ticket.": "Valige oma pilet.",
  "Fill out your personal information.": "Täitke oma isiklik teave.",
  "Add the payment details.": "Lisage makse üksikasjad.",
  "To be determined": "Määrata",
  "You can find your e-tickets attached to the email or":
    "Leiate oma e-piletid e-kirja külge või",
  "print here": "printige siia",
  "Full name": "Täisnimi",
  "Group ID": "Rühma ID",
  "to Book": "broneerima",
  "Unfortunately, your card has been declined":
    "Kahjuks on teie kaart tagasi lükatud",
  "Thank you for your purchase!": "Täname teid ostu eest!",
  "Find your printable e-tickets attached to the confirmation email":
    "Leidke oma prinditavad e-piletid, mis on lisatud kinnitusmeilile",
  Confirm: "Kinnitama",

  "Add event": "ADD sündmus",
  Events: "Sündmused",
  "Event details": "Sündmuse üksikasjad",
  Registration: "Registreerimine",
  "Guests list": "Külaliste nimekiri",
  Ticket: "Pilet",
  "General Info": "Üldteave",
  "Customize the general settings of your event":
    "Kohandage oma ürituse üldisi sätteid",
  "Event Title": "Ürituse pealkiri",
  "e.g. Birthday Party": "nt Sünnipäevapidu",
  "All Day Event": "Terve päeva üritus",
  Cross: "Risti",
  Timeline: "Ajakava",
  "Repeating event": "Korduv sündmus",
  Location: "Asukoht",
  "Venue name": "Saali nimi",
  Description: "Kirjeldus",
  Image: "Pilt",
  Color: "Värvus",
  Category: "Kategooria",
  "Add your events to color categories and let your users classify them easily":
    "Lisage oma sündmused värvikategooriatesse ja laske kasutajatel neid hõlpsalt klassifitseerida",
  "Category name": "Kategooria nimi",
  "e.g. Birthdays": "nt Sünnipäevad",
  Venue: "Koht",
  "Where the event takes place": "Kus sündmus toimub",
  "Venue name": "Saali nimi",
  "Venue phone": "Toimumiskoht",
  "Venue email": "Saali e -post",
  "Venue website": "Toimumiskoha veebisait",
  Organizer: "Korraldaja",
  "Person who makes the event": "Inimene, kes ürituse teeb",
  "Organizer name": "Korraldaja nimi",
  "Organizer phone": "Korraldaja telefon",
  "Organizer email": "Korraldaja e -post",
  "Organizer website": "Korraldaja veebisait",
  Save: "Kokkuhoid",
  Cancel: "Tühistama",
  Import: "Import",
  Past: "Möödunud",
  All: "Kõik",
  Upcoming: "Tulevane",
  Uncategorised: "Kategooriateta",
  "Date Ascending": "Kuupäev tõuseb",
  "Date Descending": "Kuupäev laskuv",
  "Title by A-Z": "A-Z pealkiri",
  "Title by Z-A": "Z-A pealkiri",
  "There are no events for this period": "Selle perioodi jaoks pole üritusi",

  "Auto-Convert Date & Time": "Automaatne konvert kuupäev ja kellaaeg",
  TimeZone: "Ajavöönd",
  Autodeletion: "Autodetimine",
  "Layout Settings": "Paigutuse sätted",
  "Yeatly view": "Yeatly vaata",
  "Monthly view header": "Igakuine vaate päis",
  "Weekly/Daily view header": "Iganädalane/igapäevane vaate päis",
  Acendings: "Akended",
  Descending: "Laskuv",
  Standart: "Staardida",
  Silver: "Hõbedane",
  Retro: "Retro",
  Dark: "Tume",
  Night: "Öö",
  Aubergine: "Babloot",
  "List view header": "Loendivaate päis",
  "Side by Side View": "Kõrvuti vaade",
  "Customize Proportions": "Kohandada proportsioone",
  "Card Margins": "Kaardi veerised",
  "Image opacity (%)": "Pildi läbipaistmatus (%)",
  "Side by Side Header": "Kõrvuti päis",
  "Text Align": "Teksti joondamine",
  "Timeline View": "Ajajoone vaade",
  "Title font color": "Pealkirja fondi värv",
  "Desciption font color": "Desciption fondi värv",
  "Line color": "Joonevärv",
  "Date Font color": "Kuupäeva fondi värv",
  "Daily events background": "Igapäevaste sündmuste taust",
  Alignment: "Joondamine",
  Vertical: "Vertikaalne",
  Horizontal: "Horisontaalne",
  "Vertical Alignment": "Vertikaalne joondamine",
  Right: "Paremale",
  Center: "Keskus",
  "Horizontal Alignment": "Horisontaalne joondamine",
  Top: "Tipus",
  Center: "Keskus",
  Bottom: "Alumine",
  "Dates Circle Design": "Kuupäevade ringi kujundus",
  "Next To The Circle": "Ringi kõrval",
  "In The Circle": "Ringis",
  "Timeline Header": "Ajajoone päis",
  Timeline: "Ajakava",
  "Show only upcoming": "Näita ainult tulevane",
  "Order by": "Tellimus",
  "Timeline Event Limit": "Ajajoone sündmuse piir",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Lubage külastajale sündmus lisada kohalikele CalDedaridele: Google, Yahoo, Outlook, iCalendar.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Lubage külastajal jagada teie üritust Facebooki, LinkedIni, Twitteri jt.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Lisage oma kalendrisse otsinguvalik, et inimesed saaksid teie sündmusi pealkirja, toimumiskoha jms järgi otsida",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Luba oma kasutajatel printida teie boomiürituste kalendrit mis tahes kuupäevavahemikus.",
  "Click to apply a theme to Calendar":
    "Klõpsake teema rakendamiseks kalendrisse",
  "Date container color": "Kuupäeva konteiner värv",
  "Daily events background": "Igapäevaste sündmuste taust",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Kasutage lisandmoodulaid, et installida oma kalendritele täpsemad funktsioonid, muutes need funktsionaalsemaks!",
  "Open Add-ons Store": "Avatud lisandmoodulite pood",
  Monday: "Esmaspäev",
  Tuesday: "Teisipäev",
  Wednesday: "Kolmapäev",
  Thursday: "Neljapäev",
  Friday: "Reede",
  Saturday: "Laupäev",
  Sunday: "Pühapäev",
  "Yearly view": "Iga -aastane vaade",
  Ascending: "Martes",
  "Show event time next to title": "Kuva sündmuse aeg pealkirja kõrval",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Reguleerige sündmuse kuupäeva ja kellaaega kasutaja kohaliku ajaga vastavalt nende ajavööndile.",
  "Display the time zone alongside the event date.":
    "Kuvage ajavöönd sündmuse kuupäeva kõrval.",
  "Show event time next to title": "Kuva sündmuse aeg pealkirja kõrval",
  "Time Zone": "Ajavöönd",
  "Upload Image": "Lae pilt üles",
  "Choose a Category": "Valige kategooria",
  "Color you have chosen will not be shown as you choose category":
    "Värvi, mille olete valitud, ei kuvata kategooria valitud",
  Website: "Veebisait",
  Next: "Järgmine",
  Save: "Kokkuhoid",
  "Last Name": "Perekonnanimi",
  "Personal Info": "Personaalne informatsioon",
  Back: "tagasi",
  "This field is required": "Selle välja täitmine on kohustuslik",
  "Your event has been submitted": "Teie üritus on esitatud",
  "Enter a location": "Sisestage asukoht",
  "Display the time zone alongside the event date.":
    "Kuvage ajavöönd sündmuse kuupäeva kõrval.",
  Home: "Kodu",
  "Side By Side Event Limit": "Kõrvuti sündmuste piir",
  "Mobille App": "Mobille'i rakendus",
  category: "kategooria",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Saate oma ajakava hõlpsalt jälgida, importides oma Facebooki sündmused kalendrisse.",
  "Synchronized Pages": "Sünkroonitud lehed",
  "There are no synchronized pages": "Sünkroonitud lehti pole",
  "Choose page": "Valige leht",
  "You have no events": "Teil pole üritusi",
};
export default et;
