let eu = {
  Categories: "Kategoria",
  "Share this event": "Partekatu gertaera hau",
  Language: "Mintzaira",
  "Show Time Zone": "Erakutsi ordu-zona",
  "Custom Local Settings": "Tokiko ezarpen pertsonalizatuak",
  "Add and showcase events on your site using a beautiful calendar.":
    "Gehitu eta erakutsi zure webguneko gertaerak egutegi eder bat erabiliz.",
  "Week Days": "Asteko egunak",
  "Manage Events": "Gertaerak kudeatu",
  General: "Jeneral",
  "Layout Picker": "Diseinu hautatzailea",
  Month: "Hil",
  Monthly: "Hileko",
  Week: "Aste",
  Weekly: "Asteko",
  Day: "Egun",
  Daily: "Eguneroko",
  Agenda: "Gai-zerrenda",
  "Navigation Buttons": "Nabigazio botoiak",
  "Week numbers": "Asteko zenbakiak",
  "Include Weekends": "Asteburuetan sartu",
  "All-day": "Egun osoan",
  "All Day": "Egun osoan",
  Label: "Etiketa",
  "Fit to Height": "Altuera egokitu",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Aplikazio proportzioak Manully Desgaitu aukera hau eta aldatu egutegia editorean.",
  "Default Layout": "Diseinu lehenetsia",
  "Monthly view": "Hileroko ikuspegia",
  "Weekly and Daily view": "Astero eta eguneroko ikuspegia",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Bisitariei esperientzia koherentea eman diezaiekezu aldi berean (6) aste berdina erakutsiz.",
  "Fixed Weekly Layout": "Asteroko diseinu finkoa",
  back: "bizkar",
  Row: "Ilara",
  "Hours in Weekly View": "Orduak astero",
  "Hours in Daily View": "Orduko ikuspegian",
  Start: "Hasiera",
  End: "Amai",
  "At This Hour": "Ordu honetan",
  Button: "Botoi",
  Buttons: "Botoiak",
  Sunday: "Igande",
  Monday: "Astelehen",
  Tuesday: "Astearte",
  Wednesday: "Asteazken",
  Thursday: "Ostegun",
  Friday: "Ostiral",
  Saturday: "Larunbat",
  "Default Date": "Data lehenetsia",
  year: "urte",
  month: "hil",
  mo: "mo",
  days: "egun",
  ago: "duela",
  ahead: "aurrera",
  Yesterday: "Atzo",
  Today: "Gaur",
  Tomorrow: "Bihar",
  Custom: "Ohitura",
  "Set Daily Rows Limit": "Ezarri eguneko errenkadak",
  "Set Proportions": "Ezarri proportzioak",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Baimendu bisitariak ekitaldia gehitzeko tokiko kalnesetara: Google, Yahoo, Outlook, iCalendar.",
  Container: "Edukiontzi",
  Background: "Hondo",
  "Container Background": "Edukiontziaren aurrekariak",
  "Container Borders": "Edukiontzien mugak",
  Calendar: "Egutegi",
  "Event Info Tooltip": "Gertaeren informazioa tresna",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Jendeak gertakari baten gainetik pasatzen duenean, inguruko informazio guztia ikusiko dute tresna-tekla batean.",
  "Event Info Window": "Gertaeren informazio leihoa",
  "This is the full information window that opens when someone clicks on the event.":
    "Hau da norbaiten klik egiten duenean irekitzen den informazio leiho osoa.",
  "Use Gradient": "Erabili gradientea",
  Vertical: "Bertikal",
  Horizontal: "Horizontala",
  First: "Lehenengo",
  Second: "Segundu",
  diagonal: "maonal",
  Radial: "Erredi",
  "Select option": "Hautatu aukera",
  Solid: "Sendo",
  Dotted: "Puntatu",
  Dashed: "Urratu",
  Double: "Bikoitz",
  "Border Radius": "Ertzaren erradioa",
  Padding: "Betegarri",
  "Date Header": "Data goiburua",
  "Event Default Color": "Gertaera lehenetsitako kolorea",
  "Days of Week": "Asteko egunak",
  "Days of Week Background": "Asteko egunak",
  Date: "Datil",
  "Event Title": "Gertaeraren izenburua",
  "Highlight today": "Nabarmendu gaur",
  "Highlight Color": "Nabarmendu kolorea",
  Hide: "Larru",
  "Calendar Border Color": "Egutegiaren mugaren kolorea",
  "Calendar Border Width": "Egutegiaren mugaren zabalera",
  "Calendar Border Style": "Egutegiaren mugako estiloa",
  "Font Color": "Letra-kolorea",
  "Event Background": "Gertaeraren aurrekariak",
  "Card Date Color": "Txartelaren data kolorea",
  "Title Font": "Izenburua",
  "Date Font": "Data letra tipoa",
  "Description Font": "Deskribapena letra",
  "Button Background": "Botoiaren atzeko planoa",
  "Button Text": "Botoiaren testua",
  "Border Color": "Ertzaren kolorea",
  "Border Width": "Ertzaren zabalera",
  "Border Type": "Mugako mota",
  Title: "Izenburua",
  Description: "Deskribapen",
  "Background Color": "Atzeko planoaren kolorea",
  Divider: "Zatitzaile",
  "Event Details Font": "Ekitaldiaren xehetasunak letra",
  "Website Link Color": "Webgunearen esteka kolorea",
  "Developer Info": "Garatzaileen informazioa",
  "User Guide": "Erabiltzailearen gida",
  "Support e-mail": "Laguntza elektronikoa",
  "Our Website": "Gure webgunea",
  "App Review": "Aplikazioen berrikuspena",
  "Enjoying App? Leave us a review in the App Market.":
    "Aplikazioaz gozatzea? Utzi berrikuspena aplikazioen merkatuan.",
  "Review Us": "Berrikusi gaitzazu",
  "Connect With Us": "Konektatu gurekin",
  "What's your email?": "Zein da zure posta elektronikoa?",
  "Invalid email address!": "Helbide elektroniko baliogabea!",
  Comments: "Esaldiak",
  "We'd love to hear from you. Send us a message.":
    "Zurekin entzutea gustatuko litzaiguke. Bidali mezu bat.",
  "Message must be at least 5 characters long":
    "Mezuak gutxienez 5 karaktere izan behar ditu",
  Send: "Bidali",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Erabiltzaileari egutegiko bista batetik bestera aldatu nahi baduzu, gaitu aukera hau eta aukeratu erakutsi nahi dituzun ikuspegiak.",
  Main: "Nagusi",
  Localize: "Toki-",
  Settings: "Ezarpen",
  Layouts: "Diseinuak",
  Advanced: "Aurreratu",
  Design: "Diseinatu",
  Support: "Lagundu",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Tokiko ezarpen guztiak zure hizkuntzan oinarrituta (automatikoki) dira. Zure hizkuntza zerrendan badago, ez da atal hau pertsonalizatu beharrik.",
  "Date Format": "Data formatua",
  "Time Format": "Orduaren formatua",
  "Text Direction": "Testuaren norabidea",
  "Left to Right": "Ezkerretik eskuinera",
  "Right to Left": "Eskuinera ezkerrera",
  "Week Starts On": "Astea hasten da",
  "Agenda Style": "Agenda estiloa",
  Classic: "Klasiko",
  Modern: "Oraingo",
  "Agenda Header": "Agenda goiburua",
  "Upcoming Events": "Hurrengo ekitaldiak",
  "Agenda Event Limit": "Agenda Ekitaldiaren muga",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Eguneratu orain eta lortu ezaugarri gehiago eta gozatu zure aplikazioan!",
  "Upgrade Now": "Berritu orain",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Egun osoan irauten duten ekitaldiak antolatzea? Horrek zure egutegian erakusteko aukera ematen dizu.",
  "24 hours": "24 ordu",
  Sat: "Etorri",
  Sun: "Eguzki",
  Mon: "-En astizkun",
  Default: "Ez ordaindu",
  "Select custom design style for your calendar.":
    "Hautatu zure egutegiko diseinu pertsonalizatua.",
  Style: "Estilo",
  "Styles and Colors": "Estiloak eta koloreak",
  "Calendar Name": "Egutegiaren izena",
  "Write your Calendar name here": "Idatzi zure egutegiaren izena hemen",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Hau ez da zure erabiltzaileentzat ikusgai. Ezarri izenak zure egutegiak bereizteko Boom Calendar Sync funtzioa erabiltzerakoan.",
  "General Info": "Informazio orokorra",
  Venue: "Gotoreto",
  Organizer: "Hautibo",
  Search: "Araketa",
  "Add to": "Gehitu",
  calendar: "egutegi",
  "Copy event URL": "Kopiatu gertaeraren URLa",
  "Copied!": "Kopiatu!",
  "Add & Share": "Gehitu eta partekatu",
  Map: "Mapa",
  "Calendar view": "Egutegiaren ikuspegia",
  "Add Event": "Gehitu gertaera",
  Uncategorised: "Kategorizatu gabe",
  More: "Gehiago",
  Less: "Txikiago",
  Register: "Erregistratu",
  Card: "Txartel",
  Guests: "Gonbidatuak",
  unlimited: "mugagabe",
  "Show more": "Erakutsi gehiago",
  "Enable Search": "Gaitu bilaketa",
  "+ Add Event": " + Gertaera gehitu",
  "Manage and Sync": "Kudeatu eta sinkronizatu",
  "Show event details as...": "Erakutsi gertaeren xehetasunak ...",
  Tooltip: "TOOLTIP",
  Popup: "Agertu",
  None: "Ezein ez",
  "Show Category": "Erakutsi kategoria",
  "Header Align": "Goiburua lerrokatu",
  "Show Time": "Erakutsi denbora",
  "Hours in Weekly/Daily View": "Astero / eguneroko ikuspegia",
  "Share Events": "Partekatu Ekitaldiak",
  Shadow: "Geriza",
  "Inner Padding": "Barne betegarria",
  Text: "Testu",
  "Active Button Border": "Botoiaren ertza aktiboa",
  "Light Mode": "Argi modua",
  "Event Text Color": "Ekitaldien testu kolorea",
  Dates: "Azio",
  Skeleton: "Eskeleto",
  "Skeleton Color": "Eskeleto kolorea",
  Width: "Zabalera",
  "Skeleton Style": "Eskeleto estiloa",
  Color: "Kolore",
  "Section Titles": "Atalaren izenburuak",
  "Section Content": "Atalaren edukia",
  Header: "Nagusi",
  Standard: "Kalitate",
  Retro: "Erretratu",
  Silver: "Zilar",
  Night: "Gau",
  Dark: "Iluna",
  Aubergine: "Jubisiogin",
  "Map Header": "Mapa goiburua",
  "Show Title in mobile": "Erakutsi izenburua mugikorrean",
  "Card View": "Txartelaren ikuspegia",
  "Card background color": "Txartelaren atzeko kolorea",
  "Title font": "Izenburua",
  "Desciption font": "Deskipipipion letra",
  "Section font": "Atal letra-tipoa",
  "Section divider color": "Atalaren banatzailearen kolorea",
  "Add event": "Gehitu gertaera",
  "All Day Event": "Egun osoan gertaera",
  Location: "Kokaleku",
  "Choose a category": "Aukeratu kategoria bat",
  "Venue name": "Aretoaren izena",
  "Venue phone": "Lekua",
  "Venue email": "Areto posta",
  "Venue website": "Lekuaren webgunea",
  "Organizer name": "Antolatzailearen izena",
  "Organizer phone": "Antolatzailearen telefonoa",
  "Organizer email": "Antolatzaile elektronikoa",
  "Organizer website": "Antolatzaileen webgunea",
  "Personal info": "Informazio pertsonala",
  "First name": "Izena",
  "Last name": "Abizena",
  "Email Address": "Posta elektroniko helbidea",
  "Additional Notes": "Ohar osagarriak",
  Back: "Bizkar",
  Save: "Aurreztu",
  Next: "Gero",
  "Your event has been submitted": "Zure gertaera aurkeztu da",
  "Event submittion has been failed": "Gertaeren bidalketa huts egin da",
  "e.g. Birthday Party": "E.G. Urtebetetze festa",
  "First Name": "Izena",
  "Last Name": "Abizena",
  "Phone Number": "Telefono zenbakia",
  Address: "Hitzaldi",
  "Your comments": "Zure iruzkinak",
  "How many guests?": "Zenbat gonbidatu?",
  "Anything else we need to know?": "Beste zerbait jakin behar dugu?",
  "Guests:": "Gonbidatuak:",
  Submit: "-En azpian jarri",
  "Go to Calendar": "Egutegira joan",
  "Registration completed successfully!": "Izen ematea ondo burutu da!",
  "Please check your registered email address":
    "Mesedez, egiaztatu erregistratutako helbide elektronikoa",
  "Add to Calendar": "Gehitu egutegia",
  "Share this Event": "Partekatu gertaera hau",
  "Sorry something went wrong": "Barkatu zerbait gaizki joan da",
  "Back to registration": "Itzuli erregistrora",
  "Date & Location": "Data eta kokapena",
  "Date & Time": "Data eta ordua",
  home: "etxe",
  "Header align": "Goiburua lerrokatu",
  Footer: "Korronte",
  "Categories Filter": "Kategoriak iragazkia",
  "Show only upcoming": "Erakutsi datozenak bakarrik",
  "Card(s) in a row": "Karta (k) errenkadan",
  "Space between cards": "Txartelen arteko espazioa",
  "Shown events limit": "Erakutsi gertaeren muga",
  "Style 1": "1. estiloa",
  "Style 2": "2. estiloa",
  "Style 3": "3. estiloa",
  "Style 4": "4. estiloa",
  "Buttons & Links": "Botoiak eta estekak",
  "Button corner radius": "Button Corner RADIUS",
  "Buttons font": "Botoien letra",
  "Buttons background": "Botoien atzeko planoa",
  "Get notified by Email": "Jakinarazi posta elektroniko bidez",
  "Review events": "Berrikusteko gertaerak",
  "Click on date": "Egin klik data gainean",
  "Add Event button": "Gehitu gertaera botoia",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Egutegiaren sinkronizazioak zure ekitaldiak eta saioak zure boom egutegiarekin integratzeko aukera ematen du.",
  connect: "batu",
  "Synchronized Calendars": "Egutegi sinkronizatuak",
  "Import events": "Inportazio gertaerak",
  Disconnect: "Deskonektatu",
  "Choose calendar": "Aukeratu Egutegia",
  "Monitor your Wix events through the sync feature":
    "Begira ezazu zure Wix gertaerak sinkronizazio funtzioaren bidez",
  "Connect all your Boom calendars available on your website":
    "Konektatu zure webgunean dauden boom egutegi guztiak",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Ordutegia, elkartu eta kudeatu zoom bilerak gure boom egutegiaren bidez.",
  "Monitor your Event Brite events through the Event Brite sync feature.":
    "Begira ezazu zure gertaera Brite gertaerak ekitaldiaren Brite Sync funtzioaren bidez",
  Email: "I-posta",
  "Add-ons": "Gehigarriak",
  "Receive notification emails as soon as users add events to your calendar.":
    "Jaso jakinarazpen mezu elektronikoak erabiltzaileek zure egutegian gertaerak gehitu bezain laster.",
  "Enable + button on the calendar header":
    "Gaitu + botoia egutegiko goiburuan",
  "Accept or decline events added by customers before making them public.":
    "Onartu edo baztertu bezeroek gehitutako gertaerak publiko egin aurretik.",
  "Switch Add Event": "Aldatu Gehitu gertaera",
  "Enable your browser cookies to connect to your account.":
    "Gaitu arakatzailearen cookieak zure kontura konektatzeko.",
  "Learn more": "Gehiago ikasi",
  "Print Button": "Inprimatu botoia",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Baimendu erabiltzaileei zure boom gertaeren egutegia inprimatu edozein data tartean.",
  "Show Title on mobile": "Erakutsi izenburua mugikorrean",
  "Show Skeleton on mobile": "Erakutsi eskeletoa mugikorrean",
  "Start 7-day Business trial": "7 eguneko negozio epaiketa hastea",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Gozatu mugagabeko ezaugarri guztiak, hala nola saldu sarrerak, erregistroa, bisitarien gertaera gehigarriak.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Kontuan izan: epaiketaren amaieran, lehendik dagoen harpidetza planera itzuliko zara.",
  "Not Now": "Orain ez",
  "Start free trial": "Doako proba hasi",
  "Congrats!": "Zorionak!",
  "Your 7-day Business trial has been successfully activated.":
    "Zure 7 eguneko negozio epaiketa arrakastaz aktibatu da.",
  Done: "Egin",
  "Title font color": "Izenburua Letra-kolorea",
  "Desciption font color": "Descipipion Letra-kolorea",
  "Section font color": "Ataleko letra-kolorea",
  "Card Header": "Txartelaren goiburua",
  Category: "Kategoria",
  "Display at the": "Bistaratu",
  top: "tontor",
  bottom: "azpi",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Erakutsi kategoria iragazkia goiko aldean edo egutegiaren behealdean. Ezarpenak agenda eta txartelen ikuspegietan soilik aplikatzen dira",
  "Processing your events": "Zure gertaerak prozesatzen",
  "Search for events": "Gertaerak bilatu",
  "There are no events added": "Ez da gertaerarik gehitu",
  "Location: To be determined": "Kokapena: zehazteko",
  "No events for selected date": "Ez da gertaerarik hautatutako datarako",
  Uncategorized: "Kategorizatu gabe",
  "Edit event": "Editatu gertaera",
  "Edit original event": "Editatu Jatorrizko gertaera",
  "Copy event": "Kopiatu gertaera",
  "Copy as new event": "Kopiatu gertaera berri gisa",
  "Delete event": "Ezabatu gertaera",
  "Stop repeating on this date": "Data honetan errepikatzen utzi",
  "Exclude this date": "Data hau baztertu",
  "Location is going to be announced": "Kokapena jakinaraziko da",
  "Fill your personal information": "Bete zure informazio pertsonala",
  "Check Box": "Kontrol-laukia",
  "Single Choice": "Aukera bakarra",
  Option: "Hauta",
  "Share Event": "Partekatu gertaera",
  "Oops! Something went wrong": "Oops! Zerbait gaizki joan zen",
  "We are sorry this event has already taken place":
    "Sentitzen dugu ekitaldi hau dagoeneko egin da",
  "Back to calendar": "Egutegira itzuli",
  "This field is required": "Eremu hau derrigorrezkoa da",
  Phone: "Mugikorra",
  "Number field": "Zenbakien eremua",
  "Please provide a valid email": "Mesedez, eman baliozko mezu elektronikoa",
  "Select at least one option": "Aukeratu gutxienez aukera bat",
  "Choose tickets to see total value": "Aukeratu sarrerak balio osoa ikusteko",
  tickets: "sarrerak",
  "Choose Tickets": "Aukeratu sarrerak",
  "Choose payment method": "Aukeratu ordainketa metodoa",
  Pay: "Ordainketa",
  Total: "Guztizko",
  Free: "Dohainik",
  "Buy tickets": "Sarrerak erosi",
  "Sold Out": "Salduta",
  "Tickets are available": "Sarrerak eskuragarri daude",
  "Sales End": "Salmenten amaiera",
  "Availible from": "Erabilgarri",
  "Go to Orders": "Joan eskaeretara",
  "Go to Details": "Joan xehetasunetara",
  "Group ticket": "Talde txartela",
  Name: "Izen",
  Price: "Salneurri",
  "Order by": "Agindua",
  "Order ID": "Agindu IDa",
  Applied: "Aptete",
  Fees: "Tasak",
  "Enter promo code": "Sartu promo kodea",
  Apply: "Atxiki",
  "Promo Code": "Promozio kodea",
  Cash: "Kobratu",
  "You can find your e-tickets attached to your email or download them":
    "Zure posta elektronikora erantsitako e-sarrerak aurki ditzakezu edo deskargatu",
  here: "asko",
  Time: "Denbora",
  "Invalid promo code": "Promo kode baliogabea",
  "Credit card": "Kreditu txartela",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Laster zure helbide elektronikora erregistratzeko berrespen mezua jasoko duzu.",
  "You can also check your order details below.":
    "Zure eskaeraren xehetasunak ere ikus ditzakezu.",
  at: "-an",
  Buy: "Erosi",
  Donation: "Emari",
  "Enter price": "Sartu prezioa",
  Choose: "Aukeratu",
  Chosen: "Aukeratu",
  "Choose your plan": "Aukeratu zure plana",
  week: "aste",
  wk: "wzu",
  "Choose plan cycle": "Aukeratu Plan Zikloa",
  months: "hilabete",
  years: "urte",
  weeks: "aste",
  "Copy Event Url": "Kopiatu gertaeraren URLa",
  "You can find your e-tickets attached to your email or print them":
    "Zure posta elektronikora erantsitako zure helbide elektronikoak aurki ditzakezu edo inprimatu",
  "Guest Info": "Gonbidatuen informazioa",
  "Ticket Info": "Sarreren informazioa",
  "Ticket name": "Sarreren izena",
  "Ticket price": "Sarreren prezioa",
  "Ticket ID": "Sarreren IDa",
  "If you have any questions contact to organizer":
    "Galderarik baduzu, harremanetarako antolatzailearekin",
  "As soon as event ends": "Gertaera amaitu bezain pronto",
  "1 day after event ends": "Gertaera amaitu eta egun 1",
  "7 days after event ends": "Gertaera amaitu ondorengo 7 egun",
  "14 days after event ends": "Gertaera amaitu eta 14 egun igaro ondoren",
  "30 days after event ends": "Gertaera amaitu eta 30 egun igaro ondoren",
  Menu: "Menu",
  "No event for selected date": "Ez da gertaerarik hautatutako datarako",
  view: "ikusmen",
  List: "Zerrenda",
  Year: "Urte",
  Yearly: "Urte-urtean",
  "Year view header": "Urtea Ikusi goiburua",
  "Yearly Style": "Urteko estiloa",
  "There are no events": "Ez dago gertaerarik",
  Autotranslation: "Autotranslation",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Behin gaituta, zure egutegiaren widget webgunearen hizkuntzan oinarrituta itzuliko da. * Kontuan izan egutegiaren izenburua eta deskribapenak ezin direla itzul daitezkeen testuak.",
  "Note on mobile": "Oharra Mugikorrean",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Itzali edo aldatu egutegiko bertsio mugikorreko 'Ekitaldirik gabeko' barra",
  Autodeletion: "Autodelezioa",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Aukera gaitzea, automatikoki zure iraganeko gertaerak kenduko ditu egutegitik.",
  "This does not apply to repeating events!":
    "Hau ez da aplikatzen gertaerak errepikatzen!",
  "Notify event creators about the guest":
    "Gonbidatuari buruzko gertaeren sortzaileei jakinarazi",
  "Send event creators notification emails as soon as guests register for their events":
    "Bidali gertaeren sortzaileen jakinarazpen mezu elektronikoak gonbidatuak beren gertaeretan izena eman bezain laster",
  "List View Type": "Zerrenda ikuspegi mota",
  "Description font": "Deskribapena letra",
  Connect: "Batu",
  "You have no events": "Ez duzu gertaerarik",
  Synchronize: "Sinkronizatu",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Google Calendar Sync-ek zure ekitaldiak eta saioak zure boom egutegiarekin integratzeko aukera ematen du.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Outlook Calendar Sync-ek zure ekitaldiak eta saioak zure boom egutegiarekin integratzeko aukera ematen du.",
  "Your message has been sent successfully!": "Zure mezua ondo bidali da!",
  "There are no synchronized calendars": "Ez dago egutegi sinkronizaturik",
  "to view more than 7 events": "7 gertaera baino gehiago ikusteko",
  "Mobile app": "Aplikazio mugikorra",
  "Admin Account": "Admin kontua",
  Password: "Kontrazeinu",
  "Second User": "Bigarren erabiltzailea",
  Edit: "Editatu",
  "Guest limit": "Gonbidatuen muga",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Tokiko ezarpen guztiak zure hizkuntzan oinarrituta (automatikoki) dira. Zure hizkuntza zerrendan badago, ez dago atal hau pertsonalizatu beharrik.",
  available: "erabilgarri",
  next: "gero",
  Tickets: "Sarrerak",
  Quantity: "Kantitate",
  "Promo code": "Promozio kodea",
  "Select a payment method": "Hautatu ordainketa metodoa",
  Fee: "Zerbitzu-sariak",
  Book: "Liburu",
  "All the tickets have been sold out": "Sarrerak guztiak agortu dira",
  "Choose at least one ticket": "Aukeratu gutxienez txartel bat",
  "First choose ticket": "Lehenik aukeratu txartela",
  "Please fill out your personal information.":
    "Bete zure informazio pertsonala.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "Erosketa arrakastatsua egiteko, hautatu zure ordainketa-metodoa hobetsia eta sartu promo kodea deskontatutako sarreretarako.",
  "Credit/Debit card": "Kreditu / Zordun Txartela",
  "print here.": "Inprimatu hemen.",
  "QR code for all tickets": "Sarrera guztientzako QR kodea",
  Duration: "Iraupen",
  "Full Name": "Izen osoa",
  "Ticket id": "Sarreren IDa",
  "Group id": "Taldearen IDa",
  "Choose your ticket.": "Aukeratu zure txartela.",
  "Fill out your personal information.": "Bete zure informazio pertsonala.",
  "Add the payment details.": "Gehitu ordainketa xehetasunak.",
  "To be determined": "Zehazteko",
  "You can find your e-tickets attached to the email or":
    "Zure helbide elektronikoak mezu elektronikora edo erantsitakoak aurki ditzakezu",
  "print here": "Inprimatu hemen",
  "Full name": "Izen osoa",
  "Group ID": "Taldearen IDa",
  "to Book": "liburu",
  "Unfortunately, your card has been declined":
    "Zoritxarrez, zure txartela ukatu egin da",
  "Thank you for your purchase!": "Eskerrik asko zure erosketarengatik!",
  "Find your printable e-tickets attached to the confirmation email":
    "Aurkitu zure inprimagailu elektronikoak konfirmatzeko posta elektronikoan erantsita",
  Confirm: "Berretsi",

  "Add event": "Gehitu gertaera",
  Events: "Gertaera",
  "Event details": "Ekitaldiaren xehetasunak",
  Registration: "Inskribatze",
  "Guests list": "Gonbidatuen zerrenda",
  Ticket: "Txartel",
  "General Info": "Informazio orokorra",
  "Customize the general settings of your event":
    "Pertsonalizatu zure gertaeraren ezarpen orokorrak",
  "Event Title": "Gertaeraren izenburua",
  "e.g. Birthday Party": "E.G. Urtebetetze festa",
  "All Day Event": "Egun osoan gertaera",
  Cross: "Gurutze",
  Timeline: "Presentzia",
  "Repeating event": "Ekitaldia errepikatzea",
  Location: "Kokaleku",
  "Venue name": "Aretoaren izena",
  Description: "Deskribapen",
  Image: "Irudi",
  Color: "Kolore",
  Category: "Kategoria",
  "Add your events to color categories and let your users classify them easily":
    "Gehitu zure gertaerak kolore kategorietan eta utzi erabiltzaileei erraz sailkatzea",
  "Category name": "Kategoria izena",
  "e.g. Birthdays": "E.G. Urtebetetzeak",
  Venue: "Gotoreto",
  "Where the event takes place": "Gertaera gertatzen den tokian",
  "Venue name": "Aretoaren izena",
  "Venue phone": "Lekua",
  "Venue email": "Areto posta",
  "Venue website": "Lekuaren webgunea",
  Organizer: "Hautibo",
  "Person who makes the event": "Gertaera egiten duen pertsona",
  "Organizer name": "Antolatzailearen izena",
  "Organizer phone": "Antolatzailearen telefonoa",
  "Organizer email": "Antolatzaile elektronikoa",
  "Organizer website": "Antolatzaileen webgunea",
  Save: "Aurreztu",
  Cancel: "Indargabetu",
  Import: "Inportatu",
  Past: "Iragana",
  All: "Guzti",
  Upcoming: "Hurrengo",
  Uncategorised: "Kategorizatu gabe",
  "Date Ascending": "Data goranzkoa",
  "Date Descending": "Data jaitsiera",
  "Title by A-Z": "I-Z izenburua",
  "Title by Z-A": "Izenburua Z-A",
  "There are no events for this period": "Garai honetarako ez dago gertaerarik",

  "Auto-Convert Date & Time": "Auto-Bihurketa Data eta Ordua",
  TimeZone: "Ordu eremu",
  Autodeletion: "Autodelezioa",
  "Layout Settings": "Diseinu ezarpenak",
  "Yeatly view": "Yeatly view",
  "Monthly view header": "Hileroko ikuspegi goiburua",
  "Weekly/Daily view header": "Astero / Eguneko ikuspegi goiburua",
  Acendings: "Akzioak",
  Descending: "JARDUERA",
  Standart: "Birplante",
  Silver: "Zilar",
  Retro: "Erretratu",
  Dark: "Iluna",
  Night: "Gau",
  Aubergine: "Jubisiogin",
  "List view header": "Zerrenda Ikusi goiburua",
  "Side by Side View": "Alboko ikuspegia",
  "Customize Proportions": "Proportzioak pertsonalizatu",
  "Card Margins": "Txartelaren marjinak",
  "Image opacity (%)": "Irudi opakutasuna (%)",
  "Side by Side Header": "Alboko goiburua",
  "Text Align": "Testua lerrokatzea",
  "Timeline View": "Kronologia ikuspegia",
  "Title font color": "Izenburua Letra-kolorea",
  "Desciption font color": "Descipipion Letra-kolorea",
  "Line color": "Linearen kolorea",
  "Date Font color": "Data Letra-kolorea",
  "Daily events background": "Eguneko gertaeren aurrekariak",
  Alignment: "Lerroketa",
  Vertical: "Bertikal",
  Horizontal: "Horizontala",
  "Vertical Alignment": "Lerrokatze bertikala",
  Right: "Zuzen",
  Center: "Gune",
  "Horizontal Alignment": "Lerrokatze horizontala",
  Top: "Tontor",
  Center: "Gune",
  Bottom: "Azpi",
  "Dates Circle Design": "Datak Zirkuluaren diseinua",
  "Next To The Circle": "Zirkuluaren ondoan",
  "In The Circle": "Zirkuluan",
  "Timeline Header": "Kronologia goiburua",
  Timeline: "Presentzia",
  "Show only upcoming": "Erakutsi datozenak bakarrik",
  "Order by": "Agindua",
  "Timeline Event Limit": "Kronologia gertaeren muga",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Baimendu bisitariak ekitaldia gehitzeko tokiko kalnesetara: Google, Yahoo, Outlook, iCalendar.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Baimendu bisitariak zure gertaera partekatzeko Facebook, LinkedIn, Twitter eta abar.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Gehitu bilaketa aukera zure egutegian jendeak zure gertaerei izenburua, egoitza eta abar bilatzeko.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Baimendu erabiltzaileei zure boom gertaeren egutegia inprimatu edozein data tartean.",
  "Click to apply a theme to Calendar":
    "Egin klik gai bat egutegian aplikatzeko",
  "Date container color": "Data edukiontziko kolorea",
  "Daily events background": "Eguneko gertaeren aurrekariak",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Erabili gehigarriak zure egutegietan funtzio aurreratuak instalatzeko, funtzionalagoak bihurtuz!",
  "Open Add-ons Store": "Ireki gehigarrien denda",
  Monday: "Astelehen",
  Tuesday: "Astearte",
  Wednesday: "Asteazken",
  Thursday: "Ostegun",
  Friday: "Ostiral",
  Saturday: "Larunbat",
  Sunday: "Igande",
  Ascending: "Goranzko",
  "Yearly view": "Urteko ikuspegia",
  "Show event time next to title":
    "Erakutsi gertaera-denbora izenburuaren ondoan",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Egokitu gertaeraren data eta ordua erabiltzailearen tokira beren ordu-eremuan oinarrituta.",
  "Display the time zone alongside the event date.":
    "Bistaratu ordu-eremua gertaeraren datarekin batera.",
  "Show event time next to title":
    "Erakutsi gertaera-denbora izenburuaren ondoan",
  "Time Zone": "Ordu eremu",
  "Upload Image": "Kargatu irudia",
  "Choose a Category": "Aukeratu kategoria bat",
  "Color you have chosen will not be shown as you choose category":
    "Aukeratu duzun kolorea ez da kategoria aukeratzen duzunean erakutsiko",
  Website: "Ordeinu",
  Next: "Gero",
  Save: "Aurreztu",
  "Last Name": "Abizena",
  "Personal Info": "Informazio pertsonala",
  Back: "Bizkar",
  "This field is required": "Eremu hau derrigorrezkoa da",
  "Your event has been submitted": "Zure gertaera aurkeztu da",
  "Enter a location": "Sartu kokapen bat",
  "Display the time zone alongside the event date.":
    "Bistaratu ordu-eremua gertaeraren datarekin batera.",
  Home: "Etxe",
  "Side By Side Event Limit": "Alboko gertaeren mugaren arabera",
  "Mobille App": "Mobille aplikazioa",
  category: "kategoria",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Jarrai ezazu zure ordutegia erraz zure Facebook-eko gertaerak zure egutegira inportatuz.",
  "Synchronized Pages": "Sinkronizatutako orrialdeak",
  "There are no synchronized pages": "Ez dago orrialde sinkronizaturik",
  "Choose page": "Aukeratu orria",
  "You have no events": "Ez duzu gertaerarik",
};
export default eu;
