let fr = {
  Categories: "Catégories",
  "Share this event": "Partagez cet événement",
  Language: "La langue",
  "Show Time Zone": "Afficher le fuseau horaire",
  "Custom Local Settings": "Paramètres locaux personnalisés",
  "Add and showcase events on your site using a beautiful calendar.":
    "Ajoutez et présentez des événements sur votre site en utilisant un beau calendrier . ",
  "Week Days": "Jours de la semaine",
  "Manage Events": "Gérer les événements",
  General: "Général",
  "Layout Picker": "Layout Picker",
  Month: "Mois",
  Monthly: "Mensuel",
  Week: "La semaine",
  Weekly: "Hebdomadaire",
  Day: "Journée",
  Daily: "Du quotidien",
  Agenda: "Ordre du jour",
  "Navigation Buttons": "Boutons de navigation",
  Today: "Aujourd'hui",
  "Week numbers": "Numéros de semaine",
  "Include Weekends": "Inclure les week-ends",
  "All-day": "Toute la journée",
  "All Day": "Toute la journée",
  Label: "Étiquette",
  "Fit to Height": "Ajuster à la hauteur",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Pour définir les proportions de l'application, désactivez manuellement cette option et redimensionnez le calendrier dans l'éditeur.",
  "Default Layout": "Mise en page par défaut",
  "Monthly view": "Vue mensuelle",
  "Weekly and Daily view": "Vue hebdomadaire et quotidienne",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Vous pouvez offrir aux visiteurs une expérience plus cohérente en affichant le même nombre de semaines (6) à la fois.",
  "Fixed Weekly Layout": "Mise en page hebdomadaire fixe",
  back: "retour",
  Row: "Rangée",
  "Hours in Weekly View": "Heures en affichage hebdomadaire",
  "Hours in Daily View": "Heures en affichage quotidien",
  Start: "Début",
  End: "Fin",
  "At This Hour": "À cette heure",
  Button: "Bouton",
  Buttons: "Boutons",
  Sunday: "Dimanche",
  Monday: "Lundi",
  Tuesday: "Mardi",
  Wednesday: "Mercredi",
  Thursday: "Mardi",
  Friday: "Vendredi",
  Saturday: "Samedi",
  "Default Date": "Date par défaut",
  year: "année",
  month: "mois",
  mo: "mois",
  days: "journées",
  ago: "depuis",
  ahead: "devant",
  Yesterday: "Hier",
  Tomorrow: "Demain",
  Custom: "Douane",
  "Set Daily Rows Limit": "Définir la limite quotidienne de lignes",
  "Set Proportions": "Définir les proportions",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    " Autoriser un visiteur à ajouter un événement aux journaux locaux, Google, Yahoo, Outlook, ICalendar.",
  Container: "Récipient",
  Background: "Contexte",
  "Container Background": "Contexte du conteneur",
  "Container Borders": "Frontières de conteneurs",
  Calendar: "Calendrier",
  "Event Info Tooltip": "Info sur l'événement",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Lorsque les personnes survolent un événement, elles voient toutes les informations à ce sujet dans une info-bulle.",
  "Event Info Window": "Fenêtre d'informations sur l'événement",
  "This is the full information window that opens when someone clicks on the event.":
    "Il s'agit de la fenêtre d'informations complètes qui s'ouvre lorsque quelqu'un clique sur l'événement.",
  "Use Gradient": "Utiliser le dégradé",
  Vertical: "Verticale",
  Horizontal: "Horizontal",
  First: "Premier",
  Second: "Seconde",
  diagonal: "diagonale",
  Radial: "Radial",
  "Select option": "Choisir une option",
  Solid: "Solide",
  Dotted: "À pois",
  Dashed: "Dashed",
  Double: "Doub le",
  "Border Radius": "Rayon de la frontière",
  Padding: "Rembourrage",
  "Date Header": "Date Header",
  "Event Default Color": "Couleur par défaut de l'événement",
  "Days of Week": "Jours de la semaine",
  "Days of Week Background": "Contexte des jours de la semaine",
  Date: "Date",
  "Event Title": "Titre de lévénement",
  "Highlight today": "Mettez en valeur aujourd'hui",
  "Highlight Color": "Couleur de surbrillance",
  Hide: "Cacher",
  "Calendar Border Color": "Couleur de la bordure du calendrier",
  "Calendar Border Width": "Largeur de la bordure du calendrier",
  "Calendar Border Style": "Style de bordure de calendrier",
  "Font Color": "Couleur de la police",
  "Event Background": "Contexte de l'événement",
  "Card Date Color": "Couleur de la date de la carte",
  "Title Font": "Police de titre",
  "Date Font": "Date Police",
  "Description Font": "Description Font",
  "Button Background": "Arrière-plan du bouton",
  "Button Text": "Texte du bouton",
  "Border Color": "Couleur de la bordure",
  "Border Width": "Largeur de la bordure",
  "Border Type": "Type de bordure",
  Title: "Titre",
  Description: "La description",
  "Background Color": "Couleur de fond",
  Divider: "Diviseur",
  "Event Details Font": " Police des détails de l'événement",
  "Website Link Color": "Couleur du lien de site Web",
  "Developer Info": "Info développeur",
  "User Guide": "Mode d'emploi",
  "Support e-mail": "Support e-mail",
  "Our Website": "Notre site Web",
  "App Review": "App Review",
  "Enjoying App? Leave us a review in the App Market.":
    "Apprécier App? Laissez-nous un commentaire sur l'App Market.",
  "Review Us": "Revoir nous",
  "Connect With Us": "Connecte-toi avec nous",
  "What's your email?": "Quel est ton e-mail?",
  "Invalid email address!": "Adresse e-mail invalide!",
  Comments: "Commentaires",
  "We'd love to hear from you. Send us a message.":
    "Nous aimerions beaucoup avoir de vos nouvelles. Envoyez-nous un message.",
  "Message must be at least 5 characters long":
    "Le message doit comporter au moins 5 caractères",
  Send: "Envoyer",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Si vous souhaitez autoriser l'utilisateur à basculer entre les vues de l'agenda, activez cette option et choisissez les vues à afficher.",
  Main: "Principal",
  Localize: "Localiser",
  Settings: "Réglages",
  Layouts: "Agencement",
  Advanced: "Avancé",
  Design: "Conception",
  Support: "Soutien",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Tous les paramètres locaux sont (automatiquement) basés sur votre langue. Si votre langue figure sur la liste, il n'est pas nécessaire de personnaliser cette section.",
  "Date Format": "Format de date",
  "Time Format": "Format de l'heure",
  "Text Direction": "Direction du texte",
  "Left to Right": "De gauche à droite",
  "Right to Left": "De droite à gauche",
  "Week Starts On": "La semaine commence",
  "Agenda Style": "Style de l'ordre du jour",
  Classic: "Classique",
  Modern: "Moderne",
  "Agenda Header": "En-tête d'agenda",
  "Upcoming Events": "Évènements à venir",
  "Agenda Event Limit": "Limite d'événements de l'agenda",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Mettez à niveau maintenant et obtenez beaucoup plus de fonctionnalités et profitez pleinement de votre application!",
  "Upgrade Now": "Mettre à jour maintenant",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Organiser des événements qui durent toute la journée? Cela vous permet de les afficher sur votre calendrier.",
  "24 hours": "24 heures",
  Sat: "Sam",
  Sun: "Dim",
  Mon: "Lun",
  Default: "Défaut",
  "Select custom design style for your calendar.":
    "Sélectionnez un style de conception personnalisé pour votre calendrier.",
  Style: "Style",
  "Styles and Colors": "Styles et Couleurs",
  "Calendar Name": "Nom du calendrier",
  "Write your Calendar name here": "Écrivez votre nom de calendrier ici",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Ce n'est pas visible pour vos utilisateurs. Définissez des noms pour différencier vos calendriers lorsque vous utilisez la fonction Synchronisation du calendrier Boom.",
  "General Info": "Informations générales",
  Venue: "Lieu",
  Organizer: "Organisateur",
  Search: "Chercher",
  "Add to": "Ajouter à",
  calendar: "calendrier",
  "Copy event URL": "Copier l'URL de l'événement",
  "Copied!": "Kopieare!",
  "Add & Share": "Ajouter et partager",
  Map: "Carte",
  "Calendar view": "Vue du calendrier",
  "Add Event": "Ajouter un évènement",
  Uncategorised: "Non catégorisé",
  More: "Plus",
  Less: "Moins",
  Register: "S'inscrire",
  Card: "Carte",
  Guests: "Invités",
  unlimited: "illimité",
  "Show more": "Montre plus",
  "Enable Search": "Activer la recherche",
  "+ Add Event": "+ Ajouter un événement",
  "Manage and Sync": "Gérer et synchroniser",
  "Show event details as...": "Afficher les détails de l'événement comme .",
  Tooltip: "Info-bulle",
  Popup: "Boîte d'info",
  None: "Aucun",
  "Show Category": "Afficher la catégorie",
  "Header Align": "Alignement d'en-tête",
  "Show Time": "Afficher l'heure",
  "Hours in Weekly/Daily View": "Heures en vue hebdomadaire / quotidienne",
  "Share Events": "Partager des événements",
  Shadow: "Ombre",
  "Inner Padding": "Rembourrage intérieur",
  Text: "Texte",
  "Active Button Border": "Bordure de bouton actif",
  "Light Mode": "Mode lumière",
  "Event Text Color": "Couleur du texte de l'événement",
  Dates: "Rendez-vous",
  Skeleton: "Squelette",
  "Skeleton Color": "Couleur du squelette",
  Width: "Largeur",
  "Skeleton Style": "Style squelette",
  Color: "Couleur",
  "Section Titles": "Titres de section",
  "Section Content": "Contenu de la section",
  Header: "Entête",
  Standard: "la norme",
  Retro: "Rétro",
  Silver: "Argent",
  Night: "Nuit",
  Dark: "Sombre",
  Aubergine: "Aubergine",
  "Map Header": "En-tête de carte",
  "Show Title in mobile": "Afficher le titre sur mobile",
  "Card View": "Vue de la carte",
  "Card background color": "Couleur d'arrière-plan de la carte",
  "Title font": "Police de titre",
  "Desciption font": "Police de description",
  "Section font": "Section font",
  "Section divider color": "Couleur du séparateur de section",
  "Add event": "Ajouter un évènement",
  "All Day Event": "Événement dune journée",
  Location: "Emplacement",
  "Choose a category": "Choisissez une catégorie",
  "Venue name": "Nom de la place",
  "Venue phone": "Téléphone de la salle",
  "Venue email": "E-mail du lieu",
  "Venue website": "Site web du lieu",
  "Organizer name": "Nom de lorganisateur",
  "Organizer phone": "Téléphone de lorganisateur",
  "Organizer email": "E-mail de lorganisateur",
  "Organizer website": "Site Web de lorganisateur",
  "Personal info": "Informations personnelles",
  "First name": "Prénom",
  "Last name": "Nom de famille",
  "Email Address": "Adresse e-mail",
  "Additional Notes": "Notes complémentaires",
  Back: "Retour",
  Save: "Sauvegarder",
  Next: "Suivant",
  "Your event has been submitted": "Votre événement a été soumis",
  "Event submittion has been failed": "La soumission de lévénement a échoué",
  "e.g. Birthday Party": "par exemple. Fête danniversaire",
  "First Name": "Prénom",
  "Last Name": "Nom de famille",
  "Phone Number": "Numéro de téléphone",
  Address: "Adresse",
  "Your comments": "Vos commentaires",
  "How many guests?": "Combien d'invités?",
  "Anything else we need to know?":
    "Y a-t-il autre chose que nous devons savoir?",
  "Guests:": "Invités:",
  Submit: "Soumettre",
  "Go to Calendar": "Aller au calendrier",
  "Registration completed successfully!": "Inscription terminée avec succès!",
  "Please check your registered email address":
    "Veuillez vérifier votre adresse e-mail enregistrée",
  "Add to Calendar": "Ajouter au calendrier",
  "Share this Event": "Partagez cet événement",
  "Sorry something went wrong": "מצטערים, משהו השתבש",
  "Back to registration": "Retour à l'inscription",
  "Date & Location": "Date et lieu",
  "Date & Time": "Date et heure",
  home: "domicile",
  "Header align": "Aligner l'en-tête",
  Footer: "Bas de page",
  "Categories Filter": "catégories Filtre",
  "Show only upcoming": "Afficher uniquement à venir",
  "Card(s) in a row": "Carte (s) d'affilée",
  "Space between cards": "Espace entre les cartes",
  "Shown events limit": "Limite d'événements affichés",
  "Style 1": "Style 1",
  "Style 2": "Style 2",
  "Style 3": "Style 3",
  "Style 4": "Style 4",
  "Buttons & Links": "Boutons et liens",
  "Button corner radius": "Rayon du coin du bouton",
  "Buttons font": "Police des boutons",
  "Buttons background": "Fond de boutons",
  "Get notified by Email": "Recevoir une notification par e-mail",
  "Review events": "Examiner les événements",
  "Click on date": "Cliquez sur la date",
  "Add Event button": "Bouton Ajouter un événement",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "La synchronisation du calendrier vous permet d'intégrer vos événements et sessions à votre calendrier Boom.",
  connect: "relier",
  "Synchronized Calendars": "Calendriers synchronisés",
  "Import events": "Événements d'importation",
  Disconnect: "Déconnecter",
  "Choose calendar": "Choisissez le calendrier",
  "Monitor your Wix events through the sync feature":
    "Surveillez vos événements Wix grâce à la fonction de synchronisation",
  "Connect all your Boom calendars available on your website":
    "Connectez tous vos calendriers Boom disponibles sur votre site Web",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Planifiez, rejoignez et gérez les réunions Zoom directement via notre calendrier Boom.",
  "Monitor your Event Brite events through the Event Brite sync feature.":
    "Surveillez vos événements Event Brite grâce à la fonction de synchronisation Event Brite",
  Email: "E-mail",
  "Add-ons": "Modules complémentaires",
  "Receive notification emails as soon as users add events to your calendar.":
    "Recevez des courriels de notification dès que les utilisateurs ajoutent des événements à votre calendrier.",
  "Enable + button on the calendar header":
    "Activer + bouton sur l'en-tête du calendrier",
  "Accept or decline events added by customers before making them public.":
    "Acceptez ou déclinez des événements ajoutés par les clients avant de les rendre publics.",
  "Switch Add Event": "Switch Ajouter un événement",
  "Enable your browser cookies to connect to your account.":
    "Activez vos cookies de navigateur de vous connecter à votre compte.",
  "Learn more": "Apprendre encore plus",
  "Print Button": "Bouton d'impression",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Permettez à vos utilisateurs d'imprimer votre calendrier d'événement Boom dans n'importe quelle plage de date.",
  "Show Title on mobile": "Afficher le titre sur mobile",
  "Show Skeleton on mobile": "Montrer le squelette sur mobile",
  "Start 7-day Business trial": "Commencez votre essai commercial de 7 jours",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Profitez de toutes les fonctionnalités illimitées, telles que vendre des billets, une inscription, des add-ons des événements de visiteur.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Veuillez noter: à la fin de la période d'essai, vous serez retourné dans votre plan d'abonnement existant.",
  "Not Now": "Pas maintenant",
  "Start free trial": "Commencer l'essai gratuit",
  "Congrats!": "Félicitations!",
  "Your 7-day Business trial has been successfully activated.":
    "Votre essai commercial de 7 jours a été activé avec succès.",
  Done: "Terminé",
  "Title font color": "Titre Couleur de la police",
  "Desciption font color": "Description Couleur de la police",
  "Section font color": "Couleur de la police",
  "Card Header": "En-tête de carte",
  Category: "Catégorie",
  "Display at the": "Afficher",
  top: "Haut",
  bottom: "bas",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Présentez le filtre de catégorie en haut ou au bas du calendrier.Les paramètres s'appliquent uniquement aux vues de l'ordre du jour et de la carte",
  "Processing your events": "Traitement de vos événements",
  "Search for events": "Recherche d'événements",
  "There are no events added": "Il n'y a aucun événement ajouté",
  "Location: To be determined": "Lieu: à déterminer",
  "No events for selected date": "Aucun événement pour la date sélectionnée",
  Uncategorized: "Non classé",
  "Edit event": "Modifier l'événement",
  "Edit original event": "Modifier l'événement original",
  "Copy event": "Copier l'événement",
  "Copy as new event": "Copier comme un nouvel événement",
  "Delete event": "Supprimer l'événement",
  "Stop repeating on this date": "Arrêtez de répéter à cette date",
  "Exclude this date": "Exclure cette date",
  "Location is going to be announced": "L'emplacement va être annoncé",
  "Fill your personal information": "Remplissez vos informations personnelles",
  "Check Box": "Cocher",
  "Single Choice": "Choix unique",
  Option: "Option",
  "Share Event": "Événement de partage",
  "Oops! Something went wrong": "Oops!Quelque chose s'est mal passé",
  "We are sorry this event has already taken place":
    "Nous sommes désolés que cet événement a déjà eu lieu",
  "Back to calendar": "Retour au calendrier",
  "This field is required": "Ce champ est requis",
  Phone: "Téléphoner",
  "Number field": "Champ de numéro",
  "Please provide a valid email": "Veuillez fournir un e-mail valide",
  "Select at least one option": "Sélectionnez au moins une option",
  "Sold Out": "Épuisé",
  "Tickets are available": "Les billets sont disponibles",
  "Sales End": "Fin de vente",
  "Buy tickets": "Acheter des billets",
  "Availible from": "Disponible depuis",
  "You will soon receive a confirmation message of successful registration to your email address. You can also check your order details below.":
    "Vous recevrez bientôt un message de confirmation de l'inscription réussie à votre adresse e-mail.Vous pouvez également vérifier les détails de votre commande ci-dessous.",
  "Go to Orders": "Aller aux commandes",
  "Go to Details": "Aller aux détails",
  "Group ticket": "Billet de groupe",
  Name: "Nom",
  Price: "Prix",
  "Order by": "Commandé par",
  "Order ID": "numéro de commande",
  Applied: "Appliqué",
  Fees: "Frais",
  "Enter promo code": "Saisir le code promotionnel",
  Apply: "Appliquer",
  "Promo Code": "Code promo",
  Cash: "En espèces",
  "You can find your e-tickets attached to your email or download them":
    "Vous pouvez trouver vos creux électroniques joints à votre e-mail ou les télécharger",
  here: "ici",
  Time: "Temps",
  "Invalid promo code": "Code promotionnel non valide",
  "Credit card": "Carte de crédit",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Vous recevrez bientôt un message de confirmation de l'inscription réussie à votre adresse e-mail.",
  "You can also check your order details below.":
    "Vous pouvez également vérifier les détails de votre commande ci-dessous.",
  at: "à",
  Buy: "Acheter",
  Donation: "Don",
  "Enter price": "Entreprise",
  Choose: "Choisir",
  Chosen: "Choisi",
  "Choose your plan": "Choisissez votre plan",
  week: "la semaine",
  wk: "la semaine",
  "Choose plan cycle": "Choisissez le cycle du plan",
  months: "mois",
  years: "années",
  weeks: "semaines",
  "Copy Event Url": "Copier l'URL de l'événement",
  "You can find your e-tickets attached to your email or print them":
    "Vous pouvez trouver vos creux électroniques joints à votre e-mail ou les imprimer",
  "Guest Info": "Informations invitées",
  "Ticket Info": "Informations sur les billets",
  "Ticket name": "Nom de billet",
  "Ticket price": "Prix ​​du billet",
  "Ticket ID": "ID de billets",
  "If you have any questions contact to organizer":
    "Si vous avez des questions, contactez l'organisateur",
  "As soon as event ends": "Dès que l'événement se termine",
  "1 day after event ends": "1 jour après l'événement se termine",
  "7 days after event ends": "7 jours après la fin de l'événement",
  "14 days after event ends": "14 jours après la fin de l'événement",
  "30 days after event ends": "30 jours après la fin de l'événement",
  Menu: "Menu",
  "No event for selected date": "Aucun événement pour la date sélectionnée",
  view: "voir",
  List: "Liste",
  Year: "Année",
  "Yearly Style": "Style annuel",
  Upgrade: "Améliorer",
  "There are no events": "Il n'y a pas d'événements",
  Ascending: "Ascendant",
  Descending: "Descendant",
  "Open Add-ons Store": "Ouvrir la boutique de modules complémentaires",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Utilisez les modules complémentaires pour installer des fonctionnalités avancées sur vos calendriers et les rendre plus fonctionnels !",
  Autotranslation: "Autotranslation",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Une fois activé, votre widget de calendrier sera traduit en fonction de la langue du site Web.* Notez que tant que le titre du calendrier et les descriptions sont des textes saisis, ils ne peuvent pas être traduits.",
  "Note on mobile": "Note sur mobile",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Éteignez ou changez le texte de la barre «Aucun événement» sur la version mobile du calendrier",
  Autodeletion: "Autodélétion",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "L'activation de l'option supprimera automatiquement vos événements passés du calendrier.",
  "This does not apply to repeating events!":
    "Cela ne s'applique pas aux événements de répétition!",
  "Notify event creators about the guest":
    "Informer les utilisateurs de l'invité",
  "Send event creators notification emails as soon as guests register for their events":
    "Envoyez des e-mails de notification aux créateurs d'événements dès que les invités s'inscrivent à leurs événements",
  "List View Type": "Type de vue de liste",
  "Description font": "Police de description",
  Connect: "relier",
  "You have no events": "Vous n'avez aucun événement",
  Synchronize: "Synchroniser",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Google Calendar Sync vous permet d'intégrer vos événements et vos sessions avec votre calendrier de boom.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "La synchronisation du calendrier Outlook vous permet d'intégrer vos événements et sessions à votre calendrier Boom.",
  "Your message has been sent successfully!":
    "Votre message a été envoyé avec succès!",
  "There are no synchronized calendars":
    "Il n'y a pas de calendriers synchronisés",
  "to view more than 7 events": "pour voir plus de 7 événements",
  "Mobile app": "נייד App.",
  "Admin Account": "Compte administrateur",
  Password: "סיסמה",
  "Second User": "Deuxième utilisateur",
  Edit: "Éditer",
  "Guest limit": "Limite d'invité",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Tous les paramètres locaux sont (automatiquement) en fonction de votre langue.Si votre langue figure sur la liste, il n'est pas nécessaire de personnaliser cette section.",
  available: "disponible",
  next: "suivante",
  Tickets: "Des billets",
  Quantity: "Quantité",
  "Promo code": "Code promo",
  "Select a payment method": "Choisissez une méthode de paiement",
  Fee: "Frais",
  Book: "Livre",
  "All the tickets have been sold out": "Tous les billets ont été vendus",
  "Choose at least one ticket": "Choisissez au moins un billet",
  "First choose ticket": "Premier billet de choix",
  "Please fill out your personal information.":
    "S'il vous plaît remplir vos informations personnelles.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "Pour effectuer un achat réussi, veuillez sélectionner votre mode de paiement préféré et saisir le code promotionnel pour les billets à prix réduit.",
  "Choose payment method": "Choisissez le mode de paiement",
  "Credit/Debit card": "Carte de crédit / débit",
  "print here.": "Imprimez ici.",
  "QR code for all tickets": "QR code pour tous les billets",
  Duration: "Durée",
  "Full Name": "Nom et prénom",
  Total: "Le total",
  "Ticket id": "ID de billets",
  "Group id": "ID de groupe",
  "Choose your ticket.": "Choisissez votre billet.",
  "Fill out your personal information.":
    "Remplissez vos informations personnelles.",
  "Add the payment details.": "Ajouter les détails du paiement.",
  "To be determined": "Être déterminé",
  Pay: "Payer",
  Free: "Libérer",
  "You can find your e-tickets attached to the email or":
    "Vous pouvez trouver vos billets électroniques attachés à l'e-mail ou",
  "print here": "imprimer ici",
  "Full name": "Nom et prénom",
  "Group ID": "ID de groupe",
  "to Book": "réserver",
  "Unfortunately, your card has been declined":
    "Malheureusement, votre carte a été refusée",
  "Thank you for your purchase!": "Merci pour votre achat!",
  "Find your printable e-tickets attached to the confirmation email":
    "Trouvez vos couvertures électroniques imprimables jointes à l'e-mail de confirmation",
  Confirm: "Confirmer",

  "Add event": "Ajouter un évènement",
  Events: "Événements",
  "Event details": "Détails de l'évènement",
  Registration: "Inscription",
  "Guests list": "Liste des invités",
  Ticket: "Billet",
  "General Info": "Informations générales",
  "Customize the general settings of your event":
    "Personnalisez les paramètres généraux de votre événement",
  "Event Title": "Titre de l'événement",
  "e.g. Birthday Party": "par exemple. Fête d'anniversaire",
  "All Day Event": "Événement d'une journée",
  Cross: "Croix",
  Timeline: "Calendrier",
  "Repeating event": "Événement répétitif",
  Location: "Emplacement",
  "Venue name": "Nom de la place",
  Description: "Description",
  Image: "Image",
  Color: "Couleur",
  Category: "Catégorie",
  "Add your events to color categories and let your users classify them easily":
    "Ajoutez vos événements aux catégories de couleurs et laissez vos utilisateurs les classer facilement",
  "Category name": "Nom de catégorie",
  "e.g. Birthdays": "par exemple. Anniversaires",
  Venue: "Lieu",
  "Where the event takes place": "Où l'événement se déroule",
  "Venue name": "Nom de la place",
  "Venue phone": "Téléphone de lieu",
  "Venue email": "E-mail de lieu",
  "Venue website": "Site Web de lieu",
  Organizer: "Organisateur",
  "Person who makes the event": "Personne qui fait l'événement",
  "Organizer name": "Nom de l'organisateur",
  "Organizer phone": "Téléphone de l'organisateur",
  "Organizer email": "E-mail de l'organisateur",
  "Organizer website": "Site Web de l'organisateur",
  Save: "Sauvegarder",
  Cancel: "Annuler",
  Import: "Importer",
  Past: "Passé",
  All: "Tous",
  Upcoming: "A venir",
  Uncategorised: "Non catégorisé",
  "Date Ascending": "Date ascendante",
  "Date Descending": "Date descendante",
  "Title by A-Z": "Titre par A-Z",
  "Title by Z-A": "Titre par Z-A",
  "There are no events for this period":
    "Il n'y a pas d'événements pour cette période",

  "Auto-Convert Date & Time": "Date et heure de converti automatique",
  TimeZone: "Fuseau horaire",
  Autodeletion: "Autodélétion",
  "Layout Settings": "Paramètres de mise en page",
  "Yeatly view": "Voir",
  "Monthly view header": "En-tête de vue mensuelle",
  "Weekly/Daily view header": "En-tête de vue hebdomadaire / quotidien",
  Acendings: "Acénérations",
  Descending: "Descendant",
  Standart: "Standart",
  Silver: "Argent",
  Retro: "Rétro",
  Dark: "Sombre",
  Night: "Nuit",
  Aubergine: "Aubergine",
  "List view header": "En-tête de vue de la liste",
  "Side by Side View": "Vue côte à côte",
  "Customize Proportions": "Personnaliser les proportions",
  "Card Margins": "Marges de carte",
  "Image opacity (%)": "Opacité de l'image (%)",
  "Side by Side Header": "Tête côte à côte",
  "Text Align": "Aligner le texte",
  "Timeline View": "Vue de chronologie",
  "Title font color": "Couleur de police de titre",
  "Desciption font color": "Couleur de police de descriptions",
  "Line color": "Couleur de la ligne",
  "Date Font color": "Couleur de police de date",
  "Daily events background": "Contexte des événements quotidiens",
  Alignment: "Alignement",
  Vertical: "Vertical",
  Horizontal: "Horizontal",
  "Vertical Alignment": "Alignement vertical",
  Right: "Droite",
  Center: "Centre",
  "Horizontal Alignment": "Alignement horizontal",
  Top: "Haut",
  Center: "Centre",
  Bottom: "Bas",
  "Dates Circle Design": "Dates Circle Design",
  "Next To The Circle": "À côté du cercle",
  "In The Circle": "Dans le cercle",
  "Timeline Header": "En-tête de chronologie",
  Timeline: "Calendrier",
  "Show only upcoming": "Ne montre que à venir",
  "Order by": "Commandé par",
  "Timeline Event Limit": "Limite de l'événement de chronologie",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Autoriser le visiteur à ajouter un événement aux Calneds locaux: Google, Yahoo, Outlook, ICalidendar.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Autoriser le visiteur à partager votre événement sur Facebook, LinkedIn, Twitter et etc.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Ajoutez une option de recherche sur votre calendrier pour permettre aux gens de rechercher vos événements par titre, lieu, etc.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Permettez à vos utilisateurs d'imprimer votre calendrier d'événements de boom dans n'importe quelle plage de dates.",
  "Click to apply a theme to Calendar":
    "Cliquez pour appliquer un thème au calendrier",
  "Date container color": "Couleur de récipient de date",
  "Daily events background": "Contexte des événements quotidiens",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Utilisez les modules complémentaires pour installer des fonctionnalités avancées sur vos calendriers, ce qui les rend plus fonctionnels!",
  "Open Add-ons Store": "Store de compléments ouverts",
  Monday: "Lundi",
  Tuesday: "Mardi",
  Wednesday: "Mercredi",
  Thursday: "Jeudi",
  Friday: "Vendredi",
  Saturday: "Samedi",
  Sunday: "Dimanche",
  "Yearly view": "Vue annuelle",
  Ascending: "Nouseva",
  "Show event time next to title":
    "Afficher l'heure de l'événement à côté du titre",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Ajustez la date et l'heure de l'événement à l'heure locale de l'utilisateur en fonction de son fuseau horaire.",
  "Display the time zone alongside the event date.":
    "Affichez le fuseau horaire le long de la date de l'événement.",
  "Show event time next to title":
    "Afficher l'heure de l'événement à côté du titre",
  "Time Zone": "Fuseau horaire",
  "Upload Image": "Télécharger l'image",
  "Choose a Category": "Choisissez une catégorie",
  "Color you have chosen will not be shown as you choose category":
    "La couleur que vous avez choisie ne sera pas affichée lorsque vous choisissez la catégorie",
  Website: "Site Internet",
  Next: "Suivant",
  Save: "Sauvegarder",
  "Last Name": "Nom de famille",
  "Personal Info": "Informations personnelles",
  Back: "Dos",
  "This field is required": "Ce champ est obligatoire",
  "Your event has been submitted": "Votre événement a été soumis",
  "Enter a location": "Entrez un emplacement",
  "Display the time zone alongside the event date.":
    "Affichez le fuseau horaire le long de la date de l'événement.",
  Home: "Maison",
  "Side By Side Event Limit": "Limite d'événement côte à côte",
  "Mobille App": "Application Mobille",
  category: "catégorie",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Gardez une trace de votre emploi du temps facilement en important vos événements Facebook dans votre calendrier.",
  "Synchronized Pages": "Pages synchronisées",
  "There are no synchronized pages": "Il n'y a pas de pages synchronisées",
  "Choose page": "Choisir la page",
  "You have no events": "Vous n'avez pas d'événements",
};
export default fr;
