let he = {
  Categories: "קטגוריות",
  "Share this event": "שתפו אירוע זה",
  Language: "שפה",
  "Show Time Zone": "הצג אזור זמן",
  "Custom Local Settings": "הגדרות מקומיות בהתאמה אישית",
  "Add and showcase events on your site using a beautiful calendar.":
    "הוסף והציג אירועים באתר שלך באמצעות לוח שנה יפה . ",
  "Week Days": "ימי חול",
  "Manage Events": "נהל אירועים",
  General: "כללי",
  "Layout Picker": "בורר פריסה",
  Month: "חודש",
  Monthly: "חודשי",
  Week: "שבוע",
  Weekly: "שבועי",
  Day: "יום",
  Daily: "יומי",
  Agenda: "סדר יום",
  "Navigation Buttons": "כפתורי ניווט",
  "Week numbers": "מספרי שבוע",
  "Include Weekends": "כלול סופי שבוע",
  "All-day": "כל היום",
  "All Day": "כל היום",
  Label: "תווית",
  "Fit to Height": "מתאים לגובה",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "כדי להגדיר פרופורציות של אפליקציות בטל באופן ידני אפשרות זו ולשנות את גודל לוח השנה בעורך. ",
  "Default Layout": "מערך ברירת מחדל",
  "Monthly view": "תצוגה חודשית",
  "Weekly and Daily view": "תצוגה שבועית ויומית",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "אתה יכול להעניק למבקרים חוויה עקבית יותר על ידי הצגת מספר זהה של שבועות ( 6) בכל פעם.",
  "Fixed Weekly Layout": "מתווה שבועי קבוע",
  back: " בחזרה ",
  Row: "שורה",
  "Hours in Weekly View": "שעות בתצוגה שבועית",
  "Hours in Daily View": "שעות בתצוגה יומית",
  Start: "הַתחָלָה",
  End: "סוֹף",
  "At This Hour": "בשעה זו",
  Button: "כפתור",
  Buttons: "כפתורים",
  Sunday: "יום ראשון",
  Monday: "יום שני",
  Tuesday: "יום שלישי",
  Wednesday: "יום רביעי",
  Thursday: "יום חמישי",
  Friday: "יום שישי",
  Saturday: "יום שבת",
  "Default Date": "תאריך ברירת מחדל",
  year: " שנה ",
  month: " חודש ",
  mo: " חודש ",
  days: " ימים ",
  ago: " לפני ",
  ahead: " קדימה ",
  Yesterday: "אתמול",
  Today: "היום",
  Tomorrow: "מחר",
  Custom: "המותאם אישית",
  "Set Daily Rows Limit": "הגדר מגבלת שורות יומיות",
  "Set Proportions": "קבע פרופורציות",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "אפשר המבקר להוסיף האירוע המקומי Calnedars , Google, Yahoo, Outlook, iCalendar . ",
  Container: "מיכל",
  Background: "רקע כללי",
  "Container Background": "רקע מיכל",
  "Container Borders": "גבולות מיכל",
  Calendar: "לוח שנה",
  "Event Info Tooltip": "הסבר הכלים למידע על אירועים",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "כשאנשים מרחפים מעל אירוע הם יראו את כל המידע על זה בסמל הכלים. ",
  "Event Info Window": "חלון פרטי אירוע",
  "This is the full information window that opens when someone clicks on the event.":
    "זהו חלון המידע המלא שנפתח כשמישהו לוחץ על האירוע. ",
  "Use Gradient": "השתמש בשיפוע",
  Vertical: "אנכי",
  Horizontal: "אופקי",
  First: "ראשון",
  Second: "שני",
  diagonal: " אלכסון ",
  Radial: "רדיאלי",
  "Select option": "בחר אפשרות",
  Solid: "מוצק",
  Dotted: "מנוקד",
  Dashed: "מקווקו",
  Double: "כפול",
  "Border Radius": "רדיוס הגבול",
  Padding: "ריפוד",
  "Date Header": "כותרת תאריך",
  "Event Default Color": "צבע ברירת מחדל לאירוע",
  "Days of Week": "ימי השבוע",
  "Days of Week Background": "רקע ימי השבוע",
  Date: "תַאֲרִיך",
  "Event Title": "כותרת האירוע",
  "Highlight today": "הדגש היום",
  "Highlight Color": "הדגש צבע",
  Hide: "להתחבא",
  "Calendar Border Color": "צבע גבול לוח שנה",
  "Calendar Border Width": "רוחב גבול לוח השנה",
  "Calendar Border Style": "סגנון גבול לוח שנה",
  "Font Color": "צבע גופן",
  "Event Background": "רקע אירוע",
  "Card Date Color": "צבע תאריך כרטיס",
  "Title Font": "גופן כותרת",
  "Date Font": "גופן תאריך",
  "Description Font": "גופן תיאור",
  "Button Background": "רקע כפתור",
  "Button Text": "טקסט כפתור",
  "Border Color": "צבע גבול",
  "Border Width": "רוחב גבול",
  "Border Type": "סוג גבול",
  Title: "כותרת",
  Description: "תיאור",
  "Background Color": "צבע רקע",
  Divider: "מחיצה",
  "Event Details Font": "גופן פרטי האירוע",
  "Website Link Color": "צבע קישור לאתר",
  "Developer Info": "מידע על מפתחים",
  "User Guide": "מדריך למשתמש",
  "Support e-mail": "תמיכה בדואר אלקטרוני",
  "Our Website": "האתר שלנו",
  "App Review": "סקירת אפליקציות",
  "Enjoying App? Leave us a review in the App Market.":
    "נהנה מאפליקציה? השאר לנו ביקורת בשוק האפליקציות. ",
  "Review Us": "סקור אותנו",
  "Connect With Us": "התחבר אלינו",
  "What's your email?": "מה המייל שלך?",
  "Invalid email address!": 'כתובת דוא"ל לא חוקית!',
  Comments: "הערות",
  "We'd love to hear from you. Send us a message.":
    "נשמח לשמוע ממך. שלח לנו הודעה. ",
  "Message must be at least 5 characters long":
    "ההודעה חייבת להיות לפחות 5 תווים",
  Send: "שלח",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "אם ברצונך לאפשר למשתמש לעבור בין תצוגות לוח השנה, הפעל אפשרות זו ובחר את התצוגות שברצונך להציג. ",
  Main: "עיקרי",
  Localize: "לוקליזציה",
  Settings: "הגדרות",
  Layouts: "פריסות",
  Advanced: "מתקדם",
  Design: "עיצוב",
  Support: "תמיכה",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "כל ההגדרות המקומיות מבוססות (אוטומטית) על פי שפתך. אם השפה שלך ברשימה, אין צורך להתאים אישית את החלק הזה.",
  "Date Format": "פורמט תאריך",
  "Time Format": "פורמט זמן",
  "Text Direction": "כיוון טקסט",
  "Left to Right": "משמאל לימין",
  "Right to Left": "מימין לשמאל",
  "Week Starts On": "השבוע מתחיל",
  "Agenda Style": "סגנון אג'נדה",
  Classic: "קלַאסִי",
  Modern: "מוֹדֶרנִי",
  "Agenda Header": "כותרת סדר יום",
  "Upcoming Events": "אירועים קרובים",
  "Agenda Event Limit": "מגבלת אירועי סדר יום",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "שדרג עכשיו וקבל הרבה יותר תכונות ותיהנה מהאפליקציה שלך במלואה!",
  "Upgrade Now": "שדרג עכשיו",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "אירוח אירועים שנמשך כל היום? זה מאפשר לך להראות אותם בלוח השנה שלך.",
  "24 hours": "24 שעות",
  Sat: "יום שבת",
  Sun: "יום ראשון",
  Mon: "יום שני",
  Default: "בְּרִירַת מֶחדָל",
  "Select custom design style for your calendar.":
    "בחר סגנון עיצוב מותאם אישית ללוח השנה שלך.",
  Style: "סגנון",
  "Styles and Colors": "סגנונות וצבעים",
  "Calendar Name": "שם לוח השנה",
  "Write your Calendar name here": "כתוב כאן את שם לוח השנה",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "זה לא גלוי למשתמשים שלך. הגדר שמות כדי להבדיל את לוחות השנה שלך בעת השימוש בפונקציית סנכרון לוח השנה של Boom.",
  "General Info": "מידע כללי",
  Venue: "מָקוֹם מִפגָשׁ",
  Organizer: "מְאַרגֵן",
  Search: "לחפש",
  "Add to": "להוסיף ל",
  calendar: "לוּחַ שָׁנָה",
  "Copy event URL": "העתק כתובת אתר לאירוע",
  "Copied!": "מוּעֲתָק!",
  "Add & Share": "הוסף ושיתוף",
  Map: "מַפָּה",
  "Calendar view": "תצוגת לוח שנה",
  "Add Event": "הוסף אירועث",
  Uncategorised: "ללא קטגוריה",
  More: "יותר",
  Less: "פָּחוּת",
  Register: "הירשם",
  Card: "כַּרְטִיס",
  Guests: "אורחים",
  unlimited: "ללא הגבלה",
  "Show more": "להראות יותר",
  "Enable Search": "אפשר חיפוש",
  "+ Add Event": "+ הוסף אירוע",
  "Manage and Sync": "ניהול וסנכרון",
  "Show event details as...": "הצג פרטי אירוע כ ...",
  Tooltip: "הסבר כלים",
  Popup: "תיבת מידע",
  None: "אף אחד",
  "Show Category": "הצג קטגוריה",
  "Header Align": "יישור כותרת",
  "Show Time": "הצגת זמן",
  "Hours in Weekly/Daily View": "שעות בתצוגה שבועית / יומית",
  "Share Events": "שתף אירועים",
  Shadow: "צֵל",
  "Inner Padding": "ריפוד פנימי",
  Text: "טֶקסט",
  "Active Button Border": "גבול כפתור פעיל",
  "Light Mode": "מצב אור",
  "Event Text Color": "צבע טקסט אירוע",
  Dates: "תאריכים",
  Skeleton: "שֶׁלֶד",
  "Skeleton Color": "צבע השלד",
  Width: "רוֹחַב",
  "Skeleton Style": "סגנון השלד",
  Color: "צֶבַע",
  "Section Titles": "כותרות קטע",
  "Section Content": "תוכן המדור",
  Header: "כּוֹתֶרֶת",
  Standard: "תֶקֶן",
  Retro: "רטרו",
  Silver: "כסף",
  Night: "לַיְלָה",
  Dark: "אפל",
  Aubergine: "חציל",
  "Map Header": "כותרת מפה",
  "Show Title in mobile": "הצג כותרת בנייד",
  "Card View": "תצוגת כרטיס",
  "Card background color": "צבע רקע כרטיס",
  "Title font": "גופן כותרת",
  "Desciption font": "גופן תיאור",
  "Section font": "קטע גופן",
  "Section divider color": "צבע מחלק חתך",
  "Add event": "הוסף אירוע",
  "All Day Event": "אירוע לכל היום",
  Location: "מקום",
  "Choose a category": "בחר קטגוריה",
  "Venue name": "שם המקום",
  "Venue phone": "טלפון במקום",
  "Venue email": 'דוא"ל במקום',
  "Venue website": "אתר המקום",
  "Organizer name": "שם מארגן",
  "Organizer phone": "טלפון מארגן",
  "Organizer email": 'דוא"ל מארגן',
  "Organizer website": "אתר מארגן",
  "Personal info": "מידע אישי",
  "First name": "שם פרטי",
  "Last name": "שם משפחה",
  "Email Address": 'כתובת דוא"ל',
  "Additional Notes": "הערות נוספות",
  Back: "חזור",
  Save: "להציל",
  Next: "הַבָּא",
  "Your event has been submitted": "האירוע שלך הוגש",
  "Event submittion has been failed": "הגשת האירוע נכשלה",
  "e.g. Birthday Party": "לְמָשָׁל. מסיבת יום הולדת",
  "First Name": "שם פרטי",
  "Last Name": "שם משפחה",
  "Phone Number": "מספר טלפון",
  Address: "כתובת",
  "Your comments": "התגובות שלך",
  "How many guests?": "כמה אורחים?",
  "Anything else we need to know?": "עוד משהו שאנחנו צריכים לדעת?",
  "Guests:": "אורחים:",
  Submit: "שלח",
  "Go to Calendar": "עבור ליומן",
  "Registration completed successfully!": "ההרשמה הושלמה בהצלחה!",
  "Please check your registered email address":
    'אנא בדוק את כתובת הדוא"ל הרשומה שלך',
  "Add to Calendar": "הוסף ליומן",
  "Share this Event": "שתפו אירוע זה",
  "Sorry something went wrong": "מצטערים, משהו השתבש",
  "Back to registration": "חזרה להרשמה",
  "Date & Location": "תאריך ומיקום",
  "Date & Time": "תאריך שעה",
  home: "בית",
  "Header align": "יישור הכותרת",
  Footer: "כותרת תחתונה",
  "Categories Filter": "קטגוריות סינון",
  "Show only upcoming": "הצג רק בקרוב",
  "Card(s) in a row": "כרטיס / ים ברצף",
  "Space between cards": "רווח בין קלפים",
  "Shown events limit": "מגבלת אירועים שהוצגה",
  "Style 1": "סגנון 1",
  "Style 2": "סגנון 2",
  "Style 3": "סגנון 3.",
  "Style 4": "סגנון 4",
  "Buttons & Links": "כפתורים וקישורים",
  "Button corner radius": "רדיוס פינת כפתור",
  "Buttons font": "גופן כפתורים",
  "Buttons background": "לחצנים רקע",
  "Get notified by Email": 'קבל הודעה בדוא"ל',
  "Review events": "סקור אירועים",
  "Click on date": "לחץ על תאריך",
  "Add Event button": "כפתור הוסף אירוע",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "סנכרון לוח השנה מאפשר לך לשלב את האירועים וההפעלות שלך עם לוח השנה של הבום שלך.",
  connect: "לְחַבֵּר",
  "Synchronized Calendars": "לוחות שנה מסונכרנים",
  "Import events": "ייבא אירועים",
  Disconnect: "לְנַתֵק",
  "Choose calendar": "בחר לוח שנה",
  "Monitor your Wix events through the sync feature":
    "עקוב אחר אירועי ה- Wix שלך באמצעות תכונת הסינכרון",
  "Connect all your Boom calendars available on your website":
    "חבר את כל לוחות השנה של Boom הזמינים באתר שלך",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "לוח הזמנים, הצטרף וננהל מפגשי זום דרך היומן שלנו בום.",
  "Monitor your Event Brite events through the Event Brite sync feature.":
    "עקוב אחר אירועי Brite האירועים שלך באמצעות תכונת הסינכרון של Event Brite",
  Email: "אימייל",
  "Add-ons": "תוספות",
  "Receive notification emails as soon as users add events to your calendar.":
    'קבלת הודעות דוא"ל בהקדם האפשרי כמשתמשים להוסיף אירועים ללוח השנה שלך.',
  "Enable + button on the calendar header": "הפעל + כפתור בכותרת היומן",
  "Accept or decline events added by customers before making them public.":
    "קבל או ירידה באירועים שנוספו על ידי לקוחות לפני ביצועם ציבוריים.",
  "Switch Add Event": "מתג להוסיף אירוע",
  "Enable your browser cookies to connect to your account.":
    "הפעל עוגיות הדפדפן שלך כדי להתחבר לחשבון שלך.",
  "Learn more": "למד עוד",
  "Print Button": "Bouton d'impression",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "היתר למשתמשים שלך להדפיס את לוח האירוע של בום בכל טווח תאריך.",
  "Show Title on mobile": "הצג כותרת על נייד",
  "Show Skeleton on mobile": "הצג שלד על נייד",
  "Start 7-day Business trial": "התחל את המשפט העסקי של 7 ימים",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "ליהנות מכל התכונות הבלתי מוגבלות, כגון למכור כרטיסים, רישום, תוספות אירוע מבקרים.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "שים לב: בסוף תקופת הניסיון תוחזר לתוכנית המנוי הקיימת שלך.",
  "Not Now": "לא עכשיו",
  "Start free trial": "להתחיל ניסיון ללא תשלום",
  "Congrats!": "מזל טוב!",
  "Your 7-day Business trial has been successfully activated.":
    "המשפט העסקי של 7 ימים שלך הופעל בהצלחה.",
  Done: "בוצע",
  "Title font color": "כותרת צבע גופן",
  "Desciption font color": "תיאור צבע גופן",
  "Section font color": "סעיף צבע גופן",
  "Card Header": "כותרת כרטיס",
  Category: "קטגוריה",
  "Display at the": "תצוגה ב",
  top: "חלק עליון",
  bottom: "תַחתִית",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "הצג את מסנן הקטגוריה בחלק העליון או בחלק התחתון של היומן.ההגדרות חלות על תצוגות אג'נדה וכרטיס בלבד",
  "Processing your events": "עיבוד האירועים שלך",
  "Search for events": "חפש אירועים",
  "There are no events added": "לא הוסיף אירועים",
  "Location: To be determined": "מיקום: כדי לקבוע",
  "No events for selected date": "אין אירועים לתאריך שנבחר",
  Uncategorized: "לא מסווג",
  "Edit event": "ערוך אירוע",
  "Edit original event": "ערוך אירוע מקורי",
  "Copy event": "אירוע העתק",
  "Copy as new event": "העתק כאירוע חדש",
  "Delete event": "מחק אירוע",
  "Stop repeating on this date": "הפסק לחזור בתאריך זה",
  "Exclude this date": "תכלול תאריך זה",
  "Location is going to be announced": "המיקום הולך להיות מוכרז",
  "Fill your personal information": "מלא את המידע האישי שלך",
  "Check Box": "תיבת סימון",
  "Single Choice": "בחירה יחידה",
  Option: "אוֹפְּצִיָה",
  "Share Event": "שתף אירוע",
  "Oops! Something went wrong": "אופס!משהו השתבש",
  "We are sorry this event has already taken place":
    "אנו מצטערים האירוע הזה כבר התרחש",
  "Back to calendar": "חזרה ללוח השנה",
  "This field is required": "זהו שדה חובה",
  Phone: "טלפון",
  "Number field": "שדה מספר",
  "Please provide a valid email": "אנא ספק אימייל חוקי",
  "Select at least one option": "בחר לפחות אפשרות אחת",
  "Choose tickets to see total value": "בחר כרטיסים כדי לראות ערך כולל",
  tickets: "כרטיסים",
  "Choose Tickets": "בחר כרטיסים",
  "Choose payment method": "בחר אמצעי תשלום",
  Pay: "לְשַׁלֵם",
  Total: "סך הכל",
  Free: "חינם",
  "Buy tickets": "קנה כרטיסים",
  "Sold Out": "נמכר",
  "Tickets are available": "ניתן להשיג כרטיסים",
  "Sales End": "סיום המכירות",
  "Availible from": "זמין מ",
  "Go to Orders": "עבור להזמנות",
  "Go to Details": "עבור לפרטים",
  "Group ticket": "כרטיס קבוצתי",
  Name: "שֵׁם",
  Price: "מחיר",
  "Order by": "מיין לפי",
  "Order ID": "מספר הזמנה",
  Applied: "מיושם",
  Fees: "עמלות",
  "Enter promo code": "הכנס את קוד הזיכוי",
  Apply: "להגיש מועמדות",
  "Promo Code": "קוד קופון",
  Cash: "כסף מזומן",
  "You can find your e-tickets attached to your email or download them":
    'אתה יכול למצוא את הכרטיסים האלקטרוניים שלך המחוברים לדוא"ל שלך או להוריד אותם',
  here: "כאן",
  Time: "זְמַן",
  "Invalid promo code": "קוד פרומו לא חוקי",
  "Credit card": "כרטיס אשראי",
  "You will soon receive a confirmation message of successful registration to your email address.":
    'בקרוב תקבל הודעת אישור של רישום מוצלח לכתובת הדוא"ל שלך.',
  "You can also check your order details below.":
    "אתה יכול גם לבדוק את פרטי ההזמנה שלך למטה.",
  at: "בְּ-",
  Buy: "לִקְנוֹת",
  Donation: "תרומה",
  "Enter price": "מִפְעָל",
  Choose: "בחר",
  Chosen: "נִבחָר",
  "Choose your plan": "בחר את התוכנית שלך",
  week: "שָׁבוּעַ",
  wk: "שָׁבוּעַ",
  "Choose plan cycle": "בחר מחזור תוכנית",
  months: "חודשים",
  years: "שנים",
  weeks: "שבועות",
  "Copy Event Url": "העתק את כתובת האירוע",
  "You can find your e-tickets attached to your email or print them":
    "אתה יכול למצוא את הכרטיסים האלקטרונים שלך מצורפים למייל שלך או להדפיס אותם",
  "Guest Info": "מידע על אורח",
  "Ticket Info": "מידע על כרטיס",
  "Ticket name": "שם כרטיס",
  "Ticket price": "מחיר כרטיס",
  "Ticket ID": "מזהה כרטיס",
  "If you have any questions contact to organizer": "אם יש לך שאלות קשר למארגן",
  "As soon as event ends": "ברגע שהאירוע מסתיים",
  "1 day after event ends": "יום אחד לאחר סיום האירוע",
  "7 days after event ends": "7 ימים לאחר סיום האירוע",
  "14 days after event ends": "14 יום לאחר סיום האירוע",
  "30 days after event ends": "30 יום לאחר סיום האירוע",
  Menu: "תַפרִיט",
  "No event for selected date": "אין אירוע לתאריך שנבחר",
  view: "נוף",
  List: "רשימה",
  Year: "שָׁנָה",
  Yearly: "שְׁנָתִי",
  "Year view header": "כותרת תצוגת שנה",
  "Yearly Style": "סגנון שנתי",
  "There are no events": "אין אירועים",
  Autotranslation: "Autotranslation.",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "לאחר הפעלת, יישומון היומן שלך תתורגם על בסיס שפת האתר.* שים לב כי כל עוד כותרת לוח השנה, ואת התיאורים הם קלטת טקסטים שהם לא יכולים להיות מתורגמים.",
  "Note on mobile": "הערה על הנייד",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "לכבות או לשנות את הטקסט של 'אין אירועים' בר גירסה ניידת של לוח שנה",
  Autodeletion: "Autodeletion",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "הפעלת האפשרות תסיר אוטומטית את אירועי העבר שלך מהלוח.",
  "This does not apply to repeating events!": "זה לא חל על אירועים חוזרים!",
  "Notify event creators about the guest": "הודע למשתמשים על האורח",
  "Send event creators notification emails as soon as guests register for their events":
    "שלח הודעות אימייל של יוצרי אירועים ברגע שהאורחים נרשמים לאירועים שלהם",
  "List View Type": "סוג תצוגת רשימה",
  "Description font": "גופן תיאור",
  Connect: "לְחַבֵּר",
  "You have no events": "אין לך אירועים",
  Synchronize: "לְסַנכְרֵן",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Google Calendar Sync vous permet d'intégrer vos événements et vos sessions avec votre calendrier de boom.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "La synchronisation du calendrier Outlook vous permet d'intégrer vos événements et sessions à votre calendrier Boom.",
  "Your message has been sent successfully!":
    "Votre message a été envoyé avec succès!",
  "There are no synchronized calendars":
    "Il n'y a pas de calendriers synchronisés",
  "to view more than 7 events": "pour voir plus de 7 événements",
  "Mobile app": "נייד App.",
  "Admin Account": "Compte administrateur",
  Password: "סיסמה",
  "Second User": "משתמש שני",
  Edit: "Éditer",
  "Guest limit": "מגבלת אורח",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "כל ההגדרות המקומיות הן (באופן אוטומטי) בהתבסס על השפה שלך.אם השפה שלך נמצאת ברשימה, אין צורך להתאים אישית את החלק הזה.",
  available: "זמין",
  next: "הַבָּא",
  Tickets: "כרטיסים",
  Quantity: "כַּמוּת",
  "Promo code": "קוד קופון",
  "Select a payment method": "בחר אפשרות תשלום",
  Fee: "תַשְׁלוּם",
  Book: "סֵפֶר",
  "All the tickets have been sold out": "כל הכרטיסים נמכרו",
  "Choose at least one ticket": "לבחור לפחות כרטיס אחד",
  "First choose ticket": "ראשית לבחור כרטיס",
  "Please fill out your personal information.": "מלא את המידע האישי שלך.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "כדי לבצע רכישה מוצלחת, בחר את שיטת התשלום המועדפת והזן את קוד הפרומו לכרטיסים מוזלים.",
  "Credit/Debit card": "כרטיס אשראי / חיוב",
  "print here.": "הדפס כאן.",
  "QR code for all tickets": "קוד QR עבור כל הכרטיסים",
  Duration: "מֶשֶׁך",
  "Full Name": "שם מלא",
  "Ticket id": "מזהה כרטיס",
  "Group id": "מזהה קבוצתי",
  "Choose your ticket.": "בחר את הכרטיס שלך.",
  "Fill out your personal information.": "למלא את המידע האישי שלך.",
  "Add the payment details.": "הוסף את פרטי התשלום.",
  "To be determined": "להיות נחוש",
  "You can find your e-tickets attached to the email or":
    "אתה יכול למצוא כרטיסים אלקטרוניים שלך המצורפת לדואל או",
  "print here": "הדפס כאן",
  "Full name": "שם מלא",
  "Group ID": "מזהה קבוצתי",
  "to Book": "כדי להזמין",
  "Unfortunately, your card has been declined": "למרבה הצער, הכרטיס שלך נדחה",
  "Thank you for your purchase!": "תודה על רכישתך!",
  "Find your printable e-tickets attached to the confirmation email":
    "מצא את הכרטיסים האלקטרוניים הניתנים להדפסה שלך המצורפים לדואל האישור",
  Confirm: "לְאַשֵׁר",

  "Add event": "הוסף אירוע",
  Events: "אירועים",
  "Event details": "פרטי האירוע",
  Registration: "הַרשָׁמָה",
  "Guests list": "רשימת האורחים",
  Ticket: "כַּרְטִיס",
  "General Info": "מידע כללי",
  "Customize the general settings of your event":
    "התאם אישית את ההגדרות הכלליות של האירוע שלך",
  "Event Title": "כותרת האירוע",
  "e.g. Birthday Party": "לְמָשָׁל מסיבת יום הולדת",
  "All Day Event": "אירוע לכל היום",
  Cross: "לַחֲצוֹת",
  Timeline: "ציר זמן",
  "Repeating event": "אירוע חוזר",
  Location: "מקום",
  "Venue name": "שם מקום",
  Description: "תיאור",
  Image: "תמונה",
  Color: "צֶבַע",
  Category: "קטגוריה",
  "Add your events to color categories and let your users classify them easily":
    "הוסף את האירועים שלך לקטגוריות צבעוניות ותן למשתמשים שלך לסווג אותם בקלות",
  "Category name": "שם קטגוריה",
  "e.g. Birthdays": "לְמָשָׁל ימי הולדת",
  Venue: "מָקוֹם מִפגָשׁ",
  "Where the event takes place": "היכן שהאירוע מתרחש",
  "Venue name": "שם מקום",
  "Venue phone": "טלפון במקום",
  "Venue email": "דואל במקום",
  "Venue website": "אתר אינטרנט",
  Organizer: "מְאַרגֵן",
  "Person who makes the event": "אדם שעושה את האירוע",
  "Organizer name": "שם מארגן",
  "Organizer phone": "טלפון מארגן",
  "Organizer email": "דואמארגן",
  "Organizer website": "אתר מארגן",
  Save: "להציל",
  Cancel: "לְבַטֵל",
  Import: "יְבוּא",
  Past: "עבר",
  All: "את כל",
  Upcoming: "צפוי",
  Uncategorised: "לא מסווג",
  "Date Ascending": "תאריך עולה",
  "Date Descending": "תאריך יורד",
  "Title by A-Z": "כותרת מאת A-Z",
  "Title by Z-A": "כותרת מאת Z-A",
  "There are no events for this period": "אין אירועים לתקופה זו",

  "Auto-Convert Date & Time": "תאריך ושעה של הקלה אוטומטית",
  TimeZone: "אזור זמן",
  Autodeletion: "Autodeletion",
  "Layout Settings": "הגדרות פריסה",
  "Yeatly view": "מבט לייטי",
  "Monthly view header": "כותרת תצוגה חודשית",
  "Weekly/Daily view header": "כותרת ראייה שבועית/יומית",
  Acendings: "אודות",
  Descending: "יורד",
  Standart: "סטנדארט",
  Silver: "כסף",
  Retro: "רטרו",
  Dark: "אפל",
  Night: "לַיְלָה",
  Aubergine: "חציל",
  "List view header": "רשימת כותרת תצוגה",
  "Side by Side View": "זה לצד זה",
  "Customize Proportions": "התאמה אישית של פרופורציות",
  "Card Margins": "שולי כרטיסים",
  "Image opacity (%)": "אטימות תמונה (%)",
  "Side by Side Header": "כותרת זו לצד זה",
  "Text Align": "יישור טקסט",
  "Timeline View": "תצוגת ציר זמן",
  "Title font color": "צבע גופן כותרת",
  "Desciption font color": "צבע גופן ירידה",
  "Line color": "צבע קו",
  "Date Font color": "צבע גופן של תאריך",
  "Daily events background": "רקע אירועים יומיים",
  Alignment: "יישור",
  Vertical: "אֲנָכִי",
  Horizontal: "אופקי",
  "Vertical Alignment": "יישור אנכי",
  Right: "ימין",
  Center: "מֶרְכָּז",
  "Horizontal Alignment": "יישור אופקי",
  Top: "חלק עליון",
  Center: "מֶרְכָּז",
  Bottom: "תַחתִית",
  "Dates Circle Design": "עיצוב מעגל תאריכים",
  "Next To The Circle": "ליד המעגל",
  "In The Circle": "במעגל",
  "Timeline Header": "כותרת ציר זמן",
  Timeline: "ציר זמן",
  "Show only upcoming": "להראות רק מתקרב",
  "Order by": "מיין לפי",
  "Timeline Event Limit": "מגבלת אירועי ציר זמן",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "אפשר למבקר להוסיף אירוע לקלנדים מקומיים: Google, Yahoo, Outlook, Icicendar.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "אפשר למבקר לשתף את האירוע שלך לפייסבוק, לינקדאין, טוויטר וכו '.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "הוסף אפשרות חיפוש בלוח השנה שלך כדי לאפשר לאנשים לחפש באירועים שלך לפי כותרת, מקום וכו '.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "הרשה למשתמשים שלך להדפיס את לוח האירועים שלך בום בכל טווח תאריכים.",
  "Click to apply a theme to Calendar": "לחץ כדי להחיל נושא על לוח השנה",
  "Date container color": "צבע מיכל תאריך",
  "Daily events background": "רקע אירועים יומיים",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "השתמש בתוספות כדי להתקין תכונות מתקדמות ביומנים שלך, מה שהופך אותם לפונקציונליים יותר!",
  "Open Add-ons Store": "פתח חנות תוספות",
  Monday: "יוֹם שֵׁנִי",
  Tuesday: "יוֹם שְׁלִישִׁי",
  Wednesday: "יום רביעי",
  Thursday: "יוֹם חֲמִישִׁי",
  Friday: "יוֹם שִׁישִׁי",
  Saturday: "יום שבת",
  Sunday: "יוֹם רִאשׁוֹן",
  "Yearly view": "מבט שנתי",
  Ascending: "יוֹם שֵׁנִי",
  "Show event time next to title": "הצג זמן אירוע הבא לכותרת",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "התאם את תאריך האירוע והשעה לזמן המקומי של המשתמש על סמך אזור הזמן שלהם.",
  "Display the time zone alongside the event date.":
    "הצג את אזור הזמן לצד תאריך האירוע.",
  "Show event time next to title": "הצג זמן אירוע הבא לכותרת",
  "Time Zone": "אזור זמן",
  "Upload Image": "העלאת תמונה",
  "Choose a Category": "בחר קטגוריה",
  "Color you have chosen will not be shown as you choose category":
    "צבע שבחרת לא יוצג כפי שתבחר בקטגוריה",
  Website: "אתר אינטרנט",
  Next: "הַבָּא",
  Save: "להציל",
  "Last Name": "שם משפחה",
  "Personal Info": "מידע אישי",
  Back: "חזור",
  "This field is required": "זהו שדה חובה",
  "Your event has been submitted": "האירוע שלך הוגש",
  "Enter a location": "הזן מיקום",
  "Display the time zone alongside the event date.":
    "הצג את אזור הזמן לצד תאריך האירוע.",
  Home: "בית",
  "Side By Side Event Limit": "מגבלת אירוע זה לצד זה",
  "Mobille App": "אפליקציית Mobille",
  category: "קטגוריה",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "עקוב אחר לוח הזמנים שלך בקלות על ידי ייבוא אירועי הפייסבוק שלך ליומן שלך.",
  "Synchronized Pages": "דפים מסונכרנים",
  "There are no synchronized pages": "אין דפים מסונכרנים",
  "Choose page": "בחר עמוד",
  "You have no events": "אין לך אירועים",
};
export default he;
