let hi = {
  Categories: "श्रेणियाँ",
  "Share this event": "इस घटना को साझा करें",
  Language: "भाषा",
  "Show Time Zone": "समय क्षेत्र दिखाएं",
  "Custom Local Settings": "कस्टम स्थानीय सेटिंग",
  "Add and showcase events on your site using a beautiful calendar.":
    "एक सुंदर कैलेंडर का उपयोग करके अपनी साइट पर इवेंट जोड़ें और दिखाएं । ",
  "Week Days": "सप्ताह के दिन",
  "Manage Events": "ईवेंट प्रबंधित करें",
  General: "सामान्य",
  "Layout Picker": "लेआउट पिकर",
  Month: "महीना",
  Monthly: "महीने के",
  Week: "सप्ताह",
  Weekly: "साप्ताहिक",
  Day: "दिवस",
  Daily: "रोज",
  Agenda: "एजेंडा",
  "Navigation Buttons": "नेविगेशन बटन",
  "Week numbers": "सप्ताह संख्या",
  "Include Weekends": "सप्ताहांत शामिल करें",
  "All-day": "पूरे दिन",
  "All Day": "पूरे दिन",
  Label: "लेबल",
  "Fit to Height": "फिट टू हाइट",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "ऐप अनुपात सेट करने के लिए इस विकल्प को मैन्युअल रूप से अक्षम करें और संपादक में कैलेंडर का आकार बदलें। ",
  "Default Layout": "मूलभूत ढांचा",
  "Monthly view": "मासिक दृश्य",
  "Weekly and Daily view": "साप्ताहिक और दैनिक दृश्य",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "आप एक बार में एक ही सप्ताह ( 6) दिखा कर आगंतुकों को अधिक सुसंगत अनुभव दे सकते हैं ।",
  "Fixed Weekly Layout": "फिक्स्ड साप्ताहिक लेआउट",
  back: " वापस ",
  Row: "पंक्ति",
  "Hours in Weekly View": "साप्ताहिक दृश्य में घंटे",
  "Hours in Daily View": "दैनिक दृश्य में घंटे",
  Start: "शुरू",
  End: "समाप्त",
  "At This Hour": "इस घंटे",
  Button: "बटन",
  Buttons: "बटन",
  Sunday: "रविवार",
  Monday: "सोमवार",
  Tuesday: "मंगलवार",
  Wednesday: "बुधवार",
  Thursday: " गुरुवार ",
  Friday: "शुक्रवार",
  Saturday: "शनिवार",
  "Default Date": "डिफ़ॉल्ट तिथि",
  year: " वर्ष ",
  month: " महीना ",
  mo: " महीना ",
  days: " दिन ",
  ago: " पहले ",
  ahead: " आगे ",
  Yesterday: "बिता कल",
  Today: "आज",
  Tomorrow: "आने वाला कल",
  Custom: "कस्टम",
  "Set Daily Rows Limit": "दैनिक पंक्तियाँ सीमा निर्धारित करें",
  "Set Proportions": "सेट अनुपात",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "आगंतुक को स्थानीय कैलेंडर में घटना जोड़ने की अनुमति दें , Google, Yahoo, Outlook, ICalendar । ",
  Container: "कंटेनर",
  Background: "पृष्ठभूमि",
  "Container Background": "कंटेनर पृष्ठभूमि",
  "Container Borders": "कंटेनर बॉर्डर",
  Calendar: "कैलेंडर",
  "Event Info Tooltip": "घटना की जानकारी टूलटिप",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "जब लोग किसी घटना पर होवर करते हैं तो वे इसके बारे ��ें सारी जानकारी टूलटिप में देखेंगे। ",
  "Event Info Window": "इवेंट इंफो विंडो",
  "This is the full information window that opens when someone clicks on the event.":
    "यह पूरी जानकारी विंडो है जो किसी के घटना पर क्लिक करने पर खुलती है। ",
  "Use Gradient": "ग्रेडिएंट का उपयोग करें",
  Vertical: "लंबवत",
  Horizontal: "क्षैतिज",
  First: "प्रथम",
  Second: "दूसरा",
  diagonal: " विकर्ण ",
  Radial: "रेडियल",
  "Select option": "विकल्प चुनें",
  Solid: "ठोस",
  Dotted: "बिंदीदार",
  Dashed: "डैश्ड",
  Double: "डबल",
  "Border Radius": "सीमा त्रिज्या",
  Padding: "गद्दी",
  "Date Header": "तिथि हैडर",
  "Event Default Color": "ईवेंट डिफ़ॉल्ट रंग",
  "Days of Week": "सप्ताह के दिन",
  "Days of Week Background": "सप्ताह की पृष्ठभूमि के दिन",
  Date: "दिनांक",
  "Event Title": "कार्यक्रम का शीर्षक",
  "Highlight today": "आज हाइलाइट करें",
  "Highlight Color": "हाइलाइट रंग",
  Hide: "छिपाना",
  "Calendar Border Color": "कैलेंडर बॉर्डर कलर",
  "Calendar Border Width": "कैलेंडर बॉर्डर चौड़ाई",
  "Calendar Border Style": "कैलेंडर बॉर्डर स्टाइल",
  "Font Color": "लिपि का रंग",
  "Event Background": "इवेंट बैकग्राउंड",
  "Card Date Color": "कार्ड की तारीख का रंग",
  "Title Font": "टाइटल फ़ॉन्ट",
  "Date Font": "दिनांक फ़ॉन्ट",
  "Description Font": "विवरण विवरण",
  "Button Background": "बटन पृष्ठभूमि",
  "Button Text": "टेक्स्ट बटन",
  "Border Color": "किनारे का रंग",
  "Border Width": "सीमा चौड़ाई",
  "Border Type": "सीमा प्रकार",
  Title: "शीर्षक",
  Description: "विवरण",
  "Background Color": "पीछे का रंग",
  Divider: "विभाजक",
  "Event Details Font": "ईवेंट विवरण फ़ॉन्ट",
  "Website Link Color": "वेबसाइट लिंक रंग",
  "Developer Info": "डेवलपर",
  "User Guide": "उपयोगकर्ता गाइड",
  "Support e-mail": "ई-मेल का समर्थन करें",
  "Our Website": "हमारी वेबसाइट",
  "App Review": "ऐप रिव्यू",
  "Enjoying App? Leave us a review in the App Market.":
    "ऐप का आनंद लेना । ऐप मार्केट में हमें एक समीक्षा छोड़ दें । ",
  "Review Us": "हमारी समीक्षा करें",
  "Connect With Us": "हमसे जुडे",
  "What's your email?": "आपका ईमेल क्या है? ",
  "Invalid email address!": "अमान्य ईमेल पता! ",
  Comments: "टिप्पणियाँ",
  "We'd love to hear from you. Send us a message.":
    "हम आपसे सुनना पसंद करेंगे। हमें एक संदेश भेजें। ",
  "Message must be at least 5 characters long":
    "संदेश कम से कम 5 वर्ण लंबा होना चाहिए",
  Send: "भेजें",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "यदि आप उपयोगकर्ता को कैलेंडर विचारों के बीच स्विच करने की अनुमति देना चाहते हैं, तो इस विकल्प को सक्षम करें औ�� उन विचारों को चुनें जिन्हें आप दिखाना चाहते हैं। ",
  Main: "मुख्य",
  Localize: "स्थानीय बनाना",
  Settings: "सेटिंग्स",
  Layouts: "लेआउट",
  Advanced: "उन्नत",
  Design: "डिज़ाइन",
  Support: "समर्थन",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "आपकी भाषा के आधार पर सभी स्थानीय सेटिंग्स (स्वचालित रूप से) हैं। यदि आपकी भाषा सूची में है, तो इस अनुभाग को अनुकूलित करने की कोई आवश्यकता नहीं है।",
  "Date Format": "डेटा प्रारूप",
  "Time Format": "समय प्रारूप",
  "Text Direction": "पाठ की दिशा",
  "Left to Right": "बाएं से दाएं",
  "Right to Left": "दाएं से बाएं",
  "Week Starts On": "सप्ताह की शुरुआत",
  "Agenda Style": "एजेंडा स्टाइल",
  Classic: "क्लासिक",
  Modern: "आधुनिक",
  "Agenda Header": "एजेंडा हैडर",
  "Upcoming Events": "आने वाले कार्यक्रम",
  "Agenda Event Limit": "एजेंडा इवेंट लिमिट",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "अब अपग्रेड करें और बहुत अधिक सुविधाएं प्राप्त करें और अपने एपीपी का पूरा आनंद लें!",
  "Upgrade Now": "अभी अपग्रेड करें",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "पूरे दिन चलने वाली घटनाओं की मेजबानी करना; इससे आप उन्हें अपने कैलेंडर पर दिखा सकते हैं।",
  "24 hours": "चौबीस घंटे",
  Sun: "रविवार",
  Mon: "सोमवार",
  Sat: "शनिवार",
  Default: "चूक",
  "Select custom design style for your calendar.":
    "अपने कैलेंडर के लिए कस्टम डिज़ाइन शैली का चयन करें।",
  Style: "अंदाज",
  "Styles and Colors": "शैलियाँ और रंग",
  "Calendar Name": "कैलेंडर का नाम",
  "Write your Calendar name here": "अपने कैलेंडर का नाम यहाँ लिखें",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "यह आपके उपयोगकर्ताओं को दिखाई नहीं देता है। बूम कैलेंडर सिंक फ़ंक्शन का उपयोग करते समय अपने कैलेंडर को अलग करने के लिए नाम सेट करें।",
  "General Info": "सामान्य जानकारी",
  Venue: "स्थान",
  Organizer: "व्यवस्था करनेवाला",
  Search: "खोज",
  "Add to": "में जोड़े",
  calendar: "पंचांग",
  "Copy event URL": "ईवेंट URL की प्रतिलिपि बनाएँ",
  "Copied!": "מוּעֲתָק!",
  "Add & Share": "जोड़ें और साझा करें",
  Map: "नक्शा",
  "Calendar view": "कैलेंडर दृश्य",
  "Add Event": "कार्यक्रम जोड़ेंث",
  Uncategorised: "अवर्गीकृत",
  More: "अधिक",
  Less: "कम",
  Register: "रजिस्टर करें",
  Card: "कार्ड",
  Guests: "मेहमानों",
  unlimited: "��सीमित",
  "Show more": "और दिखाओ",
  "Enable Search": "खोज सक्षम करें",
  "+ Add Event": "+ ईवेंट जोड़ें",
  "Manage and Sync": "प्रबंधित करें और सिंक करें",
  "Show event details as...": "घटना का विवरण दिखाएं ...",
  Tooltip: "टूलटिप",
  Popup: "जानकारी बॉक्स",
  None: "कोई नहीं",
  "Show Category": "श्रेणी दिखाएँ",
  "Header Align": "हैडर संरेखित करें",
  "Show Time": "शो टाइम",
  "Hours in Weekly/Daily View": "साप्ताहिक / दैनिक दृश्य में घंटे",
  "Share Events": "घटनाओं को साझा करें",
  Shadow: "साया",
  "Inner Padding": "इनर पैडिंग",
  Text: "टेक्स्ट",
  "Active Button Border": "सक्रिय बटन बॉर्डर",
  "Light Mode": "लाइट मोड",
  "Event Text Color": "इवेंट टेक्स्ट कलर",
  Dates: "खजूर",
  Skeleton: "कंकाल",
  "Skeleton Color": "कंकाल का रंग",
  Width: "चौड़ाई",
  "Skeleton Style": "कंकाल शैली",
  Color: "रंग",
  "Section Titles": "अनुभाग शीर्षक",
  "Section Content": "अनुभाग सामग्री",
  Header: "हैडर",
  Standard: "मानक",
  Retro: "रेट्रो",
  Silver: "चांदी",
  Night: "रात",
  Dark: "अंधेरा",
  Aubergine: "बैंगन",
  "Map Header": "नक्शा हैडर",
  "Show Title in mobile": "मोबाइल में शीर्षक दिखाएं",
  "Card View": "कार्ड देखें",
  "Card background color": "कार्ड पृष्ठभूमि का रंग",
  "Title font": "टाइटल फ़ॉन्ट",
  "Desciption font": "वर्णन फ़ॉन्ट",
  "Section font": "फ़ॉन्ट अनुभाग",
  "Section divider color": "खंड विभक्त रंग",
  "Add event": "कार्यक्रम जोड़ें",
  "All Day Event": "पूरे दिन की घटना",
  Location: "स्थान",
  "Choose a category": "कोई श्रेणी चुनें",
  "Venue name": "स्थल का नाम",
  "Venue phone": "वेन्यू फोन",
  "Venue email": "वेन्यू ईमेल",
  "Venue website": "स्थल वेबसाइट",
  "Organizer name": "आयोजक का नाम",
  "Organizer phone": "आयोजक फोन",
  "Organizer email": "आयोजक ईमेल",
  "Organizer website": "आयोजक वेबसाइट",
  "Personal info": "व्यक्तिगत जानकारी",
  "First name": "पहला नाम",
  "Last name": "उपनाम",
  "Email Address": "ईमेल पता",
  "Additional Notes": "अतिरिक्त नोट्स",
  Back: "वापस",
  Save: "सहेजें",
  Next: "आगे",
  "Your event has been submitted": "आपका ईवेंट सबमिट कर दिया गया है",
  "Event submittion has been failed": "इवेंट सबमिशन फेल हो गया है",
  "e.g. Birthday Party": "जैसे जन्मदिन उत्सव",
  "First Name": "पहला नाम",
  "Last Name": "उपनाम",
  "Phone Number": "फ़ोन नंबर",
  Address: "पता",
  "Your comments": "आपकी टिप्पणी",
  "How many guests?": "कितने मेहमान?",
  "Anything else we need to know?": "हमें कुछ और जानना चाहिए?",
  "Guests:": "मेहमान:",
  Submit: "प्रस्तुत",
  "Go to Calendar": "עבור ליומן",
  "Registration completed successfully!": "पंजीकरण सफलतापूर्वक पूरा हुआ!",
  "Please check your registered email address":
    "कृपया अपना पंजीकृत ईमेल पता जांचें",
  "Add to Calendar": "कैलेंडर में जोड़ें",
  "Share this Event": "इस घटना को साझा करें",
  "Sorry something went wrong": "क्षमा करें, कुछ गलत हो गया",
  "Back to registration": "वापस पंजीकरण के लिए",
  "Date & Location": "दिनांक और स्थान",
  "Date & Time": "दिनांक और समय",
  home: "घर",
  "Header align": "Header align",
  Footer: "फ़ुटबाल",
  "Categories Filter": "श्रेणियां फ़िल्टर",
  "Show only upcoming": "केवल आगामी दिखाएं",
  "Card(s) in a row": "एक पंक्ति में कार्ड",
  "Space between cards": "कार्ड के बीच की जगह",
  "Shown events limit": "दिखाया घटनाओं की सीमा",
  "Style 1": "शैली 1",
  "Style 2": "शैली २",
  "Style 3": "शैली ३",
  "Style 4": "शैली ४",
  "Buttons & Links": "Buttons & Links",
  "Button corner radius": "बटन कोने त्रिज्या",
  "Buttons font": "बटन फ़ॉन्ट",
  "Buttons background": "बटन पृष्ठभूमि",
  "Get notified by Email": "ईमेल द्वारा अधिसूचित हो जाओ",
  "Review events": "घटनाक्रम की समीक्षा",
  "Click on date": "तारीख पर क्लिक करें",
  "Add Event button": "ईवेंट बटन जोड़ें",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "कैलेंडर सिंक आपको अपने बूम कैलेंडर के साथ अपनी घटनाओं और सत्रों को एकीकृत करने की अनुमति देता है।",
  connect: "connect",
  "Synchronized Calendars": "सिंक्रनाइज़ कैलेंडर्स",
  "Import events": "घटनाओं को आयात करें",
  Disconnect: "डिस्कनेक्ट",
  "Choose calendar": "कैलेंडर चुनें",
  "Monitor your Wix events through the sync feature":
    "सिंक सुविधा के माध्यम से अपनी Wix घटनाओं की निगरानी करें",
  "Connect all your Boom calendars available on your website":
    "अपनी वेबसाइट पर उपलब्ध अपने सभी बूम कैलेंडर को कनेक्ट करें",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "हमारे बूम कैलेंडर के माध्यम से सही ज़ूम मीटिंग्स को शेड्यूल करें, जुड़ें और प्रबंधित करें।",
  "Monitor your Event Brite events through the Event Brite sync feature.":
    "इवेंट ब्राइट सिंक फीचर के माध्यम से अपने ईवेंट ब्राइट इवेंट्स की निगरानी करें",
  Email: "ईमेल",
  "Add-ons": "ऐड-ऑन",
  "Receive notification emails as soon as users add events to your calendar.":
    "Receive notification emails as soon as users add events to your calendar.",
  "Enable + button on the calendar header": "कैलेंडर हेडर पर + बटन सक्षम करें",
  "Accept or decline events added by customers before making them public.":
    "उन्हें सार्वजनिक करने से पहले ग्राहकों द्वारा जोड़े गए घटनाओं को स्वीकार या अस्वीकार करें।",
  "Switch Add Event": "स्विच इवेंट स्विच करें",
  "Enable your browser cookies to connect to your account.":
    "अपने खाते से कनेक्ट करने के लिए अपनी ब्राउज़र कुकीज़ सक्षम करें।",
  "Learn more": "और अधिक जानें",
  "Print Button": "Bouton d'impression",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "अपने उपयोगकर्ताओं को किसी भी तारीख सीमा में अपने बूम इवेंट कैलेंडर को प्रिंट करने की अनुमति दें।",
  "Show Title on mobile": "मोबाइल पर शीर्षक दिखाएं",
  "Show Skeleton on mobile": "मोबाइल पर कंकाल दिखाएं",
  "Start 7-day Business trial": "अपना 7-दिन का व्यवसाय परीक्षण शुरू करें",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "टिकट, पंजीकरण, आगंतुक घटना ऐड-ऑन बेचने जैसी सभी असीमित सुविधाओं का आनंद लें।",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "कृपया ध्यान दें: परीक्षण अवधि के अंत में, आपको अपनी मौजूदा सदस्यता योजना में वापस कर दिया जाएगा।",
  "Not Now": "अभी नहीं",
  "Start free trial": "निशुल्क आजमाइश शुरु करें",
  "Congrats!": "बधाई!",
  "Your 7-day Business trial has been successfully activated.":
    "आपका 7-दिवसीय व्यवसाय परीक्षण सफलतापूर्वक सक्रिय हो गया है।",
  Done: "किया हुआ",
  "Title font color": "शीर्षक फ़ॉन्ट रंग",
  "Desciption font color": "विवरण फ़ॉन्ट रंग",
  "Section font color": "खंड फ़ॉन्ट रंग",
  "Card Header": "कार्ड हेडर",
  Category: "श्रेणी",
  "Display at the": "पर प्रदर्शित",
  top: "ऊपर",
  bottom: "नीचे",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "शीर्ष पर या कैलेंडर के नीचे श्रेणी फ़िल्टर का प्रदर्शन करें।सेटिंग्स केवल एजेंडा और कार्ड के दृश्यों पर लागू होती हैं",
  "Processing your events": "अपनेघटनाओंका संसाधन",
  "Search for events": "घटनाओं के लिए खोजें",
  "There are no events added": "कोई घटना नहीं है",
  "Location: To be determined": "स्थान: निर्धारित किया जाना है",
  "No events for selected date": "चयनित तिथि के लिए कोई घटना नहीं",
  Uncategorized: "अवर्गीकृत",
  "Edit event": "संपादन कार्यक्रम",
  "Edit original event": "मूल घटना संपादित करें",
  "Copy event": "प्रतिलिपि घटना",
  "Copy as new event": "नई घटना के रूप में कॉपी करें",
  "Delete event": "घटना को हटा दें",
  "Stop repeating on this date": "इस तिथि को दोहराना बंद करें",
  "Exclude this date": "इस तिथि को छोड़ दें",
  "Location is going to be announced": "स्थान की घोषणा की जा रही है",
  "Fill your personal information": "अपनी व्यक्तिगत जानकारी भरें",
  "Check Box": "चेक बॉक्स",
  "Single Choice": "एकल विकल्प",
  Option: "विकल्प",
  "Share Event": "शेयर घटना",
  "Oops! Something went wrong": "उफ़!कुछ गलत हो गया",
  "We are sorry this event has already taken place":
    "हमें खेद है कि यह घटना पहले ही हो चुकी है",
  "Back to calendar": "वापस कैलेंडर",
  "This field is required": "यह फ़ील्ड आवश्यक है",
  Phone: "फ़ोन",
  "Number field": "संख्या क्षेत्र",
  "Please provide a valid email": "कृपया सही ईमेल पता बताएं",
  "Select at least one option": "कम से कम एक विकल्प चुनें",
  "Choose tickets to see total value": "कुल मूल्य देखने के लिए टिकट चुनें",
  tickets: "टिकट",
  "Choose Tickets": "टिकट चुनें",
  "Choose payment method": "भुगतान का तरीका चुनें",
  Pay: "वेतन",
  Total: "संपूर्ण",
  Free: "नि: शुल्क",
  "Buy tickets": "टिकट खरीदो",
  "Sold Out": "बिक चुका है",
  "Tickets are available": "टिकट उपलब्ध हैं",
  "Sales End": "बिक्री समाप्ति",
  "Availible from": "से उपलब्ध",
  "Go to Orders": "आदेशों पर जाना",
  "Go to Details": "विवरण पर जाएं",
  "Group ticket": "समूह टिकट",
  Name: "नाम",
  Price: "कीमत",
  "Order by": "द्वारा आदेश",
  "Order ID": "आदेश ID",
  Applied: "लागू",
  Fees: "फीस",
  "Enter promo code": "प्रचार कि नियमावली दर्ज करो",
  Apply: "लागू",
  "Promo Code": "प्रचार कोड",
  Cash: "नकद",
  "You can find your e-tickets attached to your email or download them":
    "आप अपने ईमेल से जुड़े अपने ई-टिकट पा सकते हैं या उन्हें डाउनलोड कर सकते हैं",
  here: "यहां",
  Time: "समय",
  "Invalid promo code": "अमान्य प्रोमो कोड",
  "Credit card": "क्रेडिट कार्ड",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "आप जल्द ही अपने ईमेल पते पर सफल पंजीकरण का एक पुष्टिकरण संदेश प्राप्त करेंगे।",
  "You can also check your order details below.":
    "आप नीचे दिए गए अपने ऑर्डर विवरण भी देख सकते हैं।",
  at: "पर",
  Buy: "खरीदना",
  Donation: "दान",
  "Enter price": "उद्यम",
  Choose: "चुनना",
  Chosen: "चुना",
  "Choose your plan": "अपनी योजना चुनें",
  week: "सप्ताह",
  wk: "सप्ताह",
  "Choose plan cycle": "योजना चक्र चुनें",
  months: "महीने",
  years: "वर्षों",
  weeks: "हफ्तों",
  "Copy Event Url": "कॉपी इवेंट URL",
  "You can find your e-tickets attached to your email or print them":
    "आप अपने ईमेल से जुड़े अपने ई-टिकट पा सकते हैं या उन्हें प्रिंट कर सकते हैं",
  "Guest Info": "अतिथि जानकारी",
  "Ticket Info": "टिकट की जानकारी",
  "Ticket name": "टिकट का नाम",
  "Ticket price": "टिकट की कीमत",
  "Ticket ID": "टिकट आईडी",
  "If you have any questions contact to organizer":
    "यदि आपके पास आयोजक से कोई प्रश्न संपर्क है",
  "As soon as event ends": "जैसे ही घटना समाप्त हो जाती है",
  "1 day after event ends": "घटना समाप्त होने के 1 दिन बाद",
  "7 days after event ends": "घटना समाप्त होने के 7 दिन बाद",
  "14 days after event ends": "घटना समाप्त होने के 14 दिन बाद",
  "30 days after event ends": "घटना समाप्त होने के 30 दिन बाद",
  Menu: "मेन्यू",
  "No event for selected date": "चयनित तिथि के लिए कोई घटना नहीं",
  view: "देखना",
  List: "सूची",
  Year: "वर्ष",
  Yearly: "सालाना",
  "Year view header": "वर्ष का दृश्य हैडर",
  "Yearly Style": "वार्षिक शैली",
  "There are no events": "कोई घटना नहीं है",
  Autotranslation: "ऑटोट्रैसन",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "एक बार सक्षम होने के बाद, आपके कैलेंडर विजेट का अनुवाद वेबसाइट की भाषा के आधार पर किया जाएगा।* ध्यान दें कि जब तक कैलेंडर शीर्षक, और विवरण इनपुट किए गए ग्रंथों को इनपुट नहीं किया जा सकता है।",
  "Note on mobile": "मोबाइल पर ध्यान दें",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "कैलेंडर के मोबाइल संस्करण पर 'कोई घटना' बार के पाठ को बंद या बदलें",
  Autodeletion: "स्वैच्छिकता",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "विकल्प को सक्षम करना, स्वचालित रूप से आपकी पिछली घटनाओं को कैलेंडर से हटा देगा।",
  "This does not apply to repeating events!":
    "यह दोहराने वाली घटनाओं पर लागू नहीं होता है!",
  "Notify event creators about the guest":
    "अतिथि के बारे में उपयोगकर्ताओं को सूचित करें",
  "Send event creators notification emails as soon as guests register for their events":
    "जैसे ही मेहमान अपनी घटनाओं के लिए पंजीकरण करते हैं, ईवेंट निर्माता अधिसूचना ईमेल भेजें",
  "List View Type": "सूची दृश्य प्रकार",
  "Description font": "वर्णन फ़ॉन्ट",
  Connect: "Connect",
  "You have no events": "आपका कोई कार्यक्रम नहीं है",
  Synchronize: "सिंक्रनाइज़",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "A Google Naptár Sync lehetővé teszi az események és munkamenetek integrálását a Boom naptárával.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Az Outlook Naptár szinkronizálása lehetővé teszi az események és munkamenetek integrálását a Boom naptárral.",
  "Your message has been sent successfully!":
    "आपका संदेश सफलतापूर्वक प्रेषित किया गया!",
  "There are no synchronized calendars": "Nincsenek szinkronizált naptárak",
  "to view more than 7 events": "7 से अधिक घटनाओं को देखने के लिए",
  "Mobile app": "Mobil alkalmazás",
  "Admin Account": "व्यवस्थापक लेखा",
  Password: "Jelszó",
  "Second User": "दूसरा उपयोगकर्ता",
  Edit: "Szerkesztés",
  "Guest limit": "अतिथि सीमा",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "सभी स्थानीय सेटिंग्स आपकी भाषा के आधार पर (स्वचालित रूप से) हैं।यदि आपकी भाषा सूची में है, तो इस खंड को अनुकूलित करने की आवश्यकता नहीं है।",
  available: "उपलब्ध",
  next: "अगला",
  Tickets: "टिकट",
  Quantity: "मात्रा",
  "Promo code": "प्रचार कोड",
  "Select a payment method": "कोई भुगतान विधि चुनें",
  Fee: "शुल्क",
  Book: "पुस्तक",
  "All the tickets have been sold out": "सभी टिकट बेचे गए हैं",
  "Choose at least one ticket": "कम से कम एक टिकट चुनें",
  "First choose ticket": "पहले टिकट चुनें",
  "Please fill out your personal information.":
    "कृपया अपनी व्यक्तिगत जानकारी भरें।",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "एक सफल खरीद करने के लिए, कृपया अपनी पसंदीदा भुगतान विधि का चयन करें और रियायती टिकटों के लिए प्रोमो कोड दर्ज करें।",
  "Credit/Debit card": "क्रेडिट / डेबिट कार्ड",
  "print here.": "यहां प्रिंट करें।",
  "QR code for all tickets": "सभी टिकटों के लिए क्यूआर कोड",
  Duration: "समयांतराल",
  "Full Name": "पूरा नाम",
  "Ticket id": "टिकट आईडी",
  "Group id": "समूह आईडी",
  "Choose your ticket.": "अपना टिकट चुनें।",
  "Fill out your personal information.": "अपनी व्यक्तिगत जानकारी भरें।",
  "Add the payment details.": "भुगतान विवरण जोड़ें।",
  "To be determined": "निर्धारित किए जाने हेतु",
  "You can find your e-tickets attached to the email or":
    "आप अपने ई-टिकट ईमेल से जुड़े पा सकते हैं या",
  "print here": "यहां प्रिंट करें",
  "Full name": "पूरा नाम",
  "Group ID": "समूह आईडी",
  "to Book": "बुक करने के लिए",
  "Unfortunately, your card has been declined":
    "दुर्भाग्य से, आपके कार्ड को अस्वीकार कर दिया गया है",
  "Thank you for your purchase!": "आपकी खरीदारी के लिए धन्यवाद!",
  "Find your printable e-tickets attached to the confirmation email":
    "पुष्टिकरण ईमेल से जुड़े अपने प्रिंट करने योग्य ई-टिकट खोजें",
  Confirm: "पुष्टि करें",

  "Add event": "कार्यक्रम जोड़ें",
  Events: "आयोजन",
  "Event details": "घटना की जानकारी",
  Registration: "पंजीकरण",
  "Guests list": "मेहमानों की सूची",
  Ticket: "टिकट",
  "General Info": "सामान्य जानकारी",
  "Customize the general settings of your event":
    "अपने ईवेंट की सामान्य सेटिंग्स को अनुकूलित करें",
  "Event Title": "कार्यक्रम का शीर्षक",
  "e.g. Birthday Party": "उदा। जन्मदिन की पार्टी",
  "All Day Event": "सारे दिन का कार्यक्रम",
  Cross: "पार करना",
  Timeline: "समय",
  "Repeating event": "दोहराने की घटना",
  Location: "जगह",
  "Venue name": "स्थल का नाम",
  Description: "विवरण",
  Image: "छवि",
  Color: "रंग",
  Category: "वर्ग",
  "Add your events to color categories and let your users classify them easily":
    "अपनी घटनाओं को रंग श्रेणियों में जोड़ें और अपने उपयोगकर्ताओं को आसानी से वर्गीकृत करें",
  "Category name": "श्रेणी नाम",
  "e.g. Birthdays": "उदा। जनमदि की",
  Venue: "कार्यक्रम का स्थान",
  "Where the event takes place": "जहां घटना होती है",
  "Venue name": "स्थल का नाम",
  "Venue phone": "स्थल फोन",
  "Venue email": "स्थल ईमेल",
  "Venue website": "स्थल वेबसाइट",
  Organizer: "व्यवस्था करनेवाला",
  "Person who makes the event": "वह व्यक्ति जो घटना करता है",
  "Organizer name": "आयोजक नाम",
  "Organizer phone": "आयोजक फोन",
  "Organizer email": "आयोजक ईमेल",
  "Organizer website": "आयोजक वेबसाइट",
  Save: "बचाना",
  Cancel: "रद्द करना",
  Import: "आयात",
  Past: "अतीत",
  All: "सभी",
  Upcoming: "आगामी",
  Uncategorised: "अवर्गीकृत",
  "Date Ascending": "तिथि आरोही",
  "Date Descending": "दिनांक अवरोही",
  "Title by A-Z": "ए-जेड द्वारा शीर्षक",
  "Title by Z-A": "जेड-ए द्वारा शीर्षक",
  "There are no events for this period": "इस अवधि के लिए कोई घटना नहीं हैं",

  "Auto-Convert Date & Time": "ऑटो-कन्वर्ट दिनांक और समय",
  TimeZone: "समय क्षेत्र",
  Autodeletion: "स्वैच्छिकता",
  "Layout Settings": "लेआउट सेटिंग",
  "Yeatly view": "Yeatly दृश्य",
  "Monthly view header": "मासिक दृश्य हैडर",
  "Weekly/Daily view header": "साप्ताहिक/दैनिक दृश्य हैडर",
  Acendings: "एक प्रकार का",
  Descending: "अवरोही",
  Standart: "स्टैंडर्ट",
  Silver: "चाँदी",
  Retro: "रेट्रो",
  Dark: "अँधेरा",
  Night: "रात",
  Aubergine: "बैंगन",
  "List view header": "सूची दृश्य शीर्ष लेख",
  "Side by Side View": "साइड -साइड व्यू",
  "Customize Proportions": "अनुपात को अनुकूलित करें",
  "Card Margins": "कार्ड मार्जिन",
  "Image opacity (%)": "छवि अपारदर्शिता (%)",
  "Side by Side Header": "साइड हेडर द्वारा",
  "Text Align": "पाठ संरेखित",
  "Timeline View": "समयरेखा दृश्य",
  "Title font color": "शीर्षक फ़ॉन्ट रंग",
  "Desciption font color": "डिसिप्शन फ़ॉन्ट कलर",
  "Line color": "रेखा रंग",
  "Date Font color": "दिनांक फ़ॉन्ट रंग",
  "Daily events background": "दैनिक घटनाओं की पृष्ठभूमि",
  Alignment: "संरेखण",
  Vertical: "खड़ा",
  Horizontal: "क्षैतिज",
  "Vertical Alignment": "ऊर्ध्वाधर संरेखण",
  Right: "सही",
  Center: "केंद्र",
  "Horizontal Alignment": "क्षैतिज संरेखण",
  Top: "ऊपर",
  Center: "केंद्र",
  Bottom: "तल",
  "Dates Circle Design": "दिनांक सर्कल डिजाइन",
  "Next To The Circle": "सर्कल के बगल में",
  "In The Circle": "सर्कल में",
  "Timeline Header": "समयरेखा हेडर",
  Timeline: "समय",
  "Show only upcoming": "केवल आगामी दिखाएं",
  "Order by": "द्वारा आदेश",
  "Timeline Event Limit": "समयरेखा घटना सीमा",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "आगंतुक को स्थानीय Calnedars में इवेंट जोड़ने की अनुमति दें: Google, Yahoo, Outlook, icalendar।",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "आगंतुक को फेसबुक, लिंक्डइन, ट्विटर और आदि को अपना ईवेंट साझा करने की अनुमति दें।",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "अपने कैलेंडर पर एक खोज विकल्प जोड़ें ताकि लोगों को शीर्षक, स्थल, आदि द्वारा अपनी घटनाओं को खोजने दिया जा सके।",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "अपने उपयोगकर्ताओं को किसी भी दिनांक सीमा में अपने बूम इवेंट कैलेंडर को प्रिंट करने की अनुमति दें।",
  "Click to apply a theme to Calendar":
    "कैलेंडर के लिए एक थीम लागू करने के लिए क्लिक करें",
  "Date container color": "दिनांक कंटेनर रंग",
  "Daily events background": "दैनिक घटनाओं की पृष्ठभूमि",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "अपने कैलेंडर पर उन्नत सुविधाओं को स्थापित करने के लिए ऐड-ऑन का उपयोग करें, जिससे वे अधिक कार्यात्मक हो जाएं!",
  "Open Add-ons Store": "ऐड-ऑन स्टोर खोलें",
  Monday: "सोमवार",
  Tuesday: "मंगलवार",
  Wednesday: "बुधवार",
  Thursday: "गुरुवार",
  Friday: "शुक्रवार",
  Saturday: "शनिवार",
  Sunday: "रविवार",
  "Yearly view": "वार्षिक दृश्य",
  Ascending: "आरोही",
  "Show event time next to title": "टाइटल के बगल में इवेंट टाइम दिखाएं",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "घटना की तारीख और समय को उपयोगकर्ता के स्थानीय समय के लिए उनके समय क्षेत्र के आधार पर समायोजित करें।",
  "Display the time zone alongside the event date.":
    "ईवेंट तिथि के साथ समय क्षेत्र प्रदर्शित करें।",
  "Show event time next to title": "टाइटल के बगल में इवेंट टाइम दिखाएं",
  "Time Zone": "समय क्षेत्र",
  "Upload Image": "तस्विर अपलोड करना",
  "Choose a Category": "कोई श्रेणी चुनें",
  "Color you have chosen will not be shown as you choose category":
    "आपके द्वारा चुने गए रंग को नहीं दिखाया जाएगा क्योंकि आप श्रेणी चुनते हैं",
  Website: "वेबसाइट",
  Next: "अगला",
  Save: "बचाना",
  "Last Name": "उपनाम",
  "Personal Info": "व्यक्तिगत जानकारी",
  Back: "पीछे",
  "This field is required": "यह फ़ील्ड आवश्यक है",
  "Your event has been submitted": "आपका ईवेंट सबमिट किया गया है",
  "Enter a location": "एक स्थान दर्ज करें",
  "Display the time zone alongside the event date.":
    "ईवेंट तिथि के साथ समय क्षेत्र प्रदर्शित करें।",
  Home: "घर",
  "Side By Side Event Limit": "साइड बाय साइड इवेंट लिमिट",
  "Mobille App": "मोबिल ऐप",
  category: "वर्ग",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "अपने Facebook ईवेंट को अपने कैलेंडर में आयात करके आसानी से अपने शेड्यूल पर नज़र रखें।",
  "Synchronized Pages": "सिंक्रोनाइज़्ड पेज",
  "There are no synchronized pages": "कोई समकालिक पृष्ठ नहीं हैं",
  "Choose page": "पेज चुनें",
  "You have no events": "आपके पास कोई घटना नहीं है",
};
export default hi;
