let hr = {
  Categories: "Kategorije",
  "Share this event": "Podijelite ovaj događaj",
  Language: "Jezik",
  "Show Time Zone": "Prikaži vremensku zonu",
  "Custom Local Settings": "Prilagođene lokalne postavke",
  "Add and showcase events on your site using a beautiful calendar.":
    "Dodajte i pokažite događaje na svojoj web stranici pomoću prekrasnog kalendara.",
  "Week Days": "Tjedan dana",
  "Manage Events": "Upravljanje događajima",
  General: "Općenito",
  "Layout Picker": "Berator",
  Month: "Mjesec",
  Monthly: "Mjesečno",
  Week: "Tjedan",
  Weekly: "Tjedni",
  Day: "Dan",
  Daily: "Dnevno",
  Agenda: "Dnevni red",
  "Navigation Buttons": "Navigacijski gumbi",
  "Week numbers": "Tjedna broja",
  "Include Weekends": "Uključite vikende",
  "All-day": "Cijeli dan",
  "All Day": "Cijeli dan",
  Label: "Označiti",
  "Fit to Height": "U skladu s visinom",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Da biste postavili proporcije aplikacije Manully onemogućite ovu opciju i promijenite veličinu kalendara u uređivaču.",
  "Default Layout": "Zadani izgled",
  "Monthly view": "Mjesečni prikaz",
  "Weekly and Daily view": "Tjedni i svakodnevni pogled",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Posjetiteljima možete pružiti dosljednije iskustvo pokazujući isti broj tjedana (6) odjednom.",
  "Fixed Weekly Layout": "Fiksni tjedni izgled",
  back: "leđa",
  Row: "Red",
  "Hours in Weekly View": "Sati u tjednom pogledu",
  "Hours in Daily View": "Sati u dnevnom pogledu",
  Start: "Početak",
  End: "Kraj",
  "At This Hour": "U ovom satu",
  Button: "Dugme",
  Buttons: "Gumbi",
  Sunday: "nedjelja",
  Monday: "ponedjeljak",
  Tuesday: "utorak",
  Wednesday: "srijeda",
  Thursday: "četvrtak",
  Friday: "petak",
  Saturday: "subota",
  "Default Date": "Zadani datum",
  year: "godina",
  month: "mjesec",
  mo: "mokar",
  days: "dani",
  ago: "prije",
  ahead: "ispred",
  Yesterday: "Jučer",
  Today: "Danas",
  Tomorrow: "Sutra",
  Custom: "Prilagođen",
  "Set Daily Rows Limit": "Postavite dnevne retke ograničenje",
  "Set Proportions": "Postavite proporcije",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Dopustite posjetitelju da doda događaj lokalnim Calnedarima: Google, Yahoo, Outlook, iCleEndar.",
  Container: "Spremnik",
  Background: "Pozadina",
  "Container Background": "Pozadina spremnika",
  "Container Borders": "Kontejnere granice",
  Calendar: "Kalendar",
  "Event Info Tooltip": "Info Info Tooltip",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Kad ljudi lebde nad događajem, vidjet će sve informacije o tome u alatu.",
  "Event Info Window": "Info prozor događaja",
  "This is the full information window that opens when someone clicks on the event.":
    "Ovo je puni prozor informacija koji se otvara kada netko klikne na događaj.",
  "Use Gradient": "Koristite gradijent",
  Vertical: "Vertikalan",
  Horizontal: "Horizontalan",
  First: "Prvi",
  Second: "Drugi",
  diagonal: "dijagonalan",
  Radial: "Radijalan",
  "Select option": "Odaberite opciju",
  Solid: "Čvrst",
  Dotted: "Isprekidan",
  Dashed: "Razbijen",
  Double: "Dvostruko",
  "Border Radius": "Polumjer",
  Padding: "Jadnja",
  "Date Header": "Zaglavlje datuma",
  "Event Default Color": "Događaj zadana boja",
  "Days of Week": "Dani u tjednu",
  "Days of Week Background": "Pozadina dana u tjednu",
  Date: "Datum",
  "Event Title": "Naslov događaja",
  "Highlight today": "Istaknite danas",
  "Highlight Color": "Istaknuti boju",
  Hide: "Sakriti",
  "Calendar Border Color": "Kalendarska boja obruba",
  "Calendar Border Width": "Širina granice kalendara",
  "Calendar Border Style": "Kalendar obrubnog stila",
  "Font Color": "Boja fonta",
  "Event Background": "Pozadina događaja",
  "Card Date Color": "Kartica Datum boja",
  "Title Font": "Naslov fonta",
  "Date Font": "Datum fonta",
  "Description Font": "Opis fonta",
  "Button Background": "Pozadina gumba",
  "Button Text": "Tekst gumba",
  "Border Color": "Boja obruba",
  "Border Width": "Širina granice",
  "Border Type": "Vrsta obruba",
  Title: "Titula",
  Description: "Opis",
  "Background Color": "Boja pozadine",
  Divider: "Šestar",
  "Event Details Font": "FONT FONT",
  "Website Link Color": "Boja veze web stranice",
  "Developer Info": "Informacije o programeru",
  "User Guide": "Korisnički vodič",
  "Support e-mail": "Podrška e-mail",
  "Our Website": "Naša web stranica",
  "App Review": "Pregled aplikacija",
  "Enjoying App? Leave us a review in the App Market.":
    "Uživate u aplikaciji? Ostavite nam pregled na tržištu aplikacija.",
  "Review Us": "Pregledati nas",
  "Connect With Us": "Poveži se s nama",
  "What's your email?": "Koja je tvoja e-mail adresa?",
  "Invalid email address!": "Nevažeća adresa e -pošte!",
  Comments: "Komentari",
  "We'd love to hear from you. Send us a message.":
    "Voljeli bismo vas čuti. Pošaljite nam poruku.",
  "Message must be at least 5 characters long":
    "Poruka mora biti najmanje 5 znakova",
  Send: "Poslati",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Ako želite omogućiti korisniku da se prebaci između prikaza kalendara, omogućite ovu opciju i odaberite prikaze koje želite pokazati.",
  Main: "Glavni",
  Localize: "Ograničiti",
  Settings: "Postavke",
  Layouts: "Rasporedi",
  Advanced: "Napredna",
  Design: "Oblikovati",
  Support: "Podržati",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Sve se lokalne postavke (automatski) temelje na vašem jeziku. Ako je vaš jezik na popisu, nema potrebe za prilagodbom ovog odjeljka.",
  "Date Format": "Oblik datuma",
  "Time Format": "Vremenski format",
  "Text Direction": "Smjer teksta",
  "Left to Right": "S lijeva nadesno",
  "Right to Left": "S desna na lijevo",
  "Week Starts On": "Tjedan započinje",
  "Agenda Style": "Dnevni red stil",
  Classic: "Klasičan",
  Modern: "Moderan",
  "Agenda Header": "Zaglavlje dnevnog reda",
  "Upcoming Events": "Nadolazeći događaji",
  "Agenda Event Limit": "Ograničenje događaja dnevnog reda",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Nadogradite odmah i nabavite puno više značajki i uživajte u svojoj aplikaciji u cijelosti!",
  "Upgrade Now": "Nadograditi sada",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Hosting događaja koji traju cijeli dan? To vam omogućuje da ih pokažete u svom kalendaru.",
  "24 hours": "24 sata",
  Sat: "Sjedio",
  Sun: "Sunce",
  Mon: "Pon",
  Default: "Zadano",
  "Select custom design style for your calendar.":
    "Odaberite prilagođeni stil dizajna za svoj kalendar.",
  Style: "Stil",
  "Styles and Colors": "Stilovi i boje",
  "Calendar Name": "Ime kalendara",
  "Write your Calendar name here": "Napišite svoje ime kalendara ovdje",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "To nije vidljivo vašim korisnicima. Postavite imena za razlikovanje kalendara pri korištenju funkcije sinkronizacije kalendara.",
  "General Info": "Opće informacije",
  Venue: "Mjesto",
  Organizer: "Organizator",
  Search: "traži",
  "Add to": "Dodaj u",
  calendar: "kalendar",
  "Copy event URL": "Kopirajte URL događaja",
  "Copied!": "Kopirano!",
  "Add & Share": "Dodaj i podijeli",
  Map: "Karta",
  "Calendar view": "Kalendar prikaz",
  "Add Event": "Dodaj događaj",
  Uncategorised: "Nekategoriziran",
  More: "Više",
  Less: "Manje",
  Register: "Registar",
  Card: "Kartica",
  Guests: "Gosti",
  unlimited: "neograničen",
  "Show more": "Prikaži više",
  "Enable Search": "Omogući pretraživanje",
  "+ Add Event": " + Dodaj događaj",
  "Manage and Sync": "Upravljati i sinkronizirati",
  "Show event details as...": "Prikaži detalje događaja kao ...",
  Tooltip: "Alat",
  Popup: "Iskočiti",
  None: "Nijedan",
  "Show Category": "Show kategorija",
  "Header Align": "Poravnavanje zaglavlja",
  "Show Time": "Pokazati vrijeme",
  "Hours in Weekly/Daily View": "Sati u tjednom/dnevnom pogledu",
  "Share Events": "Dijeliti događaje",
  Shadow: "Sjena",
  "Inner Padding": "Unutarnja obloga",
  Text: "Tekst",
  "Active Button Border": "Aktivni obrub gumba",
  "Light Mode": "Lagani način",
  "Event Text Color": "Boja teksta događaja",
  Dates: "Datumi",
  Skeleton: "Kostur",
  "Skeleton Color": "Boja kostura",
  Width: "Širina",
  "Skeleton Style": "Kosturni stil",
  Color: "Boja",
  "Section Titles": "Naslovi odjeljenja",
  "Section Content": "Sadržaj odjeljka",
  Header: "Zaglavlje",
  Standard: "Standard",
  Retro: "Retro",
  Silver: "Srebro",
  Night: "Noć",
  Dark: "Tamna",
  Aubergine: "Župnik",
  "Map Header": "Zaglavlje karte",
  "Show Title in mobile": "Prikaži naslov u mobilnom uređaju",
  "Card View": "Prikaz karata",
  "Card background color": "Boja pozadine",
  "Title font": "Naslov fonta",
  "Desciption font": "Skrbnički font",
  "Section font": "Presjek fonta",
  "Section divider color": "Boja razdjelnika odjeljka",
  "Add event": "Dodaj događaj",
  "All Day Event": "Cjelodnevni događaj",
  Location: "Mjesto",
  "Choose a category": "Odaberite kategoriju",
  "Venue name": "Ime mjesta",
  "Venue phone": "Telefon na mjestu",
  "Venue email": "E -mail na mjestu događaja",
  "Venue website": "Web stranica mjesta",
  "Organizer name": "Naziv organizatora",
  "Organizer phone": "Organizator telefon",
  "Organizer email": "E -pošta organizatora",
  "Organizer website": "Web stranica organizatora",
  "Personal info": "Osobne informacije",
  "First name": "Ime",
  "Last name": "Prezime",
  "Email Address": "Email adresa",
  "Additional Notes": "dodatne napomene",
  Back: "leđa",
  Save: "Uštedjeti",
  Next: "Sljedeći",
  "Your event has been submitted": "Vaš je događaj podnesen",
  "Event submittion has been failed": "Podnošenje događaja nije uspjelo",
  "e.g. Birthday Party": "npr. Rođendanska zabava",
  "First Name": "Ime",
  "Last Name": "Prezime",
  "Phone Number": "Broj telefona",
  Address: "Adresa",
  "Your comments": "Vaši komentari",
  "How many guests?": "Koliko gostiju?",
  "Anything else we need to know?": "Još nešto što trebamo znati?",
  "Guests:": "Gosti:",
  Submit: "podnijeti",
  "Go to Calendar": "Idite u kalendar",
  "Registration completed successfully!": "Registracija je uspješno završena!",
  "Please check your registered email address":
    "Molimo provjerite svoju registriranu adresu e -pošte",
  "Add to Calendar": "Dodaj u kalendar",
  "Share this Event": "Podijelite ovaj događaj",
  "Sorry something went wrong": "Oprostite, nešto je pošlo naopako",
  "Back to registration": "Povratak na registraciju",
  "Date & Location": "Datum i lokacija",
  "Date & Time": "Datum vrijeme",
  home: "Dom",
  "Header align": "Poravnavanje zaglavlja",
  Footer: "Podnožje",
  "Categories Filter": "Filter kategorije",
  "Show only upcoming": "Pokazati samo nadolazeće",
  "Card(s) in a row": "Kartice (i) u nizu",
  "Space between cards": "Prostor između karata",
  "Shown events limit": "Prikazani događaji ograničavaju",
  "Style 1": "Stil 1",
  "Style 2": "Stil 2",
  "Style 3": "Stil 3",
  "Style 4": "Stil 4",
  "Buttons & Links": "Gumbi i veze",
  "Button corner radius": "Polumjer kuta gumba",
  "Buttons font": "Gumbi font",
  "Buttons background": "Pozadina gumba",
  "Get notified by Email": "Obavijestite se e -poštom",
  "Review events": "Pregledati događaje",
  "Click on date": "Kliknite na datum",
  "Add Event button": "Dodaj gumb događaja",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Kalendar Sync omogućuje vam integriranje događaja i sesija s kalendarom za procvat.",
  connect: "Spojiti",
  "Synchronized Calendars": "Sinkronizirani kalendari",
  "Import events": "Uvoz događaja",
  Disconnect: "Isključiti",
  "Choose calendar": "Odaberite kalendar",
  "Monitor your Wix events through the sync feature":
    "Pratite svoje WIX događaje putem Sync značajke",
  "Connect all your Boom calendars available on your website":
    "Spojite sve svoje kalendare za procvat dostupne na vašoj web stranici",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Zakažite, pridružite se i upravljajte sastancima zumiranja kroz naš kalendar procvata.",
  "Monitor your Event Brite events through the Event Brite sync feature.":
    "Pratite svoj događaj BRITE događaja kroz značajku događaja Brite Sync",
  Email: "E -pošta",
  "Add-ons": "Dodaci",
  "Receive notification emails as soon as users add events to your calendar.":
    "Primite e -poštu obavijesti čim korisnici dodaju događaje u svoj kalendar.",
  "Enable + button on the calendar header":
    "Omogući + gumb na zaglavlju kalendara",
  "Accept or decline events added by customers before making them public.":
    "Prihvatite ili odbijte događaje koje kupci dodaju prije nego što ih objave.",
  "Switch Add Event": "Switch Dodaj događaj",
  "Enable your browser cookies to connect to your account.":
    "Omogućite kolačićima preglednika da se povežu s računom.",
  "Learn more": "Saznajte više",
  "Print Button": "Gumb za ispis",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Omogućite korisnicima da ispisuju vaš kalendar događaja u bilo kojem datumskom rasponu.",
  "Show Title on mobile": "Prikaži naslov na mobilnom uređaju",
  "Show Skeleton on mobile": "Prikaži kostur na mobitelu",
  "Start 7-day Business trial": "Započnite 7-dnevno poslovno suđenje",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Uživajte u svim neograničenim značajkama, poput prodajnih ulaznica, registracije, dodataka za posjetitelje.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Napomena: Na kraju probnog razdoblja bit ćete vraćeni u vaš postojeći plan pretplate.",
  "Not Now": "Ne sada",
  "Start free trial": "Započnite besplatno probno razdoblje",
  "Congrats!": "Čestitamo!",
  "Your 7-day Business trial has been successfully activated.":
    "Vaše sedmodnevno poslovno ispitivanje uspješno je aktivirano.",
  Done: "Završen",
  "Title font color": "Boja naslova fonta",
  "Desciption font color": "Boja font -a za pomračenje",
  "Section font color": "Odjeljak boja fonta",
  "Card Header": "Zaglavlje karata",
  Category: "Kategorija",
  "Display at the": "Prikaz na",
  top: "vrh",
  bottom: "dno",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Izložite filter kategorije na vrhu ili na dnu kalendara. Postavke se odnose samo na dnevni red i prikaze kartica",
  "Processing your events": "Obrada vaših događaja",
  "Search for events": "Potražite događaje",
  "There are no events added": "Nema dodanih događaja",
  "Location: To be determined": "Mjesto: treba utvrditi",
  "No events for selected date": "Nema događaja za odabrani datum",
  Uncategorized: "Nekategoriziran",
  "Edit event": "Uredi događaj",
  "Edit original event": "Uredi originalni događaj",
  "Copy event": "Kopija događaja",
  "Copy as new event": "Kopirajte kao novi događaj",
  "Delete event": "Izbriši događaj",
  "Stop repeating on this date": "Prestanite ponavljati na ovaj datum",
  "Exclude this date": "Isključite ovaj datum",
  "Location is going to be announced": "Lokacija će biti najavljena",
  "Fill your personal information": "Ispunite svoje osobne podatke",
  "Check Box": "Potvrdni okvir",
  "Single Choice": "Pojedinačni izbor",
  Option: "Opcija",
  "Share Event": "Dijeljenje događaja",
  "Oops! Something went wrong": "Ups! Nešto je pošlo po zlu",
  "We are sorry this event has already taken place": "Žao nam je",
  "Back to calendar": "Povratak na kalendar",
  "This field is required": "ovo polje je obavezno",
  Phone: "Telefon",
  "Number field": "Brojčano polje",
  "Please provide a valid email": "Navedite valjanu e -poštu",
  "Select at least one option": "Odaberite barem jednu opciju",
  "Choose tickets to see total value":
    "Odaberite ulaznice da biste vidjeli ukupnu vrijednost",
  tickets: "ulaznice",
  "Choose Tickets": "Odaberite ulaznice",
  "Choose payment method": "Izaberite način plaćanja",
  Pay: "Platiti",
  Total: "Ukupno",
  Free: "Besplatno",
  "Buy tickets": "Kupiti karte",
  "Sold Out": "Prodano",
  "Tickets are available": "Ulaznice su dostupne",
  "Sales End": "Prodaja",
  "Availible from": "Dostupno iz",
  "Go to Orders": "Idite na zapovijed",
  "Go to Details": "Idite na detalje",
  "Group ticket": "Grupna karta",
  Name: "Ime",
  Price: "Cijena",
  "Order by": "Narediti",
  "Order ID": "ID narudžbe",
  Applied: "Primijenjen",
  Fees: "Naknada",
  "Enter promo code": "Unesite promo kod",
  Apply: "Prijaviti",
  "Promo Code": "Promo kod",
  Cash: "Unovčiti",
  "You can find your e-tickets attached to your email or download them":
    "Možete pronaći svoje e-ulaznice priložene na vašu e-poštu ili ih preuzeti",
  here: "ovdje",
  Time: "Vrijeme",
  "Invalid promo code": "Nevažeći promo kod",
  "Credit card": "Kreditna kartica",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Uskoro ćete dobiti potvrdnu poruku uspješne registracije na vašu adresu e -pošte.",
  "You can also check your order details below.":
    "Također možete provjeriti detalje narudžbe u nastavku.",
  at: "na",
  Buy: "Kupiti",
  Donation: "Donacija",
  "Enter price": "Unesite cijenu",
  Choose: "Odabrati",
  Chosen: "Izabran",
  "Choose your plan": "Odaberite svoj plan",
  week: "tjedan",
  wk: "wk",
  "Choose plan cycle": "Odaberite ciklus plana",
  months: "mjeseci",
  years: "godine",
  weeks: "tjedni",
  "Copy Event Url": "Kopirajte URL događaja",
  "You can find your e-tickets attached to your email or print them":
    "Možete pronaći svoje e-ulaznice priložene na vašu e-poštu ili ih ispisati",
  "Guest Info": "Informacije o gostima",
  "Ticket Info": "Informacije o ulaznicama",
  "Ticket name": "Ime ulaznica",
  "Ticket price": "Cijena karte",
  "Ticket ID": "Id ulaznica",
  "If you have any questions contact to organizer":
    "Ako imate bilo kakvih pitanja, obratite se organizatoru",
  "As soon as event ends": "Čim se događaj završi",
  "1 day after event ends": "1 dan nakon završetka događaja",
  "7 days after event ends": "7 dana nakon završetka događaja",
  "14 days after event ends": "14 dana nakon završetka događaja",
  "30 days after event ends": "30 dana nakon završetka događaja",
  Menu: "Jelovnik ",
  "No event for selected date": "Nema događaja za odabrani datum",
  view: "pogled",
  List: "Popis",
  Year: "Godina",
  Yearly: "Godišnje",
  "Year view header": "Zaglavlje za pregled godine",
  "Yearly Style": "Godišnji stil",
  "There are no events": "Nema događaja",
  Autotranslation: "Autotranslacija",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Nakon što je omogućen, vaš kalendarski widget bit će preveden na temelju jezika web stranice. *Imajte na umu da sve dok su kalendarski naslov i opisi uneseni tekstovi ne mogu se prevesti.",
  "Note on mobile": "Napomena na mobilnom uređaju",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Isključite ili promijenite tekst trake 'Nema događaja' na mobilnoj verziji kalendara",
  Autodeletion: "Autodeletion",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Omogućivanje opcije automatski će ukloniti vaše prošle događaje iz kalendara.",
  "This does not apply to repeating events!":
    "To se ne odnosi na ponavljanje događaja!",
  "Notify event creators about the guest":
    "Obavijestite kreativce događaja o gostu",
  "Send event creators notification emails as soon as guests register for their events":
    "Pošaljite e -mailove kreativaca događaja čim se gosti registriraju za njihove događaje",
  "List View Type": "Vrsta prikaza popisa",
  "Description font": "Opis fonta",
  Connect: "Spojiti",
  "You have no events": "Nemate događaja",
  Synchronize: "Sinkronizirati",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Google kalendar Sync omogućuje vam integriranje vaših događaja i sesija s kalendarom Boom.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Outlook kalendar Sync omogućuje vam integriranje događaja i sesija s kalendarom za procvat.",
  "Your message has been sent successfully!":
    "Tvoja je poruka uspješno poslana!",
  "There are no synchronized calendars": "Nema sinkroniziranih kalendara",
  "to view more than 7 events": "Da biste pogledali više od 7 događaja",
  "Mobile app": "Mobilna aplikacija",
  "Admin Account": "Administratorski račun",
  Password: "Lozinka",
  "Second User": "Drugi korisnik",
  Edit: "Uredi",
  "Guest limit": "Ograničenje gostiju",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Sve se lokalne postavke (automatski) temelje na vašem jeziku. Ako je vaš jezik na popisu, nema potrebe za prilagodbom ovog odjeljka.",
  available: "dostupno",
  next: "Sljedeći",
  Tickets: "Ulaznice",
  Quantity: "Količina",
  "Promo code": "Promo kod",
  "Select a payment method": "Odaberi način plaćanja",
  Fee: "Pristojba",
  Book: "Knjiga",
  "All the tickets have been sold out": "Sve su ulaznice rasprodate",
  "Choose at least one ticket": "Odaberite najmanje jednu kartu",
  "First choose ticket": "Prvo odaberite kartu",
  "Please fill out your personal information.":
    "Ispunite svoje osobne podatke.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "Da biste izvršili uspješnu kupnju, odaberite preferirani način plaćanja i unesite promotivni kôd za ulaznice s popustom.",
  "Credit/Debit card": "Kreditna/debitna kartica",
  "print here.": "tiskati ovdje.",
  "QR code for all tickets": "QR kod za sve karte",
  Duration: "Trajanje",
  "Full Name": "Puno ime",
  "Ticket id": "Id ulaznica",
  "Group id": "Grupa",
  "Choose your ticket.": "Odaberite svoju kartu.",
  "Fill out your personal information.": "Ispunite svoje osobne podatke.",
  "Add the payment details.": "Dodajte detalje o plaćanju.",
  "To be determined": "Biti odlučan",
  "You can find your e-tickets attached to the email or":
    "Možete pronaći svoje e-ulaznice priložene e-pošti ili",
  "print here": "tiskati ovdje",
  "Full name": "Puno ime",
  "Group ID": "Grupa",
  "to Book": "rezervirati",
  "Unfortunately, your card has been declined":
    "Nažalost, vaša je kartica odbijena",
  "Thank you for your purchase!": "Hvala vam na kupnji!",
  "Find your printable e-tickets attached to the confirmation email":
    "Pronađite svoje e-karte za ispis priložene na e-poštu s potvrdom",
  Confirm: "Potvrditi",

  "Add event": "Dodaj događaj",
  Events: "Događaj",
  "Event details": "Detalji događaja",
  Registration: "Prijava",
  "Guests list": "Popis gostiju",
  Ticket: "Ulaznica",
  "General Info": "Opće informacije",
  "Customize the general settings of your event":
    "Prilagodite opće postavke vašeg događaja",
  "Event Title": "Naslov događaja",
  "e.g. Birthday Party": "npr. Rođendanska zabava",
  "All Day Event": "Cjelodnevni događaj",
  Cross: "Križ",
  Timeline: "Vremenska Crta",
  "Repeating event": "Ponavljajući događaj",
  Location: "Mjesto",
  "Venue name": "Ime mjesta",
  Description: "Opis",
  Image: "Slika",
  Color: "Boja",
  Category: "Kategorija",
  "Add your events to color categories and let your users classify them easily":
    "Dodajte svoje događaje u kategorije boja i pustite da ih korisnici lako klasificiraju",
  "Category name": "Ime kategorije",
  "e.g. Birthdays": "npr. Rođendani",
  Venue: "Mjesto",
  "Where the event takes place": "Tamo gdje se događaj odvija",
  "Venue name": "Ime mjesta",
  "Venue phone": "Telefon na mjestu",
  "Venue email": "E -mail na mjestu događaja",
  "Venue website": "Web stranica mjesta",
  Organizer: "Organizator",
  "Person who makes the event": "Osoba koja događa događaj",
  "Organizer name": "Naziv organizatora",
  "Organizer phone": "Organizator telefon",
  "Organizer email": "E -pošta organizatora",
  "Organizer website": "Web stranica organizatora",
  Save: "Uštedjeti",
  Cancel: "Otkazati",
  Import: "Uvoz",
  Past: "Prošlost",
  All: "svi",
  Upcoming: "Nadolazeće",
  Uncategorised: "Nekategoriziran",
  "Date Ascending": "Datum uzlaznih",
  "Date Descending": "Datum spuštanja",
  "Title by A-Z": "Naslov A-Z",
  "Title by Z-A": "Naslov Z-A",
  "There are no events for this period": "Nema događaja za ovo razdoblje",

  "Auto-Convert Date & Time": "Automatsko popravljanje datuma i vremena",
  TimeZone: "Vremenska zona",
  Autodeletion: "Autodeletion",
  "Layout Settings": "Postavke izgleda",
  "Yeatly view": "Yealy View",
  "Monthly view header": "Zaglavlje mjesečnog pogleda",
  "Weekly/Daily view header": "Tjedni/dnevni vid zaglavlje",
  Acendings: "Provedbe",
  Descending: "Silazni",
  Standart: "Standart",
  Silver: "Srebro",
  Retro: "Retro",
  Dark: "Tamna",
  Night: "Noć",
  Aubergine: "Župnik",
  "List view header": "Popis zaglavlja prikaza",
  "Side by Side View": "Podnožje",
  "Customize Proportions": "Prilagodite proporcije",
  "Card Margins": "Marže karata",
  "Image opacity (%)": "Neprozirnost slike (%)",
  "Side by Side Header": "Bočno zaglavlje",
  "Text Align": "Poravnaj teksta",
  "Timeline View": "Pregled vremenske trake",
  "Title font color": "Boja naslova fonta",
  "Desciption font color": "Boja font -a za pomračenje",
  "Line color": "Crta boja",
  "Date Font color": "Datum boja fonta",
  "Daily events background": "Pozadina dnevnih događaja",
  Alignment: "Poravnanje",
  Vertical: "Vertikalan",
  Horizontal: "Horizontalan",
  "Vertical Alignment": "Vertikalno poravnanje",
  Right: "Pravo",
  Center: "Centar",
  "Horizontal Alignment": "Horizontalno poravnanje",
  Top: "Vrh",
  Center: "Centar",
  Bottom: "Dno",
  "Dates Circle Design": "Datumi dizajn kruga",
  "Next To The Circle": "Pored kruga",
  "In The Circle": "U krugu",
  "Timeline Header": "Zaglavlje vremenske trake",
  Timeline: "Vremenska Crta",
  "Show only upcoming": "Pokažite samo nadolazeće",
  "Order by": "Narediti",
  "Timeline Event Limit": "Ograničenje događaja vremenske trake",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Dopustite posjetitelju da doda događaj lokalnim Calnedarima: Google, Yahoo, Outlook, iCeder.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Dopustite posjetitelju da podijeli vaš događaj na Facebooku, LinkedInu, Twitteru i sl.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Dodajte opciju pretraživanja u svoj kalendar kako biste ljudi pretraživali vaše događaje po naslovu, mjestom itd.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Omogućite svojim korisnicima da ispisuju kalendar događaja Boom u bilo kojem rasponu.",
  "Click to apply a theme to Calendar":
    "Kliknite da biste primijenili temu u kalendar",
  "Date container color": "DATUM Spremnik boja",
  "Daily events background": "Pozadina dnevnih događaja",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Upotrijebite dodatke za instaliranje naprednih značajki na svoje kalendare, što ih čini funkcionalnijim!",
  "Open Add-ons Store": "Otvorite prodavaonicu Add-Cons",
  Monday: "ponedjeljak",
  Tuesday: "utorak",
  Wednesday: "srijeda",
  Thursday: "četvrtak",
  Friday: "petak",
  Saturday: "subota",
  Sunday: "nedjelja",
  Ascending: "Uzlazni",
  "Yearly view": "Godišnji pogled",
  "Show event time next to title": "Prikaži vrijeme događaja pored naslova",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Prilagodite datum i vrijeme događaja na lokalno vrijeme korisnika na temelju njihove vremenske zone.",
  "Display the time zone alongside the event date.":
    "Prikažite vremensku zonu uz datum događaja.",
  "Show event time next to title": "Prikaži vrijeme događaja pored naslova",
  "Time Zone": "Vremenska zona",
  "Upload Image": "Učitaj sliku",
  "Choose a Category": "Odaberite kategoriju",
  "Color you have chosen will not be shown as you choose category":
    "Boja koju ste odabrali neće biti prikazano kad odaberete kategoriju",
  Website: "Web stranica",
  Next: "Sljedeći",
  Save: "Uštedjeti",
  "Last Name": "Prezime",
  "Personal Info": "Osobne informacije",
  Back: "leđa",
  "This field is required": "ovo polje je obavezno",
  "Your event has been submitted": "Vaš je događaj podnesen",
  "Enter a location": "Unesite mjesto",
  "Display the time zone alongside the event date.":
    "Prikažite vremensku zonu uz datum događaja.",
  Home: "Dom",
  "Side By Side Event Limit": "Granica događaja radno uz drugo",
  "Mobille App": "Mobille App",
  category: "kategorija",
  Add: "Aghjustate",
  "Mobile App": "App mobile",
  username: "Usuariu",
  password: "codice",
  "Connect all your Boom calendars available on your website.":
    "Cunnette tutte e vostre calendari Boom dispunibili in u vostru situ web.",
  "Monitor your Wix events through the sync feature.":
    "Monitorate i vostri avvenimenti Wix per via di a funzione di sincronia.",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Lako pratite svoj raspored uvozom svojih Facebook događaja u svoj kalendar.",
  "Synchronized Pages": "Sinkronizirane stranice",
  "There are no synchronized pages": "Nema sinkroniziranih stranica",
  "Choose page": "Odaberite stranicu",
  "You have no events": "Nemate događaja",
};
export default hr;
