let hu = {
  Categories: "Kategóriáks",
  "Share this event": "Ossza meg ezt az eseményt",
  Language: "Nyelv",
  "Show Time Zone": "Mutasson Idő zónát",
  "Custom Local Settings": "Egyedi hely beállítás",
  "Add and showcase events on your site using a beautiful calendar.":
    "Adj hozzá eseményeket az oldaladhoz, ezzel a csodás naptárral.",
  "Week Days": "Hétköznapok",
  "Manage Events": "Események kezelése",
  General: "Általános",
  "Layout Picker": "Kinézet választó",
  Month: "Hónap",
  Monthly: "Havonta",
  Week: "Hét",
  Weekly: "Hetente",
  Day: "Nap",
  Daily: "Naponta",
  Agenda: "Napirend",
  "Navigation Buttons": "Irányító gombok",
  "Week numbers": "Hetek számozása",
  "Include Weekends": "Hétvégét belevéve",
  "All Day": "Egész nap",
  Label: "Felirat",
  "Fit to Height": "Magassághoz igazítva",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Az alkalmazás méretének manuális beállításához tiltsale ezt a lehetőséget, és méretezzé át a Naptár szerkesztőben.",
  "Default Layout": "Alapértelmezett nézet",
  "Monthly view": "Havi nézet",
  "Weekly and Daily view": "Heti és Napi nézet",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "A látogatóknak nyújts következetesebb érzést azzal, hogy ugyanazt a hetet mutatod.",
  "Fixed Weekly Layout": "Fix heti kinézet",
  back: "vissza",
  Row: "Sor",
  "Hours in Weekly View": "Órák a heti nézetben",
  "Hours in Daily View": "Órák a napi nézetben",
  Start: "Rajt",
  End: "Vég",
  "At This Hour": "Ebben az órában",
  Button: "Gomb",
  Buttons: "Gombok",
  Sunday: "Vasárnap",
  Monday: "Hétfő",
  Tuesday: "Kedd",
  Wednesday: "Szerda",
  Thursday: "Csütörtök",
  Friday: "Péntek",
  Saturday: "Szombat",
  "Default Date": "Alapértelmezett dátum",
  year: "év",
  month: "hónap",
  mo: "hónap",
  days: "napok",
  ago: "előtt",
  ahead: "előre",
  Yesterday: "Tegnap",
  Today: "Ma",
  Tomorrow: "Holnap",
  Custom: "Egyedi",
  "Set Daily Rows Limit": "Állíts napi sor limitet",
  "Set Proportions": "Állíts tagolást",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Engedélyezd a látogatóknak, hogy hozzáadják az eseményeket a saját naptárjukhoz = Google, Yahoo, Outlook, ICalender.",
  Container: "Tartó",
  Background: "Háttér",
  "Container Background": "Tartó háttér",
  "Container Borders": "Tartó keretek",
  Calendar: "Naptár",
  "Event Info Tooltip": "Esemény info tanács",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Amikor az emberek az egérmutatót egy esemény fölé viszik, akkor azerről szóló összes információt egy leírásban látják.",
  "Event Info Window": "Esemény Info Ablak",
  "This is the full information window that opens when someone clicks on the event.":
    "Ez a full információ ablak, ha valaki rákattint az eseményre,Use Gradient = Használja a színátmenetet",
  "Use Gradient": "Használja a színátmenetet",
  Vertical: "Vertikális",
  Horizontal: "Horizontális",
  First: "Első",
  Second: "Második",
  diagonal: "átló",
  Radial: "Sugár",
  "Select option": "Választható opció",
  Solid: "Szolid",
  Dotted: "Pontos",
  Dashed: "Szaggatott",
  Double: "Kettős",
  "Border Radius": "Határ sugár",
  Padding: "Tömés",
  "Date Header": "Dátum fejléc",
  "Event Default Color": "Esemény alapértelmezett szín",
  "Days of Week": "A hét napjai",
  "Days of Week Background": "A hét napjai háttere",
  Date: "Dátum",
  "Event Title": "Esemény címe",
  "Highlight today": "Kiemelés ma",
  "Highlight Color": "Kiemelés szín",
  Hide: "Elrejt",
  "Calendar Border Color": "Naptár keret szín",
  "Calendar Border Width": "Naptár keret szélesség",
  "Calendar Border Style": "Naptár keret stílus",
  "Font Color": "Betűtípus szín",
  "Event Background": "Esemény háttér",
  "Card Date Color": "Kártya datum szín",
  "Title Font": "Cím betűtípus",
  "Date Font": "Dátum betűtípus",
  "Description Font": "Leírás betűtípus",
  "Button Background": "Gomb háttér",
  "Button Text": "Gomb szöveg",
  "Border Color": "Keret szín",
  "Border Width": "Keret szélesség",
  "Border Type": "Keret típus",
  Title: "Cím",
  Description: "Leírás",
  "Background Color": "Háttér szín",
  Divider: "Osztó",
  "Event Details Font": "Esemény leírás betűtípus",
  "Website Link Color": "Weboldal link szín",
  "Developer Info": "Fejlesztői Info",
  "User Guide": "Használati útmutató",
  "Support e-mail": "Ügyfélszolgálat e-mail",
  "Our Website": "Mi weboldalunk",
  "App Review": "App értékelés",
  "Enjoying App? Leave us a review in the App Market.":
    "Tetszik az app? Írj egy értékelés az App Marketben.",
  "Review Us": "Értékelj minket",
  "Connect With Us": "Lépj kapcsolatban velünk",
  "What's your email?": "Mi az email címed?",
  "Invalid email address!": "Helytelen email cím!",
  Comments: "Kommentek",
  "We'd love to hear from you. Send us a message.":
    "Örömmel hallunk felőled! Írj üzenetet nekünk.",
  "Message must be at least 5 characters long":
    "Az üzenetnek minimum 5 karakter hosszúságúnak kell hogy legyen",
  Send: "Küldés",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Ha azt szeretnéd hogy a felhasználók tudjanak váltani a naptár nézet között, engedélyezd ezt a opciót és válassza ki a megjeleníteni kívánt nézetet.",
  Main: "Főoldal",
  Localize: "Hely",
  Settings: "Beállítások",
  Layouts: "Kinézetek",
  Advanced: "Haladó",
  Design: "Kinézet",
  Support: "Segítség",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Az összes helyi beállítás (automatikusan) az Ön nyelvén alapul. Ha az Ön nyelve szerepel a listán, akkor nem kell testreszabnia ezt a részt.",
  "Date Format": "Dátum formátum",
  "Time Format": "Idő formátum",
  "Text Direction": "Szöveg irány",
  "Left to Right": "Balról jobbra",
  "Right to Left": "Jobbról balra",
  "Week Starts On": "Hét kezdés",
  "Agenda Style": "Napirend stílus",
  Classic: "Klasszikus",
  Modern: "Modern",
  "Agenda Header": "Napirend fejléc",
  "Upcoming Events": "Közeledő események",
  "Agenda Event Limit": "Agenda Event Limit",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Bővíts most és aktiválj több lehetőséget, hogy teljes mértékben élvezd az APP- ot!",
  "Upgrade Now": "Bővíts most",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Egésznapos események? Ez lehetővé teszi, hogy megmutassa őket a naptárban.",
  "24 hours": "24 órás",
  Sun: "Vas",
  Mon: "Hét",
  Sat: "Szom",
  Default: "Alapértelmezett",
  Style: "Stílus",
  "Calendar Name": "Naptár neve",
  "Write your Calendar name here": "Írja ide a naptár nevét",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Ez a felhasználók számára nem látható. Nevek beállítása a naptárak megkülönböztetésére a Boom Calendar Sync funkció használatakor.",
  "General Info": "Általános információ",
  Venue: "Helyszín",
  Organizer: "Szervező",
  Search: "Keresés",
  "Add to": "Hozzáad",
  calendar: "naptár",
  "Copy event URL": "Másolja az esemény URL-jét",
  "Copied!": "Másolt!",
  "Add & Share": "Hozzáadás és megosztás",
  Map: "Térkép",
  "Calendar view": "Naptár nézet",
  "Add Event": "Esemény hozzáadása",
  Uncategorised: "Uncategorized",
  More: "Több",
  Less: "Kevésbé",
  Register: "Regisztráció",
  Card: "Kártya",
  Guests: "Vendégek",
  unlimited: "korlátlan",
  "Show more": "Mutass többet",
  "Enable Search": "A keresés engedélyezése",
  "+ Add Event": "+ Esemény hozzáadása",
  "Manage and Sync": "Kezelés és szinkronizálás",
  "Show event details as...": "Mutassa az esemény részleteit mint ...",
  Tooltip: "Tooltip",
  Popup: "Információs doboz",
  None: "Egyik sem",
  "Show Category": "Kategória megjelenítése",
  "Header Align": "Fejléc igazítása",
  "Show Time": "Mutasd az időt",
  "Hours in Weekly/Daily View": "Órák heti / napi nézetben",
  "Share Events": "Események megosztása",
  Shadow: "Árnyék",
  "Inner Padding": "Belső párna",
  Text: "Szöveg",
  "Active Button Border": "Aktív gomb szegély",
  "Light Mode": "Világos mód",
  "Event Text Color": "Esemény szöveg színe",
  Dates: "Időpontok",
  Skeleton: "Csontváz",
  "Skeleton Color": "Csontváz szín",
  Width: "Szélesség",
  "Skeleton Style": "Csontváz stílus",
  Color: "Szín",
  "Section Titles": "Szakasz címei",
  "Section Content": "Szakasz tartalma",
  Header: "Fejléc",
  Standard: "Alapértelmezett",
  Retro: "Retro",
  Silver: "Ezüst",
  Night: "Éjszaka",
  Dark: "Sötét",
  Aubergine: "Padlizsán",
  "Map Header": "Térkép fejléce",
  "Show Title in mobile": "Mutasd a címet mobilon",
  "Card View": "Kártya nézet",
  "Card background color": "Kártya háttér színe",
  "Title font": "Cím betűtípusa",
  "Desciption font": "Leírás betűtípus",
  "Section font": "Betűkészlet szakasz",
  "Section divider color": "Szakaszelválasztó színe",
  "Add event": "Esemény hozzáadása",
  "All Day Event": "Egész napos esemény",
  Location: "Elhelyezkedés",
  "Choose a category": "Válasszon kategóriát",
  "Venue name": "Helyszín neve",
  "Venue phone": "Helyszín telefon",
  "Venue email": "Helyszín e-mail",
  "Venue website": "Helyszín helyszíne",
  "Organizer name": "Szervező neve",
  "Organizer phone": "Szervező telefon",
  "Organizer email": "Szervező e-mail",
  "Organizer website": "Szervező honlapja",
  "Personal info": "Személyes adatok",
  "First name": "Keresztnév",
  "Last name": "Vezetéknév",
  "Email Address": "Email cím",
  "Additional Notes": "További megjegyzések",
  Back: "Vissza",
  Save: "Megment",
  Next: "Következő",
  "Your event has been submitted": "Az esemény beküldve",
  "Event submittion has been failed": "Az esemény beküldése nem sikerült",
  "e.g. Birthday Party": "például. Szülinapi buli",
  "First Name": "Keresztnév",
  "Last Name": "Vezetéknév",
  "Phone Number": "Telefonszám",
  Address: "Cím",
  "Your comments": "Az Ön észrevételei",
  "How many guests?": "Hány vendég?",
  "Anything else we need to know?": "Van még valami, amit tudnunk kell?",
  "Guests:": "Vendégek:",
  Submit: "Beküldés",
  "Go to Calendar": "Nyissa meg a Naptár lehetőséget",
  "Registration completed successfully!":
    "A regisztráció sikeresen befejeződött!",
  "Please check your registered email address":
    "Kérjük, ellenőrizze regisztrált e-mail címét",
  "Add to Calendar": "Hozzáadás a naptárhoz",
  "Share this Event": "Ossza meg ezt az eseményt",
  "Sorry something went wrong": "Elnézést, valami nem ment jól",
  "Back to registration": "Vissza a regisztrációhoz",
  "Date & Location": "Dátum és hely",
  "Date & Time": "Dátum idő",
  home: "itthon",
  "Header align": "Fejléc igazítása",
  Footer: "Lábléc",
  "Categories Filter": "kategóriák Szűrés",
  "Show only upcoming": "Csak a közelgő megjelenítése",
  "Card(s) in a row": "Kártya (k) egymás után",
  "Space between cards": "Hely a kártyák között",
  "Shown events limit": "A megjelenített események korlátozása",
  "Style 1": "1. stílus",
  "Style 2": "2. stílus",
  "Style 3": "3. stílus",
  "Style 4": "4. stílus",
  "Buttons & Links": "Gombok és linkek",
  "Button corner radius": "Gomb sarok sugara",
  "Buttons font": "Gombok betűtípusa",
  "Buttons background": "Gombok háttér",
  "Get notified by Email": "Értesítést kap e-mailben",
  "Review events": "Tekintse át az eseményeket",
  "Click on date": "Kattintson a dátumra",
  "Add Event button": "Esemény gomb hozzáadása",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "A Naptár szinkronizálása lehetővé teszi az események és munkamenetek integrálását a Boom Naptárral.",
  connect: "csatlakozzon",
  "Synchronized Calendars": "Szinkronizált naptárak",
  "Import events": "Események importálása",
  Disconnect: "Kapcsolat bontása",
  "Choose calendar": "Válasszon naptárt",
  "Monitor your Wix events through the sync feature":
    "Figyelje a Wix eseményeit a szinkronizálási szolgáltatáson keresztül",
  "Connect all your Boom calendars available on your website":
    "Csatlakoztassa az összes webhelyén elérhető Boom-naptárt",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Ütemezzen, csatlakozzon és kezelje a Zoom értekezleteket közvetlenül a Boom naptárunkon keresztül.",
  "Monitor your Event Brite events through the Event Brite sync feature.":
    "Figyelje az Event Brite eseményeit az Event Brite szinkronizálási szolgáltatásán keresztül",
  Email: "Email",
  "Add-ons": "Kiegészítők",
  "Receive notification emails as soon as users add events to your calendar.":
    "Értesítési e-maileket kapunk, amint a felhasználók eseményeket adnak a naptárhoz.",
  "Enable + button on the calendar header":
    "Enable + button on the calendar header",
  "Accept or decline events added by customers before making them public.":
    "Elfogadja vagy csökkentse az ügyfelek által hozzáadott eseményeket, mielőtt nyilvánosságra hozná őket.",
  "Switch Add Event": "Kapcsoló hozzáadása esemény",
  "Enable your browser cookies to connect to your account.":
    "Engedélyezze a böngésző cookie-kat, hogy csatlakozzon fiókjához.",
  "Learn more": "Tudj meg többet",
  "Print Button": "Nyomtatás gomb",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Engedélyezze a felhasználók számára, hogy bármilyen dátumtartományban nyomtassák a Boom eseménynaptárát.",
  "Show Title on mobile": "A cím megjelenítése a mobilon",
  "Show Skeleton on mobile": "A csontváz megjelenítése a mobilon",
  "Start 7-day Business trial": "Indítsa el a 7 napos üzleti tárgyalást",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Élvezze az összes korlátlan funkciót, például jegyeket, regisztrációt, látogató esemény-kiegészítőket.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Kérjük, vegye figyelembe: A próbaidőszak végén visszaküldjük a meglévő előfizetési tervét.",
  "Not Now": "Nem most",
  "Start free trial": "Ingyenes próba indítása",
  "Congrats!": "Gratula!",
  "Your 7-day Business trial has been successfully activated.":
    "A 7 napos üzleti tárgyalás sikeresen aktiválódott.",
  Done: "Kész",
  "Title font color": "Cím betűtípus színe",
  "Desciption font color": "Leírás Font Szín",
  "Section font color": "Szakasz betűtípus színe",
  "Card Header": "Kártya fejléc",
  Category: "Kategória",
  "Display at the": "Megjelenik a",
  top: "top",
  bottom: "alsó",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Mutassa be a kategória-szűrőt a naptár tetején vagy alján.A beállítások csak napirendre és kártyára vonatkoznak",
  "Processing your events": "Az események feldolgozása",
  "Search for events": "Események keresése",
  "There are no events added": "Nincsenek események hozzáadva",
  "Location: To be determined": "Helyszín: Meg kell határozni",
  "No events for selected date": "Nincsenek események a kiválasztott dátumra",
  Uncategorized: "Nem kategorizálatlan",
  "Edit event": "Esemény szerkesztése",
  "Edit original event": "Eredeti esemény szerkesztése",
  "Copy event": "Másolási esemény",
  "Copy as new event": "Másoljon új eseményként",
  "Delete event": "Esemény törlése",
  "Stop repeating on this date": "Hagyd abba az ismétlést ezen a dátumon",
  "Exclude this date": "Kivéve ezt a dátumot",
  "Location is going to be announced": "A helyet bejelentik",
  "Fill your personal information": "Töltse ki személyes adatait",
  "Check Box": "Jelölőnégyzet",
  "Single Choice": "Egyetlen választás",
  Option: "választási lehetőség",
  "Share Event": "Megosztási esemény",
  "Oops! Something went wrong": "Hoppá!Valami elromlott",
  "We are sorry this event has already taken place":
    "Sajnáljuk, hogy ez az esemény már megtörtént",
  "Back to calendar": "Vissza a naptárba",
  "This field is required": "Ez a mező kötelező",
  Phone: "Telefon",
  "Number field": "Számmező",
  "Please provide a valid email": "Kérjük, adjon meg érvényes e -mailt",
  "Select at least one option": "Válasszon legalább egy lehetőséget",
  "Choose tickets to see total value":
    "Válassza a Jegyeket a teljes érték megtekintéséhez",
  tickets: "jegyek",
  "Choose Tickets": "Válassza a Jegyeket",
  "Choose payment method": "Válassz fizetési módot",
  Pay: "Fizetés",
  Total: "Teljes",
  Free: "Ingyenes",
  "Buy tickets": "Jegyeket vesz",
  "Sold Out": "Elkelt",
  "Tickets are available": "Jegyek elérhetők",
  "Sales End": "Értékesítési cél",
  "Availible from": "elérhető ekkortól",
  "Go to Orders": "Menjen a megrendelésekre",
  "Go to Details": "Lépjen a részletekre",
  "Group ticket": "Csoportjegy",
  Name: "Név",
  Price: "Ár",
  "Order by": "Rendezés",
  "Order ID": "Rendelés azonosító",
  Applied: "Alkalmazott",
  Fees: "Díj",
  "Enter promo code": "Írja be a promóciós kódot",
  Apply: "Alkalmaz",
  "Promo Code": "Promóciós kód",
  Cash: "Készpénz",
  "You can find your e-tickets attached to your email or download them":
    "Megtalálhatja az e-mailhez csatolt e-jegyeket, vagy letöltheti azokat",
  here: "itt",
  Time: "Idő",
  "Invalid promo code": "Érvénytelen promóciós kód",
  "Credit card": "Hitelkártya",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Hamarosan megerősítő üzenetet kap a sikeres regisztrációról az e -mail címére.",
  "You can also check your order details below.":
    "Az alábbiakban ellenőrizheti a megrendelés részleteit is.",
  at: "nál nél",
  Buy: "megvesz",
  Donation: "Adomány",
  "Enter price": "Vállalkozás",
  Choose: "Választ",
  Chosen: "Választott",
  "Choose your plan": "Válassza ki a tervét",
  week: "hét",
  wk: "hét",
  "Choose plan cycle": "Válassza a Planciklus lehetőséget",
  months: "hónapok",
  years: "évek",
  weeks: "hetek",
  "Copy Event Url": "Másolja az esemény URL -jét",
  "You can find your e-tickets attached to your email or print them":
    "Megtalálhatja az e-mailhez csatolt e-jegyeket, vagy kinyomtathatja azokat",
  "Guest Info": "Vendéginformáció",
  "Ticket Info": "Jegyinformáció",
  "Ticket name": "Jegynév",
  "Ticket price": "Jegyár",
  "Ticket ID": "Jegy -azonosító",
  "If you have any questions contact to organizer":
    "Ha bármilyen kérdése van, vegye fel a kapcsolatot a szervezővel",
  "As soon as event ends": "Amint az esemény véget ér",
  "1 day after event ends": "1 nappal az esemény vége után",
  "7 days after event ends": "7 nappal az esemény vége után",
  "14 days after event ends": "14 nappal az esemény vége után",
  "30 days after event ends": "30 nappal az esemény vége után",
  Menu: "Menü",
  "No event for selected date": "Nincs esemény a kiválasztott dátumra",
  view: "Kilátás",
  List: "Lista",
  Year: "Év",
  "Yearly Style": "Évi stílus",
  "There are no events": "Nincsenek események",
  Autotranslation: "Autotranszláció",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Ha engedélyezve van, a naptári widget a webhely nyelvén alapul.* Ne feledje, hogy mindaddig, amíg a naptár címe, és a leírások be vannak adva szövegek, amelyeket nem lehet lefordítani.",
  "Note on mobile": "Megjegyzés a mobilon",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Kapcsolja ki vagy módosítsa a 'Nincs esemény' sáv szövegét a naptár mobil verzióján",
  Autodeletion: "Autodelezés",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Az opció engedélyezése automatikusan eltávolítja a múltbeli eseményeket a naptárból.",
  "This does not apply to repeating events!":
    "Ez nem vonatkozik az események megismétlésére!",
  "Notify event creators about the guest":
    "Értesítse a felhasználókat a vendégről",
  "Send event creators notification emails as soon as guests register for their events":
    "Küldje el az eseménykészítők értesítési e-mailjeit, amint a vendégek regisztrálnak az eseményeikre",
  "List View Type": "Lista nézet típusa",
  Yearly: "Évi",
  "Year view header": "Év nézet fejléc",
  "Description font": "Leírás betűtípus",
  Connect: "csatlakozzon",
  "You have no events": "आपका कोई कार्यक्रम नहीं है",
  Synchronize: "सिंक्रनाइज़",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "A Google Naptár Sync lehetővé teszi az események és munkamenetek integrálását a Boom naptárával.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Az Outlook Naptár szinkronizálása lehetővé teszi az események és munkamenetek integrálását a Boom naptárral.",
  "Your message has been sent successfully!":
    "आपका संदेश सफलतापूर्वक प्रेषित किया गया!",
  "There are no synchronized calendars": "Nincsenek szinkronizált naptárak",
  "to view more than 7 events": "több mint 7 esemény megtekintéséhez",
  "Mobile app": "Mobil alkalmazás",
  "Admin Account": "व्यवस्थापक लेखा",
  Password: "Jelszó",
  "Second User": "दूसरा उपयोगकर्ता",
  Edit: "Szerkesztés",
  "Guest limit": "Vendégkorlát",
  "All-day": "Egész nap",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Az összes helyi beállítás (automatikus) az Ön nyelvén alapul.Ha a nyelved a listán szerepel, nincs szükség a szakasz testreszabására.",
  available: "elérhető",
  next: "következő",
  Tickets: "Jegyek",
  Quantity: "Mennyiség",
  "Promo code": "Promóciós kód",
  "Select a payment method": "Válassz fizetési módot",
  Fee: "Díj",
  Book: "Könyv",
  "All the tickets have been sold out": "Minden jegyet elfogyott",
  "Choose at least one ticket": "Válasszon legalább egy jegyet",
  "First choose ticket": "Először válasszon jegyet",
  "Please fill out your personal information.":
    "Kérjük, töltse ki személyes adatait.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "A sikeres vásárláshoz válassza ki a kívánt fizetési módot, és írja be a kedvezményes jegyek promóciós kódját.",
  "Credit/Debit card": "Hitel- / betéti kártya",
  "print here.": "Nyomtatás itt.",
  "QR code for all tickets": "QR-kód minden jegyhez",
  Duration: "Időtartam",
  "Full Name": "Teljes név",
  "Ticket id": "Jegyazonosító",
  "Group id": "Csoportazonosító",
  "Choose your ticket.": "Válassza ki a jegyét.",
  "Fill out your personal information.": "Töltse ki személyes adatait.",
  "Add the payment details.": "Adja hozzá a fizetési adatokat.",
  "To be determined": "Meg kell határozni",
  "You can find your e-tickets attached to the email or":
    "Megtalálhatja az e-mailhez csatolt e-jegyeket, vagy",
  "print here": "Nyomtatás itt",
  "Full name": "Teljes név",
  "Group ID": "Csoportazonosító",
  "to Book": "foglalni",
  "Unfortunately, your card has been declined":
    "Sajnos a kártyáját elutasították",
  "Thank you for your purchase!": "Köszönjük a vásárlást!",
  "Find your printable e-tickets attached to the confirmation email":
    "Keresse meg a megerősítő e-mailhez csatolt nyomtatható e-jegyeket",
  Confirm: "megerősít",

  "Add event": "Esemény hozzáadása",
  Events: "Események",
  "Event details": "Esemény részletei",
  Registration: "Bejegyzés",
  "Guests list": "A vendégek listája",
  Ticket: "Jegy",
  "General Info": "Általános információ",
  "Customize the general settings of your event":
    "Testreszabhatja az esemény általános beállításait",
  "Event Title": "Rendezvény címe",
  "e.g. Birthday Party": "például. Szülinapi buli",
  "All Day Event": "Egész napos esemény",
  Cross: "Kereszt",
  Timeline: "Idővonal",
  "Repeating event": "Ismétlődő esemény",
  Location: "Elhelyezkedés",
  "Venue name": "Helyszín neve",
  Description: "Leírás",
  Image: "Kép",
  Color: "Szín",
  Category: "Kategória",
  "Add your events to color categories and let your users classify them easily":
    "Adja hozzá eseményeit a színkategóriákhoz, és hagyja, hogy a felhasználók könnyen osztályozzák őket",
  "Category name": "Kategória név",
  "e.g. Birthdays": "például. Születésnapok",
  Venue: "Helyszín",
  "Where the event takes place": "Ahol az esemény zajlik",
  "Venue name": "Helyszín neve",
  "Venue phone": "Helyszíni telefon",
  "Venue email": "Helyszín e -mail",
  "Venue website": "Helyszín",
  Organizer: "Szervező",
  "Person who makes the event": "Személy, aki az eseményt készíti",
  "Organizer name": "Szervező neve",
  "Organizer phone": "Szervező telefon",
  "Organizer email": "Szervező e -mail",
  "Organizer website": "Szervező webhely",
  Save: "Megment",
  Cancel: "Megszünteti",
  Import: "Behozatal",
  Past: "Múlt",
  All: "Minden",
  Upcoming: "Közelgő",
  Uncategorised: "Nem kategorizálatlan",
  "Date Ascending": "Dátum emelkedő",
  "Date Descending": "Dátum leszállni",
  "Title by A-Z": "Címe: A-Z",
  "Title by Z-A": "Címe: Z-A",
  "There are no events for this period":
    "Nincsenek események erre az időszakra",

  "Auto-Convert Date & Time": "Auto-konvert dátum és idő",
  TimeZone: "Időzóna",
  Autodeletion: "Autodelezés",
  "Layout Settings": "Elrendezési beállítások",
  "Yeatly view": "Yeatly View",
  "Monthly view header": "Havi nézet fejléc",
  "Weekly/Daily view header": "Heti/napi nézet fejléc",
  Acendings: "Acendings",
  Descending: "Leszálló",
  Standart: "Standár",
  Silver: "Ezüst",
  Retro: "Retro",
  Dark: "Sötét",
  Night: "Éjszaka",
  Aubergine: "Padlizsán",
  "List view header": "Lista nézet fejléc",
  "Side by Side View": "Egymás melletti nézet",
  "Customize Proportions": "Testreszabhatja az arányokat",
  "Card Margins": "Kártya margók",
  "Image opacity (%)": "Képpacitás (%)",
  "Side by Side Header": "Egymás mellett fejléc",
  "Text Align": "Szöveg igazítás",
  "Timeline View": "Ütemterv nézet",
  "Title font color": "Cím betűtípus színe",
  "Desciption font color": "Leeresztési betűszín",
  "Line color": "Vonalszín",
  "Date Font color": "Dátum betűtípus színe",
  "Daily events background": "Napi események háttér",
  Alignment: "Igazítás",
  Vertical: "Függőleges",
  Horizontal: "Vízszintes",
  "Vertical Alignment": "Függőleges igazítás",
  Right: "Jobb",
  Center: "Központ",
  "Horizontal Alignment": "Vízszintes igazítás",
  Top: "Felső",
  Center: "Központ",
  Bottom: "Alsó",
  "Dates Circle Design": "Dátumok Körtervezés",
  "Next To The Circle": "A kör mellett",
  "In The Circle": "Körben",
  "Timeline Header": "Idővonal fejléc",
  Timeline: "Idővonal",
  "Show only upcoming": "Csak a közelgő mutasd",
  "Order by": "Rendezés",
  "Timeline Event Limit": "Ütemterv eseménykorlátozása",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Engedje meg, hogy a látogató eseményt adjon a helyi Calnedarshoz: Google, Yahoo, Outlook, Icalendar.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Engedje meg, hogy a látogató megossza eseményét a Facebook, a LinkedIn, a Twitter stb.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Adjon hozzá egy keresési opciót a naptárába, hogy az emberek cím, helyszín, stb. Keresés szerint keressék az eseményeket.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Engedje meg, hogy a felhasználók bármilyen dátumtartományban kinyomtassák a Boom eseménynaptárát.",
  "Click to apply a theme to Calendar":
    "Kattintson egy téma alkalmazására a naptárra",
  "Date container color": "Date konténer színe",
  "Daily events background": "Napi események háttér",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "A kiegészítők segítségével telepítse a fejlett funkciókat a naptárába, így funkcionálisabbá válik!",
  "Open Add-ons Store": "Nyissa meg a kiegészítő áruházat",
  Monday: "hétfő",
  Tuesday: "kedd",
  Wednesday: "szerda",
  Thursday: "csütörtök",
  Friday: "péntek",
  Saturday: "szombat",
  Sunday: "vasárnap",
  "Yearly view": "Éves nézet",
  Ascending: "Uzlazni",
  "Show event time next to title": "Mutassa meg az eseményidőt a cím mellett",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Állítsa be az esemény dátumát és időt a felhasználó helyi időpontjába az időzónájuk alapján.",
  "Display the time zone alongside the event date.":
    "Jelenítse meg az időzónát az esemény dátuma mellett.",
  "Show event time next to title": "Mutassa meg az eseményidőt a cím mellett",
  "Time Zone": "Időzóna",
  "Upload Image": "Feltöltés kép",
  "Choose a Category": "Válasszon kategóriát",
  "Color you have chosen will not be shown as you choose category":
    "A választott színt nem jelenik meg a kategória választásakor",
  Website: "Weboldal",
  Next: "Következő",
  Save: "Megment",
  "Last Name": "Vezetéknév",
  "Personal Info": "Személyes adatok",
  Back: "Vissza",
  "This field is required": "Ez a mező kötelező",
  "Your event has been submitted": "Az eseményedet benyújtották",
  "Enter a location": "Írjon be egy helyet",
  "Display the time zone alongside the event date.":
    "Jelenítse meg az időzónát az esemény dátuma mellett.",
  Home: "itthon",
  "Side By Side Event Limit": "Egymás melletti eseménykorlátozás",
  "Mobille App": "Mobille alkalmazás",
  category: "kategória",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Könnyen nyomon követheti menetrendjét, ha importálja Facebook eseményeit a naptárába.",
  "Synchronized Pages": "Szinkronizált oldalak",
  "There are no synchronized pages": "Nincsenek szinkronizált oldalak",
  "Choose page": "Válasszon oldalt",
  "You have no events": "Nincsenek eseményeid",
};
export default hu;
