let hy = {
  Categories: "Կատեգորիաներ",
  "Share this event": "Կիսվեք այս իրադարձությունից",
  Language: "Լեզու",
  "Show Time Zone": "Ցույց տալ ժամանակի գոտին",
  "Custom Local Settings": "Պատվերով տեղական պարամետրեր",
  "Add and showcase events on your site using a beautiful calendar.":
    "Ձեր կայքում ավելացնել եւ ցուցադրել իրադարձություններ, օգտագործելով գեղեցիկ օրացույց:",
  "Week Days": "Շաբաթվա օր",
  "Manage Events": "Կառավարեք իրադարձությունները",
  General: "Ընդհանուր",
  "Layout Picker": "Դասավորության ընտրություն",
  Month: "Ամիս",
  Monthly: "Ամսական",
  Week: "Շաբաթ",
  Weekly: "Շաբաթական",
  Day: "Օր",
  Daily: "Օրական",
  Agenda: "Օրակարգ",
  "Navigation Buttons": "Նավիգացիոն կոճակներ",
  "Week numbers": "Շաբաթվա համարներ",
  "Include Weekends": "Ներառեք հանգստյան օրերը",
  "All-day": "Ամբողջ օրը",
  "All Day": "Ամբողջ օրը",
  Label: "Պիտակ",
  "Fit to Height": "Տեղավորվում է բարձրությանը",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Ծրագրերի համամասնությունները դնելու համար Manully անջատեք այս տարբերակը եւ չափափոխեք խմբագրին:",
  "Default Layout": "Լռելյայն դասավորություն",
  "Monthly view": "Ամսական դիտում",
  "Weekly and Daily view": "Շաբաթվա եւ ամենօրյա տեսակետ",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Այցելուներին կարող եք ավելի կայուն փորձ տալ, միանգամից նույնքան շաբաթներ (6) ցույց տալով:",
  "Fixed Weekly Layout": "Հաստատուն շաբաթական դասավորություն",
  back: "Հետ",
  Back: "Հետ",
  Row: "Թիավարում",
  "Hours in Weekly View": "Ժամեր շաբաթական տեսանկյունից",
  "Hours in Daily View": "Ժամեր ամենօրյա տեսանկյունից",
  Start: "Սկիզբ",
  End: "Վերջ",
  "At This Hour": "Այս ժամին",
  Button: "Կոճղ",
  Buttons: "Կոճակներ",
  Sunday: "Կիրակի",
  Monday: "Երկուշաբթի",
  Tuesday: "Երեքշաբթի",
  Wednesday: "Չորեքշաբթի",
  Thursday: "Հինգշաբթի",
  Friday: "Ուրբաթ",
  Saturday: "Շաբաթ",
  "Default Date": "Լռելյայն ամսաթիվը",
  year: "տարի",
  month: "ամիս",
  mo: "ժամանակ",
  days: "օր",
  ago: "առաջ",
  ahead: "առաջ",
  Yesterday: "Երեկ",
  Today: "Այսօր",
  Tomorrow: "Վաղը",
  Custom: "Մաքսատուրք",
  "Set Daily Rows Limit": "Սահմանեք ամենօրյա տողերի սահմանը",
  "Set Proportions": "Սահմանեք համամասնություններ",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Թույլ տվեք այցելուին ավելացնել իրադարձություն տեղական հանգստավայրերին. Google, Yahoo, Outlook, iCalendar:",
  Container: "Բեռնարկղ",
  Background: "Նախապատմել",
  "Container Background": "Բեռնարկղային ֆոն",
  "Container Borders": "Բեռնարկղային սահմաններ",
  Calendar: "Օրացույց",
  "Event Info Tooltip": "Իրադարձության մասին տեղեկատվության գործիքակազմ",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Երբ մարդիկ սավառնում են մի իրադարձության, նրանք կտեսնեն դրա մասին բոլոր տեղեկությունները գործիքակազմում:",
  "Event Info Window": "Միջոցառման մասին տեղեկությունների պատուհանը",
  "This is the full information window that opens when someone clicks on the event.":
    "Սա տեղեկատվական ամբողջական պատուհանն է, որը բացվում է, երբ ինչ-որ մեկը կտտացնում է իրադարձությունը:",
  "Use Gradient": "Օգտագործեք գրադիենտ",
  Vertical: "Ուղղաձիգ",
  Horizontal: "Հորիզոնական",
  First: "Առաջին",
  Second: "Երկրորդ",
  diagonal: "անկյունագիծ",
  Radial: "Ճառագայթային",
  "Select option": "Ընտրեք տարբերակ",
  Solid: "Ամուր",
  Dotted: "Կետավոր",
  Dashed: "Թեթլ",
  Double: "Կրկնակի",
  "Border Radius": "Սահմանային շառավիղ",
  Padding: "Լիցք",
  "Date Header": "Ամսաթիվ վերնագիր",
  "Event Default Color": "Իրադարձության կանխադրված գույնը",
  "Days of Week": "Շաբաթվա օրեր",
  "Days of Week Background": "Շաբաթվա օրերի նախապատմություն",
  Date: "Ժամադրություն",
  "Event Title": "Միջոցառման վերնագիր",
  "Highlight today": "Ներկայացրեք այսօր",
  "Highlight Color": "Կարեւորեք գույնը",
  Hide: "Թաքցնել",
  "Calendar Border Color": "Օրացույցի սահմանի գույնը",
  "Calendar Border Width": "Օրացույցի սահմանի լայնությունը",
  "Calendar Border Style": "Օրացույցի սահմանային ոճը",
  "Font Color": "Տառատեսակի գույնը",
  "Event Background": "Իրադարձության ֆոն",
  "Card Date Color": "Քարտի ամսաթվի գույն",
  "Title Font": "Վերնագրի տառատեսակ",
  "Date Font": "Ամսագրի տառատեսակ",
  "Description Font": "Նկարագրություն Տառատեսակ",
  "Button Background": "Կոճակի ֆոն",
  "Button Text": "Կոճակի տեքստ",
  "Border Color": "Սահմանային գույն",
  "Border Width": "Սահմանի լայնությունը",
  "Border Type": "Սահմանի տեսակը",
  Title: "Կոչում",
  Description: "Նկարագրություն",
  "Background Color": "Ֆոնի գույնը",
  Divider: "Ստորաքարշ",
  "Event Details Font": "Իրադարձության մանրամասները տառատեսակ",
  "Website Link Color": "Վեբ կայքի կապի գույնը",
  "Developer Info": "Հեղինակային տվյալներ",
  "User Guide": "Ուղեցույց",
  "Support e-mail": "Աջակցեք էլ. Փոստին",
  "Our Website": "Մեր կայքը",
  "App Review": "Ծրագրի ակնարկ",
  "Enjoying App? Leave us a review in the App Market.":
    "Վայելել ծրագիրը: Թողեք մեզ ակնարկ ծրագրի շուկայում:",
  "Review Us": "Վերանայեք մեզ",
  "Connect With Us": "Միացեք մեզ հետ",
  "What's your email?": "Որն է ձեր էլ.",
  "Invalid email address!": "Էլ.փոստի անվավեր հասցե:",
  Comments: "Մեկնաբանություններ",
  "We'd love to hear from you. Send us a message.":
    "Մենք կցանկանայինք լսել ձեզնից: Ուղարկեք մեզ հաղորդագրություն:",
  "Message must be at least 5 characters long":
    "Հաղորդագրությունը պետք է լինի առնվազն 5 նիշ",
  Send: "Ուղարկել",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Եթե ​​ցանկանում եք թույլ տալ օգտագործողին փոխել օրացույցային դիտումների միջեւ, միացնել այս տարբերակը եւ ընտրել այն տեսակետները, որոնք ցանկանում եք ցույց տալ:",
  Main: "Գլխավոր",
  Localize: "Տեղավորել",
  Settings: "Կարգավորումներ",
  Layouts: "Դասավորություններ",
  Advanced: "Առաջ քաշված",
  Design: "Դիզայն",
  Support: "Աջակցություն",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Տեղական բոլոր պարամետրերը (ինքնաբերաբար) են ձեր լեզվի հիման վրա: Եթե ​​ձեր լեզուն ցուցակի մեջ է, այս բաժինը հարմարեցնելու կարիք չկա:",
  "Date Format": "Ամսաթիվ ձեւաչափ",
  "Time Format": "Ժամանակի ձեւաչափ",
  "Text Direction": "Տեքստի ուղղություն",
  "Left to Right": "Ձախից աջ",
  "Right to Left": "Ձախից աջ",
  "Week Starts On": "Շաբաթը սկսվում է",
  "Agenda Style": "Օրակարգ ոճը",
  Classic: "Դասական",
  Modern: "Ժամանակակից",
  "Agenda Header": "Օրակարգի վերնագիր",
  "Upcoming Events": "Սպասվող իրադարձություններ",
  "Agenda Event Limit": "Օրակարգի իրադարձության սահմանը",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Արդիականացրեք հիմա եւ շատ ավելի շատ հատկություններ ստացեք եւ ամբողջությամբ վայելեք ձեր ծրագիրը:",
  "Upgrade Now": "Թարմացնել հիմա",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Հոստինգի իրադարձություններ, որոնք տեւում են ամբողջ օրը: Սա ձեզ հնարավորություն է տալիս ցույց տալ դրանք ձեր օրացույցում:",
  "24 hours": "24 ժամ",
  Sat: "Շբթ",
  Sun: "Կրկ",
  Mon: "Երկ",
  Default: "Թերություն",
  "Select custom design style for your calendar.":
    "Ընտրեք ձեր օրացույցի համար պատրաստված ձեւավորման ոճը:",
  Style: "Ոճ",
  "Styles and Colors": "Ոճեր եւ գույներ",
  "Calendar Name": "Օրացույցի անվանումը",
  "Write your Calendar name here": "Գրեք ձեր օրացույցի անունը այստեղ",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Սա տեսանելի չէ ձեր օգտագործողների համար: Անուններ տեղադրեք ձեր օրացույցները տարբերելու համար, երբ օգտագործում եք Boom Calendar Sync գործառույթը:",
  "General Info": "Ընդհանուր տեղեկություններ",
  Venue: "Տեղ",
  Organizer: "Կազմակերպիչ",
  Search: "Որոնել",
  "Add to": "Ավելացնել",
  calendar: "օրացույց",
  "Copy event URL": "Պատճենել իրադարձությունների URL",
  "Copied!": "Պատճենված:",
  "Add & Share": "Ավելացնել եւ կիսվել",
  Map: "Քարտեզ",
  "Calendar view": "Օրացույցի դիտում",
  "Add Event": "Ավելացնել իրադարձություն",
  Uncategorised: "Չդասակարգված",
  More: "Ավելի շատ",
  Less: "Ավելի քիչ",
  Register: "Գրանցվել",
  Card: "Քարտ",
  Guests: "Հյուրեր",
  unlimited: "անսահմանափակ",
  "Show more": "Ցույց տալ ավելին",
  "Enable Search": "Միացնել որոնումը",
  "+ Add Event": " + Ավելացնել իրադարձություն",
  "Manage and Sync": "Կառավարեք եւ համաժամեցրեք",
  "Show event details as...":
    "Ցուցադրել իրադարձության մանրամասները, ինչպես ...",
  Tooltip: "Փաստաթղթեր",
  Popup: "Թռուցիկ",
  None: "Ոչ ոք",
  "Show Category": "Second ուցադրել կատեգորիա",
  "Header Align": "Վերնագիր",
  "Show Time": "Ցույց տալ ժամանակը",
  "Hours in Weekly/Daily View": "Ժամեր ամեն շաբաթ / ամենօրյա տեսարանում",
  "Share Events": "ԿԻՍՎԵԼ Իրադարձություններ",
  Shadow: "Ստվեր",
  "Inner Padding": "Ներքին լիցք",
  Text: "Տեքստ",
  "Active Button Border": "Ակտիվ կոճակի սահման",
  "Light Mode": "Թեթեւ ռեժիմ",
  "Event Text Color": "Իրադարձության տեքստի գույն",
  Dates: "Ամսաթվեր",
  Skeleton: "Կմախք",
  "Skeleton Color": "Կմախքի գույնը",
  Width: "Լայնություն",
  "Skeleton Style": "Կմախքի ոճը",
  Color: "Գույն",
  "Section Titles": "Բաժնի վերնագրեր",
  "Section Content": "Բաժնի պարունակություն",
  Header: "Վերնագիր",
  Standard: "Ստանդարտ",
  Retro: "Ռետրո",
  Silver: "Արծաթ",
  Night: "Գիշերօթիկ",
  Dark: "Մութ",
  Aubergine: "Սմբուկ",
  "Map Header": "Քարտեզի վերնագիր",
  "Show Title in mobile": "Ցուցադրել վերնագիրը բջջայինում",
  "Card View": "Քարտի դիտում",
  "Card background color": "Քարտի ֆոնի գույնը",
  "Title font": "Վերնագրի տառատեսակ",
  "Desciption font": "ՆԱԽԱԳԾԻ Տառատեսակ",
  "Section font": "Բաժնի տառատեսակ",
  "Section divider color": "Բաժնի բաժանարար գույն",
  "Add event": "Ավելացնել իրադարձություն",
  "All Day Event": "Ամբողջ օրվա իրադարձություն",
  Location: "Գտնվելու վայր",
  "Choose a category": "Ընտրեք կատեգորիա",
  "Venue name": "Տեղի անվանումը",
  "Venue phone": "Տեղի հեռախոս",
  "Venue email": "Տեղի էլ",
  "Venue website": "Տեղի կայք",
  "Organizer name": "Կազմակերպչի անունը",
  "Organizer phone": "Կազմակերպիչ հեռախոս",
  "Organizer email": "Կազմակերպիչ էլ",
  "Organizer website": "Կազմակերպչի կայք",
  "Personal info": "Անձնական տեղեկություն",
  "First name": "Անուն",
  "Last Name": "Ազգանուն",
  "Email Address": "Էլեկտրոնային հասցե",
  "Additional Notes": "լրացուցիչ նշումներ",
  Save: "Խնայել",
  Next: "Հաջորդ",
  "Your event has been submitted": "Ձեր իրադարձությունը ներկայացվել է",
  "Event submittion has been failed": "Event Event Enginesstion- ը ձախողվել է",
  "e.g. Birthday Party": "Է.Գ. Ծննդյան Խնջույք",
  "First Name": "Անուն",
  "Last Name": "Ազգանուն",
  "Phone Number": "Հեռախոսահամար",
  Address: "Ուղերձ",
  "Your comments": "Ձեր մեկնաբանությունը",
  "How many guests?": "Քանի հյուր:",
  "Anything else we need to know?": "Ուրիշ բան, որ մենք պետք է իմանանք:",
  "Guests:": "Հյուրեր.",
  Submit: "Ներկայացնել",
  "Go to Calendar": "Գնալ օրացույց",
  "Registration completed successfully!": "Գրանցումը հաջողությամբ ավարտվեց:",
  "Please check your registered email address":
    "Խնդրում ենք ստուգել ձեր գրանցված էլփոստի հասցեն",
  "Add to Calendar": "Ավելացնել օրացույցին",
  "Share this Event": "Կիսվեք այս իրադարձությունից",
  "Sorry something went wrong": "Կներեք ինչ-որ բան սխալ է եղել",
  "Back to registration": "Վերադառնալ գրանցման",
  "Date & Location": "Ամսաթիվ եւ գտնվելու վայր",
  "Date & Time": "Ամսաթիվ եւ ժամանակ",
  home: "տուն",
  "Header align": "Վերնագիր",
  Footer: "Ոտնաթաթ",
  "Categories Filter": "Կատեգորիաներ Զտիչ",
  "Show only upcoming": "Ցուցադրել միայն առաջիկա",
  "Card(s) in a row": "Քարտ (ներ) անընդմեջ",
  "Space between cards": "Տիեզերք քարտերի միջեւ",
  "Shown events limit": "Sh ուցադրված իրադարձությունների սահմանը",
  "Style 1": "Ոճ 1",
  "Style 2": "Ոճ 2",
  "Style 3": "Ոճ 3",
  "Style 4": "Ոճ 4",
  "Buttons & Links": "Կոճակներ եւ հղումներ",
  "Button corner radius": "Կոճակի անկյունային շառավիղ",
  "Buttons font": "Կոճակների տառատեսակ",
  "Buttons background": "Կոճակների ֆոն",
  "Get notified by Email": "Տեղեկացեք էլ. Փոստով",
  "Review events": "Վերանայեք իրադարձությունները",
  "Click on date": "Կտտացրեք Ամսաթիվը",
  "Add Event button": "Ավելացնել իրադարձության կոճակ",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Օրացույցի համաժամացումը թույլ է տալիս ինտեգրվել ձեր իրադարձությունները եւ նստաշրջանները ձեր բում օրացույցով:",
  connect: "միացնել",
  "Synchronized Calendars": "Սինխրոնացված օրացույցներ",
  "Import events": "Ներմուծում իրադարձություններ",
  Disconnect: "Անջատել",
  "Choose calendar": "Ընտրեք օրացույց",
  "Monitor your Wix events through the sync feature":
    "Դիտեք ձեր Wix- ի իրադարձությունները համաժամացման գործառույթի միջոցով",
  "Connect all your Boom calendars available on your website":
    "Միացրեք ձեր բոլոր Boom Calendars- ը ձեր կայքում",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Ժամանակացույց, միացեք եւ կառավարեք մեծացնելու հանդիպումները հենց մեր բում օրացույցի միջոցով:",
  "Monitor your Event Brite events through the Event Brite sync feature.":
    "Դիտեք ձեր իրադարձության համար նախատեսված իրադարձությունները Միջոցառման միջոցով Brite Sync Feature",
  Email: "Էլ",
  "Add-ons": "Լրացումներ",
  "Receive notification emails as soon as users add events to your calendar.":
    "Ստացեք ծանուցման էլ. Փոստեր, քանի որ օգտվողները ձեր օրացույցին միջոցառումներ են ավելացնում:",
  "Enable + button on the calendar header": "Միացրեք + կոճակը Օրացույցի գլխին",
  "Accept or decline events added by customers before making them public.":
    "Ընդունել կամ մերժել հաճախորդների կողմից ավելացված իրադարձությունները, նախքան դրանք հրապարակելը:",
  "Switch Add Event": "Անջատեք Ավելացնել իրադարձություն",
  "Enable your browser cookies to connect to your account.":
    "Միացրեք ձեր զննարկչի բլիթները ձեր հաշվին միանալու համար:",
  "Learn more": "Իմացեք ավելին",
  "Print Button": "Տպել կոճակը",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Թույլ տվեք ձեր օգտագործողներին տպել ձեր Boom իրադարձության օրացույցը ցանկացած ամսաթվերի սահմաններում:",
  "Show Title on mobile": "Ցույց տալ վերնագիրը բջջայինով",
  "Show Skeleton on mobile": "Ցույց տալ կմախքը բջջայինի վրա",
  "Start 7-day Business trial": "Սկսեք 7-օրյա բիզնեսի դատավարությունը",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Վայելեք բոլոր անսահմանափակ առանձնահատկությունները, ինչպիսիք են վաճառքի տոմսերը, գրանցումը, այցելուի միջոցառման հավելումները:",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Խնդրում ենք նկատի ունենալ. Դատավարության ավարտին դուք կվերադարձվի ձեր առկա բաժանորդագրության պլանը:",
  "Not Now": "Ոչ հիմա",
  "Start free trial": "Սկսեք անվճար փորձարկում",
  "Congrats!": "Շնորհավորում ենք:",
  "Your 7-day Business trial has been successfully activated.":
    "Ձեր 7-օրյա բիզնեսի դատավարությունը հաջողությամբ ակտիվացել է:",
  Done: "Կատարած",
  "Title font color": "Վերնագրի տառատեսակի գույնը",
  "Desciption font color": "Նրբության տառատեսակի գույնը",
  "Section font color": "Բաժնի տառատեսակի գույնը",
  "Card Header": "Քարտի վերնագիր",
  Category: "Կատեգորիա",
  "Display at the": "Ցուցադրել",
  top: "գագաթ",
  bottom: "հատակից",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Ցուցադրել կատեգորիայի զտիչը օրացույցի վերեւում կամ ներքեւում: Պարամետրերը վերաբերում են միայն օրակարգի եւ քարտի դիտումներին",
  "Processing your events": "Ձեր իրադարձությունների վերամշակում",
  "Search for events": "Իրադարձություններ որոնում",
  "There are no events added": "Չկան ավելացված իրադարձություններ",
  "Location: To be determined": "Գտնվելու վայրը. Որոշվել",
  "No events for selected date": "Ընտրված ամսաթվի համար միջոցառում չկա",
  Uncategorized: "Չդասակարգված",
  "Edit event": "Խմբագրել իրադարձությունը",
  "Edit original event": "Խմբագրել բնօրինակ իրադարձությունը",
  "Copy event": "Պատճենել իրադարձություն",
  "Copy as new event": "Պատճենել որպես նոր իրադարձություն",
  "Delete event": "Ջնջել իրադարձությունը",
  "Stop repeating on this date": "Դադարեք կրկնել այս ամսաթվին",
  "Exclude this date": "Բացառեք այս ամսաթիվը",
  "Location is going to be announced": "Տեղադրությունը կհայտարարվի",
  "Fill your personal information": "Լրացրեք ձեր անձնական տեղեկությունները",
  "Check Box": "Ստուգման տուփ",
  "Single Choice": "Մեկ ընտրություն",
  Option: "Տարբերակ",
  "Share Event": "Համօգտագործման իրադարձություն",
  "Oops! Something went wrong": "Վայ: Ինչ որ բան այնպես չգնաց",
  "We are sorry this event has already taken place":
    "Sootoo ավում ենք, որ այս իրադարձությունն արդեն տեղի է ունեցել",
  "Back to calendar": "Վերադառնալ օրացույց",
  "This field is required": "Այս դաշտը պարտադիր է",
  Phone: "Հեռախոս",
  "Number field": "Գնորդի դաշտ",
  "Please provide a valid email": "Խնդրում ենք տրամադրել վավեր էլ",
  "Select at least one option": "Ընտրեք առնվազն մեկ տարբերակ",
  "Choose tickets to see total value":
    "Ընտրեք տոմսեր `ընդհանուր արժեքը տեսնելու համար",
  tickets: "տոմսեր",
  "Choose Tickets": "Ընտրեք տոմսեր",
  "Choose payment method": "Ընտրեք վճարման եղանակը",
  Pay: "Վճարել",
  Total: "Ընդհանուր",
  Free: "Անվճար",
  "Buy tickets": "Գնեք տոմսեր",
  "Sold Out": "Վաճառված է",
  "Tickets are available": "Տոմսերը մատչելի են",
  "Sales End": "Վաճառքի ավարտ",
  "Availible from": "Առկա է",
  "Go to Orders": "Գնացեք պատվերների",
  "Go to Details": "Գնալ մանրամասների",
  "Group ticket": "Խմբի տոմս",
  Name: "Անուն",
  Price: "Գինը",
  "Order by": "Պատվիրեք ըստ",
  "Order ID": "Պատվիրեք ID",
  Applied: "Կիրառական",
  Fees: "Վճար",
  "Enter promo code": "Մուտքագրեք պրոմո կոդ",
  Apply: "Կիրառել",
  "Promo Code": "Պրոմո Կոդ",
  Cash: "Կանխիկ",
  "You can find your e-tickets attached to your email or download them":
    "Դուք կարող եք գտնել ձեր էլ. Փոստի կցված ձեր էլեկտրոնային տոմսերը կամ ներբեռնել դրանք",
  here: "այստեղ",
  Time: "Ժամանակ",
  "Invalid promo code": "Անվավեր գովազդային կոդ",
  "Credit card": "ԿՐԵԴԻՏ քարտ",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Դուք շուտով կստանաք հաստատման հաստատման հաղորդագրություն ձեր էլ. Փոստի հասցեին:",
  "You can also check your order details below.":
    "Կարող եք նաեւ ստուգել ձեր պատվերի մանրամասները ստորեւ:",
  at: "մոտ",
  Buy: "Գնել",
  Donation: "Նվիրատվություն",
  "Enter price": "Մուտքագրեք գինը",
  Choose: "Ընտրել",
  Chosen: "Ընտրված",
  "Choose your plan": "Ընտրեք ձեր ծրագիրը",
  week: "շաբաթ",
  wk: "շշմեցնել",
  "Choose plan cycle": "Ընտրեք պլանի ցիկլը",
  months: "ամիս",
  years: "տարիներ",
  weeks: "շաբաթ",
  "Copy Event Url": "Պատճենել իրադարձությունների URL",
  "You can find your e-tickets attached to your email or print them":
    "Կարող եք գտնել ձեր էլ. Փոստով կցված ձեր էլեկտրոնային տոմսերը կամ տպել դրանք",
  "Guest Info": "Հյուրի տեղեկություններ",
  "Ticket Info": "Տոմսերի տեղեկություններ",
  "Ticket name": "Տոմսերի անվանումը",
  "Ticket price": "Տոմսերի գին",
  "Ticket ID": "Տոմսերի ID",
  "If you have any questions contact to organizer":
    "Եթե ​​ունեք որեւէ հարց, որը կապ ունեք կազմակերպիչին",
  "As soon as event ends": "Երբ իրադարձությունն ավարտվի",
  "1 day after event ends": "Իրադարձության ավարտից 1 օր անց",
  "7 days after event ends": "Միջոցառումից 7 օր անց ավարտվում է",
  "14 days after event ends": "Միջոցառումից 14 օր անց",
  "30 days after event ends": "Միջոցառումից 30 օր անց ավարտվում է",
  Menu: "Մենյու",
  "No event for selected date": "Ոչ մի իրադարձություն ընտրված ամսաթվի համար",
  view: "տեղավորել",
  List: "Ցուցակում",
  Year: "Տարի",
  Yearly: "Ամեն տարի",
  "Year view header": "Տարվա դիտում վերնագիր",
  "Yearly Style": "Տարեկան ոճը",
  "There are no events": "Միջոցառումներ չկան",
  Autotranslation: "Ինքնաթարգմանում",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Միացնելուց հետո ձեր օրացույցի widget- ը թարգմանվելու է կայքի լեզվի հիման վրա: * Նշեք, որ քանի դեռ օրացույցի վերնագիրն են, եւ նկարագրությունները մուտքագրված տեքստեր են, դրանք չեն կարող թարգմանվել:",
  "Note on mobile": "Նշում բջջայինում",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Անջատեք կամ փոխեք «Ոչ իրադարձություններ» բարի տեքստը Օրացույցի բջջային տարբերակի վրա",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Ընտրանքների միացումը, ավտոմատ կերպով կվերացնի ձեր անցյալի իրադարձությունները օրացույցից:",
  "This does not apply to repeating events!":
    "Սա չի տարածվում կրկնվող իրադարձությունների համար:",
  "Notify event creators about the guest":
    "Տեղեկացրեք իրադարձությունների ստեղծողներին հյուրի մասին",
  "Send event creators notification emails as soon as guests register for their events":
    "Ուղարկեք իրադարձություն Ստեղծողներ Տեղեկացման էլ. Փոստեր, երբ հյուրերը գրանցվեն իրենց իրադարձությունների համար",
  "List View Type": "Ցուցակի դիտման տեսակը",
  "Description font": "Նկարագրություն Տառատեսակ",
  Connect: "Միացնել",
  "You have no events": "Դուք միջոցառումներ չունեք",
  Synchronize: "Համաժամացնել",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Google Calendar Sync- ը թույլ է տալիս ինտեգրվել ձեր իրադարձությունները եւ նստաշրջանները ձեր բում օրացույցով:",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Outlook Calendar Sync- ը թույլ է տալիս ինտեգրվել ձեր իրադարձությունները եւ նստաշրջանները ձեր բում օրացույցով:",
  "Your message has been sent successfully!":
    "Ձեր հաղորդագրությունն ուղարկվել է հաջողությամբ:",
  "There are no synchronized calendars": "Սինխրոնային օրացույցներ չկան",
  "to view more than 7 events": "դիտելու ավելի քան 7 իրադարձություններ",
  "Mobile app": "Բջջային ծրագիր",
  "Admin Account": "Ադմինիստրատորի հաշիվ",
  Password: "Գաղտնաբառ",
  "Second User": "Երկրորդ օգտագործող",
  Edit: "Խմբագրել",
  "Guest limit": "Հյուրի սահմանը",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Տեղական բոլոր պարամետրերը (ինքնաբերաբար) են ձեր լեզվի հիման վրա: Եթե ​​ձեր լեզուն ցուցակի մեջ է, այս բաժինը հարմարեցնելու կարիք չկա:",
  available: "մատչելի",
  next: "հաջորդ",
  Tickets: "Տոմսեր",
  Quantity: "Քանակ",
  "Promo code": "Պրոմո Կոդ",
  "Select a payment method": "Ընտրեք վճարման եղանակ",
  Fee: "Վճար",
  Book: "Գիրք",
  "All the tickets have been sold out": "Բոլոր տոմսերը վաճառվել են",
  "Choose at least one ticket": "Ընտրեք առնվազն մեկ տոմս",
  "First choose ticket": "Նախ ընտրեք տոմս",
  "Please fill out your personal information.":
    "Խնդրում ենք լրացնել ձեր անձնական տվյալները:",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "Հաջողակ գնում կատարելու համար ընտրեք ձեր նախընտրած վճարման եղանակը եւ մուտքագրեք գովազդային ծածկագիրը զեղչված տոմսերի համար:",
  "Credit/Debit card": "Վարկային / դեբետային քարտ",
  "print here.": "Տպել այստեղ.",
  "QR code for all tickets": "QR կոդ բոլոր տոմսերի համար",
  Duration: "Տեւողությունը",
  "Full Name": "Ամբողջական",
  "Ticket id": "Տոմսերի ID",
  "Group id": "Խմբի ID",
  "Choose your ticket.": "Ընտրեք ձեր տոմսը:",
  "Fill out your personal information.": "Լրացրեք ձեր անձնական տվյալները:",
  "Add the payment details.": "Ավելացնել վճարման մանրամասները:",
  "To be determined": "Որոշվելու համար",
  "You can find your e-tickets attached to the email or":
    "Կարող եք գտնել էլ-նամակին կցված ձեր էլեկտրոնային տոմսերը կամ",
  "print here": "Տպել այստեղ",
  "Full name": "Ամբողջական",
  "Group ID": "Խմբի ID",
  "to Book": "Պատվիրել",
  "Unfortunately, your card has been declined":
    "Դժբախտաբար, ձեր քարտը մերժվել է",
  "Thank you for your purchase!": "Շնորհակալություն գնման համար:",
  "Find your printable e-tickets attached to the confirmation email":
    "Գտեք ձեր տպագրական էլեկտրոնային տոմսերը `հաստատման էլ. Փոստին",
  Confirm: "Հաստատել",

  "Add event": "Ավելացնել իրադարձություն",
  Events: "Իրադարձություններ",
  "Event details": "Միջոցառման մանրամասները",
  Registration: "Գրանցում",
  "Guests list": "Հյուրերի ցուցակ",
  Ticket: "Տոմս",
  "General Info": "Ընդհանուր տեղեկություններ",
  "Customize the general settings of your event":
    "Անհատականացրեք ձեր իրադարձության ընդհանուր պարամետրերը",
  "Event Title": "Միջոցառման վերնագիր",
  "e.g. Birthday Party": "Է.Գ. Ծննդյան Խնջույք",
  "All Day Event": "Ամբողջ օրվա իրադարձություն",
  Cross: "Խաչ",
  Timeline: "Ժամանակացույց",
  "Repeating event": "Կրկնող իրադարձություն",
  Location: "Գտնվելու վայր",
  "Venue name": "Տեղի անվանումը",
  Description: "Նկարագրություն",
  Image: "Պատկեր",
  Color: "Գույն",
  Category: "Կատեգորիա",
  "Add your events to color categories and let your users classify them easily":
    "Ձեր իրադարձությունները ավելացրեք գունային կատեգորիաների եւ թույլ տվեք, որ ձեր օգտվողները հեշտությամբ դասակարգեն դրանք",
  "Category name": "Կատեգորիայի անվանումը",
  "e.g. Birthdays": "Է.Գ. Ծննդյան տոները",
  Venue: "Տեղ",
  "Where the event takes place": "Որտեղ տեղի է ունենում իրադարձությունը",
  "Venue name": "Տեղի անվանումը",
  "Venue phone": "Տեղի հեռախոս",
  "Venue email": "Տեղի էլ",
  "Venue website": "Տեղի կայք",
  Organizer: "Կազմակերպիչ",
  "Person who makes the event": "Անձը, ով կատարում է իրադարձությունը",
  "Organizer name": "Կազմակերպչի անունը",
  "Organizer phone": "Կազմակերպիչ հեռախոս",
  "Organizer email": "Կազմակերպիչ էլ",
  "Organizer website": "Կազմակերպչի կայք",
  Save: "Խնայել",
  Cancel: "Չեղարկել",
  Import: "Ներմուծում",
  Past: "Անցյալ",
  All: "Բոլորը",
  Upcoming: "Գալիք",
  "Date Ascending": "Ամսաթիվ աճող",
  "Date Descending": "Ամսաթիվը իջնում ​​է",
  "Title by A-Z": "Վերնագիր A-Z- ի կողմից",
  "Title by Z-A": "Վերնագիր Z-A",
  "There are no events for this period":
    "Այս ժամանակահատվածի համար միջոցառումներ չկան",

  "Auto-Convert Date & Time": "Ավտոմատ փոխարկել ամսաթիվը եւ ժամանակը",
  TimeZone: "Ժամային գոտի",
  Autodeletion: "Ավտոմատ ջնջում",
  "Layout Settings": "Դասավորության կարգավորումներ",
  "Yeatly view": "Yeatly դիտում",
  "Monthly view header": "Ամսվա դիտման վերնագիր",
  "Weekly/Daily view header": "Շաբաթվա / ամենօրյա դիտման վերնագիր",
  Acendings: "Պայմաններ",
  Descending: "Իջնող",
  Standart: "Ստանդարտ",
  Silver: "Արծաթ",
  Retro: "Ռետրո",
  Dark: "Մութ",
  Night: "Գիշերօթիկ",
  Aubergine: "Սմբուկ",
  "List view header": "Մանրամասն Սայլակ",
  "Side by Side View": "Կողք կողքի դիտում",
  "Customize Proportions": "Անհատականացրեք համամասնությունները",
  "Card Margins": "Քարտի լուսանցքներ",
  "Image opacity (%)": "Պատկերի անթափանցիկություն (%)",
  "Side by Side Header": "Կողք կողքի վերնագիր",
  "Text Align": "Տեքստի հավասարեցրեք",
  "Timeline View": "Ժամանակացույցի դիտում",
  "Title font color": "Վերնագրի տառատեսակի գույնը",
  "Desciption font color": "Նրբության տառատեսակի գույնը",
  "Line color": "Տողի գույնը",
  "Date Font color": "Ամսաթվի տառատեսակի գույնը",
  "Daily events background": "Ամենօրյա իրադարձությունների ֆոն",
  Alignment: "Հավասարեցում",
  Vertical: "Ուղղաձիգ",
  Horizontal: "Հորիզոնական",
  "Vertical Alignment": "Ուղղահայաց հավասարեցում",
  Right: "Ճիշտ",
  Center: "Կենտրոն",
  "Horizontal Alignment": "Հորիզոնական հավասարեցում",
  Top: "Գագաթ",
  Center: "Կենտրոն",
  Bottom: "Հատակից",
  "Dates Circle Design": "Ամսաթվերի շրջանակի ձեւավորում",
  "Next To The Circle": "Շրջապատի կողքին",
  "In The Circle": "Շրջանակում",
  "Timeline Header": "Ժամկետային վերնագիր",
  Timeline: "Ժամանակացույց",
  "Show only upcoming": "Ցուցադրել միայն առաջիկա",
  "Order by": "Պատվիրեք ըստ",
  "Timeline Event Limit": "Ժամկետային իրադարձության սահմանը",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Թույլ տվեք այցելուին ավելացնել իրադարձություն տեղական հանգստավայրերին. Google, Yahoo, Outlook, iCalendar:",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Թույլ տվեք այցելուին կիսել ձեր իրադարձությունը Facebook- ում, LinkedIn- ին, Twitter- ին եւ այլն:",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Ձեր օրացույցում ավելացրեք որոնման տարբերակ, որպեսզի մարդիկ որոնեն ձեր իրադարձությունները վերնագրով, վայրով եւ այլով:",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Թույլ տվեք ձեր օգտագործողներին տպել ձեր Boom իրադարձության օրացույցը ցանկացած ամսաթվերի սահմաններում:",
  "Click to apply a theme to Calendar":
    "Կտտացրեք թեման օրացույցին կիրառելու համար",
  "Date container color": "Ամսաթվի բեռնարկղի գույնը",
  "Daily events background": "Ամենօրյա իրադարձությունների ֆոն",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Օգտագործեք հավելումները `ձեր օրացույցների վրա առաջադեմ առանձնահատկություններ տեղադրելու համար, դրանք ավելի ֆունկցիոնալ դարձնելով:",
  "Open Add-ons Store": "Բաց հավելյալ խանութ",
  Monday: "Երկուշաբթի",
  Tuesday: "Երեքշաբթի",
  Wednesday: "Չորեքշաբթի",
  Thursday: "Հինգշաբթի",
  Friday: "Ուրբաթ",
  Saturday: "Շաբաթ",
  Sunday: "Կիրակի",
  "Yearly view": "Տարեկան դիտում",
  Ascending: "Բարձրացող",
  "Show event time next to title":
    "Ցուցադրել իրադարձության ժամանակը վերնագրի կողքին",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Կարգավորեք իրադարձության ամսաթիվը եւ ժամանակը օգտագործողի տեղական ժամանակին, հիմնվելով իրենց ժամային գոտու վրա:",
  "Display the time zone alongside the event date.":
    "Display ուցադրել Ժամկետային գոտին իրադարձության ամսաթվի կողքին:",
  "Show event time next to title":
    "Ցուցադրել իրադարձության ժամանակը վերնագրի կողքին",
  "Show event time next to title":
    "Ցուցադրել իրադարձության ժամանակը վերնագրի կողքին",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Կարգավորեք իրադարձության ամսաթիվը եւ ժամանակը օգտագործողի տեղական ժամանակին, հիմնվելով իրենց ժամային գոտու վրա:",
  "Display the time zone alongside the event date.":
    "Ցուցադրել Ժամկետային գոտին իրադարձության ամսաթվի կողքին:",
  "Show event time next to title":
    "Ցուցադրել իրադարձության ժամանակը վերնագրի կողքին",
  "Time Zone": "Ժամային գոտի",
  "Upload Image": "Վերբեռնեք պատկերը",
  "Choose a Category": "Ընտրեք կատեգորիա",
  "Color you have chosen will not be shown as you choose category":
    "Ընտրած գույնը չի ցուցադրվի որպես կատեգորիա",
  Website: "Կայք",
  Next: "Հաջորդ",
  Save: "Պահպանել",
  "Last Name": "Ազգանուն",
  "Personal Info": "Անձնական տեղեկություն",
  Back: "Հետ",
  "This field is required": "Այս դաշտը պարտադիր է",
  "Your event has been submitted": "Ձեր իրադարձությունը ներկայացվել է",
  "Enter a location": "Մուտքագրեք գտնվելու վայրը",
  "Display the time zone alongside the event date.":
    "Ցուցադրել Ժամկետային գոտին իրադարձության ամսաթվի կողքին:",
  Home: "տուն",
  "Side By Side Event Limit": "Կողք կողքի իրադարձության սահմանաչափը",
  "Mobille App": "Mobile հավելված",
  category: "Կատեգորիա",
  Add: "Ավելացնել",
  "Mobile App": "Բջջային ծրագիր",
  username: "օգտագործողի անունը",
  password: "գաղտնաբառ",
  "Connect all your Boom calendars available on your website.":
    "Միացրեք ձեր բոլոր Boom Calendars- ը ձեր կայքում:",
  "Monitor your Wix events through the sync feature.":
    "Դիտեք ձեր Wix- ի իրադարձությունները համաժամացման գործառույթի միջոցով:",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Հեշտությամբ հետևեք ձեր ժամանակացույցին՝ ներմուծելով ձեր Facebook իրադարձությունները ձեր օրացույց:",
  "Synchronized Pages": "Սինքրոնացված էջեր",
  "There are no synchronized pages": "Սինքրոնացված էջեր չկան",
  "Choose page": "Ընտրեք էջը",
  "You have no events": "Դուք միջոցառումներ չունեք",
};
export default hy;
