let id = {
  Categories: "Kategori",
  "Share this event": "Bagikan acara ini",
  Language: "Bahasa",
  "Show Time Zone": "Tunjukkan zona waktu",
  "Custom Local Settings": "Pengaturan lokal khusus",
  "Add and showcase events on your site using a beautiful calendar.":
    "Tambah dan tunjukkan acara di situs Anda menggunakan kalender yang indah.",
  "Week Days": "Hari minggu",
  "Manage Events": "Kelola acara",
  General: "Umum",
  "Layout Picker": "Pemetik tata letak",
  Month: "Bulan",
  Monthly: "Bulanan",
  Week: "Pekan",
  Weekly: "Mingguan",
  Day: "Hari",
  Daily: "Sehari-hari",
  Agenda: "Jadwal acara",
  "Navigation Buttons": "Tombol navigasi",
  "Week numbers": "Nomor minggu",
  "Include Weekends": "Termasuk akhir pekan",
  "All-day": "Sepanjang hari",
  "All Day": "Sepanjang hari",
  Label: "Label",
  "Fit to Height": "Cocok dengan tinggi",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Untuk mengatur proporsi aplikasi secara manulal menonaktifkan opsi ini dan mengubah ukuran kalender di editor.",
  "Default Layout": "Tata letak default",
  "Monthly view": "Tampilan bulanan",
  "Weekly and Daily view": "Tampilan mingguan dan harian",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Anda dapat memberi pengunjung pengalaman yang lebih konsisten dengan menunjukkan jumlah minggu yang sama (6) sekaligus.",
  "Fixed Weekly Layout": "Tetap tata letak mingguan",
  back: "kembali",
  Row: "Baris",
  "Hours in Weekly View": "Berjam -jam dalam tampilan mingguan",
  "Hours in Daily View": "Berjam -jam dalam tampilan harian",
  Start: "Awal",
  End: "Akhir",
  "At This Hour": "Pada jam ini",
  Button: "Tombol",
  Buttons: "Tombol",
  Sunday: "Minggu",
  Monday: "Senin",
  Tuesday: "Selasa",
  Wednesday: "Rabu",
  Thursday: "Kamis",
  Friday: "Jumat",
  Saturday: "Sabtu",
  "Default Date": "Tanggal default",
  year: "tahun",
  month: "bulan",
  mo: "mo",
  days: "hari -hari",
  ago: "yang lalu",
  ahead: "di depan",
  Yesterday: "Kemarin",
  Today: "Hari ini",
  Tomorrow: "Besok",
  Custom: "Kebiasaan",
  "Set Daily Rows Limit": "Tetapkan batas baris harian",
  "Set Proportions": "Menetapkan proporsi",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Izinkan pengunjung untuk menambahkan acara ke calnedars lokal: Google, Yahoo, Outlook, icalendar.",
  Container: "Wadah",
  Background: "Latar belakang",
  "Container Background": "Latar belakang wadah",
  "Container Borders": "Perbatasan kontainer",
  Calendar: "Kalender",
  "Event Info Tooltip": "Acara Info Tooltip",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Ketika orang -orang melayang di atas suatu acara, mereka akan melihat semua info tentang hal itu di tooltip.",
  "Event Info Window": "Jendela Info Acara",
  "This is the full information window that opens when someone clicks on the event.":
    "Ini adalah jendela informasi lengkap yang terbuka ketika seseorang mengklik acara tersebut.",
  "Use Gradient": "Gunakan gradien",
  Vertical: "Vertikal",
  Horizontal: "Horisontal",
  First: "Pertama",
  Second: "Kedua",
  diagonal: "diagonal",
  Radial: "Radial",
  "Select option": "Pilih opsi",
  Solid: "Padat",
  Dotted: "Burik",
  Dashed: "Putus -putus",
  Double: "Dobel",
  "Border Radius": "Radius perbatasan",
  Padding: "Lapisan",
  "Date Header": "Header tanggal",
  "Event Default Color": "Warna default acara",
  "Days of Week": "Hari-hari dalam seminggu",
  "Days of Week Background": "Latar belakang hari dalam seminggu",
  Date: "Tanggal",
  "Event Title": "Judul acara",
  "Highlight today": "Sorot hari ini",
  "Highlight Color": "Warna Sorotan",
  Hide: "Bersembunyi",
  "Calendar Border Color": "Warna perbatasan kalender",
  "Calendar Border Width": "Lebar perbatasan kalender",
  "Calendar Border Style": "Gaya perbatasan kalender",
  "Font Color": "Warna huruf",
  "Event Background": "Latar belakang acara",
  "Card Date Color": "Warna tanggal kartu",
  "Title Font": "Font Judul",
  "Date Font": "Font tanggal",
  "Description Font": "Deskripsi Font",
  "Button Background": "Latar belakang tombol",
  "Button Text": "Teks Tombol",
  "Border Color": "Warna perbatasan",
  "Border Width": "Lebar perbatasan",
  "Border Type": "Tipe perbatasan",
  Title: "Judul",
  Description: "Keterangan",
  "Background Color": "Warna latar belakang",
  Divider: "Pembagi",
  "Event Details Font": "Detail Acara Font",
  "Website Link Color": "Warna tautan situs web",
  "Developer Info": "Info pengembang",
  "User Guide": "Panduan pengguna",
  "Support e-mail": "Dukung email",
  "Our Website": "Situs web kami",
  "App Review": "Ulasan aplikasi",
  "Enjoying App? Leave us a review in the App Market.":
    "Menikmati aplikasi? Tinggalkan kami ulasan di pasar aplikasi.",
  "Review Us": "Tinjau kami",
  "Connect With Us": "Terhubung dengan kami",
  "What's your email?": "apa e-mailmu?",
  "Invalid email address!": "Alamat email salah!",
  Comments: "Komentar",
  "We'd love to hear from you. Send us a message.":
    "Kami ingin mendengar dari Anda. Kirimi kami pesan.",
  "Message must be at least 5 characters long":
    "Pesan harus setidaknya 5 karakter",
  Send: "Mengirim",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Jika Anda ingin mengizinkan pengguna beralih di antara tampilan kalender, aktifkan opsi ini dan pilih tampilan yang ingin Anda tunjukkan.",
  Main: "Utama",
  Localize: "Melokalisir",
  Settings: "Pengaturan",
  Layouts: "Tata letak",
  Advanced: "Canggih",
  Design: "Desain",
  Support: "Mendukung",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Semua pengaturan lokal (secara otomatis) berdasarkan bahasa Anda. Jika bahasa Anda ada dalam daftar, tidak perlu menyesuaikan bagian ini.",
  "Date Format": "Format tanggal",
  "Time Format": "Format waktu",
  "Text Direction": "Arah teks",
  "Left to Right": "Kiri ke kanan",
  "Right to Left": "Kanan ke kiri",
  "Week Starts On": "Minggu dimulai",
  "Agenda Style": "Gaya agenda",
  Classic: "Klasik",
  Modern: "Modern",
  "Agenda Header": "Header Agenda",
  "Upcoming Events": "Acara Mendatang",
  "Agenda Event Limit": "Batas Acara Agenda",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Tingkatkan sekarang dan dapatkan lebih banyak fitur dan nikmati aplikasi Anda secara penuh!",
  "Upgrade Now": "Tingkatkan sekarang",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Hosting acara yang bertahan sepanjang hari? Ini memungkinkan Anda menunjukkannya di kalender Anda.",
  "24 hours": "24 jam",
  Sat: "Duduk",
  Sun: "Matahari",
  Mon: "Senin",
  Default: "Bawaan",
  "Select custom design style for your calendar.":
    "Pilih gaya desain khusus untuk kalender Anda.",
  Style: "Gaya",
  "Styles and Colors": "Gaya dan warna",
  "Calendar Name": "Nama Kalender",
  "Write your Calendar name here": "Tulis nama kalender Anda di sini",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Ini tidak terlihat oleh pengguna Anda. Atur nama untuk membedakan kalender Anda saat menggunakan fungsi Sinkronisasi Kalender Boom.",
  "General Info": "Informasi Umum",
  Venue: "Lokasi",
  Organizer: "Penyelenggara",
  Search: "Mencari",
  "Add to": "Tambahkan",
  calendar: "kalender",
  "Copy event URL": "Salin URL Acara",
  "Copied!": "Disalin!",
  "Add & Share": "Tambahkan & Bagikan",
  Map: "Peta",
  "Calendar view": "Tampilan Kalender",
  "Add Event": "Tambahkan acara",
  Uncategorised: "Tidak dikategorikan",
  More: "Lagi",
  Less: "Lebih sedikit",
  Register: "Daftar",
  Card: "Kartu",
  Guests: "Tamu",
  unlimited: "tak terbatas",
  "Show more": "Menampilkan lebih banyak",
  "Enable Search": "Aktifkan pencarian",
  "+ Add Event": " + Tambahkan acara",
  "Manage and Sync": "Kelola dan Sinkronisasi",
  "Show event details as...": "Tampilkan detail acara sebagai ...",
  Tooltip: "Tooltip",
  Popup: "Muncul",
  None: "Tidak ada",
  "Show Category": "Tampilkan kategori",
  "Header Align": "Header sejajar",
  "Show Time": "Waktu pertunjukan",
  "Hours in Weekly/Daily View": "Berjam -jam dalam tampilan mingguan/harian",
  "Share Events": "Bagikan acara",
  Shadow: "Bayangan",
  "Inner Padding": "Padding dalam",
  Text: "Teks",
  "Active Button Border": "Batas tombol aktif",
  "Light Mode": "Mode Cahaya",
  "Event Text Color": "Warna teks acara",
  Dates: "tanggal",
  Skeleton: "Kerangka",
  "Skeleton Color": "Warna kerangka",
  Width: "Lebar",
  "Skeleton Style": "Gaya kerangka",
  Color: "Warna",
  "Section Titles": "Judul bagian",
  "Section Content": "Konten bagian",
  Header: "Header",
  Standard: "Standar",
  Retro: "Retro",
  Silver: "Perak",
  Night: "Malam",
  Dark: "Gelap",
  Aubergine: "Terong",
  "Map Header": "Header peta",
  "Show Title in mobile": "Tampilkan judul di ponsel",
  "Card View": "Tampilan kartu",
  "Card background color": "Warna latar belakang kartu",
  "Title font": "Font Judul",
  "Desciption font": "Font Desciption",
  "Section font": "Bagian Font",
  "Section divider color": "Bagian Warna Pembagi Bagian",
  "Add event": "Tambahkan acara",
  "All Day Event": "Acara sepanjang hari",
  Location: "Lokasi",
  "Choose a category": "Pilih kategori",
  "Venue name": "Nama tempat",
  "Venue phone": "Telepon Tempat",
  "Venue email": "Email venue",
  "Venue website": "Situs web venue",
  "Organizer name": "Nama organizer",
  "Organizer phone": "Ponsel organizer",
  "Organizer email": "Email organizer",
  "Organizer website": "Situs web organizer",
  "Personal info": "Informasi pribadi",
  "First name": "Nama depan",
  "Last name": "nama keluarga",
  "Email Address": "Alamat email",
  "Additional Notes": "catatan tambahan",
  Back: "Kembali",
  Save: "Menyimpan",
  Next: "Berikutnya",
  "Your event has been submitted": "Acara Anda telah dikirimkan",
  "Event submittion has been failed": "Pengajuan acara telah gagal",
  "e.g. Birthday Party": "misalnya Pesta ulang tahun",
  "First Name": "Nama depan",
  "Last Name": "Nama keluarga",
  "Phone Number": "Nomor telepon",
  Address: "Alamat",
  "Your comments": "Komentar Anda",
  "How many guests?": "Berapa banyak tamu?",
  "Anything else we need to know?": "Ada lagi yang perlu kita ketahui?",
  "Guests:": "Tamu:",
  Submit: "Kirim",
  "Go to Calendar": "Pergi ke Kalender",
  "Registration completed successfully!": "Pendaftaran selesai dengan sukses!",
  "Please check your registered email address":
    "Silakan periksa alamat email terdaftar Anda",
  "Add to Calendar": "Tambahkan ke Kalender",
  "Share this Event": "Bagikan acara ini",
  "Sorry something went wrong": "Maaf ada yang salah",
  "Back to registration": "Kembali ke pendaftaran",
  "Date & Location": "Tanggal & Lokasi",
  "Date & Time": "Tanggal Waktu",
  home: "rumah",
  "Header align": "Header sejajar",
  Footer: "Footer",
  "Categories Filter": "Kategori Filter",
  "Show only upcoming": "Tampilkan hanya mendatang",
  "Card(s) in a row": "Kartu berturut -turut",
  "Space between cards": "Ruang Antara Kartu",
  "Shown events limit": "Batas acara yang ditunjukkan",
  "Style 1": "Gaya 1",
  "Style 2": "Gaya 2",
  "Style 3": "Gaya 3",
  "Style 4": "Gaya 4",
  "Buttons & Links": "Tombol & Tautan",
  "Button corner radius": "Radius sudut tombol",
  "Buttons font": "Tombol Font",
  "Buttons background": "Latar belakang tombol",
  "Get notified by Email": "Dapatkan diberitahu melalui email",
  "Review events": "Tinjau acara",
  "Click on date": "Klik tanggal",
  "Add Event button": "Tambahkan tombol acara",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Sinkronisasi kalender memungkinkan Anda untuk mengintegrasikan acara dan sesi Anda dengan kalender boom Anda.",
  connect: "Menghubung",
  "Synchronized Calendars": "Kalender yang disinkronkan",
  "Import events": "Acara impor",
  Disconnect: "Memutuskan",
  "Choose calendar": "Pilih Kalender",
  "Monitor your Wix events through the sync feature":
    "Pantau acara WIX Anda melalui fitur sinkronisasi",
  "Connect all your Boom calendars available on your website":
    "Hubungkan semua kalender boom Anda yang tersedia di situs web Anda",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Jadwalkan, bergabunglah, dan kelola pertemuan zoom tepat melalui kalender boom kami.",
  "Monitor your Event Brite events through the Event Brite sync feature.":
    "Pantau acara Brite acara Anda melalui fitur Sinkronisasi Acara Brite",
  Email: "Surel",
  "Add-ons": "Add-on",
  "Receive notification emails as soon as users add events to your calendar.":
    "Terima email pemberitahuan segera setelah pengguna menambahkan acara ke kalender Anda.",
  "Enable + button on the calendar header":
    "Aktifkan + tombol di header kalender",
  "Accept or decline events added by customers before making them public.":
    "Terima atau tolak acara yang ditambahkan oleh pelanggan sebelum menjadikannya publik.",
  "Switch Add Event": "Beralih Tambah Acara",
  "Enable your browser cookies to connect to your account.":
    "Aktifkan cookie browser Anda untuk terhubung ke akun Anda.",
  "Learn more": "Belajarlah lagi",
  "Print Button": "Tombol cetak",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Izinkan pengguna Anda untuk mencetak kalender acara boom Anda dalam kisaran tanggal apa pun.",
  "Show Title on mobile": "Tampilkan judul di ponsel",
  "Show Skeleton on mobile": "Tunjukkan kerangka di ponsel",
  "Start 7-day Business trial": "Mulai uji coba bisnis 7 hari",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Nikmati semua fitur yang tidak disimi, seperti jual tiket, pendaftaran, tambahan acara pengunjung.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Harap dicatat: Di akhir periode percobaan, Anda akan dikembalikan ke rencana berlangganan yang ada.",
  "Not Now": "Tidak sekarang",
  "Start free trial": "Mulai uji coba gratis",
  "Congrats!": "Selamat!",
  "Your 7-day Business trial has been successfully activated.":
    "Uji coba bisnis 7 hari Anda telah berhasil diaktifkan.",
  Done: "Selesai",
  "Title font color": "Warna font judul",
  "Desciption font color": "Warna font desciption",
  "Section font color": "Bagian Font Warna",
  "Card Header": "Header kartu",
  Category: "Kategori",
  "Display at the": "Tampilan di",
  top: "atas",
  bottom: "dasar",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Pamerkan filter kategori di bagian atas atau di bagian bawah kalender. Pengaturan hanya berlaku untuk agenda dan tampilan kartu",
  "Processing your events": "Memproses acara Anda",
  "Search for events": "Cari Acara",
  "There are no events added": "Tidak ada acara yang ditambahkan",
  "Location: To be determined": "Lokasi: untuk ditentukan",
  "No events for selected date": "Tidak ada acara untuk tanggal yang dipilih",
  Uncategorized: "Tidak dikategorikan",
  "Edit event": "Edit Event",
  "Edit original event": "Edit acara asli",
  "Copy event": "Salin acara",
  "Copy as new event": "Salin sebagai Acara Baru",
  "Delete event": "Hapus acara",
  "Stop repeating on this date": "Berhenti mengulangi tanggal ini",
  "Exclude this date": "Kecualikan tanggal ini",
  "Location is going to be announced": "Lokasi akan diumumkan",
  "Fill your personal information": "Isi Informasi Pribadi Anda",
  "Check Box": "Kotak centang",
  "Single Choice": "Pilihan tunggal",
  Option: "Pilihan",
  "Share Event": "Bagikan acara",
  "Oops! Something went wrong": "Ups! Ada yang salah",
  "We are sorry this event has already taken place":
    "Kami minta maaf acara ini telah terjadi",
  "Back to calendar": "Kembali ke Kalender",
  "This field is required": "Bagian ini diperlukan",
  Phone: "Telepon",
  "Number field": "Bidang Nomor",
  "Please provide a valid email": "Harap berikan email yang valid",
  "Select at least one option": "Pilih setidaknya satu opsi",
  "Choose tickets to see total value": "Pilih tiket untuk melihat nilai total",
  tickets: "tiket",
  "Choose Tickets": "Pilih tiket",
  "Choose payment method": "Pilih cara pembayaran",
  Pay: "Membayar",
  Total: "Total",
  Free: "Bebas",
  "Buy tickets": "Beli tiket",
  "Sold Out": "Terjual habis",
  "Tickets are available": "Tiket tersedia",
  "Sales End": "Akhir penjualan",
  "Availible from": "Tersedia dari",
  "Go to Orders": "Pergi ke pesanan",
  "Go to Details": "Pergi ke detail",
  "Group ticket": "Tiket grup",
  Name: "Nama",
  Price: "Harga",
  "Order by": "Dipesan oleh",
  "Order ID": "Id pemesanan",
  Applied: "Terapan",
  Fees: "Biaya",
  "Enter promo code": "Masukkan kode promo",
  Apply: "Menerapkan",
  "Promo Code": "Kode promosi",
  Cash: "Uang tunai",
  "You can find your e-tickets attached to your email or download them":
    "Anda dapat menemukan E-Ticket Anda dilampirkan ke email Anda atau mengunduhnya",
  here: "Di Sini",
  Time: "Waktu",
  "Invalid promo code": "Kode promo tidak valid",
  "Credit card": "Kartu kredit",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Anda akan segera menerima pesan konfirmasi pendaftaran yang berhasil ke alamat email Anda.",
  "You can also check your order details below.":
    "Anda juga dapat memeriksa detail pesanan Anda di bawah ini.",
  at: "pada",
  Buy: "Membeli",
  Donation: "Sumbangan",
  "Enter price": "Masukkan harga",
  Choose: "Memilih",
  Chosen: "Terpilih",
  "Choose your plan": "Pilih rencana Anda",
  week: "pekan",
  wk: "wk",
  "Choose plan cycle": "Pilih Siklus Rencana",
  months: "bulan",
  years: "bertahun-tahun",
  weeks: "minggu -minggu",
  "Copy Event Url": "Salin URL Acara",
  "You can find your e-tickets attached to your email or print them":
    "Anda dapat menemukan E-Ticket Anda terlampir pada email Anda atau mencetaknya",
  "Guest Info": "Info tamu",
  "Ticket Info": "Info tiket",
  "Ticket name": "Nama tiket",
  "Ticket price": "Harga tiket",
  "Ticket ID": "ID tiket",
  "If you have any questions contact to organizer":
    "Jika Anda memiliki pertanyaan, kontak ke penyelenggara",
  "As soon as event ends": "Segera setelah acara berakhir",
  "1 day after event ends": "1 hari setelah acara berakhir",
  "7 days after event ends": "7 hari setelah acara berakhir",
  "14 days after event ends": "14 hari setelah acara berakhir",
  "30 days after event ends": "30 hari setelah acara berakhir",
  Menu: "Menu",
  "No event for selected date": "Tidak ada acara untuk tanggal yang dipilih",
  view: "melihat",
  List: "Daftar",
  Year: "Tahun",
  Yearly: "Tahunan",
  "Year view header": "HEADER TERJADI TAHUN",
  "Yearly Style": "Gaya tahunan",
  "There are no events": "Tidak ada acara",
  Autotranslation: "Autotranslasi",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Setelah diaktifkan, widget kalender Anda akan diterjemahkan berdasarkan bahasa situs web. *Perhatikan bahwa selama judul kalender, dan deskripsi dimasukkan teks mereka tidak dapat diterjemahkan.",
  "Note on mobile": "Catatan di ponsel",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Matikan atau ubah teks bilah 'No Events' pada Kalender Versi Seluler",
  Autodeletion: "Autodeletion",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Mengaktifkan opsi, akan secara otomatis menghapus acara masa lalu Anda dari kalender.",
  "This does not apply to repeating events!":
    "Ini tidak berlaku untuk acara berulang!",
  "Notify event creators about the guest":
    "Beri tahu pencipta acara tentang tamu",
  "Send event creators notification emails as soon as guests register for their events":
    "Kirim email pemberitahuan pencipta acara segera setelah tamu mendaftar untuk acara mereka",
  "List View Type": "Jenis Tampilan Daftar",
  "Description font": "Deskripsi Font",
  Connect: "Menghubung",
  "You have no events": "Anda tidak memiliki acara",
  Synchronize: "Sinkronisasi",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Google Calendar Sync memungkinkan Anda untuk mengintegrasikan acara dan sesi Anda dengan kalender boom Anda.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Outlook Calendar Sync memungkinkan Anda untuk mengintegrasikan acara dan sesi Anda dengan kalender boom Anda.",
  "Your message has been sent successfully!":
    "Pesan Anda telah berhasil dikirim!",
  "There are no synchronized calendars": "Tidak ada kalender yang disinkronkan",
  "to view more than 7 events": "untuk melihat lebih dari 7 acara",
  "Mobile app": "Aplikasi seluler",
  "Admin Account": "Akun Admin",
  Password: "Kata sandi",
  "Second User": "Pengguna kedua",
  Edit: "Edit",
  "Guest limit": "Batas tamu",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Semua pengaturan lokal (secara otomatis) berdasarkan bahasa Anda. Jika bahasa Anda ada dalam daftar, tidak perlu menyesuaikan bagian ini.",
  available: "tersedia",
  next: "Berikutnya",
  Tickets: "Tiket",
  Quantity: "Kuantitas",
  "Promo code": "Kode promosi",
  "Select a payment method": "Pilih metode pembayaran",
  Fee: "Biaya",
  Book: "Buku",
  "All the tickets have been sold out": "Semua tiket telah terjual habis",
  "Choose at least one ticket": "Pilih setidaknya satu tiket",
  "First choose ticket": "Pertama pilih tiket",
  "Please fill out your personal information.":
    "Harap isi informasi pribadi Anda.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "Untuk melakukan pembelian yang berhasil, pilih metode pembayaran pilihan Anda dan masukkan kode promo untuk tiket diskon.",
  "Credit/Debit card": "Kartu Kredit/Debit",
  "print here.": "Cetak di sini.",
  "QR code for all tickets": "Kode QR untuk semua tiket",
  Duration: "Durasi",
  "Full Name": "Nama lengkap",
  "Ticket id": "ID tiket",
  "Group id": "ID grup",
  "Choose your ticket.": "Pilih tiket Anda.",
  "Fill out your personal information.": "Isi informasi pribadi Anda.",
  "Add the payment details.": "Tambahkan detail pembayaran.",
  "To be determined": "Untuk ditentukan",
  "You can find your e-tickets attached to the email or":
    "Anda dapat menemukan E-Ticket Anda terlampir pada email atau",
  "print here": "Cetak di sini",
  "Full name": "Nama lengkap",
  "Group ID": "ID grup",
  "to Book": "untuk memesan",
  "Unfortunately, your card has been declined":
    "Sayangnya, kartu Anda telah ditolak",
  "Thank you for your purchase!": "Terima kasih atas pembelian Anda!",
  "Find your printable e-tickets attached to the confirmation email":
    "Temukan tiket elektronik Anda yang dapat dicetak terlampir pada email konfirmasi",
  Confirm: "Mengonfirmasi",

  "Add event": "Tambahkan acara",
  Events: "Acara",
  "Event details": "Detail acara",
  Registration: "Registrasi",
  "Guests list": "Daftar tamu",
  Ticket: "Tiket",
  "General Info": "Informasi Umum",
  "Customize the general settings of your event":
    "Kustomisasi Pengaturan Umum Acara Anda",
  "Event Title": "Judul acara",
  "e.g. Birthday Party": "misalnya Pesta ulang tahun",
  "All Day Event": "Acara sepanjang hari",
  Cross: "Menyeberang",
  Timeline: "Linimasa",
  "Repeating event": "Acara berulang",
  Location: "Lokasi",
  "Venue name": "Nama tempat",
  Description: "Keterangan",
  Image: "Gambar",
  Color: "Warna",
  Category: "Kategori",
  "Add your events to color categories and let your users classify them easily":
    "Tambahkan acara Anda ke kategori mewarnai dan biarkan pengguna Anda mengklasifikasikannya dengan mudah",
  "Category name": "Nama Kategori",
  "e.g. Birthdays": "misalnya Ulang tahun",
  Venue: "Lokasi",
  "Where the event takes place": "Dimana acara berlangsung",
  "Venue name": "Nama tempat",
  "Venue phone": "Telepon Tempat",
  "Venue email": "Email venue",
  "Venue website": "Situs web venue",
  Organizer: "Penyelenggara",
  "Person who makes the event": "Orang yang membuat acara tersebut",
  "Organizer name": "Nama organizer",
  "Organizer phone": "Telepon organizer",
  "Organizer email": "Email organizer",
  "Organizer website": "Situs web organizer",
  Save: "Menyimpan",
  Cancel: "Membatalkan",
  Import: "Impor",
  Past: "Masa lalu",
  All: "Semua",
  Upcoming: "Mendatang",
  Uncategorised: "Tidak dikategorikan",
  "Date Ascending": "Tanggal naik",
  "Date Descending": "Tanggal turun",
  "Title by A-Z": "Judul oleh A-Z",
  "Title by Z-A": "Judul oleh Z-A",
  "There are no events for this period": "Tidak ada acara untuk periode ini",

  "Auto-Convert Date & Time": "Tanggal & Waktu Konversi Otomatis",
  TimeZone: "Zona waktu",
  Autodeletion: "Autodeletion",
  "Layout Settings": "pengaturan tampilan",
  "Yeatly view": "Melihat dengan baik",
  "Monthly view header": "Tajuk tampilan bulanan",
  "Weekly/Daily view header": "Header Mingguan/Harian View",
  Acendings: "AKENDING",
  Descending: "Menurun",
  Standart: "Standart",
  Silver: "Perak",
  Retro: "Retro",
  Dark: "Gelap",
  Night: "Malam",
  Aubergine: "Terong",
  "List view header": "Daftar Tampilan Tajuk",
  "Side by Side View": "Tampilan berdampingan",
  "Customize Proportions": "Kustomisasi proporsi",
  "Card Margins": "Margin kartu",
  "Image opacity (%)": "Gambar opacity (%)",
  "Side by Side Header": "Header berdampingan",
  "Text Align": "Teks Align",
  "Timeline View": "Tampilan Timeline",
  "Title font color": "Warna font judul",
  "Desciption font color": "Warna font desciption",
  "Line color": "Warna garis",
  "Date Font color": "Warna font tanggal",
  "Daily events background": "Latar belakang acara harian",
  Alignment: "Penyelarasan",
  Vertical: "Vertikal",
  Horizontal: "Horisontal",
  "Vertical Alignment": "Penyelarasan vertikal",
  Right: "Benar",
  Center: "Tengah",
  "Horizontal Alignment": "Penyelarasan horizontal",
  Top: "Atas",
  Center: "Tengah",
  Bottom: "Dasar",
  "Dates Circle Design": "Desain Lingkaran Tanggal",
  "Next To The Circle": "Di sebelah lingkaran",
  "In The Circle": "Di lingkaran",
  "Timeline Header": "Header timeline",
  Timeline: "Linimasa",
  "Show only upcoming": "Tampilkan hanya mendatang",
  "Order by": "Dipesan oleh",
  "Timeline Event Limit": "Batas Acara Timeline",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Izinkan pengunjung untuk menambahkan acara ke calnedars lokal: Google, Yahoo, Outlook, icalendar.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Izinkan pengunjung untuk membagikan acara Anda ke Facebook, LinkedIn, Twitter dan dll.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Tambahkan opsi pencarian di kalender Anda untuk membiarkan orang mencari acara Anda berdasarkan judul, tempat, dll.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Izinkan pengguna Anda untuk mencetak kalender acara boom Anda dalam kisaran tanggal apa pun.",
  "Click to apply a theme to Calendar":
    "Klik untuk menerapkan tema ke kalender",
  "Date container color": "Warna wadah tanggal",
  "Daily events background": "Latar belakang acara harian",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Gunakan add-on untuk menginstal fitur canggih di kalender Anda, membuatnya lebih fungsional!",
  "Open Add-ons Store": "Buka toko tambahan",
  Monday: "Senin",
  Tuesday: "Selasa",
  Wednesday: "Rabu",
  Thursday: "Kamis",
  Friday: "Jumat",
  Saturday: "Sabtu",
  Sunday: "Minggu",
  "Yearly view": "Tampilan tahunan",
  "Show event time next to title": "Tampilkan waktu acara di sebelah judul",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Sesuaikan tanggal dan waktu acara dengan waktu lokal pengguna berdasarkan zona waktu mereka.",
  "Display the time zone alongside the event date.":
    "Tampilkan zona waktu bersamaan dengan tanggal acara.",
  "Show event time next to title": "Tampilkan waktu acara di sebelah judul",
  "Time Zone": "Zona waktu",
  "Upload Image": "Unggah gambar",
  "Choose a Category": "Pilih kategori",
  "Color you have chosen will not be shown as you choose category":
    "Warna yang Anda pilih tidak akan ditampilkan saat Anda memilih kategori",
  Website: "Situs web",
  Next: "Berikutnya",
  Save: "Menyimpan",
  "Last Name": "Nama keluarga",
  "Personal Info": "Informasi pribadi",
  Back: "Kembali",
  "This field is required": "Bagian ini diperlukan",
  "Your event has been submitted": "Acara Anda telah dikirimkan",
  "Enter a location": "Masukkan lokasi",
  "Display the time zone alongside the event date.":
    "Tampilkan zona waktu bersamaan dengan tanggal acara.",
  Home: "Rumah",
  "Side By Side Event Limit": "Batas acara berdampingan",
  "Mobille App": "Aplikasi Mobille",
  category: "kategori",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Pantau jadwal Anda dengan mudah dengan mengimpor acara Facebook ke kalender Anda.",
  "Synchronized Pages": "Halaman yang Disinkronkan",
  "There are no synchronized pages": "Tidak ada halaman yang disinkronkan",
  "Choose page": "Pilih halaman",
  "You have no events": "Anda tidak memiliki acara",
};
export default id;
