let is = {
  Categories: "Flokkar",
  "Share this event": "Deildu þessum atburði",
  Language: "Tungumál",
  "Show Time Zone": "Sýna tímabelti",
  "Custom Local Settings": "Sérsniðnar staðbundnar stillingar",
  "Add and showcase events on your site using a beautiful calendar.":
    "Bættu við og sýndu atburði á síðunni þinni með fallegu dagatali.",
  "Week Days": "Vikudagar",
  "Manage Events": "Stjórna atburðum",
  General: "Almennt",
  "Layout Picker": "Layout Picker",
  Month: "Mánuður",
  Monthly: "Mánaðarlega",
  Week: "Vika",
  Weekly: "Vikulega",
  Day: "Dagur",
  Daily: "Daglega",
  Agenda: "Dagskrá",
  "Navigation Buttons": "Siglingarhnappar",
  "Week numbers": "Vikatölur",
  "Include Weekends": "Fela í sér helgar",
  "All-day": "Allan daginn",
  "All Day": "Allan daginn",
  Label: "Merkimiða",
  "Fit to Height": "Passa að hæð",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Til að stilla hlutföll apps slökkva á þessum valkosti og breyta stærð dagatals í ritstjóra.",
  "Default Layout": "Sjálfgefið skipulag",
  "Monthly view": "Mánaðarlega útsýni",
  "Weekly and Daily view": "Vikulega og daglega útsýni",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Þú getur veitt gestum stöðugri reynslu með því að sýna sama fjölda vikna (6) í einu.",
  "Fixed Weekly Layout": "Fast vikulega skipulag",
  back: "aftur",
  Row: "Röð",
  "Hours in Weekly View": "Klukkustundir í vikulegu útsýni",
  "Hours in Daily View": "Klukkustundir í daglegu sýn",
  Start: "Byrjaðu",
  End: "Enda",
  "At This Hour": "Á þessari klukkustund",
  Button: "Takki",
  Buttons: "Hnappar",
  Sunday: "Sunnudagur",
  Monday: "Mánudagur",
  Tuesday: "Þriðjudagur",
  Wednesday: "Miðvikudag",
  Thursday: "Fimmtudag",
  Friday: "Föstudag",
  Saturday: "Laugardag",
  "Default Date": "Sjálfgefin dagsetning",
  year: "ár",
  month: "Mánuður",
  mo: "Mo.",
  days: "dagar",
  ago: "síðan",
  ahead: "á undan",
  Yesterday: "Í gær",
  Today: "Í dag",
  Tomorrow: "Á morgun",
  Custom: "Sérsniðin",
  "Set Daily Rows Limit": "Stilltu dagleg línur mörk",
  "Set Proportions": "Setja hlutföll",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Leyfa gestinum að bæta viðburði við staðbundna kálfa: Google, Yahoo, Outlook, Icalendar.",
  Container: "Ílát",
  Background: "Bakgrunnur",
  "Container Background": "Bakgrunnur íláts",
  "Container Borders": "Gámamörk",
  Calendar: "Dagatal",
  "Event Info Tooltip": "Upplýsingar um atburði",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Þegar fólk sveima yfir atburði mun það sjá allar upplýsingar um það í verkfæri.",
  "Event Info Window": "Upplýsingar um atburði",
  "This is the full information window that opens when someone clicks on the event.":
    "Þetta er allur upplýsingaglugginn sem opnar þegar einhver smellir á viðburðinn.",
  "Use Gradient": "Notaðu halla",
  Vertical: "Lóðrétt",
  Horizontal: "Lárétt",
  First: "Fyrsta",
  Second: "Annað",
  diagonal: "ská",
  Radial: "Geislamyndun",
  "Select option": "Veldu valkost",
  Solid: "Solid",
  Dotted: "Punktur",
  Dashed: "Strikað",
  Double: "Tvöfalt",
  "Border Radius": "Landamærasldíus",
  Padding: "Padding",
  "Date Header": "Dagsetning haus",
  "Event Default Color": "Sjálfgefinn litur atburðar",
  "Days of Week": "Daga vikunnar",
  "Days of Week Background": "Dagar af bakgrunni vikunnar",
  Date: "Dagsetning",
  "Event Title": "Titill atburða",
  "Highlight today": "Hápunktur í dag",
  "Highlight Color": "Hápunktur lit.",
  Hide: "Fela",
  "Calendar Border Color": "Litur dagatalsins",
  "Calendar Border Width": "Breidd dagatala",
  "Calendar Border Style": "Calendar landamærastíll",
  "Font Color": "Leturlitur",
  "Event Background": "Bakgrunnur atburða",
  "Card Date Color": "Litur dagsetningar",
  "Title Font": "Titill leturgerð",
  "Date Font": "Dagsetning leturgerð",
  "Description Font": "Lýsing leturgerð",
  "Button Background": "Bakgrunnur hnappsins",
  "Button Text": "Hnappatexti",
  "Border Color": "Landamæralitur",
  "Border Width": "Breidd landamæra",
  "Border Type": "Landamærategund",
  Title: "Titill",
  Description: "Lýsing",
  "Background Color": "Bakgrunns litur",
  Divider: "Skipting",
  "Event Details Font": "Upplýsingar um atburði letur",
  "Website Link Color": "Litur á vefsíðu",
  "Developer Info": "Upplýsingar um verktaki",
  "User Guide": "Notkunarleiðbeiningar",
  "Support e-mail": "Styðjið tölvupóst",
  "Our Website": "Vefsíða okkar",
  "App Review": "Endurskoðun app",
  "Enjoying App? Leave us a review in the App Market.":
    "Njóttu apps? Skildu okkur yfirferð á appinu.",
  "Review Us": "Farðu yfir okkur",
  "Connect With Us": "Tengjast okkur",
  "What's your email?": "hvað er netfangið þitt?",
  "Invalid email address!": "Ógilt netfang!",
  Comments: "Athugasemdir",
  "We'd love to hear from you. Send us a message.":
    "Við viljum gjarnan heyra frá þér. Sendu okkur skilaboð.",
  "Message must be at least 5 characters long":
    "Skilaboð verða að vera að minnsta kosti 5 stafir",
  Send: "Senda",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Ef þú vilt leyfa notanda að skipta á milli dagatalsskoðana skaltu virkja þennan valkost og velja skoðanir sem þú vilt sýna.",
  Main: "Aðal",
  Localize: "Staðbundið",
  Settings: "Stillingar",
  Layouts: "Skipulag",
  Advanced: "Langt gengið",
  Design: "Hönnun",
  Support: "Stuðningur",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Allar staðbundnar stillingar eru (sjálfkrafa) byggðar á tungumálinu þínu. Ef tungumál þitt er á listanum er engin þörf á að sérsníða þennan hluta.",
  "Date Format": "Dagsetningarsnið",
  "Time Format": "Tímasnið",
  "Text Direction": "Textastefna",
  "Left to Right": "Vinstri til hægri",
  "Right to Left": "Hægri til vinstri",
  "Week Starts On": "Vika byrjar á",
  "Agenda Style": "Dagskrá stíll",
  Classic: "Klassískt",
  Modern: "Modern",
  "Agenda Header": "Dagskrár haus",
  "Upcoming Events": "Viðburðir á næstunni",
  "Agenda Event Limit": "Dagskrárviðburðamörk",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Uppfærðu núna og fáðu miklu fleiri aðgerðir og njóttu appsins þíns að fullu!",
  "Upgrade Now": "Uppfæra núna",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Hýsir viðburði sem endast allan daginn? Þetta gerir þér kleift að sýna þeim á dagatalinu þínu.",
  "24 hours": "24 klukkustundir",
  Sat: "Sat",
  Sun: "Sól",
  Mon: "Mán",
  Default: "Sjálfgefið",
  "Select custom design style for your calendar.":
    "Veldu sérsniðinn hönnunarstíl fyrir dagatalið þitt.",
  Style: "Stíll",
  "Styles and Colors": "Stíl og litir",
  "Calendar Name": "Nafn dagatals",
  "Write your Calendar name here": "Skrifaðu nafn dagatalsins hér",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Þetta er ekki sýnilegt notendum þínum. Settu nöfn til að aðgreina dagatalin þín þegar þú notar BOOM dagatal samstillingaraðgerðina.",
  "General Info": "Almennar upplýsingar",
  Venue: "Staður",
  Organizer: "Skipuleggjandi",
  Search: "Leitaðu",
  "Add to": "Bæta við",
  calendar: "dagatal",
  "Copy event URL": "Afritunarslóð",
  "Copied!": "Afritað!",
  "Add & Share": "Bæta við og deila",
  Map: "Kort",
  "Calendar view": "Dagatalsskoðun",
  "Add Event": "Bæta við atburði",
  Uncategorised: "Óflokkað",
  More: "Meira",
  Less: "Minna",
  Register: "Skráðu þig",
  Card: "Spil",
  Guests: "Gestir",
  unlimited: "ótakmarkað",
  "Show more": "Sýndu meira",
  "Enable Search": "Virkja leit",
  "+ Add Event": " + Bæta við atburði",
  "Manage and Sync": "Stjórna og samstilla",
  "Show event details as...": "Sýna upplýsingar um atburði sem ...",
  Tooltip: "Tooltip",
  Popup: "Skjóta upp kollinum",
  None: "Enginn",
  "Show Category": "Sýna flokk",
  "Header Align": "Haus samræma",
  "Show Time": "Sýningartími",
  "Hours in Weekly/Daily View": "Klukkustundir í vikulega/daglegu útsýni",
  "Share Events": "Deildu atburðum",
  Shadow: "Skugga",
  "Inner Padding": "Innri padding",
  Text: "Texti",
  "Active Button Border": "Virkur hnappur landamæri",
  "Light Mode": "Léttur háttur",
  "Event Text Color": "Litur við atburði",
  Dates: "Dagsetningar",
  Skeleton: "Beinagrind",
  "Skeleton Color": "Beinagrind litur",
  Width: "Breidd",
  "Skeleton Style": "Beinagrindastíll",
  Color: "Litur",
  "Section Titles": "Hluti titla",
  "Section Content": "Innihald kafla",
  Header: "Haus",
  Standard: "Standard",
  Retro: "Aftur",
  Silver: "Silfur",
  Night: "Nótt",
  Dark: "Myrkur",
  Aubergine: "Aubergine",
  "Map Header": "Korthaus",
  "Show Title in mobile": "Sýna titil í farsíma",
  "Card View": "Kort útsýni",
  "Card background color": "Bakgrunnslitur korta",
  "Title font": "Titill leturgerð",
  "Desciption font": "Desciption leturgerð",
  "Section font": "Kafla leturgerð",
  "Section divider color": "Hluti skiljunarlitur",
  "Add event": "Bæta við atburði",
  "All Day Event": "Allan daginn atburður",
  Location: "Staðsetning",
  "Choose a category": "Veldu flokk",
  "Venue name": "Nafn vettvangs",
  "Venue phone": "Vettvangssími",
  "Venue email": "Tölvupóstur vettvangs",
  "Venue website": "Vefsíða vettvangs",
  "Organizer name": "Skipuleggjandi nafn",
  "Organizer phone": "Skipuleggjandi sími",
  "Organizer email": "Skipuleggjandi tölvupóstur",
  "Organizer website": "Skipuleggjandi vefsíða",
  "Personal info": "Persónulegar upplýsingar",
  "First name": "Fyrsta nafn",
  "Last name": "Eftirnafn",
  "Email Address": "Netfang",
  "Additional Notes": "Viðbótarbréf",
  Back: "Aftur",
  Save: "Vista",
  Next: "Næst",
  "Your event has been submitted": "Viðburðurinn þinn hefur verið lagður inn",
  "Event submittion has been failed": "Sendingu atburða hefur mistekist",
  "e.g. Birthday Party": "t.d. Afmælisveisla",
  "First Name": "Fyrsta nafn",
  "Last Name": "Eftirnafn",
  "Phone Number": "Símanúmer",
  Address: "Heimilisfang",
  "Your comments": "Athugasemdir þínar",
  "How many guests?": "Hversu margir gestir?",
  "Anything else we need to know?": "Eitthvað annað sem við þurfum að vita?",
  "Guests:": "Gestir:",
  Submit: "Sendu",
  "Go to Calendar": "Farðu í dagatal",
  "Registration completed successfully!": "Skráning lokið með góðum árangri!",
  "Please check your registered email address":
    "Vinsamlegast athugaðu skráða netfangið þitt",
  "Add to Calendar": "Bættu við dagatal",
  "Share this Event": "Deildu þessum atburði",
  "Sorry something went wrong": "Afsakið, eitthvað fór úrskeiðis",
  "Back to registration": "Aftur í skráningu",
  "Date & Location": "Dagsetning og staðsetning",
  "Date & Time": "Dagsetning og tími",
  home: "heim",
  "Header align": "Haus samræma",
  Footer: "Fótur",
  "Categories Filter": "Flokkar sía",
  "Show only upcoming": "Sýna aðeins komandi",
  "Card(s) in a row": "Kort (s) í röð",
  "Space between cards": "Rými milli korts",
  "Shown events limit": "Sýnir atburðir takmarkanir",
  "Style 1": "Stíll 1",
  "Style 2": "Stíll 2",
  "Style 3": "Stíll 3",
  "Style 4": "Stíll 4",
  "Buttons & Links": "Hnappar og tenglar",
  "Button corner radius": "Radíus hnappsins",
  "Buttons font": "Hnappar leturgerðar",
  "Buttons background": "Hnappar bakgrunnur",
  "Get notified by Email": "Fá tilkynnt með tölvupósti",
  "Review events": "Farið yfir atburði",
  "Click on date": "Smelltu á dagsetningu",
  "Add Event button": "Bættu við atburðarhnappi",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Dagatal Sync gerir þér kleift að samþætta atburði og fundi með Boom Calendar.",
  connect: "Tengdu",
  "Synchronized Calendars": "Samstillt dagatal",
  "Import events": "Flytja inn atburði",
  Disconnect: "Aftengdu",
  "Choose calendar": "Veldu dagatal",
  "Monitor your Wix events through the sync feature":
    "Fylgstu með Wix atburðum þínum í gegnum samstillingaraðgerðina",
  "Connect all your Boom calendars available on your website":
    "Tengdu allar boom dagatalin þín sem er aðgengileg á vefsíðunni þinni",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Tímasettu, taktu þátt og stjórna aðdráttarafundum í gegnum Boom dagatalið okkar.",
  "Monitor your Event Brite events through the Event Brite sync feature.":
    "Fylgstu með atburðinum þínum Brite atburði í gegnum atburðinn Brite Sync aðgerð",
  Email: "Netfang",
  "Add-ons": "Viðbót",
  "Receive notification emails as soon as users add events to your calendar.":
    "Fáðu tilkynningarpóst um leið og notendur bæta viðburði við dagatalið þitt.",
  "Enable + button on the calendar header":
    "Virkja + hnappinn á dagatalshausnum",
  "Accept or decline events added by customers before making them public.":
    "Samþykkja eða hafna atburðum sem viðskiptavinir hafa bætt við áður en þeir gera þá opinbera.",
  "Switch Add Event": "Skiptu um atburði",
  "Enable your browser cookies to connect to your account.":
    "Virkja vafrakökurnar þínar til að tengjast reikningnum þínum.",
  "Learn more": "Læra meira",
  "Print Button": "Prenta hnappinn",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Leyfðu notendum þínum að prenta uppsveifludagatalið þitt í hvaða dagsetningarsvið sem er.",
  "Show Title on mobile": "Sýna titil í farsíma",
  "Show Skeleton on mobile": "Sýna beinagrind í farsíma",
  "Start 7-day Business trial": "Byrjaðu 7 daga viðskiptapróf",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Njóttu allra ótakmarkaðra aðgerða, svo sem selja miða, skráningu, viðburði fyrir gestum.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Vinsamlegast athugið: Í lok prufutímabilsins verður þér skilað í núverandi áskriftaráætlun þína.",
  "Not Now": "Ekki núna",
  "Start free trial": "Byrjaðu ókeypis prufuáskrift",
  "Congrats!": "Til hamingju!",
  "Your 7-day Business trial has been successfully activated.":
    "7 daga viðskiptapróf þín hafa verið virk.",
  Done: "Gert",
  "Title font color": "Titill leturlitur",
  "Desciption font color": "Dreifing leturlitur",
  "Section font color": "Hluti leturlitur",
  "Card Header": "Korthaus",
  Category: "Flokkur",
  "Display at the": "Sýna á",
  top: "Efst",
  bottom: "botn",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Sýndu flokkasíuna efst eða neðst á dagatalinu. Stillingarnar eiga aðeins við um dagskrá og kortaskoðanir",
  "Processing your events": "Vinna úr atburðum þínum",
  "Search for events": "Leitaðu að atburðum",
  "There are no events added": "Það eru engir atburðir bætt við",
  "Location: To be determined": "Staðsetning: Að vera ákvörðuð",
  "No events for selected date": "Engir atburðir fyrir valinn dagsetningu",
  Uncategorized: "Óflokkað",
  "Edit event": "Breyta atburði",
  "Edit original event": "Breyta upprunalegum atburði",
  "Copy event": "Afritaratburður",
  "Copy as new event": "Afritaðu sem nýr viðburður",
  "Delete event": "Eyða atburði",
  "Stop repeating on this date": "Hættu að endurtaka þennan dag",
  "Exclude this date": "Útiloka þessa dagsetningu",
  "Location is going to be announced": "Tilkynnt verður staðsetning",
  "Fill your personal information": "Fylltu persónulegar upplýsingar þínar",
  "Check Box": "Gátreit",
  "Single Choice": "Eitt val",
  Option: "Valmöguleiki",
  "Share Event": "Deildu atburði",
  "Oops! Something went wrong": "Úps! Eitthvað fór úrskeiðis",
  "We are sorry this event has already taken place":
    "Okkur þykir leitt að þessi atburður hefur þegar átt sér stað",
  "Back to calendar": "Aftur í dagatal",
  "This field is required": "Þetta reit er krafist",
  Phone: "Sími",
  "Number field": "Fjöldi reitur",
  "Please provide a valid email": "Vinsamlegast gefðu upp gildan tölvupóst",
  "Select at least one option": "Veldu að minnsta kosti einn valkost",
  "Choose tickets to see total value": "Veldu miða til að sjá heildarverðmæti",
  tickets: "Miðar",
  "Choose Tickets": "Veldu miða",
  "Choose payment method": "Veldu greiðslumáta",
  Pay: "Borgaðu",
  Total: "Alls",
  Free: "Ókeypis",
  "Buy tickets": "Kauptu miða",
  "Sold Out": "Uppselt",
  "Tickets are available": "Miðar eru í boði",
  "Sales End": "Sölumennsku",
  "Availible from": "Gagnleg frá",
  "Go to Orders": "Farðu í pantanir",
  "Go to Details": "Farðu í smáatriði",
  "Group ticket": "Hópmiða",
  Name: "Nafn",
  Price: "Verð",
  "Order by": "Raða eftir",
  "Order ID": "Pöntunarauðkenni",
  Applied: "Beitt",
  Fees: "Gjöld",
  "Enter promo code": "Sláðu inn kynningarkóða",
  Apply: "Notaðu",
  "Promo Code": "Kynningarnúmer",
  Cash: "Reiðufé",
  "You can find your e-tickets attached to your email or download them":
    "Þú getur fundið rafrænu miða þína sem fylgja tölvupóstinum þínum eða halaðu þeim niður",
  here: "hér",
  Time: "Tími",
  "Invalid promo code": "Ógildur kynningarkóði",
  "Credit card": "Kreditkort",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Þú munt brátt fá staðfestingarskilaboð um árangursríka skráningu á netfangið þitt.",
  "You can also check your order details below.":
    "Þú getur líka athugað pöntunarupplýsingar þínar hér að neðan.",
  at: "At",
  Buy: "Kaupa",
  Donation: "Framlag",
  "Enter price": "Sláðu inn verð",
  Choose: "Veldu",
  Chosen: "Valið",
  "Choose your plan": "Veldu áætlun þína",
  week: "vika",
  wk: "wk",
  "Choose plan cycle": "Veldu Plan Cycle",
  months: "mánuðum",
  years: "ár",
  weeks: "vikur",
  "Copy Event Url": "Afritunarslóð",
  "You can find your e-tickets attached to your email or print them":
    "Þú getur fundið rafrænu miða þína fest við tölvupóstinn þinn eða prentað þá",
  "Guest Info": "Gestaupplýsingar",
  "Ticket Info": "Upplýsingar um miða",
  "Ticket name": "Miðanafn",
  "Ticket price": "Miðaverð",
  "Ticket ID": "Miðaauðkenni",
  "If you have any questions contact to organizer":
    "Ef þú hefur einhverjar spurningar hafðu samband við skipuleggjandi",
  "As soon as event ends": "Um leið og atburði lýkur",
  "1 day after event ends": "1 degi eftir að atburði lýkur",
  "7 days after event ends": "7 dögum eftir að atburði lýkur",
  "14 days after event ends": "14 dögum eftir að atburði lýkur",
  "30 days after event ends": "30 dögum eftir að atburði lýkur",
  Menu: "Matseðill",
  "No event for selected date": "Enginn atburður fyrir valinn dagsetningu",
  view: "útsýni",
  List: "Listi",
  Year: "Ár",
  Yearly: "Árlega",
  "Year view header": "Ársýnihaus",
  "Yearly Style": "Árlegur stíll",
  "There are no events": "Það eru engir atburðir",
  Autotranslation: "Sjálfstýring",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Þegar búið er að virkja verður dagatalbúnaðinn þinn þýddur út frá tungumáli vefsíðunnar. *Athugið að svo framarlega sem dagatalsheiti, og lýsingar eru settir inn er ekki hægt að þýða þá.",
  "Note on mobile": "Athugið í farsíma",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Slökktu á eða breyttu texta „No Events“ stikunnar á farsímaútgáfu af dagatalinu",
  Autodeletion: "Sjálfstýring",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Með því að virkja valkostinn mun það sjálfkrafa fjarlægja fyrri atburði þína úr dagatalinu.",
  "This does not apply to repeating events!":
    "Þetta á ekki við um að endurtaka atburði!",
  "Notify event creators about the guest":
    "Tilkynna höfundum viðburða um gestinn",
  "Send event creators notification emails as soon as guests register for their events":
    "Sendu tilkynningartölvupóst við atburði um leið og gestir skrá sig í viðburði sína",
  "List View Type": "Listategund",
  "Description font": "Lýsing leturgerð",
  Connect: "Tengdu",
  "You have no events": "Þú hefur enga atburði",
  Synchronize: "Samstilla",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Google Calendar Sync gerir þér kleift að samþætta viðburði og fundi með Boom Calendar.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Outlook Calendar Sync gerir þér kleift að samþætta atburði og fundi með Boom dagatalinu þínu.",
  "Your message has been sent successfully!":
    "Skilaboðin þín hafa verið send með góðum árangri!",
  "There are no synchronized calendars": "Það eru engar samstilltar dagatal",
  "to view more than 7 events": "að skoða meira en 7 atburði",
  "Mobile app": "Farsímaforrit",
  "Admin Account": "Stjórnandi reikningur",
  Password: "Lykilorð",
  "Second User": "Annar notandi",
  Edit: "EDIT",
  "Guest limit": "Gestamörk",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Allar staðbundnar stillingar eru (sjálfkrafa) byggðar á tungumálinu þínu. Ef tungumál þitt er á listanum er engin þörf á að sérsníða þennan hluta.",
  available: "laus",
  next: "Næst",
  Tickets: "Miðar",
  Quantity: "Magn",
  "Promo code": "Kynningarnúmer",
  "Select a payment method": "Veldu greiðslumáta",
  Fee: "Gjald",
  Book: "Bók",
  "All the tickets have been sold out": "Allir miðar hafa verið uppseldir",
  "Choose at least one ticket": "Veldu að minnsta kosti einn miða",
  "First choose ticket": "Veldu fyrst miða",
  "Please fill out your personal information.":
    "Vinsamlegast fylltu út persónulegar upplýsingar þínar.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "Til að kaupa vel, vinsamlegast veldu valinn greiðslumáta og sláðu inn kynningarnúmerið fyrir afsláttarmiða.",
  "Credit/Debit card": "Kredit-/debetkort",
  "print here.": "prenta hér.",
  "QR code for all tickets": "QR kóða fyrir alla miða",
  Duration: "Lengd",
  "Full Name": "Fullt nafn",
  "Ticket id": "Miðaauðkenni",
  "Group id": "Hópsauðkenni",
  "Choose your ticket.": "Veldu miðann þinn.",
  "Fill out your personal information.":
    "Fylltu út persónulegar upplýsingar þínar.",
  "Add the payment details.": "Bættu við greiðsluupplýsingum.",
  "To be determined": "Að vera ákveðinn",
  "You can find your e-tickets attached to the email or":
    "Þú getur fundið rafrænu miða þína fest við tölvupóstinn eða",
  "print here": "prenta hér",
  "Full name": "Fullt nafn",
  "Group ID": "Hópsauðkenni",
  "to Book": "að bóka",
  "Unfortunately, your card has been declined":
    "Því miður hefur kortinu þínu hafnað",
  "Thank you for your purchase!": "Takk fyrir viðskiptin!",
  "Find your printable e-tickets attached to the confirmation email":
    "Finndu prentvænu rafrænu miðana þína sem fylgja staðfestingarpóstinum",
  Confirm: "Staðfesta",

  "Add event": "Bæta við atburði",
  Events: "Atburðir",
  "Event details": "Upplýsingar um atburði",
  Registration: "Skráning",
  "Guests list": "Gestalisti",
  Ticket: "Miða",
  "General Info": "Almennar upplýsingar",
  "Customize the general settings of your event":
    "Aðlaga almennar stillingar viðburðarins þíns",
  "Event Title": "Titill atburða",
  "e.g. Birthday Party": "t.d. Afmælisveisla",
  "All Day Event": "Allan daginn atburður",
  Cross: "Kross",
  Timeline: "Tímalína",
  "Repeating event": "Endurtekin atburður",
  Location: "Staðsetning",
  "Venue name": "Nafn vettvangs",
  Description: "Lýsing",
  Image: "Mynd",
  Color: "Litur",
  Category: "Flokkur",
  "Add your events to color categories and let your users classify them easily":
    "Bættu viðburði þínum við litaflokka og láttu notendur þína flokka þá auðveldlega",
  "Category name": "Flokkanafn",
  "e.g. Birthdays": "t.d. Afmælisdagar",
  Venue: "Staður",
  "Where the event takes place": "Þar sem atburðurinn fer fram",
  "Venue name": "Nafn vettvangs",
  "Venue phone": "Vettvangssími",
  "Venue email": "Tölvupóstur vettvangs",
  "Venue website": "Vefsíða vettvangs",
  Organizer: "Skipuleggjandi",
  "Person who makes the event": "Manneskja sem gerir atburðinn",
  "Organizer name": "Skipuleggjandi nafn",
  "Organizer phone": "Skipuleggjandi sími",
  "Organizer email": "Skipuleggjandi tölvupóstur",
  "Organizer website": "Skipuleggjandi vefsíða",
  Save: "Vista",
  Cancel: "Hætta við",
  Import: "Flytja inn",
  Past: "Fortíð",
  All: "Allt",
  Upcoming: "Komandi",
  Uncategorised: "Óflokkað",
  "Date Ascending": "Dagsetning stígandi",
  "Date Descending": "Dagsetning lækkandi",
  "Title by A-Z": "Titill eftir A-Z",
  "Title by Z-A": "Titill eftir Z-A",
  "There are no events for this period":
    "Það eru engir atburðir fyrir þetta tímabil",

  "Auto-Convert Date & Time": "Sjálfvirkt umbreytt dagsetning og tími",
  TimeZone: "Tímabelti",
  Autodeletion: "Sjálfstýring",
  "Layout Settings": "Skipulagsstillingar",
  "Yeatly view": "Yeatly View",
  "Monthly view header": "Mánaðarlega útsýni haus",
  "Weekly/Daily view header": "Vikulega/daglega útsýni haus",
  Acendings: "Acendings",
  Descending: "Lækkandi",
  Standart: "Standart",
  Silver: "Silfur",
  Retro: "Aftur",
  Dark: "Myrkur",
  Night: "Nótt",
  Aubergine: "Aubergine",
  "List view header": "Listaskjáhaus",
  "Side by Side View": "Hlið við hlið",
  "Customize Proportions": "Aðlaga hlutföll",
  "Card Margins": "Kortamörk",
  "Image opacity (%)": "Ógagnsæi myndar (%)",
  "Side by Side Header": "Hlið við hlið haus",
  "Text Align": "Texti samræma",
  "Timeline View": "Tímalínu",
  "Title font color": "Titill leturlitur",
  "Desciption font color": "Dreifing leturlitur",
  "Line color": "Línulit",
  "Date Font color": "Dagsetning leturlitur",
  "Daily events background": "Daglegur atburður bakgrunnur",
  Alignment: "Jöfnun",
  Vertical: "Lóðrétt",
  Horizontal: "Lárétt",
  "Vertical Alignment": "Lóðrétt röðun",
  Right: "Ekki satt",
  Center: "Miðja",
  "Horizontal Alignment": "Lárétt röðun",
  Top: "Efst",
  Center: "Miðja",
  Bottom: "Botn",
  "Dates Circle Design": "Dagsetningarhringhönnun",
  "Next To The Circle": "Við hliðina á hringnum",
  "In The Circle": "Í hringnum",
  "Timeline Header": "Tímalínuhaus",
  Timeline: "Tímalína",
  "Show only upcoming": "Sýna aðeins komandi",
  "Order by": "Raða eftir",
  "Timeline Event Limit": "Tímalínuviðburðamörk",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Leyfa gestinum að bæta viðburði við staðbundna kálfa: Google, Yahoo, Outlook, Icalendar.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Leyfðu gestinum að deila viðburðinum þínum á Facebook, LinkedIn, Twitter og ETC.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Bættu við leitarmöguleika á dagatalinu þínu til að láta fólk leita við atburði eftir titli, vettvangi osfrv.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Leyfðu notendum þínum að prenta uppsveifludagatalið þitt í hvaða dagsetningarsvið sem er.",
  "Click to apply a theme to Calendar": "Smelltu til að beita þema á dagatal",
  "Date container color": "Litur í gámum",
  "Daily events background": "Daglegur atburður bakgrunnur",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Notaðu viðbótina til að setja upp háþróaða eiginleika á dagatalunum þínum, sem gerir þær virkari!",
  "Open Add-ons Store": "Opnaðu verslunina",
  Monday: "Mánudagur",
  Tuesday: "Þriðjudagur",
  Wednesday: "Miðvikudag",
  Thursday: "Fimmtudag",
  Friday: "Föstudag",
  Saturday: "Laugardag",
  Sunday: "Sunnudagur",
  "Yearly view": "Árlega skoðun",
  Ascending: "Stígandi",
  "Show event time next to title": "Sýna viðburðartíma við hliðina á titli",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Aðlagaðu dagsetningu og tíma atburðarins að staðartíma notandans út frá tímabelti þeirra.",
  "Display the time zone alongside the event date.":
    "Birtu tímabeltið samhliða viðburðinum.",
  "Show event time next to title": "Sýna viðburðartíma við hliðina á titli",
  "Time Zone": "Tímabelti",
  "Upload Image": "Hlaða mynd",
  "Choose a Category": "Veldu flokk",
  "Color you have chosen will not be shown as you choose category":
    "Litur sem þú hefur valið verður ekki sýndur þar sem þú velur flokk",
  Website: "Vefsíðu",
  Next: "Næst",
  Save: "Vista",
  "Last Name": "Eftirnafn",
  "Personal Info": "Persónulegar upplýsingar",
  Back: "Aftur",
  "This field is required": "Þetta reit er krafist",
  "Your event has been submitted": "Viðburðurinn þinn hefur verið lagður inn",
  "Enter a location": "Sláðu inn staðsetningu",
  "Display the time zone alongside the event date.":
    "Birtu tímabeltið samhliða viðburðinum.",
  Home: "Heim",
  "Side By Side Event Limit": "Hlið við hlið atburðarmörk",
  "Mobille App": "MOMILLE APP",
  category: "Flokkur",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Fylgstu auðveldlega með dagskránni þinni með því að flytja Facebook viðburði þína inn í dagatalið þitt.",
  "Synchronized Pages": "Samstilltar síður",
  "There are no synchronized pages": "Það eru engar samstilltar síður",
  "Choose page": "Veldu síðu",
  "You have no events": "Þú hefur enga atburði",
};
export default is;
