let it = {
  Categories: "Categorie",
  "Share this event": "Condividi questo evento",
  Language: "Linguaggio",
  "Show Time Zone": "Mostra fuso orario",
  "Custom Local Settings": "Impostazioni locali personalizzate",
  "Add and showcase events on your site using a beautiful calendar.":
    "Aggiungi e mostra gli eventi sul tuo sito utilizzando un bellissimo calendario . ",
  "Week Days": "Giorni della settimana",
  "Manage Events": "Gestisci eventi",
  General: "Generale",
  "Layout Picker": "Selettore layout",
  Month: "Mese",
  Monthly: "Mensile",
  Week: "Settimana",
  Weekly: "Settimanalmente",
  Day: "Giorno",
  Daily: "Quotidiano",
  Agenda: "Agenda",
  "Navigation Buttons": "Pulsanti di navigazione",
  "Week numbers": "Numeri settimanali",
  "Include Weekends": "Includi fine settimana",
  "All-day": "Tutto il giorno",
  "All Day": "Tutto il giorno",
  Label: "Etichetta",
  "Fit to Height": "Adatta all'altezza",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Per impostare proporzioni app disabilita manualmente questa opzione e ridimensiona il calendario in Editor. ",
  "Default Layout": "Layout predefinito",
  "Monthly view": "Vista mensile",
  "Weekly and Daily view": "Vista settimanale e giornaliera",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Puoi offrire ai visitatori un'esperienza più coerente mostrando lo stesso numero di settimane ( 6) alla volta.",
  "Fixed Weekly Layout": "Layout settimanale fisso",
  back: "indietro",
  Row: "Riga",
  "Hours in Weekly View": "Ore nella vista settimanale",
  "Hours in Daily View": "Ore nella vista giornaliera",
  Start: "Inizio",
  End: "Fine",
  "At This Hour": "A quest'ora",
  Button: "Pulsante",
  Buttons: "Pulsanti",
  Sunday: "Domenica",
  Monday: "Lunedi",
  Tuesday: "Martedì",
  Wednesday: "Mercoledì",
  Thursday: " Giovedì ",
  Friday: "Venerdì",
  Saturday: "Sabato",
  "Default Date": "Data predefinita",
  year: " anno ",
  month: " mese ",
  mo: " mese ",
  days: " giorni ",
  ago: " ago ",
  ahead: " avanti ",
  Yesterday: "Ieri",
  Today: "Oggi",
  Tomorrow: "Domani",
  Custom: "Custom",
  "Set Daily Rows Limit": "Imposta limite righe giornaliere",
  "Set Proportions": "Imposta proporzioni",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Consenti al visitatore di aggiungere un evento ai Calnedars locali , Google, Yahoo, Outlook, ICalendar . ",
  Container: "Contenitore",
  Background: "Sfondo",
  "Container Background": "Sfondo contenitore",
  "Container Borders": "Confini del contenitore",
  Calendar: "Calendario",
  "Event Info Tooltip": "Descrizione info evento",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Quando le persone passano il mouse sopra un evento vedranno tutte le informazioni a riguardo in una descrizione comandi. ",
  "Event Info Window": "Finestra informazioni evento",
  "This is the full information window that opens when someone clicks on the event.":
    "Questa è la finestra con le informazioni complete che si apre quando qualcuno fa clic sull'evento. ",
  "Use Gradient": "Usa sfumatura",
  Vertical: "Verticale",
  Horizontal: "Orizzontale",
  First: "Primo",
  Second: "Secondo",
  diagonal: " diagonale ",
  Radial: "Radiale",
  "Select option": "Selezionare l'opzione",
  Solid: "Solido",
  Dotted: "Tratteggiata",
  Dashed: "Tratteggiata",
  Double: "Doppio",
  "Border Radius": "Raggio di confine",
  Padding: "Imbottitura",
  "Date Header": "Intestazione data",
  "Event Default Color": "Colore predefinito evento",
  "Days of Week": "Giorni della settimana",
  "Days of Week Background": "Sfondo giorni della settimana",
  Date: "Data",
  "Event Title": "Titolo evento",
  "Highlight today": "Evidenzia oggi",
  "Highlight Color": "Evidenzia colore",
  Hide: "Nascondere",
  "Calendar Border Color": "Colore bordo calendario",
  "Calendar Border Width": "Larghezza bordo calendario",
  "Calendar Border Style": "Stile bordo calendario",
  "Font Color": "Colore del carattere",
  "Event Background": "Sfondo dell'evento",
  "Card Date Color": "Colore data carta",
  "Title Font": "Carattere del titolo",
  "Date Font": "Carattere data",
  "Description Font": "Carattere descrizione",
  "Button Background": "Sfondo pulsante",
  "Button Text": "Testo pulsante",
  "Border Color": "Colore del bordo",
  "Border Width": "Larghezza del bordo",
  "Border Type": "Tipo di bordo",
  Title: "Titolo",
  Description: "Descrizione",
  "Background Color": "Colore di sfondo",
  Divider: "Divisore",
  "Event Details Font": "Carattere dettagli evento",
  "Website Link Color": "Colore link sito Web",
  "Developer Info": "Informazioni sviluppatore",
  "User Guide": "Guida utente",
  "Support e-mail": "Supporto e-mail",
  "Our Website": "Il nostro sito web",
  "App Review": "Revisione app",
  "Enjoying App? Leave us a review in the App Market.":
    "Ti piace l'app? Lasciaci una recensione nel mercato delle app. ",
  "Review Us": "Revisionaci",
  "Connect With Us": "Mettiti in comunicazione con noi",
  "What's your email?": "Qual è la tua email? ",
  "Invalid email address!": "Indirizzo email non valido! ",
  Comments: "Commenti",
  "We'd love to hear from you. Send us a message.":
    "Ci piacerebbe avere tue notizie. Inviaci un messaggio. ",
  "Message must be at least 5 characters long":
    "Il messaggio deve contenere almeno 5 caratteri",
  Send: "Inviare",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Se si desidera consentire all'utente di alternare le visualizzazioni del calendario, abilitare questa opzione e scegliere le visualizzazioni che si desidera mostrare. ",
  Main: "Principale",
  Localize: "Localizzare",
  Settings: "Impostazioni",
  Layouts: "Disposizione",
  Advanced: "Avanzati",
  Design: "Disegno",
  Support: "Supporto",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Tutte le impostazioni locali sono (automaticamente) in base alla tua lingua. Se la tua lingua è nell'elenco, non è necessario personalizzare questa sezione.",
  "Date Format": "Formato data",
  "Time Format": "Formato orario",
  "Text Direction": "Direzione del testo",
  "Left to Right": "Da sinistra a destra",
  "Right to Left": "Da destra a sinistra",
  "Week Starts On": "La settimana inizia",
  "Agenda Style": "Stile agenda",
  Classic: "Classic",
  Modern: "Modern",
  "Agenda Header": "Intestazione agenda",
  "Upcoming Events": "Prossimi eventi",
  "Agenda Event Limit": "Limite evento agenda",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Esegui l'upgrade ora e ottieni molte più funzioni e goditi appieno la tua APP!",
  "Upgrade Now": "Aggiorna ora",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Ospitare eventi che durano tutto il giorno? Questo ti consente di mostrarli sul tuo calendario.",
  "24 hours": "24 ore",
  Sat: "Sab",
  Sun: "Dom",
  Mon: "Lun",
  Default: "Default",
  "Select custom design style for your calendar.":
    "Seleziona uno stile di design personalizzato per il tuo calendario.",
  Style: "Stile",
  "Styles and Colors": "Stili e colori",
  "Calendar Name": "Nome del calendario",
  "Write your Calendar name here": "Scrivi qui il nome del tuo calendario",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Questo non è visibile ai tuoi utenti. Imposta i nomi per differenziare i tuoi calendari quando usi la funzione Sincronizzazione Boom Calendar.",
  "General Info": "Informazioni generali",
  Venue: "sede",
  Organizer: "Organizzatore",
  Search: "Ricerca",
  "Add to": "Aggiungere a",
  calendar: "calendario",
  "Copy event URL": "Copia l'URL dell'evento",
  "Copied!": "Copiato!",
  "Add & Share": "Aggiungi e condividi",
  Map: "Carta geografica",
  "Calendar view": "Visualizzazione calendario",
  "Add Event": "Aggiungi evento",
  Uncategorised: "Non categorizzato",
  More: "Di Più",
  Less: "Di meno",
  Register: "Registrati",
  Card: "Carta",
  Guests: "Ospiti",
  unlimited: "illimitato",
  "Show more": "Mostra di più",
  "Enable Search": "Abilita ricerca",
  "+ Add Event": "+ Aggiungi evento",
  "Manage and Sync": "Gestisci e sincronizza",
  "Show event details as...": "Mostra i dettagli dell'evento come ...",
  Tooltip: "tooltip",
  Popup: "Info box",
  None: "Nessuna",
  "Show Category": "Mostra categoria",
  "Header Align": "Allinea intestazione",
  "Show Time": "Orario dello spettacolo",
  "Hours in Weekly/Daily View": "Ore in Vista settimanale / giornaliera",
  "Share Events": "Condividi eventi",
  Shadow: "Ombra",
  "Inner Padding": "Imbottitura interna",
  Text: "Testo",
  "Active Button Border": "Bordo pulsante attivo",
  "Light Mode": "Modalità luce",
  "Event Text Color": "Colore del testo dell'evento",
  Dates: "Date",
  Skeleton: "Scheletro",
  "Skeleton Color": "Colore scheletro",
  Width: "Larghezza",
  "Skeleton Style": "Stile scheletro",
  Color: "Colore",
  "Section Titles": "Titoli di sezione",
  "Section Content": "Contenuto della sezione",
  Header: "Intestazione",
  Standard: "Standard",
  Retro: "Retrò",
  Silver: "Argento",
  Night: "Notte",
  Dark: "Buio",
  Aubergine: "Melanzana",
  "Map Header": "Intestazione della mappa",
  "Show Title in mobile": "Mostra il titolo sul cellulare",
  "Card View": "Visualizzazione scheda",
  "Card background color": "Colore di sfondo della carta",
  "Title font": "Carattere del titolo",
  "Desciption font": "Carattere descrizione",
  "Section font": "Sezione dei caratteri",
  "Section divider color": "Colore divisore di sezione",
  "Add event": "Aggiungi evento",
  "All Day Event": "Evento tutto il giorno",
  Location: "Posizione",
  "Choose a category": "Scegli una categoria",
  "Venue name": "Nome sede",
  "Venue phone": "Telefono sede",
  "Venue email": "Email sede",
  "Venue website": "Sito web della sede",
  "Organizer name": "Nome organizzatore",
  "Organizer phone": "Telefono organizzatore",
  "Organizer email": "Email organizzatore",
  "Organizer website": "Sito web dellorganizzatore",
  "Personal info": "Informazioni personali",
  "First name": "Nome di battesimo",
  "Last name": "Cognome",
  "Email Address": "Indirizzo e-mail",
  "Additional Notes": "Note aggiuntive",
  Back: "Indietro",
  Save: "Salva",
  Next: "Il prossimo",
  "Your event has been submitted": "Il tuo evento è stato inviato",
  "Event submittion has been failed": "\tLinvio dellevento non è riuscito",
  "e.g. Birthday Party": "per esempio. Festa di compleanno",
  "First Name": "Nome di battesimo",
  "Last Name": "Cognome",
  "Phone Number": "Numero di telefono",
  Address: "Indirizzo",
  "Your comments": "I tuoi commenti",
  "How many guests?": "Quanti ospiti?",
  "Anything else we need to know?": "C'è qualcos'altro che dobbiamo sapere?",
  "Guests:": "Ospiti:",
  Submit: "Invia",
  "Go to Calendar": "Vai al calendario",
  "Registration completed successfully!":
    "Registrazione completata con successo!",
  "Please check your registered email address":
    "Per favore controlla il tuo indirizzo email registrato",
  "Add to Calendar": "Aggiungi al calendario",
  "Share this Event": "Condividi questo evento",
  "Sorry something went wrong": "מצטערים, משהו השתבש",
  "Back to registration": "Torna alla registrazione",
  "Date & Location": "Data e posizione",
  "Date & Time": "Appuntamento",
  home: "casa",
  "Header align": "Allineamento intestazione",
  Footer: "Piè di pagina",
  "Categories Filter": "Filtro categorie",
  "Show only upcoming": "Mostra solo in arrivo",
  "Card(s) in a row": "Carta / e di fila",
  "Space between cards": "Spazio tra le carte",
  "Shown events limit": "Limite eventi mostrato",
  "Style 1": "Stile 1",
  "Style 2": "Stile 2.",
  "Style 3": "Stile 3",
  "Style 4": "Stile 4",
  "Buttons & Links": "Pulsanti e collegamenti",
  "Button corner radius": "Raggio dell'angolo del pulsante",
  "Buttons font": "Carattere dei pulsanti",
  "Buttons background": "Sfondo di pulsanti",
  "Get notified by Email": "Ricevi una notifica tramite e-mail",
  "Review events": "Rivedi gli eventi",
  "Click on date": "Fare clic sulla data",
  "Add Event button": "Pulsante Aggiungi evento",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Calendar Sync ti consente di integrare i tuoi eventi e le tue sessioni con il tuo calendario BOOM.",
  connect: "Collegare",
  "Synchronized Calendars": "Calendari sincronizzati",
  "Import events": "Importa eventi",
  Disconnect: "Disconnetti",
  "Choose calendar": "Scegli il calendario",
  "Monitor your Wix events through the sync feature":
    "Monitora i tuoi eventi Wix attraverso la funzione di sincronizzazione",
  "Connect all your Boom calendars available on your website":
    "Collega tutti i tuoi calendari Boom disponibili sul tuo sito web",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Pianifica, partecipa e gestisci le riunioni Zoom direttamente tramite il nostro calendario Boom.",
  "Monitor your Event Brite events through the Event Brite sync feature.":
    "Monitora i tuoi eventi Event Brite tramite la funzione di sincronizzazione Event Brite",
  Email: "E-mail",
  "Add-ons": "Componenti aggiuntivi",
  "Receive notification emails as soon as users add events to your calendar.":
    "Ricevere e-mail di notifica non appena gli utenti aggiungono eventi al tuo calendario.",
  "Enable + button on the calendar header":
    "Enable + button on the calendar header",
  "Accept or decline events added by customers before making them public.":
    "Accept or decline events added by customers before making them public.",
  "Switch Add Event": "Switch Aggiungi evento",
  "Enable your browser cookies to connect to your account.":
    "Abilita i cookie del browser di connettersi al tuo account.",
  "Learn more": "Per saperne di più",
  "Print Button": "印刷ボタン",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Permetti ai tuoi utenti di stampare il calendario degli eventi BOOM in qualsiasi intervallo di date.",
  "Show Title on mobile": "Mostra titolo su Mobile",
  "Show Skeleton on mobile": "Mostra scheletro sul cellulare",
  "Start 7-day Business trial": "Inizia il tuo processo aziendale di 7 giorni",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Goditi tutte le funzionalità illimitate, come il biglietto di vendita, la registrazione, i componenti aggiuntivi degli eventi dei visitatori.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Nota: alla fine del periodo di prova, verrà restituito al piano di abbonamento esistente.",
  "Not Now": "Non adesso",
  "Start free trial": "Inizia la prova gratuita",
  "Congrats!": "Congratulazioni!",
  "Your 7-day Business trial has been successfully activated.":
    "Il tuo processo aziendale di 7 giorni è stato attivato con successo.",
  Done: "Fatto",
  "Title font color": "Titolo del carattere Color.",
  "Desciption font color": "Descrizione Font Color.",
  "Section font color": "Sezione Carattere Colore",
  "Card Header": "Intestazione della carta",
  Category: "Categoria",
  "Display at the": "Mostra al",
  top: "superiore",
  bottom: "parte inferiore",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Mostra il filtro della categoria in alto o nella parte inferiore del calendario.Le impostazioni si applicano solo all'agenda e alle viste delle carte",
  "Processing your events": "Elaborare i tuoi eventi",
  "Search for events": "Cerca eventi",
  "There are no events added": "Non ci sono eventi aggiunti",
  "Location: To be determined": "Posizione: da determinare",
  "No events for selected date": "Nessun evento per data selezionata",
  Uncategorized: "Non categorizzato",
  "Edit event": "Modifica evento",
  "Edit original event": "Modifica evento originale",
  "Copy event": "Copia evento",
  "Copy as new event": "Copia come nuovo evento",
  "Delete event": "Elimina evento",
  "Stop repeating on this date": "Smetti di ripetere in questa data",
  "Exclude this date": "Escludere questa data",
  "Location is going to be announced": "La posizione verrà annunciata",
  "Fill your personal information": "Riempi le tue informazioni personali",
  "Check Box": "Casella di controllo",
  "Single Choice": "Scelta singola",
  Option: "Opzione",
  "Share Event": "Evento di condivisione",
  "Oops! Something went wrong": "Oops!Qualcosa è andato storto",
  "We are sorry this event has already taken place":
    "Siamo spiacenti che questo evento abbia già avuto luogo",
  "Back to calendar": "Torna al calendario",
  "This field is required": "Questo campo è obbligatorio",
  Phone: "Telefono",
  "Number field": "Campo numerico",
  "Please provide a valid email": "Per favore inserisci un'email valida",
  "Select at least one option": "Seleziona almeno un'opzione",
  "Sold Out": "Venduto",
  "Tickets are available": "I biglietti sono disponibili",
  "Sales End": "Fine delle vendite",
  "Buy tickets": "Comprare biglietti",
  "Availible from": "Disponibile dal",
  "Go to Orders": "Vai agli ordini",
  "Go to Details": "Vai ai dettagli",
  "Group ticket": "Biglietto di gruppo",
  Name: "Nome",
  Price: "Prezzo",
  "Order by": "Ordinato da",
  "Order ID": "ID ordine",
  Applied: "Applicato",
  Fees: "Commissioni",
  "Enter promo code": "Immettere il codice promozionale",
  Apply: "Applicare",
  "Promo Code": "Codice promozionale",
  Cash: "Contanti",
  "You can find your e-tickets attached to your email or download them":
    "Puoi trovare i tuoi biglietti elettronici allegati alla tua e-mail o scaricarli",
  here: "qui",
  Time: "Volta",
  "Invalid promo code": "Codice promozionale non valido",
  "Credit card": "Carta di credito",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Presto riceverai un messaggio di conferma della registrazione riuscita al tuo indirizzo email.",
  "You can also check your order details below.":
    "Di seguito puoi anche controllare i dettagli dell'ordine.",
  at: "a",
  Buy: "Acquistare",
  Donation: "Donazione",
  "Enter price": "Impresa",
  Choose: "Scegliere",
  Chosen: "Scelto",
  "Choose your plan": "Scegli il tuo piano",
  week: "settimana",
  wk: "settimana",
  "Choose plan cycle": "Scegli il ciclo del piano",
  months: "mesi",
  years: "anni",
  weeks: "settimane",
  "Copy Event Url": "Copia URL evento",
  "You can find your e-tickets attached to your email or print them":
    "Puoi trovare i tuoi biglietti elettronici allegati alla tua e-mail o stamparli",
  "Guest Info": "Informazioni per gli ospiti",
  "Ticket Info": "Informazioni sul biglietto",
  "Ticket name": "Nome del biglietto",
  "Ticket price": "Prezzo del biglietto",
  "Ticket ID": "Ticket ID",
  "If you have any questions contact to organizer":
    "Se hai domande contatta per l'organizzatore",
  "As soon as event ends": "Non appena l'evento termina",
  "1 day after event ends": "1 giorno dopo la fine dell'evento",
  "7 days after event ends": "7 giorni dopo la fine dell'evento",
  "14 days after event ends": "14 giorni dopo la fine dell'evento",
  "30 days after event ends": "30 giorni dopo la fine dell'evento",
  Menu: "Menù",
  "No event for selected date": "Nessun evento per la data selezionata",
  view: "visualizzazione",
  List: "Elenco",
  Year: "Anno",
  Yearly: "Annuale",
  "Year view header": "Testa di visualizzazione dell'anno",
  "Yearly Style": "Stile annuale",
  "There are no events": "Non ci sono eventi",
  Autotranslation: "Autotrasimazione",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Una volta abilitato, il tuo widget del calendario sarà tradotto in base alla lingua del sito web.* Si noti che finché il titolo del calendario e le descrizioni vengono immesse i testi che non possono essere tradotti.",
  "Note on mobile": "Nota su Mobile.",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Spegnere o modificare il testo della barra 'No Eventi' sulla versione mobile del calendario",
  Autodeletion: "Autodelezione",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Abilitando l'opzione, rimuoverà automaticamente i tuoi eventi passati dal calendario.",
  "This does not apply to repeating events!":
    "Questo non si applica agli eventi ripetuti!",
  "Notify event creators about the guest": "Informare gli utenti sull'ospite",
  "Send event creators notification emails as soon as guests register for their events":
    "Invia email di notifica ai creatori di eventi non appena gli ospiti si registrano per i loro eventi",
  "List View Type": "Tipo di visualizzazione elenco",
  "Description font": "Carattere descrizione",
  Connect: "Collegare",
  "You have no events": "Non hai eventi",
  Synchronize: "Sincronizzare",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Google Calendar Sync ti consente di integrare i tuoi eventi e le tue sessioni con il tuo calendario BOOM.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Outlookカレンダーの同期を使用すると、イベントとセッションをブームカレンダーと統合できます。",
  "Your message has been sent successfully!":
    "あなたのメッセージは正常に送信されました！",
  "There are no synchronized calendars": "Non ci sono calendari sincronizzati",
  "to view more than 7 events": "7つ以上のイベントを見るために",
  "Mobile app": "モバイルアプリ",
  "Admin Account": "管理者アカウント",
  Password: "パスワード",
  "Second User": "Secondo utente",
  Edit: "modificare",
  "Guest limit": "Limite ospiti",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Tutte le impostazioni locali sono (automaticamente) in base alla tua lingua.Se la tua lingua è sulla lista, non c'è bisogno di personalizzare questa sezione.",
  available: "a disposizione",
  next: "Il prossimo",
  Tickets: "Biglietti",
  Quantity: "Quantità",
  "Promo code": "Codice promozionale",
  "Select a payment method": "Seleziona un metodo di pagamento",
  Fee: "A pagamento",
  Book: "Libro",
  "All the tickets have been sold out": "Tutti i biglietti sono stati esauriti",
  "Choose at least one ticket": "Scegli almeno un biglietto",
  "First choose ticket": "Prima scegli il biglietto",
  "Please fill out your personal information.":
    "Si prega di compilare le tue informazioni personali.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "Per effettuare un acquisto di successo, selezionare il metodo di pagamento preferito e inserisci il codice promozionale per i biglietti scontati.",
  "Choose payment method": "scegli il metodo di pagamento",
  "Credit/Debit card": "Carta di credito / debito",
  "print here.": "Stampa qui.",
  "QR code for all tickets": "Codice QR per tutti i biglietti",
  Duration: "Durata",
  "Full Name": "Nome e cognome",
  Total: "Totale",
  "Ticket id": "ID Biglietto",
  "Group id": "ID Gruppo",
  "Choose your ticket.": "Scegli il tuo biglietto.",
  "Fill out your personal information.":
    "Compila le tue informazioni personali.",
  "Add the payment details.": "Aggiungi i dettagli di pagamento.",
  "To be determined": "Essere determinati",
  Pay: "pagare",
  Free: "Gratuita",
  "You can find your e-tickets attached to the email or":
    "Puoi trovare i tuoi biglietti elettronici allegati all'e-mail o",
  "print here": "Stampa qui",
  "Full name": "Nome e cognome",
  "Group ID": "ID Gruppo",
  "to Book": "prenotare",
  "Unfortunately, your card has been declined":
    "Sfortunatamente, la tua carta è stata rifiutata",
  "Thank you for your purchase!": "Grazie per il vostro acquisto!",
  "Find your printable e-tickets attached to the confirmation email":
    "Trova i tuoi biglietti elettronici stampabili allegati all'e-mail di conferma",
  Confirm: "Confermare",

  "Add event": "Aggiungi evento",
  Events: "Eventi",
  "Event details": "Dettagli dell'evento",
  Registration: "Registrazione",
  "Guests list": "Elenco degli ospiti",
  Ticket: "Biglietto",
  "General Info": "Informazioni generali",
  "Customize the general settings of your event":
    "Personalizza le impostazioni generali del tuo evento",
  "Event Title": "Titolo dell'evento",
  "e.g. Birthday Party": "per esempio. Festa di compleanno",
  "All Day Event": "Evento per tutto il giorno",
  Cross: "Attraverso",
  Timeline: "Sequenza temporale",
  "Repeating event": "Evento ripetuto",
  Location: "Posizione",
  "Venue name": "Nome del luogo",
  Description: "Descrizione",
  Image: "Immagine",
  Color: "Colore",
  Category: "Categoria",
  "Add your events to color categories and let your users classify them easily":
    "Aggiungi i tuoi eventi alle categorie di colori e lascia che i tuoi utenti li classifichino facilmente",
  "Category name": "Nome della categoria",
  "e.g. Birthdays": "per esempio. Compleanni",
  Venue: "Luogo",
  "Where the event takes place": "Dove si svolge l'evento",
  "Venue name": "Nome del luogo",
  "Venue phone": "Telefono",
  "Venue email": "Email del luogo",
  "Venue website": "Sito web del luogo",
  Organizer: "Organizzatore",
  "Person who makes the event": "Persona che fa l'evento",
  "Organizer name": "Nome organizzatore",
  "Organizer phone": "Telefono organizzatore",
  "Organizer email": "Email dell'organizzatore",
  "Organizer website": "Sito web dell'organizzatore",
  Save: "Salva",
  Cancel: "Annulla",
  Import: "Importare",
  Past: "Passato",
  All: "Tutto",
  Upcoming: "Imminente",
  Uncategorised: "Non categorializzato",
  "Date Ascending": "Data ascendente",
  "Date Descending": "Data discendente",
  "Title by A-Z": "Titolo di A-Z",
  "Title by Z-A": "Titolo di Z-A",
  "There are no events for this period":
    "Non ci sono eventi per questo periodo",

  "Auto-Convert Date & Time": "Data e ora del converte automatico",
  TimeZone: "Fuso orario",
  Autodeletion: "Autodelezione",
  "Layout Settings": "Impostazioni di Layout",
  "Yeatly view": "Visualizza yeatly",
  "Monthly view header": "Testa di visualizzazione mensile",
  "Weekly/Daily view header": "Intestazione settimanale/Daily View",
  Acendings: "Acendings",
  Descending: "Discendente",
  Standart: "Standart",
  Silver: "Argento",
  Retro: "Retrò",
  Dark: "Buio",
  Night: "Notte",
  Aubergine: "Melanzana",
  "List view header": "Elenco Visualizza intestazione",
  "Side by Side View": "A fianco della vista",
  "Customize Proportions": "Personalizza le proporzioni",
  "Card Margins": "Margini delle carte",
  "Image opacity (%)": "Immagine Opacity (%)",
  "Side by Side Header": "Testata fianco a fianco",
  "Text Align": "Testo allineare",
  "Timeline View": "Vista della sequenza temporale",
  "Title font color": "Colore del carattere del titolo",
  "Desciption font color": "Desciption Font Color",
  "Line color": "Colore della linea",
  "Date Font color": "Data di carattere colore",
  "Daily events background": "Background degli eventi quotidiani",
  Alignment: "Allineamento",
  Vertical: "Verticale",
  Horizontal: "Orizzontale",
  "Vertical Alignment": "Allineamento verticale",
  Right: "Giusto",
  Center: "Centro",
  "Horizontal Alignment": "Allineamento orizzontale",
  Top: "Superiore",
  Center: "Centro",
  Bottom: "Metter il fondo a",
  "Dates Circle Design": "Date Design del cerchio",
  "Next To The Circle": "Accanto al cerchio",
  "In The Circle": "Nel cerchio",
  "Timeline Header": "Testa della sequenza temporale",
  Timeline: "Sequenza temporale",
  "Show only upcoming": "Mostra solo imminente",
  "Order by": "Ordinato da",
  "Timeline Event Limit": "Limite di eventi della sequenza temporale",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Consenti ai visitatori di aggiungere un evento ai calnear locali: Google, Yahoo, Outlook, ICALENDAR.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Consenti ai visitatori di condividere il tuo evento su Facebook, LinkedIn, Twitter e ecc.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Aggiungi un'opzione di ricerca sul tuo calendario per consentire alle persone di cercare i tuoi eventi per titolo, sede, ecc.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Consenti ai tuoi utenti di stampare il tuo calendario per eventi boom in qualsiasi intervallo di date.",
  "Click to apply a theme to Calendar":
    "Fare clic per applicare un tema al calendario",
  "Date container color": "Colore del contenitore della data",
  "Daily events background": "Background degli eventi quotidiani",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Usa i componenti aggiuntivi per installare funzionalità avanzate sui calendari, rendendole più funzionali!",
  "Open Add-ons Store": "Apri i componenti aggiuntivi",
  Monday: "Lunedi",
  Tuesday: "Martedì",
  Wednesday: "Mercoledì",
  Thursday: "Giovedì",
  Friday: "Venerdì",
  Saturday: "Sabato",
  Sunday: "Domenica",
  "Yearly view": "Vista annuale",
  "Yearly view": "Vista annuale",
  Ascending: "Ascendente",
  "Show event time next to title":
    "Mostra il tempo dell'evento accanto al titolo",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Regola la data e l'ora dell'evento all'ora locale dell'utente in base al proprio fuso orario.",
  "Display the time zone alongside the event date.":
    "Visualizza il fuso orario insieme alla data dell'evento.",
  "Show event time next to title":
    "Mostra il tempo dell'evento accanto al titolo",
  "Time Zone": "Fuso orario",
  "Upload Image": "Carica immagine",
  "Choose a Category": "Scegli una categoria",
  "Color you have chosen will not be shown as you choose category":
    "Il colore che hai scelto non verrà mostrato quando scegli la categoria",
  Website: "Sito web",
  Next: "Prossimo",
  Save: "Salva",
  "Last Name": "Cognome",
  "Personal Info": "Informazioni personali",
  Back: "Indietro",
  "This field is required": "Questo campo è obbligatorio",
  "Your event has been submitted": "Il tuo evento è stato inviato",
  "Enter a location": "Immettere una posizione",
  "Display the time zone alongside the event date.":
    "Visualizza il fuso orario insieme alla data dell'evento.",
  Home: "Casa",
  "Side By Side Event Limit": "Limite di evento side by side",
  "Mobille App": "App Mobille",
  category: "categoria",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Tieni facilmente traccia del tuo programma importando i tuoi eventi di Facebook nel tuo calendario.",
  "Synchronized Pages": "Pagine sincronizzate",
  "There are no synchronized pages": "Non ci sono pagine sincronizzate",
  "Choose page": "Scegli pagina",
  "You have no events": "Non hai eventi",
};
export default it;
