let ka = {
  Categories: "კატეგორიები",
  "Share this event": "გააზიარე ეს ღონისძიება",
  Language: "Ენა",
  "Show Time Zone": "აჩვენეთ დროის ზონა",
  "Custom Local Settings": "ადგილობრივი ადგილობრივი პარამეტრები",
  "Add and showcase events on your site using a beautiful calendar.":
    "დაამატეთ და აჩვენეთ ღონისძიებები თქვენს საიტზე ლამაზი კალენდრის გამოყენებით.",
  "Week Days": "Კვირის დღეები",
  "Manage Events": "ღონისძიებების მართვა",
  General: "გენერალი",
  "Layout Picker": "განლაგების ამომრჩეველი",
  Month: "თვე",
  Monthly: "ყოველთვიური",
  Week: "კვირა",
  Weekly: "ყოველკვირეული",
  Day: "Დღეს",
  Daily: "ყოველდღიური",
  Agenda: "დღის წესრიგი",
  "Navigation Buttons": "ნავიგაციის ღილაკები",
  "Week numbers": "კვირის ნომრები",
  "Include Weekends": "შაბათ -კვირას ჩართეთ",
  "All-day": "Მთელი დღე",
  "All Day": "Მთელი დღე",
  Label: "იარლიყი",
  "Fit to Height": "მოთავსებული სიმაღლეზე",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "აპლიკაციების პროპორციების დაყენება Manully გამორთეთ ეს ვარიანტი და შეცვალეთ კალენდარი რედაქტორში.",
  "Default Layout": "ნაგულისხმევი განლაგება",
  "Monthly view": "ყოველთვიური ხედი",
  "Weekly and Daily view": "ყოველკვირეული და ყოველდღიური ხედი",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "თქვენ შეგიძლიათ სტუმრებს უფრო თანმიმდევრული გამოცდილება მიანიჭოთ იმავე კვირების (6) იმავე რაოდენობის ჩვენებით.",
  "Fixed Weekly Layout": "ფიქსირებული ყოველკვირეული განლაგება",
  back: "ზურგი",
  Row: "რიგი",
  "Hours in Weekly View": "საათები ყოველკვირეული ხედით",
  "Hours in Daily View": "საათები ყოველდღიური ხედით",
  Start: "დასაწყისი",
  End: "Დასასრული",
  "At This Hour": "ამ საათში",
  Button: "ღილი",
  Buttons: "ღილაკები",
  Sunday: "კვირა",
  Monday: "ორშაბათი",
  Tuesday: "სამშაბათი",
  Wednesday: "ოთხშაბათი",
  Thursday: "ხუთშაბათი",
  Friday: "პარასკევი",
  Saturday: "შაბათი",
  "Default Date": "ნაგულისხმევი თარიღი",
  year: "წელი",
  month: "თვე",
  mo: "თო",
  days: "დღეები",
  ago: "წინათ",
  ahead: "წინ",
  Yesterday: "Გუშინ",
  Today: "დღეს",
  Tomorrow: "ხვალ",
  Custom: "ჩვეულება",
  "Set Daily Rows Limit": "ყოველდღიური რიგების ლიმიტი",
  "Set Proportions": "პროპორციები",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "საშუალებას მისცემს ვიზიტორს დაამატოთ ღონისძიება ადგილობრივ კალნედარებში: Google, Yahoo, Outlook, icalendar.",
  Container: "კონტეინერი",
  Background: "ფონი",
  "Container Background": "კონტეინერის ფონი",
  "Container Borders": "კონტეინერის საზღვრები",
  Calendar: "Კალენდარი",
  "Event Info Tooltip": "ღონისძიების შესახებ ინფორმაციის ინსტრუმენტები",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "როდესაც ადამიანები მოვლენებზე გადადიან, ისინი დაინახავენ ყველა ინფორმაციას ამის შესახებ ინსტრუმენტულ რეჟიმში.",
  "Event Info Window": "ღონისძიების ინფორმაციის ფანჯარა",
  "This is the full information window that opens when someone clicks on the event.":
    "ეს არის სრული ინფორმაციის ფანჯარა, რომელიც იხსნება, როდესაც ვინმე დააჭირეთ ღონისძიებას.",
  "Use Gradient": "გამოიყენეთ გრადიენტი",
  Vertical: "ვერტიკალური",
  Horizontal: "Ჰორიზონტალური",
  First: "Პირველი",
  Second: "მეორე",
  diagonal: "დიაგონალური",
  Radial: "რადიალური",
  "Select option": "აირჩიეთ ვარიანტი",
  Solid: "Მყარი",
  Dotted: "წერტილოვანი",
  Dashed: "გატეხილი",
  Double: "Ორმაგი",
  "Border Radius": "სასაზღვრო რადიუსი",
  Padding: "ბადება",
  "Date Header": "თარიღის სათაური",
  "Event Default Color": "ღონისძიების ნაგულისხმევი ფერი",
  "Days of Week": "Კვირის დღეები",
  "Days of Week Background": "კვირის ფონი",
  Date: "თარიღი",
  "Event Title": "ღონისძიების სათაური",
  "Highlight today": "დღეს მონიშნეთ",
  "Highlight Color": "ხაზს უსვამს ფერს",
  Hide: "დამალვა",
  "Calendar Border Color": "კალენდარული სასაზღვრო ფერი",
  "Calendar Border Width": "კალენდარული საზღვრის სიგანე",
  "Calendar Border Style": "კალენდარული სასაზღვრო სტილი",
  "Font Color": "Შრიფტის ფერი",
  "Event Background": "მოვლენის ფონი",
  "Card Date Color": "ბარათის თარიღის ფერი",
  "Title Font": "სათაურის შრიფტი",
  "Date Font": "თარიღის შრიფტი",
  "Description Font": "აღწერა შრიფტი",
  "Button Background": "ღილაკის ფონი",
  "Button Text": "ღილაკის ტექსტი",
  "Border Color": "სასაზღვრო ფერი",
  "Border Width": "საზღვრის სიგანე",
  "Border Type": "სასაზღვრო ტიპი",
  Title: "ტიტული",
  Description: "აღწერილობა",
  "Background Color": "Ფონის ფერი",
  Divider: "Გამყოფი",
  "Event Details Font": "ღონისძიების დეტალების შრიფტი",
  "Website Link Color": "ვებსაიტის ბმულის ფერი",
  "Developer Info": "დეველოპერის ინფორმაცია",
  "User Guide": "Მომხმარებლის სახელმძღვანელო",
  "Support e-mail": "ელ.ფოსტის მხარდაჭერა",
  "Our Website": "ჩვენი ვებ - გვერდი",
  "App Review": "აპლიკაციის მიმოხილვა",
  "Enjoying App? Leave us a review in the App Market.":
    "აპლიკაცია სიამოვნებით? დაგვიტოვეთ მიმოხილვა აპლიკაციების ბაზარზე.",
  "Review Us": "გადახედეთ ჩვენ",
  "Connect With Us": "დაუკავშირდით ჩვენთან",
  "What's your email?": "Რა არის შენი იმეილი?",
  "Invalid email address!": "არასწორი ელ.ფოსტის მისამართი!",
  Comments: "კომენტარები",
  "We'd love to hear from you. Send us a message.":
    "ჩვენ გვსურს მოვისმინოთ თქვენგან. გამოგვიგზავნეთ შეტყობინება.",
  "Message must be at least 5 characters long":
    "შეტყობინება უნდა იყოს მინიმუმ 5 სიმბოლო",
  Send: "გაგზავნა",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "თუ გსურთ მომხმარებელმა შეცვალოს კალენდარული ხედვები, ჩართეთ ეს ვარიანტი და შეარჩიეთ ისეთი შეხედულებები, რომელთა ჩვენებაც გსურთ.",
  Main: "მთავარი",
  Localize: "ლოკალიზაცია",
  Settings: "პარამეტრები",
  Layouts: "განლაგებები",
  Advanced: "Მოწინავე",
  Design: "ჩანაფიქრი",
  Support: "მხარდაჭერა",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "ყველა ადგილობრივი პარამეტრი არის (ავტომატურად) თქვენი ენიდან გამომდინარე. თუ თქვენი ენა სიაშია, არ არის საჭირო ამ განყოფილების მორგება.",
  "Date Format": "Თარიღის ფორმატი",
  "Time Format": "Დროის ფორმატი",
  "Text Direction": "ტექსტის მიმართულება",
  "Left to Right": "Მარცხნიდან მარჯვნივ",
  "Right to Left": "მარჯვნივ მარცხნივ",
  "Week Starts On": "კვირა იწყება",
  "Agenda Style": "დღის წესრიგის სტილი",
  Classic: "კლასიკური",
  Modern: "Თანამედროვე",
  "Agenda Header": "დღის წესრიგის სათაური",
  "Upcoming Events": "მომავალი ღონისძიებები",
  "Agenda Event Limit": "დღის წესრიგის ღონისძიების ლიმიტი",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "განაახლეთ ახლა და მიიღეთ კიდევ ბევრი ფუნქცია და ისიამოვნეთ თქვენი აპლიკაციით!",
  "Upgrade Now": "განაახლეთ ახლა",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "მასპინძლობის ღონისძიებები, რომლებიც გრძელდება მთელი დღის განმავლობაში? ეს საშუალებას გაძლევთ აჩვენოთ ისინი თქვენს კალენდარში.",
  "24 hours": "24 საათი",
  Sat: "იჯდა",
  Sun: "მზე",
  Mon: "ორშაბათი",
  Default: "ვალდებულების შეუსრულებლობა",
  "Select custom design style for your calendar.":
    "შეარჩიეთ საბაჟო დიზაინის სტილი თქვენი კალენდრისთვის.",
  Style: "სტილი",
  "Styles and Colors": "სტილები და ფერები",
  "Calendar Name": "კალენდარული სახელი",
  "Write your Calendar name here": "დაწერეთ თქვენი კალენდარული სახელი აქ",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "ეს არ ჩანს თქვენი მომხმარებლებისთვის. დააყენეთ სახელები, რომ განასხვავოთ თქვენი კალენდარი Boom კალენდარული სინქრონიზაციის ფუნქციის გამოყენებისას.",
  "General Info": "Ზოგადი ინფორმაცია",
  Venue: "ადგილი",
  Organizer: "ორგანიზატორი",
  Search: "ძებნა",
  "Add to": "Დაამატე",
  calendar: "კალენდარი",
  "Copy event URL": "დააკოპირეთ ღონისძიების URL",
  "Copied!": "კოპირებული!",
  "Add & Share": "დამატება და გაზიარება",
  Map: "რუკა",
  "Calendar view": "კალენდარული ხედი",
  "Add Event": "ღონისძიების დამატება",
  Uncategorised: "დაუსაბუთებელი",
  More: "მეტი",
  Less: "Ნაკლები",
  Register: "რეგისტრირება",
  Card: "ბარათი",
  Guests: "სტუმრები",
  unlimited: "შეუზღუდავი",
  "Show more": "მეტი აჩვენე",
  "Enable Search": "ჩართეთ ძებნა",
  "+ Add Event": " + დაამატეთ ღონისძიება",
  "Manage and Sync": "მართვა და სინქრონიზაცია",
  "Show event details as...": "აჩვენეთ ღონისძიების დეტალები, როგორც ...",
  Tooltip: "ინსტრუმენტები",
  Popup: "პიპუპ",
  None: "არაფერი",
  "Show Category": "აჩვენეთ კატეგორია",
  "Header Align": "სათაურის გასწორება",
  "Show Time": "Შოუს დრო",
  "Hours in Weekly/Daily View": "საათები ყოველკვირეულად/ყოველდღიური ხედით",
  "Share Events": "გააზიარეთ ღონისძიებები",
  Shadow: "Ჩრდილი",
  "Inner Padding": "შიდა ბალიშები",
  Text: "ტექსტი",
  "Active Button Border": "აქტიური ღილაკის საზღვარი",
  "Light Mode": "მსუბუქი რეჟიმი",
  "Event Text Color": "ღონისძიების ტექსტის ფერი",
  Dates: "თარიღები",
  Skeleton: "ჩონჩხი",
  "Skeleton Color": "ჩონჩხის ფერი",
  Width: "სიგანე",
  "Skeleton Style": "ჩონჩხის სტილი",
  Color: "ფერი",
  "Section Titles": "განყოფილების სათაურები",
  "Section Content": "განყოფილების შინაარსი",
  Header: "სათაური",
  Standard: "სტანდარტი",
  Retro: "რეტრო",
  Silver: "ვერცხლი",
  Night: "Ღამე",
  Dark: "Ბნელი",
  Aubergine: "ბადრიჯანი",
  "Map Header": "რუკის სათაური",
  "Show Title in mobile": "აჩვენეთ სათაური მობილურით",
  "Card View": "ბარათის ხედი",
  "Card background color": "ბარათის ფონის ფერი",
  "Title font": "სათაურის შრიფტი",
  "Desciption font": "დისტანციური შრიფტი",
  "Section font": "მონაკვეთის შრიფტი",
  "Section divider color": "განყოფილების გამყოფი ფერი",
  "Add event": "ღონისძიების დამატება",
  "All Day Event": "მთელი დღის ღონისძიება",
  Location: "ადგილმდებარეობა",
  "Choose a category": "აირჩიეთ კატეგორია",
  "Venue name": "ადგილის სახელი",
  "Venue phone": "ადგილის ტელეფონი",
  "Venue email": "ადგილის ელ.ფოსტა",
  "Venue website": "ადგილის ვებსაიტი",
  "Organizer name": "ორგანიზატორის სახელი",
  "Organizer phone": "ორგანიზატორის ტელეფონი",
  "Organizer email": "ორგანიზატორის ელ.ფოსტა",
  "Organizer website": "ორგანიზატორის ვებსაიტი",
  "Personal info": "Პირადი ინფორმაცია",
  "First name": "Სახელი",
  "Last name": "Გვარი",
  "Email Address": "Ელექტრონული მისამართი",
  "Additional Notes": "დამატებითი შენიშვნები",
  Back: "ზურგი",
  Save: "Გადარჩენა",
  Next: "შემდეგი",
  "Your event has been submitted": "თქვენი ღონისძიება წარდგენილია",
  "Event submittion has been failed": "ღონისძიების წარდგენა ვერ მოხერხდა",
  "e.g. Birthday Party": "მაგალითად. Დაბადების დღის წვეულება",
  "First Name": "Სახელი",
  "Last Name": "Გვარი",
  "Phone Number": "Ტელეფონის ნომერი",
  Address: "მისამართი",
  "Your comments": "Თქვენი კომენტარები",
  "How many guests?": "რამდენი სტუმარი?",
  "Anything else we need to know?": "კიდევ რამე უნდა ვიცოდეთ?",
  "Guests:": "სტუმრები:",
  Submit: "დამორჩილება",
  "Go to Calendar": "გადადით კალენდარში",
  "Registration completed successfully!": "რეგისტრაცია წარმატებით დასრულდა!",
  "Please check your registered email address":
    "გთხოვთ, შეამოწმოთ თქვენი რეგისტრირებული ელ.ფოსტის მისამართი",
  "Add to Calendar": "დაამატეთ კალენდარი",
  "Share this Event": "გააზიარე ეს ღონისძიება",
  "Sorry something went wrong": "Ბოდიში, რაღაც არ არის რიგზე",
  "Back to registration": "რეგისტრაციაზე დაბრუნება",
  "Date & Location": "თარიღი და ადგილმდებარეობა",
  "Date & Time": "თარიღი და დრო",
  home: "სახლი",
  "Header align": "სათაურის გასწორება",
  Footer: "კალი",
  "Categories Filter": "კატეგორიების ფილტრი",
  "Show only upcoming": "აჩვენეთ მხოლოდ მომავალი",
  "Card(s) in a row": "ზედიზედ ბარათი (ები)",
  "Space between cards": "სივრცე ბარათებს შორის",
  "Shown events limit": "ნაჩვენები მოვლენების ზღვარი",
  "Style 1": "სტილი 1",
  "Style 2": "სტილი 2",
  "Style 3": "სტილი 3",
  "Style 4": "სტილი 4",
  "Buttons & Links": "ღილაკები და ბმულები",
  "Button corner radius": "ღილაკის კუთხის რადიუსი",
  "Buttons font": "ღილაკების შრიფტი",
  "Buttons background": "ღილაკების ფონი",
  "Get notified by Email": "აცნობეთ ელ.ფოსტით",
  "Review events": "გადახედეთ ღონისძიებებს",
  "Click on date": "დააჭირეთ თარიღს",
  "Add Event button": "ღონისძიების ღილაკის დამატება",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Calendar Sync საშუალებას გაძლევთ ინტეგრირდეთ თქვენი მოვლენებისა და სესიების ინტეგრირება თქვენი ბუმის კალენდრით.",
  connect: "დაკავშირება",
  "Synchronized Calendars": "სინქრონიზებული კალენდარი",
  "Import events": "იმპორტის ღონისძიებები",
  Disconnect: "გათიშვა",
  "Choose calendar": "აირჩიეთ კალენდარი",
  "Monitor your Wix events through the sync feature":
    "დააკონტროლეთ თქვენი WIX მოვლენები სინქრონიზაციის მახასიათებლის საშუალებით",
  "Connect all your Boom calendars available on your website":
    "დააკავშირეთ ყველა თქვენი ბუმის კალენდარი, რომელიც ხელმისაწვდომია თქვენს ვებსაიტზე",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "დაგეგმეთ, შეუერთდით და მართეთ ზუმის შეხვედრები ჩვენი ბუმის კალენდრის საშუალებით.",
  "Monitor your Event Brite events through the Event Brite sync feature.":
    "აკონტროლეთ თქვენი ღონისძიების brite მოვლენები ღონისძიების Brite სინქრონიზაციის საშუალებით",
  Email: "ელ.წერილი",
  "Add-ons": "დანამატები",
  "Receive notification emails as soon as users add events to your calendar.":
    "მიიღეთ შეტყობინებების ელ.წერილი, როგორც კი მომხმარებლები დაამატებენ მოვლენებს თქვენს კალენდარში.",
  "Enable + button on the calendar header":
    "ჩართეთ + ღილაკი კალენდრის სათაურზე",
  "Accept or decline events added by customers before making them public.":
    "მომხმარებლების მიერ დამატებული მოვლენების მიღება ან შემცირება მათ, სანამ მათ გახდება.",
  "Switch Add Event": "შეცვალეთ ღონისძიება",
  "Enable your browser cookies to connect to your account.":
    "ჩართეთ თქვენი ბრაუზერის ქუქი -ფაილები თქვენს ანგარიშთან დასაკავშირებლად.",
  "Learn more": "Გაიგე მეტი",
  "Print Button": "ბეჭდვის ღილაკი",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "თქვენს მომხმარებლებს დაუშვან დაბეჭდონ თქვენი Boom Event Calendar ნებისმიერი თარიღის დიაპაზონში.",
  "Show Title on mobile": "აჩვენეთ სათაური მობილურით",
  "Show Skeleton on mobile": "აჩვენეთ ჩონჩხი მობილურით",
  "Start 7-day Business trial": "დაიწყეთ 7-დღიანი საქმიანი სასამართლო პროცესი",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "ისიამოვნეთ ყველა შეუზღუდავი მახასიათებლით, როგორიცაა ბილეთების გაყიდვა, რეგისტრაცია, ვიზიტორთა ღონისძიების დამატება.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "გთხოვთ გაითვალისწინოთ: საცდელი პერიოდის ბოლოს, თქვენ დაუბრუნდებით თქვენს არსებულ სააბონენტო გეგმას.",
  "Not Now": "Ახლა არა",
  "Start free trial": "დაიწყეთ უფასო საცდელი",
  "Congrats!": "Გილოცავ!",
  "Your 7-day Business trial has been successfully activated.":
    "თქვენი 7-დღიანი საქმიანი სასამართლო პროცესი წარმატებით გააქტიურდა.",
  Done: "შესრულებულია",
  "Title font color": "სათაური შრიფტის ფერი",
  "Desciption font color": "Desciption შრიფტის ფერი",
  "Section font color": "სექციის შრიფტის ფერი",
  "Card Header": "ბარათის სათაური",
  Category: "კატეგორია",
  "Display at the": "ჩვენება",
  top: "თავი",
  bottom: "ძირი",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "აჩვენეთ კატეგორიის ფილტრი ზედა ან კალენდრის ბოლოში. პარამეტრები ვრცელდება მხოლოდ დღის წესრიგისა და ბარათების ხედვებზე",
  "Processing your events": "თქვენი მოვლენების დამუშავება",
  "Search for events": "მოძებნეთ მოვლენები",
  "There are no events added": "არ არის დამატებული მოვლენები",
  "Location: To be determined": "ადგილმდებარეობა: განისაზღვროს",
  "No events for selected date": "არჩეული თარიღისთვის",
  Uncategorized: "უპატრონო",
  "Edit event": "რედაქტირება ღონისძიება",
  "Edit original event": "ორიგინალური ღონისძიების რედაქტირება",
  "Copy event": "დააკოპირეთ ღონისძიება",
  "Copy as new event": "დააკოპირეთ როგორც ახალი ღონისძიება",
  "Delete event": "წაშალეთ ღონისძიება",
  "Stop repeating on this date": "შეწყვიტეთ გამეორება ამ თარიღზე",
  "Exclude this date": "გამორიცხეთ ეს თარიღი",
  "Location is going to be announced": "ადგილმდებარეობის გამოცხადდება",
  "Fill your personal information": "შეავსეთ თქვენი პირადი ინფორმაცია",
  "Check Box": "გამშვები ყუთი",
  "Single Choice": "ერთი არჩევანი",
  Option: "არჩევა",
  "Share Event": "გაზიარება ღონისძიება",
  "Oops! Something went wrong": "უი! Რაღაც არასწორად წავიდა",
  "We are sorry this event has already taken place":
    "ჩვენ ვწუხვართ, რომ ეს ღონისძიება უკვე ჩატარდა",
  "Back to calendar": "კალენდარში დაბრუნება",
  "This field is required": "ეს ველი სავალდებულოა",
  Phone: "ტელეფონი",
  "Number field": "რიცხვის ველი",
  "Please provide a valid email": "გთხოვთ, მიაწოდოთ მოქმედი ელ.ფოსტა",
  "Select at least one option": "აირჩიეთ მინიმუმ ერთი ვარიანტი",
  "Choose tickets to see total value":
    "შეარჩიეთ ბილეთები, რომ ნახოთ საერთო ღირებულება",
  tickets: "ბილეთები",
  "Choose Tickets": "შეარჩიეთ ბილეთები",
  "Choose payment method": "აირჩიეთ გადახდის მეთოდი",
  Pay: "გადახდა",
  Total: "მთელი",
  Free: "უფასო",
  "Buy tickets": "Ბილეთების ყიდვა",
  "Sold Out": "Გაყიდულია",
  "Tickets are available": "ბილეთები ხელმისაწვდომია",
  "Sales End": "გაყიდვების დასასრული",
  "Availible from": "ხელმისაწვდომია",
  "Go to Orders": "გადადით შეკვეთებზე",
  "Go to Details": "გადადით დეტალებზე",
  "Group ticket": "ჯგუფური ბილეთი",
  Name: "სახელი",
  Price: "ფასი",
  "Order by": "შეკვეთა",
  "Order ID": "შეკვეთის ნომერი",
  Applied: "Გამოყენებითი",
  Fees: "მოსაკრებლები",
  "Enter promo code": "შეიყვანეთ პრომო კოდი",
  Apply: "გამოყენება",
  "Promo Code": "Პრომო კოდი",
  Cash: "ნაღდი ფული",
  "You can find your e-tickets attached to your email or download them":
    "თქვენ შეგიძლიათ იპოვოთ თქვენი ელექტრონული ბილეთები, რომლებიც თან ერთვის თქვენს ელ.ფოსტაზე ან გადმოწერეთ",
  here: "აქ",
  Time: "დრო",
  "Invalid promo code": "არასწორი პრომო კოდი",
  "Credit card": "Საკრედიტო ბარათი",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "თქვენ მალე მიიღებთ წარმატებული რეგისტრაციის დადასტურების შეტყობინებას თქვენს ელ.ფოსტის მისამართზე.",
  "You can also check your order details below.":
    "ასევე შეგიძლიათ შეამოწმოთ თქვენი შეკვეთის დეტალები ქვემოთ.",
  at: "-ზე",
  Buy: "ყიდვა",
  Donation: "საჩუქარი",
  "Enter price": "შეიყვანეთ ფასი",
  Choose: "არჩევა",
  Chosen: "Არჩეული",
  "Choose your plan": "აირჩიე შენი გეგმა",
  week: "კვირა",
  wk: "WK",
  "Choose plan cycle": "აირჩიეთ გეგმის ციკლი",
  months: "თვეები",
  years: "წლები",
  weeks: "კვირები",
  "Copy Event Url": "დააკოპირეთ ღონისძიების URL",
  "You can find your e-tickets attached to your email or print them":
    "თქვენ შეგიძლიათ იპოვოთ თქვენი ელექტრონული ბილეთები, რომლებიც თან ერთვის თქვენს ელ.ფოსტაზე ან დაბეჭდეთ",
  "Guest Info": "სტუმრის ინფორმაცია",
  "Ticket Info": "ბილეთის ინფორმაცია",
  "Ticket name": "ბილეთის სახელი",
  "Ticket price": "Ბილეთის ფასი",
  "Ticket ID": "ბილეთის პირადობის მოწმობა",
  "If you have any questions contact to organizer":
    "თუ თქვენ გაქვთ რაიმე შეკითხვები, დაუკავშირდით ორგანიზატორს",
  "As soon as event ends": "როგორც კი მოვლენა დასრულდება",
  "1 day after event ends": "ღონისძიების დასრულებიდან 1 დღის შემდეგ",
  "7 days after event ends": "ღონისძიების დასრულებიდან 7 დღის შემდეგ",
  "14 days after event ends": "ღონისძიების დასრულებიდან 14 დღის შემდეგ",
  "30 days after event ends": "ღონისძიების დასრულებიდან 30 დღის შემდეგ",
  Menu: "მენიუ",
  "No event for selected date": "არანაირი ღონისძიება არჩეული თარიღისთვის",
  view: "ხედი",
  List: "სია",
  Year: "წელი",
  Yearly: "ყოველწლიური",
  "Year view header": "წლის ხედვის სათაური",
  "Yearly Style": "წლიური სტილი",
  "There are no events": "არ არსებობს მოვლენები",
  Autotranslation: "ავტოტრანსლაცია",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "ჩართვის შემდეგ, თქვენი კალენდარული ვიჯეტი ითარგმნება ვებსაიტის ენაზე დაყრდნობით. *გაითვალისწინეთ, რომ სანამ კალენდარული სათაური და აღწერილობები შეიტანება ტექსტები, მათი თარგმნა შეუძლებელია.",
  "Note on mobile": "შენიშვნა მობილურზე",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "გამორთეთ ან შეცვალეთ კალენდრის მობილური ვერსიაზე 'No Events' - ის ტექსტი",
  Autodeletion: "ავტოტოლეონი",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "ვარიანტის ჩართვა, ავტომატურად ამოიღებს თქვენს წარსულ მოვლენებს კალენდარიდან.",
  "This does not apply to repeating events!":
    "ეს არ ეხება მოვლენების გამეორებას!",
  "Notify event creators about the guest":
    "აცნობეთ ღონისძიების შემქმნელებს სტუმრის შესახებ",
  "Send event creators notification emails as soon as guests register for their events":
    "გაგზავნეთ ღონისძიების შემქმნელების შეტყობინების ელ.წერილი, როგორც კი სტუმრები დარეგისტრირდებიან თავიანთი ღონისძიებებისთვის",
  "List View Type": "სიის ნახვის ტიპი",
  "Description font": "აღწერა შრიფტი",
  Connect: "დაკავშირება",
  "You have no events": "თქვენ არ გაქვთ მოვლენები",
  Synchronize: "სინქრონიზაცია",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Google Calendar Sync საშუალებას გაძლევთ ინტეგრირდეთ თქვენი მოვლენებისა და სესიების ინტეგრირება თქვენი ბუმის კალენდარით.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Outlook Calendar Sync საშუალებას გაძლევთ ინტეგრირდეთ თქვენი მოვლენებისა და სესიების ინტეგრირება თქვენი ბუმის კალენდრით.",
  "Your message has been sent successfully!":
    "თქვენი შეტყობინება წარმატებით გაიგზავნა!",
  "There are no synchronized calendars": "არ არსებობს სინქრონიზებული კალენდარი",
  "to view more than 7 events": "7 -ზე მეტი ღონისძიების სანახავად",
  "Mobile app": "მობილური აპლიკაცია",
  "Admin Account": "ადმინისტრატორის ანგარიში",
  Password: "პაროლი",
  "Second User": "მეორე მომხმარებელი",
  Edit: "რედაქტირება",
  "Guest limit": "სტუმრების ზღვარი",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "ყველა ადგილობრივი პარამეტრი არის (ავტომატურად) თქვენი ენიდან გამომდინარე. თუ თქვენი ენა სიაშია, ამ განყოფილების მორგება არ არის საჭირო.",
  available: "არსებული",
  next: "შემდეგი",
  Tickets: "ბილეთები",
  Quantity: "რაოდენობა",
  "Promo code": "Პრომო კოდი",
  "Select a payment method": "Აირჩიეთ გადახდის მეთოდი",
  Fee: "ჰონორარი",
  Book: "Წიგნი",
  "All the tickets have been sold out": "ყველა ბილეთი გაიყიდა",
  "Choose at least one ticket": "აირჩიეთ მინიმუმ ერთი ბილეთი",
  "First choose ticket": "პირველი აირჩიე ბილეთი",
  "Please fill out your personal information.":
    "გთხოვთ, შეავსოთ თქვენი პირადი ინფორმაცია.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "წარმატებული შეძენის მიზნით, გთხოვთ, შეარჩიოთ თქვენი გადახდის სასურველი მეთოდი და შეიყვანეთ პრომო კოდი ფასდაკლებული ბილეთებისთვის.",
  "Credit/Debit card": "საკრედიტო/სადებეტო ბარათი",
  "print here.": "დაბეჭდეთ აქ.",
  "QR code for all tickets": "QR კოდი ყველა ბილეთისთვის",
  Duration: "ხანგრძლივობა",
  "Full Name": "Სრული სახელი",
  "Ticket id": "ბილეთის პირადობის მოწმობა",
  "Group id": "ჯგუფის პირადობის მოწმობა",
  "Choose your ticket.": "შეარჩიეთ თქვენი ბილეთი.",
  "Fill out your personal information.": "შეავსეთ თქვენი პირადი ინფორმაცია.",
  "Add the payment details.": "დაამატეთ გადახდის დეტალები.",
  "To be determined": "Იყო მონდომებული",
  "You can find your e-tickets attached to the email or":
    "თქვენ შეგიძლიათ იპოვოთ თქვენი ელექტრონული ბილეთები, რომლებიც თან ერთვის ელ.ფოსტით ან",
  "print here": "დაბეჭდეთ აქ",
  "Full name": "Სრული სახელი",
  "Group ID": "ჯგუფის პირადობის მოწმობა",
  "to Book": "დაჯავშნა",
  "Unfortunately, your card has been declined":
    "სამწუხაროდ, თქვენი ბარათი უარი თქვეს",
  "Thank you for your purchase!": "გმადლობთ შეძენისთვის!",
  "Find your printable e-tickets attached to the confirmation email":
    "იპოვნეთ თქვენი დასაბეჭდი ელექტრონული ბილეთები, რომლებიც თან ერთვის დადასტურების ელ.წერილს",
  Confirm: "დადასტურება",

  "Add event": "ღონისძიების დამატება",
  Events: "Ივენთი",
  "Event details": "მოვლენის დეტალები",
  Registration: "რეგისტრაცია",
  "Guests list": "სტუმრების სია",
  Ticket: "Ბილეთი",
  "General Info": "Ზოგადი ინფორმაცია",
  "Customize the general settings of your event":
    "მოირგეთ თქვენი ღონისძიების ზოგადი პარამეტრები",
  "Event Title": "ღონისძიების სათაური",
  "e.g. Birthday Party": "მაგალითად. Დაბადების დღის წვეულება",
  "All Day Event": "მთელი დღის ღონისძიება",
  Cross: "ჯვარი",
  Timeline: "Ვადები",
  "Repeating event": "განმეორებითი მოვლენა",
  Location: "ადგილმდებარეობა",
  "Venue name": "ადგილის სახელი",
  Description: "აღწერილობა",
  Image: "გამოსახულება",
  Color: "ფერი",
  Category: "კატეგორია",
  "Add your events to color categories and let your users classify them easily":
    "დაამატეთ თქვენი მოვლენები ფერების კატეგორიებში და თქვენს მომხმარებლებს მარტივად მიეცით კლასიფიკაცია",
  "Category name": "კატეგორიის სახელი",
  "e.g. Birthdays": "მაგალითად. დაბადების დღეები",
  Venue: "ადგილი",
  "Where the event takes place": "სადაც ხდება ღონისძიება",
  "Venue name": "ადგილის სახელი",
  "Venue phone": "ადგილის ტელეფონი",
  "Venue email": "ადგილის ელ.ფოსტა",
  "Venue website": "ადგილის ვებსაიტი",
  Organizer: "ორგანიზატორი",
  "Person who makes the event": "ადამიანი, ვინც აკეთებს ღონისძიებას",
  "Organizer name": "ორგანიზატორის სახელი",
  "Organizer phone": "ორგანიზატორის ტელეფონი",
  "Organizer email": "ორგანიზატორის ელ.ფოსტა",
  "Organizer website": "ორგანიზატორის ვებსაიტი",
  Save: "Გადარჩენა",
  Cancel: "გაუქმება",
  Import: "იმპორტი",
  Past: "წარსული",
  All: "ყველა",
  Upcoming: "მომავალი",
  Uncategorised: "დაუსაბუთებელი",
  "Date Ascending": "თარიღი ასვლა",
  "Date Descending": "თარიღი დაღმავალი",
  "Title by A-Z": "სათაური ა-ზ",
  "Title by Z-A": "სათაური Z-A- ს მიერ",
  "There are no events for this period":
    "ამ პერიოდისთვის მოვლენები არ არსებობს",

  "Auto-Convert Date & Time": "ავტო-ჩაკეტვის თარიღი და დრო",
  TimeZone: "Დროის სარტყელი",
  Autodeletion: "ავტოტოლეონი",
  "Layout Settings": "განლაგების პარამეტრები",
  "Yeatly view": "Yeatly ხედი",
  "Monthly view header": "ყოველთვიური ხედვის სათაური",
  "Weekly/Daily view header": "ყოველკვირეული/ყოველდღიური ხედვის სათაური",
  Acendings: "ოსტატები",
  Descending: "Დაღმავალი",
  Standart: "სტენდ -დღე",
  Silver: "ვერცხლი",
  Retro: "რეტრო",
  Dark: "Ბნელი",
  Night: "Ღამე",
  Aubergine: "ბადრიჯანი",
  "List view header": "სიის ხედვის სათაური",
  "Side by Side View": "გვერდით ხედი",
  "Customize Proportions": "პროპორციების მორგება",
  "Card Margins": "ბარათის მინდვრები",
  "Image opacity (%)": "გამოსახულების გამჭრიახობა (%)",
  "Side by Side Header": "გვერდით სათაურის გვერდით",
  "Text Align": "ტექსტის გასწორება",
  "Timeline View": "ვადების ხედი",
  "Title font color": "სათაური შრიფტის ფერი",
  "Desciption font color": "Desciption შრიფტის ფერი",
  "Line color": "ხაზის ფერი",
  "Date Font color": "თარიღი შრიფტის ფერი",
  "Daily events background": "ყოველდღიური მოვლენების ფონი",
  Alignment: "გასწორება",
  Vertical: "ვერტიკალური",
  Horizontal: "Ჰორიზონტალური",
  "Vertical Alignment": "ვერტიკალური გასწორება",
  Right: "სწორი",
  Center: "ცენტრი",
  "Horizontal Alignment": "ჰორიზონტალური გასწორება",
  Top: "თავი",
  Center: "ცენტრი",
  Bottom: "ძირი",
  "Dates Circle Design": "თარიღების წრის დიზაინი",
  "Next To The Circle": "წრის გვერდით",
  "In The Circle": "წრეში",
  "Timeline Header": "ვადების სათაური",
  Timeline: "Ვადები",
  "Show only upcoming": "აჩვენეთ მხოლოდ მომავალი",
  "Order by": "შეკვეთა",
  "Timeline Event Limit": "ვადების ღონისძიების ლიმიტი",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "საშუალებას მისცემს ვიზიტორს დაამატოთ ღონისძიება ადგილობრივ კალნედარებში: Google, Yahoo, Outlook, icalendar.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "საშუალებას მისცემს ვიზიტორს გაუზიაროთ თქვენი ღონისძიება Facebook- ზე, LinkedIn- ში, Twitter- ზე და ა.შ.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "დაამატეთ ძიების ვარიანტი თქვენს კალენდარში, რათა ხალხს მოიძიოთ თქვენი მოვლენები სათაურით, ადგილით და ა.შ.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "თქვენს მომხმარებლებს დაუშვან დაბეჭდონ თქვენი Boom Event Calendar ნებისმიერი თარიღის დიაპაზონში.",
  "Click to apply a theme to Calendar": "დააჭირეთ კალენდარში თემის გამოყენებას",
  "Date container color": "თარიღი კონტეინერის ფერი",
  "Daily events background": "ყოველდღიური მოვლენების ფონი",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "გამოიყენეთ დანამატები თქვენს კალენდრებზე მოწინავე მახასიათებლების დასაყენებლად, რაც მათ უფრო ფუნქციონირებს!",
  "Open Add-ons Store": "გახსენით დანამატების მაღაზია",
  Monday: "ორშაბათი",
  Tuesday: "სამშაბათი",
  Wednesday: "ოთხშაბათი",
  Thursday: "ხუთშაბათი",
  Friday: "პარასკევი",
  Saturday: "შაბათი",
  Sunday: "კვირა",
  Ascending: "აწევა",
  "Yearly view": "კვირა",
  "Show event time next to title": "აჩვენეთ ღონისძიების დრო სათაურის გვერდით",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "შეცვალეთ ღონისძიების თარიღი და დრო მომხმარებლის ადგილობრივ დროზე, მათი დროის ზონის საფუძველზე.",
  "Display the time zone alongside the event date.":
    "აჩვენეთ დროის ზონა ღონისძიების თარიღთან ერთად.",
  "Show event time next to title": "აჩვენეთ ღონისძიების დრო სათაურის გვერდით",
  "Time Zone": "Დროის სარტყელი",
  "Upload Image": "Სურათის ატვირთვა",
  "Choose a Category": "აირჩიეთ კატეგორია",
  "Color you have chosen will not be shown as you choose category":
    "თქვენ მიერ არჩეული ფერი არ იქნება ნაჩვენები, როგორც თქვენ აირჩევთ კატეგორიას",
  Website: "ვებსაიტი",
  Next: "შემდეგი",
  Save: "Გადარჩენა",
  "Last Name": "Გვარი",
  "Personal Info": "Პირადი ინფორმაცია",
  Back: "ზურგი",
  "This field is required": "ეს ველი სავალდებულოა",
  "Your event has been submitted": "თქვენი ღონისძიება წარდგენილია",
  "Enter a location": "შეიყვანეთ ადგილმდებარეობა",
  "Display the time zone alongside the event date.":
    "აჩვენეთ დროის ზონა ღონისძიების თარიღთან ერთად.",
  Home: "სახლი",
  "Side By Side Event Limit": "გვერდით ღონისძიების ლიმიტი",
  "Mobille App": "Mobille App",
  category: "კატეგორია",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "თვალყური ადევნეთ თქვენს განრიგს მარტივად თქვენი Facebook მოვლენების თქვენს კალენდარში იმპორტით.",
  "Synchronized Pages": "სინქრონიზებული გვერდები",
  "There are no synchronized pages": "არ არის სინქრონიზებული გვერდები",
  "Choose page": "აირჩიეთ გვერდი",
  "You have no events": "თქვენ არ გაქვთ მოვლენები",
};
export default ka;
