let ko = {
  Categories: "카테고리",
  "Share this event": "이 이벤트를 공유",
  Language: "언어",
  "Show Time Zone": "시간대 표시",
  "Custom Local Settings": "맞춤 지역 설정",
  "Add and showcase events on your site using a beautiful calendar.":
    "아름다운 캘린더를 사용하여 사이트의 이벤트를 추가하고 보여줍니다 . ",
  "Week Days": "주중 일",
  "Manage Events": "이벤트 관리",
  General: "일반",
  "Layout Picker": "레이아웃 선택 도구",
  Month: "달",
  Monthly: "월간 간행물",
  Week: "주",
  Weekly: "주간",
  Day: "일",
  Daily: "매일",
  Agenda: "비망록",
  "Navigation Buttons": "탐색 버튼",
  "Week numbers": "주 번호",
  "Include Weekends": "주말 포함",
  "All-day": "하루 종일",
  "All Day": "하루 종일",
  Label: "상표",
  "Fit to Height": "높이에 맞추기",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "앱 비율을 설정하려면이 옵션을 비활성화하고 편집기에서 캘린더의 크기를 조정하십시오.",
  "Default Layout": "기본 레이아웃",
  "Monthly view": "월간보기",
  "Weekly and Daily view": "주간 및 일일보기",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "한 번에 같은 주 수 ( 6)를 표시함으로써 방문자에게보다 일관된 경험을 제공 할 수 있습니다 .",
  "Fixed Weekly Layout": "고정 주간 레이아웃",
  back: " 뒤로 ",
  Row: "열",
  "Hours in Weekly View": "주간보기 시간",
  "Hours in Daily View": "일일보기 시간",
  Start: "스타트",
  End: "종료",
  "At This Hour": "이 시간에",
  Button: "단추",
  Buttons: "버튼",
  Sunday: "일요일",
  Monday: "월요일",
  Tuesday: "화요일",
  Wednesday: "수요일",
  Thursday: " 목요일 ",
  Friday: "금요일",
  Saturday: "토요일",
  "Default Date": "기본 날짜",
  year: " 년 ",
  month: " 월 ",
  mo: " 월 ",
  days: " 일 ",
  ago: " 이전 ",
  ahead: " 앞으로 ",
  Yesterday: "어제",
  Today: "오늘",
  Tomorrow: "내일",
  Custom: "관습",
  "Set Daily Rows Limit": "일일 행 제한 설정",
  "Set Proportions": "비율 설정",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "방문자가 지역 Calnedars : Google, Yahoo, Outlook, ICalendar에 이벤트를 추가 할 수 있습니다.",
  Container: "컨테이너",
  Background: "배경",
  "Container Background": "컨테이너 배경",
  "Container Borders": "컨테이너 테두리",
  Calendar: "달력",
  "Event Info Tooltip": "이벤트 정보 툴팁",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "사람들이 이벤트에 마우스를 가져 가면 툴팁에 모든 정보가 표시됩니다. ",
  "Event Info Window": "이벤트 정보 창",
  "This is the full information window that opens when someone clicks on the event.":
    "이것은 누군가가 이벤트를 클릭하면 열리는 전체 정보 창입니다. ",
  "Use Gradient": "그라디언트 사용",
  Vertical: "수직선",
  Horizontal: "수평 적",
  First: "먼저",
  Second: "둘째",
  diagonal: " 대각선 ",
  Radial: "방사형",
  "Select option": "선택 옵션",
  Solid: "고체",
  Dotted: "점이 찍힌",
  Dashed: "Dashed",
  Double: "더블",
  "Border Radius": "테두리 반지름",
  Padding: "심",
  "Date Header": "날짜 헤더",
  "Event Default Color": "이벤트 기본 색상",
  "Days of Week": "요일",
  "Days of Week Background": "요일 배경",
  Date: "데이트",
  "Event Title": "이벤트 제목",
  "Highlight today": "오늘 하이라이트",
  "Highlight Color": "하이라이트 색상",
  Hide: "숨는 장소",
  "Calendar Border Color": "일정 테두리 색",
  "Calendar Border Width": "일정 테두리 너비",
  "Calendar Border Style": "일정 테두리 스타일",
  "Font Color": "글꼴 색상",
  "Event Background": "이벤트 배경",
  "Card Date Color": "카드 날짜 색상",
  "Title Font": "제목 글꼴",
  "Date Font": "날짜 글꼴",
  "Description Font": "설명 글꼴",
  "Button Background": "버튼 배경",
  "Button Text": "버튼 텍스트",
  "Border Color": "테두리 색상",
  "Border Width": "테두리 너비",
  "Border Type": "테두리 유형",
  Title: "표제",
  Description: "기술",
  "Background Color": "배경색",
  Divider: "분할기",
  "Event Details Font": "이벤트 세부 정보 글꼴",
  "Website Link Color": "웹 사이트 링크 색상",
  "Developer Info": "개발자 정보",
  "User Guide": "사용자 설명서",
  "Support e-mail": "지원 이메일",
  "Our Website": "우리의 웹 사이트",
  "App Review": "앱 검토",
  "Enjoying App? Leave us a review in the App Market.":
    "앱 즐기기? App Market에서 리뷰를 남겨주세요 . ",
  "Review Us": "검토하기",
  "Connect With Us": "우리와 접촉",
  "What's your email?": "귀하의 이메일은 무엇입니까? ",
  "Invalid email address!": "잘못된 이메일 주소입니다! ",
  Comments: "코멘트",
  "We'd love to hear from you. Send us a message.":
    "우리는 당신의 의견을 듣고 싶습니다. 우리에게 메시지를 보내십시오. ",
  "Message must be at least 5 characters long":
    "메시지 길이는 5 자 이상이어야합니다.",
  Send: "보내다",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "사용자가 캘린더보기간에 전환 할 수있게하려면이 옵션을 활성화하고 표시 할보기를 선택하십시오. ",
  Main: "본관",
  Localize: "지역화",
  Settings: "설정",
  Layouts: "레이아웃",
  Advanced: "많은",
  Design: "디자인",
  Support: "지원하다",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "모든 로컬 설정은 사용자의 언어에 따라 (자동으로) 설정됩니다. 언어가 목록에 있으면이 섹션을 사용자 정의 할 필요가 없습니다.",
  "Date Format": "날짜 형식",
  "Time Format": "시간 형식",
  "Text Direction": "텍스트 방향",
  "Left to Right": "왼쪽에서 오른쪽으로",
  "Right to Left": "오른쪽에서 왼쪽으로",
  "Week Starts On": "주 시작",
  "Agenda Style": "아젠다 스타일",
  Classic: "권위 있는",
  Modern: "현대",
  "Agenda Header": "아젠다 헤더",
  "Upcoming Events": "다가오는 이벤트",
  "Agenda Event Limit": "의제 이벤트 제한",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "지금 업그레이드하고 더 많은 기능을 사용하고 APP을 완전히 즐기십시오!",
  "Upgrade Now": "지금 업그레이드",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "하루 종일 지속되는 행사를 주최합니까? 캘린더에 표시 할 수 있습니다.",
  "24 hours": "24 시간",
  Sat: "토요일",
  Sun: "일요일",
  Mon: "월요일",
  Default: "기본",
  "Select custom design style for your calendar.":
    "캘린더에 대한 사용자 정의 디자인 스타일을 선택하십시오.",
  Style: "스타일",
  "Styles and Colors": "스타일과 색상",
  "Calendar Name": "캘린더 이름",
  "Write your Calendar name here": "여기에 캘린더 이름을 작성하십시오",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "사용자에게는 보이지 않습니다. 붐 캘린더 동기화 기능을 사용할 때 캘린더를 구별 할 수 있도록 이름을 설정하십시오.",
  "General Info": "일반 정보",
  Venue: "장소",
  Organizer: "조직자",
  Search: "검색",
  "Add to": "다음에 추가",
  calendar: "달력",
  "Copy event URL": "이벤트 URL 복사",
  "Copied!": "복사했습니다!",
  "Add & Share": "추가 및 공유",
  Map: "지도",
  "Calendar view": "달력보기",
  "Add Event": "이벤트 추가",
  Uncategorised: "분류되지 않음",
  More: "더",
  Less: "적게",
  Register: "레지스터",
  Card: "카드",
  Guests: "손님",
  unlimited: "제한 없는",
  "Show more": "자세히보기",
  "Enable Search": "검색 사용",
  "+ Add Event": "+ 이벤트 추가",
  "Manage and Sync": "관리 및 동기화",
  "Show event details as...": "일정 세부 정보 표시 ...",
  Tooltip: "툴팁",
  Popup: "정보 상자",
  None: "없음",
  "Show Category": "카테고리 표시",
  "Header Align": "헤더 정렬",
  "Show Time": "쇼 시간",
  "Hours in Weekly/Daily View": "주간 / 일일 시간",
  "Share Events": "이벤트 공유",
  Shadow: "그림자",
  "Inner Padding": "내부 패딩",
  Text: "본문",
  "Active Button Border": "활성 버튼 테두리",
  "Light Mode": "라이트 모드",
  "Event Text Color": "이벤트 텍스트 색상",
  Dates: "날짜",
  Skeleton: "해골",
  "Skeleton Color": "스켈레톤 컬러",
  Width: "폭",
  "Skeleton Style": "스켈레톤 스타일",
  Color: "색깔",
  "Section Titles": "섹션 제목",
  "Section Content": "섹션 내용",
  Header: "헤더",
  Standard: "표준",
  Retro: "레트로",
  Silver: "은",
  Night: "밤",
  Dark: "어두운",
  Aubergine: "가지",
  "Map Header": "지도 헤더",
  "Show Title in mobile": "모바일에서 제목 표시",
  "Card View": "카드보기",
  "Card background color": "카드 배경색",
  "Title font": "제목 글꼴",
  "Desciption font": "설명 글꼴",
  "Section font": "글꼴 섹션",
  "Section divider color": "섹션 구분선 색상",
  "Add event": "이벤트 추가",
  "All Day Event": "하루 종일 이벤트",
  Location: "위치",
  "Choose a category": "카테고리 선택",
  "Venue name": "장소 이름",
  "Venue phone": "회장 전화",
  "Venue email": "장소 이메일",
  "Venue website": "장소 웹 사이트",
  "Organizer name": "주최자 이름",
  "Organizer phone": "주최자 전화",
  "Organizer email": "주최자 이메일",
  "Organizer website": "주최자 웹 사이트",
  "Personal info": "개인적인 정보",
  "First name": "이름",
  "Last name": "성",
  "Email Address": "이메일 주소",
  "Additional Notes": "추가 참고 사항",
  Back: "뒤",
  Save: "저장",
  Next: "다음",
  "Your event has been submitted": "이벤트가 제출되었습니다",
  "Event submittion has been failed": "이벤트 제출 실패",
  "e.g. Birthday Party": "예 : 생일 파티",
  "First Name": "이름",
  "Last Name": "성",
  "Phone Number": "전화 번호",
  Address: "주소",
  "Your comments": "귀하의 의견",
  "How many guests?": "손님은 몇 명입니까?",
  "Anything else we need to know?": "우리가 알아야 할 다른 것이 있습니까?",
  "Guests:": "손님 :",
  Submit: "제출",
  "Go to Calendar": "캘린더로 이동",
  "Registration completed successfully!": "등록이 성공적으로 완료되었습니다!",
  "Please check your registered email address":
    "등록 된 이메일 주소를 확인하세요",
  "Add to Calendar": "캘린더에 추가",
  "Share this Event": "이 이벤트를 공유",
  "Sorry something went wrong": "죄송합니다. 문제가 발생했습니다.",
  "Back to registration": "등록으로 돌아 가기",
  "Date & Location": "날짜 및 위치",
  "Date & Time": "날짜 시간",
  home: "집",
  "Header align": "헤더 정렬",
  Footer: "보행인",
  "Categories Filter": "카테고리 필터",
  "Show only upcoming": "예정된 항목 만 표시",
  "Card(s) in a row": "연속 된 카드",
  "Space between cards": "카드 사이의 공간",
  "Shown events limit": "표시된 이벤트 제한",
  "Style 1": "스타일 1",
  "Style 2": "스타일 2",
  "Style 3": "스타일 3",
  "Style 4": "스타일 4",
  "Buttons & Links": "버튼 및 링크",
  "Button corner radius": "버튼 모서리 반경",
  "Buttons font": "버튼 글꼴",
  "Buttons background": "버튼 배경",
  "Get notified by Email": "이메일로 통보 받으십시오",
  "Review events": "이벤트 검토",
  "Click on date": "날짜를 클릭",
  "Add Event button": "이벤트 추가 버튼",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "캘린더 동기화를 통해 이벤트 및 세션을 Boom 캘린더와 통합 할 수 있습니다.",
  connect: "잇다",
  "Synchronized Calendars": "동기화 된 캘린더",
  "Import events": "이벤트 가져 오기",
  Disconnect: "연결 해제",
  "Choose calendar": "달력 선택",
  "Monitor your Wix events through the sync feature":
    "동기화 기능을 통해 Wix 이벤트 모니터링",
  "Connect all your Boom calendars available on your website":
    "웹 사이트에서 사용 가능한 모든 Boom 캘린더 연결",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Boom 캘린더를 통해 Zoom 회의를 예약, 참여 및 관리하세요.",
  "Monitor your Event Brite events through the Event Brite sync feature.":
    "Event Brite 동기화 기능을 통해 Event Brite 이벤트 모니터링",
  Email: "이메일",
  "Add-ons": "부가 기능",
  "Receive notification emails as soon as users add events to your calendar.":
    "사용자가 이벤트를 캘린더에 추가하자마자 알림 전자 메일을받습니다.",
  "Enable + button on the calendar header": "캘린더 헤더의 + 버튼을 사용합니다",
  "Accept or decline events added by customers before making them public.":
    "고객이 추가 한 이벤트를 수락하거나 거절합니다.",
  "Switch Add Event": "스위치 추가 이벤트",
  "Enable your browser cookies to connect to your account.":
    "브라우저 쿠키를 사용하여 계정에 연결할 수 있습니다.",
  "Learn more": "더 알아보기",
  "Print Button": "Drukāšanas poga",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "사용자가 모든 날짜 범위에서 붐 이벤트 캘린더를 인쇄하도록 허용하십시오.",
  "Show Title on mobile": "모바일에 제목을 보여줍니다",
  "Show Skeleton on mobile": "모바일에서 스켈레톤을 보여줍니다",
  "Start 7-day Business trial": "7 일간 비즈니스 재판을 시작하십시오",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "판매 티켓, 등록, 방문자 이벤트 애드온과 같은 모든 무제한 기능을 즐기십시오.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "참고 : 평가판 기간이 끝나면 기존 가입 계획으로 돌아갑니다.",
  "Not Now": "지금은 아닙니다",
  "Start free trial": "무료 평가판을 시작하십시오",
  "Congrats!": "축하 해요!",
  "Your 7-day Business trial has been successfully activated.":
    "7 일 비즈니스 재판이 성공적으로 활성화되었습니다.",
  Done: "완료",
  "Title font color": "제목 글꼴 색상",
  "Desciption font color": "설명 글꼴 색상",
  "Section font color": "섹션 글꼴 색상",
  "Card Header": "카드 헤더",
  Category: "범주",
  "Display at the": "그대로 표시",
  top: "맨 위",
  bottom: "맨 아래",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "카테고리 필터를 맨 위 또는 캘린더 하단에 표시합니다.설정은 의제 및 카드 뷰에만 적용됩니다",
  "Processing your events": "이벤트 처리",
  "Search for events": "이벤트 검색",
  "There are no events added": "추가 된 이벤트가 없습니다",
  "Location: To be determined": "위치 : 결정됩니다",
  "No events for selected date": "선택한 날짜에 대한 이벤트가 없습니다",
  Uncategorized: "분류되지 않은",
  "Edit event": "이벤트 편집",
  "Edit original event": "원본 이벤트 편집",
  "Copy event": "사본 이벤트",
  "Copy as new event": "새 이벤트로 복사하십시오",
  "Delete event": "이벤트 삭제",
  "Stop repeating on this date": "이 날짜에 반복하지 마십시오",
  "Exclude this date": "이 날짜를 제외하십시오",
  "Location is going to be announced": "위치가 발표 될 예정입니다",
  "Fill your personal information": "개인 정보를 작성하십시오",
  "Check Box": "확인란",
  "Single Choice": "단일 선택",
  Option: "옵션",
  "Share Event": "공유 이벤트",
  "Oops! Something went wrong": "죄송합니다!뭔가 잘못되었습니다",
  "We are sorry this event has already taken place":
    "이 이벤트가 이미 발생한 죄송합니다",
  "Back to calendar": "캘린더로 돌아 가기",
  "This field is required": "이 필드가 필요합니다",
  Phone: "핸드폰",
  "Number field": "번호 필드",
  "Please provide a valid email": "유효한 이메일을 제공하십시오",
  "Select at least one option": "하나 이상의 옵션을 선택하십시오",
  "Choose tickets to see total value":
    "총 가치를 확인하려면 티켓을 선택하십시오",
  tickets: "티켓",
  "Choose Tickets": "티켓을 선택하십시오",
  "Choose payment method": "결제 방법 선택",
  Pay: "지불",
  Total: "합계",
  Free: "비어 있는",
  "Buy tickets": "표를 사다",
  "Sold Out": "매진",
  "Tickets are available": "티켓을 사용할 수 있습니다",
  "Sales End": "판매 종료",
  "Availible from": "사용 가능",
  "Go to Orders": "주문으로 이동하십시오",
  "Go to Details": "세부 사항으로 이동하십시오",
  "Group ticket": "그룹 티켓",
  Name: "이름",
  Price: "가격",
  "Order by": "주문",
  "Order ID": "주문 아이디",
  Applied: "적용된",
  Fees: "수수료",
  "Enter promo code": "프로모션 코드 입력하기",
  Apply: "대다",
  "Promo Code": "프로모션 코드",
  Cash: "현금",
  "You can find your e-tickets attached to your email or download them":
    "이메일에 첨부 된 전자 티켓을 찾거나 다운로드 할 수 있습니다.",
  here: "여기",
  Time: "시간",
  "Invalid promo code": "잘못된 프로모션 코드",
  "Credit card": "신용 카드",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "곧 이메일 주소에 성공적인 등록의 확인 메시지를 받게됩니다.",
  "You can also check your order details below.":
    "아래에서 주문 세부 정보를 확인할 수도 있습니다.",
  at: "~에",
  Buy: "구입하다",
  Donation: "기부",
  "Enter price": "기업",
  Choose: "선택하다",
  Chosen: "선택",
  "Choose your plan": "계획을 선택하십시오",
  week: "주",
  wk: "주",
  "Choose plan cycle": "계획주기를 선택하십시오",
  months: "달",
  years: "연령",
  weeks: "주",
  "Copy Event Url": "이벤트 URL 복사",
  "You can find your e-tickets attached to your email or print them":
    "이메일에 첨부 된 전자 티켓을 찾거나 인쇄 할 수 있습니다.",
  "Guest Info": "게스트 정보",
  "Ticket Info": "티켓 정보",
  "Ticket name": "티켓 이름",
  "Ticket price": "티켓 가격",
  "Ticket ID": "티켓 ID",
  "If you have any questions contact to organizer":
    "궁금한 점이 있으면 주최자에게 연락하십시오",
  "As soon as event ends": "이벤트가 끝나 자마자",
  "1 day after event ends": "이벤트가 끝나고 1 일 후에",
  "7 days after event ends": "이벤트가 끝나고 7 일 후",
  "14 days after event ends": "이벤트가 끝나고 14 일 후",
  "30 days after event ends": "이벤트가 끝나고 30 일 후",
  Menu: "메뉴",
  "No event for selected date": "선택된 날짜에 대한 이벤트가 없습니다",
  view: "보다",
  List: "목록",
  Year: "년도",
  Yearly: "매년",
  "Year view header": "연도 뷰 헤더",
  "There are no events": "이벤트가 없습니다",
  Autotranslation: "오토 론",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "일단 활성화되면 캘린더 위젯이 웹 사이트의 언어를 기준으로 번역됩니다.* 캘린더 타이틀 및 설명이 입력 된 텍스트의 경우 번역 할 수없는 텍스트입니다.",
  "Note on mobile": "모바일에 참고하십시오",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "캘린더의 모바일 버전에서 '이벤트 없음'막대의 텍스트를 끄거나 변경하십시오.",
  Autodeletion: "자가 재산",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "옵션을 활성화하면 캘린더에서 과거 이벤트를 자동으로 제거합니다.",
  "This does not apply to repeating events!":
    "이것은 반복적 인 이벤트에는 적용되지 않습니다!",
  "Notify event creators about the guest": "게스트에 대해 사용자에게 알림",
  "Send event creators notification emails as soon as guests register for their events":
    "게스트가 이벤트에 등록하는 즉시 이벤트 크리에이터 알림 이메일 보내기",
  "List View Type": "목록보기 유형",
  "Yearly Style": "매년 스타일",
  "Description font": "설명 글꼴",
  Connect: "잇다",
  "You have no events": "Jums nav notikumu",
  Synchronize: "Sinhronizēt",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Met Google Calendar Sync kunt u uw evenementen en sessies integreren met uw giekkalender.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Outlook kalendāra sinhronizācija ļauj integrēt savus notikumus un sesijas ar jūsu uzplaukuma kalendāru.",
  "Your message has been sent successfully!":
    "Jūsu ziņojums ir veiksmīgi nosūtīts!",
  "There are no synchronized calendars": "동기화 된 캘린더가 없습니다.",
  "to view more than 7 events": "Om meer dan 7 evenementen te bekijken",
  "Mobile app": "모바일 앱",
  "Admin Account": "관리자 계정",
  Password: "암호",
  "Second User": "Tweede gebruiker",
  Edit: "Bewerk",
  "Guest limit": "게스트 리미트",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "모든 로컬 설정은 언어를 기반으로 자동 설정입니다.언어가 목록에있는 경우이 섹션을 사용자 정의 할 필요가 없습니다.",
  available: "유효한",
  next: "다음",
  Tickets: "티켓",
  Quantity: "수량",
  "Promo code": "프로모션 코드",
  "Select a payment method": "결제 방법을 선택",
  Fee: "회비",
  Book: "도서",
  "All the tickets have been sold out": "모든 티켓은 매진되었습니다",
  "Choose at least one ticket": "적어도 하나의 티켓을 선택하십시오",
  "First choose ticket": "먼저 항공권을 선택하십시오",
  "Please fill out your personal information.":
    "귀하의 개인 정보를 작성하십시오.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "성공적인 구매를하기 위해 원하는 지불 방법을 선택하고 할인 된 티켓에 대한 프로모션 코드를 입력하십시오.",
  "Credit/Debit card": "신용 / 직불 카드",
  "print here.": "여기에 인쇄하십시오.",
  "QR code for all tickets": "모든 티켓에 대한 QR 코드",
  Duration: "지속",
  "Full Name": "성명",
  "Ticket id": "티켓 ID.",
  "Group id": "그룹 ID",
  "Choose your ticket.": "티켓을 선택하십시오.",
  "Fill out your personal information.": "귀하의 개인 정보를 작성하십시오.",
  "Add the payment details.": "지불 세부 사항을 추가하십시오.",
  "To be determined": "결정된다",
  "You can find your e-tickets attached to the email or":
    "전자 메일에 첨부 된 전자 티켓을 찾을 수 있습니다.",
  "print here": "여기에 인쇄하십시오",
  "Full name": "성명",
  "Group ID": "그룹 ID",
  "to Book": "예약하기",
  "Unfortunately, your card has been declined":
    "불행히도 카드가 거부되었습니다",
  "Thank you for your purchase!": "구입 주셔서 감사합니다!",
  "Find your printable e-tickets attached to the confirmation email":
    "확인 이메일에 첨부 된 인쇄 가능한 전자 티켓을 찾으십시오",
  Confirm: "확인하다",

  "Add event": "이벤트 추가",
  Events: "이벤트",
  "Event details": "이벤트 세부 사항",
  Registration: "등록",
  "Guests list": "손님 목록",
  Ticket: "티켓",
  "General Info": "일반 정보",
  "Customize the general settings of your event":
    "이벤트의 일반 설정을 사용자 정의하십시오",
  "Event Title": "이벤트 제목",
  "e.g. Birthday Party": "예를 들어 생일 파티",
  "All Day Event": "하루 종일 이벤트",
  Cross: "십자가",
  Timeline: "타임 라인",
  "Repeating event": "반복 이벤트",
  Location: "위치",
  "Venue name": "장소 이름",
  Description: "설명",
  Image: "영상",
  Color: "색상",
  Category: "범주",
  "Add your events to color categories and let your users classify them easily":
    "이벤트를 색상 카테고리에 추가하고 사용자가 쉽게 분류 할 수 있습니다.",
  "Category name": "카테고리 이름",
  "e.g. Birthdays": "예를 들어 생일",
  Venue: "장소",
  "Where the event takes place": "행사가 열리는 곳",
  "Venue name": "장소 이름",
  "Venue phone": "장소 전화",
  "Venue email": "장소 이메일",
  "Venue website": "장소 웹 사이트",
  Organizer: "조직자",
  "Person who makes the event": "이벤트를 만드는 사람",
  "Organizer name": "주최자 이름",
  "Organizer phone": "주최자 전화",
  "Organizer email": "주최자 이메일",
  "Organizer website": "주최자 웹 사이트",
  Save: "구하다",
  Cancel: "취소",
  Import: "수입",
  Past: "과거",
  All: "모두",
  Upcoming: "다가오는",
  Uncategorised: "분류되지 않은",
  "Date Ascending": "오름차순",
  "Date Descending": "내림차순",
  "Title by A-Z": "A-Z의 제목",
  "Title by Z-A": "Z-A의 제목",
  "There are no events for this period": "이시기에는 이벤트가 없습니다",

  "Auto-Convert Date & Time": "자동 컨버터 날짜 및 시간",
  TimeZone: "시간대",
  Autodeletion: "자가 재산",
  "Layout Settings": "레이아웃 설정",
  "Yeatly view": "예의 바로보기",
  "Monthly view header": "월간보기 헤더",
  "Weekly/Daily view header": "주간/데일리 뷰 헤더",
  Acendings: "ACENDINGS",
  Descending: "내림차순",
  Standart: "Standart",
  Silver: "은",
  Retro: "레트로",
  Dark: "어두운",
  Night: "밤",
  Aubergine: "가지",
  "List view header": "목록 뷰 헤더",
  "Side by Side View": "나란히보기",
  "Customize Proportions": "비율을 사용자 정의하십시오",
  "Card Margins": "카드 마진",
  "Image opacity (%)": "이미지 불투명도 (%)",
  "Side by Side Header": "나란히 헤더",
  "Text Align": "텍스트 정렬",
  "Timeline View": "타임 라인보기",
  "Title font color": "제목 글꼴 색상",
  "Desciption font color": "하강 글꼴 색상",
  "Line color": "라인 색상",
  "Date Font color": "날짜 글꼴 색상",
  "Daily events background": "매일 이벤트 배경",
  Alignment: "조정",
  Vertical: "수직의",
  Horizontal: "수평의",
  "Vertical Alignment": "수직 정렬",
  Right: "오른쪽",
  Center: "센터",
  "Horizontal Alignment": "수평 정렬",
  Top: "맨 위",
  Center: "센터",
  Bottom: "맨 아래",
  "Dates Circle Design": "데이트 서클 디자인",
  "Next To The Circle": "원 옆",
  "In The Circle": "원 안에",
  "Timeline Header": "타임 라인 헤더",
  Timeline: "타임 라인",
  "Show only upcoming": "다가오는 만 보여주십시오",
  "Order by": "주문",
  "Timeline Event Limit": "타임 라인 이벤트 한도",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "방문자가 Google, Yahoo, Outlook, Icalendar와 같은 지역 Calnedars에 이벤트를 추가하도록 허용합니다.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "방문자가 이벤트를 Facebook, LinkedIn, Twitter 등으로 공유하도록 허용합니다.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "캘린더에 검색 옵션을 추가하여 사람들이 제목, 장소 등으로 이벤트를 검색 할 수 있도록합니다.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "사용자가 날짜 범위에서 붐 이벤트 캘린더를 인쇄하도록 허용하십시오.",
  "Click to apply a theme to Calendar": "일정에 테마를 적용하려면 클릭하십시오",
  "Date container color": "날짜 컨테이너 색상",
  "Daily events background": "매일 이벤트 배경",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "애드온을 사용하여 캘린더에 고급 기능을 설치하여보다 기능적으로 만듭니다!",
  "Open Add-ons Store": "Add-ons 스토어를 엽니 다",
  Monday: "월요일",
  Tuesday: "화요일",
  Wednesday: "수요일",
  Thursday: "목요일",
  Friday: "금요일",
  Saturday: "토요일",
  Sunday: "일요일",
  "Yearly view": "연간 견해",
  Ascending: "오름차순",
  "Show event time next to title": "타이틀 옆에 이벤트 시간을 표시하십시오",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "이벤트 날짜와 시간을 시간대에 따라 사용자의 현지 시간으로 조정하십시오.",
  "Display the time zone alongside the event date.":
    "이벤트 날짜와 함께 시간대를 표시하십시오.",
  "Show event time next to title": "타이틀 옆에 이벤트 시간을 표시하십시오",
  "Time Zone": "시간대",
  "Upload Image": "이미지 업로드",
  "Choose a Category": "카테고리를 선택하십시오",
  "Color you have chosen will not be shown as you choose category":
    "선택한 색상은 카테고리를 선택할 때 표시되지 않습니다.",
  Website: "웹 사이트",
  Next: "다음",
  Save: "구하다",
  "Last Name": "성",
  "Personal Info": "개인적인 정보",
  Back: "뒤쪽에",
  "This field is required": "이 필드가 필요합니다",
  "Your event has been submitted": "귀하의 이벤트가 제출되었습니다",
  "Enter a location": "위치를 입력하십시오",
  "Display the time zone alongside the event date.":
    "이벤트 날짜와 함께 시간대를 표시하십시오.",
  Home: "집",
  "Side By Side Event Limit": "나란히 이벤트 한도",
  "Mobille App": "Mobille 앱",
  category: "범주",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Facebook 이벤트를 캘린더로 가져와 일정을 쉽게 추적하세요.",
  "Synchronized Pages": "동기화된 페이지",
  "There are no synchronized pages": "동기화된 페이지가 없습니다",
  "Choose page": "페이지 선택",
  "You have no events": "이벤트가 없습니다",
};
export default ko;
