let lv = {
  Categories: "Kategorijas",
  "Share this event": "Kopīgojiet šo notikumu",
  Language: "Valoda",
  "Show Time Zone": "Rādīt laika joslu",
  "Custom Local Settings": "Pielāgoti vietējie iestatījumi",
  "Add and showcase events on your site using a beautiful calendar.":
    "Pievienojiet un demonstrējiet notikumus savā vietnē, izmantojot skaistu kalendāru . ",
  "Week Days": "Nedēļas dienas",
  "Manage Events": "Pārvaldīt pasākumus",
  General: "Vispārīgi",
  "Layout Picker": "Izkārtojuma atlasītājs",
  Month: "Mēnesis",
  Monthly: "Mēneša",
  Week: "Nedēļa",
  Weekly: "Iknedēļas",
  Day: "Diena",
  Daily: "Katru dienu",
  Agenda: "Darba kārtība",
  "Navigation Buttons": "Navigācijas pogas",
  "Week numbers": "Nedēļas numuri",
  "Include Weekends": "Iekļaut nedēļas nogales",
  "All-day": "Visu dienu",
  "All Day": "Visu dienu",
  Label: "Etiķete",
  "Fit to Height": "Fit to Height",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Lai iestatītu lietotņu proporcijas, manuāli jāatspējo šī opcija un jāmaina kalendāra lielums redaktorā. ",
  "Default Layout": "Noklusētais izkārtojums",
  "Monthly view": "Mēneša skats",
  "Weekly and Daily view": "Nedēļas un dienas skats",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Varat sniegt apmeklētājiem konsekventāku pieredzi, parādot vienādu nedēļu skaitu ( 6) vienlaikus.",
  "Fixed Weekly Layout": "Fiksēts nedēļas izkārtojums",
  back: " atpakaļ ",
  Row: "Rinda",
  "Hours in Weekly View": "Stundas nedēļas skatījumā",
  "Hours in Daily View": "Stundas ikdienas skatījumā",
  Start: "Sākt",
  End: "Beigas",
  "At This Hour": "Šajā stundā",
  "Add to": "Pievienot",
  Button: "Poga",
  Buttons: "Pogas",
  Sunday: "Svētdiena",
  Monday: "Pirmdiena",
  Tuesday: "Otrdiena",
  Wednesday: "Trešdiena",
  Thursday: " Ceturtdiena ",
  Friday: "Piektdiena",
  Saturday: "Sestdiena",
  "Default Date": "Noklusējuma datums",
  year: " gads ",
  month: " mēnesis ",
  mo: " mēnesis ",
  days: " dienas ",
  ago: " pirms ",
  ahead: " priekšā ",
  Yesterday: "Vakar",
  Today: "Šodien",
  Tomorrow: "Rīt",
  Custom: "Pielāgots",
  "Set Daily Rows Limit": "Iestatīt ikdienas rindu limitu",
  "Set Proportions": "Iestatīt proporcijas",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Atļaut apmeklētājam pievienot notikumu vietējiem calnedars , Google, Yahoo, Outlook, ICalendar . ",
  Container: "Konteiners",
  Background: "Fons",
  "Container Background": "Konteinera fons",
  "Container Borders": "Konteineru robežas",
  Calendar: "Kalendārs",
  "Event Info Tooltip": "Pasākuma informācijas rīka padoms",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Kad cilvēki virzās virs kursora, viņi rīka padomā redzēs visu informāciju par to. ",
  "Event Info Window": "Pasākuma informācijas logs",
  "This is the full information window that opens when someone clicks on the event.":
    "Šis ir pilns informācijas logs, kas tiek atvērts, kad kāds noklikšķina uz notikuma. ",
  "Use Gradient": "Izmantojiet gradientu",
  Vertical: "Vertikāls",
  Horizontal: "Horizontāls",
  First: "Pirmais",
  Second: "Otrais",
  diagonal: " pa diagonāli ",
  Radial: "Radiāls",
  "Select option": "Atlasīt opciju",
  Solid: "Ciets",
  Dotted: "Punktēts",
  Dashed: "Dashed",
  Double: "Double",
  "Border Radius": "Robežas rādiuss",
  Padding: "Polsterējums",
  "Date Header": "Datuma galvene",
  "Event Default Color": "Notikuma noklusējuma krāsa",
  "Days of Week": "Nedēļas dienas",
  "Days of Week Background": "Nedēļas dienu fons",
  Date: "Datums",
  "Event Title": "Pasākuma nosaukums",
  "Highlight today": "Izcelt šodien",
  "Highlight Color": "Izcelt krāsu",
  Hide: "Slēpt",
  "Calendar Border Color": "Kalendāra apmales krāsa",
  "Calendar Border Width": "Kalendāra robežas platums",
  "Calendar Border Style": "Kalendāra apmales stils",
  "Font Color": "Fonta krāsa",
  "Event Background": "Pasākuma fons",
  "Card Date Color": "Kartes datuma krāsa",
  "Title Font": "Nosaukuma fonts",
  "Date Font": "Datuma fonts",
  "Description Font": "Apraksts fonts",
  "Button Background": "Pogas fons",
  "Button Text": "Pogas teksts",
  "Border Color": "Apmales krāsa",
  "Border Width": "Robežas platums",
  "Border Type": "Robežas tips",
  Title: "Virsraksts",
  Description: "Apraksts",
  "Background Color": "Fona krāsa",
  Divider: "Dalītājs",
  "Event Details Font": "Pasākuma detaļu fonts",
  "Website Link Color": "Vietnes saites krāsa",
  "Developer Info": "Informācija par izstrādātāju",
  "User Guide": "Lietotāja rokasgrāmata",
  "Support e-mail": "Atbalsta e-pasts",
  "Our Website": "Mūsu vietne",
  "App Review": "Lietotnes pārskats",
  "Enjoying App? Leave us a review in the App Market.":
    "Patīk lietotne? Atstājiet mums pārskatu App Market. ",
  "Review Us": "Pārskatiet mūs",
  "Connect With Us": "Sazinieties ar mums",
  "What's your email?": "Kāds ir jūsu e-pasts? ",
  "Invalid email address!": "Nederīga e-pasta adrese! ",
  Comments: "Komentāri",
  "We'd love to hear from you. Send us a message.":
    "Mēs labprāt dzirdētu no jums. Nosūtiet mums ziņojumu. ",
  "Message must be at least 5 characters long":
    "Ziņojumam jābūt vismaz 5 rakstzīmju garam",
  Send: "Sūtīt",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Ja vēlaties ļaut lietotājam pārslēgties starp kalendāra skatiem, iespējojiet šo opciju un izvēlieties skatus, kurus vēlaties parādīt. ",
  Main: "Galvenais",
  Localize: "Lokalizēt",
  Settings: "Iestatījumi",
  Layouts: "Izkārtojumi",
  Advanced: "Uzlabots",
  Design: "Dizains",
  Support: "Atbalsts",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Visi vietējie iestatījumi (automātiski) ir balstīti uz jūsu valodu. Ja jūsu valoda ir sarakstā, šī sadaļa nav jāpielāgo.",
  "Date Format": "Datuma formāts",
  "Time Format": "Laika formāts",
  "Text Direction": "Teksta virziens",
  "Left to Right": "No kreisās uz labo",
  "Right to Left": "Pa labi no kreisās",
  "Week Starts On": "Nedēļa sākas",
  "Agenda Style": "Darba kārtības stils",
  Classic: "Klasisks",
  Modern: "Moderns",
  "Agenda Header": "Darba kārtības galvene",
  "Upcoming Events": "Gaidāmie notikumi",
  "Agenda Event Limit": "Darba kārtības notikumu limits",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Jauniniet tagad un iegūstiet daudz vairāk funkciju un pilnībā izbaudiet savu lietotni!",
  "Upgrade Now": "Uzlabot tagad",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Notikumi, kas ilgst visu dienu? Tas ļauj jums tos parādīt kalendārā.",
  "24 hours": "24 stundas",
  Sun: "Svēt",
  Mon: "Pirm",
  Sat: "Sest",
  Default: "Noklusējums",
  "Select custom design style for your calendar.":
    "Atlasiet sava kalendāra pielāgoto noformējuma stilu.",
  Style: "Stils",
  "Styles and Colors": "Stili un krāsas",
  "Calendar Name": "Kalendāra nosaukums",
  "Write your Calendar name here": "Šeit ierakstiet kalendāra vārdu",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Tas jūsu lietotājiem nav redzams. Iestatiet nosaukumus, lai atšķirtu kalendārus, kad izmantojat Boom Calendar Sync funkciju.",
  "General Info": "Vispārīga informācija",
  Venue: "Norises vieta",
  Organizer: "Organizators",
  Search: "Meklēt",
  calendar: "kalendārs",
  "Copy event URL": "Kopēt notikuma URL",
  "Copied!": "Nokopēts!",
  "Add & Share": "Pievienot un kopīgot",
  Map: "Karte",
  "Calendar view": "Kalendāra skats",
  "Add Event": "Pievienot notikumu",
  Uncategorised: "Uncategorized",
  More: "Vairāk",
  Less: "Mazāk",
  Register: "Reģistrēties",
  Card: "Karte",
  Guests: "Viesi",
  unlimited: "neierobežots",
  "Show more": "Parādīt vairāk",
  "Enable Search": "Iespējot meklēšanu",
  "+ Add Event": "+ Pievienot notikumu",
  "Manage and Sync": "Pārvaldīt un sinhronizēt",
  "Show event details as...": "Rādīt informāciju par notikumu kā ...",
  Tooltip: "Rīka padoms",
  Popup: "Informācijas lodziņš",
  None: "Nav",
  "Show Category": "Rādīt kategoriju",
  "Header Align": "Galvenes izlīdzināšana",
  "Show Time": "Laiks izrādei",
  "Hours in Weekly/Daily View": "Stundas nedēļas / dienas skatā",
  "Share Events": "Kopīgojiet pasākumus",
  Shadow: "Ēna",
  "Inner Padding": "Iekšējais polsterējums",
  Text: "Teksts",
  "Active Button Border": "Aktīvās pogas apmale",
  "Light Mode": "Gaismas režīms",
  "Event Text Color": "Pasākuma teksta krāsa",
  Dates: "Datumi",
  Skeleton: "Skelets",
  "Skeleton Color": "Skeleta krāsa",
  Width: "Platums",
  "Skeleton Style": "Skeleta stils",
  Color: "Krāsa",
  "Section Titles": "Sadaļu nosaukumi",
  "Section Content": "Sadaļas saturs",
  Header: "Galvene",
  Standard: "Standarta",
  Retro: "Retro",
  Silver: "Sudrabs",
  Night: "Nakts",
  Dark: "Tumšs",
  Aubergine: "Baklažāni",
  "Map Header": "Kartes galvene",
  "Show Title in mobile": "Rādīt virsrakstu mobilajā telefonā",
  "Card View": "Kartes skats",
  "Card background color": "Kartes fona krāsa",
  "Title font": "Nosaukuma fonts",
  "Desciption font": "Apraksta fonts",
  "Section font": "Fontu sadaļa",
  "Section divider color": "Sadaļu dalītāja krāsa",
  "Add event": "Pievienot notikumu",
  "All Day Event": "Visas dienas pasākums",
  Location: "Atrašanās vieta",
  "Choose a category": "Izvēlieties kategoriju",
  "Venue name": "Norises vietas nosaukums",
  "Venue phone": "Vietas tālrunis",
  "Venue email": "Norises vietas e-pasts",
  "Venue website": "Vietas vietne",
  "Organizer name": "Organizer name",
  "Organizer phone": "Organizatora tālrunis",
  "Organizer email": "Organizer e-pasts",
  "Organizer website": "Organizatora vietne",
  "Personal info": "Personiskā informācija",
  "First name": "Vārds",
  "Last name": "Uzvārds",
  "Email Address": "Epasta adrese",
  "Additional Notes": "Papildu piezīmes",
  Back: "Atpakaļ",
  Save: "Saglabāt",
  Next: "Nākamais",
  "Your event has been submitted": "Jūsu pasākums ir iesniegts",
  "Event submittion has been failed": "Notikuma iesniegšana neizdevās",
  "e.g. Birthday Party": "piem. Dzimšanas dienas ballīte",
  "First Name": "Vārds",
  "Last Name": "Uzvārds",
  "Phone Number": "Telefona numurs",
  Address: "Adrese",
  "Your comments": "Jūsu komentāri",
  "How many guests?": "Cik viesu?",
  "Anything else we need to know?": "Vai vēl kaut kas mums jāzina?",
  "Guests:": "Viesi:",
  Submit: "Iesniegt",
  "Go to Calendar": "Dodieties uz Kalendāru",
  "Registration completed successfully!": "Reģistrācija veiksmīgi pabeigta!",
  "Please check your registered email address":
    "Lūdzu, pārbaudiet savu reģistrēto e-pasta adresi",
  "Add to Calendar": "Pievienot kalendāram",
  "Share this Event": "Kopīgojiet šo notikumu",
  "Sorry something went wrong": "Sorry, er ging iets mis",
  "Back to registration": "Atpakaļ pie reģistrācijas",
  "Date & Location": "Datums un vieta",
  "Date & Time": "Datums Laiks",
  home: "mājas",
  "Header align": "Galvenes izlīdzināšana",
  Footer: "Kājene",
  "Categories Filter": "kategorijas Filtrēt",
  "Show only upcoming": "Rādīt tikai gaidāmos",
  "Card(s) in a row": "Karte (-s) pēc kārtas",
  "Space between cards": "Vieta starp kartēm",
  "Shown events limit": "Parādīts notikumu ierobežojums",
  "Style 1": "1. stils",
  "Style 2": "2. stils",
  "Style 3": "3. stils",
  "Style 4": "4. stils",
  "Buttons & Links": "Pogas un saites",
  "Button corner radius": "Pogas stūra rādiuss",
  "Buttons font": "Pogu fonts",
  "Buttons background": "Pogu fons",
  "Get notified by Email": "Saņemiet paziņojumu pa e-pastu",
  "Review events": "Pārskatiet notikumus",
  "Click on date": "Noklikšķiniet uz datuma",
  "Add Event button": "Pievienot notikumu pogu",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Sinhronizējot kalendāru, varat integrēt savus notikumus un sesijas savā Boom kalendārā.",
  connect: "savienot",
  "Synchronized Calendars": "Sinhronizētie kalendāri",
  "Import events": "Importēt pasākumus",
  Disconnect: "Atvienojiet",
  "Choose calendar": "Izvēlieties kalendāru",
  "Monitor your Wix events through the sync feature":
    "Pārraugiet savus Wix notikumus, izmantojot sinhronizācijas funkciju",
  "Connect all your Boom calendars available on your website":
    "Pievienojiet visus jūsu vietnē pieejamos Boom kalendārus",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Ieplānojiet, pievienojieties un pārvaldiet tālummaiņas sapulces tieši caur mūsu uzplaukuma kalendāru.",
  "Monitor your Event Brite events through the Event Brite sync feature.":
    "Pārraugiet savus Event Brite notikumus, izmantojot Event Brite sinhronizācijas funkciju",
  Email: "E-pasts",
  "Add-ons": "Papildinājumi",
  "Receive notification emails as soon as users add events to your calendar.":
    "Saņemt paziņojumu e-pastus, tiklīdz lietotāji pievieno notikumus jūsu kalendārā.",
  "Enable + button on the calendar header":
    "Ieslēgt + pogu uz kalendāra galvenes",
  "Accept or decline events added by customers before making them public.":
    "Pirms publiskošanas pieņemt vai noraidīt klientu pievienotos notikumus.",
  "Switch Add Event": "Switch Pievienot notikumu",
  "Enable your browser cookies to connect to your account.":
    "Iespējojiet pārlūkprogrammas sīkfailus izveidot savienojumu ar jūsu kontu.",
  "Learn more": "Uzzināt vairāk",
  "Print Button": "Drukāšanas poga",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Atļaujiet saviem lietotājiem izdrukāt jūsu Boom notikuma kalendāru jebkurā datuma diapazonā.",
  "Show Title on mobile": "Parādīt nosaukumu mobilajā ierīcē",
  "Show Skeleton on mobile": "Rādīt skeletu mobilajā telefonā",
  "Start 7-day Business trial": "Sāciet savu 7 dienu biznesa izmēģinājumu",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Izbaudiet visas neierobežotās funkcijas, piemēram, pārdot biļetes, reģistrāciju, apmeklētāju notikumu papildinājumu.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Lūdzu, ņemiet vērā: beigās izmēģinājuma perioda, jūs atgriezīsies jūsu esošajā abonēšanas plānā.",
  "Not Now": "Ne tagad",
  "Start free trial": "Sākt bezmaksas izmēģinājumu",
  "Congrats!": "Apsveicu!",
  "Your 7-day Business trial has been successfully activated.":
    "Jūsu 7 dienu biznesa izmēģinājums ir veiksmīgi aktivizēts.",
  Done: "Darīts",
  "Title font color": "Nosaukuma fonta krāsa",
  "Desciption font color": "Apraksts Fonta krāsa",
  "Section font color": "Sekcijas fonta krāsa",
  "Card Header": "Kartes galvene",
  Category: "Kategorija",
  "Display at the": "Displejs pie",
  top: "tops",
  bottom: "apakšējā daļa",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Vitrīna kategorijas filtru augšpusē vai apakšā kalendāra.Uzstādījumi attiecas tikai uz darba kārtību un kartēm",
  "Processing your events": "Jūsu notikumu apstrāde",
  "Search for events": "Meklēt notikumus",
  "There are no events added": "Nav pievienoti notikumi",
  "Location: To be determined": "Atrašanās vieta: jānosaka",
  "No events for selected date": "Nav notikumu izvēlētajam datumam",
  Uncategorized: "Kategorizēts",
  "Edit event": "Rediģēšanas pasākums",
  "Edit original event": "Rediģēt oriģinālo notikumu",
  "Copy event": "Kopijas pasākums",
  "Copy as new event": "Kopēt kā jaunu notikumu",
  "Delete event": "Dzēst pasākumu",
  "Stop repeating on this date": "Pārtrauciet atkārtot šajā datumā",
  "Exclude this date": "Izslēdziet šo datumu",
  "Location is going to be announced": "Atrašanās vieta tiks paziņota",
  "Fill your personal information": "Aizpildiet savu personisko informāciju",
  "Check Box": "Izvēles rūtiņa",
  "Single Choice": "Viena izvēle",
  Option: "Izvēle",
  "Share Event": "Dalīties pasākumā",
  "Oops! Something went wrong": "Hmm!Kaut kas nogāja greizi",
  "We are sorry this event has already taken place":
    "Mums ir žēl, ka šis notikums jau ir noticis",
  "Back to calendar": "Atpakaļ uz kalendāru",
  "This field is required": "Šis lauks ir obligāts",
  Phone: "Telefons",
  "Number field": "Numura lauks",
  "Please provide a valid email": "Lūdzu, norādiet derīgu e -pastu",
  "Select at least one option": "Atlasiet vismaz vienu opciju",
  "Choose tickets to see total value":
    "Izvēlieties biļetes, lai redzētu kopējo vērtību",
  tickets: "biļetes",
  "Choose Tickets": "Izvēlieties biļetes",
  "Choose payment method": "Izvēlieties maksājuma veidu",
  Pay: "Samaksāt",
  Total: "Kopā",
  Free: "Bez maksas",
  "Buy tickets": "Pirkt biļetes",
  "Sold Out": "Izpārdots",
  "Tickets are available": "Biļetes ir pieejamas",
  "Sales End": "Pārdošanas beigas",
  "Availible from": "pieejams no",
  "Go to Orders": "Dodieties uz pasūtījumiem",
  "Go to Details": "Dodieties uz detaļām",
  "Group ticket": "Grupas biļete",
  Name: "Nosaukt",
  Price: "Cena",
  "Order by": "Sakārtot pēc",
  "Order ID": "Pasūtījuma ID",
  Applied: "Uzklāts",
  Fees: "Nodevas",
  "Enter promo code": "Ievadiet reklāmas kodu",
  Apply: "Pielietot",
  "Promo Code": "Reklāmas kods",
  Cash: "Nauda",
  "You can find your e-tickets attached to your email or download them":
    "Jūs varat atrast e-pasta e-e-e-biļetes vai tos lejupielādēt",
  here: "šeit",
  Time: "Laiks",
  "Invalid promo code": "Nederīgs reklāmas kods",
  "Credit card": "Kredītkarte",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Drīz jūs saņemsit apstiprinājuma ziņojumu par veiksmīgu reģistrāciju uz savu e -pasta adresi.",
  "You can also check your order details below.":
    "Varat arī pārbaudīt savu pasūtījuma informāciju zemāk.",
  at: "pie",
  Buy: "Iegādāties",
  Donation: "Ziedojums",
  "Enter price": "Uzņēmums",
  Choose: "Izvēlēties",
  Chosen: "Izvēlēts",
  "Choose your plan": "Izvēlieties savu plānu",
  week: "nedēļa",
  wk: "nedēļa",
  "Choose plan cycle": "Izvēlieties plāna ciklu",
  months: "mēneši",
  years: "gadi",
  weeks: "nedēļu",
  "Copy Event Url": "Kopēt notikumu URL",
  "You can find your e-tickets attached to your email or print them":
    "Jūs varat atrast e-pasta e-e-e-biļetes vai tos izdrukāt",
  "Guest Info": "Viesu informācija",
  "Ticket Info": "Informācija par biļetēm",
  "Ticket name": "Biļetes nosaukums",
  "Ticket price": "Biļešu cena",
  "Ticket ID": "Biļetes ID",
  "If you have any questions contact to organizer":
    "Ja jums ir kādi jautājumi, kontaktējas ar organizatoru",
  "As soon as event ends": "Tiklīdz notikums beidzas",
  "1 day after event ends": "1 dienu pēc notikuma beigām",
  "7 days after event ends": "7 dienas pēc notikuma beigām",
  "14 days after event ends": "14 dienas pēc notikuma beigām",
  "30 days after event ends": "30 dienas pēc notikuma beigām",
  Menu: "Ēdienkarte",
  "No event for selected date": "Nav notikumu atlasītajam datumam",
  view: "skats",
  List: "Saraksts",
  Year: "Gads",
  Yearly: "Ikgadējs",
  "Year view header": "Gada skata galvene",
  "Yearly Style": "Ikgadējā stils",
  "There are no events": "Nav notikumu",
  Autotranslation: "Autotranslācija",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Kad esat iespējojis, jūsu kalendāra logrīks tiks tulkots, pamatojoties uz tīmekļa vietnes valodu.* Ņemiet vērā, ka tik ilgi, cik kalendāra nosaukums un apraksti tiek ievadīti tekstus, kurus tos nevar tulkot.",
  "Note on mobile": "Piezīme par mobilo",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Izslēdziet vai mainiet 'Nē notikumu' joslas tekstu kalendāra mobilajā versijā",
  Autodeletion: "Autodelēšana",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Iespējojot opciju, automātiski noņems iepriekšējos notikumus no kalendāra.",
  "This does not apply to repeating events!":
    "Tas neattiecas uz notikumu atkārtošanu!",
  "Notify event creators about the guest": "Pranešti vartotojams apie svečią",
  "Send event creators notification emails as soon as guests register for their events":
    "Mittere rei creatores notitiam sodales mox ut hospites varius enim eorum gesta",
  "List View Type": "Saraksta skata tips",
  "Description font": "Apraksta fonts",
  Connect: "savienot",
  "You have no events": "Jums nav notikumu",
  Synchronize: "Sinhronizēt",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Met Google Calendar Sync kunt u uw evenementen en sessies integreren met uw giekkalender.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Outlook kalendāra sinhronizācija ļauj integrēt savus notikumus un sesijas ar jūsu uzplaukuma kalendāru.",
  "Your message has been sent successfully!":
    "Jūsu ziņojums ir veiksmīgi nosūtīts!",
  "There are no synchronized calendars": "동기화 된 캘린더가 없습니다.",
  "to view more than 7 events": "Om meer dan 7 evenementen te bekijken",
  "Mobile app": "모바일 앱",
  "Admin Account": "관리자 계정",
  Password: "암호",
  "Second User": "Otrais lietotājs",
  Edit: "Bewerk",
  "Guest limit": "Viesu limits",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Visi vietējie iestatījumi ir (automātiski), pamatojoties uz jūsu valodu.Ja jūsu valoda ir sarakstā, nav nepieciešams pielāgot šo sadaļu.",
  available: "pieejams",
  next: "Nākamais",
  Tickets: "Biļetes",
  Quantity: "Daudzums",
  "Promo code": "Reklāmas kods",
  "Select a payment method": "Izvēlieties maksājuma veidu",
  Fee: "Maksa",
  Book: "Grāmata",
  "All the tickets have been sold out": "Visas biļetes ir pārdotas",
  "Choose at least one ticket": "Izvēlieties vismaz vienu biļeti",
  "First choose ticket": "Vispirms izvēlieties biļeti",
  "Please fill out your personal information.":
    "Lūdzu, aizpildiet savu personisko informāciju.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "Lai veiktu veiksmīgu pirkumu, lūdzu, izvēlieties vēlamo maksājuma veidu un ievadiet reklāmas kodu diskontētās biļetēm.",
  "Credit/Debit card": "Kredīta / debetkarte",
  "print here.": "Drukāt šeit.",
  "QR code for all tickets": "QR kods visām biļetēm",
  Duration: "Ilgums",
  "Full Name": "Pilnais vārds",
  "Ticket id": "Biļetes ID",
  "Group id": "Grupas ID",
  "Choose your ticket.": "Izvēlieties savu biļeti.",
  "Fill out your personal information.":
    "Aizpildiet savu personisko informāciju.",
  "Add the payment details.": "Pievienojiet maksājuma datus.",
  "To be determined": "Tiks noteikts",
  "You can find your e-tickets attached to the email or":
    "Jūs varat atrast e-biļetes pievienotas e-pastam vai",
  "print here": "drukāt šeit",
  "Full name": "Pilnais vārds",
  "Group ID": "Grupas ID",
  "to Book": "rezervēt",
  "Unfortunately, your card has been declined":
    "Diemžēl jūsu karte ir noraidīta",
  "Thank you for your purchase!": "Paldies par pirkumu!",
  "Find your printable e-tickets attached to the confirmation email":
    "Atrodiet izdrukājamos e-biļetes, kas pievienotas apstiprinājuma e-pastam",
  Confirm: "Apstiprināt",

  "Add event": "Pievienot notikumu",
  Events: "Notikumi",
  "Event details": "Noteikta informācija",
  Registration: "Reģistrācija",
  "Guests list": "Viesu saraksts",
  Ticket: "Biļete",
  "General Info": "Vispārīga informācija",
  "Customize the general settings of your event":
    "Pielāgojiet sava pasākuma vispārīgos iestatījumus",
  "Event Title": "Notikuma nosaukums",
  "e.g. Birthday Party": "piem. Dzimšanas dienas ballīte",
  "All Day Event": "Visu dienu pasākums",
  Cross: "Šķērsot",
  Timeline: "Laika grafiks",
  "Repeating event": "Atkārtošanas notikums",
  Location: "Atrašanās vieta",
  "Venue name": "Norises nosaukums",
  Description: "Apraksts",
  Image: "Attēls",
  Color: "Krāsa",
  Category: "Kategorija",
  "Add your events to color categories and let your users classify them easily":
    "Pievienojiet savus pasākumus krāsu kategorijām un ļaujiet lietotājiem tos viegli klasificēt",
  "Category name": "Kategorijas nosaukums",
  "e.g. Birthdays": "piem. Dzimšanas dienas",
  Venue: "Norises vieta",
  "Where the event takes place": "Kur notiek pasākums",
  "Venue name": "Norises nosaukums",
  "Venue phone": "Norises telefons",
  "Venue email": "Norises e -pasts",
  "Venue website": "Norises vietas vietne",
  Organizer: "Organizators",
  "Person who makes the event": "Persona, kas veido pasākumu",
  "Organizer name": "Organizatora nosaukums",
  "Organizer phone": "Organizatora tālrunis",
  "Organizer email": "Organizatora e -pasts",
  "Organizer website": "Organizatora vietne",
  Save: "Ietaupīt",
  Cancel: "Atcelt",
  Import: "Importēt",
  Past: "Pagātne",
  All: "Viss",
  Upcoming: "Gaidāmais",
  Uncategorised: "Kategorijas",
  "Date Ascending": "Datums Augstums",
  "Date Descending": "Datums dilstoties",
  "Title by A-Z": "A-Z nosaukums",
  "Title by Z-A": "Nosaukums BY Z-A",
  "There are no events for this period": "Šajā periodā nav notikumu",

  "Auto-Convert Date & Time": "Automātiskā konvertēšanas datums un laiks",
  TimeZone: "Laika zona",
  Autodeletion: "Autodelēšana",
  "Layout Settings": "Izkārtojuma iestatījumi",
  "Yeatly view": "Yeatly skats",
  "Monthly view header": "Ikmēneša skata galvene",
  "Weekly/Daily view header": "Nedēļas/ikdienas skata galvene",
  Acendings: "Piegaršojumi",
  Descending: "Nolaišanās",
  Standart: "Standarts",
  Silver: "Sudrabs",
  Retro: "Retro",
  Dark: "Tumšs",
  Night: "Naktsmītne",
  Aubergine: "Baklažāns",
  "List view header": "Saraksta skata galvene",
  "Side by Side View": "Sānu skats",
  "Customize Proportions": "Pielāgojiet proporcijas",
  "Card Margins": "Kāršu malas",
  "Image opacity (%)": "Attēla necaurredzamība (%)",
  "Side by Side Header": "Sānu galvene",
  "Text Align": "Teksta izlīdzināšana",
  "Timeline View": "Laika skats",
  "Title font color": "Nosaukuma fonta krāsa",
  "Desciption font color": "Desciption fonta krāsa",
  "Line color": "Līnijas krāsa",
  "Date Font color": "Datuma fonta krāsa",
  "Daily events background": "Ikdienas notikumu fons",
  Alignment: "Izlīdzināšana",
  Vertical: "Vertikāls",
  Horizontal: "Horizontāls",
  "Vertical Alignment": "Vertikāla izlīdzināšana",
  Right: "Pa labi",
  Center: "Centrs",
  "Horizontal Alignment": "Horizontāla izlīdzināšana",
  Top: "Tops",
  Center: "Centrs",
  Bottom: "Dibens",
  "Dates Circle Design": "Datumu apļa dizains",
  "Next To The Circle": "Blakus apli",
  "In The Circle": "Lokā",
  "Timeline Header": "Laika skala",
  Timeline: "Laika grafiks",
  "Show only upcoming": "Rādīt tikai gaidāmo",
  "Order by": "Sakārtot pēc",
  "Timeline Event Limit": "Laika skalas notikumu ierobežojums",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Ļaujiet apmeklētājam pievienot notikumu vietējiem Calnedars: Google, Yahoo, Outlook, Icalendar.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Ļaujiet apmeklētājam koplietot savu pasākumu ar Facebook, LinkedIn, Twitter un utt.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Kalendārā pievienojiet meklēšanas opciju, lai ļautu cilvēkiem meklēt jūsu pasākumus pēc nosaukuma, norises vietas utt.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Ļaujiet lietotājiem izdrukāt jūsu uzplaukuma notikumu kalendāru jebkurā datumu diapazonā.",
  "Click to apply a theme to Calendar":
    "Noklikšķiniet, lai kalendārā izmantotu tēmu",
  "Date container color": "Datuma konteinera krāsa",
  "Daily events background": "Ikdienas notikumu fons",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Izmantojiet papildinājumus, lai kalendāros instalētu uzlabotas funkcijas, padarot tās funkcionālākas!",
  "Open Add-ons Store": "Atvērts papildinājumu veikals",
  Monday: "Pirmdiena",
  Tuesday: "Otrdiena",
  Wednesday: "Trešdiena",
  Thursday: "Ceturtdiena",
  Friday: "Piektdiena",
  Saturday: "Sestdiena",
  Sunday: "Svētdiena",
  "Yearly view": "Ikgadējā skats",
  Ascending: "Augošs",
  "Show event time next to title": "Izrādes notikumu laiks blakus nosaukumam",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Pielāgojiet notikuma datumu un laiku lietotāja vietējam laikam, pamatojoties uz viņu laika joslu.",
  "Display the time zone alongside the event date.":
    "Parādiet laika joslu līdzās notikuma datumam.",
  "Show event time next to title": "Izrādes notikumu laiks blakus nosaukumam",
  "Time Zone": "Laika zona",
  "Upload Image": "Augšupielādēt attēlu",
  "Choose a Category": "Izvēlieties kategoriju",
  "Color you have chosen will not be shown as you choose category":
    "Izvēlētā krāsa netiks parādīta, kā izvēlaties kategoriju",
  Website: "Vietne",
  Next: "Nākamais",
  Save: "Ietaupīt",
  "Last Name": "Uzvārds",
  "Personal Info": "Personiskā informācija",
  Back: "Aizmugure",
  "This field is required": "Šis lauks ir obligāts",
  "Your event has been submitted": "Jūsu pasākums ir iesniegts",
  "Enter a location": "Ievadiet vietu",
  "Display the time zone alongside the event date.":
    "Parādiet laika joslu līdzās notikuma datumam.",
  Home: "Mājas",
  "Side By Side Event Limit": "Sānu notikumu ierobežojums",
  "Mobille App": "Mobille lietotne",
  category: "kategorija",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Ērti sekojiet līdzi savam grafikam, importējot savus Facebook notikumus savā kalendārā.",
  "Synchronized Pages": "Sinhronizētās lapas",
  "There are no synchronized pages": "Nav sinhronizētu lapu",
  "Choose page": "Izvēlieties lapu",
  "You have no events": "Jums nav notikumu",
};
export default lv;
