let mn = {
  Categories: "Ангилал",
  "Share this event": "Энэ үйл явдлыг хуваалцах",
  Language: "Хэл",
  "Show Time Zone": "Цагийн бүсийг харуулах",
  "Custom Local Settings": "Захиалгат орон нутгийн тохиргоо",
  "Add and showcase events on your site using a beautiful calendar.":
    "Үзэсгэлэнт хуанли ашиглан сайт дээрээ үйл явдлыг нэмж оруулаарай.",
  "Week Days": "Ажлын өдрүүд",
  "Manage Events": "Ариувлан үйл ажиллагааг удирдах",
  General: "Жанжин",
  "Layout Picker": "Зохион байгуулалт сонгогч",
  Month: "Сар",
  Monthly: "Сар бүр",
  Week: "Долоо хоног",
  Weekly: "Хэвлэл",
  Day: "Өдөр",
  Daily: "Өдөр бүр",
  Agenda: "Хэлэлцэх асуудал",
  "Navigation Buttons": "Навигацийн товчлуурууд",
  "Week numbers": "Долоо хоногийн дугаар",
  "Include Weekends": "Амралтын өдрүүдэд орно",
  "All-day": "Бүх өдөр",
  "All Day": "Бүх өдөр",
  Label: "Шошго",
  "Fit to Height": "Өндөрт тохирох",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Апп пропорцийг тохируулахын тулд энэ сонголтыг идэвхжүүлж, энэ сонголтыг идэвхжүүлж, редакторын календарийг өөрчлөх.",
  "Default Layout": "Анхдагч байрлал",
  "Monthly view": "Сараар харах",
  "Weekly and Daily view": "Долоо хоног, өдөр бүр үзэх",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Та зочдод нэг удаадаа ижил тооны долоо хоног (6) харуулсан илүү тууштай туршлага өгч болно.",
  "Fixed Weekly Layout": "Тогтмол долоо хоног бүр зохион байгуулалт",
  back: "буцах",
  Row: "Эгнээ",
  "Hours in Weekly View": "Долоо хоног бүр үзэх цаг",
  "Hours in Daily View": "Өдөр тутмын харах цаг",
  Start: "Эхлэх",
  End: "Төгсгөл",
  "At This Hour": "Энэ цаг",
  Button: "Товч",
  Buttons: "Товчлуурууд",
  Sunday: "Ням гариг",
  Monday: "Даваа гариг",
  Tuesday: "Мягмар гариг",
  Wednesday: "Лхагва гараг",
  Thursday: "Пурэв гариг",
  Friday: "Баасан гариг",
  Saturday: "Бямба гараг",
  "Default Date": "Үндсэн хугацаа",
  year: "жил",
  month: "сар",
  mo: "mo",
  days: "ах",
  ago: "урьд",
  ahead: "түрүүнд",
  Yesterday: "Өчигдөр",
  Today: "Оноо",
  Tomorrow: "Маргааш",
  Custom: "Ес заншил",
  "Set Daily Rows Limit": "Өдөр бүр мөрийг тогтооно",
  "Set Proportions": "Хэцүүг тохируулна уу",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Зочинд очиж, орон нутгийн калледедард үйл явдлыг орон нутгийн калледаруудад нэмэхийг зөвшөөрөх",
  Container: "Чингэлэг",
  Background: "Дэвсгэр",
  "Container Background": "Савны дэвсгэр",
  "Container Borders": "Контейнер хил",
  Calendar: "Хуанли",
  "Event Info Tooltip": "Үйл явдлын мэдээллийн хэрэгсэл",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Хүмүүс үйл явдлын дээгүүр явж байгаа үед тэд бүх мэдээллийг хэрэгсэхгүй болгох болно.",
  "Event Info Window": "Үйл явдлын мэдээлэл",
  "This is the full information window that opens when someone clicks on the event.":
    "Энэ бол хэн нэгэн үйл явдал дээр дарахад нээгддэг бүрэн мэдээллийн цонх юм.",
  "Use Gradient": "Градиентийг ашиглах",
  Vertical: "Босоо шугам",
  Horizontal: "Хэвтээ",
  First: "Хамгийн түрүүнд",
  Second: "Хоёрдахь нь",
  diagonal: "Даглаг эх",
  Radial: "Цахилгаан тэжээл",
  "Select option": "Сонголт сонгоно уу",
  Solid: "Хатуу биет",
  Dotted: "Загвар",
  Dashed: "Тассон",
  Double: "Ижил юм",
  "Border Radius": "Хилийн радиус",
  Padding: "Дэвсгэр",
  "Date Header": "Ог огноо",
  "Event Default Color": "Үйл явдлын анхдагч өнгө",
  "Days of Week": "Долоо хоногийн өдрүүд",
  "Days of Week Background": "Долоо хоногийн өдрүүд",
  Date: "Огноо",
  "Event Title": "Арга хэмжээний гарчиг",
  "Highlight today": "Өнөөдөр онцлох",
  "Highlight Color": "Өнгөөр ​​тодруул",
  Hide: "Арөс элдэх",
  "Calendar Border Color": "Хуанли хилийн өнгө",
  "Calendar Border Width": "Хуанлийн хилийн өргөн",
  "Calendar Border Style": "Хуанлийн хилийн хэв маяг",
  "Font Color": "Үсгийн өнгө",
  "Event Background": "Арга хэмжээний дэвсгэр",
  "Card Date Color": "Картын огноо өнгө",
  "Title Font": "Гарчиг фонт",
  "Date Font": "Огноо огноо",
  "Description Font": "Тайлбар Фонт",
  "Button Background": "Товчны суурь",
  "Button Text": "Товчлуурын текст",
  "Border Color": "Хилийн өнгө",
  "Border Width": "Хилийн өргөн",
  "Border Type": "Хилийн төрөл",
  Title: "Гарчиг",
  Description: "Тодорхойлолт / төрөл анги",
  "Background Color": "Дэвсгэр өнгө",
  Divider: "Gooloteerer",
  "Event Details Font": "Арга хэмжээний дэлгэрэнгүй мэдээлэл",
  "Website Link Color": "Вэбсайтын холбоос",
  "Developer Info": "Хөгжүүлэгчийн мэдээлэл",
  "User Guide": "Хэрэглэгчийн гарын авлага",
  "Support e-mail": "И-мэйлийг дэмжих",
  "Our Website": "Манай вэбсайт",
  "App Review": "Батлан ​​шийдвэр",
  "Enjoying App? Leave us a review in the App Market.":
    "Апп тааламжтай байна уу? Биднийг апп зах зээл дээр тоймлох.",
  "Review Us": "Биднийг тоймлох",
  "Connect With Us": "Бидэнтэй холбогдох",
  "What's your email?": "Таны и-мэйл юу вэ?",
  "Invalid email address!": "Хүчингүй мэйл хаяг!",
  Comments: "Смхиман",
  "We'd love to hear from you. Send us a message.":
    "Бид танаас сонсохыг хүсч байна. Бидэнд мессеж илгээх.",
  "Message must be at least 5 characters long":
    "Зурвас нь дор хаяж 5 тэмдэгтээс урт байх ёстой",
  Send: "Явуулах",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Хэрэв та хэрэглэгчийг калентын үзэл бодлын хооронд шилжүүлэхийг зөвшөөрөхийг хүсч байвал энэ сонголтыг идэвхжүүлж, үзүүлэхийг хүсч буй үзэл бодлыг сонгоно уу.",
  Main: "Гол зүйл",
  Localize: "Ерөнхий бүл",
  Settings: "Тохиргоо",
  Layouts: "Тохируулга",
  Advanced: "Дэвшилттэй",
  Design: "Дизайн",
  Support: "Дэмжлэг",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Бүх орон нутгийн тохиргоо нь таны хэл дээр үндэслэн (автоматаар) байдаг. Хэрэв таны хэл жагсаалтад байгаа бол энэ хэсгийг өөрчлөх шаардлагагүй.",
  "Date Format": "Огноо формат",
  "Time Format": "Хугацааны баримт",
  "Text Direction": "Текс тасаль чиглэл",
  "Left to Right": "Зүүнээс баруун тийш",
  "Right to Left": "Баруун тийш",
  "Week Starts On": "Долоо хоног эхэлнэ",
  "Agenda Style": "Хэлэлцэх хэв маяг",
  Classic: "Сонгонгууль",
  Modern: "Орчин үеийн",
  "Agenda Header": "Хэлэлцэх асуудал",
  "Upcoming Events": "Удахгүй болох арга хэмжээ",
  "Agenda Event Limit": "Хэлэлцэх арга хэмжээний хязгаарлалт",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Одоо шинэчлэгдэж, илүү их онцлог шинж чанаруудыг олж аваад апп-аа бүрэн дүүрэн өнгөрүүлээрэй!",
  "Upgrade Now": "Одоо шинэчлэх",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Өдөржингөө зохион байгуулж буй үйл явдлыг зохион байгуулах уу? Энэ нь таныг хуанли дээр нь харуулах боломжийг танд олгоно.",
  "24 hours": "24 цаг",
  Sat: "Хуваар сар",
  Sun: "Нар",
  Mon: "Монгол",
  Default: "Үл хүрэлцэх",
  "Select custom design style for your calendar.":
    "Календарьт зориулан захиалгын загварыг сонгоно уу.",
  Style: "Хэв маяг",
  "Styles and Colors": "Загвар ба өнгө",
  "Calendar Name": "Календарийн нэр",
  "Write your Calendar name here": "Өөрийн Календарийн нэрийг энд бичнэ үү",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Энэ нь таны хэрэглэгчдэд харагдахгүй байна. Boom Calnendar Sync функцийг ашиглахдаа өөрийн хуанлигаа өөрчилнө үү.",
  "General Info": "Ерөнхий мэдээлэл",
  Venue: "Venue",
  Organizer: "Цэг хурал",
  Search: "Эрэл хайгуул хийх",
  "Add to": "Нэмж нах",
  calendar: "хуанли",
  "Copy event URL": "Үйл явдлын URL хуулах",
  "Copied!": "Хуулбарласан!",
  "Add & Share": "Нэмэх ба хуваалцах",
  Map: "Газрын зураг",
  "Calendar view": "Календарь үзэх",
  "Add Event": "Галт нэмэх",
  Uncategorised: "Ангилагдаагүй",
  More: "Илүү / их олон",
  Less: "Бага",
  Register: "Бүртгүүлэх",
  Card: "Хөзөр",
  Guests: "З зогүүд",
  unlimited: "хязгааргүй",
  "Show more": "Дэлгэрэнгүй харуулах",
  "Enable Search": "Хайлтыг идэвхжүүлэх",
  "+ Add Event": " + Арга хэмжээ нэмэх",
  "Manage and Sync": "Удирдах, синк хийх",
  "Show event details as...": "Үйл явдлын мэдээллийг харуулах ...",
  Tooltip: "Хэрэгсэл",
  Popup: "Пулоп",
  None: "Хэн ч",
  "Show Category": "Хариулалын гүйлгэх",
  "Header Align": "Алдаа тэгш хурал",
  "Show Time": "Цаг нь харлал",
  "Hours in Weekly/Daily View": "Долоо хоног бүр / өдөр бүр үзэх цаг",
  "Share Events": "Хувь нэмрүүд бусад арга",
  Shadow: "Харанхуй",
  "Inner Padding": "Дотоод дэвсгэр",
  Text: "Сэдэв",
  "Active Button Border": "Идэвхтэй товчлуурын хил",
  "Light Mode": "Гэрлэлт",
  "Event Text Color": "Үйл явдлын текст өнгө",
  Dates: "Огноо",
  Skeleton: "Араг яс",
  "Skeleton Color": "Арагтон өнгө",
  Width: "Өргөн",
  "Skeleton Style": "Арагхоникийн загварын түүх",
  Color: "Өнгө",
  "Section Titles": "Хэсчилт хувь",
  "Section Content": "Дүрэм",
  Header: "Чимээ",
  Standard: "Стандарт",
  Retro: "Reted",
  Silver: "Мөнгө",
  Night: "Шөнө",
  Dark: "Бүдүүлэг",
  Aubergine: "Aёgerinny",
  "Map Header": "Газрын зургийн толгой",
  "Show Title in mobile": "Гар утсан дээр гарчиг үзүүлэх",
  "Card View": "Карт карт од",
  "Card background color": "Картын дэвсгэр өнгө",
  "Title font": "Гарчиг фонт",
  "Desciption font": "ҮНЭГҮЙ ҮНЭГҮЙ",
  "Section font": "Хувь хувьхант догол",
  "Section divider color": "Хэсэг нь хуваагчийн өнгийг",
  "Add event": "Галт нэмэх",
  "All Day Event": "Бүх өдрийн арга хэмжээг",
  Location: "Байрлал",
  "Choose a category": "Ангилал сонгоно уу",
  "Venue name": "Үйлнэлийн нэр",
  "Venue phone": "Зоогийн газрын утас",
  "Venue email": "Газар олгох",
  "Venue website": "ТУСГАЙ САЙХАН",
  "Organizer name": "Зохион байгуулагч Нэр",
  "Organizer phone": "Зохион байгуулагч утас",
  "Organizer email": "Орилохор код",
  "Organizer website": "Зохион байгуулагч вэбсайт",
  "Personal info": "Хувийн мэдээлэл",
  "First name": "Нэр",
  "Last name": "Хугацагтай",
  "Email Address": "Имэйл хаяг",
  "Additional Notes": "Нэмэлт нэвтрэх",
  Back: "Буцах",
  Save: "Аврах",
  Next: "Дараачийн",
  "Your event has been submitted": "Таны үйл явдлыг ирүүлэв",
  "Event submittion has been failed": "Үйл явдлын илтгэл амжилтгүй болсон",
  "e.g. Birthday Party": "жишээ нь e. Төрсөн өдрийн үдэшлэг",
  "First Name": "Нэр",
  "Last Name": "Хугацагтай",
  "Phone Number": "Утасны дугаар",
  Address: "Хаяглах",
  "Your comments": "Таны сэтгэгдэл",
  "How many guests?": "Хэдэн зочин бэ?",
  "Anything else we need to know?": "Бид мэдэх хэрэгтэй өөр зүйл байна уу?",
  "Guests:": "Зочид:",
  Submit: "Бууж өгөх",
  "Go to Calendar": "Хуанли руу очно уу",
  "Registration completed successfully!": "Бүртгэл амжилттай дууссан!",
  "Please check your registered email address":
    "Бүртгэгдсэн имэйл хаягаа шалгана уу",
  "Add to Calendar": "Хуанли руу нэмж оруулаарай",
  "Share this Event": "Энэ үйл явдлыг хуваалцах",
  "Sorry something went wrong": "Уучлаарай, алдаа гарсан байна",
  "Back to registration": "Бүртгэл рүү буцах",
  "Date & Location": "Огноо ба байршил",
  "Date & Time": "Он сар өдөр цаг",
  home: "гэр",
  "Header align": "Алдаа тэгш хурал",
  Footer: "Загварын",
  "Categories Filter": "Ангилал шүүлтүүр",
  "Show only upcoming": "Зөвхөн удахгүй болох шоу",
  "Card(s) in a row": "Мөрөнд карт (ууд)",
  "Space between cards": "Картуудын хоорондох зай",
  "Shown events limit": "Үйл явдлын хязгаарлалт",
  "Style 1": "Загвар 1",
  "Style 2": "Тоолуур 2",
  "Style 3": "SteB3",
  "Style 4": "Дөх хэв маяг",
  "Buttons & Links": "Товчлуур ба холбоосууд",
  "Button corner radius": "Товчлуурын булангийн радиус",
  "Buttons font": "Товчлуурууд фонт",
  "Buttons background": "Товчлуурууд",
  "Get notified by Email": "Имэйлээр мэдэгдэх",
  "Review events": "Үйл явдлыг хянах",
  "Click on date": "Огноо дээр дарна уу",
  "Add Event button": "Үйл явдлын товчийг нэмнэ үү",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Календарь синхрончлол нь таны үйл явдлууд, хуралдааныг Boom Calend-тай нэгтгэх боломжийг олгодог.",
  connect: "холбох",
  "Synchronized Calendars": "Синхрон хуанли",
  "Import events": "Импортлох үйлчилгээ",
  Disconnect: "Тусгаарлах",
  "Choose calendar": "Хуанли сонгох",
  "Monitor your Wix events through the sync feature":
    "WIX үйл явдлыг синхрончлох замаар хянах",
  "Connect all your Boom calendars available on your website":
    "Таны вэбсайт дээр байгаа бүх BOOM CACENDARS-ийг холбоно уу",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Хуваарь, нэгдэх, томруулах уулзалтыг манай Boom хуанлигаар дамжуулан зөв удирддаг.",
  "Monitor your Event Brite events through the Event Brite sync feature..":
    "Үйл явдлын Brite үйл явдлын синхрончлолоор дамжуулан таны үйл явдлыг хянах",
  Email: "Байлдлаа",
  "Add-ons": "Нэмэлт",
  "Receive notification emails as soon as users add events to your calendar.":
    "Хэрэглэгчдэд үйл явдлыг календарь нэмэх арга хэмжээ нэмэгдэхэд мэдэгдлийн имэйл хүлээн авах.",
  "Enable + button on the calendar header":
    "Хуанли толгой дээр + товчийг дарна уу",
  "Accept or decline events added by customers before making them public.":
    "Үйлчлүүлэгчдэд олон нийтэд нээлттэй болгохын өмнө үйл явдлыг хүлээн авах эсвэл татгалзах.",
  "Switch Add Event": "Шилжүүлэгч нэмэх арга хэмжээ нэмнэ",
  "Enable your browser cookies to connect to your account.":
    "Өөрийн хөтөчийн жигнэмэгийг өөрийн акаунт руу холбоно уу.",
  "Learn more": "Илүү их судла",
  "Print Button": "Хэвлэсэн товч",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Хэрэглэгчид таны хэрэглэгчид таны Boom үйл явдлын хуанлигаа хэзээ ч болзоонд хэвлэхийг зөвшөөрнө үү.",
  "Show Title on mobile": "Гарчиг гарчиг дээр харуул",
  "Show Skeleton on mobile": "Гар утсан дээр араг ясыг харуул",
  "Start 7-day Business trial": "7 хоногийн бизнес шүүх хурал эхлэх",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Тасалбар, бүртгэл, бүртгэлийн арга хэмжээг зарах гэх мэт бүх хязгааргүй шинж чанаруудыг сайхан өнгөрүүлээрэй.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Анхаарна уу: Туршилтын хугацааны төгсгөлд та одоо байгаа захиалгын төлөвлөгөөнд буцаж ирнэ.",
  "Not Now": "Одоо биш",
  "Start free trial": "Үнэгүй туршилт эхэлнэ",
  "Congrats!": "Баяр хүргэе!",
  "Your 7-day Business trial has been successfully activated.":
    "Таны 7 хоногийн бизнес шүүх хурал амжилттай идэвхжсэн байна.",
  Done: "Хийх",
  "Title font color": "Гарчиг үсгийн өнгө",
  "Desciption font color": "ҮНЭГҮЙ ҮНЭГҮЙ ҮНЭГҮЙ",
  "Section font color": "Хэсгийн үсгийн өнгө",
  "Card Header": "Ак мэдээллийн хүрэг",
  Category: "Зэрэглэл",
  "Display at the": "Харуулах",
  top: "таг",
  bottom: "ероол",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Ангилалын шүүлтүүрийг дээд эсвэл хуанлийн ёроолд харуул. Тохиргоо нь зөвхөн хэлэлцэх асуудал, картын үзэл бодолд хамаарна",
  "Processing your events": "Таны үйл явдлыг боловсруулах",
  "Search for events": "Үйл явдлыг хайх",
  "There are no events added": "Ямар ч арга хэмжээ байхгүй байна",
  "Location: To be determined": "Байршил: Тодорхойлох",
  "No events for selected date":
    "Сонгосон огноог хийх арга хэмжээ байхгүй байна",
  Uncategorized: "Ангилагдаагүй",
  "Edit event": "Засах үйл явдлыг засах",
  "Edit original event": "Анхны үйл явдлыг засах",
  "Copy event": "Хуулах үйл яв",
  "Copy as new event": "Шинэ үйл явдал болгон хуулах",
  "Delete event": "Арга хэмжээг устгах",
  "Stop repeating on this date": "Энэ өдрийг давтахаа боль",
  "Exclude this date": "Энэ хугацааг хасах",
  "Location is going to be announced": "Байршлыг зарлах гэж байна",
  "Fill your personal information": "Хувийн мэдээллийг бөглөнө үү",
  "Check Box": "Доог залгаж",
  "Single Choice": "Бие сонголт",
  Option: "Сонголт",
  "Share Event": "Хувьцааны арга хэмжээ",
  "Oops! Something went wrong": "Өө! Ямар нэгэн зүйл буруугаар эргэсэн",
  "We are sorry this event has already taken place":
    "Уучлаарай, энэ арга хэмжээ аль хэдийн явагдсан байна",
  "Back to calendar": "Календар руу буцах",
  "This field is required": "Энэ талбар шаардлагатай байна",
  Phone: "Утас",
  "Number field": "Дугаар Хөөний болно",
  "Please provide a valid email": "Зөв имэйлээр оруулна уу",
  "Select at least one option": "Дор хаяж нэг сонголтыг сонгоно уу",
  "Choose tickets to see total value":
    "Нийт дүнг харахын тулд тасалбараа сонгоно уу",
  tickets: "тасал",
  "Choose Tickets": "Тасалбараа сонгоно уу",
  "Choose payment method": "Төлбөрийн аргыг сонгоно уу",
  Pay: "Төлөх",
  Total: "Нийт",
  Free: "Үнэгүй",
  "Buy tickets": "Тасалбар худалдаж авах",
  "Sold Out": "Зарлагдсан",
  "Tickets are available": "Тасалбар авах боломжтой",
  "Sales End": "Буллиллаар дуусах",
  "Availible from": "Үүнээс",
  "Go to Orders": "Захиалга руу яв",
  "Go to Details": "Дэлгэрэнгүй хүн",
  "Group ticket": "Камерын тасалбар",
  Name: "Нэр",
  Price: "Үнэ",
  "Order by": "Хэмжээ захиал",
  "Order ID": "Захиалах ID",
  Applied: "Хэрэгл өргөдөл",
  Fees: "Хур сурталчилгааны",
  "Enter promo code": "Сурталчилгааны кодыг оруулна уу",
  Apply: "Хандах",
  "Promo Code": "Сурталчилгаа",
  Cash: "Бэлэн мөнгө",
  "You can find your e-tickets attached to your email or download them":
    "Та өөрийн цахим тасалбараа имэйлд хавсаргасан эсвэл татаж авах боломжтой",
  here: "энэ",
  Time: "Цаг хугацаа",
  "Invalid promo code": "Буруу сурталчилгааны код",
  "Credit card": "Автомат карт",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Та удахгүй таны имэйл хаяг руу амжилттай бүртгэлийн баталгаажуулалтыг баталгаажуулах болно.",
  "You can also check your order details below.":
    "Та мөн захиалгын мэдээллийг доороос шалгаж болно.",
  at: "дэргэд",
  Buy: "Худалдан авах",
  Donation: "Хандив",
  "Enter price": "Үнэ оруулна",
  Choose: "Сонгох",
  Chosen: "Сонгогд",
  "Choose your plan": "Төлөвлөгөөгөө сонгоно уу",
  week: "долоо хоног",
  wk: "эг cy",
  "Choose plan cycle": "Төлөвлөгөөний мөчлөгийг сонгоно уу",
  months: "сар",
  years: "жил",
  weeks: "долоо хаана байна",
  "Copy Event Url": "Үйл явдлын URL хуулах",
  "You can find your e-tickets attached to your email or print them":
    "Та өөрийн цахим тасалбараа имэйлд хавсаргасан эсвэл тэдгээрийг хэвлэх боломжтой",
  "Guest Info": "Зочны мэдээлэл",
  "Ticket Info": "Тасалбарын мэдээлэл",
  "Ticket name": "Тасалбарын нэр",
  "Ticket price": "Тасалбарын үнэ",
  "Ticket ID": "Тасалбарын дугаар",
  "If you have any questions contact to organizer":
    "Хэрэв танд ямар нэгэн асуулт байвал ADICERAGER-тай холбоо барина уу",
  "As soon as event ends": "Үйл явдлын дуусмагц",
  "1 day after event ends": "Үйл явдлын дараа 1 өдөр дуусна",
  "7 days after event ends": "Үйл явдлын дараа 7 хоногийн дараа дуусна",
  "14 days after event ends": "Үйл явдлын дараа 14 хоногийн дараа",
  "30 days after event ends": "Үйл явдлын дараа 30 хоногийн дараа дуусна",
  Menu: "Хоолны нэрс",
  "No event for selected date":
    "Сонгосон огноо ямар ч арга хэмжээ байхгүй байна",
  view: "харагдац",
  List: "Жагсаалт",
  Year: "Жил",
  Yearly: "Настай",
  "Year view header": "Жилийн харах толгой",
  "Yearly Style": "Жилд маягийн хэв маяг",
  "There are no events": "Арга хэмжээ байхгүй байна",
  Autotranslation: "Autotranslation",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Нэгэнт нэг удаа идэвхжүүлсэн, хуанлигийн виджетийг вэбсайтын хэл дээр үндэслэн хийнэ. * Календарийн гарчиг, тайлбар, тайлбар нь орчуулагдсан текстийг оруулж, тайлбарыг оруулж болно.",
  "Note on mobile": "Гар утсан дээр тэмдэглэл",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Календарийн гар утасны хувилбар дээрх 'арга хэмжээ байхгүй' текстийг унтраа эсвэл өөрчлөх",
  Autodeletion: "Autodewnion",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Сонголтыг идэвхжүүлж, таны өнгөрсөн үйл явдлыг хуанлигаас автоматаар устгах болно.",
  "This does not apply to repeating events!":
    "Энэ нь давтагдах арга хэмжээнд хамаарахгүй!",
  "Notify event creators about the guest":
    "Зочны тухай үйл явдлын бүтээгчдийг мэдэгдэх",
  "Send event creators notification emails as soon as guests register for their events":
    "Үйл явдлын бүтээгчид өөрсдийн үйл явдлуудад зочдод бүртгүүлэх",
  "List View Type": "Жагсаалтын харагдах байдал",
  "Description font": "Тайлбар Фонт",
  Connect: "Холбох",
  "You have no events": "Танд арга хэмжээ байхгүй байна",
  Synchronize: "Синхрончлох",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Google Calendar Sync нь таны үйл явдлууд, хуралдааныг Boom Calend-тай нэгтгэх боломжийг танд олгоно.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Outlook Calend Sync нь таны үйл явдлууд, хуралдааныг Boomendar-тай нэгтгэх боломжийг олгодог.",
  "Your message has been sent successfully!":
    "Таны мессеж амжилттай илгээгдсэн!",
  "There are no synchronized calendars": "Синхрончлогдсон хуанли байхгүй байна",
  "to view more than 7 events": "7-аас дээш үйл явдлыг үзэх",
  "Mobile app": "Хөдөлгөөнт програм",
  "Admin Account": "Админ данс",
  Password: "Нууц үг",
  "Second User": "Хоёр дахь хэрэглэгч",
  Edit: "Хянан засварлах / хэвлэлд бэлтгэх",
  "Guest limit": "Загварын хязгаар",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Бүх орон нутгийн тохиргоо нь таны хэл дээр үндэслэн (автоматаар) байдаг. Хэрэв таны хэл жагсаалтад байгаа бол энэ хэсгийг өөрчлөх шаардлагагүй.",
  available: "бэлнээр байгаа",
  next: "дараачийн",
  Tickets: "Тасал",
  Quantity: "Тоо хэмжээ",
  "Promo code": "Сурталчилгаа",
  "Select a payment method": "Төлбөрийн аргыг сонгоно уу",
  Fee: "Өртөг шан",
  Book: "Ном",
  "All the tickets have been sold out": "Бүх тасалбар зарагдсан",
  "Choose at least one ticket": "Дор хаяж нэг тийзийг сонгоно уу",
  "First choose ticket": "Эхлээд тийз сонгох",
  "Please fill out your personal information.": "Хувийн мэдээллийг бөглөнө үү.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "Амжилттай худалдан авалт хийхийн тулд өөрийн сонгосон төлбөрийн аргыг сонгоод хямдралтай тасалбарыг оруулна уу.",
  "Credit/Debit card": "Кредит / дебит карт",
  "print here.": "Энд хэвлэ.",
  "QR code for all tickets": "Бүх тасалбарын QR код",
  Duration: "Үргэлжлэх хугацаа",
  "Full Name": "Бүтэн нэр",
  "Ticket id": "Тасалбарын дугаар",
  "Group id": "Багуу үнэмлэх",
  "Choose your ticket.": "Тасалбараа сонгоно уу.",
  "Fill out your personal information.": "Хувийн мэдээллийг бөглөнө үү.",
  "Add the payment details.": "Төлбөрийн дэлгэрэнгүй мэдээллийг нэмнэ үү.",
  "To be determined": "Тодорхойлох",
  "You can find your e-tickets attached to the email or":
    "Та имэйлд хавсаргасан цахим тасалбараа олж болно эсвэл",
  "print here": "энд хэв",
  "Full name": "Бүтэн нэр",
  "Group ID": "Багуу үнэмлэх",
  "to Book": "захиалах",
  "Unfortunately, your card has been declined":
    "Харамсалтай нь, таны карт татгалзсан байна",
  "Thank you for your purchase!": "Худалдан авсанд баярлалаа!",
  "Find your printable e-tickets attached to the confirmation email":
    "Баталгаажуулах имэйлд хавсаргасан цахим тасалбараа олоорой",
  Confirm: "Батлах",

  "Add event": "Галт нэмэх",
  Events: "Галтт хүн",
  "Event details": "Урьдчилхай нөхцөл",
  Registration: "Тэмдэглэл",
  "Guests list": "Загварын жагсаалт",
  Ticket: "Тасалбар",
  "General Info": "Ерөнхий мэдээлэл",
  "Customize the general settings of your event":
    "Таны үйл явдлын ерөнхий тохиргоог өөрчлөх",
  "Event Title": "Арга хэмжээний гарчиг",
  "e.g. Birthday Party": "жишээ нь e. Төрсөн өдрийн үдэшлэг",
  "All Day Event": "Бүх өдрийн арга хэмжээг",
  Cross: "Загалмай",
  Timeline: "Хугацаа",
  "Repeating event": "Давтгаа гүйлгээ",
  Location: "Байрлал",
  "Venue name": "Үйлнэлийн нэр",
  Description: "Тодорхойлолт / төрөл анги",
  Image: "Дүр",
  Color: "Өнгө",
  Category: "Зэрэглэл",
  "Add your events to color categories and let your users classify them easily":
    "Үйл явдлыг өнгөт категориудад нэмж, хэрэглэгчдэд хялбархан ангилдаг",
  "Category name": "Ангийнагны нэр",
  "e.g. Birthdays": "жишээ нь e. Төрсөн өдрийн",
  Venue: "Venue",
  "Where the event takes place": "Арга хэмжээ хаана явагддаг",
  "Venue name": "Үйлнэлийн нэр",
  "Venue phone": "Зоогийн газрын утас",
  "Venue email": "Газар олгох",
  "Venue website": "ТУСГАЙ САЙХАН",
  Organizer: "Цэг хурал",
  "Person who makes the event": "Үйл явдлыг хийдэг хүн",
  "Organizer name": "Зохион байгуулагч Нэр",
  "Organizer phone": "Зохион байгуулагч утас",
  "Organizer email": "Орилохор код",
  "Organizer website": "Зохион байгуулагч вэбсайт",
  Save: "Аврах",
  Cancel: "Цуаах",
  Import: "Импортлох",
  Past: "Урөдах",
  All: "Бүгд",
  Upcoming: "Тогтворнэх",
  Uncategorised: "Ангилагдаагүй",
  "Date Ascending": "ӨӨРИЙГӨӨ ӨӨРИЙГӨӨ ӨӨРЧЛӨЛТ",
  "Date Descending": "Дуудлага буурах",
  "Title by A-Z": "A-Z-ийн гарчиг",
  "Title by Z-A": "Гарчиг нь z-a",
  "There are no events for this period":
    "Энэ хугацаанд ямар ч арга хэмжээ байхгүй байна",

  "Auto-Convert Date & Time": "Автоматаар хөрвүүлэх огноо, цаг",
  TimeZone: "Цагийн бүс",
  Autodeletion: "Autodewnion",
  "Layout Settings": "Зохион байгуулалтын тохиргоо",
  "Yeatly view": "Yeatly харах",
  "Monthly view header": "Сарын харах толгой",
  "Weekly/Daily view header": "Долоо хоног бүр / өдөр тутмын харах толгой",
  Acendings: "Ауталууд",
  Descending: "Урсгал",
  Standart: "Зүйхан гарчиг",
  Silver: "Мөнгө",
  Retro: "Reted",
  Dark: "Бүдүүлэг",
  Night: "Шөнө",
  Aubergine: "Aёgerinny",
  "List view header": "Жагсаалт харах толгойн жагсаалт",
  "Side by Side View": "Хажуу тийш харах",
  "Customize Proportions": "Пропорцийг тохируулах",
  "Card Margins": "Картын тэнхлэг",
  "Image opacity (%)": "Зургийн тунгалаг байдал (%)",
  "Side by Side Header": "Хажуугийн толгойн хажуу талд",
  "Text Align": "Текстийн зэрэгцээ",
  "Timeline View": "Хугацаа харах",
  "Title font color": "Гарчиг үсгийн өнгө",
  "Desciption font color": "ҮНЭГҮЙ ҮНЭГҮЙ ҮНЭГҮЙ",
  "Line color": "Шугамын өнгө",
  "Date Font color": "Огнооны үсгийн өнгө",
  "Daily events background": "Өдөр тутмын үйл явдлууд",
  Alignment: "Тохиролцох",
  Vertical: "Босоо шугам",
  Horizontal: "Хэвтээ",
  "Vertical Alignment": "Босоо чиглэлд",
  Right: "Зөв байх",
  Center: "Тов",
  "Horizontal Alignment": "Хэвтээ чиглүүлэгч",
  Top: "Таг",
  Center: "Тов",
  Bottom: "Ероол",
  "Dates Circle Design": "DATE DILL DIENTION",
  "Next To The Circle": "Тойргийн хажууд",
  "In The Circle": "Тойрог хэсэгт",
  "Timeline Header": "Хугацаа нь",
  Timeline: "Хугацаа",
  "Show only upcoming": "Зөвхөн удахгүй болох шоу",
  "Order by": "Хэмжээ захиал",
  "Timeline Event Limit": "Хугацааны хугацааг хязгаарлах",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Зочинд очиж, орон нутгийн калледедард үйл явдлыг орон нутгийн калледаруудад нэмэхийг зөвшөөрөх",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Зочинд өөрийн үйл явдлыг Facebook, LinkedIn, Twitter болон ETC-д хуваалцахыг зөвшөөрнө үү.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Хүмүүс таны үйл явдлыг хайлтаар хайлт хийхийн тулд Хайлтын сонголтыг нэн даруй, газар, газар гэх мэтээр хайх боломжтой.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Хэрэглэгчид таны хэрэглэгчид таны Boom үйл явдлын хуанлигаа хэвлэхийг зөвшөөрнө үү.",
  "Click to apply a theme to Calendar":
    "Календар руу сэдэвчилсэн сэдвийг дарна уу",
  "Date container color": "ОДОО НЭГДСЭН ШУУД ҮЗЭХ",
  "Daily events background": "Өдөр тутмын үйл явдлууд",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Нэмэлт функцийг өөрийн хуанли дээр суулгахын тулд нэмэлт функцийг ашиглана уу, тэдгээрийг илүү функциональ болгох!",
  "Open Add-ons Store": "Нэмэлт нэмэлт дэлгүүр",
  Monday: "Даваа гариг",
  Tuesday: "Мягмар гариг",
  Wednesday: "Лхагва гараг",
  Thursday: "Пурэв гариг",
  Friday: "Баасан гариг",
  Saturday: "Бямба гараг",
  Sunday: "Ням гариг",
  "Yearly view": "Жилд харах",
  Ascending: "Даваа гариг",
  "Show event time next to title": "Гарчигны хажууд үйл явдлын хугацааг харуул",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Үйл явдлын огноо, цаг хугацаанаас хамааран хэрэглэгчийн цагийн бүсэд суурилсан.",
  "Display the time zone alongside the event date.":
    "Үйл явдлын өдрүүдийн хамт цагийн бүсийг харуул.",
  "Show event time next to title": "Гарчигны хажууд үйл явдлын хугацааг харуул",
  "Time Zone": "Цагийн бүс",
  "Upload Image": "Зургийг байршуулах",
  "Choose a Category": "Ангилал сонгоно уу",
  "Color you have chosen will not be shown as you choose category":
    "Та категорийг сонгохдоо сонгосон өнгийг харуулахгүй",
  Website: "Вэ хэн вэ",
  Next: "Дараачийн",
  Save: "Аврах",
  "Last Name": "Хугацагтай",
  "Personal Info": "Хувийн мэдээлэл",
  Back: "Буцах",
  "This field is required": "Энэ талбар шаардлагатай байна",
  "Your event has been submitted": "Таны үйл явдлыг ирүүлэв",
  "Enter a location": "Бууцгаа оруулах",
  "Display the time zone alongside the event date.":
    "Үйл явдлын өдрүүдийн хамт цагийн бүсийг харуул.",
  Home: "Гэр",
  "Side By Side Event Limit": "Хажуугийн үйл явдлын хязгаарлалт",
  "Mobille App": "Moble App",
  category: "зэрэглэл",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Фэйсбүүкийн үйл явдлуудыг хуанлидаа импортлох замаар цагийн хуваарийг хялбархан хянаж байгаарай.",
  "Synchronized Pages": "Синхрончлогдсон хуудсууд",
  "There are no synchronized pages": "Синхрончлогдсон хуудас байхгүй байна",
  "Choose page": "Хуудсыг сонгоно уу",
  "You have no events": "Танд арга хэмжээ байхгүй байна",
};
export default mn;
