let mr = {
  Categories: "श्रेणी",
  "Share this event": "हा कार्यक्रम सामायिक करा",
  Language: "इंग्रजी",
  "Show Time Zone": "वेळ क्षेत्र दर्शवा",
  "Custom Local Settings": "सानुकूल स्थानिक सेटिंग्ज",
  "Add and showcase events on your site using a beautiful calendar.":
    "एक सुंदर कॅलेंडर वापरुन आपल्या साइटवर इव्हेंट जोडा आणि दर्शवा.",
  "Week Days": "आठवडा दिवस",
  "Manage Events": "कार्यक्रम व्यवस्थापित करा",
  General: "सामान्य",
  "Layout Picker": "लेआउट पिकर",
  Month: "महिना",
  Monthly: "मासिक",
  Week: "आठवडा",
  Weekly: "साप्ताहिक",
  Day: "दिवस",
  Daily: "दररोज",
  Agenda: "अजेंडा",
  "Navigation Buttons": "नेव्हिगेशन बटणे",
  "Week numbers": "आठवडा क्रमांक",
  "Include Weekends": "शनिवार व रविवार समाविष्ट करा",
  "All-day": "संपूर्ण दिवस",
  "All Day": "संपूर्ण दिवस",
  Label: "लेबल",
  "Fit to Height": "उंची फिट",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "अ‍ॅप प्रमाण सेट करण्यासाठी मॅनुली हा पर्याय अक्षम करा आणि संपादकात कॅलेंडरचे आकार बदलवा.",
  "Default Layout": "डीफॉल्ट लेआउट",
  "Monthly view": "मासिक दृश्य",
  "Weekly and Daily view": "साप्ताहिक आणि दैनिक दृश्य",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "आपण अभ्यागतांना एकावेळी समान आठवडे (6) दर्शवून अधिक सुसंगत अनुभव देऊ शकता.",
  "Fixed Weekly Layout": "निश्चित साप्ताहिक लेआउट",
  back: "मागे",
  Row: "पंक्ती",
  "Hours in Weekly View": "साप्ताहिक दृश्यात तास",
  "Hours in Daily View": "दररोजच्या दृश्यात तास",
  Start: "प्रारंभ करा",
  End: "शेवट",
  "At This Hour": "या तासात",
  Button: "बटण",
  Buttons: "बटणे",
  Sunday: "रविवारी",
  Monday: "सोमवार",
  Tuesday: "मंगळवार",
  Wednesday: "बुधवार",
  Thursday: "गुरुवारी",
  Friday: "शुक्रवार",
  Saturday: "शनिवार",
  "Default Date": "डीफॉल्ट तारीख",
  year: "वर्ष",
  month: "महिना",
  mo: "मो",
  days: "दिवस",
  ago: "आधी",
  ahead: "पुढे",
  Yesterday: "काल",
  Today: "आज",
  Tomorrow: "उद्या",
  Custom: "सानुकूल",
  "Set Daily Rows Limit": "दररोज पंक्ती मर्यादा सेट करा",
  "Set Proportions": "प्रमाण सेट करा",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "स्थानिक कॅल्डेनर्समध्ये इव्हेंट जोडण्यासाठी अभ्यागतास अनुमती द्या: Google, याहू, आउटलुक, इकलँडर.",
  Container: "कंटेनर",
  Background: "पार्श्वभूमी",
  "Container Background": "कंटेनर पार्श्वभूमी",
  "Container Borders": "कंटेनर सीमा",
  Calendar: "कॅलेंडर",
  "Event Info Tooltip": "इव्हेंट माहिती टूलटिप",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "जेव्हा लोक एखाद्या इव्हेंटवर फिरतात तेव्हा त्यांना त्याबद्दल सर्व माहिती टूलटिपमध्ये दिसेल.",
  "Event Info Window": "इव्हेंट माहिती विंडो",
  "This is the full information window that opens when someone clicks on the event.":
    "जेव्हा कोणी इव्हेंटवर क्लिक करते तेव्हा ही पूर्ण माहिती विंडो आहे.",
  "Use Gradient": "ग्रेडियंट वापरा",
  Vertical: "अनुलंब",
  Horizontal: "क्षैतिज",
  First: "पहिला",
  Second: "दुसरा",
  diagonal: "कर्ण",
  Radial: "रेडियल",
  "Select option": "पर्याय निवडा",
  Solid: "घन",
  Dotted: "ठिपकेदार",
  Dashed: "तुटक",
  Double: "दुहेरी",
  "Border Radius": "सीमा त्रिज्या",
  Padding: "पॅडिंग",
  "Date Header": "तारीख हेडर",
  "Event Default Color": "इव्हेंट डीफॉल्ट रंग",
  "Days of Week": "आठवड्याचे दिवस",
  "Days of Week Background": "आठवड्यातील पार्श्वभूमीचे दिवस",
  Date: "तारीख",
  "Event Title": "कार्यक्रम शीर्षक",
  "Highlight today": "आज हायलाइट करा",
  "Highlight Color": "हायलाइट रंग",
  Hide: "लपवा",
  "Calendar Border Color": "कॅलेंडर सीमा रंग",
  "Calendar Border Width": "कॅलेंडर बॉर्डर रूंदी",
  "Calendar Border Style": "कॅलेंडर सीमा शैली",
  "Font Color": "फॉन्टचा रंग",
  "Event Background": "कार्यक्रम पार्श्वभूमी",
  "Card Date Color": "कार्ड तारीख रंग",
  "Title Font": "शीर्षक फॉन्ट",
  "Date Font": "तारीख फॉन्ट",
  "Description Font": "वर्णन फॉन्ट",
  "Button Background": "बटण पार्श्वभूमी",
  "Button Text": "बटण मजकूर",
  "Border Color": "सीमा रंग",
  "Border Width": "सीमा रुंदी",
  "Border Type": "सीमा प्रकार",
  Title: "शीर्षक",
  Description: "वर्णन",
  "Background Color": "पार्श्वभूमी रंग",
  Divider: "विभाजक",
  "Event Details Font": "इव्हेंट तपशील फॉन्ट",
  "Website Link Color": "वेबसाइट दुवा रंग",
  "Developer Info": "विकसक माहिती",
  "User Guide": "वापरकर्ता मार्गदर्शक",
  "Support e-mail": "समर्थन ई-मेल",
  "Our Website": "आमची वेबसाइट",
  "App Review": "अॅप पुनरावलोकन",
  "Enjoying App? Leave us a review in the App Market.":
    "अ‍ॅपचा आनंद घेत आहात? आम्हाला अ‍ॅप मार्केटमध्ये पुनरावलोकन सोडा.",
  "Review Us": "आमचे पुनरावलोकन करा",
  "Connect With Us": "आमच्याशी कनेक्ट व्हा",
  "What's your email?": "तुझा ईमेल काय आहे?",
  "Invalid email address!": "अवैध ई - मेल पत्ता!",
  Comments: "टिप्पण्या",
  "We'd love to hear from you. Send us a message.":
    "आम्हाला आपल्याकडून ऐकायला आवडेल. आम्हाला एक संदेश पाठवा.",
  "Message must be at least 5 characters long":
    "संदेश कमीतकमी 5 वर्ण लांब असणे आवश्यक आहे",
  Send: "पाठवा",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "आपण वापरकर्त्यास कॅलेंडर दृश्यांमधील स्विच करण्यास परवानगी देऊ इच्छित असल्यास, हा पर्याय सक्षम करा आणि आपण दर्शवू इच्छित दृश्ये निवडा.",
  Main: "मुख्य",
  Localize: "स्थानिकीकरण",
  Settings: "सेटिंग्ज",
  Layouts: "लेआउट",
  Advanced: "प्रगत",
  Design: "डिझाइन",
  Support: "समर्थन",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "सर्व स्थानिक सेटिंग्ज आपल्या भाषेच्या आधारे (स्वयंचलितपणे) आहेत. आपली भाषा यादीमध्ये असल्यास, हा विभाग सानुकूलित करण्याची आवश्यकता नाही.",
  "Date Format": "दिनांक प्रारुप",
  "Time Format": "वेळ स्वरूप",
  "Text Direction": "मजकूर दिशा",
  "Left to Right": "डावीकडून उजवीकडे",
  "Right to Left": "उजवीकडे डावीकडे",
  "Week Starts On": "आठवडा सुरू होतो",
  "Agenda Style": "अजेंडा शैली",
  Classic: "क्लासिक",
  Modern: "आधुनिक",
  "Agenda Header": "अजेंडा शीर्षलेख",
  "Upcoming Events": "पुढील कार्यक्रम",
  "Agenda Event Limit": "अजेंडा इव्हेंट मर्यादा",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "आता श्रेणीसुधारित करा आणि बरीच वैशिष्ट्ये मिळवा आणि आपल्या अ‍ॅपचा पूर्ण आनंद घ्या!",
  "Upgrade Now": "आता अपग्रेड करा",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "दिवसभर टिकणार्‍या इव्हेंटचे होस्टिंग? हे आपल्याला आपल्या कॅलेंडरवर दर्शवू देते.",
  "24 hours": "24 तास",
  Sat: "शनि",
  Sun: "सूर्य",
  Mon: "सोम",
  Default: "डीफॉल्ट",
  "Select custom design style for your calendar.":
    "आपल्या कॅलेंडरसाठी सानुकूल डिझाइन शैली निवडा.",
  Style: "शैली",
  "Styles and Colors": "शैली आणि रंग",
  "Calendar Name": "कॅलेंडर नाव",
  "Write your Calendar name here": "आपले कॅलेंडर नाव येथे लिहा",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "हे आपल्या वापरकर्त्यांसाठी दृश्यमान नाही. बूम कॅलेंडर समक्रमण फंक्शन वापरताना आपल्या कॅलेंडरमध्ये फरक करण्यासाठी नावे सेट करा.",
  "General Info": "सामान्य माहिती",
  Venue: "ठिकाण",
  Organizer: "आयोजक",
  Search: "शोध",
  "Add to": "जोडू",
  calendar: "कॅलेंडर",
  "Copy event URL": "इव्हेंट URL कॉपी करा",
  "Copied!": "कॉपी!",
  "Add & Share": "जोडा आणि सामायिक करा",
  Map: "नकाशा",
  "Calendar view": "कॅलेंडर दृश्य",
  "Add Event": "कार्यक्रम जोडा",
  Uncategorised: "अवर्गीकृत",
  More: "अधिक",
  Less: "कमी",
  Register: "नोंदणी करा",
  Card: "कार्ड",
  Guests: "अतिथी",
  unlimited: "अमर्यादित",
  "Show more": "अजून दाखवा",
  "Enable Search": "शोध सक्षम करा",
  "+ Add Event": " + कार्यक्रम जोडा",
  "Manage and Sync": "व्यवस्थापित आणि समक्रमित",
  "Show event details as...": "इव्हेंटचा तपशील म्हणून दर्शवा ...",
  Tooltip: "टूलटिप",
  Popup: "पॉपअप",
  None: "काहीही नाही",
  "Show Category": "श्रेणी दर्शवा",
  "Header Align": "शीर्षलेख संरेखित",
  "Show Time": "खेळाची वेळ",
  "Hours in Weekly/Daily View": "साप्ताहिक/दररोजच्या दृश्यात तास",
  "Share Events": "कार्यक्रम सामायिक करा",
  Shadow: "छाया",
  "Inner Padding": "अंतर्गत पॅडिंग",
  Text: "मजकूर",
  "Active Button Border": "सक्रिय बटण सीमा",
  "Light Mode": "प्रकाश मोड",
  "Event Text Color": "कार्यक्रम मजकूर रंग",
  Dates: "तारखा",
  Skeleton: "सांगाडा",
  "Skeleton Color": "सांगाडा रंग",
  Width: "रुंदी",
  "Skeleton Style": "कंकाल शैली",
  Color: "रंग",
  "Section Titles": "विभाग शीर्षके",
  "Section Content": "विभाग सामग्री",
  Header: "शीर्षलेख",
  Standard: "मानक",
  Retro: "रेट्रो",
  Silver: "चांदी",
  Night: "रात्री",
  Dark: "गडद",
  Aubergine: "ऑबर्जिन",
  "Map Header": "नकाशा शीर्षलेख",
  "Show Title in mobile": "मोबाइलमध्ये शीर्षक दर्शवा",
  "Card View": "कार्ड दृश्य",
  "Card background color": "कार्ड पार्श्वभूमी रंग",
  "Title font": "शीर्षक फॉन्ट",
  "Desciption font": "डेसिप्शन फॉन्ट",
  "Section font": "विभाग फॉन्ट",
  "Section divider color": "विभाग विभाजक रंग",
  "Add event": "कार्यक्रम जोडा",
  "All Day Event": "दिवसभर कार्यक्रम",
  Location: "स्थान",
  "Choose a category": "एक श्रेणी निवडा",
  "Venue name": "ठिकाण नाव",
  "Venue phone": "स्थळ फोन",
  "Venue email": "स्थळ ईमेल",
  "Venue website": "स्थळ वेबसाइट",
  "Organizer name": "आयोजक नाव",
  "Organizer phone": "आयोजक फोन",
  "Organizer email": "आयोजक ईमेल",
  "Organizer website": "आयोजक वेबसाइट",
  "Personal info": "वैयक्तिक माहिती",
  "First name": "पहिले नाव",
  "Last name": "आडनाव",
  "Email Address": "ईमेल पत्ता",
  "Additional Notes": "अतीरिक्त नोंदी",
  Back: "मागे",
  Save: "जतन करा",
  Next: "पुढे",
  "Your event has been submitted": "आपला कार्यक्रम सबमिट केला गेला आहे",
  "Event submittion has been failed": "कार्यक्रम सबमिट अयशस्वी झाला आहे",
  "e.g. Birthday Party": "उदा. वाढदिवस पार्टी",
  "First Name": "पहिले नाव",
  "Last Name": "आडनाव",
  "Phone Number": "फोन नंबर",
  Address: "पत्ता",
  "Your comments": "आपली प्रतिक्रिया",
  "How many guests?": "किती अतिथी?",
  "Anything else we need to know?": "आम्हाला इतर काहीही माहित असणे आवश्यक आहे?",
  "Guests:": "अतिथी:",
  Submit: "प्रस्तुत करणे",
  "Go to Calendar": "कॅलेंडरवर जा",
  "Registration completed successfully!": "नोंदणी यशस्वीरित्या पूर्ण झाली!",
  "Please check your registered email address":
    "कृपया आपला नोंदणीकृत ईमेल पत्ता तपासा",
  "Add to Calendar": "कॅलेंडरमध्ये जोडा",
  "Share this Event": "हा कार्यक्रम सामायिक करा",
  "Sorry something went wrong": "माफ करा, काहीतरी चुकलंय",
  "Back to registration": "नोंदणीकडे परत",
  "Date & Location": "तारीख आणि स्थान",
  "Date & Time": "तारीख वेळ",
  home: "मुख्यपृष्ठ",
  "Header align": "शीर्षलेख संरेखित",
  Footer: "तळटीप",
  "Categories Filter": "श्रेणी फिल्टर",
  "Show only upcoming": "फक्त आगामी दर्शवा",
  "Card(s) in a row": "सलग कार्ड",
  "Space between cards": "कार्ड दरम्यान जागा",
  "Shown events limit": "इव्हेंटची मर्यादा दर्शविली",
  "Style 1": "शैली 1",
  "Style 2": "शैली 2",
  "Style 3": "शैली 3",
  "Style 4": "शैली 4",
  "Buttons & Links": "बटणे आणि दुवे",
  "Button corner radius": "बटण कोपरा त्रिज्या",
  "Buttons font": "बटणे फॉन्ट",
  "Buttons background": "बटणे पार्श्वभूमी",
  "Get notified by Email": "ईमेलद्वारे सूचित करा",
  "Review events": "कार्यक्रमांचे पुनरावलोकन करा",
  "Click on date": "तारखेला क्लिक करा",
  "Add Event button": "इव्हेंट बटण जोडा",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "कॅलेंडर समक्रमण आपल्याला आपल्या इव्हेंट्स आणि सत्रांना आपल्या बूम कॅलेंडरसह समाकलित करण्याची परवानगी देते.",
  connect: "कनेक्ट करा",
  "Synchronized Calendars": "सिंक्रोनाइझ कॅलेंडर",
  "Import events": "कार्यक्रम आयात करा",
  Disconnect: "डिस्कनेक्ट",
  "Choose calendar": "कॅलेंडर निवडा",
  "Monitor your Wix events through the sync feature":
    "समक्रमित वैशिष्ट्याद्वारे आपल्या WIX इव्हेंटचे परीक्षण करा",
  "Connect all your Boom calendars available on your website":
    "आपल्या वेबसाइटवर उपलब्ध आपली सर्व बूम कॅलेंडर कनेक्ट करा",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "आमच्या बूम कॅलेंडरद्वारे झूम संमेलनेचे वेळापत्रक, सामील व्हा आणि व्यवस्थापित करा.",
  "Monitor your Event Brite events through the Event Brite sync feature..":
    "इव्हेंट ब्रिट सिंक वैशिष्ट्याद्वारे आपल्या इव्हेंट ब्रिट इव्हेंटचे परीक्षण करा",
  Email: "ईमेल",
  "Add-ons": "-ड-ऑन्स",
  "Receive notification emails as soon as users add events to your calendar.":
    "वापरकर्त्यांनी आपल्या कॅलेंडरमध्ये कार्यक्रम जोडताच सूचना ईमेल प्राप्त करा.",
  "Enable + button on the calendar header":
    "कॅलेंडर शीर्षलेख वर + बटण सक्षम करा",
  "Accept or decline events added by customers before making them public.":
    "ग्राहकांना सार्वजनिक करण्यापूर्वी ग्राहकांनी जोडलेले इव्हेंट स्वीकारा किंवा नाकारणे.",
  "Switch Add Event": "इव्हेंट जोडा",
  "Enable your browser cookies to connect to your account.":
    "आपल्या खात्याशी कनेक्ट होण्यासाठी आपल्या ब्राउझर कुकीज सक्षम करा.",
  "Learn more": "अधिक जाणून घ्या",
  "Print Button": "मुद्रण बटण",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "आपल्या वापरकर्त्यांना कोणत्याही तारखेच्या श्रेणीत आपले बूम इव्हेंट कॅलेंडर मुद्रित करण्याची परवानगी द्या.",
  "Show Title on mobile": "मोबाइलवर शीर्षक दर्शवा",
  "Show Skeleton on mobile": "मोबाइलवर सांगाडा दर्शवा",
  "Start 7-day Business trial": "7-दिवसांचा व्यवसाय चाचणी प्रारंभ करा",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "विक्रीची तिकिटे, नोंदणी, अभ्यागत इव्हेंट अ‍ॅड-ऑन्स यासारख्या सर्व अमर्याद वैशिष्ट्यांचा आनंद घ्या.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "कृपया लक्षात ठेवा: चाचणी कालावधीच्या शेवटी, आपल्याला आपल्या विद्यमान सदस्यता योजनेत परत केले जाईल.",
  "Not Now": "आता नाही",
  "Start free trial": "विनामूल्य चाचणी सुरू करा",
  "Congrats!": "अभिनंदन!",
  "Your 7-day Business trial has been successfully activated.":
    "आपली 7-दिवसांची व्यवसाय चाचणी यशस्वीरित्या सक्रिय केली गेली आहे.",
  Done: "पूर्ण झाले",
  "Title font color": "शीर्षक फॉन्ट रंग",
  "Desciption font color": "डेसिप्शन फॉन्ट रंग",
  "Section font color": "विभाग फॉन्ट रंग",
  "Card Header": "कार्ड शीर्षलेख",
  Category: "वर्ग",
  "Display at the": "येथे प्रदर्शन",
  top: "शीर्ष",
  bottom: "तळ",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "शीर्षस्थानी किंवा कॅलेंडरच्या तळाशी श्रेणी फिल्टर दर्शवा. सेटिंग्ज केवळ अजेंडा आणि कार्ड दृश्यांवर लागू आहेत",
  "Processing your events": "आपल्या इव्हेंटवर प्रक्रिया करीत आहे",
  "Search for events": "कार्यक्रम शोधा",
  "There are no events added": "तेथे कोणतेही कार्यक्रम जोडले जात नाहीत",
  "Location: To be determined": "स्थानः निश्चित करणे",
  "No events for selected date": "निवडलेल्या तारखेसाठी कोणतेही कार्यक्रम नाहीत",
  Uncategorized: "अवर्गीकृत",
  "Edit event": "कार्यक्रम संपादित करा",
  "Edit original event": "मूळ कार्यक्रम संपादित करा",
  "Copy event": "कॉपी इव्हेंट",
  "Copy as new event": "नवीन कार्यक्रम म्हणून कॉपी करा",
  "Delete event": "कार्यक्रम हटवा",
  "Stop repeating on this date": "या तारखेला पुनरावृत्ती करणे थांबवा",
  "Exclude this date": "ही तारीख वगळा",
  "Location is going to be announced": "स्थान जाहीर केले जाईल",
  "Fill your personal information": "आपली वैयक्तिक माहिती भरा",
  "Check Box": "चेक बॉक्स",
  "Single Choice": "एकल निवड",
  Option: "पर्याय",
  "Share Event": "कार्यक्रम सामायिक करा",
  "Oops! Something went wrong": "अरेरे! काहीतरी चूक झाली",
  "We are sorry this event has already taken place":
    "आम्ही दिलगीर आहोत की हा कार्यक्रम आधीच झाला आहे",
  "Back to calendar": "कॅलेंडरकडे परत",
  "This field is required": "हे क्षेत्र आवश्यक आहे",
  Phone: "फोन",
  "Number field": "क्रमांक फील्ड",
  "Please provide a valid email": "कृपया एक वैध ईमेल प्रदान करा",
  "Select at least one option": "कमीतकमी एक पर्याय निवडा",
  "Choose tickets to see total value": "एकूण मूल्य पाहण्यासाठी तिकिटे निवडा",
  tickets: "तिकिटे",
  "Choose Tickets": "तिकिटे निवडा",
  "Choose payment method": "देयक पद्धत निवडा",
  Pay: "वेतन",
  Total: "एकूण",
  Free: "फुकट",
  "Buy tickets": "तिकीट खरेदी कर",
  "Sold Out": "विकले",
  "Tickets are available": "तिकिटे उपलब्ध आहेत",
  "Sales End": "विक्री समाप्त",
  "Availible from": "पासून उपलब्ध",
  "Go to Orders": "ऑर्डरवर जा",
  "Go to Details": "तपशील वर जा",
  "Group ticket": "गट तिकीट",
  Name: "नाव",
  Price: "किंमत",
  "Order by": "च्या आदेशाने",
  "Order ID": "ऑर्डर आयडी",
  Applied: "लागू",
  Fees: "फी",
  "Enter promo code": "प्रोमो कोड प्रविष्ट करा",
  Apply: "अर्ज करा",
  "Promo Code": "प्रोमो कोड",
  Cash: "रोख",
  "You can find your e-tickets attached to your email or download them":
    "आपण आपल्या ईमेलला जोडलेले आपले ई-तिकिटे शोधू शकता किंवा त्यांना डाउनलोड करू शकता",
  here: "येथे",
  Time: "वेळ",
  "Invalid promo code": "अवैध प्रोमो कोड",
  "Credit card": "क्रेडीट कार्ड",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "आपल्याला लवकरच आपल्या ईमेल पत्त्यावर यशस्वी नोंदणीचा ​​एक पुष्टीकरण संदेश प्राप्त होईल.",
  "You can also check your order details below.":
    "आपण खाली आपल्या ऑर्डरचा तपशील देखील तपासू शकता.",
  at: "वर",
  Buy: "खरेदी",
  Donation: "देणगी",
  "Enter price": "किंमत प्रविष्ट करा",
  Choose: "निवडा",
  Chosen: "निवडलेले",
  "Choose your plan": "आपली योजना निवडा",
  week: "आठवडा",
  wk: "डब्ल्यूके",
  "Choose plan cycle": "योजना चक्र निवडा",
  months: "महिने",
  years: "वर्षे",
  weeks: "आठवडे",
  "Copy Event Url": "इव्हेंट URL कॉपी करा",
  "You can find your e-tickets attached to your email or print them":
    "आपण आपल्या ईमेलला जोडलेले आपले ई-तिकिटे शोधू शकता किंवा त्यांना मुद्रित करू शकता",
  "Guest Info": "अतिथी माहिती",
  "Ticket Info": "तिकिट माहिती",
  "Ticket name": "तिकिट नाव",
  "Ticket price": "तिकिट किंमत",
  "Ticket ID": "तिकिट आयडी",
  "If you have any questions contact to organizer":
    "आपल्याकडे काही प्रश्न असल्यास आयोजकांशी संपर्क साधा",
  "As soon as event ends": "कार्यक्रम संपताच",
  "1 day after event ends": "कार्यक्रम संपल्यानंतर 1 दिवस",
  "7 days after event ends": "कार्यक्रम संपल्यानंतर 7 दिवस",
  "14 days after event ends": "कार्यक्रम संपल्यानंतर 14 दिवसानंतर",
  "30 days after event ends": "इव्हेंट संपल्यानंतर 30 दिवसानंतर",
  Menu: "मेनू",
  "No event for selected date": "निवडलेल्या तारखेसाठी कोणताही कार्यक्रम नाही",
  view: "दृश्य",
  List: "यादी",
  Year: "वर्ष",
  Yearly: "वार्षिक",
  "Year view header": "वर्ष पहा शीर्षलेख",
  "Yearly Style": "वार्षिक शैली",
  "There are no events": "तेथे कोणतेही कार्यक्रम नाहीत",
  Autotranslation: "ऑटोट्रांसलेशन",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "एकदा सक्षम झाल्यानंतर, आपले कॅलेंडर विजेट वेबसाइटच्या भाषेच्या आधारे भाषांतरित केले जाईल. *लक्षात घ्या की जोपर्यंत कॅलेंडर शीर्षक आणि वर्णन इनपुट केलेले मजकूर आहेत ज्यांचे भाषांतर केले जाऊ शकत नाही.",
  "Note on mobile": "मोबाइलवर टीप",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "कॅलेंडरच्या मोबाइल आवृत्तीवरील “नो इव्हेंट्स” बारचा मजकूर बंद करा किंवा बदला",
  Autodeletion: "ऑटोडलेशन",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "पर्याय सक्षम करणे, आपल्या मागील इव्हेंट्स आपोआप कॅलेंडरमधून काढून टाकेल.",
  "This does not apply to repeating events!":
    "हे पुनरावृत्ती इव्हेंटवर लागू होत नाही!",
  "Notify event creators about the guest":
    "अतिथीबद्दल कार्यक्रम निर्मात्यांना सूचित करा",
  "Send event creators notification emails as soon as guests register for their events":
    "अतिथी त्यांच्या इव्हेंटसाठी नोंदणी करताच इव्हेंट क्रिएटर्स अधिसूचना ईमेल पाठवा",
  "List View Type": "सूची दृश्य प्रकार",
  "Description font": "वर्णन फॉन्ट",
  Connect: "कनेक्ट करा",
  "You have no events": "आपल्याकडे कोणतेही कार्यक्रम नाहीत",
  Synchronize: "समक्रमित",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Google कॅलेंडर समक्रमण आपल्याला आपल्या इव्हेंट्स आणि सत्रांना आपल्या बूम कॅलेंडरसह समाकलित करण्याची परवानगी देते.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "आउटलुक कॅलेंडर समक्रमण आपल्याला आपल्या इव्हेंट्स आणि सत्रांना आपल्या बूम कॅलेंडरसह समाकलित करण्याची परवानगी देते.",
  "Your message has been sent successfully!":
    "आपला संदेश यशस्वीरित्या पाठविला गेला आहे!",
  "There are no synchronized calendars": "कोणतीही सिंक्रोनाइज्ड कॅलेंडर नाहीत",
  "to view more than 7 events": "7 पेक्षा जास्त कार्यक्रम पाहण्यासाठी",
  "Mobile app": "मोबाइल अॅप",
  "Admin Account": "प्रशासन खाते",
  Password: "संकेतशब्द",
  "Second User": "दुसरा वापरकर्ता",
  Edit: "सुधारणे",
  "Guest limit": "अतिथी मर्यादा",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "सर्व स्थानिक सेटिंग्ज आपल्या भाषेच्या आधारे (स्वयंचलितपणे) आहेत. आपली भाषा यादीमध्ये असल्यास, हा विभाग सानुकूलित करण्याची आवश्यकता नाही.",
  available: "उपलब्ध",
  next: "पुढे",
  Tickets: "तिकिटे",
  Quantity: "प्रमाण",
  "Promo code": "प्रोमो कोड",
  "Select a payment method": "देयक पद्धत निवडा",
  Fee: "फी",
  Book: "पुस्तक",
  "All the tickets have been sold out": "सर्व तिकिटे विकली गेली आहेत",
  "Choose at least one ticket": "कमीतकमी एक तिकिट निवडा",
  "First choose ticket": "प्रथम तिकिट निवडा",
  "Please fill out your personal information.":
    "कृपया आपली वैयक्तिक माहिती भरा.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "यशस्वी खरेदी करण्यासाठी, कृपया आपली पसंतीची पेमेंट पद्धत निवडा आणि सवलतीच्या तिकिटांसाठी प्रोमो कोड प्रविष्ट करा.",
  "Credit/Debit card": "क्रेडिट/डेबिट कार्ड",
  "print here.": "येथे मुद्रित करा.",
  "QR code for all tickets": "सर्व तिकिटांसाठी क्यूआर कोड",
  Duration: "कालावधी",
  "Full Name": "पूर्ण नाव",
  "Ticket id": "तिकिट आयडी",
  "Group id": "गट आयडी",
  "Choose your ticket.": "आपले तिकीट निवडा.",
  "Fill out your personal information.": "आपली वैयक्तिक माहिती भरा.",
  "Add the payment details.": "देय तपशील जोडा.",
  "To be determined": "निर्धारित करणे",
  "You can find your e-tickets attached to the email or":
    "आपण ईमेलला जोडलेले आपले ई-तिकिटे शोधू शकता किंवा",
  "print here": "येथे मुद्रित करा",
  "Full name": "पूर्ण नाव",
  "Group ID": "गट आयडी",
  "to Book": "बुक करण्यासाठी",
  "Unfortunately, your card has been declined":
    "दुर्दैवाने, आपले कार्ड नाकारले गेले आहे",
  "Thank you for your purchase!": "आपल्या खरेदीबद्दल धन्यवाद!",
  "Find your printable e-tickets attached to the confirmation email":
    "पुष्टीकरण ईमेलला संलग्न आपले मुद्रणयोग्य ई-तिकिटे शोधा",
  Confirm: "पुष्टी",

  "Add event": "कार्यक्रम जोडा",
  Events: "घटना",
  "Event details": "कार्यक्रमाचा तपशील",
  Registration: "नोंदणी",
  "Guests list": "अतिथींची यादी",
  Ticket: "तिकिट",
  "General Info": "सामान्य माहिती",
  "Customize the general settings of your event":
    "आपल्या इव्हेंटच्या सामान्य सेटिंग्ज सानुकूलित करा",
  "Event Title": "कार्यक्रम शीर्षक",
  "e.g. Birthday Party": "उदा. वाढदिवस पार्टी",
  "All Day Event": "दिवसभर कार्यक्रम",
  Cross: "फुली",
  Timeline: "टाइमलाइन",
  "Repeating event": "पुनरावृत्ती कार्यक्रम",
  Location: "स्थान",
  "Venue name": "ठिकाण नाव",
  Description: "वर्णन",
  Image: "प्रतिमा",
  Color: "रंग",
  Category: "वर्ग",
  "Add your events to color categories and let your users classify them easily":
    "रंग श्रेणींमध्ये आपले इव्हेंट जोडा आणि आपल्या वापरकर्त्यांना त्यांचे सहज वर्गीकरण करू द्या",
  "Category name": "श्रेणी नाव",
  "e.g. Birthdays": "उदा. वाढदिवस",
  Venue: "ठिकाण",
  "Where the event takes place": "जेथे कार्यक्रम होतो",
  "Venue name": "ठिकाण नाव",
  "Venue phone": "स्थळ फोन",
  "Venue email": "स्थळ ईमेल",
  "Venue website": "स्थळ वेबसाइट",
  Organizer: "आयोजक",
  "Person who makes the event": "जो इव्हेंट बनवितो",
  "Organizer name": "आयोजक नाव",
  "Organizer phone": "आयोजक फोन",
  "Organizer email": "आयोजक ईमेल",
  "Organizer website": "आयोजक वेबसाइट",
  Save: "जतन करा",
  Cancel: "रद्द करा",
  Import: "आयात",
  Past: "भूतकाळ",
  All: "सर्व",
  Upcoming: "आगामी",
  Uncategorised: "अवर्गीकृत",
  "Date Ascending": "तारीख चढता",
  "Date Descending": "तारीख उतरणारी तारीख",
  "Title by A-Z": "ए-झेड द्वारे शीर्षक",
  "Title by Z-A": "झेड-ए द्वारे शीर्षक",
  "There are no events for this period":
    "या कालावधीसाठी कोणतेही कार्यक्रम नाहीत",

  "Auto-Convert Date & Time": "स्वयं-रूपांतरित तारीख आणि वेळ",
  TimeZone: "वेळ क्षेत्र",
  Autodeletion: "ऑटोडलेशन",
  "Layout Settings": "लेआउट सेटिंग्ज",
  "Yeatly view": "येटली पहा",
  "Monthly view header": "मासिक दृश्य शीर्षलेख",
  "Weekly/Daily view header": "साप्ताहिक/दैनिक दृश्य शीर्षलेख",
  Acendings: "Edendings",
  Descending: "उतरत्या",
  Standart: "स्टँडार्ट",
  Silver: "चांदी",
  Retro: "रेट्रो",
  Dark: "गडद",
  Night: "रात्री",
  Aubergine: "ऑबर्जिन",
  "List view header": "सूची शीर्षलेख",
  "Side by Side View": "साइड बाय साइड व्ह्यू",
  "Customize Proportions": "प्रमाण सानुकूलित करा",
  "Card Margins": "कार्ड मार्जिन",
  "Image opacity (%)": "प्रतिमा अस्पष्टता (%)",
  "Side by Side Header": "शेजारी शेजारी हेडर",
  "Text Align": "मजकूर संरेखित",
  "Timeline View": "टाइमलाइन दृश्य",
  "Title font color": "शीर्षक फॉन्ट रंग",
  "Desciption font color": "डेसिप्शन फॉन्ट रंग",
  "Line color": "ओळ रंग",
  "Date Font color": "तारीख फॉन्ट रंग",
  "Daily events background": "दैनंदिन घटना पार्श्वभूमी",
  Alignment: "संरेखन",
  Vertical: "अनुलंब",
  Horizontal: "क्षैतिज",
  "Vertical Alignment": "अनुलंब संरेखन",
  Right: "बरोबर",
  Center: "मध्य",
  "Horizontal Alignment": "क्षैतिज संरेखन",
  Top: "शीर्ष",
  Center: "मध्य",
  Bottom: "तळ",
  "Dates Circle Design": "तारखा मंडळ डिझाइन",
  "Next To The Circle": "मंडळाच्या पुढे",
  "In The Circle": "वर्तुळात",
  "Timeline Header": "टाइमलाइन शीर्षलेख",
  Timeline: "टाइमलाइन",
  "Show only upcoming": "फक्त आगामी दर्शवा",
  "Order by": "च्या आदेशाने",
  "Timeline Event Limit": "टाइमलाइन इव्हेंट मर्यादा",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "स्थानिक कॅल्डेनर्समध्ये इव्हेंट जोडण्यासाठी अभ्यागतास अनुमती द्या: Google, याहू, आउटलुक, इलेंडर.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "आपला कार्यक्रम फेसबुक, लिंक्डइन, ट्विटर इ. मध्ये सामायिक करण्यास अभ्यागतास अनुमती द्या",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "लोकांना शीर्षक, ठिकाण, इत्यादीद्वारे आपल्या इव्हेंट्स शोधू देण्यासाठी आपल्या कॅलेंडरवर शोध पर्याय जोडा.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "आपल्या वापरकर्त्यांना कोणत्याही तारखेच्या श्रेणीत आपले बूम इव्हेंट कॅलेंडर मुद्रित करण्याची परवानगी द्या.",
  "Click to apply a theme to Calendar":
    "कॅलेंडरवर थीम लागू करण्यासाठी क्लिक करा",
  "Date container color": "तारीख कंटेनर रंग",
  "Daily events background": "दैनंदिन घटना पार्श्वभूमी",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "आपल्या कॅलेंडरवर प्रगत वैशिष्ट्ये स्थापित करण्यासाठी अ‍ॅड-ऑन्स वापरा, त्या अधिक कार्यशील बनवा!",
  "Open Add-ons Store": "अ‍ॅड-ऑन्स स्टोअर उघडा",
  Monday: "सोमवार",
  Tuesday: "मंगळवार",
  Wednesday: "बुधवार",
  Thursday: "गुरुवारी",
  Friday: "शुक्रवार",
  Saturday: "शनिवार",
  Sunday: "रविवारी",
  "Yearly view": "वार्षिक दृश्य",
  Ascending: "चढत्या",
  "Show event time next to title": "शीर्षकाच्या पुढे इव्हेंट वेळ दर्शवा",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "त्यांच्या टाइम झोनच्या आधारे वापरकर्त्याच्या स्थानिक वेळेमध्ये इव्हेंटची तारीख आणि वेळ समायोजित करा.",
  "Display the time zone alongside the event date.":
    "कार्यक्रमाच्या तारखेसह टाइम झोन प्रदर्शित करा.",
  "Show event time next to title": "शीर्षकाच्या पुढे इव्हेंट वेळ दर्शवा",
  "Time Zone": "वेळ क्षेत्र",
  "Upload Image": "प्रतिमा अपलोड करा",
  "Choose a Category": "एक श्रेणी निवडा",
  "Color you have chosen will not be shown as you choose category":
    "आपण निवडलेला रंग दर्शविला जाणार नाही",
  Website: "संकेतस्थळ",
  Next: "पुढे",
  Save: "जतन करा",
  "Last Name": "आडनाव",
  "Personal Info": "वैयक्तिक माहिती",
  Back: "मागे",
  "This field is required": "हे क्षेत्र आवश्यक आहे",
  "Your event has been submitted": "आपला कार्यक्रम सबमिट केला गेला आहे",
  "Enter a location": "एक स्थान प्रविष्ट करा",
  "Display the time zone alongside the event date.":
    "कार्यक्रमाच्या तारखेसह टाइम झोन प्रदर्शित करा.",
  Home: "मुख्यपृष्ठ",
  "Side By Side Event Limit": "साइड बाय साइड इव्हेंट मर्यादा",
  "Mobille App": "मोबिल अॅप",
  category: "वर्ग",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "तुमच्या कॅलेंडरमध्ये तुमचे Facebook इव्हेंट इंपोर्ट करून तुमच्या शेड्यूलचा सहज मागोवा ठेवा.",
  "Synchronized Pages": "सिंक्रोनाइझ केलेली पृष्ठे",
  "There are no synchronized pages": "कोणतीही समक्रमित पृष्ठे नाहीत",
  "Choose page": "पृष्ठ निवडा",
  "You have no events": "आपल्याकडे कोणतेही कार्यक्रम नाहीत",
};
export default mr;
