let ms = {
  Categories: "Kategori",
  "Share this event": "Kongsi acara ini",
  Language: "Bahasa",
  "Show Time Zone": "Tunjukkan zon waktu",
  "Custom Local Settings": "Tetapan tempatan tersuai",
  "Add and showcase events on your site using a beautiful calendar.":
    "Tambah dan tunjukkan acara di laman web anda menggunakan kalendar yang indah.",
  "Week Days": "Hari minggu",
  "Manage Events": "Menguruskan acara",
  General: "Umum",
  "Layout Picker": "Pemetik susun atur",
  Month: "Bulan",
  Monthly: "Bulanan",
  Week: "Minggu",
  Weekly: "Setiap minggu",
  Day: "Hari",
  Daily: "Setiap hari",
  Agenda: "Agenda",
  "Navigation Buttons": "Butang navigasi",
  "Week numbers": "Nombor minggu",
  "Include Weekends": "Sertakan hujung minggu",
  "All-day": "Sepanjang hari",
  "All Day": "Sepanjang hari",
  Label: "Label",
  "Fit to Height": "Sesuai dengan ketinggian",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Untuk menetapkan perkadaran aplikasi secara manully melumpuhkan pilihan ini dan mengubah saiz kalendar dalam editor.",
  "Default Layout": "Susun atur lalai",
  "Monthly view": "Pandangan bulanan",
  "Weekly and Daily view": "Pandangan Mingguan dan Harian",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Anda boleh memberi pengunjung pengalaman yang lebih konsisten dengan menunjukkan bilangan minggu yang sama (6) pada satu masa.",
  "Fixed Weekly Layout": "Susun atur mingguan tetap",
  back: "Kembali",
  Row: "Baris",
  "Hours in Weekly View": "Jam dalam paparan mingguan",
  "Hours in Daily View": "Jam dalam pandangan harian",
  Start: "Mula",
  End: "Akhir",
  "At This Hour": "Pada jam ini",
  Button: "Butang",
  Buttons: "Butang",
  Sunday: "Ahad",
  Monday: "Isnin",
  Tuesday: "Selasa",
  Wednesday: "Rabu",
  Thursday: "Khamis",
  Friday: "Jumaat",
  Saturday: "Sabtu",
  "Default Date": "Tarikh lalai",
  year: "tahun",
  month: "bulan",
  mo: "mo",
  days: "hari",
  ago: "yang lalu",
  ahead: "di hadapan",
  Yesterday: "Semalam",
  Today: "Hari ini",
  Tomorrow: "Esok",
  Custom: "Adat",
  "Set Daily Rows Limit": "Tetapkan had baris harian",
  "Set Proportions": "Tetapkan perkadaran",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Benarkan pengunjung menambah acara ke Calnedars tempatan: Google, Yahoo, Outlook, icalendar.",
  Container: "Bekas",
  Background: "Latar belakang",
  "Container Background": "Latar belakang kontena",
  "Container Borders": "Sempadan kontena",
  Calendar: "Kalendar",
  "Event Info Tooltip": "Petua Maklumat Acara",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Apabila orang melayang ke atas peristiwa, mereka akan melihat semua maklumat mengenainya dalam tooltip.",
  "Event Info Window": "Tetingkap Maklumat Acara",
  "This is the full information window that opens when someone clicks on the event.":
    "Ini adalah tetingkap maklumat penuh yang dibuka apabila seseorang mengklik pada acara tersebut.",
  "Use Gradient": "Gunakan kecerunan",
  Vertical: "Menegak",
  Horizontal: "Mendatar",
  First: "Pertama",
  Second: "Kedua",
  diagonal: "pepenjuru",
  Radial: "Radial",
  "Select option": "Pilih pilihan",
  Solid: "Pepejal",
  Dotted: "Dotted",
  Dashed: "Putus -putus",
  Double: "Ganda",
  "Border Radius": "Jejari sempadan",
  Padding: "Padding",
  "Date Header": "Header Tarikh",
  "Event Default Color": "Warna lalai acara",
  "Days of Week": "Hari dalam minggu",
  "Days of Week Background": "Latar Belakang Hari Minggu",
  Date: "Tarikh",
  "Event Title": "Tajuk Acara",
  "Highlight today": "Sorot hari ini",
  "Highlight Color": "Sorot warna",
  Hide: "Sembunyikan",
  "Calendar Border Color": "Warna sempadan kalendar",
  "Calendar Border Width": "Lebar sempadan kalendar",
  "Calendar Border Style": "Gaya sempadan kalendar",
  "Font Color": "Warna fon",
  "Event Background": "Latar belakang acara",
  "Card Date Color": "Warna tarikh kad",
  "Title Font": "Font tajuk",
  "Date Font": "Font tarikh",
  "Description Font": "Penerangan Font",
  "Button Background": "Latar belakang butang",
  "Button Text": "Teks butang",
  "Border Color": "Warna sempadan",
  "Border Width": "Lebar sempadan",
  "Border Type": "Jenis Sempadan",
  Title: "Tajuk",
  Description: "Penerangan",
  "Background Color": "Warna latar belakang",
  Divider: "Pembahagi",
  "Event Details Font": "Font Butiran Acara",
  "Website Link Color": "Warna pautan laman web",
  "Developer Info": "Maklumat pemaju",
  "User Guide": "Panduan pengguna",
  "Support e-mail": "Sokongan E-mel",
  "Our Website": "Laman web kami",
  "App Review": "Kajian App",
  "Enjoying App? Leave us a review in the App Market.":
    "Menikmati aplikasi? Tinggalkan kami semakan di pasaran aplikasi.",
  "Review Us": "Semak kami",
  "Connect With Us": "Berhubung dengan kami",
  "What's your email?": "Apa e -mel anda?",
  "Invalid email address!": "Alamat email tidak sah!",
  Comments: "Komen",
  "We'd love to hear from you. Send us a message.":
    "Kami ingin mendengar daripada anda. Hantarkan mesej kepada kami.",
  "Message must be at least 5 characters long":
    "Mesej mestilah sekurang -kurangnya 5 aksara",
  Send: "Hantar",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Jika anda ingin membenarkan pengguna menukar antara pandangan kalendar, aktifkan pilihan ini dan pilih pandangan yang ingin anda tunjukkan.",
  Main: "Utama",
  Localize: "Melokalisasikan",
  Settings: "Tetapan",
  Layouts: "Susun atur",
  Advanced: "Lanjutan",
  Design: "Reka bentuk",
  Support: "Sokongan",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Semua tetapan tempatan adalah (secara automatik) berdasarkan bahasa anda. Jika bahasa anda berada dalam senarai, tidak perlu menyesuaikan bahagian ini.",
  "Date Format": "Format tarikh",
  "Time Format": "Format masa",
  "Text Direction": "Arah teks",
  "Left to Right": "Kiri ke kanan",
  "Right to Left": "Kanan ke kiri",
  "Week Starts On": "Minggu bermula",
  "Agenda Style": "Gaya Agenda",
  Classic: "Klasik",
  Modern: "Moden",
  "Agenda Header": "Header Agenda",
  "Upcoming Events": "Aktiviti yang akan datang",
  "Agenda Event Limit": "Had acara agenda",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Naik taraf sekarang dan dapatkan lebih banyak ciri dan nikmati aplikasi anda sepenuhnya!",
  "Upgrade Now": "Menaiktaraf sekarang",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Menganjurkan acara yang berlangsung sepanjang hari? Ini membolehkan anda menunjukkan kepada mereka pada kalendar anda.",
  "24 hours": "24 jam",
  Sat: "Duduk",
  Sun: "matahari",
  Mon: "Mon",
  Default: "Lalai",
  "Select custom design style for your calendar.":
    "Pilih gaya reka bentuk tersuai untuk kalendar anda.",
  Style: "Gaya",
  "Styles and Colors": "Gaya dan warna",
  "Calendar Name": "Nama kalendar",
  "Write your Calendar name here": "Tulis nama kalendar anda di sini",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Ini tidak dapat dilihat oleh pengguna anda. Tetapkan nama untuk membezakan kalendar anda apabila menggunakan fungsi penyegerakan kalendar boom.",
  "General Info": "Maklumat umum",
  Venue: "Tempat",
  Organizer: "Penganjur",
  Search: "Cari",
  "Add to": "Tambah ke",
  calendar: "kalendar",
  "Copy event URL": "Salin url acara",
  "Copied!": "Disalin!",
  "Add & Share": "Tambah & kongsi",
  Map: "Peta",
  "Calendar view": "Pandangan kalendar",
  "Add Event": "Tambah acara",
  Uncategorised: "Tidak dikategorikan",
  More: "Lebih",
  Less: "Kurang",
  Register: "Daftar",
  Card: "Kad",
  Guests: "Tetamu",
  unlimited: "tidak terhad",
  "Show more": "Tunjukkan lebih banyak",
  "Enable Search": "Dayakan carian",
  "+ Add Event": " + Tambah acara",
  "Manage and Sync": "Mengurus dan menyegerakkan",
  "Show event details as...": "Tunjukkan butiran acara sebagai ...",
  Tooltip: "Tooltip",
  Popup: "Popup",
  None: "Tiada",
  "Show Category": "Tunjukkan kategori",
  "Header Align": "Header Align",
  "Show Time": "Masa pertunjukan",
  "Hours in Weekly/Daily View": "Jam dalam pandangan mingguan/harian",
  "Share Events": "Kongsi acara",
  Shadow: "Bayangan",
  "Inner Padding": "Padding dalaman",
  Text: "Teks",
  "Active Button Border": "Sempadan butang aktif",
  "Light Mode": "Mod cahaya",
  "Event Text Color": "Warna teks acara",
  Dates: "Tarikh",
  Skeleton: "Rangka",
  "Skeleton Color": "Warna rangka",
  Width: "Lebar",
  "Skeleton Style": "Gaya Skeleton",
  Color: "Warna",
  "Section Titles": "Tajuk Seksyen",
  "Section Content": "Kandungan seksyen",
  Header: "Kepala",
  Standard: "Standard",
  Retro: "Retro",
  Silver: "Perak",
  Night: "Malam",
  Dark: "Gelap",
  Aubergine: "Terung",
  "Map Header": "Header Map",
  "Show Title in mobile": "Tunjukkan Tajuk dalam Mudah Alih",
  "Card View": "Paparan kad",
  "Card background color": "Warna latar belakang kad",
  "Title font": "Font tajuk",
  "Desciption font": "Font desciption",
  "Section font": "Font Seksyen",
  "Section divider color": "Warna pembahagi bahagian",
  "Add event": "Tambah acara",
  "All Day Event": "Acara sepanjang hari",
  Location: "Lokasi",
  "Choose a category": "Pilih Kategori",
  "Venue name": "Nama tempat",
  "Venue phone": "Telefon Tempat",
  "Venue email": "E -mel tempat",
  "Venue website": "Laman web tempat",
  "Organizer name": "Nama penganjur",
  "Organizer phone": "Telefon penganjur",
  "Organizer email": "E -mel penganjur",
  "Organizer website": "Laman web penganjur",
  "Personal info": "Maklumat peribadi",
  "First name": "Nama pertama",
  "Last name": "Nama terakhir",
  "Email Address": "Alamat emel",
  "Additional Notes": "Nota tambahan",
  Back: "Kembali",
  Save: "Simpan",
  Next: "Seterusnya",
  "Your event has been submitted": "Acara anda telah dihantar",
  "Event submittion has been failed": "Penyerahan acara telah gagal",
  "e.g. Birthday Party": "mis. Parti hari lahir",
  "First Name": "Nama pertama",
  "Last Name": "Nama terakhir",
  "Phone Number": "Nombor telefon",
  Address: "Alamat",
  "Your comments": "Komen anda",
  "How many guests?": "Berapa banyak tetamu?",
  "Anything else we need to know?": "Ada perkara lain yang perlu kita ketahui?",
  "Guests:": "Tetamu:",
  Submit: "Hantar",
  "Go to Calendar": "Pergi ke kalendar",
  "Registration completed successfully!": "Pendaftaran selesai dengan jayanya!",
  "Please check your registered email address":
    "Sila periksa alamat e -mel berdaftar anda",
  "Add to Calendar": "Tambah ke kalendar",
  "Share this Event": "Kongsi acara ini",
  "Sorry something went wrong": "Maaf, sesuatu telah berlaku",
  "Back to registration": "Kembali ke pendaftaran",
  "Date & Location": "Tarikh & Lokasi",
  "Date & Time": "Masa tarikh",
  home: "rumah",
  "Header align": "Header Align",
  Footer: "Footer",
  "Categories Filter": "Penapis kategori",
  "Show only upcoming": "Hanya menunjukkan yang akan datang",
  "Card(s) in a row": "Kad berturut -turut",
  "Space between cards": "Ruang antara kad",
  "Shown events limit": "Had peristiwa yang ditunjukkan",
  "Style 1": "Gaya 1",
  "Style 2": "Gaya 2",
  "Style 3": "Gaya 3",
  "Style 4": "Gaya 4",
  "Buttons & Links": "Butang & Pautan",
  "Button corner radius": "Jejari sudut butang",
  "Buttons font": "Font Butang",
  "Buttons background": "Latar belakang butang",
  "Get notified by Email": "Dapatkan diberitahu melalui e -mel",
  "Review events": "Mengkaji semula acara",
  "Click on date": "Klik pada tarikh",
  "Add Event button": "Tambahkan butang Acara",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Penyegerakan kalendar membolehkan anda mengintegrasikan acara dan sesi anda dengan kalendar boom anda.",
  connect: "Sambung",
  "Synchronized Calendars": "Kalendar yang disegerakkan",
  "Import events": "Acara import",
  Disconnect: "Putus",
  "Choose calendar": "Pilih kalendar",
  "Monitor your Wix events through the sync feature":
    "Pantau acara Wix anda melalui ciri penyegerakan",
  "Connect all your Boom calendars available on your website":
    "Sambungkan semua kalendar boom anda yang terdapat di laman web anda",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Jadual, sertai, dan menguruskan mesyuarat zoom melalui kalendar boom kami.",
  "Monitor your Event Brite events through the Event Brite sync feature..":
    "Pantau acara Brite acara anda melalui acara Brite Sync Ciri",
  Email: "E -mel",
  "Add-ons": "Tambah",
  "Receive notification emails as soon as users add events to your calendar.":
    "Terima e -mel pemberitahuan sebaik sahaja pengguna menambah acara ke kalendar anda.",
  "Enable + button on the calendar header":
    "Dayakan Butang + pada tajuk kalendar",
  "Accept or decline events added by customers before making them public.":
    "Menerima atau menolak peristiwa yang ditambah oleh pelanggan sebelum membuat mereka awam.",
  "Switch Add Event": "Tukar Acara Tambah",
  "Enable your browser cookies to connect to your account.":
    "Dayakan kuki penyemak imbas anda untuk menyambung ke akaun anda.",
  "Learn more": "Ketahui lebih lanjut",
  "Print Button": "Butang Cetak",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Permit pengguna anda untuk mencetak kalendar acara Boom anda dalam julat tarikh.",
  "Show Title on mobile": "Tunjukkan tajuk di telefon bimbit",
  "Show Skeleton on mobile": "Tunjukkan kerangka di telefon bimbit",
  "Start 7-day Business trial": "Mulakan Percubaan Perniagaan 7 Hari",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Nikmati semua ciri yang tidak terhad, seperti menjual tiket, pendaftaran, tambahan acara pelawat.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Sila ambil perhatian: Pada akhir tempoh percubaan, anda akan dikembalikan kepada pelan langganan anda yang sedia ada.",
  "Not Now": "Bukan sekarang",
  "Start free trial": "Mulakan Percubaan Percuma",
  "Congrats!": "Tahniah!",
  "Your 7-day Business trial has been successfully activated.":
    "Percubaan perniagaan 7 hari anda telah berjaya diaktifkan.",
  Done: "Selesai",
  "Title font color": "Warna fon tajuk",
  "Desciption font color": "Warna font desciption",
  "Section font color": "Warna fon bahagian",
  "Card Header": "Tajuk kad",
  Category: "Kategori",
  "Display at the": "Paparan di",
  top: "Atas",
  bottom: "bawah",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Mempamerkan penapis kategori di bahagian atas atau di bahagian bawah kalendar. Tetapan ini berlaku untuk pandangan agenda dan kad sahaja",
  "Processing your events": "Memproses acara anda",
  "Search for events": "Cari acara",
  "There are no events added": "Tidak ada acara yang ditambah",
  "Location: To be determined": "Lokasi: akan ditentukan",
  "No events for selected date": "Tiada acara untuk tarikh yang dipilih",
  Uncategorized: "Tidak dikategorikan",
  "Edit event": "Edit acara",
  "Edit original event": "Edit acara asal",
  "Copy event": "Acara Salin",
  "Copy as new event": "Salin sebagai acara baru",
  "Delete event": "Padam acara",
  "Stop repeating on this date": "Berhenti mengulangi tarikh ini",
  "Exclude this date": "Tidak termasuk tarikh ini",
  "Location is going to be announced": "Lokasi akan diumumkan",
  "Fill your personal information": "Isi maklumat peribadi anda",
  "Check Box": "Kotak periksa",
  "Single Choice": "Pilihan tunggal",
  Option: "Pilihan",
  "Share Event": "Acara Kongsi",
  "Oops! Something went wrong": "Alamak! Ada yang tidak kena",
  "We are sorry this event has already taken place":
    "Kami minta maaf acara ini sudah berlaku",
  "Back to calendar": "Kembali ke kalendar",
  "This field is required": "Bidang ini diperlukan",
  Phone: "Telefon",
  "Number field": "Medan nombor",
  "Please provide a valid email": "Sila berikan e -mel yang sah",
  "Select at least one option": "Pilih sekurang -kurangnya satu pilihan",
  "Choose tickets to see total value": "Pilih tiket untuk melihat jumlah nilai",
  tickets: "Tiket",
  "Choose Tickets": "Pilih tiket",
  "Choose payment method": "pilih cara pembayaran",
  Pay: "Bayar",
  Total: "Jumlah",
  Free: "Percuma",
  "Buy tickets": "Beli tiket",
  "Sold Out": "Habis dijual",
  "Tickets are available": "Tiket disediakan",
  "Sales End": "Akhir jualan",
  "Availible from": "Boleh didapati dari",
  "Go to Orders": "Pergi ke pesanan",
  "Go to Details": "Pergi ke butiran",
  "Group ticket": "Tiket kumpulan",
  Name: "Nama",
  Price: "Harga",
  "Order by": "Perintah oleh",
  "Order ID": "ID pesanan",
  Applied: "Digunakan",
  Fees: "Yuran",
  "Enter promo code": "Masukkan kod promo",
  Apply: "Memohon",
  "Promo Code": "Kod promosi",
  Cash: "Tunai",
  "You can find your e-tickets attached to your email or download them":
    "Anda boleh menemui e-tiket anda yang dilampirkan pada e-mel anda atau memuat turunnya",
  here: "di sini",
  Time: "Masa",
  "Invalid promo code": "Kod promo yang tidak sah",
  "Credit card": "Kad kredit",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Anda akan segera menerima mesej pengesahan pendaftaran yang berjaya ke alamat e -mel anda.",
  "You can also check your order details below.":
    "Anda juga boleh menyemak butiran pesanan anda di bawah.",
  at: "pada",
  Buy: "Beli",
  Donation: "Derma",
  "Enter price": "Masukkan harga",
  Choose: "Pilih",
  Chosen: "Dipilih",
  "Choose your plan": "Pilih rancangan anda",
  week: "minggu",
  wk: "wk",
  "Choose plan cycle": "Pilih kitaran pelan",
  months: "bulan",
  years: "tahun",
  weeks: "minggu",
  "Copy Event Url": "Salin url acara",
  "You can find your e-tickets attached to your email or print them":
    "Anda boleh menemui e-tiket anda yang dilampirkan pada e-mel anda atau mencetaknya",
  "Guest Info": "Maklumat tetamu",
  "Ticket Info": "Maklumat Tiket",
  "Ticket name": "Nama Tiket",
  "Ticket price": "Harga tiket",
  "Ticket ID": "ID Tiket",
  "If you have any questions contact to organizer":
    "Sekiranya anda mempunyai pertanyaan hubungi penganjur",
  "As soon as event ends": "Sebaik sahaja acara berakhir",
  "1 day after event ends": "1 hari selepas acara berakhir",
  "7 days after event ends": "7 hari selepas acara berakhir",
  "14 days after event ends": "14 hari selepas acara berakhir",
  "30 days after event ends": "30 hari selepas acara berakhir",
  Menu: "Menu",
  "No event for selected date": "Tiada acara untuk tarikh yang dipilih",
  view: "Lihat",
  List: "Senarai",
  Year: "Tahun",
  Yearly: "Setiap tahun",
  "Year view header": "Header Lihat Tahun",
  "Yearly Style": "Gaya tahunan",
  "There are no events": "Tidak ada acara",
  Autotranslation: "Autotranslation",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Sebaik sahaja diaktifkan, widget kalendar anda akan diterjemahkan berdasarkan bahasa laman web. *Perhatikan bahawa selagi tajuk kalendar, dan deskripsi adalah teks input yang tidak dapat diterjemahkan.",
  "Note on mobile": "Perhatikan di telefon bimbit",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Matikan atau ubah teks bar 'tiada acara' pada versi mudah alih kalendar",
  Autodeletion: "Autodeletion",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Mengaktifkan pilihan, secara automatik akan mengeluarkan peristiwa masa lalu anda dari kalendar.",
  "This does not apply to repeating events!":
    "Ini tidak terpakai untuk mengulangi peristiwa!",
  "Notify event creators about the guest":
    "Memberitahu pencipta acara mengenai tetamu",
  "Send event creators notification emails as soon as guests register for their events":
    "Hantar E -mel Pemberitahuan Pencipta Acara Sebaik sahaja tetamu mendaftar untuk acara mereka",
  "List View Type": "Senarai jenis paparan",
  "Description font": "Penerangan Font",
  Connect: "Sambung",
  "You have no events": "Anda tidak mempunyai acara",
  Synchronize: "Menyegerakkan",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Google Calendar Sync membolehkan anda mengintegrasikan acara dan sesi anda dengan kalendar boom anda.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Sync kalendar Outlook membolehkan anda mengintegrasikan acara dan sesi anda dengan kalendar boom anda.",
  "Your message has been sent successfully!":
    "Mesej anda telah berjaya dihantar!",
  "There are no synchronized calendars": "Tidak ada kalendar yang disegerakkan",
  "to view more than 7 events": "Untuk melihat lebih daripada 7 acara",
  "Mobile app": "Aplikasi mudah alih",
  "Admin Account": "Akaun pentadbir",
  Password: "Kata laluan",
  "Second User": "Pengguna kedua",
  Edit: "Edit",
  "Guest limit": "Had tetamu",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Semua tetapan tempatan adalah (secara automatik) berdasarkan bahasa anda. Sekiranya bahasa anda berada dalam senarai, tidak perlu menyesuaikan seksyen ini.",
  available: "Terdapat",
  next: "Seterusnya",
  Tickets: "Tiket",
  Quantity: "Kuantiti",
  "Promo code": "Kod promosi",
  "Select a payment method": "Pilih kaedah pembayaran",
  Fee: "Bayaran",
  Book: "Buku",
  "All the tickets have been sold out": "Semua tiket telah habis dijual",
  "Choose at least one ticket": "Pilih sekurang -kurangnya satu tiket",
  "First choose ticket": "Mula -mula pilih tiket",
  "Please fill out your personal information.":
    "Sila isi maklumat peribadi anda.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "Untuk membuat pembelian yang berjaya, sila pilih kaedah pembayaran pilihan anda dan masukkan kod promo untuk tiket diskaun.",
  "Credit/Debit card": "Kad kredit/debit",
  "print here.": "Cetak di sini.",
  "QR code for all tickets": "Kod QR untuk semua tiket",
  Duration: "Tempoh",
  "Full Name": "Nama penuh",
  "Ticket id": "ID Tiket",
  "Group id": "ID Kumpulan",
  "Choose your ticket.": "Pilih tiket anda.",
  "Fill out your personal information.": "Isi maklumat peribadi anda.",
  "Add the payment details.": "Tambahkan butiran pembayaran.",
  "To be determined": "Akan ditentukan",
  "You can find your e-tickets attached to the email or":
    "Anda boleh menemui e-tiket anda yang dilampirkan pada e-mel atau",
  "print here": "Cetak di sini",
  "Full name": "Nama penuh",
  "Group ID": "ID Kumpulan",
  "to Book": "untuk tempahan",
  "Unfortunately, your card has been declined":
    "Malangnya, kad anda telah ditolak",
  "Thank you for your purchase!": "Terima kasih atas pembelian anda!",
  "Find your printable e-tickets attached to the confirmation email":
    "Cari e-tiket cetak anda yang dilampirkan pada e-mel pengesahan",
  Confirm: "Mengesahkan",

  "Add event": "Tambah acara",
  Events: "Peristiwa",
  "Event details": "Butiran Acara",
  Registration: "Pendaftaran",
  "Guests list": "Senarai tetamu",
  Ticket: "Tiket",
  "General Info": "Maklumat umum",
  "Customize the general settings of your event":
    "Sesuaikan tetapan umum acara anda",
  "Event Title": "Tajuk Acara",
  "e.g. Birthday Party": "mis. Parti hari lahir",
  "All Day Event": "Acara sepanjang hari",
  Cross: "Menyeberang",
  Timeline: "Garis masa",
  "Repeating event": "Mengulangi acara",
  Location: "Lokasi",
  "Venue name": "Nama tempat",
  Description: "Penerangan",
  Image: "Gambar",
  Color: "Warna",
  Category: "Kategori",
  "Add your events to color categories and let your users classify them easily":
    "Tambahkan acara anda ke kategori warna dan biarkan pengguna anda mengklasifikasikannya dengan mudah",
  "Category name": "Nama kategori",
  "e.g. Birthdays": "mis. Hari lahir",
  Venue: "Tempat",
  "Where the event takes place": "Di mana acara berlangsung",
  "Venue name": "Nama tempat",
  "Venue phone": "Telefon Tempat",
  "Venue email": "E -mel tempat",
  "Venue website": "Laman web tempat",
  Organizer: "Penganjur",
  "Person who makes the event": "Orang yang membuat acara itu",
  "Organizer name": "Nama penganjur",
  "Organizer phone": "Telefon penganjur",
  "Organizer email": "E -mel penganjur",
  "Organizer website": "Laman web penganjur",
  Save: "Simpan",
  Cancel: "Batalkan",
  Import: "Import",
  Past: "Masa lalu",
  All: "Semua",
  Upcoming: "Akan datang",
  Uncategorised: "Tidak dikategorikan",
  "Date Ascending": "Tarikh naik",
  "Date Descending": "Tarikh turun",
  "Title by A-Z": "Tajuk oleh A-Z",
  "Title by Z-A": "Tajuk oleh Z-A",
  "There are no events for this period": "Tidak ada acara untuk tempoh ini",

  "Auto-Convert Date & Time": "Tarikh & Masa Tukar Auto",
  TimeZone: "Zon masa",
  Autodeletion: "Autodeletion",
  "Layout Settings": "Tetapan susun atur",
  "Yeatly view": "Lihatlah",
  "Monthly view header": "Header View Bulanan",
  "Weekly/Daily view header": "Pengepala Mingguan/Harian Pandangan",
  Acendings: "Acendings",
  Descending: "Turun",
  Standart: "Standart",
  Silver: "Perak",
  Retro: "Retro",
  Dark: "Gelap",
  Night: "Malam",
  Aubergine: "Terung",
  "List view header": "Senarai header paparan",
  "Side by Side View": "Pandangan bersebelahan",
  "Customize Proportions": "Sesuaikan perkadaran",
  "Card Margins": "Margin kad",
  "Image opacity (%)": "Kelegapan Imej (%)",
  "Side by Side Header": "Tajuk sampingan",
  "Text Align": "Teks Align",
  "Timeline View": "Pandangan garis masa",
  "Title font color": "Warna fon tajuk",
  "Desciption font color": "Warna font desciption",
  "Line color": "Warna garis",
  "Date Font color": "Warna fon tarikh",
  "Daily events background": "Latar Belakang Peristiwa Harian",
  Alignment: "Penjajaran",
  Vertical: "Menegak",
  Horizontal: "Mendatar",
  "Vertical Alignment": "Penjajaran menegak",
  Right: "Betul",
  Center: "Pusat",
  "Horizontal Alignment": "Penjajaran mendatar",
  Top: "Atas",
  Center: "Pusat",
  Bottom: "Bawah",
  "Dates Circle Design": "Tarikh reka bentuk bulatan",
  "Next To The Circle": "Di sebelah bulatan",
  "In The Circle": "Dalam bulatan",
  "Timeline Header": "Header Timeline",
  Timeline: "Garis masa",
  "Show only upcoming": "Hanya menunjukkan yang akan datang",
  "Order by": "Perintah oleh",
  "Timeline Event Limit": "Had peristiwa garis masa",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Benarkan pengunjung menambah acara ke Calnedars tempatan: Google, Yahoo, Outlook, icalendar.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Benarkan pelawat berkongsi acara anda ke Facebook, LinkedIn, Twitter dan lain -lain.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Tambahkan pilihan carian pada kalendar anda untuk membiarkan orang mencari acara anda dengan tajuk, tempat, dll.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Permit pengguna anda untuk mencetak kalendar acara Boom anda dalam julat tarikh.",
  "Click to apply a theme to Calendar":
    "Klik untuk menggunakan tema untuk kalendar",
  "Date container color": "Warna kontena tarikh",
  "Daily events background": "Latar Belakang Peristiwa Harian",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Gunakan add-on untuk memasang ciri canggih pada kalendar anda, menjadikannya lebih berfungsi!",
  "Open Add-ons Store": "Buka kedai tambahan",
  Monday: "Isnin",
  Tuesday: "Selasa",
  Wednesday: "Rabu",
  Thursday: "Khamis",
  Friday: "Jumaat",
  Saturday: "Sabtu",
  Sunday: "Ahad",
  "Yearly view": "Pandangan tahunan",
  Ascending: "Selasa",
  "Show event time next to title": "Tunjukkan masa acara di sebelah tajuk",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Laraskan tarikh dan masa acara ke masa tempatan pengguna berdasarkan zon waktu mereka.",
  "Display the time zone alongside the event date.":
    "Paparkan zon waktu bersama tarikh acara.",
  "Show event time next to title": "Tunjukkan masa acara di sebelah tajuk",
  "Time Zone": "Zon masa",
  "Upload Image": "Muat naik gambar",
  "Choose a Category": "Pilih Kategori",
  "Color you have chosen will not be shown as you choose category":
    "Warna yang anda pilih tidak akan ditunjukkan semasa anda memilih kategori",
  Website: "Laman web",
  Next: "Seterusnya",
  Save: "Simpan",
  "Last Name": "Nama terakhir",
  "Personal Info": "Maklumat peribadi",
  Back: "Kembali",
  "This field is required": "Bidang ini diperlukan",
  "Your event has been submitted": "Acara anda telah dihantar",
  "Enter a location": "Masukkan lokasi",
  "Display the time zone alongside the event date.":
    "Paparkan zon waktu bersama tarikh acara.",
  Home: "Rumah",
  "Side By Side Event Limit": "Had acara bersebelahan",
  "Mobille App": "Aplikasi Mobille",
  category: "kategori",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Jejaki jadual anda dengan mudah dengan mengimport acara Facebook anda ke kalendar anda.",
  "Synchronized Pages": "Halaman Disegerakkan",
  "There are no synchronized pages": "Tiada halaman yang disegerakkan",
  "Choose page": "Pilih halaman",
  "You have no events": "Anda tidak mempunyai acara",
};
export default ms;
