let nl = {
  Categories: "Categorieën",
  "Share this event": "Deel dit evenement",
  Language: "Taal",
  "Show Time Zone": "Tijdzone Tonen",
  "Custom Local Settings": "Aangepaste Lokale Instellingen",
  "Add and showcase events on your site using a beautiful calendar.":
    "Voeg evenementen toe aan uw pagina met behulp van een mooie kalender . ",
  "Week Days": "Dagen van de Week",
  "Manage Events": "Beheer Evenementen",
  General: "Algemeen",
  "Layout Picker": "Kies Layout",
  Month: "Maand",
  Monthly: "Per Maand",
  Week: "Week",
  Weekly: "Per Week",
  Day: "Dag",
  Daily: "Per Dag",
  Agenda: "Agenda",
  "Navigation Buttons": "Navigatie Knoppen",
  "Week numbers": "Weeknummers",
  "Include Weekends": "Inclusief Weekend",
  "All-day": "De hele dag",
  "All Day": "De hele dag",
  Label: "Benoemen",
  "Fit to Height": "Aanpassen aan Hoogte",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Als u app-verhoudingen wilt instellen, schakelt u deze optie uit en wijzigt u de grootte van Kalender in Editor. ",
  "Default Layout": "Standaard Opmaak",
  "Monthly view": "per Maand",
  "Weekly and Daily view": "Wekelijkse en Dagelijkse overzicht",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "U kunt bezoekers een meer consistente ervaring geven door hetzelfde aantal weken ( 6) tegelijkertijd weer te geven.",
  "Fixed Weekly Layout": "Vaste Weekindeling",
  back: " terug ",
  Row: "Rij",
  "Hours in Weekly View": "Uren per Week",
  "Hours in Daily View": "Uren per Dag",
  Start: "Start",
  End: "Slutt",
  "At This Hour": "Tijdstip",
  Button: "Knop",
  Buttons: "Toetsen",
  Sunday: "Zondag",
  Monday: "Maandag",
  Tuesday: "Dinsdag",
  Wednesday: "Woensdag",
  Thursday: " Donderdag ",
  Friday: "Vrijdag",
  Saturday: "Zaterdag",
  "Default Date": "Standaard Datum",
  year: " jaar ",
  month: " maand ",
  mo: " maand ",
  days: " dagen ",
  ago: " geleden ",
  ahead: " vooruit ",
  Yesterday: "Gisteren",
  Today: "Vandaag",
  Tomorrow: "Morgen",
  Custom: "Aangepast",
  "Set Daily Rows Limit": "Rijenlimiet Dagen Instellen",
  "Set Proportions": "Eigenschappen Instellen",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Toestaan dat bezoeker evenement aan lokale Agenda's toevoegt , Google, Yahoo, Outlook, ICalendar . ",
  Container: "Kader",
  Background: "Achtergrond",
  "Container Background": "Achtergrond Kader",
  "Container Borders": "Randen Kader",
  Calendar: "Kalender",
  "Event Info Tooltip": "Event Info Tooltip",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Wanneer mensen boven een evenement hangen, zien ze alle info erover in een tooltip. ",
  "Event Info Window": "Event Info Window",
  "This is the full information window that opens when someone clicks on the event.":
    "Dit is het volledige informatievenster dat opent, wanneer men op het evenement klikt. ",
  "Use Gradient": "Gebruik Gradient",
  Vertical: "Verticaal",
  Horizontal: "Horizontaal",
  First: "Eerste",
  Second: "Tweede",
  diagonal: " Diagonaal ",
  Radial: "Radiaal",
  "Select option": "Selecteer optie",
  Solid: "Solide",
  Dotted: "Gestippeld",
  Dashed: "Gestreept",
  Double: "Dubbel",
  "Border Radius": "Rand Radius",
  Padding: "Vulling",
  "Date Header": "Datum Koptekst",
  "Event Default Color": "Standaardkleur Evenement",
  "Days of Week": "Dagen van de Week",
  "Days of Week Background": "Achtergrond Dagen van de Week",
  Date: "Dato",
  "Event Title": "Event title",
  "Highlight today": "Markeer Vandaag",
  "Highlight Color": "Markeer Kleur",
  Hide: "Verbergen",
  "Calendar Border Color": "Randkleur Kalender",
  "Calendar Border Width": "Randbreedte Kalender",
  "Calendar Border Style": "Randstijl Kalender",
  "Font Color": "Letterkleur",
  "Event Background": "Achtergrond Activiteit",
  "Card Date Color": "Kaart Datum kleur",
  "Title Font": "Titel Lettertype",
  "Date Font": "Datum Lettertype",
  "Description Font": "Omschrijving Lettertype",
  "Button Background": "Knop Achtergrond",
  "Button Text": "Knop Tekst",
  "Border Color": "Randkleur",
  "Border Width": "Grensbreedte",
  "Border Type": "Rand Type",
  Title: "Titel",
  Description: "Beskrivelse",
  "Background Color": "Achtergrond Kleur",
  Divider: "Verdeler",
  "Event Details Font": "Evenement Details Lettertype",
  "Website Link Color": "Website Link Kleur",
  "Developer Info": "Info ontwikkelaar",
  "User Guide": "Gebruikershandleiding",
  "Support e-mail": "Ondersteuning e-mail",
  "Our Website": "Onze website",
  "App Review": "App Beoordeling",
  "Enjoying App? Leave us a review in the App Market.":
    "Blij met de app? Schrijf een beoordeling in de App-markt. ",
  "Review Us": "Beoordeel ons",
  "Connect With Us": "Bericht sturen",
  "What's your email?": "Wat is uw e-mail? ",
  "Invalid email address!": "Ongeldig e-mailadres! ",
  Comments: "Reacties",
  "We'd love to hear from you. Send us a message.":
    "Wij horen graag van u. Stuur ons een bericht. ",
  "Message must be at least 5 characters long":
    "Bericht moet minimaal 5 tekens lang zijn",
  Send: "Verzenden",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Als u de gebruiker wilt laten schakelen tussen agendaweergaven, schakelt u deze optie in en kiest u de weergaven die u wilt zien. ",
  Main: "Hoofd",
  Localize: "Lokaliseren",
  Settings: "Instellingen",
  Layouts: "Opmaak",
  Advanced: "Geavanceerd",
  Design: "Ontwerp",
  Support: "Hulp",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Alle lokale instellingen zijn (automatisch) gebaseerd op uw taal. Als uw taal in de lijst staat, hoeft u dit gedeelte niet aan te passen.",
  "Date Format": "Datum",
  "Time Format": "Tijd",
  "Text Direction": "Tekstrichting",
  "Left to Right": "van Links naar Rechts",
  "Right to Left": "van Rechts naar Links",
  "Week Starts On": "Week Begint Op",
  "Agenda Style": "Agendastijl",
  Classic: "Klassiek",
  Modern: "Modern",
  "Agenda Header": "Koptekst Agenda",
  "Upcoming Events": "Aankomende Evenementen",
  "Agenda Event Limit": "Agenda Event Limit",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Upgrade nu en krijg veel meer functies en geniet volop van uw APP!",
  "Upgrade Now": "Nu upgraden",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Organiseert u evenementen die de hele dag duren? Hiermee kunt u ze in uw agenda weergeven.",
  "24 hours": "24 uur",
  Sat: "Zat",
  Sun: "Zon",
  Mon: "Maan",
  Default: "Standaard",
  "Select custom design style for your calendar.":
    "Selecteer een aangepaste ontwerpstijl voor uw kalender.",
  Style: "Stijl",
  "Styles and Colors": "Stijlen en kleuren",
  "Calendar Name": "Naam van agenda",
  "Write your Calendar name here": "Schrijf hier uw agendanaam",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Dit is niet zichtbaar voor uw gebruikers. Stel namen in om uw agenda's te onderscheiden wanneer u de Boom Calendar Sync-functie gebruikt.",
  "General Info": "Generell info",
  Venue: "Evenementenlocatie",
  Organizer: "Organisator",
  Search: "Zoeken",
  "Add to": "Voeg toe",
  calendar: "kalender",
  "Copy event URL": "Event-URL kopiëren",
  "Copied!": "Gekopieerd!",
  "Add & Share": "Toevoegen en delen",
  Map: "Kart",
  "Calendar view": "Kalenderweergave",
  "Add Event": "Voeg evenement toe",
  Uncategorised: "Ukategorisert",
  More: "Meer",
  Less: "Minder",
  Register: "Registreren",
  Card: "Kaart",
  Guests: "Gjestene",
  unlimited: "ubegrenset",
  "Show more": "Bekijk meer",
  "Enable Search": "Zoeken inschakelen",
  "+ Add Event": "+ Evenement toevoegen",
  "Manage and Sync": "Beheer en synchroniseer",
  "Show event details as...": "Afspraakdetails weergeven als ...",
  Tooltip: "Knopinfo",
  Popup: "Informatie box",
  None: "Geen",
  "Show Category": "Categorie weergeven",
  "Header Align": "Koptekst uitlijnen",
  "Show Time": "Show Time",
  "Hours in Weekly/Daily View": "Uren in wekelijkse / dagelijkse weergave",
  "Share Events": "Deel evenementen",
  Shadow: "Schaduw",
  "Inner Padding": "Inner Padding",
  Text: "Tekst",
  "Active Button Border": "Actieve knoprand",
  "Light Mode": "Lichte modus",
  "Event Text Color": "Tekstkleur gebeurtenis",
  Dates: "Datums",
  Skeleton: "Skelet",
  "Skeleton Color": "Skeleton kleur",
  Width: "Breedte",
  "Skeleton Style": "Skeleton stijl",
  Color: "Farge",
  "Section Titles": "Sectie titels",
  "Section Content": "Sectie-inhoud",
  Header: "Koptekst",
  Standard: "Standard",
  Retro: "Retro",
  Silver: "Sølv",
  Night: "Natt",
  Dark: "Mørk",
  Aubergine: "Aubergine",
  "Map Header": "Karthode",
  "Show Title in mobile": "Titel weergeven op mobiel",
  "Card View": "Kaartweergave",
  "Card background color": "Achtergrondkleur van de kaart",
  "Title font": "Titel lettertype",
  "Desciption font": "Beschrijving lettertype",
  "Section font": "Lettertype sectie",
  "Section divider color": "Kleur sectiescherm",
  "Add event": "Legg til hendelse",
  "All Day Event": "Heldags hendelse",
  Location: "Plassering",
  "Choose a category": "Velg en kategori",
  "Venue name": "Stedets navn",
  "Venue phone": "Lokaltelefon",
  "Venue email": "E-poststed",
  "Venue website": "Stedets nettsted",
  "Organizer name": "Arrangørens navn",
  "Organizer phone": "Organiser-telefon",
  "Organizer email": "Organiser-e-post",
  "Organizer website": "Arrangørens nettsted",
  "Personal info": "Personlig informasjon",
  "First name": "Fornavn",
  "Last name": "Etternavn",
  "Email Address": "E-mailadres",
  "Additional Notes": "Tilleggsmerknader",
  Back: "Tilbake",
  Save: "Lagre",
  Next: "Neste",
  "Your event has been submitted": "Arrangementet ditt er sendt inn",
  "Event submittion has been failed": "Innlevering av hendelse mislyktes",
  "e.g. Birthday Party": "f.eks. Bursdagsfest",
  "First Name": "Voornaam",
  "Last Name": "Achternaam",
  "Phone Number": "Telefonnummer",
  Address: "Adresse",
  "Your comments": "Dine kommentarer",
  "How many guests?": "Hvor mange gjester?",
  "Anything else we need to know?": "Is er nog iets dat we moeten weten?",
  "Guests:": "Gasten:",
  Submit: "Verzenden",
  "Go to Calendar": "Ga naar Kalender",
  "Registration completed successfully!": "Registreringen fullført!",
  "Please check your registered email address":
    "Controleer uw geregistreerde e-mailadres",
  "Add to Calendar": "Toevoegen aan agenda",
  "Share this Event": "Deel dit evenement",
  "Sorry something went wrong": "죄송합니다. 문제가 발생했습니다.",
  "Back to registration": "Terug naar registratie",
  "Date & Location": "Datum en locatie",
  "Date & Time": "Datum Tijd",
  home: "huis",
  "Header align": "Koptekst uitlijnen",
  Footer: "Voettekst",
  "Categories Filter": "categorieën Filter",
  "Show only upcoming": "Toon alleen aanstaande",
  "Card(s) in a row": "Kaart (en) op een rij",
  "Space between cards": "Ruimte tussen kaarten",
  "Shown events limit": "Limiet voor weergegeven evenementen",
  "Style 1": "Stijl 1",
  "Style 2": "Stijl 2",
  "Style 3": "Stijl 3",
  "Style 4": "Stijl 4",
  "Buttons & Links": "Knoppen en koppelingen",
  "Button corner radius": "Hoekstraal van knop",
  "Buttons font": "Knoppen lettertype",
  "Buttons background": "Knoppen achtergrond",
  "Get notified by Email": "Ontvang een melding per e-mail",
  "Review events": "Bekijk evenementen",
  "Click on date": "Klik op datum",
  "Add Event button": "Gebeurtenis toevoegen knop",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Met agendasynchronisatie kunt u uw evenementen en sessies integreren met uw Boom-agenda.",
  connect: "aansluiten",
  "Synchronized Calendars": "Gesynchroniseerde kalenders",
  "Import events": "Evenementen importeren",
  Disconnect: "verbinding verbreken",
  "Choose calendar": "Kies een kalender",
  "Monitor your Wix events through the sync feature":
    "Houd uw Wix-evenementen bij via de synchronisatiefunctie",
  "Connect all your Boom calendars available on your website":
    "Verbind al uw Boom-agenda's die beschikbaar zijn op uw website",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Plan, neem deel en beheer Zoom-vergaderingen rechtstreeks via onze Boom-agenda.",
  "Monitor your Event Brite events through the Event Brite sync feature..":
    "Volg uw Event Brite-evenementen via de Event Brite-synchronisatiefunctie",
  Email: "E-mail",
  "Add-ons": "Add-ons",
  "Receive notification emails as soon as users add events to your calendar.":
    "Ontvang meldings-e-mails zodra gebruikers gebeurtenissen aan uw agenda toevoegen.",
  "Enable + button on the calendar header": "Enable + knop op de kalenderkop",
  "Accept or decline events added by customers before making them public.":
    "Accepteert of weigeren gebeurtenissen die door klanten zijn toegevoegd voordat u ze openbaar maakt.",
  "Switch Add Event": "Schakel evenement toe",
  "Enable your browser cookies to connect to your account.":
    "Schakel uw browsercookies in om verbinding te maken met uw account.",
  "Learn more": "Kom meer te weten",
  "Print Button": "Drukāšanas poga",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Sta uw gebruikers toe om uw Boom Event-kalender in elk datumbereik af te drukken.",
  "Show Title on mobile": "Toon titel op mobiel",
  "Show Skeleton on mobile": "Toon skelet op mobiel",
  "Start 7-day Business trial": "Start uw bedrijfsprove met 7 dagen",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Geniet van alle onbeperkte functies, zoals verkooptickets, registratie, add-ons van bezoekersgebeurtenis.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Let op: aan het einde van de proefperiode wordt u teruggestuurd naar uw bestaande abonnementsplan.",
  "Not Now": "Niet nu",
  "Start free trial": "Start gratis proefversie",
  "Congrats!": "Proficiat!",
  "Your 7-day Business trial has been successfully activated.":
    "Uw 7-daagse bedrijfsproef is succesvol geactiveerd.",
  Done: "Klaar",
  "Title font color": "Titel lettertype kleur",
  "Desciption font color": "Beschrijving Lettertypekleur",
  "Section font color": "Sectie lettertype kleur",
  "Card Header": "Kaartkop",
  Category: "Categorie",
  "Display at the": "Weergave op de",
  top: "bovenkant",
  bottom: "onderkant",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Toon de categoriefilter aan de bovenkant of onderaan de kalender.De instellingen zijn alleen van toepassing op Agenda and Card-views",
  "Processing your events": "Uw evenementen verwerken",
  "Search for events": "Zoek naar evenementen",
  "There are no events added": "Er zijn geen gebeurtenissen toegevoegd",
  "Location: To be determined": "Locatie: te bepalen",
  "No events for selected date": "Geen evenementen voor geselecteerde datum",
  Uncategorized: "Niet gecategoriseerd",
  "Edit event": "Event bewerken",
  "Edit original event": "Origineel evenement bewerken",
  "Copy event": "Kopieerevenement",
  "Copy as new event": "Kopieer als nieuw evenement",
  "Delete event": "Verwijder evenement",
  "Stop repeating on this date": "Stop met herhalen op deze datum",
  "Exclude this date": "Sluit deze datum uit",
  "Location is going to be announced": "Locatie wordt aangekondigd",
  "Fill your personal information": "Vul uw persoonlijke informatie in",
  "Check Box": "Selectievakje",
  "Single Choice": "Enkele keuze",
  Option: "Keuze",
  "Share Event": "Deelgebeurtenis",
  "Oops! Something went wrong": "Oeps!Er is iets fout gegaan",
  "We are sorry this event has already taken place":
    "Het spijt ons dat dit evenement al heeft plaatsgevonden",
  "Back to calendar": "Terug naar kalender",
  "This field is required": "dit veld is verplicht",
  Phone: "Telefoon",
  "Number field": "Nummerveld",
  "Please provide a valid email": "Geef een geldige e -mail op",
  "Select at least one option": "Selecteer ten minste één optie",
  "Choose tickets to see total value":
    "Kies tickets om de totale waarde te zien",
  tickets: "kaartjes",
  "Choose Tickets": "Kies tickets",
  "Choose payment method": "Kies betalingsmethode",
  Pay: "Betalen",
  Total: "Totaal",
  Free: "Vrij",
  "Buy tickets": "Koop kaartjes",
  "Sold Out": "Uitverkocht",
  "Tickets are available": "Tickets zijn beschikbaar",
  "Sales End": "Verkoopuiteinde",
  "Availible from": "Beschikbaar van",
  "Go to Orders": "Ga naar bestellingen",
  "Go to Details": "Ga naar details",
  "Group ticket": "Groepsticket",
  Name: "Naam",
  Price: "Prijs",
  "Order by": "Bestellen door",
  "Order ID": "Order ID",
  Applied: "Toegepast",
  Fees: "Vergoedingen",
  "Enter promo code": "Voer de promotiecode in",
  Apply: "Van toepassing zijn",
  "Promo Code": "Promotiecode",
  Cash: "Contant geld",
  "You can find your e-tickets attached to your email or download them":
    "U kunt uw e-tickets aan uw e-mail vinden of downloaden",
  here: "hier",
  Time: "Tijd",
  "Invalid promo code": "Ongeldige promotiecode",
  "Credit card": "Kredietkaart",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "U ontvangt binnenkort een bevestigingsbericht van succesvolle registratie van uw e -mailadres.",
  "You can also check your order details below.":
    "U kunt hieronder ook uw bestelgegevens controleren.",
  at: "Bij",
  Buy: "Kopen",
  Donation: "Bijdrage",
  "Enter price": "Onderneming",
  Choose: "Kiezen",
  Chosen: "Gekozen",
  "Choose your plan": "Kies uw plan",
  week: "week",
  wk: "week",
  "Choose plan cycle": "Kies de plancyclus",
  months: "maanden",
  years: "jaar",
  weeks: "weken",
  "Copy Event Url": "Kopieer Event URL",
  "You can find your e-tickets attached to your email or print them":
    "U kunt uw e-tickets aan uw e-mail vinden of afdrukken",
  "Guest Info": "Gastinformatie",
  "Ticket Info": "Ticketinformatie",
  "Ticket name": "Ticketnaam",
  "Ticket price": "Ticket prijs",
  "Ticket ID": "Ticket ID",
  "If you have any questions contact to organizer":
    "Als u vragen heeft, neem contact op met de organisator",
  "As soon as event ends": "Zodra het evenement eindigt",
  "1 day after event ends": "1 dag na het einde van het evenement",
  "7 days after event ends": "7 dagen nadat het evenement is afgelopen",
  "14 days after event ends": "14 dagen nadat het evenement is afgelopen",
  "30 days after event ends": "30 dagen nadat het evenement is afgelopen",
  Menu: "Menu",
  "No event for selected date": "Geen gebeurtenis voor geselecteerde datum",
  view: "weergave",
  List: "Lijst",
  Year: "Jaar",
  "Yearly Style": "Jaarlijkse stijl",
  "There are no events": "Er zijn geen evenementen",
  Autotranslation: "Autotranslatie",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Eenmaal ingeschakeld, wordt uw kalenderwidget vertaald op basis van de taal van de website.* Merk op dat zo lang als kalendertitel en beschrijvingen worden ingevoerd teksten die ze niet kunnen worden vertaald.",
  "Note on mobile": "Opmerking op mobiel",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Schakel de tekst uit of verander de tekst van de 'No Events' -balk op de mobiele versie van de kalender",
  Autodeletion: "Autodeletie",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Als u de optie inschakelt, wordt uw gebeurtenissen in het verleden automatisch uit de kalender verwijderd.",
  "This does not apply to repeating events!":
    "Dit is niet van toepassing op herhalende evenementen!",
  "Notify event creators about the guest":
    "Cuir úsáideoirí ar an eolas faoin aoi",
  "Send event creators notification emails as soon as guests register for their events":
    "Send e-mails om begivenhedsskabere, så snart gæsterne tilmelder sig deres begivenheder",
  "List View Type": "Lijstweergave Type",
  Yearly: "Jaarlijks",
  "Year view header": "Jaaroverzicht header",
  "Description font": "Beschrijving lettertype",
  Connect: "aansluiten",
  "You have no events": "Jums nav notikumu",
  Synchronize: "동기화",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Met Google Calendar Sync kunt u uw evenementen en sessies integreren met uw giekkalender.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Outlook kalendāra sinhronizācija ļauj integrēt savus notikumus un sesijas ar jūsu uzplaukuma kalendāru.",
  "Your message has been sent successfully!":
    "Jūsu ziņojums ir veiksmīgi nosūtīts!",
  "There are no synchronized calendars": "동기화 된 캘린더가 없습니다.",
  "to view more than 7 events": "Om meer dan 7 evenementen te bekijken",
  "Mobile app": "모바일 앱",
  "Admin Account": "Beheerdersaccount",
  Password: "암호",
  "Second User": "Tweede gebruiker",
  Edit: "Bewerk",
  "Guest limit": "Gastenlimiet",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Alle lokale instellingen zijn (automatisch) op basis van uw taal.Als uw taal op de lijst staat, hoeft u dit gedeelte niet aan te passen.",
  available: "beschikbaar",
  next: "De volgende",
  Tickets: "Kaartjes",
  Quantity: "Aantal stuks",
  "Promo code": "Promotiecode",
  "Select a payment method": "Kies een betalingsmethode",
  Fee: "Vergoeding",
  Book: "Boek",
  "All the tickets have been sold out": "Alle tickets zijn uitverkocht",
  "Choose at least one ticket": "Kies ten minste één ticket",
  "First choose ticket": "Kies eerst ticket",
  "Please fill out your personal information.":
    "Vul alstublieft uw persoonlijke gegevens in.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "Om een succesvolle aankoop te doen, selecteert u uw gewenste betaalmethode en voert u de promocode in voor kortingstickets.",
  "Credit/Debit card": "Creditcard / betaalkaart",
  "print here.": "Print hier.",
  "QR code for all tickets": "QR-code voor alle tickets",
  Duration: "Looptijd",
  "Full Name": "Voor-en achternaam",
  "Ticket id": "Ticket ID",
  "Group id": "Groeps-ID",
  "Choose your ticket.": "Kies je ticket.",
  "Fill out your personal information.": "Vul uw persoonlijke gegevens in.",
  "Add the payment details.": "Voeg de betalingsgegevens toe.",
  "To be determined": "Nader te bepalen",
  "You can find your e-tickets attached to the email or":
    "U kunt uw e-tickets vinden die zijn aangesloten op de e-mail of",
  "print here": "Print hier",
  "Full name": "Voor-en achternaam",
  "Group ID": "Groeps-ID",
  "to Book": "boeken",
  "Unfortunately, your card has been declined": "Helaas is uw kaart geweigerd",
  "Thank you for your purchase!": "dank voor uw aankoop!",
  "Find your printable e-tickets attached to the confirmation email":
    "Zoek uw afdrukbare e-tickets die zijn gekoppeld aan de bevestigingsmail",
  Confirm: "Bevestigen",

  "Add event": "Voeg evenement toe",
  Events: "Evenementen",
  "Event details": "Evenementgegevens",
  Registration: "Registratie",
  "Guests list": "Gastenlijst",
  Ticket: "Ticket",
  "General Info": "Algemene informatie",
  "Customize the general settings of your event":
    "Pas de algemene instellingen van uw evenement aan",
  "Event Title": "Titel van het evenement",
  "e.g. Birthday Party": "bijv. Verjaardagsfeest",
  "All Day Event": "De hele dag evenement",
  Cross: "Kruis",
  Timeline: "Tijdlijn",
  "Repeating event": "Herhaalde gebeurtenis",
  Location: "Plaats",
  "Venue name": "Locatienaam",
  Description: "Beschrijving",
  Image: "Afbeelding",
  Color: "Kleur",
  Category: "Categorie",
  "Add your events to color categories and let your users classify them easily":
    "Voeg uw evenementen toe aan kleurcategorieën en laat uw gebruikers ze gemakkelijk classificeren",
  "Category name": "Categorie naam",
  "e.g. Birthdays": "bijv. Verjaardagen",
  Venue: "Locatie",
  "Where the event takes place": "Waar het evenement plaatsvindt",
  "Venue name": "Locatienaam",
  "Venue phone": "Locatie telefoon",
  "Venue email": "Locatie -e -mail",
  "Venue website": "Locatiewebsite",
  Organizer: "Organisator",
  "Person who makes the event": "Persoon die het evenement maakt",
  "Organizer name": "Naam van de organisator",
  "Organizer phone": "Organisator telefoon",
  "Organizer email": "Organisator -e -mail",
  "Organizer website": "Organizer website",
  Save: "Redden",
  Cancel: "Annuleren",
  Import: "Importeren",
  Past: "Verleden",
  All: "Alle",
  Upcoming: "Aankomend",
  Uncategorised: "Niet gecategoriseerd",
  "Date Ascending": "Datum stijgt",
  "Date Descending": "Datum dalen",
  "Title by A-Z": "Titel van A-Z",
  "Title by Z-A": "Titel door Z-A",
  "There are no events for this period":
    "Er zijn geen gebeurtenissen voor deze periode",

  "Auto-Convert Date & Time": "Auto-converteerdatum en tijd",
  TimeZone: "Tijdzone",
  Autodeletion: "Autodeletie",
  "Layout Settings": "opmaak instellingen",
  "Yeatly view": "Yeatly Bekijk",
  "Monthly view header": "Maandelijkse weergavekop",
  "Weekly/Daily view header": "Wekelijkse/dagelijkse view header",
  Acendings: "Hekel",
  Descending: "Aflopend",
  Standart: "Standart",
  Silver: "Zilver",
  Retro: "Retro",
  Dark: "Donker",
  Night: "Nacht",
  Aubergine: "Aubergine",
  "List view header": "Lijstweergave koptekst",
  "Side by Side View": "Naast elkaar uitzicht",
  "Customize Proportions": "Pas verhoudingen aanpassen",
  "Card Margins": "Kaartmarges",
  "Image opacity (%)": "Afbeelding opaciteit (%)",
  "Side by Side Header": "Naast elkaar kopbal",
  "Text Align": "Tekstuitlichting",
  "Timeline View": "Tijdlijnweergave",
  "Title font color": "Titellettertype kleur",
  "Desciption font color": "Disciption lettertype kleur",
  "Line color": "Lijnkleur",
  "Date Font color": "Datumlettertype kleur",
  "Daily events background": "Dagelijkse gebeurtenissen achtergrond",
  Alignment: "Uitlijning",
  Vertical: "Verticaal",
  Horizontal: "Horizontaal",
  "Vertical Alignment": "Verticale uitlijning",
  Right: "Rechts",
  Center: "Centrum",
  "Horizontal Alignment": "Horizontale uitlijning",
  Top: "Bovenkant",
  Center: "Centrum",
  Bottom: "Onderkant",
  "Dates Circle Design": "Datums Circle Design",
  "Next To The Circle": "Naast de cirkel",
  "In The Circle": "In de cirkel",
  "Timeline Header": "Tijdlijnkop",
  Timeline: "Tijdlijn",
  "Show only upcoming": "Toon alleen aankomend",
  "Order by": "Bestellen door",
  "Timeline Event Limit": "Limiet van tijdlijngebeurtenissen",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Sta bezoeker toe om evenement toe te voegen aan lokale Calnedars: Google, Yahoo, Outlook, Icicendar.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Sta bezoeker toe om uw evenement te delen met Facebook, LinkedIn, Twitter en enz.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Voeg een zoekoptie toe op uw agenda om mensen uw evenementen te laten zoeken op titel, locatie, etc.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Sta uw gebruikers toe om uw Boom Event -agenda in elke datumbereik af te drukken.",
  "Click to apply a theme to Calendar":
    "Klik om een ​​thema toe te passen op agenda",
  "Date container color": "Datum container kleur",
  "Daily events background": "Dagelijkse gebeurtenissen achtergrond",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Gebruik de add-ons om geavanceerde functies op uw agenda's te installeren, waardoor ze meer functioneel zijn!",
  "Open Add-ons Store": "Open add-ons-winkel",
  Monday: "Maandag",
  Tuesday: "Dinsdag",
  Wednesday: "Woensdag",
  Thursday: "Donderdag",
  Friday: "Vrijdag",
  Saturday: "Zaterdag",
  Sunday: "Zondag",
  "Yearly view": "Jaarlijkse weergave",
  Ascending: "Stijgend",
  "Show event time next to title": "Toon evenemententijd naast de titel",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Pas de datum en tijd van de gebeurtenis aan op de lokale tijd van de gebruiker op basis van hun tijdzone.",
  "Display the time zone alongside the event date.":
    "Geef de tijdzone weer naast de evenementdatum.",
  "Show event time next to title": "Toon evenemententijd naast de titel",
  "Time Zone": "Tijdzone",
  "Upload Image": "Afbeelding uploaden",
  "Choose a Category": "Kies een categorie",
  "Color you have chosen will not be shown as you choose category":
    "Kleur die je hebt gekozen, wordt niet getoond als je categorie kiest",
  Website: "Website",
  Next: "Volgende",
  Save: "Redden",
  "Last Name": "Achternaam",
  "Personal Info": "Persoonlijke informatie",
  Back: "Rug",
  "This field is required": "dit veld is verplicht",
  "Your event has been submitted": "Uw evenement is ingediend",
  "Enter a location": "Voer een locatie in",
  "Display the time zone alongside the event date.":
    "Geef de tijdzone weer naast de evenementdatum.",
  Home: "Thuis",
  "Side By Side Event Limit": "Limiet bij zij aan zij",
  "Mobille App": "Mobille -app",
  category: "categorie",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Houd eenvoudig uw planning bij door uw Facebook-evenementen in uw agenda te importeren.",
  "Synchronized Pages": "Gesynchroniseerde pagina's",
  "There are no synchronized pages": "Er zijn geen gesynchroniseerde pagina's",
  "Choose page": "Kies pagina",
  "You have no events": "Je hebt geen evenementen",
};
export default nl;
