let pt = {
  Categories: "Categorias",
  "Share this event": "Compartilhar este evento",
  Language: "Língua",
  "Show Time Zone": "Mostrar fuso horário",
  "Custom Local Settings": "Configurações locais personalizadas",
  "Add and showcase events on your site using a beautiful calendar.":
    "Adicione e exiba eventos em seu site usando um calendário bonito . ",
  "Week Days": "Dias úteis",
  "Manage Events": "Gerenciar Eventos",
  General: "Geral",
  "Layout Picker": "Selecionador de Layout",
  Month: "Mês",
  Monthly: "Por mês",
  Week: "Semana",
  Weekly: "Semanal",
  Day: "Dia",
  Daily: "Diariamente",
  Agenda: "Agenda",
  "Navigation Buttons": "Botões de Navegação",
  "Week numbers": "Números da semana",
  "Include Weekends": "Incluir fins de semana",
  "All-day": "Dia todo",
  "All Day": "Dia todo",
  Label: "Rótulo",
  "Fit to Height": "Ajustar à altura",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Para definir proporções App manully desabilitar essa opção e redimensionar Calendário no Editor. ",
  "Default Layout": "Layout padrão",
  "Monthly view": "Visualização mensal",
  "Weekly and Daily view": "Vista semanal e diária",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Você pode oferecer aos visitantes uma experiência mais consistente, mostrando o mesmo número de semanas ( 6) de cada vez.",
  "Fixed Weekly Layout": "Layout Semanal Fixo",
  back: "de volta ",
  Row: "Linha",
  "Hours in Weekly View": "Horas na Vista Semanal",
  "Hours in Daily View": "Horas na visualização diária",
  Start: "Começar",
  End: "Fim",
  "At This Hour": "Nesta hora",
  Button: "Botão",
  Buttons: "Botões",
  Sunday: "Domingo",
  Monday: "Segunda-feira",
  Tuesday: "Terça",
  Wednesday: "Quarta-feira",
  Thursday: " Quinta-feira ",
  Friday: "Sexta-feira",
  Saturday: "Sábado",
  "Default Date": "Data padrão",
  year: " ano ",
  month: " mês ",
  mo: " mês ",
  days: " dias ",
  ago: " ago ",
  ahead: " à frente ",
  Yesterday: "Ontem",
  Today: "Hoje",
  Tomorrow: "Amanhã",
  Custom: "Personalizadas",
  "Set Daily Rows Limit": "Definir Limite de Linhas Diárias",
  "Set Proportions": "Definir Proporções",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Permitir que o visitante adicione o evento aos Calendários locais , Google, Yahoo, Outlook, ICalendar . ",
  Container: "Recipiente",
  Background: "Fundo",
  "Container Background": "Fundo do recipiente",
  "Container Borders": "Fronteiras do contêiner",
  Calendar: "Calendário",
  "Event Info Tooltip": "Event Info Tooltip",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Quando as pessoas passam o mouse sobre um evento, elas verão todas as informações sobre ele em uma dica de ferramenta. ",
  "Event Info Window": "Janela de Informações do Evento",
  "This is the full information window that opens when someone clicks on the event.":
    "Esta é a janela de informações completa que se abre quando alguém clica no evento. ",
  "Use Gradient": "Use Gradient",
  Vertical: "Vertical",
  Horizontal: "Horizontal",
  First: "Primeiro",
  Second: "Segundo",
  diagonal: " diagonal ",
  Radial: "Radial",
  "Select option": "Selecionar opção",
  Solid: "Sólido",
  Dotted: "Pontilhado",
  Dashed: "Tracejadas",
  Double: "Em dobro",
  "Border Radius": "Raio da Borda",
  Padding: "Preenchimento",
  "Date Header": "Data de cabeçalho",
  "Event Default Color": "Cor Padrão do Evento",
  "Days of Week": "Dias da semana",
  "Days of Week Background": "Dias de fundo da semana",
  Date: "Encontro",
  "Event Title": "Título do evento",
  "Highlight today": "Destaque hoje",
  "Highlight Color": "Cor de destaque",
  Hide: "Ocultar",
  "Calendar Border Color": "Calendar Border Color",
  "Calendar Border Width": "Largura do limite do calendário",
  "Calendar Border Style": "Estilo de borda do calendário",
  "Font Color": "Cor da fonte",
  "Event Background": "Antecedentes do Evento",
  "Card Date Color": "Cor da data do cartão",
  "Title Font": "Fonte do título",
  "Date Font": "Data da fonte",
  "Description Font": "Descrição da fonte",
  "Button Background": "Botão de fundo",
  "Button Text": "Botão de texto",
  "Border Color": "Cor da borda",
  "Border Width": "Largura da Fronteira",
  "Border Type": "Tipo de Borda",
  Title: "Título",
  Description: "Descrição",
  "Background Color": "Cor de fundo",
  Divider: "Divisor",
  "Event Details Font": "Fonte de detalhes do evento",
  "Website Link Color": "Website Link Color",
  "Developer Info": "Informações do desenvolvedor",
  "User Guide": "Guia de usuario",
  "Support e-mail": "Suporte e-mail",
  "Our Website": "Nosso site",
  "App Review": "App Review",
  "Enjoying App? Leave us a review in the App Market.":
    "Desfrutando App? Deixe-nos um comentário no App Market. ",
  "Review Us": "Revise-nos",
  "Connect With Us": "Conecte-se conosco",
  "What's your email?": "Qual é o seu email? ",
  "Invalid email address!": "Endereço de email inválido! ",
  Comments: "Comentários",
  "We'd love to hear from you. Send us a message.":
    "Gostaríamos muito de ouvir de você. Envie-nos uma mensagem. ",
  "Message must be at least 5 characters long":
    "A mensagem deve ter pelo menos 5 caracteres",
  Send: "Mandar",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Se você quiser permitir que o usuário alterne entre exibições de calendário, ative esta opção e escolha as exibições que deseja exibir. ",
  Main: "a Principal",
  Localize: "Localizar",
  Settings: "Definições",
  Layouts: "Plano",
  Advanced: "Avançado",
  Design: "desenhar",
  Support: "Apoio, suporte",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Todas as configurações locais são (automaticamente) baseadas no seu idioma. Se o seu idioma estiver na lista, não há necessidade de personalizar esta seção.",
  "Date Format": "Formato de data",
  "Time Format": "Formato de hora",
  "Text Direction": "Direção do texto",
  "Left to Right": "Esquerda para a direita",
  "Right to Left": "Direita para esquerda",
  "Week Starts On": "Semana começa em",
  "Agenda Style": "Agenda Style",
  Classic: "Classic",
  Modern: "Modern",
  "Agenda Header": "Cabeçalho da agenda",
  "Upcoming Events": "Próximos eventos",
  "Agenda Event Limit": "Limite de eventos da agenda",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Atualize agora e tenha muito mais recursos e aproveite seu aplicativo na íntegra!",
  "Upgrade Now": "Atualize agora",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Eventos de hospedagem que duram o dia todo? Isso permite que você os mostre no seu calendário.",
  "24 hours": "24 horas",
  Sun: "Dom",
  Mon: "Seg",
  Sat: "Sáb",
  Default: "Predefinição",
  "Select custom design style for your calendar.":
    "Selecione o estilo de design personalizado para o seu calendário.",
  Style: "Estilo",
  "Styles and Colors": "Estilos e cores",
  "Calendar Name": "Nome do calendário",
  "Write your Calendar name here": "Escreva aqui o nome do seu calendário",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Isso não é visível para seus usuários. Defina nomes para diferenciar seus calendários ao usar a função Boom Calendar Sync.",
  "General Info": "Informações gerais",
  Venue: "Local",
  Organizer: "Organizador",
  Search: "Procurar",
  "Add to": "Adicionar à",
  calendar: "calendário",
  "Copy event URL": "Copiar URL do evento",
  "Copied!": "Copiado!",
  "Add & Share": "Adicionar e compartilhar",
  Map: "Mapa",
  "Calendar view": "Kalenderweergave",
  "Add Event": "Voeg evenement toe",
  Uncategorised: "Sem categoria",
  More: "Mais",
  Less: "Menos",
  Register: "Registro",
  Card: "Cartão",
  Guests: "Convidados",
  unlimited: "ilimitado",
  "Show more": "Mostre mais",
  "Enable Search": "Ativar pesquisa",
  "+ Add Event": "+ Adicionar evento",
  "Manage and Sync": "Gerenciar e sincronizar",
  "Show event details as...": "Mostrar detalhes do evento como ...",
  Tooltip: "Sugestão",
  Popup: "Caixa de informação",
  None: "Nenhum",
  "Show Category": "Mostrar categoria",
  "Header Align": "Alinhamento de cabeçalho",
  "Show Time": "Altura de começar",
  "Hours in Weekly/Daily View": "Horas na exibição semanal / diária",
  "Share Events": "Compartilhar Eventos",
  Shadow: "Sombra",
  "Inner Padding": "Estofamento interno",
  Text: "Texto",
  "Active Button Border": "Borda do botão ativo",
  "Light Mode": "Modo de luz",
  "Event Text Color": "Cor do texto do evento",
  Dates: "datas",
  Skeleton: "Esqueleto",
  "Skeleton Color": "Cor do esqueleto",
  Width: "Largura",
  "Skeleton Style": "Estilo esqueleto",
  Color: "Cor",
  "Section Titles": "Títulos da Seção",
  "Section Content": "Conteúdo da seção",
  Header: "Cabeçalho",
  Standard: "Padrão",
  Retro: "Retro",
  Silver: "Prata",
  Night: "Noite",
  Dark: "Sombrio",
  Aubergine: "Beringela",
  "Map Header": "Cabeçalho do Mapa",
  "Show Title in mobile": "Mostrar título no celular",
  "Card View": "Visualização de cartão",
  "Card background color": "Cor de fundo do cartão",
  "Title font": "Fonte do título",
  "Desciption font": "Fonte de descrição",
  "Section font": "Seção de fonte",
  "Section divider color": "Cor do divisor de seção",
  "Add event": "Adicionar Evento",
  "All Day Event": "Evento de dia inteiro",
  Location: "Localização",
  "Choose a category": "Escolha uma categoria",
  "Venue name": "Nome do local",
  "Venue phone": "Telefone local",
  "Venue email": "Email do local",
  "Venue website": "Site do local",
  "Organizer name": "Nome do organizador",
  "Organizer phone": "Telefone organizador",
  "Organizer email": "Email do organizador",
  "Organizer website": "Site do organizador",
  "Personal info": "Informação pessoal",
  "First name": "Primeiro nome",
  "Last name": "Último nome",
  "Email Address": "Endereço de email",
  "Additional Notes": "Notas Adicionais",
  Back: "Costas",
  Save: "Salve ",
  Next: "Próximo",
  "Your event has been submitted": "Seu evento foi enviado",
  "Event submittion has been failed": "O envio do evento falhou",
  "e.g. Birthday Party": "por exemplo. Festa de aniversário",
  "First Name": "Primeiro nome",
  "Last Name": "Último nome",
  "Phone Number": "Número de telefone",
  Address: "Endereço",
  "Your comments": "Os teus comentários",
  "How many guests?": "Quantos convidados?",
  "Anything else we need to know?": "Mais alguma coisa que precisamos saber?",
  "Guests:": "Convidados:",
  Submit: "Enviar",
  "Go to Calendar": "Vá para o calendário",
  "Registration completed successfully!": "Registro concluído com sucesso!",
  "Please check your registered email address":
    "Por favor, verifique o seu endereço de e-mail registrado",
  "Add to Calendar": "Adicionar ao calendário",
  "Share this Event": "Compartilhar este evento",
  "Sorry something went wrong": "Desculpe, algo deu errado",
  "Back to registration": "กลับไปที่การลงทะเบียน",
  "Date & Location": "Data e local",
  "Date & Time": "Data hora",
  home: "casa",
  "Header align": "Cabeçalho alinhar",
  Footer: "Rodapé",
  "Categories Filter": "filtro de categorias",
  "Show only upcoming": "Mostrar apenas os próximos",
  "Card(s) in a row": "Cartão (s) em uma linha",
  "Space between cards": "Espaço entre cartas",
  "Shown events limit": "Limite de eventos mostrados",
  "Style 1": "Estilo 1",
  "Style 2": "Estilo 2",
  "Style 3": "Estilo 3",
  "Style 4": "Estilo 4",
  "Buttons & Links": "Botões e links",
  "Button corner radius": "Raio do canto do botão",
  "Buttons font": "Fonte de botões",
  "Buttons background": "Fundo dos botões",
  "Get notified by Email": "Seja notificado por e-mail",
  "Review events": "Rever eventos",
  "Click on date": "Clique na data",
  "Add Event button": "Botão Adicionar Evento",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "A sincronização do calendário permite que você integre seus eventos e sessões com o seu calendário Boom.",
  connect: "conectar",
  "Synchronized Calendars": "Calendários sincronizados",
  "Import events": "Importar eventos",
  Disconnect: "desconectar",
  "Choose calendar": "Escolha o calendário",
  "Monitor your Wix events through the sync feature":
    "Monitore seus eventos Wix por meio do recurso de sincronização",
  "Connect all your Boom calendars available on your website":
    "Conecte todos os seus calendários Boom disponíveis em seu site",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Agende, participe e gerencie reuniões do Zoom direto por meio do nosso Calendário Boom.",
  "Monitor your Event Brite events through the Event Brite sync feature..":
    "Monitore seus eventos do Event Brite por meio do recurso de sincronização do Event Brite",
  Email: "O email",
  "Add-ons": "Add-ons",
  "Receive notification emails as soon as users add events to your calendar.":
    "Receba e-mails de notificação assim que os usuários adicionem eventos ao seu calendário.",
  "Enable + button on the calendar header":
    "Ativar + botão no cabeçalho do calendário",
  "Accept or decline events added by customers before making them public.":
    "Aceitar ou recusar eventos adicionados pelos clientes antes de torná-los públicos.",
  "Switch Add Event": "Switch adicionar evento",
  "Enable your browser cookies to connect to your account.":
    "Ative seus cookies do navegador para se conectarem à sua conta.",
  "Learn more": "Saber mais",
  "Print Button": "Botão de impressão",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Permita que seus usuários imprimem seu calendário de eventos de boom em qualquer intervalo de datas.",
  "Show Title on mobile": "Mostrar título no celular",
  "Show Skeleton on mobile": "Mostrar esqueleto no celular",
  "Start 7-day Business trial": "Comece seu teste de negócios de 7 dias",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Aproveite todos os recursos ilimitados, como ingressos de venda, inscrição, add-ons de eventos de visitantes.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Por favor, note: No final do período de teste, você será devolvido ao seu plano de assinatura existente.",
  "Not Now": "Agora não",
  "Start free trial": "Iniciar teste gratuito",
  "Congrats!": "Parabéns!",
  "Your 7-day Business trial has been successfully activated.":
    "Seu teste de negócios de 7 dias foi ativado com sucesso.",
  Done: "Feita",
  "Title font color": "Cor da fonte do título.",
  "Desciption font color": "Descrição Cor da fonte",
  "Section font color": "Cor da fonte de seção",
  "Card Header": "Cabeçalho de cartão",
  Category: "Categoria",
  "Display at the": "Exibir no",
  top: "principal",
  bottom: "fundo",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Showcase o filtro de categoria na parte superior ou na parte inferior do calendário.As configurações se aplica apenas à agenda e visualizações de cartão",
  "Processing your events": "Processando seus eventos",
  "Search for events": "Procure por eventos",
  "There are no events added": "Não há eventos adicionados",
  "Location: To be determined": "Localização: para ser determinado",
  "No events for selected date": "Nenhum evento para a data selecionada",
  Uncategorized: "Sem categoria",
  "Edit event": "Evento de edição",
  "Edit original event": "Edite o evento original",
  "Copy event": "Evento de cópia",
  "Copy as new event": "Cópia como novo evento",
  "Delete event": "Excluir evento",
  "Stop repeating on this date": "Pare de repetir nesta data",
  "Exclude this date": "Exclua esta data",
  "Location is going to be announced": "A localização será anunciada",
  "Fill your personal information": "Preencha suas informações pessoais",
  "Check Box": "Caixa de seleção",
  "Single Choice": "Escolha única",
  Option: "Opção",
  "Share Event": "Evento de compartilhamento",
  "Oops! Something went wrong": "Opa!Algo deu errado",
  "We are sorry this event has already taken place":
    "Lamentamos que este evento já tenha ocorrido",
  "Back to calendar": "De volta ao calendário",
  "This field is required": "Este campo é obrigatório",
  Phone: "Telefone",
  "Number field": "Campo numérico",
  "Please provide a valid email": "Por favor forneça um email válido",
  "Select at least one option": "Selecione pelo menos uma opção",
  "Choose tickets to see total value":
    "Escolha ingressos para ver o valor total",
  tickets: "ingressos",
  "Choose Tickets": "Escolha ingressos",
  "Choose payment method": "escolha o método de pagamento",
  Pay: "Pagar",
  Total: "Total",
  Free: "Livre",
  "Buy tickets": "Comprar bilhetes",
  "Sold Out": "Vendido",
  "Tickets are available": "Os ingressos estão disponíveis",
  "Sales End": "Vendas terminam",
  "Availible from": "disponível a partir de",
  "Go to Orders": "Vá para ordens",
  "Go to Details": "Vá para detalhes",
  "Group ticket": "Bilhete em grupo",
  Name: "Nome",
  Price: "Preço",
  "Order by": "Ordenar por",
  "Order ID": "ID do pedido",
  Applied: "Aplicado",
  Fees: "Honorários",
  "Enter promo code": "Insira o código promocional",
  Apply: "Aplicar",
  "Promo Code": "Código promocional",
  Cash: "Dinheiro",
  "You can find your e-tickets attached to your email or download them":
    "Você pode encontrar seus bilhetes eletrônicos anexados ao seu e-mail ou baixá-los",
  here: "aqui",
  Time: "Tempo",
  "Invalid promo code": "Código promocional inválido",
  "Credit card": "Cartão de crédito",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Em breve, você receberá uma mensagem de confirmação do registro bem -sucedido no seu endereço de e -mail.",
  "You can also check your order details below.":
    "Você também pode verificar os detalhes do seu pedido abaixo.",
  at: "no",
  Buy: "Comprar",
  Donation: "Doação",
  "Enter price": "Empreendimento",
  Choose: "Escolher",
  Chosen: "Escolhido",
  "Choose your plan": "Escolha o seu plano",
  week: "semana",
  wk: "semana",
  "Choose plan cycle": "Escolha o ciclo do plano",
  months: "meses",
  years: "anos",
  weeks: "semanas",
  "Copy Event Url": "Copiar URL do evento",
  "You can find your e-tickets attached to your email or print them":
    "Você pode encontrar seus bilhetes eletrônicos anexados ao seu e-mail ou imprimi-los",
  "Guest Info": "Informações do convidado",
  "Ticket Info": "Informações do ingresso",
  "Ticket name": "Nome do ingresso",
  "Ticket price": "Preço do bilhete",
  "Ticket ID": "ID do ingresso",
  "If you have any questions contact to organizer":
    "Se você tiver alguma dúvida, entre em contato com o organizador",
  "As soon as event ends": "Assim que o evento termina",
  "1 day after event ends": "1 dia após o término do evento",
  "7 days after event ends": "7 dias após o término do evento",
  "14 days after event ends": "14 dias após o término do evento",
  "30 days after event ends": "30 dias após o término do evento",
  Menu: "Cardápio",
  "No event for selected date": "Nenhum evento para a data selecionada",
  view: "visualizar",
  List: "Lista",
  Year: "Ano",
  Yearly: "Anual",
  "Year view header": "Ano Visualize cabeçalho",
  "Yearly Style": "Estilo anual",
  "There are no events": "Não há eventos",
  Autotranslation: "Autotranslação",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Uma vez ativado, seu widget de calendário será traduzido com base no idioma do site.* Observe que, desde que o título de calendário e as descrições sejam textos inseridos, eles não podem ser traduzidos.",
  "Note on mobile": "Nota no celular",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Desligue ou altere o texto da barra 'No Eventos' na versão móvel do Calendário",
  Autodeletion: "Autodeleção",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Habilitando a opção, removerá automaticamente seus eventos anteriores do calendário.",
  "This does not apply to repeating events!":
    "Isso não se aplica a eventos repetidos!",
  "Notify event creators about the guest":
    "Notificar os utilizadores sobre o convidado",
  "Send event creators notification emails as soon as guests register for their events":
    "Enviar e-mails de notificação aos criadores de eventos assim que os convidados se registarem nos seus eventos",
  "List View Type": "Lista View Type",
  "Description font": "Fonte de descrição",
  Connect: "conectar",
  "You have no events": "Você não tem eventos",
  Synchronize: "Sincronizar",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "A sincronização do Google Calendar permite que você integre seus eventos e sessões com o Boom Calendar.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "O Outlook Calendar Sync permite integrar seus eventos e sessões com seu calendário de boom.",
  "Your message has been sent successfully!":
    "Sua mensagem foi enviada com sucesso!",
  "There are no synchronized calendars": "Não há calendários sincronizados",
  "to view more than 7 events": "Para ver mais de 7 eventos",
  "Mobile app": "Aplicativo móvel",
  "Admin Account": "Conta de administrador",
  Password: "Senha",
  "Second User": "Segundo usuário",
  Edit: "Editar",
  "Guest limit": "Limite de convidado",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Todas as configurações locais são (automaticamente) com base no seu idioma.Se o seu idioma estiver na lista, não há necessidade de personalizar esta seção.",
  available: "acessível",
  next: "Next",
  Tickets: "Ingressos",
  Quantity: "Quantidade",
  "Promo code": "Código promocional",
  "Select a payment method": "Selecione um método de pagamento",
  Fee: "Taxa",
  Book: "Livro",
  "All the tickets have been sold out": "Todos os ingressos foram vendidos",
  "Choose at least one ticket": "Escolha pelo menos um bilhete",
  "First choose ticket": "Primeiro escolha o bilhete",
  "Please fill out your personal information.":
    "Por favor, preencha suas informações pessoais.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "Para fazer uma compra bem-sucedida, selecione seu método de pagamento preferido e insira o código promocional para bilhetes com desconto.",
  "Credit/Debit card": "Cartão de Crédito / Débito",
  "print here.": "Imprima aqui.",
  "QR code for all tickets": "Código QR para todos os ingressos",
  Duration: "Duração",
  "Full Name": "Nome completo",
  "Ticket id": "ID do ingresso",
  "Group id": "ID do grupo",
  "Choose your ticket.": "Escolha o seu bilhete.",
  "Fill out your personal information.": "Preencha suas informações pessoais.",
  "Add the payment details.": "Adicione os detalhes de pagamento.",
  "To be determined": "Estar determinado",
  "You can find your e-tickets attached to the email or":
    "Você pode encontrar seus e-tickets anexados ao email ou",
  "print here": "Imprima aqui",
  "Full name": "Nome completo",
  "Group ID": "ID do grupo",
  "to Book": "agendar",
  "Unfortunately, your card has been declined":
    "Infelizmente, seu cartão foi recusado",
  "Thank you for your purchase!": "Obrigado pela sua compra!",
  "Find your printable e-tickets attached to the confirmation email":
    "Encontre seus bilhetes eletrônicos imprimíveis anexados ao e-mail de confirmação",
  Confirm: "confirme",

  "Add event": "Adicionar Evento",
  Events: "Eventos",
  "Event details": "Detalhes do evento",
  Registration: "Cadastro",
  "Guests list": "Lista de convidados",
  Ticket: "Bilhete",
  "General Info": "Informações gerais",
  "Customize the general settings of your event":
    "Personalize as configurações gerais do seu evento",
  "Event Title": "Título do evento",
  "e.g. Birthday Party": "por exemplo. Festa de aniversário",
  "All Day Event": "Evento durante todo o dia",
  Cross: "Cruzar",
  Timeline: "Linha do tempo",
  "Repeating event": "Evento de repetição",
  Location: "Localização",
  "Venue name": "Nome do local",
  Description: "Descrição",
  Image: "Imagem",
  Color: "Cor",
  Category: "Categoria",
  "Add your events to color categories and let your users classify them easily":
    "Adicione seus eventos às categorias de cores e deixe seus usuários classificá -los facilmente",
  "Category name": "Nome da Categoria",
  "e.g. Birthdays": "por exemplo. Aniversários",
  Venue: "Local",
  "Where the event takes place": "Onde o evento acontece",
  "Venue name": "Nome do local",
  "Venue phone": "Telefone do local",
  "Venue email": "E -mail do local",
  "Venue website": "Site do local",
  Organizer: "Organizador",
  "Person who makes the event": "Pessoa que faz o evento",
  "Organizer name": "Nome do organizador",
  "Organizer phone": "Telefone organizador",
  "Organizer email": "Email do organizador",
  "Organizer website": "Site do Organizador",
  Save: "Salvar",
  Cancel: "Cancelar",
  Import: "Importar",
  Past: "Passado",
  All: "Todos",
  Upcoming: "Por vir",
  Uncategorised: "Sem categorizado",
  "Date Ascending": "Data ascendente",
  "Date Descending": "Data descendente",
  "Title by A-Z": "Título de A-Z",
  "Title by Z-A": "Título por Z-A",
  "There are no events for this period": "Não há eventos para este período",

  "Auto-Convert Date & Time": "Data e hora de conversação automática",
  TimeZone: "Fuso horário",
  Autodeletion: "Autodeleção",
  "Layout Settings": "Configurações de Layout",
  "Yeatly view": "Você veja",
  "Monthly view header": "Cabeçalho de visualização mensal",
  "Weekly/Daily view header": "Cabeçalho semanal/diário",
  Acendings: "Acendings",
  Descending: "descendente",
  Standart: "padrão",
  Silver: "Prata",
  Retro: "Retro",
  Dark: "Escuro",
  Night: "Noite",
  Aubergine: "Beringela",
  "List view header": "Lista Visualize cabeçalho",
  "Side by Side View": "Vista lado a lado",
  "Customize Proportions": "Personalize proporções",
  "Card Margins": "Margens de cartão",
  "Image opacity (%)": "Opacidade da imagem (%)",
  "Side by Side Header": "Cabeçalho lado a lado",
  "Text Align": "Alinhamento de texto",
  "Timeline View": "Visualização da linha do tempo",
  "Title font color": "Cor da fonte do título",
  "Desciption font color": "Cor da fonte de descrição",
  "Line color": "Cor da linha",
  "Date Font color": "Data de cor da fonte",
  "Daily events background": "Antecedentes de eventos diários",
  Alignment: "Alinhamento",
  Vertical: "Vertical",
  Horizontal: "Horizontal",
  "Vertical Alignment": "Alinhamento vertical",
  Right: "Certo",
  Center: "Centro",
  "Horizontal Alignment": "Alinhamento horizontal",
  Top: "Principal",
  Center: "Centro",
  Bottom: "Fundo",
  "Dates Circle Design": "Datas Circle Design",
  "Next To The Circle": "Próximo ao círculo",
  "In The Circle": "No círculo",
  "Timeline Header": "Cabeçalho da linha do tempo",
  Timeline: "Linha do tempo",
  "Show only upcoming": "Mostre apenas",
  "Order by": "Ordenar por",
  "Timeline Event Limit": "Limite do evento da linha do tempo",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Permita que o visitante adicione o evento aos Calnendars locais: Google, Yahoo, Outlook, ICalendar.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Permita que o visitante compartilhe seu evento no Facebook, LinkedIn, Twitter e etc.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Adicione uma opção de pesquisa no seu calendário para permitir que as pessoas pesquisem seus eventos por título, local, etc.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Permita que seus usuários imprimam seu calendário de eventos de boom em qualquer intervalo de data.",
  "Click to apply a theme to Calendar":
    "Clique para aplicar um tema ao calendário",
  "Date container color": "Data da cor do contêiner",
  "Daily events background": "Antecedentes de eventos diários",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Use os complementos para instalar recursos avançados em seus calendários, tornando-os mais funcionais!",
  "Open Add-ons Store": "Aberto da loja de complementos",
  Monday: "Segunda-feira",
  Tuesday: "Terça-feira",
  Wednesday: "Quarta-feira",
  Thursday: "Quinta-feira",
  Friday: "Sexta-feira",
  Saturday: "Sábado",
  Sunday: "Domingo",
  "Yearly view": "Visualização anual",
  Ascending: "Ascendente",
  "Show event time next to title": "Mostrar hora do evento ao lado do título",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Ajuste a data e hora do evento para a hora local do usuário com base no fuso horário.",
  "Display the time zone alongside the event date.":
    "Exiba o fuso horário ao lado da data do evento.",
  "Show event time next to title": "Mostrar hora do evento ao lado do título",
  "Time Zone": "Fuso horário",
  "Upload Image": "Enviar Imagem",
  "Choose a Category": "Escolha uma categoria",
  "Color you have chosen will not be shown as you choose category":
    "Cor que você escolheu não será mostrada como você escolher a categoria",
  Website: "Local na rede Internet",
  Next: "Próximo",
  Save: "Salvar",
  "Last Name": "Sobrenome",
  "Personal Info": "Informação pessoal",
  Back: "Voltar",
  "This field is required": "Este campo é obrigatório",
  "Your event has been submitted": "Seu evento foi enviado",
  "Enter a location": "Digite um local",
  "Display the time zone alongside the event date.":
    "Exiba o fuso horário ao lado da data do evento.",
  Home: "Lar",
  "Side By Side Event Limit": "Limite de evento lado a lado",
  "Mobille App": "Mobille App",
  category: "categoria",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Acompanhe sua agenda facilmente importando seus eventos do Facebook para o seu calendário.",
  "Synchronized Pages": "Páginas sincronizadas",
  "There are no synchronized pages": "Não há páginas sincronizadas",
  "Choose page": "Escolha a página",
  "You have no events": "Você não tem eventos",
};
export default pt;
