let ro = {
  Categories: "Categorii",
  "Share this event": "Împărtășiți acest eveniment",
  Language: "Limba",
  "Show Time Zone": "Arată fusul orar",
  "Custom Local Settings": "Setări locale personalizate",
  "Add and showcase events on your site using a beautiful calendar.":
    "Adăugați și prezentați evenimente pe site -ul dvs. folosind un calendar frumos.",
  "Week Days": "Zilele saptamanii",
  "Manage Events": "Gestionați evenimentele",
  General: "General",
  "Layout Picker": "Picker de aspect",
  Month: "Lună",
  Monthly: "Lunar",
  Week: "Săptămână",
  Weekly: "Săptămânal",
  Day: "Zi",
  Daily: "Zilnic",
  Agenda: "Agendă",
  "Navigation Buttons": "Butoane de navigare",
  "Week numbers": "Numere de săptămână",
  "Include Weekends": "Includeți weekendurile",
  "All-day": "Toată ziua",
  "All Day": "Toată ziua",
  Label: "Eticheta",
  "Fit to Height": "Se potrivesc la înălțime",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Pentru a seta proporții de aplicații, dezactivați această opțiune și redimensionați calendarul în editor.",
  "Default Layout": "Aspect implicit",
  "Monthly view": "Vizualizare lunară",
  "Weekly and Daily view": "Vedere săptămânală și zilnică",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Puteți oferi vizitatorilor o experiență mai consistentă, arătând același număr de săptămâni (6) simultan.",
  "Fixed Weekly Layout": "Aspect săptămânal fix",
  back: "înapoi",
  Row: "Rând",
  "Hours in Weekly View": "Ore în vedere săptămânală",
  "Hours in Daily View": "Ore în vedere zilnic",
  Start: "start",
  End: "Sfârşit",
  "At This Hour": "La ora asta",
  Button: "Buton",
  Buttons: "Butoane",
  Sunday: "duminică",
  Monday: "luni",
  Tuesday: "marţi",
  Wednesday: "miercuri",
  Thursday: "joi",
  Friday: "vineri",
  Saturday: "sâmbătă",
  "Default Date": "Data implicită",
  year: "an",
  month: "lună",
  mo: "Mo.",
  days: "zile",
  ago: "în urmă",
  ahead: "înainte",
  Yesterday: "Ieri",
  Today: "Astăzi",
  Tomorrow: "Mâine",
  Custom: "Personalizat",
  "Set Daily Rows Limit": "Setați limita de rânduri zilnice",
  "Set Proportions": "Setați proporții",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Permiteți vizitatorului să adauge eveniment la Calnedars local: Google, Yahoo, Outlook, Icalendar.",
  Container: "Container",
  Background: "fundal",
  "Container Background": "Fundal container",
  "Container Borders": "Granițe de containere",
  Calendar: "Calendar",
  "Event Info Tooltip": "Informații despre eveniment Tooltip",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Când oamenii trec peste un eveniment, vor vedea toate informațiile despre acesta într -un instrument.",
  "Event Info Window": "Fereastra de informații despre eveniment",
  "This is the full information window that opens when someone clicks on the event.":
    "Aceasta este fereastra completă a informațiilor care se deschide atunci când cineva face clic pe eveniment.",
  "Use Gradient": "Folosiți gradient",
  Vertical: "Vertical",
  Horizontal: "Orizontală",
  First: "Primul",
  Second: "Al doilea",
  diagonal: "diagonală",
  Radial: "Radial",
  "Select option": "Selectați opțiunea",
  Solid: "Solid",
  Dotted: "Punctat",
  Dashed: "Înroșit",
  Double: "Dubla",
  "Border Radius": "Raza de frontieră",
  Padding: "Căptușeală",
  "Date Header": "Antetul datei",
  "Event Default Color": "Culoarea implicită a evenimentului",
  "Days of Week": "Zilele saptamanii",
  "Days of Week Background": "Zilele săptămânii Fundal",
  Date: "Data",
  "Event Title": "Titlul evenimentului",
  "Highlight today": "Evidențiază astăzi",
  "Highlight Color": "Evidențiați culoarea",
  Hide: "Ascunde",
  "Calendar Border Color": "Culoarea de frontieră calendaristică",
  "Calendar Border Width": "Lățimea frontierei din calendar",
  "Calendar Border Style": "Stilul de frontieră calendaristic",
  "Font Color": "Culoarea fontului",
  "Event Background": "Istoric eveniment",
  "Card Date Color": "Culoarea datei cardului",
  "Title Font": "Font de titlu",
  "Date Font": "Font de date",
  "Description Font": "Descriere font",
  "Button Background": "Fundal buton",
  "Button Text": "Text buton",
  "Border Color": "Culoarea de frontieră",
  "Border Width": "Lățimea graniței",
  "Border Type": "Tip de frontieră",
  Title: "Titlu",
  Description: "Descriere",
  "Background Color": "Culoare de fundal",
  Divider: "Divizor",
  "Event Details Font": "Detalii despre eveniment font",
  "Website Link Color": "Culoarea link -ului site -ului web",
  "Developer Info": "Informații despre dezvoltator",
  "User Guide": "Manualul utilizatorului",
  "Support e-mail": "Sprijinirea e-mailului",
  "Our Website": "Siteul nostru",
  "App Review": "Revizuirea aplicației",
  "Enjoying App? Leave us a review in the App Market.":
    "Te bucuri de aplicație? Lasă -ne o recenzie pe piața aplicațiilor.",
  "Review Us": "Examinați -ne",
  "Connect With Us": "Conecteaza-te cu noi",
  "What's your email?": "Care este emailul tau?",
  "Invalid email address!": "Adresa email invalida!",
  Comments: "Comentarii",
  "We'd love to hear from you. Send us a message.":
    "Ne-am bucura sa primim vesti de la tine. Trimite-ne un mesaj.",
  "Message must be at least 5 characters long":
    "Mesajul trebuie să aibă cel puțin 5 caractere",
  Send: "Trimite",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Dacă doriți să permiteți utilizatorului să comute între vizualizările din calendar, activați această opțiune și alegeți vizualizările pe care doriți să le afișați.",
  Main: "Principal",
  Localize: "Localiza",
  Settings: "Setări",
  Layouts: "Machete",
  Advanced: "Avansat",
  Design: "Proiecta",
  Support: "A sustine",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Toate setările locale sunt (automat) bazate pe limba dvs. Dacă limba dvs. este pe listă, nu este nevoie să personalizați această secțiune.",
  "Date Format": "Formatul datei",
  "Time Format": "Format de timp",
  "Text Direction": "Direcția textului",
  "Left to Right": "De la stânga la dreapta",
  "Right to Left": "De la dreapta la stanga",
  "Week Starts On": "Săptămâna începe",
  "Agenda Style": "Stilul agendei",
  Classic: "Clasic",
  Modern: "Modern",
  "Agenda Header": "Antetul agendei",
  "Upcoming Events": "evenimente viitoare",
  "Agenda Event Limit": "Limita evenimentului de pe agendă",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Actualizați acum și obțineți mult mai multe funcții și bucurați -vă de aplicația dvs. integral!",
  "Upgrade Now": "Imbunatateste acum",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Găzduind evenimente care durează toată ziua? Acest lucru vă permite să le arătați în calendarul dvs.",
  "24 hours": "24 de ore",
  Sat: "Sat",
  Sun: "Soare",
  Mon: "Luni",
  Default: "Mod implicit",
  "Select custom design style for your calendar.":
    "Selectați stil de design personalizat pentru calendarul dvs.",
  Style: "Stil",
  "Styles and Colors": "Stiluri și culori",
  "Calendar Name": "Numele calendarului",
  "Write your Calendar name here": "Scrie -ți numele de calendar aici",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Acest lucru nu este vizibil pentru utilizatorii dvs. Setați nume pentru a diferenția calendarele atunci când utilizați funcția de sincronizare a calendarului Boom.",
  "General Info": "Informatii generale",
  Venue: "Loc",
  Organizer: "Organizator",
  Search: "Căutare",
  "Add to": "Adaugă la",
  calendar: "calendar",
  "Copy event URL": "Copiați URL -ul evenimentului",
  "Copied!": "S -A copiat!",
  "Add & Share": "Adăugați și partajați",
  Map: "Hartă",
  "Calendar view": "Vizualizare calendaristică",
  "Add Event": "Adăugați eveniment",
  Uncategorised: "Necategorizat",
  More: "Mai mult",
  Less: "Mai puțin",
  Register: "Inregistreaza-te",
  Card: "Card",
  Guests: "Vizitatori",
  unlimited: "nelimitat",
  "Show more": "Afișați mai multe",
  "Enable Search": "Activați căutarea",
  "+ Add Event": " + Adăugați eveniment",
  "Manage and Sync": "Gestionează și sincronizează",
  "Show event details as...": "Afișați detaliile evenimentului ca ...",
  Tooltip: "Tooltip",
  Popup: "Pop-up",
  None: "Nici unul",
  "Show Category": "Categoria arată",
  "Header Align": "Antetul se aliniază",
  "Show Time": "Arată timpul",
  "Hours in Weekly/Daily View": "Ore în vedere săptămânal/zilnic",
  "Share Events": "Împărtășiți evenimente",
  Shadow: "Umbră",
  "Inner Padding": "Căptușeală interioară",
  Text: "Text",
  "Active Button Border": "Bord buton activ",
  "Light Mode": "Mod de lumină",
  "Event Text Color": "Culoarea textului evenimentului",
  Dates: "Datele",
  Skeleton: "Schelet",
  "Skeleton Color": "Culoarea scheletului",
  Width: "Lăţime",
  "Skeleton Style": "Stilul scheletului",
  Color: "Culoare",
  "Section Titles": "Titluri de secțiune",
  "Section Content": "Conținut de secțiune",
  Header: "Antet",
  Standard: "Standard",
  Retro: "Retro",
  Silver: "Argint",
  Night: "Noapte",
  Dark: "Întuneric",
  Aubergine: "Vânătă",
  "Map Header": "Antetul hărții",
  "Show Title in mobile": "Afișați titlul în mobil",
  "Card View": "Vizualizare card",
  "Card background color": "Culoarea de fundal a cardului",
  "Title font": "Font de titlu",
  "Desciption font": "FONT DE DESCIPȚIE",
  "Section font": "Font secțiune",
  "Section divider color": "Culoarea divizorului de secțiune",
  "Add event": "Adăugați eveniment",
  "All Day Event": "Eveniment pe intreaga zi",
  Location: "Locație",
  "Choose a category": "Alege o categorie",
  "Venue name": "Numele locului de întâlnire",
  "Venue phone": "Telefon",
  "Venue email": "E -mail de locație",
  "Venue website": "Site -ul locului",
  "Organizer name": "Numele organizatorului",
  "Organizer phone": "Telefon organizator",
  "Organizer email": "E -mail de organizator",
  "Organizer website": "Site -ul organizatorului",
  "Personal info": "Informatie personala",
  "First name": "Nume",
  "Last name": "Nume",
  "Email Address": "Adresa de e-mail",
  "Additional Notes": "Note Aditionale",
  Back: "Înapoi",
  Save: "Salvați",
  Next: "Următorul",
  "Your event has been submitted": "Evenimentul dvs. a fost trimis",
  "Event submittion has been failed": "Trimiterea evenimentelor a fost eșuată",
  "e.g. Birthday Party": "de exemplu. Petrecere de aniversare",
  "First Name": "Nume",
  "Last Name": "Nume",
  "Phone Number": "Număr de telefon",
  Address: "Abordare",
  "Your comments": "Comentariile dumneavoastră",
  "How many guests?": "Câți invitați?",
  "Anything else we need to know?": "Mai trebuie să știm ceva?",
  "Guests:": "Vizitatori:",
  Submit: "Trimite",
  "Go to Calendar": "Mergeți la Calendar",
  "Registration completed successfully!": "Înregistrarea finalizată cu succes!",
  "Please check your registered email address":
    "Vă rugăm să verificați adresa de e -mail înregistrată",
  "Add to Calendar": "Adăugați în calendar",
  "Share this Event": "Împărtășiți acest eveniment",
  "Sorry something went wrong": "Scuze, ceva a mers greșit",
  "Back to registration": "Înapoi la înregistrare",
  "Date & Location": "Data și locația",
  "Date & Time": "Data și ora",
  home: "Acasă",
  "Header align": "Antetul se aliniază",
  Footer: "Subsol",
  "Categories Filter": "Categorii filtrează",
  "Show only upcoming": "Arată doar viitor",
  "Card(s) in a row": "Carduri (cărți) la rând",
  "Space between cards": "Spațiu între cărți",
  "Shown events limit": "Limita evenimentelor afișate",
  "Style 1": "Stilul 1",
  "Style 2": "Stilul 2",
  "Style 3": "Stilul 3",
  "Style 4": "Stilul 4",
  "Buttons & Links": "Butoane și link -uri",
  "Button corner radius": "Raza colțului butonului",
  "Buttons font": "Font butoane",
  "Buttons background": "Fundal butoane",
  "Get notified by Email": "Obțineți notificarea prin e -mail",
  "Review events": "Examinați evenimentele",
  "Click on date": "Faceți clic pe data",
  "Add Event button": "Adăugați butonul evenimentului",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Calendar Sync vă permite să vă integrați evenimentele și sesiunile cu calendarul dvs. de boom.",
  connect: "conectați",
  "Synchronized Calendars": "Calendare sincronizate",
  "Import events": "Import evenimente",
  Disconnect: "Deconectat",
  "Choose calendar": "Alege Calendar",
  "Monitor your Wix events through the sync feature":
    "Monitorizați -vă evenimentele WIX prin funcția de sincronizare",
  "Connect all your Boom calendars available on your website":
    "Conectați toate calendarele dvs. de boom disponibile pe site -ul dvs. web",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Programează -te, alătură -te și gestionează întâlnirile zoom chiar prin calendarul nostru de boom.",
  "Monitor your Event Brite events through the Event Brite sync feature..":
    "Monitorizați -vă evenimentele BRITE EVENIMENT prin funcția de sincronizare Brite Event Brite",
  Email: "E-mail",
  "Add-ons": "Suplimente",
  "Receive notification emails as soon as users add events to your calendar.":
    "Primiți e -mailuri de notificare imediat ce utilizatorii adaugă evenimente în calendarul dvs.",
  "Enable + button on the calendar header":
    "Activați butonul + pe antetul calendarului",
  "Accept or decline events added by customers before making them public.":
    "Acceptați sau refuzați evenimentele adăugate de clienți înainte de a le face publice.",
  "Switch Add Event": "Comutați adăugați eveniment",
  "Enable your browser cookies to connect to your account.":
    "Activați cookie -urile browserului dvs. să se conecteze la contul dvs.",
  "Learn more": "Află mai multe",
  "Print Button": "Buton de imprimare",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Permiteți -vă utilizatorilor să vă imprime calendarul de evenimente Boom în orice interval de date.",
  "Show Title on mobile": "Afișați titlul pe mobil",
  "Show Skeleton on mobile": "Afișați scheletul pe mobil",
  "Start 7-day Business trial": "Începeți procesul de afaceri de 7 zile",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Bucurați-vă de toate caracteristicile nelimitate, cum ar fi vânzarea biletelor, înregistrării, suplimentelor pentru evenimente pentru vizitatori.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Vă rugăm să rețineți: La sfârșitul perioadei de încercare, veți fi returnat la planul dvs. de abonament existent.",
  "Not Now": "Nu acum",
  "Start free trial": "Incepe o probă gratuită",
  "Congrats!": "Felicitări!",
  "Your 7-day Business trial has been successfully activated.":
    "Procesul dvs. de afaceri de 7 zile a fost activat cu succes.",
  Done: "Terminat",
  "Title font color": "Culoarea fontului de titlu",
  "Desciption font color": "Culoarea fontului descifrată",
  "Section font color": "Secțiunea Culoarea fontului",
  "Card Header": "Antetul cardului",
  Category: "Categorie",
  "Display at the": "Afișare la",
  top: "top",
  bottom: "fund",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Prezentați filtrul de categorie în partea de sus sau în partea de jos a calendarului. Setările se aplică numai pentru vizualizări ale agendei și cardului",
  "Processing your events": "Procesarea evenimentelor dvs.",
  "Search for events": "Căutați evenimente",
  "There are no events added": "Nu există evenimente adăugate",
  "Location: To be determined": "Locație: Pentru a fi determinată",
  "No events for selected date": "Nu există evenimente pentru data selectată",
  Uncategorized: "Necategorizat",
  "Edit event": "Editați evenimentul",
  "Edit original event": "Editați evenimentul original",
  "Copy event": "Eveniment de copiere",
  "Copy as new event": "Copiați ca nou eveniment",
  "Delete event": "Ștergeți evenimentul",
  "Stop repeating on this date": "Nu mai repeta la această dată",
  "Exclude this date": "Excludeți această dată",
  "Location is going to be announced": "Locația va fi anunțată",
  "Fill your personal information": "Completați -vă informațiile personale",
  "Check Box": "Caseta de bifat",
  "Single Choice": "O singură alegere",
  Option: "Opțiune",
  "Share Event": "Eveniment de partajare",
  "Oops! Something went wrong": "! Ceva n-a mers bine",
  "We are sorry this event has already taken place":
    "Ne pare rău că acest eveniment a avut loc deja",
  "Back to calendar": "Înapoi la calendar",
  "This field is required": "Acest câmp este obligatoriu",
  Phone: "Telefon",
  "Number field": "Câmp numeric",
  "Please provide a valid email": "Vă rugăm să furnizați un e -mail valid",
  "Select at least one option": "Selectați cel puțin o opțiune",
  "Choose tickets to see total value":
    "Alegeți bilete pentru a vedea valoarea totală",
  tickets: "Bilete",
  "Choose Tickets": "Alegeți bilete",
  "Choose payment method": "Alege metoda de plata",
  Pay: "A plati",
  Total: "Total",
  Free: "Gratuit",
  "Buy tickets": "Cumpara bilete",
  "Sold Out": "Vândut",
  "Tickets are available": "Biletele sunt disponibile",
  "Sales End": "Finalul vânzărilor",
  "Availible from": "Disponibil de la",
  "Go to Orders": "Mergeți la comenzi",
  "Go to Details": "Accesați detalii",
  "Group ticket": "Bilet de grup",
  Name: "Nume",
  Price: "Preț",
  "Order by": "Comanda de",
  "Order ID": "Comanda ID",
  Applied: "Aplicat",
  Fees: "Taxe",
  "Enter promo code": "Introduceți codul promoțional",
  Apply: "aplica",
  "Promo Code": "Cod promoțional",
  Cash: "Bani gheata",
  "You can find your e-tickets attached to your email or download them":
    "Puteți găsi biletele electronice atașate la e-mailul dvs. sau le puteți descărca",
  here: "Aici",
  Time: "Timp",
  "Invalid promo code": "Cod promoțional nevalid",
  "Credit card": "Card de credit",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "În curând veți primi un mesaj de confirmare a înregistrării cu succes la adresa dvs. de e -mail.",
  "You can also check your order details below.":
    "De asemenea, puteți verifica detaliile comenzii mai jos.",
  at: "la",
  Buy: "Cumpără",
  Donation: "Donare",
  "Enter price": "Introduceți prețul",
  Choose: "Alege",
  Chosen: "Ales",
  "Choose your plan": "Alegeți -vă planul",
  week: "săptămână",
  wk: "WK",
  "Choose plan cycle": "Alegeți ciclul planului",
  months: "luni",
  years: "ani",
  weeks: "săptămâni",
  "Copy Event Url": "Copiați URL -ul evenimentului",
  "You can find your e-tickets attached to your email or print them":
    "Puteți găsi biletele electronice atașate la e-mailul dvs. sau le puteți imprima",
  "Guest Info": "Informații pentru oaspeți",
  "Ticket Info": "Informații despre bilet",
  "Ticket name": "Numele biletului",
  "Ticket price": "Prețul biletului",
  "Ticket ID": "ID -ul biletului",
  "If you have any questions contact to organizer":
    "Dacă aveți întrebări, contactați organizatorul",
  "As soon as event ends": "De îndată ce se va încheia evenimentul",
  "1 day after event ends": "1 zi după încheierea evenimentului",
  "7 days after event ends": "La 7 zile după încheierea evenimentului",
  "14 days after event ends": "La 14 zile după încheierea evenimentului",
  "30 days after event ends": "30 de zile după încheierea evenimentului",
  Menu: "Meniul",
  "No event for selected date": "Niciun eveniment pentru data selectată",
  view: "vedere",
  List: "Listă",
  Year: "An",
  Yearly: "Anual",
  "Year view header": "Antet de vizualizare a anului",
  "Yearly Style": "Stil anual",
  "There are no events": "Nu există evenimente",
  Autotranslation: "Autotranslație",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Odată activat, widgetul dvs. Calendar va fi tradus pe baza limbii site -ului. *Rețineți că atâta timp cât titlul calendarului și descrierile sunt texte introduse, acestea nu pot fi traduse.",
  "Note on mobile": "Notă pe mobil",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Opriți sau schimbați textul barei „Fără evenimente” pe versiunea mobilă a Calendarului",
  Autodeletion: "Autodeletion",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Activarea opțiunii, vă va elimina automat evenimentele trecute din calendar.",
  "This does not apply to repeating events!":
    "Acest lucru nu se aplică la evenimentele repetate!",
  "Notify event creators about the guest":
    "Notificați creatorii de evenimente despre invitat",
  "Send event creators notification emails as soon as guests register for their events":
    "Trimiteți e -mailuri de notificare a creatorilor de evenimente de îndată ce oaspeții se înregistrează la evenimentele lor",
  "List View Type": "Tipul de vizualizare lista",
  "Description font": "Descriere font",
  Connect: "Conectați",
  "You have no events": "Nu ai evenimente",
  Synchronize: "Sincroniza",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Google Calendar Sync vă permite să vă integrați evenimentele și sesiunile cu calendarul dvs. de boom.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Outlook Calendar Sync vă permite să vă integrați evenimentele și sesiunile cu calendarul dvs. de boom.",
  "Your message has been sent successfully!":
    "Mesajul dumneavoastra a fost trimis cu succes!",
  "There are no synchronized calendars": "Nu există calendare sincronizate",
  "to view more than 7 events": "Pentru a vizualiza mai mult de 7 evenimente",
  "Mobile app": "Aplicatie mobila",
  "Admin Account": "Cont de administrator",
  Password: "Parola",
  "Second User": "Al doilea utilizator",
  Edit: "Editați | ×",
  "Guest limit": "Limita oaspeților",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Toate setările locale sunt (automat) bazate pe limba dvs. Dacă limba dvs. este pe listă, nu este nevoie să personalizați această secțiune.",
  available: "disponibil",
  next: "Următorul",
  Tickets: "Bilete",
  Quantity: "Cantitate",
  "Promo code": "Cod promoțional",
  "Select a payment method": "Selectati o metoda de plata",
  Fee: "Taxă",
  Book: "Carte",
  "All the tickets have been sold out": "Toate biletele au fost epuizate",
  "Choose at least one ticket": "Alegeți cel puțin un bilet",
  "First choose ticket": "Mai întâi alegeți biletul",
  "Please fill out your personal information.":
    "Vă rugăm să completați informațiile dvs. personale.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "Pentru a face o achiziție de succes, vă rugăm să selectați metoda de plată preferată și să introduceți codul promoțional pentru bilete cu reducere.",
  "Credit/Debit card": "Card de Credit / Card de Debit",
  "print here.": "Tipăriți aici.",
  "QR code for all tickets": "Cod QR pentru toate biletele",
  Duration: "Durată",
  "Full Name": "Numele complet",
  "Ticket id": "ID -ul biletului",
  "Group id": "ID de grup",
  "Choose your ticket.": "Alegeți -vă biletul.",
  "Fill out your personal information.": "Completați informațiile personale.",
  "Add the payment details.": "Adăugați detaliile de plată.",
  "To be determined": "A fi determinat",
  "You can find your e-tickets attached to the email or":
    "Puteți găsi biletele electronice atașate la e-mail sau",
  "print here": "Tipăriți aici",
  "Full name": "Numele complet",
  "Group ID": "ID de grup",
  "to Book": "A rezerva",
  "Unfortunately, your card has been declined":
    "Din păcate, cardul dvs. a fost refuzat",
  "Thank you for your purchase!": "Multumesc pentru cumparaturile facute!",
  "Find your printable e-tickets attached to the confirmation email":
    "Găsiți biletele electronice imprimabile atașate la e-mailul de confirmare",
  Confirm: "A confirma",

  "Add event": "Adăugați eveniment",
  Events: "Evenimente",
  "Event details": "Detaliile evenimentului",
  Registration: "Înregistrare",
  "Guests list": "Lista oaspeților",
  Ticket: "Bilet",
  "General Info": "Informatii generale",
  "Customize the general settings of your event":
    "Personalizați setările generale ale evenimentului dvs.",
  "Event Title": "Titlul evenimentului",
  "e.g. Birthday Party": "de exemplu. Petrecere de aniversare",
  "All Day Event": "Eveniment pe intreaga zi",
  Cross: "Cruce",
  Timeline: "Cronologie",
  "Repeating event": "Eveniment repetat",
  Location: "Locație",
  "Venue name": "Numele locului de întâlnire",
  Description: "Descriere",
  Image: "Imagine",
  Color: "Culoare",
  Category: "Categorie",
  "Add your events to color categories and let your users classify them easily":
    "Adăugați evenimentele dvs. la categoriile de culori și lăsați -le utilizatorii să le clasifice cu ușurință",
  "Category name": "Numele categoriei",
  "e.g. Birthdays": "de exemplu. Zile de nastere",
  Venue: "Loc",
  "Where the event takes place": "Unde are loc evenimentul",
  "Venue name": "Numele locului de întâlnire",
  "Venue phone": "Telefon",
  "Venue email": "E -mail",
  "Venue website": "Site -ul locului",
  Organizer: "Organizator",
  "Person who makes the event": "Persoană care face evenimentul",
  "Organizer name": "Numele organizatorului",
  "Organizer phone": "Telefon organizator",
  "Organizer email": "E -mail de organizator",
  "Organizer website": "Site -ul organizatorului",
  Save: "Salvați",
  Cancel: "Anulare",
  Import: "Import",
  Past: "Trecut",
  All: "Toate",
  Upcoming: "Viitoare",
  Uncategorised: "Necategorizat",
  "Date Ascending": "Data ascendentă",
  "Date Descending": "Data coborârii",
  "Title by A-Z": "Titlu de A-Z",
  "Title by Z-A": "Titlu de Z-A",
  "There are no events for this period":
    "Nu există evenimente pentru această perioadă",

  "Auto-Convert Date & Time": "Data și ora de convertire automată",
  TimeZone: "Fus orar",
  Autodeletion: "Autodeletion",
  "Layout Settings": "setări de schemă",
  "Yeatly view": "Vedeți da",
  "Monthly view header": "Antetul de vizualizare lunar",
  "Weekly/Daily view header": "Antet săptămânal/vizualizare zilnică",
  Acendings: "Acțiuni",
  Descending: "Descendentă",
  Standart: "Standart",
  Silver: "Argint",
  Retro: "Retro",
  Dark: "Întuneric",
  Night: "Noapte",
  Aubergine: "Vânătă",
  "List view header": "Lista de vizualizare antet",
  "Side by Side View": "Vedere laterală",
  "Customize Proportions": "Personalizați proporțiile",
  "Card Margins": "Marjele de carte",
  "Image opacity (%)": "Opacitate imagine (%)",
  "Side by Side Header": "Antetul cot la cot",
  "Text Align": "Aliniere text",
  "Timeline View": "Vizualizare cronologie",
  "Title font color": "Culoarea fontului de titlu",
  "Desciption font color": "Culoarea fontului descifrată",
  "Line color": "Culoarea liniei",
  "Date Font color": "Culoarea fontului de date",
  "Daily events background": "Evenimente zilnice fundal",
  Alignment: "Aliniere",
  Vertical: "Vertical",
  Horizontal: "Orizontală",
  "Vertical Alignment": "Aliniere verticală",
  Right: "Dreapta",
  Center: "Centru",
  "Horizontal Alignment": "Aliniere orizontala",
  Top: "Top",
  Center: "Centru",
  Bottom: "Fund",
  "Dates Circle Design": "Datele Cerc Design",
  "Next To The Circle": "Lângă cerc",
  "In The Circle": "În cerc",
  "Timeline Header": "Antetul cronologiei",
  Timeline: "Cronologie",
  "Show only upcoming": "Arată doar viitor",
  "Order by": "Comanda de",
  "Timeline Event Limit": "Limita evenimentului de cronologie",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Permiteți vizitatorului să adauge eveniment la Calnedars local: Google, Yahoo, Outlook, Icalendar.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Permiteți vizitatorului să vă împărtășească evenimentul pe Facebook, LinkedIn, Twitter și etc.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Adăugați o opțiune de căutare în calendarul dvs. pentru a permite oamenilor să caute evenimentele dvs. după titlu, loc, etc.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Permiteți -vă utilizatorilor să vă imprime calendarul de evenimente Boom în orice interval de date.",
  "Click to apply a theme to Calendar":
    "Faceți clic pentru a aplica o temă în Calendar",
  "Date container color": "Culoarea containerului de date",
  "Daily events background": "Evenimente zilnice fundal",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Utilizați suplimentele pentru a instala funcții avansate pe calendarele dvs., ceea ce le face mai funcționale!",
  "Open Add-ons Store": "Magazin de suplimente deschise",
  Monday: "luni",
  Tuesday: "marţi",
  Wednesday: "miercuri",
  Thursday: "joi",
  Friday: "vineri",
  Saturday: "sâmbătă",
  Sunday: "duminică",
  "Yearly view": "Visualização anual",
  Ascending: "vineri",
  "Show event time next to title": "Afișați ora evenimentului lângă titlu",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Reglați data și ora evenimentului la ora locală a utilizatorului în funcție de fusul orar.",
  "Display the time zone alongside the event date.":
    "Afișați fusul orar alături de data evenimentului.",
  "Show event time next to title": "Afișați ora evenimentului lângă titlu",
  "Time Zone": "Fus orar",
  "Upload Image": "Incarca imaginea",
  "Choose a Category": "Alege o categorie",
  "Color you have chosen will not be shown as you choose category":
    "Culoarea pe care ați ales -o nu va fi afișată pe măsură ce alegeți categoria",
  Website: "Site -ul web",
  Next: "Următorul",
  Save: "Salvați",
  "Last Name": "Nume",
  "Personal Info": "Informatie personala",
  Back: "Înapoi",
  "This field is required": "Acest câmp este obligatoriu",
  "Your event has been submitted": "Evenimentul dvs. a fost trimis",
  "Enter a location": "Introduceți o locație",
  "Display the time zone alongside the event date.":
    "Afișați fusul orar alături de data evenimentului.",
  Home: "Acasă",
  "Side By Side Event Limit": "Limita evenimentului cot la cot",
  "Mobille App": "Aplicația Mobille",
  category: "categorie",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Urmăriți cu ușurință programul dvs. importând evenimentele Facebook în calendar.",
  "Synchronized Pages": "Pagini sincronizate",
  "There are no synchronized pages": "Nu există pagini sincronizate",
  "Choose page": "Alege pagina",
  "You have no events": "Nu ai evenimente",
};
export default ro;
