let sk = {
  Categories: "Kategórie",
  "Share this event": "Zdieľajte túto udalosť",
  Language: "Jazyk",
  "Show Time Zone": "Ukazovať časové pásmo",
  "Custom Local Settings": "Vlastné miestne nastavenia",
  "Add and showcase events on your site using a beautiful calendar.":
    "Pridajte a predvádzajte udalosti na svojom webe pomocou krásneho kalendára.",
  "Week Days": "Dni v týždni",
  "Manage Events": "Riadiť udalosti",
  General: "Všeobecný",
  "Layout Picker": "Zberateľ rozloženia",
  Month: "Mesiac",
  Monthly: "Mesačný",
  Week: "Týždeň",
  Weekly: "Týždenný",
  Day: "Deň",
  Daily: "Denne",
  Agenda: "Program",
  "Navigation Buttons": "Navigačné tlačidlá",
  "Week numbers": "Týždenné čísla",
  "Include Weekends": "Zahrňte víkendy",
  "All-day": "Celý deň",
  "All Day": "Celý deň",
  Label: "Štítok",
  "Fit to Height": "Prispôsobiť výške",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Ak chcete nastaviť proporcie aplikácií, manully deaktivujú túto možnosť a zmenili kalendár v editore.",
  "Default Layout": "Predvolené rozloženie",
  "Monthly view": "Mesačný pohľad",
  "Weekly and Daily view": "Týždenný a denný pohľad",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Návštevníkom môžete dať konzistentnejší zážitok tým, že zobrazíte rovnaký počet týždňov (6).",
  "Fixed Weekly Layout": "Opravené týždenné rozloženie",
  back: "späť",
  Row: "Riadok",
  "Hours in Weekly View": "Hodiny v týždennom zobrazení",
  "Hours in Daily View": "Hodiny v dennom pohľade",
  Start: "Štart",
  End: "Koniec",
  "At This Hour": "V túto hodinu",
  Button: "Tlačidlo",
  Buttons: "Gombíky",
  Sunday: "Nedeľa",
  Monday: "Pondelok",
  Tuesday: "Utorok",
  Wednesday: "Streda",
  Thursday: "Štvrtok",
  Friday: "Piatok",
  Saturday: "Sobota",
  "Default Date": "Predvolený dátum",
  year: "rok",
  month: "mesiac",
  mo: "mí",
  days: "dni",
  ago: "pred",
  ahead: "dopredu",
  Yesterday: "Včera",
  Today: "Dnes",
  Tomorrow: "Zajtra",
  Custom: "Zvyk",
  "Set Daily Rows Limit": "Nastaviť denný limit riadkov",
  "Set Proportions": "Nastaviť rozmery",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Povoliť návštevníkovi pridať udalosť do miestnych Calnedars: Google, Yahoo, Outlook, ICALENDAR.",
  Container: "Nádoba",
  Background: "Pozadie",
  "Container Background": "Pozadie kontajnera",
  "Container Borders": "Kontajnerové hranice",
  Calendar: "Kalendár",
  "Event Info Tooltip": "Informácie o udalosti päsť",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Keď sa ľudia vznášajú nad udalosťou, uvidia všetky informácie o tom v popise.",
  "Event Info Window": "Okno s informáciami o udalosti",
  "This is the full information window that opens when someone clicks on the event.":
    "Toto je okno Úplné informácie, ktoré sa otvára, keď niekto klikne na udalosť.",
  "Use Gradient": "Používať gradient",
  Vertical: "Vertikálny",
  Horizontal: "Horizontálny",
  First: "najprv",
  Second: "Druhý",
  diagonal: "diagonálny",
  Radial: "Radiálny",
  "Select option": "Vyberte možnosť",
  Solid: "Tuhý",
  Dotted: "Bodkovaný",
  Dashed: "Prerušovaný",
  Double: "Zdvojnásobiť",
  "Border Radius": "Okrajový polomer",
  Padding: "Vypchávka",
  "Date Header": "Hlavička",
  "Event Default Color": "Predvolená farba udalosti",
  "Days of Week": "Dni v týždni",
  "Days of Week Background": "Dni v týždni pozadie",
  Date: "Dátum",
  "Event Title": "Názov udalosti",
  "Highlight today": "Zvýrazniť dnes",
  "Highlight Color": "Zvýrazniť farbu",
  Hide: "Skryť",
  "Calendar Border Color": "Farebná hranica kalendára",
  "Calendar Border Width": "Šírka kalendára",
  "Calendar Border Style": "Ohraničný štýl kalendára",
  "Font Color": "Farba písma",
  "Event Background": "Pozadie",
  "Card Date Color": "Dátumová farba",
  "Title Font": "Písmo",
  "Date Font": "Písmo",
  "Description Font": "Popis",
  "Button Background": "Pozadie",
  "Button Text": "Text",
  "Border Color": "Farebná hranica",
  "Border Width": "Šírka hranice",
  "Border Type": "Hraničný typ",
  Title: "Názov",
  Description: "Opis",
  "Background Color": "Farba pozadia",
  Divider: "Deliteľ",
  "Event Details Font": "Podrobnosti o udalosti písmo",
  "Website Link Color": "Farba odkazu na webovú stránku",
  "Developer Info": "Informácie o vývojárovi",
  "User Guide": "Užívateľská príručka",
  "Support e-mail": "Podpora e-mailu",
  "Our Website": "Naša webová stránka",
  "App Review": "Recenzia aplikácie",
  "Enjoying App? Leave us a review in the App Market.":
    "Páčilo sa vám aplikácia? Zanechajte nám recenziu na trhu s aplikáciami.",
  "Review Us": "Skontrolovať nás",
  "Connect With Us": "Spoj sa s nami",
  "What's your email?": "aký máš email?",
  "Invalid email address!": "Neplatná emailová adresa!",
  Comments: "Pripomienky",
  "We'd love to hear from you. Send us a message.":
    "Radi by sme od vás počuli. Pošlite nám správu.",
  "Message must be at least 5 characters long":
    "Správa musí byť najmenej 5 znakov dlhá",
  Send: "Odoslať",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Ak chcete umožniť používateľovi prepínať medzi zobrazeniami kalendára, povoliť túto možnosť a vyberte zobrazenia, ktoré chcete zobraziť.",
  Main: "Hlavná",
  Localize: "Lokalizovať",
  Settings: "nastavenie",
  Layouts: "Rozloženie",
  Advanced: "Pokročilé",
  Design: "Návrh",
  Support: "podpora",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Všetky miestne nastavenia sú (automaticky) založené na vašom jazyku. Ak je váš jazyk na zozname, nie je potrebné prispôsobiť túto časť.",
  "Date Format": "Formát dátumu",
  "Time Format": "Formát času",
  "Text Direction": "Smer",
  "Left to Right": "Zľava doprava",
  "Right to Left": "Zprava doľava",
  "Week Starts On": "Týždeň sa začína ďalej",
  "Agenda Style": "Štýl programu",
  Classic: "Klasický",
  Modern: "Moderný",
  "Agenda Header": "Hlavička programu",
  "Upcoming Events": "Pripravované akcie",
  "Agenda Event Limit": "Limit udalosti programu",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Inovujte teraz a získajte oveľa viac funkcií a užite si svoju aplikáciu v plnej výške!",
  "Upgrade Now": "Vylepšiť teraz",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Hosting udalostí, ktoré trvajú celý deň? To vám umožní ukázať im vo vašom kalendári.",
  "24 hours": "24 hodín",
  Sat: "Sedieť",
  Sun: "slnko",
  Mon: "Monštrum",
  Default: "Predvolený",
  "Select custom design style for your calendar.":
    "Vyberte vlastný štýl dizajnu pre svoj kalendár.",
  Style: "Štýl",
  "Styles and Colors": "Štýly a farby",
  "Calendar Name": "Názov kalendára",
  "Write your Calendar name here": "Sem napíšte svoj názov kalendára",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "To nie je viditeľné pre vašich používateľov. Pri použití funkcie synchronizačného kalendára výživného kalendára nastavte názvy.",
  "General Info": "Všeobecné informácie",
  Venue: "Miesto konania",
  Organizer: "Organizátor",
  Search: "Vyhľadávanie",
  "Add to": "Pridať k",
  calendar: "kalendár",
  "Copy event URL": "Kopírovať adresu URL udalosti",
  "Copied!": "Skopírované!",
  "Add & Share": "Pridať a zdieľať",
  Map: "Mapovať",
  "Calendar view": "Výhľad na kalendár",
  "Add Event": "Pridať udalosť",
  Uncategorised: "Nekategrovaný",
  More: "Viac",
  Less: "Menej",
  Register: "Registrovať",
  Card: "Karta",
  Guests: "Hosť",
  unlimited: "neobmedzený",
  "Show more": "Zobraziť viac",
  "Enable Search": "Povoliť vyhľadávanie",
  "+ Add Event": " + Pridať udalosť",
  "Manage and Sync": "Spravovať a synchronizovať",
  "Show event details as...": "Zobraziť podrobnosti udalosti ako ...",
  Tooltip: "Popisový",
  Popup: "Objaviť sa",
  None: "Žiadny",
  "Show Category": "Kategória",
  "Header Align": "Vyrovnanie hlavičky",
  "Show Time": "Zobraziť čas",
  "Hours in Weekly/Daily View": "Hodiny v týždennom/dennom výhľade",
  "Share Events": "Podujatia",
  Shadow: "Zatieniť",
  "Inner Padding": "Vnútorné čalúnenie",
  Text: "Text",
  "Active Button Border": "Aktívny gombík",
  "Light Mode": "Režim",
  "Event Text Color": "Farba textu udalosti",
  Dates: "Termíny",
  Skeleton: "Skeleón",
  "Skeleton Color": "Kostra",
  Width: "Šírka",
  "Skeleton Style": "Kostra",
  Color: "Farebný",
  "Section Titles": "Tituly sekcie",
  "Section Content": "Obsah",
  Header: "Hlavička",
  Standard: "Norma",
  Retro: "Retro",
  Silver: "Striebro",
  Night: "Noc",
  Dark: "Tmavý",
  Aubergine: "Baklažán",
  "Map Header": "Hlavička mapy",
  "Show Title in mobile": "Zobraziť názov v mobile",
  "Card View": "Pohľad",
  "Card background color": "Farba na pozadí",
  "Title font": "Písmo",
  "Desciption font": "Písmo",
  "Section font": "Písmo",
  "Section divider color": "Farba deliča sekcie",
  "Add event": "Pridať udalosť",
  "All Day Event": "Celodenná udalosť",
  Location: "Miesto",
  "Choose a category": "Vyberte kategóriu",
  "Venue name": "Názov miesta konania",
  "Venue phone": "Telefónne miesto",
  "Venue email": "E -mail",
  "Venue website": "Webové stránky",
  "Organizer name": "Názov organizátora",
  "Organizer phone": "Organizátor",
  "Organizer email": "Organizátor e -mail",
  "Organizer website": "Webová stránka organizátora",
  "Personal info": "Osobné informácie",
  "First name": "Krstné meno",
  "Last name": "Priezvisko",
  "Email Address": "Emailová adresa",
  "Additional Notes": "Doplňujúce Poznámky",
  Back: "späť",
  Save: "Uložiť",
  Next: "Ďalšie",
  "Your event has been submitted": "Vaša udalosť bola odoslaná",
  "Event submittion has been failed": "Predkladanie udalostí sa zlyhalo",
  "e.g. Birthday Party": "napr. Narodeninová oslava",
  "First Name": "Krstné meno",
  "Last Name": "Priezvisko",
  "Phone Number": "Telefónne číslo",
  Address: "Osloviť",
  "Your comments": "Tvoje komentáre",
  "How many guests?": "Koľko hostí?",
  "Anything else we need to know?": "Potrebujeme ešte niečo?",
  "Guests:": "Hostia:",
  Submit: "Predložiť",
  "Go to Calendar": "Choďte do kalendára",
  "Registration completed successfully!": "Registrácia úspešne dokončená!",
  "Please check your registered email address":
    "Skontrolujte svoju registrovanú e -mailovú adresu",
  "Add to Calendar": "Pridať do kalendára",
  "Share this Event": "Zdieľajte túto udalosť",
  "Sorry something went wrong": "Prepáčte, niečo sa pokazilo",
  "Back to registration": "Späť na registráciu",
  "Date & Location": "Dátum a umiestnenie",
  "Date & Time": "Dátum Čas",
  home: "Domov",
  "Header align": "Vyrovnanie hlavičky",
  Footer: "Päta",
  "Categories Filter": "Filtrovať kategórie",
  "Show only upcoming": "Ukázať iba nadchádzajúce",
  "Card(s) in a row": "Karty v rade",
  "Space between cards": "Priestor medzi kartami",
  "Shown events limit": "Zobrazený limit udalostí",
  "Style 1": "Štýl 1",
  "Style 2": "Štýl 2",
  "Style 3": "Štýl 3",
  "Style 4": "Štýl 4",
  "Buttons & Links": "Tlačidlá a odkazy",
  "Button corner radius": "Polomer rohu gombíka",
  "Buttons font": "Tlačidlá písmo",
  "Buttons background": "Tlačidlá pozadie",
  "Get notified by Email": "Dostaňte upozornenia e -mailom",
  "Review events": "Preskúmanie",
  "Click on date": "Kliknite na dátum",
  "Add Event button": "Pridať tlačidlo udalosti",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Synchronizácia kalendára vám umožňuje integrovať vaše udalosti a relácie s kalendárom rozmachu.",
  connect: "pripojiť",
  "Synchronized Calendars": "Synchronizované kalendáre",
  "Import events": "Import",
  Disconnect: "Odpojiť",
  "Choose calendar": "Vyberte kalendár",
  "Monitor your Wix events through the sync feature":
    "Sledujte svoje udalosti WIX prostredníctvom funkcie Sync",
  "Connect all your Boom calendars available on your website":
    "Pripojte všetky vaše kalendáre pre rozmach dostupné na vašom webe",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Naplánujte si, pripojte sa a spravujte stretnutia priblíženia priamo prostredníctvom nášho kalendára rozmachu.",
  "Monitor your Event Brite events through the Event Brite sync feature..":
    "Sledujte udalosti svojej udalosti Brite prostredníctvom funkcie Event Brite Sync",
  Email: "E -mail",
  "Add-ons": "Prídavky",
  "Receive notification emails as soon as users add events to your calendar.":
    "Dostávajte e -maily s upozornením hneď, ako používatelia pridajú udalosti do vášho kalendára.",
  "Enable + button on the calendar header":
    "Povoliť + tlačidlo v hlavičke kalendára",
  "Accept or decline events added by customers before making them public.":
    "Prijmite alebo odmietnuť udalosti pridané zákazníkmi skôr, ako ich zverejnia.",
  "Switch Add Event": "Prepnúť udalosť pridať",
  "Enable your browser cookies to connect to your account.":
    "Povoľte, aby sa súbory cookie prehliadača pripojili k vášmu účtu.",
  "Learn more": "Uč sa viac",
  "Print Button": "Tlačidlo",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Umožnite svojim používateľom vytlačiť kalendár udalosti rozmachu v akomkoľvek rozsahu dátumu.",
  "Show Title on mobile": "Zobraziť názov na mobile",
  "Show Skeleton on mobile": "Zobraziť kostru na mobile",
  "Start 7-day Business trial": "Začnite 7-dňový obchodný súdny proces",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Vychutnajte si všetky neobmedzené funkcie, ako sú predajné lístky, registrácia, doplnky udalostí pre návštevníkov.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Poznámka: Na konci skúšobného obdobia sa vrátite do svojho existujúceho plánu predplatného.",
  "Not Now": "Teraz nie",
  "Start free trial": "Začnite bezplatnú skúšobnú verziu",
  "Congrats!": "Gratulujem!",
  "Your 7-day Business trial has been successfully activated.":
    "Vaša 7-dňová obchodná skúška bola úspešne aktivovaná.",
  Done: "hotový",
  "Title font color": "Farba písma",
  "Desciption font color": "Farba písma",
  "Section font color": "Farba písma",
  "Card Header": "Hlavička",
  Category: "Kategória",
  "Display at the": "Zobrazovať",
  top: "vrchol",
  bottom: "dolná časť",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Ukážte filter kategórie v hornej časti alebo v spodnej časti kalendára. Nastavenia sa vzťahujú iba na zobrazenia programu a karty",
  "Processing your events": "Spracovanie vašich udalostí",
  "Search for events": "Vyhľadajte udalosti",
  "There are no events added": "Nie sú pridané žiadne udalosti",
  "Location: To be determined": "Umiestnenie: Určenie",
  "No events for selected date": "Žiadne udalosti pre vybraný dátum",
  Uncategorized: "Negatívny",
  "Edit event": "Úpravy",
  "Edit original event": "Upraviť pôvodnú udalosť",
  "Copy event": "Kopírovanie",
  "Copy as new event": "Skopírovať ako nová udalosť",
  "Delete event": "Vymazať udalosť",
  "Stop repeating on this date": "Prestaňte sa opakovať v tento dátum",
  "Exclude this date": "Vylúčiť tento dátum",
  "Location is going to be announced": "Poloha bude oznámená",
  "Fill your personal information": "Vyplňte svoje osobné informácie",
  "Check Box": "Políčka",
  "Single Choice": "Jednotlivá voľba",
  Option: "Voľba",
  "Share Event": "Podujatie",
  "Oops! Something went wrong": "Hops! Niečo sa pokazilo",
  "We are sorry this event has already taken place":
    "Je nám ľúto tejto udalosti sa už uskutočnilo",
  "Back to calendar": "Späť do kalendára",
  "This field is required": "Toto pole je potrebné",
  Phone: "Telefonovať",
  "Number field": "Číslo číselného poľa",
  "Please provide a valid email": "Uveďte platný e -mail",
  "Select at least one option": "Vyberte aspoň jednu možnosť",
  "Choose tickets to see total value":
    "Vyberte lístky, aby ste videli celkovú hodnotu",
  tickets: "vstupenky",
  "Choose Tickets": "Vyberte lístky",
  "Choose payment method": "Vyberte si metódu platby",
  Pay: "Platiť",
  Total: "Celkom",
  Free: "zadarmo",
  "Buy tickets": "Kúpiť lístky",
  "Sold Out": "Vypredané",
  "Tickets are available": "Vstupenky sú k dispozícii",
  "Sales End": "Koniec predaja",
  "Availible from": "Dostupný",
  "Go to Orders": "Choďte na objednávky",
  "Go to Details": "Prejdite na podrobnosti",
  "Group ticket": "Vstupenka",
  Name: "názov",
  Price: "cena",
  "Order by": "Zoradiť podľa",
  "Order ID": "Číslo objednávky",
  Applied: "Aplikovaný",
  Fees: "Poplatky",
  "Enter promo code": "Zadajte promo kód",
  Apply: "Uplatňovať",
  "Promo Code": "Promo kód",
  Cash: "Hotovosť",
  "You can find your e-tickets attached to your email or download them":
    "Svoje e-lístky nájdete priložené k svojmu e-mailu alebo ich stiahnite",
  here: "tu",
  Time: "Čas",
  "Invalid promo code": "Neplatný propagačný kód",
  "Credit card": "Kreditná karta",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Čoskoro dostanete potvrdenú správu o úspešnej registrácii na vašu e -mailovú adresu.",
  "You can also check your order details below.":
    "Nižšie nájdete podrobnosti o svojej objednávke.",
  at: "pri",
  Buy: "Nákup",
  Donation: "Darovanie",
  "Enter price": "Zadajte cenu",
  Choose: "Zvoliť si",
  Chosen: "Zvolený",
  "Choose your plan": "Vyberte si svoj plán",
  week: "týždeň",
  wk: "bahno",
  "Choose plan cycle": "Vyberte cyklus plánu",
  months: "mesiace",
  years: "roky",
  weeks: "týždne",
  "Copy Event Url": "Skopírovať adresu URL udalosti",
  "You can find your e-tickets attached to your email or print them":
    "Svoje e-e-maily nájdete k svojmu e-mailu alebo ich vytlačiť",
  "Guest Info": "Hosť",
  "Ticket Info": "Informácie o lístku",
  "Ticket name": "Názov lístka",
  "Ticket price": "Cena lístku",
  "Ticket ID": "ID lístka",
  "If you have any questions contact to organizer":
    "Ak máte akékoľvek otázky, kontaktujte organizátor",
  "As soon as event ends": "Hneď ako sa udalosť skončí",
  "1 day after event ends": "1 deň po skončení udalosti",
  "7 days after event ends": "7 dní po skončení udalosti",
  "14 days after event ends": "14 dní po skončení udalosti",
  "30 days after event ends": "30 dní po skončení udalosti",
  Menu: "Ponuka",
  "No event for selected date": "Žiadna udalosť pre vybraný dátum",
  view: "vyhliadka",
  List: "Zoznam",
  Year: "Rok",
  Yearly: "Ročný",
  "Year view header": "Hlavička",
  "Yearly Style": "Ročný štýl",
  "There are no events": "Neexistujú žiadne udalosti",
  Autotranslation: "Autorácia",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Po povolení bude váš miniaplikácia kalendára preložená na základe jazyka webovej stránky. *Všimnite si, že pokiaľ sú názov kalendára a opisy sú zadané texty, nemôžu sa preložiť.",
  "Note on mobile": "Poznámka na mobile",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Vypnite alebo zmeňte text panela „No Events“ v mobilnej verzii kalendára",
  Autodeletion: "Autodeletácia",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Povolenie tejto možnosti automaticky odstráni vaše minulé udalosti z kalendára.",
  "This does not apply to repeating events!":
    "To sa nevzťahuje na opakujúce sa udalosti!",
  "Notify event creators about the guest": "Oznámte tvorcom udalostí o hosťovi",
  "Send event creators notification emails as soon as guests register for their events":
    "Pošlite e -maily tvorcov udalostí, len čo sa hostia zaregistrujú na svoje udalosti",
  "List View Type": "Zobraziť typ zobrazenia",
  "Description font": "Popis",
  Connect: "Pripojiť",
  "You have no events": "Nemáte žiadne udalosti",
  Synchronize: "Synchronizovať",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Synchronizácia kalendára Google vám umožňuje integrovať vaše udalosti a relácie s kalendárom rozmachu.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Synchronizácia kalendára programu Outlook vám umožňuje integrovať vaše udalosti a relácie s kalendárom rozmachu.",
  "Your message has been sent successfully!":
    "Vaša správa bola úspešne odoslaná!",
  "There are no synchronized calendars":
    "Neexistujú žiadne synchronizované kalendáre",
  "to view more than 7 events": "Zobraziť viac ako 7 udalostí",
  "Mobile app": "Mobilná aplikácia",
  "Admin Account": "Správca",
  Password: "Heslo",
  "Second User": "Druhý užívateľ",
  Edit: "Upraviť",
  "Guest limit": "Limit hosťa",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Všetky miestne nastavenia sú (automaticky) založené na vašom jazyku. Ak je váš jazyk na zozname, nie je potrebné prispôsobiť túto časť.",
  available: "dostupný",
  next: "Ďalšie",
  Tickets: "Vstupenky",
  Quantity: "Množstvo",
  "Promo code": "Promo kód",
  "Select a payment method": "Vyberte spôsob platby",
  Fee: "Poplatok",
  Book: "Rezervovať",
  "All the tickets have been sold out": "Všetky lístky boli vypredané",
  "Choose at least one ticket": "Vyberte aspoň jeden lístok",
  "First choose ticket": "Najskôr si vyberte lístok",
  "Please fill out your personal information.":
    "Vyplňte prosím svoje osobné informácie.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "Ak chcete urobiť úspešný nákup, vyberte svoj preferovaný spôsob platby a zadajte propagačný kód pre zľavnené lístky.",
  "Credit/Debit card": "Kreditná/debetná karta",
  "print here.": "Tlačiť tu.",
  "QR code for all tickets": "QR kód pre všetky lístky",
  Duration: "Trvanie",
  "Full Name": "Celé meno",
  "Ticket id": "ID lístka",
  "Group id": "ID skupiny",
  "Choose your ticket.": "Vyberte si lístok.",
  "Fill out your personal information.": "Vyplňte svoje osobné informácie.",
  "Add the payment details.": "Pridajte podrobnosti platby.",
  "To be determined": "Byť odhodlaný",
  "You can find your e-tickets attached to the email or":
    "Svoje elektronické lístky nájdete priložené k e-mailu alebo",
  "print here": "tu",
  "Full name": "Celé meno",
  "Group ID": "ID skupiny",
  "to Book": "rezervovať",
  "Unfortunately, your card has been declined":
    "Bohužiaľ, vaša karta bola odmietnutá",
  "Thank you for your purchase!": "Ďakujem za Váš nákup!",
  "Find your printable e-tickets attached to the confirmation email":
    "Nájdite svoje e-e-mail s tlačeným e-mailom, ktoré je možné vytlačiť",
  Confirm: "Potvrdiť",

  "Add event": "Pridať udalosť",
  Events: "Diania",
  "Event details": "Podrobnosti o udalosti",
  Registration: "Registrácia",
  "Guests list": "Zoznam hostí",
  Ticket: "Lístok",
  "General Info": "Všeobecné informácie",
  "Customize the general settings of your event":
    "Prispôsobte všeobecné nastavenia vašej udalosti",
  "Event Title": "Názov udalosti",
  "e.g. Birthday Party": "napr. Narodeninová oslava",
  "All Day Event": "Celodenná udalosť",
  Cross: "Kríž",
  Timeline: "Časová os",
  "Repeating event": "Opakujúca sa udalosť",
  Location: "Miesto",
  "Venue name": "Názov miesta konania",
  Description: "Opis",
  Image: "Obraz",
  Color: "Farba",
  Category: "Kategória",
  "Add your events to color categories and let your users classify them easily":
    "Pridajte svoje udalosti do farebných kategórií a nechajte ich ľahko klasifikovať ich",
  "Category name": "Meno kategórie",
  "e.g. Birthdays": "napr. Narodeniny",
  Venue: "Miesto konania",
  "Where the event takes place": "Kde sa udalosť koná",
  "Venue name": "Názov miesta konania",
  "Venue phone": "Telefónne miesto",
  "Venue email": "E -mail",
  "Venue website": "Webové stránky",
  Organizer: "Organizátor",
  "Person who makes the event": "Osoba, ktorá robí udalosť",
  "Organizer name": "Názov organizátora",
  "Organizer phone": "Telefónny telefón",
  "Organizer email": "Organizátor e -mail",
  "Organizer website": "Webová stránka organizátora",
  Save: "Uložiť",
  Cancel: "Zrušiť",
  Import: "Dovoz",
  Past: "Minulosť",
  All: "Všetko",
  Upcoming: "Nadchádzajúci",
  Uncategorised: "Nekategrovaný",
  "Date Ascending": "Dátum stúpajúci",
  "Date Descending": "Zostupný dátum",
  "Title by A-Z": "Titul A-Z",
  "Title by Z-A": "Názov Z-a",
  "There are no events for this period":
    "Na toto obdobie neexistujú žiadne udalosti",

  "Auto-Convert Date & Time": "Dátum a čas automatického konvertu",
  TimeZone: "Časové pásmo",
  Autodeletion: "Autodeletácia",
  "Layout Settings": "Nastavenia rozloženia",
  "Yeatly view": "Výhľad",
  "Monthly view header": "Mesačná hlavička výhľadu",
  "Weekly/Daily view header": "Týždenný/denný výhľad hlavičky",
  Acendings: "Posyšenie",
  Descending: "Zostupný",
  Standart: "Samostatný",
  Silver: "Striebro",
  Retro: "Retro",
  Dark: "Tmavý",
  Night: "Noc",
  Aubergine: "Baklažán",
  "List view header": "Hlavička Zobraziť",
  "Side by Side View": "Bok po boku",
  "Customize Proportions": "Prispôsobiť proporcie",
  "Card Margins": "Okraje",
  "Image opacity (%)": "Nepriehľadnosť (%)",
  "Side by Side Header": "Hlavná hlavička",
  "Text Align": "Zosúladiť text",
  "Timeline View": "Zobrazenie časovej osi",
  "Title font color": "Farba písma",
  "Desciption font color": "Farba písma",
  "Line color": "Farba",
  "Date Font color": "Dátumová farba",
  "Daily events background": "Denné udalosti Pozadie",
  Alignment: "Vyrovnanie",
  Vertical: "Vertikálny",
  Horizontal: "Horizontálny",
  "Vertical Alignment": "Vertikálne zarovnanie",
  Right: "Správny",
  Center: "Stred",
  "Horizontal Alignment": "Horizontálne zarovnanie",
  Top: "Vrchol",
  Center: "Stred",
  Bottom: "Dolná časť",
  "Dates Circle Design": "Dizajn kruhu",
  "Next To The Circle": "Vedľa kruhu",
  "In The Circle": "V kruhu",
  "Timeline Header": "Hlavička časovej osi",
  Timeline: "Časová os",
  "Show only upcoming": "Ukázať iba nadchádzajúce",
  "Order by": "Zoradiť podľa",
  "Timeline Event Limit": "Limit udalosti časovej osi",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Povoliť návštevníkovi pridať udalosť do miestnych Calnedars: Google, Yahoo, Outlook, ICALENDAR.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Umožnite návštevníkovi zdieľať svoju udalosť na Facebooku, LinkedIn, Twitter a atď.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Pridajte do svojho kalendára možnosť vyhľadávania, aby ste ľuďom umožnili vyhľadávať vaše udalosti podľa názvu, miesta konania atď.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Umožnite svojim používateľom vytlačiť kalendár udalosti rozmachu v akomkoľvek rozsahu dátumu.",
  "Click to apply a theme to Calendar": "Kliknutím použite tému do kalendára",
  "Date container color": "Farba kontajnera",
  "Daily events background": "Denné udalosti Pozadie",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Použite doplnky na inštaláciu pokročilých funkcií do svojich kalendárov, vďaka čomu sú funkčné!",
  "Open Add-ons Store": "Otvorte obchod s doplnkami",
  Monday: "Pondelok",
  Tuesday: "Utorok",
  Wednesday: "Streda",
  Thursday: "Štvrtok",
  Friday: "Piatok",
  Saturday: "Sobota",
  Sunday: "Nedeľa",
  "Yearly view": "Utorok",
  Ascending: "Vzostupný",
  "Show event time next to title": "Zobraziť čas udalosti najbližšie k titulu",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Upravte dátum a čas udalosti miestnemu času používateľa na základe časového pásma.",
  "Display the time zone alongside the event date.":
    "Zobraziť časové pásmo spolu s dátumom udalosti.",
  "Show event time next to title": "Zobraziť čas udalosti najbližšie k titulu",
  "Time Zone": "Časové pásmo",
  "Upload Image": "Nahrať obrázok",
  "Choose a Category": "Vyberte kategóriu",
  "Color you have chosen will not be shown as you choose category":
    "Farba, ktorú ste si vybrali, sa nezobrazí, keď si vyberiete kategóriu",
  Website: "Webová stránka",
  Next: "Ďalšie",
  Save: "Uložiť",
  "Last Name": "Priezvisko",
  "Personal Info": "Osobné informácie",
  Back: "späť",
  "This field is required": "Toto pole je potrebné",
  "Your event has been submitted": "Vaša udalosť bola odoslaná",
  "Enter a location": "Zadajte miesto",
  "Display the time zone alongside the event date.":
    "Zobraziť časové pásmo spolu s dátumom udalosti.",
  Home: "Domov",
  "Side By Side Event Limit": "Limit udalosti vedľa seba",
  "Mobille App": "Aplikácia Mobille",
  category: "kategória",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Jednoducho sledujte svoj plán importovaním udalostí z Facebooku do kalendára.",
  "Synchronized Pages": "Synchronizované stránky",
  "There are no synchronized pages":
    "Neexistujú žiadne synchronizované stránky",
  "Choose page": "Vyberte stránku",
  "You have no events": "Nemáte žiadne udalosti",
};
export default sk;
