let sq = {
  Categories: "Kategoritë",
  "Share this event": "Ndani këtë ngjarje",
  Language: "Gjuhe",
  "Show Time Zone": "Shfaq zonën e kohës",
  "Custom Local Settings": "Cilësimet lokale të personalizuara",
  "Add and showcase events on your site using a beautiful calendar.":
    "Shtoni dhe shfaqni ngjarje në faqen tuaj duke përdorur një kalendar të bukur.",
  "Week Days": "Ditët e javës",
  "Manage Events": "Menaxho ngjarjet",
  General: "Gjeneral",
  "Layout Picker": "Layout Picker",
  Month: "Muaj",
  Monthly: "Mujore",
  Week: "Javë",
  Weekly: "Javore",
  Day: "Ditë",
  Daily: "Çdo ditë",
  Agenda: "Agjenda",
  "Navigation Buttons": "Butonat e lundrimit",
  "Week numbers": "Numrat e Javës",
  "Include Weekends": "Përfshini fundjavat",
  "All-day": "Gjithe diten",
  "All Day": "Gjithe diten",
  Label: "Etiketë",
  "Fit to Height": "Përshtat në lartësi",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Për të vendosur proporcione të aplikacionit, çaktivizoni këtë opsion dhe ndryshoni madhësinë e kalendarit në redaktor.",
  "Default Layout": "Paraqitja e paracaktuar",
  "Monthly view": "Pamja mujore",
  "Weekly and Daily view": "Pamja javore dhe e përditshme",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Ju mund t'u jepni vizitorëve një përvojë më të qëndrueshme duke treguar të njëjtin numër javësh (6) në një kohë.",
  "Fixed Weekly Layout": "Paraqitja e javës fikse",
  back: "Kthehu",
  Row: "Rresht",
  "Hours in Weekly View": "Orë në pamje javore",
  "Hours in Daily View": "Orë në pamje ditore",
  Start: "Fillo",
  End: "Fund",
  "At This Hour": "Në këtë orë",
  Button: "Buton",
  Buttons: "Butonat",
  Sunday: "E Dielë",
  Monday: "E hënë",
  Tuesday: "E martë",
  Wednesday: "E mërkurë",
  Thursday: "E enjte",
  Friday: "E Premte",
  Saturday: "E shtunë",
  "Default Date": "Data e paracaktuar",
  year: "Viti",
  month: "muaj",
  mo: "Mo",
  days: "Ditë",
  ago: "më parë",
  ahead: "Përpara",
  Yesterday: "Dje",
  Today: "Sot",
  Tomorrow: "Nesër",
  Custom: "Zakon",
  "Set Daily Rows Limit": "Vendosni kufirin e rreshtave ditorë",
  "Set Proportions": "Vendosni përmasa",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Lejoni vizitorin të shtojë ngjarje në Calnedars Lokale: Google, Yahoo, Outlook, Icalendar.",
  Container: "Enë",
  Background: "Sfondi",
  "Container Background": "Sfondi i kontejnerit",
  "Container Borders": "Kufijtë e kontejnerëve",
  Calendar: "Kalendar",
  "Event Info Tooltip": "Informacioni i Informacionit të Ngjarjes",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Kur njerëzit rri pezull për një ngjarje, ata do të shohin të gjitha informacionet në lidhje me të në një mjet mjeti.",
  "Event Info Window": "Dritarja e Informacionit të Ngjarjes",
  "This is the full information window that opens when someone clicks on the event.":
    "Kjo është dritarja e plotë e informacionit që hapet kur dikush klikon në ngjarje.",
  "Use Gradient": "Përdorni gradient",
  Vertical: "Vertikale",
  Horizontal: "Horizontale",
  First: "Së pari",
  Second: "E dyta",
  diagonal: "Diagonal",
  Radial: "Radial",
  "Select option": "Zgjidhni opsionin",
  Solid: "E ngurtë",
  Dotted: "Me pika",
  Dashed: "I thyer",
  Double: "Double",
  "Border Radius": "Rrezja kufitare",
  Padding: "Mbushje",
  "Date Header": "Kreu i datës",
  "Event Default Color": "Ngjyra e paracaktuar e ngjarjes",
  "Days of Week": "Ditët e javës",
  "Days of Week Background": "Ditët e Javës Sfondi",
  Date: "Data",
  "Event Title": "Titulli i ngjarjes",
  "Highlight today": "Ngjyrosni sot",
  "Highlight Color": "Ngjyra e theksuar",
  Hide: "Fshih",
  "Calendar Border Color": "Ngjyra e Kufirit të Kalendarit",
  "Calendar Border Width": "Gjerësia e Kufirit të Kalendarit",
  "Calendar Border Style": "Stili i Kufirit të Kalendarit",
  "Font Color": "Ngjyra e shkronjave",
  "Event Background": "Sfondi i ngjarjes",
  "Card Date Color": "Ngjyra e datës së kartës",
  "Title Font": "Fonti i titullit",
  "Date Font": "Data Font",
  "Description Font": "Përshkrimi Font",
  "Button Background": "Sfond butoni",
  "Button Text": "Teksti i butonit",
  "Border Color": "Ngjyra kufitare",
  "Border Width": "Gjerësia e Kufirit",
  "Border Type": "Lloji i Kufirit",
  Title: "Titulli",
  Description: "Përshkrim",
  "Background Color": "Ngjyrë e sfondit",
  Divider: "Ndarës",
  "Event Details Font": "Detajet e Ngjarjes Font",
  "Website Link Color": "Ngjyra e lidhjes së faqes në internet",
  "Developer Info": "Informacioni i Zhvilluesit",
  "User Guide": "Udhëzues Përdorues",
  "Support e-mail": "Mbështetje e-mail",
  "Our Website": "Uebfaqja jonë",
  "App Review": "Rishikimi i Aplikacionit",
  "Enjoying App? Leave us a review in the App Market.":
    "Të shijosh aplikacionin? Na lini një përmbledhje në tregun e aplikacioneve.",
  "Review Us": "Na rishikoni",
  "Connect With Us": "Lidhu me ne",
  "What's your email?": "Cili eshte emaili juaj?",
  "Invalid email address!": "Adresa e pavlefshme e postës elektronike!",
  Comments: "Komente",
  "We'd love to hear from you. Send us a message.":
    "Ne do të donim të dëgjonim nga ju. Na dërgoni një mesazh.",
  "Message must be at least 5 characters long":
    "Mesazhi duhet të jetë së paku 5 karaktere i gjatë",
  Send: "Dërgo",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Nëse doni të lejoni përdoruesin të kalojë midis pamjeve të kalendarit, aktivizoni këtë mundësi dhe zgjidhni pamjet që dëshironi të tregoni.",
  Main: "Main",
  Localize: "Lokalizoni",
  Settings: "Cilësimet",
  Layouts: "Layouts",
  Advanced: "Avancuar",
  Design: "Dizajn",
  Support: "Mbështetje",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Të gjitha cilësimet lokale bazohen (automatikisht) bazuar në gjuhën tuaj. Nëse gjuha juaj është në listë, nuk ka nevojë ta rregulloni këtë seksion.",
  "Date Format": "Formati i datës",
  "Time Format": "Formati i kohës",
  "Text Direction": "Drejtimi i tekstit",
  "Left to Right": "Majtas në të djathtë",
  "Right to Left": "Djathtas në të majtë",
  "Week Starts On": "Java fillon",
  "Agenda Style": "Stili i axhendës",
  Classic: "Klasik",
  Modern: "Modern",
  "Agenda Header": "Kreu i axhendës",
  "Upcoming Events": "Ngjarje të ardhshme",
  "Agenda Event Limit": "Kufiri i Ngjarjes së Agjendës",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Përditësoni tani dhe merrni shumë më shumë veçori dhe shijoni plotësisht aplikacionin tuaj!",
  "Upgrade Now": "Përditëso Tani",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Ngjarjet e pritjes që zgjasin gjithë ditën? Kjo ju lejon t'i tregoni ato në kalendarin tuaj.",
  "24 hours": "24 ore",
  Sat: "Sat",
  Sun: "Dielli",
  Mon: "E hënë",
  Default: "Default",
  "Select custom design style for your calendar.":
    "Zgjidhni stilin e dizajnit me porosi për kalendarin tuaj.",
  Style: "Stil",
  "Styles and Colors": "Stilet dhe Ngjyrat",
  "Calendar Name": "Emri i Kalendarit",
  "Write your Calendar name here": "Shkruaj emrin tënd të kalendarit këtu",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Kjo nuk është e dukshme për përdoruesit tuaj. Vendosni emra për të dalluar kalendarët tuaj kur përdorni funksionin e sinkronizimit të kalendarit bum.",
  "General Info": "Informacion i përgjithshëm",
  Venue: "Vendi",
  Organizer: "Organizator",
  Search: "Kërko",
  "Add to": "Shto te",
  calendar: "Kalendar",
  "Copy event URL": "Kopjoni URL -në e ngjarjes",
  "Copied!": "Kopjuar!",
  "Add & Share": "Shto & Share",
  Map: "Harta",
  "Calendar view": "Pamja e Kalendarit",
  "Add Event": "Shto ngjarje",
  Uncategorised: "Uncategorizuar",
  More: "Më shumë",
  Less: "Më pak",
  Register: "Regjistrohu",
  Card: "Kartelë",
  Guests: "Vizitorët",
  unlimited: "Pafund",
  "Show more": "Shfaq më shumë",
  "Enable Search": "Aktivizo kërkimin",
  "+ Add Event": "+ Shto ngjarje",
  "Manage and Sync": "Menaxho dhe Sinkroni",
  "Show event details as...": "Shfaq detajet e ngjarjes si ...",
  Tooltip: "Mjeti i veglave",
  Popup: "Shfaqem",
  None: "Asnje",
  "Show Category": "Shfaq kategori",
  "Header Align": "Header Align",
  "Show Time": "Koha e shfaqjes",
  "Hours in Weekly/Daily View": "Orë në pamje javore/ditore",
  "Share Events": "Ndani ngjarjet",
  Shadow: "Hija",
  "Inner Padding": "Mbushja e brendshme",
  Text: "Tekst",
  "Active Button Border": "Kufiri aktiv i butonit",
  "Light Mode": "Mënyra e dritës",
  "Event Text Color": "Ngjyra e tekstit të ngjarjes",
  Dates: "Datat",
  Skeleton: "Skelet",
  "Skeleton Color": "Ngjyra e skeletit",
  Width: "Gjerësia",
  "Skeleton Style": "Stili i Skeletit",
  Color: "Ngjyrë",
  "Section Titles": "Titujt e Seksionit",
  "Section Content": "Përmbajtja e seksionit",
  Header: "Header",
  Standard: "Standard",
  Retro: "Retro",
  Silver: "Argjend",
  Night: "Nata",
  Dark: "E errët",
  Aubergine: "Aubergine",
  "Map Header": "Header Map",
  "Show Title in mobile": "Shfaq titullin në celular",
  "Card View": "Pamje e Kartës",
  "Card background color": "Ngjyra e sfondit të kartës",
  "Title font": "Fonti i titullit",
  "Desciption font": "Font Desciption",
  "Section font": "Seksioni Font",
  "Section divider color": "Ngjyra e ndarjes së seksionit",
  "Add event": "Shto ngjarje",
  "All Day Event": "Ngjarja gjatë gjithë ditës",
  Location: "Vendndodhja",
  "Choose a category": "Zgjidhni një kategori",
  "Venue name": "Emri i vendit",
  "Venue phone": "Telefon i vendit",
  "Venue email": "Email i vendit të ngjarjes",
  "Venue website": "Uebfaqja e Vendit",
  "Organizer name": "Emri i Organizatorit",
  "Organizer phone": "Telefon i Organizatorit",
  "Organizer email": "Email i organizatorit",
  "Organizer website": "Uebfaqja e Organizatorit",
  "Personal info": "Informacione Personale",
  "First name": "Emri",
  "Last name": "Mbiemri",
  "Email Address": "Adresa e emailit",
  "Additional Notes": "Shenime shtese",
  Back: "Kthehu",
  Save: "Ruaje",
  Next: "Tjetra",
  "Your event has been submitted": "Ngjarja juaj është dorëzuar",
  "Event submittion has been failed": "Dorëzimi i ngjarjes është dështuar",
  "e.g. Birthday Party": "p.sh. festa e ditëlindjes",
  "First Name": "Emri",
  "Last Name": "Mbiemri",
  "Phone Number": "Numri i telefonit",
  Address: "Adresë",
  "Your comments": "Komentet tuaja",
  "How many guests?": "Sa të ftuar?",
  "Anything else we need to know?": "Thingdo gjë tjetër që duhet të dimë?",
  "Guests:": "Vizitorët:",
  Submit: "Dorëzo",
  "Go to Calendar": "Shko në Kalendar",
  "Registration completed successfully!": "Regjistrimi përfundoi me sukses!",
  "Please check your registered email address":
    "Ju lutemi kontrolloni adresën tuaj të regjistruar të postës elektronike",
  "Add to Calendar": "Shto në kalendar",
  "Share this Event": "Ndani këtë ngjarje",
  "Sorry something went wrong": "Na vjen keq diçka nuk shkoi keq",
  "Back to registration": "Kthehu tek Regjistrimi",
  "Date & Location": "Data & Vendndodhja",
  "Date & Time": "Data dhe koha",
  home: "në shtëpi",
  "Header align": "Header Align",
  Footer: "Footer",
  "Categories Filter": "Kategoritë Filter",
  "Show only upcoming": "Shfaq VETEM të ardhshëm",
  "Card(s) in a row": "Karta (et) me radhë",
  "Space between cards": "Hapësirë ​​midis kartave",
  "Shown events limit": "Ngjarjet e treguara kufizojnë",
  "Style 1": "Stili 1",
  "Style 2": "Stili 2",
  "Style 3": "Stili 3",
  "Style 4": "Stili 4",
  "Buttons & Links": "Butonat dhe lidhjet",
  "Button corner radius": "Rrezet e qoshes së butonit",
  "Buttons font": "Shkronja e butonave",
  "Buttons background": "Sfond i butonave",
  "Get notified by Email": "Njoftohuni me email",
  "Review events": "Rishikimi i ngjarjeve",
  "Click on date": "Kliko në datën",
  "Add Event button": "Shto butonin e ngjarjes",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Sinkronia e Kalendarit ju lejon të integroni ngjarjet dhe seancat tuaja me kalendarin tuaj të bumit.",
  connect: "Lidhu",
  "Synchronized Calendars": "Kalendarët e sinkronizuar",
  "Import events": "Ngjarje të importit",
  Disconnect: "Shkëputni",
  "Choose calendar": "Zgjidhni Kalendarin",
  "Monitor your Wix events through the sync feature":
    "Monitoroni ngjarjet tuaja Wix përmes veçorisë së sinkronizimit",
  "Connect all your Boom calendars available on your website":
    "Lidhni të gjitha kalendarët tuaj të bumit të disponueshëm në faqen tuaj të internetit",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Programoni, bashkohuni dhe menaxhoni takimet e zmadhimit menjëherë përmes kalendarit tonë të bumit.",
  "Monitor your Event Brite events through the Event Brite sync feature..":
    "Monitoroni ngjarjen tuaj Ngjarjet Brite përmes ngjarjes Brite Sync Feature",
  Email: "Email",
  "Add-ons": "Shtesa",
  "Receive notification emails as soon as users add events to your calendar.":
    "Merrni postë elektronike të njoftimit sa më shpejt që përdoruesit të shtojnë ngjarje në kalendarin tuaj.",
  "Enable + button on the calendar header":
    "Aktivizo butonin + në kokën e kalendarit",
  "Accept or decline events added by customers before making them public.":
    "Pranoni ose refuzoni ngjarjet e shtuara nga klientët para se t'i bëni ato publike.",
  "Switch Add Event": "Switch Shto ngjarje",
  "Enable your browser cookies to connect to your account.":
    "Aktivizoni cookies tuaj të shfletuesit të lidhen me llogarinë tuaj.",
  "Learn more": "Mëso më shumë",
  "Print Button": "Butoni i shtypur",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Lejoni përdoruesit tuaj të shtypin kalendarin tuaj të ngjarjes në bum në çdo gamë data.",
  "Show Title on mobile": "Shfaq titullin në celular",
  "Show Skeleton on mobile": "Shfaq skeletin në celular",
  "Start 7-day Business trial": "Filloni Gjyqin e Biznesit 7-ditor",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Shijoni të gjitha tiparet e pakufizuara, të tilla si shitjet e biletave, regjistrimi, shtesat e ngjarjeve të vizitorëve.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Ju lutemi vini re: Në fund të periudhës së provës, do të ktheheni në planin tuaj ekzistues të pajtimit.",
  "Not Now": "Jo tani",
  "Start free trial": "Fillo Gjyqin Falas",
  "Congrats!": "Urime!",
  "Your 7-day Business trial has been successfully activated.":
    "Gjyqi juaj i biznesit 7-ditor është aktivizuar me sukses.",
  Done: "Bërë",
  "Title font color": "Ngjyra e shkronjave të titullit",
  "Desciption font color": "Ngjyra e shkronjave të zbritjes",
  "Section font color": "Ngjyra e shkronjave të seksionit",
  "Card Header": "Titulli i kartave",
  Category: "Kategoria",
  "Display at the": "Shfaq në",
  top: "Top",
  bottom: "në fund",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Shfaqni filtrin e kategorisë në krye ose në fund të kalendarit. Cilësimet vlen vetëm për axhendën dhe pamjet e kartave",
  "Processing your events": "Përpunimi i ngjarjeve tuaja",
  "Search for events": "Kërkoni për ngjarje",
  "There are no events added": "Nuk ka shtuar ngjarje",
  "Location: To be determined": "Vendndodhja: të përcaktohet",
  "No events for selected date": "Asnjë ngjarje për datën e zgjedhur",
  Uncategorized: "I pa kategorizuar",
  "Edit event": "Redakto Event",
  "Edit original event": "Redakto ngjarjen origjinale",
  "Copy event": "Kopjoni ngjarje",
  "Copy as new event": "Kopjoni si ngjarje të re",
  "Delete event": "Fshi ngjarje",
  "Stop repeating on this date": "Ndaloni të përsërisni në këtë datë",
  "Exclude this date": "Përjashtoni këtë datë",
  "Location is going to be announced": "Vendndodhja do të shpallet",
  "Fill your personal information": "Plotësoni informacionin tuaj personal",
  "Check Box": "Kutia e kontrollit",
  "Single Choice": "Zgjedhje e vetme",
  Option: "Opsion",
  "Share Event": "Ngjarja e ndarë",
  "Oops! Something went wrong": "Oops! Diçka shkoi keq",
  "We are sorry this event has already taken place":
    "Na vjen keq që kjo ngjarje tashmë ka ndodhur",
  "Back to calendar": "Kthehu në Kalendar",
  "This field is required": "Kjo fushë është e nevojshme",
  Phone: "Telefon",
  "Number field": "Fusha e numrit",
  "Please provide a valid email": "Ju lutemi jepni një email të vlefshëm",
  "Select at least one option": "Zgjidhni të paktën një opsion",
  "Choose tickets to see total value":
    "Zgjidhni biletat për të parë vlerën totale",
  tickets: "Bileta",
  "Choose Tickets": "Zgjidhni Biletat",
  "Choose payment method": "Zgjidhni metodën e pagesës",
  Pay: "Paguaj",
  Total: "Total",
  Free: "Falas",
  "Buy tickets": "Bleni bileta",
  "Sold Out": "E shitur",
  "Tickets are available": "Biletat janë në dispozicion",
  "Sales End": "Fundi i shitjeve",
  "Availible from": "Në dispozicion nga",
  "Go to Orders": "Shko te porositë",
  "Go to Details": "Shko te Detajet",
  "Group ticket": "Bileta e Grupit",
  Name: "Emri",
  Price: "Pricemimi",
  "Order by": "Urdhër nga",
  "Order ID": "ID e porosisë",
  Applied: "Aplikuar",
  Fees: "Tarifat",
  "Enter promo code": "Vendosni kodin promo",
  Apply: "Apliko",
  "Promo Code": "Kod promocional",
  Cash: "Paraja",
  "You can find your e-tickets attached to your email or download them":
    "Ju mund të gjeni pikat tuaja elektronike të bashkangjitura në emailin tuaj ose t'i shkarkoni ato",
  here: "Këtu",
  Time: "Koha",
  "Invalid promo code": "Kodi i pavlefshëm i promovimit",
  "Credit card": "Kartë Krediti",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Së shpejti do të merrni një mesazh konfirmimi të regjistrimit të suksesshëm në adresën tuaj të postës elektronike.",
  "You can also check your order details below.":
    "Ju gjithashtu mund të kontrolloni detajet e porosisë tuaj më poshtë.",
  at: "në",
  Buy: "Blej",
  Donation: "Dhurim",
  "Enter price": "Vendosni çmimin",
  Choose: "Zgjidhni",
  Chosen: "Zgjedhur",
  "Choose your plan": "Zgjidhni planin tuaj",
  week: "javë",
  wk: "wk",
  "Choose plan cycle": "Zgjidhni ciklin e planit",
  months: "muaj",
  years: "vite",
  weeks: "javë",
  "Copy Event Url": "Kopjoni URL -në e ngjarjes",
  "You can find your e-tickets attached to your email or print them":
    "Ju mund të gjeni pikat tuaja elektronike të bashkangjitura në emailin tuaj ose t'i shtypni ato",
  "Guest Info": "Informacion i Vizitorëve",
  "Ticket Info": "Informacioni i biletave",
  "Ticket name": "Emri i Biletës",
  "Ticket price": "Cmimi i biletes",
  "Ticket ID": "ID e biletave",
  "If you have any questions contact to organizer":
    "Nëse keni ndonjë pyetje kontaktoni me organizatorin",
  "As soon as event ends": "Sapo të mbarojë ngjarja",
  "1 day after event ends": "1 ditë pasi mbaron ngjarja",
  "7 days after event ends": "7 ditë pas mbarimit të ngjarjes",
  "14 days after event ends": "14 ditë pasi mbaron ngjarja",
  "30 days after event ends": "30 ditë pasi mbaron ngjarja",
  Menu: "Menu",
  "No event for selected date": "Asnjë ngjarje për datën e zgjedhur",
  view: "pamje",
  List: "Listë",
  Year: "Viti",
  Yearly: "Vjetore",
  "Year view header": "View View Header",
  "Yearly Style": "Stili vjetor",
  "There are no events": "Nuk ka ngjarje",
  Autotranslation: "Autotranslation",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Pasi të aktivizohet, widget juaj i kalendarit do të përkthehet bazuar në gjuhën e faqes në internet. *Vini re se për sa kohë që titulli i kalendarit, dhe përshkrimet futen tekste ato nuk mund të përkthehen.",
  "Note on mobile": "Shënim në celular",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Fikni ose ndryshoni tekstin e shiritit pa ngjarje në versionin celular të kalendarit",
  Autodeletion: "Autodeletion",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Mundësimi i opsionit, automatikisht do të heqë ngjarjet tuaja të kaluara nga kalendari.",
  "This does not apply to repeating events!":
    "Kjo nuk vlen për të përsëritur ngjarjet!",
  "Notify event creators about the guest":
    "Njofto krijuesit e ngjarjeve për të ftuarin",
  "Send event creators notification emails as soon as guests register for their events":
    "Dërgoni postë elektronike të njoftimit të krijuesve të ngjarjeve sa më shpejt që të ftuarit të regjistrohen për ngjarjet e tyre",
  "List View Type": "Lloji i shikimit të listës",
  "Description font": "Përshkrimi Font",
  Connect: "Lidhu",
  "You have no events": "Ju nuk keni ngjarje",
  Synchronize: "Sinkronizoni",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Google Calendar Sync ju lejon të integroni ngjarjet dhe seancat tuaja me kalendarin tuaj të bumit.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Sinkronizimi i Kalendarit Outlook ju lejon të integroni ngjarjet dhe seancat tuaja me kalendarin tuaj të bumit.",
  "Your message has been sent successfully!":
    "Mesazhi juaj është dërguar me sukses!",
  "There are no synchronized calendars": "Nuk ka kalendarë të sinkronizuar",
  "to view more than 7 events": "Për të parë më shumë se 7 ngjarje",
  "Mobile app": "Aplikacioni Mobile",
  "Admin Account": "Llogaria e administratorit",
  Password: "Fjalëkalim",
  "Second User": "Përdorues i dytë",
  Edit: "Redakto",
  "Guest limit": "Kufiri i Vizitorëve",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Të gjitha cilësimet lokale bazohen (automatikisht) bazuar në gjuhën tuaj. Nëse gjuha juaj është në listë, nuk ka nevojë ta rregulloni këtë seksion.",
  available: "Në dispozicion",
  next: "Tjetra",
  Tickets: "Bileta",
  Quantity: "Sasi",
  "Promo code": "Kod promocional",
  "Select a payment method": "Zgjidhni një metodë pagese",
  Fee: "Tarifa",
  Book: "Libër",
  "All the tickets have been sold out": "Të gjitha biletat janë shitur",
  "Choose at least one ticket": "Zgjidhni të paktën një biletë",
  "First choose ticket": "Së pari zgjidhni biletën",
  "Please fill out your personal information.":
    "Ju lutemi plotësoni informacionin tuaj personal.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "Për të bërë një blerje të suksesshme, ju lutemi zgjidhni metodën tuaj të preferuar të pagesës dhe shkruani kodin promo për biletat e zbritura.",
  "Credit/Debit card": "Karta e kreditit/debitit",
  "print here.": "Shtyp këtu.",
  "QR code for all tickets": "Kodi QR për të gjitha biletat",
  Duration: "Kohëzgjatja",
  "Full Name": "Emri i plotë",
  "Ticket id": "ID e biletave",
  "Group id": "ID e grupit",
  "Choose your ticket.": "Zgjidhni biletën tuaj.",
  "Fill out your personal information.":
    "Plotësoni informacionin tuaj personal.",
  "Add the payment details.": "Shtoni detajet e pagesës.",
  "To be determined": "Te jesh i vendosur",
  "You can find your e-tickets attached to the email or":
    "Ju mund të gjeni pikat tuaja elektronike të bashkangjitura në email ose",
  "print here": "Shtyp këtu",
  "Full name": "Emri i plotë",
  "Group ID": "ID e grupit",
  "to Book": "të rezervosh",
  "Unfortunately, your card has been declined":
    "Fatkeqësisht, karta juaj është refuzuar",
  "Thank you for your purchase!": "Faleminderit per blerjen tuaj!",
  "Find your printable e-tickets attached to the confirmation email":
    "Gjeni biletat tuaja të shtypura elektronike të bashkangjitura në emailin e konfirmimit",
  Confirm: "Konfirmoni",

  "Add event": "Shto ngjarje",
  Events: "Ngjarje",
  "Event details": "Detajet e ngjarjes",
  Registration: "Regjistrim",
  "Guests list": "Lista e miqve",
  Ticket: "Biletë",
  "General Info": "Informacion i përgjithshëm",
  "Customize the general settings of your event":
    "Rregulloni cilësimet e përgjithshme të ngjarjes tuaj",
  "Event Title": "Titulli i ngjarjes",
  "e.g. Birthday Party": "p.sh. Feste ditelindje",
  "All Day Event": "Ngjarja gjatë ditës",
  Cross: "Kryqëzim",
  Timeline: "Afat kohor",
  "Repeating event": "Ngjarja e përsëritur",
  Location: "Vend",
  "Venue name": "Emrin e vendit të ngjarjes",
  Description: "Përshkrim",
  Image: "Imazh",
  Color: "Ngjyrë",
  Category: "Kategori",
  "Add your events to color categories and let your users classify them easily":
    "Shtoni ngjarjet tuaja në kategoritë e ngjyrave dhe lërini përdoruesit tuaj t'i klasifikojnë ato lehtë",
  "Category name": "Emrin e kategorisë",
  "e.g. Birthdays": "p.sh. Ditëlindje",
  Venue: "Vendndodhje",
  "Where the event takes place": "Ku zhvillohet ngjarja",
  "Venue name": "Emrin e vendit të ngjarjes",
  "Venue phone": "Telefon i vendit të ngjarjes",
  "Venue email": "Email i vendit të ngjarjes",
  "Venue website": "Uebfaqja e Vendit",
  Organizer: "Organizator",
  "Person who makes the event": "Personi që bën ngjarjen",
  "Organizer name": "Emër organizatori",
  "Organizer phone": "Telefon organizator",
  "Organizer email": "Email i organizatorit",
  "Organizer website": "Uebfaqja e Organizatorit",
  Save: "Ruaj",
  Cancel: "Anuloj",
  Import: "Importoj",
  Past: "I kaluar",
  All: "Të gjithë",
  Upcoming: "I ardhshëm",
  Uncategorised: "I pa kategorizuar",
  "Date Ascending": "Data në ngjitje",
  "Date Descending": "Data që zbret",
  "Title by A-Z": "Titulli nga A-Z",
  "Title by Z-A": "Titulli nga Z-A",
  "There are no events for this period": "Nuk ka ngjarje për këtë periudhë",

  "Auto-Convert Date & Time": "Data dhe koha e konvertimit automatik",
  TimeZone: "Mikone kohore",
  Autodeletion: "Autodeletion",
  "Layout Settings": "Cilësimet e paraqitjes",
  "Yeatly view": "Shiko me shije",
  "Monthly view header": "Titulli i shikimit mujor",
  "Weekly/Daily view header": "Titulli i përjavshëm/Daily View",
  Acendings: "Acendings",
  Descending: "Që rrjedh",
  Standart: "I rëndësishëm",
  Silver: "Argjend",
  Retro: "Retro",
  Dark: "I errët",
  Night: "Natë",
  Aubergine: "Patëllxhan",
  "List view header": "Lista e shikimit të kokës",
  "Side by Side View": "Pamje anësore",
  "Customize Proportions": "Rregulloni përmasat",
  "Card Margins": "Kufijtë e kartave",
  "Image opacity (%)": "Opaciteti i figurës (%)",
  "Side by Side Header": "Kundërshit krah për krah",
  "Text Align": "Bashkohem me tekst",
  "Timeline View": "Pamja e afatit kohor",
  "Title font color": "Titulli Ngjyra e shkronjave",
  "Desciption font color": "Ngjyra e shkronjave të zbritjes",
  "Line color": "Ngjyra e linjës",
  "Date Font color": "Ngjyra e shkronjave të datës",
  "Daily events background": "Sfondi i ngjarjeve ditore",
  Alignment: "Radhitje",
  Vertical: "Vertikal",
  Horizontal: "Horizontal",
  "Vertical Alignment": "Shtrirje vertikale",
  Right: "I drejtë",
  Center: "Qendër",
  "Horizontal Alignment": "Shtrirje horizontale",
  Top: "I lartë",
  Center: "Qendër",
  Bottom: "Fund",
  "Dates Circle Design": "Datat e Dizajnit të Rrethit",
  "Next To The Circle": "Pranë rrethit",
  "In The Circle": "Në rreth",
  "Timeline Header": "Afat kohor",
  Timeline: "Afat kohor",
  "Show only upcoming": "Trego vetëm të ardhshëm",
  "Order by": "Urdhër nga",
  "Timeline Event Limit": "Kufiri i Ngjarjes Timeline",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Lejoni vizitorin të shtojë ngjarje në Calnedars Lokale: Google, Yahoo, Outlook, Icalendar.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Lejoni vizitorin të ndajë ngjarjen tuaj në Facebook, LinkedIn, Twitter etj.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Shtoni një opsion kërkimi në kalendarin tuaj për t'i lënë njerëzit të kërkojnë ngjarjet tuaja sipas titullit, vendit të ngjarjes, etj.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Lejoni përdoruesit tuaj të shtypin Kalendarin tuaj të Ngjarjes Bum në çdo interval data.",
  "Click to apply a theme to Calendar":
    "Klikoni për të aplikuar një temë në kalendar",
  "Date container color": "Data e ngjyrës së kontejnerit",
  "Daily events background": "Sfondi i ngjarjeve ditore",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Përdorni shtesat për të instaluar veçori të përparuara në kalendarët tuaj, duke i bërë ato më funksionale!",
  "Open Add-ons Store": "Hapni Shtesa Dyqan",
  Monday: "E hënë",
  Tuesday: "E martë",
  Wednesday: "E mërkurë",
  Thursday: "E enjte",
  Friday: "E premte",
  Saturday: "E shtunë",
  Sunday: "E diel",
  "Yearly view": "Pamja vjetore",
  Ascending: "Ngjitës",
  "Show event time next to title": "Shfaq kohën e ngjarjes pranë titullit",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Rregulloni datën dhe kohën e ngjarjes në kohën lokale të përdoruesit bazuar në zonën e tyre kohore.",
  "Display the time zone alongside the event date.":
    "Shfaq zonën kohore së bashku me datën e ngjarjes.",
  "Show event time next to title": "Shfaq kohën e ngjarjes pranë titullit",
  "Time Zone": "Zonë kohore",
  "Upload Image": "Ngarko imazhin",
  "Choose a Category": "Zgjidhni një kategori",
  "Color you have chosen will not be shown as you choose category":
    "Ngjyra që keni zgjedhur nuk do të tregohet ndërsa zgjidhni kategorinë",
  Website: "Faqe interneti",
  Next: "Tjetër",
  Save: "Ruaj",
  "Last Name": "Mbiemri",
  "Personal Info": "Informacione Personale",
  Back: "I prapambetur",
  "This field is required": "Kjo fushë është e nevojshme",
  "Your event has been submitted": "Ngjarja juaj është dorëzuar",
  "Enter a location": "Futni një vendndodhje",
  "Display the time zone alongside the event date.":
    "Shfaq zonën kohore së bashku me datën e ngjarjes.",
  Home: "Shtëpi",
  "Side By Side Event Limit": "Kufiri i ngjarjes anash",
  "Mobille App": "Aplikacioni Mobille",
  category: "kategori",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Mbani me lehtësi orarin tuaj duke importuar ngjarjet tuaja në Facebook në kalendarin tuaj.",
  "Synchronized Pages": "Faqet e sinkronizuara",
  "There are no synchronized pages": "Nuk ka faqe të sinkronizuara",
  "Choose page": "Zgjidhni faqen",
  "You have no events": "Ju nuk keni asnjë ngjarje",
};
export default sq;
