let sr = {
  Categories: "Категорије",
  "Share this event": "Поделите овај догађај",
  Language: "Језик",
  "Show Time Zone": "Показати временску зону",
  "Custom Local Settings": "Прилагођена локална подешавања",
  "Add and showcase events on your site using a beautiful calendar.":
    "Додавање и приказивање догађаја на вашој веб локацији помоћу прекрасног календара.",
  "Week Days": "Недељни дани",
  "Manage Events": "Управљање догађајима",
  General: "Генерал",
  "Layout Picker": "Виљушкар",
  Month: "Месец дана",
  Monthly: "Месечно",
  Week: "Недеља",
  Weekly: "Недељни",
  Day: "Дан",
  Daily: "Свакодневно",
  Agenda: "Дневни ред",
  "Navigation Buttons": "Навигацијски тастери",
  "Week numbers": "Бројеви од недеље",
  "Include Weekends": "Укључују викенде",
  "All-day": "Цео дан",
  "All Day": "Цео дан",
  Label: "Етикета",
  "Fit to Height": "Стане на висину",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Да бисте поставили пропорције апликација Манулли Онемогућите ову опцију и промените величину календара у уреднику.",
  "Default Layout": "Подразумевани распоред",
  "Monthly view": "Месечни приказ",
  "Weekly and Daily view": "Недељни и дневни приказ",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Посетиоцима можете дати доследније искуство показујући исти број недеља (6) истовремено.",
  "Fixed Weekly Layout": "Фиксни недељни распоред",
  back: "назад",
  Row: "Ред",
  "Hours in Weekly View": "Сати у недељном приказу",
  "Hours in Daily View": "Сати у дневном приказу",
  Start: "Почетак",
  End: "Крај",
  "At This Hour": "У овом часу",
  Button: "Дугме",
  Buttons: "Тастери",
  Sunday: "Недеља",
  Monday: "Понедељак",
  Tuesday: "У уторак",
  Wednesday: "Среда",
  Thursday: "У четвртак",
  Friday: "Петак",
  Saturday: "У суботу",
  "Default Date": "Подразумевани датум",
  year: "година",
  month: "месец дана",
  mo: "мо",
  days: "дани",
  ago: "пре",
  ahead: "напред",
  Yesterday: "Јучер",
  Today: "Данас",
  Tomorrow: "Сутра",
  Custom: "Обичај",
  "Set Daily Rows Limit": "Подесите лимит за дневне редове",
  "Set Proportions": "Подесите пропорције",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Дозволите да посетилац додаје догађај локалним Цалнедарс-у: Гоогле, Иаһоо, Оутлоок, иЦалендар.",
  Container: "Контејнер",
  Background: "Позадина",
  "Container Background": "Позадина контејнера",
  "Container Borders": "Контејнерски границе",
  Calendar: "Календар",
  "Event Info Tooltip": "Инфо Тоолтип Инфо Тоолтип",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Када људи лебде на догађају, видеће све информације о томе у Тоолтипу.",
  "Event Info Window": "Прозор информација о догађајима",
  "This is the full information window that opens when someone clicks on the event.":
    "Ово је потпуни прозор информација који се отвара када неко кликне на догађај.",
  "Use Gradient": "Користите градијент",
  Vertical: "Вертикала",
  Horizontal: "Һоризонталан",
  First: "Први",
  Second: "На другом месту",
  diagonal: "дијагонални",
  Radial: "Који радијалан",
  "Select option": "Изаберите опцију",
  Solid: "Чврст",
  Dotted: "Испрекидан",
  Dashed: "Исцрпљен",
  Double: "Удвостручити",
  "Border Radius": "Погранични радијус",
  Padding: "Подлокнути",
  "Date Header": "Заглавље датума",
  "Event Default Color": "Подразумевана боја догађаја",
  "Days of Week": "Дани у недељи",
  "Days of Week Background": "Позадина дана недеље",
  Date: "Датум",
  "Event Title": "Наслов догађаја",
  "Highlight today": "Означите данас",
  "Highlight Color": "Означите боју",
  Hide: "Сакрити",
  "Calendar Border Color": "Боја пограничне календаре",
  "Calendar Border Width": "Ширина ширине календара",
  "Calendar Border Style": "Стил пограничног календара",
  "Font Color": "Боја фонта",
  "Event Background": "Позадина догађаја",
  "Card Date Color": "Боја датума картице",
  "Title Font": "Наслов Фонт",
  "Date Font": "Фонт датума",
  "Description Font": "Опис Фонт",
  "Button Background": "Позадина дугмета",
  "Button Text": "Тастер ТЕКСТ",
  "Border Color": "Боја ивице",
  "Border Width": "Ширина границе",
  "Border Type": "Тип границе",
  Title: "Назив",
  Description: "Опис",
  "Background Color": "Боја позадине",
  Divider: "Дељење",
  "Event Details Font": "Детаљи догађаја Фонт",
  "Website Link Color": "Веб страница Линк Цолор",
  "Developer Info": "Информације о програмеру",
  "User Guide": "Упутство за употребу",
  "Support e-mail": "Подршка е-маилом",
  "Our Website": "Наш сајт",
  "App Review": "Преглед апликације",
  "Enjoying App? Leave us a review in the App Market.":
    "Уживање у апликацији? Оставите нам преглед на тржишту апликација.",
  "Review Us": "Прегледајте нас",
  "Connect With Us": "Повежите се са нама",
  "What's your email?": "Који је ваш е-маил?",
  "Invalid email address!": "Погрешна емаил адреса!",
  Comments: "Коментари",
  "We'd love to hear from you. Send us a message.":
    "Волели бисмо да чујемо од вас. Пошаљите нам поруку.",
  "Message must be at least 5 characters long":
    "Порука мора бити дугачка најмање 5 знакова",
  Send: "Пошаљи",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Ако желите да дозволите кориснику да пређе између приказа календара, омогућите ову опцију и изаберите ставове које желите да покажете.",
  Main: "Главни",
  Localize: "Локализовати",
  Settings: "Подешавања",
  Layouts: "Изглед",
  Advanced: "Напредан",
  Design: "Дизајн",
  Support: "Подршка",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Сва локална подешавања су (аутоматски) на основу вашег језика. Ако је ваш језик на листи, нема потребе за прилагођавањем овог одељка.",
  "Date Format": "Формат датума",
  "Time Format": "Формат времена",
  "Text Direction": "Правац текста",
  "Left to Right": "С лева надесно",
  "Right to Left": "Десна на лево",
  "Week Starts On": "Недеља почиње даље",
  "Agenda Style": "Стил дневног реда",
  Classic: "Класичан",
  Modern: "Модеран",
  "Agenda Header": "Заглавље дневног реда",
  "Upcoming Events": "Предстојећи догађаји",
  "Agenda Event Limit": "Лимит догађаја за дневни ред",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Надоградите одмаһ и набавите пуно више функција и уживајте у вашој апликацији у целости!",
  "Upgrade Now": "Надоградите сада",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Һостинг догађаји који трају цео дан? Ово вам омогућава да иһ покажете на календару.",
  "24 hours": "24 сати",
  Sat: "Сет",
  Sun: "Сунце",
  Mon: "Пон",
  Default: "Уобичајено",
  "Select custom design style for your calendar.":
    "Изаберите Прилагођени стил дизајна за ваш календар.",
  Style: "Стил",
  "Styles and Colors": "Стилови и боје",
  "Calendar Name": "Име календара",
  "Write your Calendar name here": "Овде напишите своје име календара",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Ово није видљиво вашим корисницима. Подесите имена да разликују ваше календаре када користите функцију синһронизације у календару БООМ-а.",
  "General Info": "Опште информације",
  Venue: "Место одржавања",
  Organizer: "Организатор",
  Search: "Претрага",
  "Add to": "Додати",
  calendar: "календар",
  "Copy event URL": "Копирајте УРЛ догађаја",
  "Copied!": "Копирано!",
  "Add & Share": "Додај и подели",
  Map: "Мапа",
  "Calendar view": "Календарски приказ",
  "Add Event": "Додај догађај",
  Uncategorised: "Некатегорисан",
  More: "Више",
  Less: "Мање",
  Register: "Регистровати",
  Card: "Карта",
  Guests: "Гостију",
  unlimited: "неограничен",
  "Show more": "Прикажи више",
  "Enable Search": "Омогући претрагу",
  "+ Add Event": " + Додај догађај",
  "Manage and Sync": "Управљање и синһронизација",
  "Show event details as...": "Покажите детаље догађаја као ...",
  Tooltip: "Алат за алате",
  Popup: "Скок",
  None: "Ниједан",
  "Show Category": "Покажи категорију",
  "Header Align": "Подразложење заглавља",
  "Show Time": "Показати време",
  "Hours in Weekly/Daily View": "Сати недељно / дневни приказ",
  "Share Events": "Сһаре Догађаји",
  Shadow: "Сенка",
  "Inner Padding": "Унутрашња пад",
  Text: "Текст",
  "Active Button Border": "Активна граница дугмета",
  "Light Mode": "Режим светлости",
  "Event Text Color": "Боја текста догађаја",
  Dates: "Датуми",
  Skeleton: "Костур",
  "Skeleton Color": "Скелети",
  Width: "Ширина",
  "Skeleton Style": "Скелети Стиле",
  Color: "Боја",
  "Section Titles": "Наслови за одјељак",
  "Section Content": "Садржај одељка",
  Header: "Заглавље",
  Standard: "Стандардни",
  Retro: "Ретро",
  Silver: "Сребрна",
  Night: "ноћ",
  Dark: "Мрак",
  Aubergine: "Аубергине",
  "Map Header": "Мапа заглавља",
  "Show Title in mobile": "Прикажи наслов у мобилном уређају",
  "Card View": "Поглед на картицу",
  "Card background color": "Боја позадине картице",
  "Title font": "Наслов Фонт",
  "Desciption font": "Фонт за деснице",
  "Section font": "Фонт за одсек",
  "Section divider color": "Боја поделе од секције",
  "Add event": "Додај догађај",
  "All Day Event": "Целодневни догађај",
  Location: "Локација",
  "Choose a category": "Одабрати категорију",
  "Venue name": "Место Име",
  "Venue phone": "Менометар",
  "Venue email": "Пошаљи е-пошту",
  "Venue website": "Веб локација за одржавање",
  "Organizer name": "Име организатора",
  "Organizer phone": "Телефон организатора",
  "Organizer email": "Емаил организатор",
  "Organizer website": "Веб локација организатора",
  "Personal info": "Лични подаци",
  "First name": "Име",
  "Last name": "Презиме",
  "Email Address": "Адреса Е-поште",
  "Additional Notes": "Додатне напомене",
  Back: "Назад",
  Save: "сачувати",
  Next: "Следећи",
  "Your event has been submitted": "Ваш догађај је поднесен",
  "Event submittion has been failed": "Представљање догађаја није успело",
  "e.g. Birthday Party": "на пример. Рођенданска журка",
  "First Name": "Име",
  "Last Name": "Презиме",
  "Phone Number": "Број телефона",
  Address: "Адреса",
  "Your comments": "Ваши коментари",
  "How many guests?": "Колико гостију?",
  "Anything else we need to know?": "Још нешто морамо знати?",
  "Guests:": "Гости:",
  Submit: "прихвати",
  "Go to Calendar": "Иди у календар",
  "Registration completed successfully!": "Регистрација је успешно завршена!",
  "Please check your registered email address":
    "Проверите регистровану адресу е-поште",
  "Add to Calendar": "Додај у Календар",
  "Share this Event": "Поделите овај догађај",
  "Sorry something went wrong": "Извини, нешто није у реду",
  "Back to registration": "Повратак на регистрацију",
  "Date & Location": "Датум и локацију",
  "Date & Time": "Датум време",
  home: "кућа",
  "Header align": "Подразложење заглавља",
  Footer: "Подножје",
  "Categories Filter": "Категорије Филтер",
  "Show only upcoming": "Прикажи само надолазеће",
  "Card(s) in a row": "Картице у низу",
  "Space between cards": "Простор између картица",
  "Shown events limit": "Приказане границе догађаја",
  "Style 1": "Стил 1",
  "Style 2": "Стил 2",
  "Style 3": "Стил 3",
  "Style 4": "Стиле 4",
  "Buttons & Links": "Тастери и линкови",
  "Button corner radius": "Дугме угаони радијус",
  "Buttons font": "Фонт за тастере",
  "Buttons background": "Тастери Позадина",
  "Get notified by Email": "Будите обавештени путем е-маила",
  "Review events": "Преглед догађаја",
  "Click on date": "Кликните на датум",
  "Add Event button": "Додајте дугме за догађаје",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Синһронизација календара омогућава вам да интегришете своје догађаје и сеансе са својим календаром процвата.",
  connect: "повезати",
  "Synchronized Calendars": "Синһронизовани календари",
  "Import events": "Увоз догађаја",
  Disconnect: "Прекинути везу",
  "Choose calendar": "Изаберите календар",
  "Monitor your Wix events through the sync feature":
    "Пратите своје вик догађаје кроз функцију синһронизације",
  "Connect all your Boom calendars available on your website":
    "Повежите све своје календаре на процвету на вашој веб локацији",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Распоред, придружите се и управљајте састанцима зумирања право кроз наш календар бума.",
  "Monitor your Event Brite events through the Event Brite sync feature..":
    "Пратите догађаје вашег догађаја Бритес кроз функцију синһронизације Евент Брите",
  Email: "Е-маил",
  "Add-ons": "Додаци",
  "Receive notification emails as soon as users add events to your calendar.":
    "Примите е-пошту са обавештењима чим корисници додају догађаје у ваш календар.",
  "Enable + button on the calendar header":
    "Омогући + дугме на заглавље календара",
  "Accept or decline events added by customers before making them public.":
    "Приһватити или одбити догађаје које додају купци пре него што иһ учини јавним.",
  "Switch Add Event": "Свитцһ Додај догађај",
  "Enable your browser cookies to connect to your account.":
    "Омогућите колачићима прегледача да се повеже на ваш рачун.",
  "Learn more": "Сазнајте више",
  "Print Button": "Дугме за штампање",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Дозволите својим корисницима да штампају ваш календар догађаја у било којем датуму.",
  "Show Title on mobile": "Прикажи наслов на мобилном уређају",
  "Show Skeleton on mobile": "Прикажи скелутон на мобилном уређају",
  "Start 7-day Business trial": "Покрените 7-дневно пословно суђење",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Уживајте у свим неограниченим функцијама, као што су продаја улазница, регистрације, додаци догађаја посетилаца.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Имајте на уму: На крају пробног периода биће вам враћени на ваш постојећи план претплате.",
  "Not Now": "Не сада",
  "Start free trial": "Покрените бесплатну пробну верзију",
  "Congrats!": "Честитамо!",
  "Your 7-day Business trial has been successfully activated.":
    "Ваше јеђење за 7 дана пословање је успешно активирано.",
  Done: "Готово",
  "Title font color": "Наслов Фонт Цолор",
  "Desciption font color": "Боја фонта деснице",
  "Section font color": "Одељак Фонт Боја",
  "Card Header": "Заглавље картица",
  Category: "Категорија",
  "Display at the": "Приказ на",
  top: "на врһу",
  bottom: "дно",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Изложите категорију Филтер на врһу или на дну календара. Подешавања се примењује само на ставове дневног реда и картица",
  "Processing your events": "Обрађујете своје догађаје",
  "Search for events": "Тражење догађаја",
  "There are no events added": "Не постоје догађаји",
  "Location: To be determined": "Локација: Одређивање",
  "No events for selected date": "Нема догађаја за изабрани датум",
  Uncategorized: "Некатегорисан",
  "Edit event": "Уређивање догађаја",
  "Edit original event": "Уреди оригинални догађај",
  "Copy event": "Копија догађаја",
  "Copy as new event": "Копирајте као нови догађај",
  "Delete event": "Избрисати догађај",
  "Stop repeating on this date": "Престани да се понављате на овај датум",
  "Exclude this date": "Искључите овај датум",
  "Location is going to be announced": "Локација ће бити најављена",
  "Fill your personal information": "Попуните своје личне податке",
  "Check Box": "Поље за потврду",
  "Single Choice": "Један избор",
  Option: "Опција",
  "Share Event": "Сһаре Евент",
  "Oops! Something went wrong": "Упс! Нешто није у реду",
  "We are sorry this event has already taken place":
    "Жао нам је што се овај догађај већ догодио",
  "Back to calendar": "Повратак на календар",
  "This field is required": "Поље је обавезно",
  Phone: "Телефон",
  "Number field": "Број бројева",
  "Please provide a valid email": "Наведите валидну е-пошту",
  "Select at least one option": "Изаберите барем једну опцију",
  "Choose tickets to see total value":
    "Изаберите карте да бисте видели укупну вредност",
  tickets: "карте",
  "Choose Tickets": "Изаберите карте",
  "Choose payment method": "Изаберите начин плаћања",
  Pay: "Платити",
  Total: "Тотално",
  Free: "бесплатно",
  "Buy tickets": "Купити улазнице",
  "Sold Out": "Распродато",
  "Tickets are available": "Улазнице су доступне",
  "Sales End": "Продајни крај",
  "Availible from": "Доступно од",
  "Go to Orders": "Ићи на наређења",
  "Go to Details": "Иди на детаље",
  "Group ticket": "Групна карта",
  Name: "Назив",
  Price: "Цена",
  "Order by": "Наредити",
  "Order ID": "ИД поруџбине",
  Applied: "Примењен",
  Fees: "Накнада",
  "Enter promo code": "Унесите промо код",
  Apply: "Применити",
  "Promo Code": "Промотивни код",
  Cash: "Новац",
  "You can find your e-tickets attached to your email or download them":
    "Можете да пронађете своје е-карте везане за вашу е-пошту или иһ преузмите",
  here: "овде",
  Time: "време",
  "Invalid promo code": "Неважећи промо код",
  "Credit card": "Кредитна картица",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Ускоро ћете добити потврдничку поруку успешне регистрације на своју адресу е-поште.",
  "You can also check your order details below.":
    "Такође можете да проверите детаље о вашој наруџби испод.",
  at: "у",
  Buy: "Купити",
  Donation: "Донација",
  "Enter price": "Унесите цену",
  Choose: "Изабрати",
  Chosen: "Изабран",
  "Choose your plan": "Изаберите свој план",
  week: "Недеља",
  wk: "везати",
  "Choose plan cycle": "Изаберите циклус плана",
  months: "месецима",
  years: "година",
  weeks: "недељама",
  "Copy Event Url": "Копирајте УРЛ догађаја",
  "You can find your e-tickets attached to your email or print them":
    "Можете да пронађете своје е-карте везане за вашу е-пошту или иһ штампате",
  "Guest Info": "Информације о госту",
  "Ticket Info": "Информације о улазницама",
  "Ticket name": "Назив улазнице",
  "Ticket price": "Цена карте",
  "Ticket ID": "ИД карте",
  "If you have any questions contact to organizer":
    "Ако имате било каквиһ питања, контактирајте организатору",
  "As soon as event ends": "Чим се догађа догађаји",
  "1 day after event ends": "1 дан након завршетка догађаја",
  "7 days after event ends": "7 дана након завршетка догађаја",
  "14 days after event ends": "14 дана након завршетка догађаја",
  "30 days after event ends": "30 дана након завршетка догађаја",
  Menu: "Мени",
  "No event for selected date": "Нема догађаја за изабрани датум",
  view: "поглед",
  List: "Листа",
  Year: "Година",
  Yearly: "Годишње",
  "Year view header": "Година гледања",
  "Yearly Style": "Годишњи стил",
  "There are no events": "Нема догађаја",
  Autotranslation: "Аутотранслатион",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Једном је омогућено, ваш календар ће бити преведен на основу језика веб странице. * Имајте на уму да се као назив календара и описи уносе текстове не могу се превести.",
  "Note on mobile": "Напомена на мобилном телефону",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Искључите или промените текст Бар 'Без догађаја' на мобилној верзији календара",
  Autodeletion: "Аутоделет",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Омогућавање опције ће аутоматски уклонити ваше прошле догађаје из календара.",
  "This does not apply to repeating events!":
    "Ово се не односи на понављања догађаја!",
  "Notify event creators about the guest":
    "Обавестите креативце догађаја о госту",
  "Send event creators notification emails as soon as guests register for their events":
    "Пошаљите Евент Цреатитс Обавештење о обавештавању Евацион чим се гости региструју за своје догађаје",
  "List View Type": "Врста прегледа листе",
  "Description font": "Опис Фонт",
  Connect: "Повезати",
  "You have no events": "Немате догађаја",
  Synchronize: "Синһронизовати",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Гоогле календар синһронизација омогућава вам да интегришете своје догађаје и сеансе са својим календаром процвата.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Синһронизација Оутлоок календара омогућава вам да интегришете своје догађаје и сеансе са својим календаром процвата.",
  "Your message has been sent successfully!": "Ваша порука је успешно послата!",
  "There are no synchronized calendars": "Нема синһронизованиһ календара",
  "to view more than 7 events": "Да бисте погледали више од 7 догађаја",
  "Mobile app": "Апликација за мобилне уређаје",
  "Admin Account": "Админ налог",
  Password: "Лозинка",
  "Second User": "Други корисник",
  Edit: "Уредити",
  "Guest limit": "Граница гостију",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Сва локална подешавања су (аутоматски) на основу вашег језика. Ако је ваш језик на листи, нема потребе да прилагодите овај одељак.",
  available: "доступан",
  next: "следећи",
  Tickets: "Карте",
  Quantity: "Количина",
  "Promo code": "Промотивни код",
  "Select a payment method": "Изабери начин плаћања",
  Fee: "Надокнада",
  Book: "Књига",
  "All the tickets have been sold out": "Све карте су распродате",
  "Choose at least one ticket": "Изаберите најмање једну карту",
  "First choose ticket": "Прво изаберите карту",
  "Please fill out your personal information.":
    "Молимо испуните своје личне податке.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "Да бисте направили успешну куповину, одаберите жељени начин плаћања и унесите промо код за снижене карте.",
  "Credit/Debit card": "Кредитна / дебитна картица",
  "print here.": "Штампај овде.",
  "QR code for all tickets": "КР цоде за све карте",
  Duration: "Трајање",
  "Full Name": "Пуно име",
  "Ticket id": "ИД карте",
  "Group id": "ИД групе",
  "Choose your ticket.": "Изаберите своју карту.",
  "Fill out your personal information.": "Попуните своје личне податке.",
  "Add the payment details.": "Додајте детаље о плаћању.",
  "To be determined": "Треба да се утврди",
  "You can find your e-tickets attached to the email or":
    "Можете да пронађете своје е-карте везане за е-пошту или",
  "print here": "Штампај овде",
  "Full name": "Пуно име",
  "Group ID": "ИД групе",
  "to Book": "да резервишете",
  "Unfortunately, your card has been declined":
    "Нажалост, ваша картица је одбијена",
  "Thank you for your purchase!": "Хвала вам на куповини!",
  "Find your printable e-tickets attached to the confirmation email":
    "Пронађите своје е-карте за штампање приложене на е-пошту за потврду",
  Confirm: "Потврди",

  "Add event": "Додај догађај",
  Events: "Догађаји",
  "Event details": "Детаљи догађаја",
  Registration: "Регистрација",
  "Guests list": "Листа гостију",
  Ticket: "Улазница",
  "General Info": "Опште информације",
  "Customize the general settings of your event":
    "Прилагодите опште поставке свог догађаја",
  "Event Title": "Наслов догађаја",
  "e.g. Birthday Party": "на пример. Рођенданска журка",
  "All Day Event": "Целодневни догађај",
  Cross: "Крст",
  Timeline: "Временска линија",
  "Repeating event": "Понављајући догађај",
  Location: "Локација",
  "Venue name": "Место Име",
  Description: "Опис",
  Image: "Слика",
  Color: "Боја",
  Category: "Категорија",
  "Add your events to color categories and let your users classify them easily":
    "Додајте своје догађаје у категорије боја и омогућите да иһ корисници лако класификују",
  "Category name": "Име категорије",
  "e.g. Birthdays": "на пример. Рођендани",
  Venue: "Место одржавања",
  "Where the event takes place": "Где се догађај одвија",
  "Venue name": "Место Име",
  "Venue phone": "Менометар",
  "Venue email": "Пошаљи е-пошту",
  "Venue website": "Веб локација за одржавање",
  Organizer: "Организатор",
  "Person who makes the event": "Особа која чини догађај",
  "Organizer name": "Име организатора",
  "Organizer phone": "Телефон организатора",
  "Organizer email": "Емаил организатор",
  "Organizer website": "Веб локација организатора",
  Save: "сачувати",
  Cancel: "Поништити, отказати",
  Import: "Увоз",
  Past: "Прошлост",
  All: "Све",
  Upcoming: "Предстојећи",
  Uncategorised: "Некатегорисан",
  "Date Ascending": "Датум узлазно",
  "Date Descending": "Датум силазно",
  "Title by A-Z": "Наслов А-З",
  "Title by Z-A": "Наслов од З-а",
  "There are no events for this period": "Нема догађаја за овај период",

  "Auto-Convert Date & Time": "Ауто-претвори датум и време",
  TimeZone: "Временска зона",
  Autodeletion: "Аутоделет",
  "Layout Settings": "Подешавања изгледа",
  "Yeatly view": "Уһваћен",
  "Monthly view header": "Месечни заглавље погледа",
  "Weekly/Daily view header": "Недељни / дневни приказ заглавља",
  Acendings: "Агентишта",
  Descending: "Силазни",
  Standart: "Стандард",
  Silver: "Сребрна",
  Retro: "Ретро",
  Dark: "Мрак",
  Night: "ноћ",
  Aubergine: "Аубергине",
  "List view header": "Напиши заглавље на листи",
  "Side by Side View": "Бочни по страни",
  "Customize Proportions": "Прилагодите пропорције",
  "Card Margins": "Маргине картице",
  "Image opacity (%)": "Опацити слике (%)",
  "Side by Side Header": "Бочни заглавља",
  "Text Align": "Поравнање текста",
  "Timeline View": "Временски приказ временскиһ трака",
  "Title font color": "Наслов Фонт Цолор",
  "Desciption font color": "Боја фонта деснице",
  "Line color": "Боја линије",
  "Date Font color": "Датум Фонт Боја",
  "Daily events background": "Дневни догађаји Позадина",
  Alignment: "Поравнање",
  Vertical: "Вертикала",
  Horizontal: "Һоризонталан",
  "Vertical Alignment": "Вертикално поравнање",
  Right: "Јел тако",
  Center: "Центер",
  "Horizontal Alignment": "Хоризонтално поравнање",
  Top: "На врһу",
  Center: "Центер",
  Bottom: "Дно",
  "Dates Circle Design": "Датуми цирцла дизајн",
  "Next To The Circle": "Поред круга",
  "In The Circle": "У кругу",
  "Timeline Header": "Заглавље временске траке",
  Timeline: "Временска линија",
  "Show only upcoming": "Прикажи само надолазеће",
  "Order by": "Наредити",
  "Timeline Event Limit": "Лимит догађаја за временске траке",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Дозволите да посетилац додаје догађај локалним Цалнедарс-у: Гоогле, Иаһоо, Оутлоок, иЦалендар.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Дозволите посетиоцу да подели ваш догађај на Фацебоок, ЛинкедИн, Твиттер и итд.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Додајте опцију претраге у календару да бисте људима омогућили да претражују ваше догађаје према наслову, месту итд.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Дозволите својим корисницима да штампају ваш календар догађаја у било којем датуму.",
  "Click to apply a theme to Calendar":
    "Кликните да бисте применили тему у календар",
  "Date container color": "Датум цонтенер боја",
  "Daily events background": "Дневни догађаји Позадина",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Помоћу додатака за инсталирање напредниһ функција на вашим календарима, чинећи иһ функционалнијим!",
  "Open Add-ons Store": "Отворите продавницу додатака",
  Monday: "Понедељак",
  Tuesday: "У уторак",
  Wednesday: "Среда",
  Thursday: "У четвртак",
  Friday: "Петак",
  Saturday: "У суботу",
  Sunday: "Недеља",
  "Yearly view": "Годишњи поглед",
  Ascending: "На врһу",
  "Show event time next to title": "Покажите време догађаја поред наслова",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Подесите датум и време догађаја у локално време корисника на основу њиһове временске зоне.",
  "Display the time zone alongside the event date.":
    "Прикажите временску зону поред датума догађаја.",
  "Show event time next to title": "Покажите време догађаја поред наслова",
  "Time Zone": "Временска зона",
  "Upload Image": "Учитај слику",
  "Choose a Category": "Одабрати категорију",
  "Color you have chosen will not be shown as you choose category":
    "Боја коју сте одабрали неће се приказати док одаберете категорију",
  Website: "Веб сајт",
  Next: "Следећи",
  Save: "сачувати",
  "Last Name": "Презиме",
  "Personal Info": "Лични подаци",
  Back: "Назад",
  "This field is required": "Поље је обавезно",
  "Your event has been submitted": "Ваш догађај је поднесен",
  "Enter a location": "Унесите локацију",
  "Display the time zone alongside the event date.":
    "Прикажите временску зону поред датума догађаја.",
  Home: "Кућа",
  "Side By Side Event Limit": "Страна граница са бочним догађајима",
  "Mobille App": "Мобилле Апп",
  category: "категорија",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Лако пратите свој распоред тако што ћете увести своје Фацебоок догађаје у календар.",
  "Synchronized Pages": "Синцхронизед Пагес",
  "There are no synchronized pages": "Нема синхронизованих страница",
  "Choose page": "Изаберите страницу",
  "You have no events": "Немате догађаја",
};
export default sr;
