let th = {
  Categories: "หมวดหมู่",
  "Share this event": "แบ่งปันกิจกรรมนี้",
  Language: "ภาษา",
  "Show Time Zone": "แสดงเขตเวลา",
  "Custom Local Settings": "การตั้งค่าท้องถิ่นที่กำหนดเอง",
  "Add and showcase events on your site using a beautiful calendar.":
    "เพิ่มและแสดงเหตุการณ์ที่เกิดขึ้นในเว็บไซต์ของคุณโดยใช้ปฏิทินที่สวยงาม. ",
  "Week Days": "วันในสัปดาห์",
  "Manage Events": "จัดการกิจกรรม",
  General: "ทั่วไป",
  "Layout Picker": "เครื่องมือเลือกเค้าโครง",
  Month: "เดือน",
  Monthly: "รายเดือน",
  Week: "สัปดาห์",
  Weekly: "รายสัปดาห์",
  Day: "วัน",
  Daily: "รายวัน",
  Agenda: "วาระ",
  "Navigation Buttons": "ปุ่มนำทาง",
  "Week numbers": "หมายเลขสัปดาห์",
  "Include Weekends": "รวมวันหยุดสุดสัปดาห์",
  "All-day": "ทั้งวัน",
  "All Day": "ทั้งวัน",
  Label: "ฉลาก",
  "Fit to Height": "พอดีกับความสูง",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "ในการตั้งค่าสัดส่วนแอพmanully ปิดการใช้งานตัวเลือกนี้และปรับขนาดปฏิทินในเครื่องมือแก้ไข",
  "Default Layout": "เค้าโครงเริ่มต้น",
  "Monthly view": "มุมมองรายเดือน",
  "Weekly and Daily view": "มุมมองรายสัปดาห์และรายวัน",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "คุณสา��ารถมอบประสบการณ์ที่สอดคล้องกันมากขึ้นให้กับผู้เข้าชมด้วยการแสดงจำนวนสัปดาห์ ( 6) ต่อครั้ง",
  "Fixed Weekly Layout": "แก้ไขเค้าโครงประจำสัปดาห์",
  back: " ย้อนกลับ",
  Row: "แถว",
  "Hours in Weekly View": "ชั่วโมงในการดูแบบรายสัปดาห์",
  "Hours in Daily View": "ชั่วโมงในการดูรายวัน",
  Start: "เริ่ม",
  End: "จบ",
  "At This Hour": "ในเวลานี้",
  Button: "ปุ่ม",
  Buttons: "ปุ่ม",
  Sunday: "อาทิตย์",
  Monday: "จันทร์",
  Tuesday: "อังคาร",
  Wednesday: "พุธ",
  Thursday: " วันพฤหัสบดี",
  Friday: "ศุกร์",
  Saturday: "วันเสาร์",
  "Default Date": "วันที่เริ่มต้น",
  year: " ปี",
  month: " เดือน",
  mo: " เดือน",
  days: " วัน",
  ago: " ที่ผ่านมา",
  ahead: " ไปข้างหน้า",
  Yesterday: "เมื่อวานนี้",
  Today: "วันนี้",
  Tomorrow: "วันพรุ่งนี้",
  Custom: "กำหนดเอง",
  "Set Daily Rows Limit": "ตั้งค่า จำกัด จำนวนแถวต่อวัน",
  "Set Proportions": "ตั้งสัดส่วน",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "อนุญาตให้ผู้เข้าชมเพื่อเพิ่มกิจกรรมท้องถิ่นCalnedars , Google, Yahoo, Outlook, iCalendar . ",
  Container: "ตู้คอนเทนเนอร์",
  Background: "พื้นหลัง",
  "Container Background": "พื้นหลังคอนเทนเนอร์",
  "Container Borders": "เส้นขอบคอนเทนเนอร์",
  Calendar: "ปฏิทิน",
  "Event Info Tooltip": "คำแนะนำเครื่องมือข้อมูลกิจกรรม",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "เมื่อผู้คนเลื่อนเมาส์ไปที่เหตุการณ์พวกเขาจะเห็นข้อมูลทั้งหมดเกี่ยวกับเหตุการณ์ในคำแนะนำเครื่องมือ",
  "Event Info Window": "หน้าต่างข้อมูลกิจกรรม",
  "This is the full information window that opens when someone clicks on the event.":
    "นี่เป็นหน้าต่างข้อมูลเต็มรูปแบบที่เปิดขึ้นเมื่อมีคนคลิกที่เหตุการณ์",
  "Use Gradient": "ใช้การไล่ระดับสี",
  Vertical: "แนวตั้ง",
  Horizontal: "แนวนอน",
  First: "ครั้งแรก",
  Second: "สอง",
  diagonal: " แนวทแยง",
  Radial: "รัศมี",
  "Select option": "เลือกตัวเลือก",
  Solid: "ของแข็ง",
  Dotted: "ประ",
  Dashed: "ประ",
  Double: "ดับเบิล",
  "Border Radius": "รัศมีชายแดน",
  Padding: "การขยายความ",
  "Date Header": "ส่วนหัววันที่",
  "Event Default Color": "สีเริ่มต้นของเหตุการณ์",
  "Days of Week": "วันในสัปดาห์",
  "Days of Week Background": "พื้นหลังของวันในสัปดาห์",
  Date: "วันที่",
  "Event Title": "ชื่อกิจกรรม",
  "Highlight today": "ไฮไลต์วันนี้",
  "Highlight Color": "เน้นสี",
  Hide: "ซ่อน",
  "Calendar Border Color": "สีเส้นขอบปฏิทิน",
  "Calendar Border Width": "ความกว้างชายแดนปฏิทิน",
  "Calendar Border Style": "สไตล์เส้นขอบปฏิทิน",
  "Font Color": "สีตัวอักษร",
  "Event Background": "พื้นหลังของเหตุการณ์",
  "Card Date Color": "สีของวันที่บัตร",
  "Title Font": "แบบอักษรของชื่อ",
  "Date Font": "วันที่อักษร",
  "Description Font": "คำอธิบายตัวอักษร",
  "Button Background": "พื้นหลังปุ่ม",
  "Button Text": "ข้อความปุ่ม",
  "Border Color": "สีเส้นขอบ",
  "Border Width": "ความกว้างชายแดน",
  "Border Type": "ประเภทชายแดน",
  Title: "หัวข้อ",
  Description: "คำอธิบาย",
  "Background Color": "สีพื้นหลัง",
  Divider: "ตัวคั่น",
  "Event Details Font": "แบบอักษรรายละเอียดกิจกรรม",
  "Website Link Color": "สีลิงค์เว็บไซต์",
  "Developer Info": "ข้อมูลผู้พัฒนา",
  "User Guide": "คู่มือผู้ใช้",
  "Support e-mail": "รองรับอีเมล",
  "Our Website": "เว็บไซต์ของเรา",
  "App Review": "รีวิวแอพ",
  "Enjoying App? Leave us a review in the App Market.":
    "เพลิดเพลินกับแอพหรือยังปล่อยให้เรารีวิวใน App Market ",
  "Review Us": "ตรวจสอบเรา",
  "Connect With Us": "เชื่อมต่อกับเรา",
  "What's your email?": "อีเมลของคุณคืออะไร",
  "Invalid email address!": "ที่อยู่อีเมลไม่ถูกต้อง! ",
  Comments: "ความคิดเห็น",
  "We'd love to hear from you. Send us a message.":
    "เราชอบที่จะได้ยินจากคุณส่งข้อความถึงเรา",
  "Message must be at least 5 characters long":
    "ข้��ความต้องมีความยาวอย่างน้อย 5 ตัวอักษร",
  Send: "ส่ง",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "หากคุณต้องการอนุญาตให้ผู้ใช้สลับระหว่างมุมมองปฏิทินให้เปิดใช้งานตัวเลือกนี้และเลือกมุมมองที่คุณต้องการแสดง",
  Main: "หลัก",
  Localize: "จำกัด",
  Settings: "การตั้งค่า",
  Layouts: "เลย์เอาต์",
  Advanced: "สูง",
  Design: "ออกแบบ",
  Support: "สนับสนุน",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "การตั้งค่าท้องถิ่นทั้งหมด (โดยอัตโนมัติ) ตามภาษาของคุณ หากภาษาของคุณอยู่ในรายการคุณไม่จำเป็นต้องกำหนดหัวข้อนี้เอง",
  "Date Format": "รูปแบบวันที่",
  "Time Format": "รูปแบบเวลา",
  "Text Direction": "ทิศทางข้อความ",
  "Left to Right": "จากซ้ายไปขวา",
  "Right to Left": "จากขวาไปซ้าย",
  "Week Starts On": "สัปดาห์เริ่มต้นใน",
  "Agenda Style": "สไตล์กำหนดการ",
  Classic: "คลาสสิก",
  Modern: "ทันสมัย",
  "Agenda Header": "ส่วนหัวของวาระ",
  "Upcoming Events": "เหตุการณ์ที่จะเกิดขึ้น",
  "Agenda Event Limit": "กำหนดการ จำกัด กิจกรรม",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "อั��เกรดทันทีและรับคุณสมบัติเพิ่มเติมมากมายและสนุกกับแอพของคุณแบบเต็ม!",
  "Upgrade Now": "อัพเกรดเดี๋ยวนี้",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "การโฮสต์กิจกรรมที่ยาวนานตลอดทั้งวันจะให้คุณแสดงในปฏิทินของคุณ",
  "24 hours": "24 ชั่วโมง",
  Sat: "วันเสาร์",
  Sun: "อาทิตย์",
  Mon: "จันทร์",
  Default: "ค่าเริ่มต้น",
  "Select custom design style for your calendar.":
    "เลือกสไตล์การออกแบบที่กำหนดเองสำหรับปฏิทินของคุณ",
  Style: "สไตล์",
  "Styles and Colors": "สไตล์และสี",
  "Calendar Name": "ชื่อปฏิทิน",
  "Write your Calendar name here": "เขียนชื่อปฏิทินของคุณที่นี่",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "ผู้ใช้ของคุณจะไม่เห็นสิ่งนี้ ตั้งชื่อเพื่อแยกความแตกต่างปฏิทินของคุณเมื่อใช้ฟังก์ชัน Boom Calendar Sync",
  "General Info": "ข้อมูลทั่วไป",
  Venue: "Spillested",
  Organizer: "Planlegger",
  Search: "ค้นหา",
  "Add to": "เพิ่ม",
  calendar: "ปฏิทิน",
  "Copy event URL": "Kopier URL event",
  "Copied!": "Kopiert!",
  "Add & Share": "เพิ่มและแบ่งปัน",
  Map: "แผนที่",
  "Calendar view": "มุมมองปฏิทิน",
  "Add Event": "เพิ่มเหตุการณ์",
  Uncategorised: "ไม่มีหมวดหมู่",
  More: "มากกว่า",
  Less: "น้อยกว่า",
  Register: "ลงทะเบียน",
  Card: "การ์ด",
  Guests: "แขกรับเชิญ",
  unlimited: "ไม่ จำกัด",
  "Show more": "แสดงมากขึ้น",
  "Enable Search": "เปิดใช้งานการค้นหา",
  "+ Add Event": "+ เพิ่มกิจกรรม",
  "Manage and Sync": "จัดการและซิงค์",
  "Show event details as...": "แสดงรายละเอียดกิจกรรมเป็น ...",
  Tooltip: "เคล็ดลับ",
  Popup: "กล่องข้อมูล",
  None: "ไม่มี",
  "Show Category": "แสดงหมวด",
  "Header Align": "จัดแนวส่วนหัว",
  "Show Time": "เวลาแสดง",
  "Hours in Weekly/Daily View": "ชั่วโมงในมุมมองรายสัปดาห์ / รายวัน",
  "Share Events": "แบ่งปันกิจกรรม",
  Shadow: "เงา",
  "Inner Padding": "แพ็ดดิ้งภายใน",
  Text: "แพ็ดดิ้งภายใน",
  "Active Button Border": "เส้นขอบปุ่มที่ใช้งาน",
  "Light Mode": "โหมดแสง",
  "Event Text Color": "สีข้อความของเหตุการณ์",
  Dates: "วันที่",
  Skeleton: "โครงกระดูก",
  "Skeleton Color": "โครงกระดูกสี",
  Width: "ความกว้าง",
  "Skeleton Style": "สไตล์โครงกระดูก",
  Color: "สี",
  "Section Titles": "มาตราชื่อเรื่อง",
  "Section Content": "เนื้อหามาตรา",
  Header: "หัวข้อ",
  Standard: "มาตรฐาน",
  Retro: "ย้อนยุค",
  Silver: "เงิน",
  Night: "กลางคืน",
  Dark: "มืด",
  Aubergine: "มะเขือม่วง",
  "Map Header": "ส่วนหัวของแผนที่",
  "Show Title in mobile": "แสดงชื่อในมือถือ",
  "Card View": "มุมมองการ์ด",
  "Card background color": "สีพื้นหลังการ์ด",
  "Title font": "แบบอักษรชื่อเรื่อง",
  "Desciption font": "แบบอักษรคำอธิบาย",
  "Section font": "ส่วนแบบอักษร",
  "Section divider color": "สีของตัวแบ่งส่วน",
  "Add event": "เพิ่มเหตุการณ์",
  "All Day Event": "กิจกรรมตลอดวัน",
  Location: "สถานที่",
  "Choose a category": "เลือกหมวดหมู่",
  "Venue name": "ชื่อสถานที่",
  "Venue phone": "โทรศัพท์สถานที่",
  "Venue email": "อีเมลสถานที่",
  "Venue website": "เว็บไซต์สถานที่",
  "Organizer name": "ชื่อผู้จัดงาน",
  "Organizer phone": "โทรศัพท์จัดงาน",
  "Organizer email": "อีเมลของผู้จัดงาน",
  "Organizer website": "เว็บไซต์ผู้จัดงาน",
  "Personal info": "ข้อมูลส่วนตัว",
  "First name": "ชื่อจริง",
  "Last name": "นามสกุล",
  "Email Address": "ที่อยู่อีเมล",
  "Additional Notes": "หมายเหตุเพิ่มเติม",
  Back: "กลับ",
  Save: "บันทึก",
  Next: "ต่อไป",
  "Your event has been submitted": "ส่งกิจกรรมของคุณแล้ว",
  "Event submittion has been failed": "การส่งกิจกรรมล้มเหลว",
  "e.g. Birthday Party": "เช่น. ปาร์ตี้วันเกิด",
  "First Name": "ชื่อจริง",
  "Last Name": "นามสกุล",
  "Phone Number": "หมายเลขโทรศัพท์",
  Address: "ที่อยู่",
  "Your comments": "ความเห็นของคุณ",
  "How many guests?": "��ขกกี่คน?",
  "Anything else we need to know?": "มีอะไรอีกบ้างที่เราต้องรู้?",
  "Guests:": "แขกรับเชิญ:",
  Submit: "ส่ง",
  "Go to Calendar": "Gå til Kalender",
  "Registration completed successfully!": "ลงทะเบียนสำเร็จ!",
  "Please check your registered email address":
    "โปรดตรวจสอบที่อยู่อีเมลที่คุณลงทะเบียน",
  "Add to Calendar": "Legg til i kalenderen",
  "Share this Event": "Del denne hendelsen",
  "Sorry something went wrong": "ขอโทษมีบางอย่างผิดพลาด",
  "Back to registration": "กลับไปที่การลงทะเบียน",
  "Date & Location": "Dato og beliggenhet",
  "Date & Time": "Dato tid",
  home: "บ้าน",
  "Header align": "จัดแนวส่วนหัว",
  Footer: "ส่วนท้าย",
  "Categories Filter": "หมวดหมู่ตัวกรอง",
  "Show only upcoming": "แสดงเฉพาะรายการที่จะเกิดขึ้น",
  "Card(s) in a row": "การ์ดในแถว",
  "Space between cards": "ช่องว่างระหว่างการ์ด",
  "Shown events limit": "ขีด จำกัด เหตุการณ์ที่แสดง",
  "Style 1": "สไตล์ 1",
  "Style 2": "สไตล์ 2",
  "Style 3": "สไตล์ 3",
  "Style 4": "สไตล์ 4",
  "Buttons & Links": "ปุ่มและลิงค์",
  "Button corner radius": "รัศมีมุมของปุ่ม",
  "Buttons font": "แบบอักษรปุ่ม",
  "Buttons background": "พื้นหลังปุ่ม",
  "Get notified by Email": "รับการแจ้งเตือนทางอีเมล",
  "Review events": "ตรวจสอบเหตุการณ์",
  "Click on date": "คลิกวันที่",
  "Add Event button": "ปุ่มเพิ่มเหตุการณ์",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "การซิงค์ปฏิทินช่วยให้คุณสามารถรวมกิจกรรมและเซสชันของคุณเข้ากับ Boom Calendar ของคุณ",
  connect: "เชื่อมต่อ",
  "Synchronized Calendars": "ปฏิทินที่ซิงโครไนซ์",
  "Import events": "นำเข้ากิจกรรม",
  Disconnect: "ยกเลิกการเชื่อมต่อ",
  "Choose calendar": "เลือกปฏิทิน",
  "Monitor your Wix events through the sync feature":
    "ตรวจสอบเหตุการณ์ Wix ของคุณผ่านคุณสมบัติการซิงค์",
  "Connect all your Boom calendars available on your website":
    "เชื่อมต่อปฏิทิน Boom ทั้งหมดของคุณที่มีอยู่ในเว็บไซต์ของคุณ",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "จัดกำหนดการเข้าร่วมและจัดการการประชุม Zoom ได้โดยตรงผ่าน Boom Calendar ของเรา",
  "Monitor your Event Brite events through the Event Brite sync feature..":
    "ตรวจสอบกิจกรรม Event Brite ของคุณผ่านคุณสมบัติการซิงค์ Event Brite",
  Email: "อีเมล์",
  "Add-ons": "ส่วนเสริม",
  "Receive notification emails as soon as users add events to your calendar.":
    "รับอีเมลแจ้งเตือนทันทีที่ผู้ใช้เพิ่มกิจกรรมในปฏิทินของคุณ",
  "Enable + button on the calendar header":
    "เปิดใช้งานปุ่ม + บนส่วนหัวของปฏิทิน",
  "Accept or decline events added by customers before making them public.":
    "ยอมรับหรือปฏิเสธเหตุการณ์ที่ลูกค้าเพิ่มขึ้นก่อนที่จะเปิดเผยต่อสาธารณะ",
  "Switch Add Event": "สวิทช์เพิ่มกิจกรรม",
  "Enable your browser cookies to connect to your account.":
    "เปิดใช้งานคุกกี้เบราว์เซอร์ของคุณเพื่อเชื่อมต่อกับบัญชีของคุณ",
  "Learn more": "Learn more",
  "Print Button": "ปุ่มพิมพ์",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "อนุญาตให้ผู้ใช้ของคุณพิมพ์ปฏิทินกิจกรรมบูมของคุณในช่วงวันที่ใดก็ได้",
  "Show Title on mobile": "แสดงชื่อบนมือถือ",
  "Show Skeleton on mobile": "แสดงโครงกระดูกบนมือถือ",
  "Start 7-day Business trial": "เริ่มการทดลองใช้ธุรกิจ 7 วันของคุณ",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "เพลิดเพลินไปกับคุณสมบัติที่ไม่ จำกัด ทั้งหมดเช่นขายตั๋วการลงทะเบียนโปรแกรมเสริมกิจกรรมผู้เยี่ยมชม",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "โปรดทราบ: เมื่อสิ้นสุดระยะเวลาทดลองใช้คุณจะถูกส่งกลับไปยังแผนการสมัครสมาชิกที่มีอยู่ของคุณ",
  "Not Now": "ไม่ใช่ตอนนี้",
  "Start free trial": "เริ่มทดลองใช้ฟรี",
  "Congrats!": "ยินดีด้วย!",
  "Your 7-day Business trial has been successfully activated.":
    "การทดลองใช้งานธุรกิจ 7 วันของคุณได้รับการเปิดใช้งานเรียบร้อยแล้ว",
  Done: "เสร็จแล้ว",
  "Title font color": "สีชื่อตัวอักษร",
  "Desciption font color": "คำอธิบายสีตัวอักษร",
  "Section font color": "ส่วนแบบอักษรสี",
  "Card Header": "ส่วนหัวของการ์ด",
  Category: "หมวดหมู่",
  "Display at the": "แสดงที่",
  top: "สูงสุด",
  bottom: "ล่าง",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "แสดงตัวกรองหมวดหมู่ที่ด้านบนหรือด้านล่างของปฏิทินการตั้งค่าใช้กับวาระการประชุมและการดูบัตรเท่านั้น",
  "Processing your events": "ประมวลผลกิจกรรมของคุณ",
  "Search for events": "ค้นหากิจกรรม",
  "There are no events added": "ไม่มีการเพิ่มกิจกรรม",
  "Location: To be determined": "สถานที่ตั้ง: จะถูกกำหนด",
  "No events for selected date": "ไม่มีกิจกรรมสำหรับวันที่ที่เลือก",
  Uncategorized: "ไม่มีหมวดหมู่",
  "Edit event": "แก้ไขเหตุการณ์",
  "Edit original event": "แก้ไขเหตุการณ์ต้นฉบับ",
  "Copy event": "สำเนากิจกรรม",
  "Copy as new event": "คัดลอกเป็นกิจกรรมใหม่",
  "Delete event": "ลบเหตุการณ์",
  "Stop repeating on this date": "หยุดซ้ำในวันนี้",
  "Exclude this date": "ไม่รวมวันที่นี้",
  "Location is going to be announced": "สถานที่จะประกาศ",
  "Fill your personal information": "กรอกข้อมูลส่วนบุคคลของคุณ",
  "Check Box": "กล่องทำเครื่องหมาย",
  "Single Choice": "ตัวเลือกเดียว",
  Option: "ตัวเลือก",
  "Share Event": "แบ่งปันกิจกรรม",
  "Oops! Something went wrong": "อ๊ะ!บางอย่างผิดพลาด",
  "We are sorry this event has already taken place":
    "เราขออภัยเหตุการณ์นี้เกิดขึ้นแล้ว",
  "Back to calendar": "กลับไปที่ปฏิทิน",
  "This field is required": "ต้องการฟิลด์นี้",
  Phone: "โทรศัพท์",
  "Number field": "ฟิลด์หมายเลข",
  "Please provide a valid email": "โปรดระบุอีเมลที่ถูกต้อง",
  "Select at least one option": "เลือกตัวเลือกอย่างน้อยหนึ่งตัวเลือก",
  "Choose tickets to see total value": "เลือกตั๋วเพื่อดูมูลค่ารวม",
  tickets: "ตั๋ว",
  "Choose Tickets": "เลือกตั๋ว",
  "Choose payment method": "เลือกวิธีการชำระเงิน",
  Pay: "จ่ายเงิน",
  Total: "รวม",
  Free: "ฟรี",
  "Buy tickets": "ซื้อตั๋ว",
  "Sold Out": "ขายหมดแล้ว",
  "Tickets are available": "มีตั๋ว",
  "Sales End": "จุดสิ้นสุดการขาย",
  "Availible from": "มีให้จาก",
  "Go to Orders": "ไปที่คำสั่งซื้อ",
  "Go to Details": "ไปที่รายละเอียด",
  "Group ticket": "ตั๋วกลุ่ม",
  Name: "ชื่อ",
  Price: "ราคา",
  "Order by": "สั่งโดย",
  "Order ID": "รหัสสั่งซื้อ",
  Applied: "สมัครแล้ว",
  Fees: "ค่าธรรมเนียม",
  "Enter promo code": "ป้อนรหัสโปรโมชั่น",
  Apply: "ใช้",
  "Promo Code": "รหัสโปรโมชั่น",
  Cash: "เงินสด",
  "You can find your e-tickets attached to your email or download them":
    "คุณสามารถค้นหา e-tickets ของคุณที่แนบมากับอีเมลของคุณหรือดาวน์โหลด",
  here: "ที่นี่",
  Time: "เวลา",
  "Invalid promo code": "รหัสโปรโมชั่นที่ไม่ถูกต้อง",
  "Credit card": "บัตรเครดิต",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "คุณจะได้รับข้อความยืนยันการลงทะเบียนที่ประสบความสำเร็จในที่อยู่อีเมลของคุณ",
  "You can also check your order details below.":
    "คุณสามารถตรวจสอบรายละเอียดการสั่งซื้อของคุณด้านล่าง",
  at: "ที่",
  Buy: "ซื้อ",
  Donation: "การบริจาค",
  "Enter price": "องค์กร",
  Choose: "เลือก",
  Chosen: "เลือกสรร",
  "Choose your plan": "เลือกแผนของคุณ",
  week: "สัปดาห์",
  wk: "สัปดาห์",
  "Choose plan cycle": "เลือกวงจรแผน",
  months: "เดือน",
  years: "ปี",
  weeks: "หลายสัปดาห์",
  "Copy Event Url": "คัดลอก URL เหตุการณ์",
  "You can find your e-tickets attached to your email or print them":
    "คุณสามารถค้นหา e-tickets ของคุณที่แนบมากับอีเมลของคุณหรือพิมพ์",
  "Guest Info": "ข้อมูลแขกรับเชิญ",
  "Ticket Info": "ข้อมูลตั๋ว",
  "Ticket name": "ชื่อตั๋ว",
  "Ticket price": "ราคาตั๋ว",
  "Ticket ID": "รหัสตั๋ว",
  "If you have any questions contact to organizer":
    "หากคุณมีคำถามใด ๆ ติดต่อผู้จัดงาน",
  "As soon as event ends": "ทันทีที่เหตุการณ์สิ้นสุดลง",
  "1 day after event ends": "1 วันหลังจากเหตุการณ์สิ้นสุดลง",
  "7 days after event ends": "7 วันหลังจากเหตุการณ์สิ้นสุดลง",
  "14 days after event ends": "14 วันหลังจากเหตุการณ์สิ้นสุดลง",
  "30 days after event ends": "30 วันหลังจากเหตุการณ์สิ้นสุดลง",
  Menu: "เมนู",
  "No event for selected date": "ไม่มีเหตุการณ์สำหรับวันที่ที่เลือก",
  view: "ดู",
  List: "รายการ",
  Yearly: "ทุกปี",
  "Year view header": "ส่วนหัวดูปี",
  "Yearly Style": "สไตล์รายปี",
  "There are no events": "ไม่มีเหตุการณ์ใด ๆ",
  Autotranslation: "autotranslation",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "เมื่อเปิดใช้งานวิดเจ็ตปฏิทินของคุณจะถูกแปลตามภาษาของเว็บไซต์* โปรดทราบว่าตราบใดที่ชื่อปฏิทินและคำอธิบายเป็นข้อความที่ป้อนเข้าไม่สามารถแปลได้",
  "Note on mobile": "หมายเหตุบนมือถือ",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "ปิดหรือเปลี่ยนข้อความของแถบ 'ไม่มีกิจกรรม' ในปฏิทินเวอร์ชันมือถือ",
  Autodeletion: "การกรองอัตโนมัติ",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "การเปิดใช้งานตัวเลือกจะลบเหตุการณ์ที่ผ่านมาของคุณออกจากปฏิทินโดยอัตโนมัติ",
  "This does not apply to repeating events!":
    "สิ่งนี้ใช้ไม่ได้กับเหตุการณ์ซ้ำ!",
  "Notify event creators about the guest": "แจ้งผู้ใช้เกี่ยวกับผู้เยี่ยมชม",
  "Send event creators notification emails as soon as guests register for their events":
    "ส่งอีเมลแจ้งเตือนผู้สร้างกิจกรรมทันทีที่แขกลงทะเบียนสำหรับกิจกรรมของพวกเขา",
  "List View Type": "รายการมุมมองรายการ",
  Year: "ปี",
  "Description font": "แบบอักษรคำอธิบาย",
  Connect: "เชื่อมต่อ",
  "You have no events": "คุณไม่มีกิจกรรม",
  Synchronize: "ซิงโครไนซ์",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "การซิงค์ Google ปฏิทินช่วยให้คุณสามารถรวมกิจกรรมและเซสชันของคุณเข้ากับ Boom Calendar ของคุณ",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "การซิงค์ปฏิทิน Outlook ช่วยให้คุณสามารถรวมกิจกรรมและเซสชันของคุณเข้ากับ Boom Calendar ของคุณได้",
  "Your message has been sent successfully!": "ข้อความของคุณถูกส่งไปเรียบร้อย!",
  "There are no synchronized calendars": "ไม่มีปฏิทินที่ซิงโครไนซ์",
  "to view more than 7 events": "เพื่อดูมากกว่า 7 เหตุการณ์",
  "Mobile app": "แอพมือถือ",
  "Admin Account": "บัญชีผู้ดูแลระบบ",
  Password: "รหัสผ่าน",
  "Second User": "ผู้ใช้คนที่สอง",
  Edit: "แก้ไข",
  "Guest limit": "จำกัด แขก",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "การตั้งค่าท้องถิ่นทั้งหมดเป็น (โดยอัตโนมัติ) ตามภาษาของคุณหากภาษาของคุณอยู่ในรายการไม่จำเป็นต้องปรับแต่งส่วนนี้",
  available: "มีให้",
  next: "ต่อไป",
  Tickets: "ตั๋ว",
  Quantity: "ปริมาณ",
  "Promo code": "รหัสโปรโมชั่น",
  "Select a payment method": "เลือกวิธีการจ่ายเงิน",
  Fee: "ค่าธรรมเนียม",
  Book: "หนังสือ",
  "All the tickets have been sold out": "ตั๋วทั้งหมดขายหมดแล้ว",
  "Choose at least one ticket": "เลือกตั๋วอย่างน้อยหนึ่งใบ",
  "First choose ticket": "ก่อนอื่นให้เลือกตั๋ว",
  "Please fill out your personal information.":
    "กรุณากรอกข้อมูลส่วนบุคคลของคุณ",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "เพื่อทำการซื้อที่ประสบความสำเร็จโปรดเลือกวิธีการชำระเงินที่คุณต้องการและป้อนรหัสโปรโมชั่นสำหรับตั๋วลดราคา",
  "Credit/Debit card": "บัตรเครดิต / เดบิต",
  "print here.": "พิมพ์ที่นี่",
  "QR code for all tickets": "รหัส QR สำหรับตั๋วทั้งหมด",
  Duration: "ระยะเวลา",
  "Full Name": "ชื่อเต็ม",
  "Ticket id": "รหัสตั๋ว",
  "Group id": "รหัสกลุ่ม",
  "Choose your ticket.": "เลือกตั๋วของคุณ",
  "Fill out your personal information.": "กรอกข้อมูลส่วนบุคคลของคุณ",
  "Add the payment details.": "เพิ่มรายละเอียดการชำระเงิน",
  "To be determined": "ที่จะต้องพิจารณา",
  "You can find your e-tickets attached to the email or":
    "คุณสามารถค้นหาตั๋วอิเล็กทรอนิกส์ของคุณที่แนบมากับอีเมลหรือ",
  "print here": "พิมพ์ที่นี่",
  "Full name": "ชื่อเต็ม",
  "Group ID": "รหัสกลุ่ม",
  "to Book": "หนังสือ",
  "Unfortunately, your card has been declined":
    "น่าเสียดายที่บัตรของคุณถูกปฏิเสธ",
  "Thank you for your purchase!": "ขอขอบคุณสำหรับการซื้อของคุณ!",
  "Find your printable e-tickets attached to the confirmation email":
    "ค้นหา e-tickets ที่พิมพ์ได้ของคุณที่แนบมากับอีเมลยืนยัน",
  Confirm: "ยืนยัน",

  "Add event": "เพิ่มเหตุการณ์",
  Events: "เหตุการณ์",
  "Event details": "รายละเอียดเหตุการณ์",
  Registration: "การลงทะเบียน",
  "Guests list": "รายชื่อแขก",
  Ticket: "ตั๋ว",
  "General Info": "ข้อมูลทั่วไป",
  "Customize the general settings of your event":
    "ปรับแต่งการตั้งค่าทั่วไปของกิจกรรมของคุณ",
  "Event Title": "ชื่อเหตุการณ์",
  "e.g. Birthday Party": "เช่น. ปาร์ตี้วันเกิด",
  "All Day Event": "เหตุการณ์ตลอดทั้งวัน",
  Cross: "ข้าม",
  Timeline: "เส้นเวลา",
  "Repeating event": "เหตุการณ์ซ้ำ",
  Location: "ที่ตั้ง",
  "Venue name": "ชื่อสถานที่",
  Description: "คำอธิบาย",
  Image: "ภาพ",
  Color: "สี",
  Category: "หมวดหมู่",
  "Add your events to color categories and let your users classify them easily":
    "เพิ่มกิจกรรมของคุณในหมวดหมู่สีและให้ผู้ใช้ของคุณจัดประเภทได้อย่างง่ายดาย",
  "Category name": "ชื่อหมวดหมู่",
  "e.g. Birthdays": "เช่น. วันเกิด",
  Venue: "สถานที่จัดงาน",
  "Where the event takes place": "เหตุการณ์ที่เกิดขึ้น",
  "Venue name": "ชื่อสถานที่",
  "Venue phone": "โทรศัพท์สถานที่",
  "Venue email": "อีเมลสถานที่",
  "Venue website": "เว็บไซต์สถานที่",
  Organizer: "ผู้จัดงาน",
  "Person who makes the event": "บุคคลที่สร้างเหตุการณ์",
  "Organizer name": "ชื่อผู้จัดงาน",
  "Organizer phone": "โทรศัพท์ผู้จัดงาน",
  "Organizer email": "อีเมลผู้จัดงาน",
  "Organizer website": "เว็บไซต์ผู้จัดงาน",
  Save: "บันทึก",
  Cancel: "ยกเลิก",
  Import: "นำเข้า",
  Past: "อดีต",
  All: "ทั้งหมด",
  Upcoming: "ที่กำลังจะมาถึง",
  Uncategorised: "ไม่มีหมวดหมู่",
  "Date Ascending": "วันที่ขึ้นไป",
  "Date Descending": "วันที่ลงมา",
  "Title by A-Z": "ชื่อโดย A-Z",
  "Title by Z-A": "ชื่อโดย Z-A",
  "There are no events for this period": "ไม่มีเหตุการณ์สำหรับช่วงเวลานี้",

  "Auto-Convert Date & Time": "วันที่และเวลาแปลงอัตโนมัติ",
  TimeZone: "เขตเวลา",
  Autodeletion: "การกรองอัตโนมัติ",
  "Layout Settings": "การตั้งค่าเค้าโครง",
  "Yeatly view": "ดูเย้ย่า",
  "Monthly view header": "ส่วนหัวมุมมองรายเดือน",
  "Weekly/Daily view header": "ส่วนหัวดูรายสัปดาห์/รายวัน",
  Acendings: "การกระตุ้น",
  Descending: "ลงมา",
  Standart: "ยืน",
  Silver: "เงิน",
  Retro: "ย้อนยุค",
  Dark: "มืด",
  Night: "กลางคืน",
  Aubergine: "มะเขือ",
  "List view header": "รายการมุมมองรายการ",
  "Side by Side View": "มุมมองด้านข้าง",
  "Customize Proportions": "ปรับแต่งสัดส่วน",
  "Card Margins": "ขอบบัตร",
  "Image opacity (%)": "ภาพความทึบ (%)",
  "Side by Side Header": "ด้านข้างด้านข้าง",
  "Text Align": "จัดเรียงข้อความ",
  "Timeline View": "มุมมองไทม์ไลน์",
  "Title font color": "ชื่อตัวอักษรชื่อ",
  "Desciption font color": "สีแบบอักษรลดลง",
  "Line color": "สี",
  "Date Font color": "วันที่ฟอนต์สี",
  "Daily events background": "พื้นหลังกิจกรรมประจำวัน",
  Alignment: "การจัดตำแหน่ง",
  Vertical: "แนวตั้ง",
  Horizontal: "ตามแนวนอน",
  "Vertical Alignment": "การจัดแนวตั้ง",
  Right: "ขวา",
  Center: "ศูนย์",
  "Horizontal Alignment": "การจัดแนวแนวนอน",
  Top: "สูงสุด",
  Center: "ศูนย์",
  Bottom: "ด้านล่าง",
  "Dates Circle Design": "การออกแบบวงกลมวันที่",
  "Next To The Circle": "ถัดจากวงกลม",
  "In The Circle": "ในวงกลม",
  "Timeline Header": "ส่วนหัวไทม์ไลน์",
  Timeline: "เส้นเวลา",
  "Show only upcoming": "แสดงเฉพาะ",
  "Order by": "สั่งโดย",
  "Timeline Event Limit": "ขีด จำกัด เหตุการณ์ไทม์ไลน์",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "อนุญาตให้ผู้เยี่ยมชมเพิ่มเหตุการณ์ใน Calnedars ในท้องถิ่น: Google, Yahoo, Outlook, Icalendar",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "อนุญาตให้ผู้เยี่ยมชมแบ่งปันกิจกรรมของคุณไปที่ Facebook, LinkedIn, Twitter และอื่น ๆ",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "เพิ่มตัวเลือกการค้นหาในปฏิทินของคุณเพื่อให้ผู้คนค้นหากิจกรรมของคุณตามชื่อเรื่องสถานที่ ฯลฯ",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "อนุญาตให้ผู้ใช้ของคุณพิมพ์ปฏิทินเหตุการณ์บูมของคุณในช่วงวันที่ใดก็ได้",
  "Click to apply a theme to Calendar": "คลิกเพื่อใช้ธีมกับปฏิทิน",
  "Date container color": "วันที่ของคอนเทนเนอร์สี",
  "Daily events background": "พื้นหลังกิจกรรมประจำวัน",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "ใช้ Add-ons เพื่อติดตั้งคุณสมบัติขั้นสูงในปฏิทินของคุณทำให้สามารถใช้งานได้มากขึ้น!",
  "Open Add-ons Store": "เปิดร้านค้า Add-Ons",
  Monday: "วันจันทร์",
  Tuesday: "วันอังคาร",
  Wednesday: "วันพุธ",
  Thursday: "วันพฤหัสบดี",
  Friday: "วันศุกร์",
  Saturday: "วันเสาร์",
  Sunday: "วันอาทิตย์",
  "Yearly view": "มุมมองประจำปี",
  Ascending: "จากน้อยไปมาก",
  "Show event time next to title": "แสดงเวลาเหตุการณ์ถัดจากชื่อเรื่อง",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "ปรับวันที่และเวลาเหตุการณ์ตามเวลาท้องถิ่นของผู้ใช้ตามเขตเวลาของพวกเขา",
  "Display the time zone alongside the event date.":
    "แสดงโซนเวลาควบคู่ไปกับวันที่จัดกิจกรรม",
  "Show event time next to title": "แสดงเวลาเหตุการณ์ถัดจากชื่อเรื่อง",
  "Time Zone": "เขตเวลา",
  "Upload Image": "อัพโหลดรูปภาพ",
  "Choose a Category": "เลือกหมวดหมู่",
  "Color you have chosen will not be shown as you choose category":
    "สีที่คุณเลือกจะไม่แสดงในขณะที่คุณเลือกหมวดหมู่",
  Website: "เว็บไซต์",
  Next: "ต่อไป",
  Save: "บันทึก",
  "Last Name": "นามสกุล",
  "Personal Info": "ข้อมูลส่วนตัว",
  Back: "กลับ",
  "This field is required": "ต้องการฟิลด์นี้",
  "Your event has been submitted": "งานของคุณถูกส่งไปแล้ว",
  "Enter a location": "ป้อนตำแหน่ง",
  "Display the time zone alongside the event date.":
    "แสดงโซนเวลาควบคู่ไปกับวันที่จัดกิจกรรม",
  Home: "บ้าน",
  "Side By Side Event Limit": "ขีด จำกัด เหตุการณ์เคียงข้างกัน",
  "Mobille App": "แอพ Mobille",
  category: "หมวดหมู่",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "ติดตามกำหนดการของคุณได้อย่างง่ายดายโดยนำเข้ากิจกรรม Facebook ของคุณไปยังปฏิทินของคุณ",
  "Synchronized Pages": "ซิงโครไนซ์เพจ",
  "There are no synchronized pages": "ไม่มีหน้าซิงโครไนซ์",
  "Choose page": "เลือกหน้า",
  "You have no events": "คุณไม่มีกิจกรรม",
};
export default th;
