let tl = {
  Categories: "Mga kategorya",
  "Share this event": "Ibahagi ang kaganapang ito",
  Language: "Wika",
  "Show Time Zone": "Ipakita ang time zone",
  "Custom Local Settings": "Pasadyang mga lokal na setting",
  "Add and showcase events on your site using a beautiful calendar.":
    "Magdagdag at ipakita ang mga kaganapan sa iyong site gamit ang isang magandang kalendaryo.",
  "Week Days": "Araw ng linggo",
  "Manage Events": "Pamahalaan ang mga kaganapan",
  General: "Pangkalahatan",
  "Layout Picker": "Layout picker",
  Month: "Buwan",
  Monthly: "Buwanang",
  Week: "Linggo",
  Weekly: "Lingguhan",
  Day: "Araw",
  Daily: "Araw -araw",
  Agenda: "Agenda",
  "Navigation Buttons": "Mga pindutan ng Navigation",
  "Week numbers": "Mga numero ng linggo",
  "Include Weekends": "Isama ang katapusan ng linggo",
  "All-day": "Buong araw",
  "All Day": "Buong araw",
  Label: "Label",
  "Fit to Height": "Magkasya sa taas",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Upang itakda ang mga proporsyon ng app na hindi paganahin ang pagpipiliang ito at baguhin ang laki ng kalendaryo sa editor.",
  "Default Layout": "Default na layout",
  "Monthly view": "Buwanang view",
  "Weekly and Daily view": "Lingguhan at pang -araw -araw na pagtingin",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Maaari kang magbigay ng mga bisita ng isang mas pare -pareho na karanasan sa pamamagitan ng pagpapakita ng parehong bilang ng mga linggo (6) sa bawat oras.",
  "Fixed Weekly Layout": "Naayos ang lingguhang layout",
  back: "Balik",
  Row: "Hilera",
  "Hours in Weekly View": "Mga oras sa lingguhang pagtingin",
  "Hours in Daily View": "Oras sa pang -araw -araw na pagtingin",
  Start: "Magsimula",
  End: "Magtapos",
  "At This Hour": "Sa oras na ito",
  Button: "Pindutan",
  Buttons: "Mga pindutan",
  Sunday: "Linggo",
  Monday: "Lunes",
  Tuesday: "Martes",
  Wednesday: "Miyerkules",
  Thursday: "Huwebes",
  Friday: "Biyernes",
  Saturday: "Sabado",
  "Default Date": "Default na petsa",
  year: "taon",
  month: "Buwan",
  mo: "mo",
  days: "araw",
  ago: "nakaraan",
  ahead: "maaga",
  Yesterday: "Kahapon",
  Today: "Ngayon",
  Tomorrow: "Bukas",
  Custom: "Pasadya",
  "Set Daily Rows Limit": "Itakda ang Limitasyon ng Pang -araw -araw na Rows",
  "Set Proportions": "Itakda ang mga proporsyon",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Payagan ang bisita na magdagdag ng kaganapan sa mga lokal na calnesars: Google, Yahoo, Outlook, Icalendar.",
  Container: "Lalagyan",
  Background: "Background",
  "Container Background": "Background ng lalagyan",
  "Container Borders": "Mga hangganan ng lalagyan",
  Calendar: "Kalendaryo",
  "Event Info Tooltip": "Impormasyon sa Impormasyon sa Kaganapan",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Kapag nag -hover ang mga tao sa isang kaganapan makikita nila ang lahat ng impormasyon tungkol dito sa isang tooltip.",
  "Event Info Window": "Window ng Impormasyon sa Kaganapan",
  "This is the full information window that opens when someone clicks on the event.":
    "Ito ang buong window ng impormasyon na magbubukas kapag may nag -click sa kaganapan.",
  "Use Gradient": "Gumamit ng gradient",
  Vertical: "Patayo",
  Horizontal: "Pahalang",
  First: "Una",
  Second: "Pangalawa",
  diagonal: "dayagonal",
  Radial: "Radial",
  "Select option": "Piliin ang pagpipilian",
  Solid: "Solid",
  Dotted: "May tuldok",
  Dashed: "Dumurog",
  Double: "Doble",
  "Border Radius": "Radius ng hangganan",
  Padding: "Padding",
  "Date Header": "Header ng petsa",
  "Event Default Color": "Kulay ng default na kaganapan",
  "Days of Week": "Araw ng linggo",
  "Days of Week Background": "Mga araw ng background sa linggo",
  Date: "Petsa",
  "Event Title": "Pamagat ng kaganapan",
  "Highlight today": "I -highlight ngayon",
  "Highlight Color": "Kulay ng Highlight",
  Hide: "Tago",
  "Calendar Border Color": "Kulay ng hangganan ng kalendaryo",
  "Calendar Border Width": "Lapad ng hangganan ng kalendaryo",
  "Calendar Border Style": "Istilo ng hangganan ng kalendaryo",
  "Font Color": "Kulay ng font",
  "Event Background": "Background ng kaganapan",
  "Card Date Color": "Kulay ng Petsa ng Card",
  "Title Font": "Pamagat na font",
  "Date Font": "Petsa ng font",
  "Description Font": "Paglalarawan Font",
  "Button Background": "Button Background",
  "Button Text": "Button Text",
  "Border Color": "Kulay ng hangganan",
  "Border Width": "Lapad ng hangganan",
  "Border Type": "Uri ng hangganan",
  Title: "Pamagat",
  Description: "Paglalarawan",
  "Background Color": "Kulay ng background",
  Divider: "Divider",
  "Event Details Font": "Mga Detalye ng Mga Detalye ng Kaganapan",
  "Website Link Color": "Kulay ng link sa website",
  "Developer Info": "Impormasyon sa developer",
  "User Guide": "Gabay sa gumagamit",
  "Support e-mail": "Suportahan ang e-mail",
  "Our Website": "Ang aming website",
  "App Review": "Repasuhin ang App",
  "Enjoying App? Leave us a review in the App Market.":
    "Nagagalak na app? Mag -iwan sa amin ng isang pagsusuri sa merkado ng app.",
  "Review Us": "Suriin kami",
  "Connect With Us": "Kumonekta sa amin",
  "What's your email?": "Ano ang iyong email?",
  "Invalid email address!": "Maling email address!",
  Comments: "Mga Komento",
  "We'd love to hear from you. Send us a message.":
    "Gusto naming makarinig mula sa iyo. Magpadala sa amin ng isang mensahe.",
  "Message must be at least 5 characters long":
    "Ang mensahe ay dapat na hindi bababa sa 5 character ang haba",
  Send: "Ipadala",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Kung nais mong payagan ang gumagamit na lumipat sa pagitan ng mga view ng kalendaryo, paganahin ang pagpipiliang ito at piliin ang mga pananaw na nais mong ipakita.",
  Main: "Pangunahing",
  Localize: "I -localize",
  Settings: "Mga setting",
  Layouts: "Mga Layout",
  Advanced: "Advanced",
  Design: "Disenyo",
  Support: "Suporta",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Ang lahat ng mga lokal na setting ay (awtomatiko) batay sa iyong wika. Kung ang iyong wika ay nasa listahan, hindi na kailangang ipasadya ang seksyong ito.",
  "Date Format": "Format ng petsa",
  "Time Format": "Format ng oras",
  "Text Direction": "Direksyon ng teksto",
  "Left to Right": "Kaliwa sa kanan",
  "Right to Left": "Kanan sa kaliwa",
  "Week Starts On": "Magsisimula ang linggo",
  "Agenda Style": "Estilo ng Agenda",
  Classic: "Klasiko",
  Modern: "Modern",
  "Agenda Header": "Header ng agenda",
  "Upcoming Events": "Paparating na mga kaganapan",
  "Agenda Event Limit": "Limitasyon ng Kaganapan ng Agenda",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Mag -upgrade ngayon at makakuha ng maraming mga tampok at tamasahin ang iyong app nang buo!",
  "Upgrade Now": "Mag-upgrade na ngayon",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Nagho -host ng mga kaganapan na huling araw? Hinahayaan ka nitong ipakita ang mga ito sa iyong kalendaryo.",
  "24 hours": "24 na oras",
  Sat: "Sat",
  Sun: "Araw",
  Mon: "Mon",
  Default: "Default",
  "Select custom design style for your calendar.":
    "Piliin ang istilo ng pasadyang disenyo para sa iyong kalendaryo.",
  Style: "Istilo",
  "Styles and Colors": "Mga Estilo at Kulay",
  "Calendar Name": "Pangalan ng Kalendaryo",
  "Write your Calendar name here":
    "Isulat ang pangalan ng iyong kalendaryo dito",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Hindi ito nakikita ng iyong mga gumagamit. Itakda ang mga pangalan upang makilala ang iyong mga kalendaryo kapag ginagamit ang pagpapaandar ng pag -sync ng kalendaryo.",
  "General Info": "Pangkalahatang Impormasyon",
  Venue: "Lugar",
  Organizer: "Tagapag -ayos",
  Search: "Maghanap",
  "Add to": "Idagdag sa",
  calendar: "kalendaryo",
  "Copy event URL": "Kopyahin ang URL ng Kaganapan",
  "Copied!": "Kinopya!",
  "Add & Share": "Magdagdag at magbahagi",
  Map: "Mapa",
  "Calendar view": "View ng kalendaryo",
  "Add Event": "Magdagdag ng kaganapan",
  Uncategorised: "Uncategorised",
  More: "Higit pa",
  Less: "Mas kaunti",
  Register: "Magrehistro",
  Card: "Card",
  Guests: "Mga panauhin",
  unlimited: "walang limitasyong",
  "Show more": "Ipakita pa",
  "Enable Search": "Paganahin ang paghahanap",
  "+ Add Event": "+ Magdagdag ng kaganapan",
  "Manage and Sync": "Pamahalaan at i -sync",
  "Show event details as...": "Ipakita ang mga detalye ng kaganapan bilang ...",
  Tooltip: "Tooltip",
  Popup: "Popup",
  None: "Wala",
  "Show Category": "Ipakita ang kategorya",
  "Header Align": "Align ng header",
  "Show Time": "Ipakita ang oras",
  "Hours in Weekly/Daily View":
    "Mga oras sa lingguhan/pang -araw -araw na pagtingin",
  "Share Events": "Magbahagi ng mga kaganapan",
  Shadow: "Anino",
  "Inner Padding": "Panloob na padding",
  Text: "Teksto",
  "Active Button Border": "Aktibong Border Border",
  "Light Mode": "Light mode",
  "Event Text Color": "Kulay ng teksto ng kaganapan",
  Dates: "Petsa",
  Skeleton: "Balangkas",
  "Skeleton Color": "Kulay ng balangkas",
  Width: "Lapad",
  "Skeleton Style": "Estilo ng balangkas",
  Color: "Kulay",
  "Section Titles": "Mga pamagat ng seksyon",
  "Section Content": "Nilalaman ng seksyon",
  Header: "Header",
  Standard: "Pamantayan",
  Retro: "Retro",
  Silver: "Pilak",
  Night: "Gabi",
  Dark: "Madilim",
  Aubergine: "Aubergine",
  "Map Header": "Header ng mapa",
  "Show Title in mobile": "Ipakita ang pamagat sa Mobile",
  "Card View": "View ng card",
  "Card background color": "Kulay ng background ng card",
  "Title font": "Pamagat na font",
  "Desciption font": "Desciption font",
  "Section font": "Seksyon font",
  "Section divider color": "Kulay ng Divider ng Seksyon",
  "Add event": "Magdagdag ng kaganapan",
  "All Day Event": "Buong araw na pagdiriwan",
  Location: "Lokasyon",
  "Choose a category": "Pumili ng isang kategorya",
  "Venue name": "Pangalan ng lugar",
  "Venue phone": "Venue phone",
  "Venue email": "Venue email",
  "Venue website": "Website ng Venue",
  "Organizer name": "Pangalan ng Organizer",
  "Organizer phone": "Telepono ng Organizer",
  "Organizer email": "Email ng Organizer",
  "Organizer website": "Website ng Organizer",
  "Personal info": "Personal na impormasyon",
  "First name": "Pangalan",
  "Last name": "Huling pangalan",
  "Email Address": "Email address",
  "Additional Notes": "Karagdagang Mga Tala",
  Back: "Balik",
  Save: "I -save",
  Next: "Susunod",
  "Your event has been submitted": "Ang iyong kaganapan ay isinumite",
  "Event submittion has been failed": "Nabigo ang pagsumite ng kaganapan",
  "e.g. Birthday Party": "hal. Kaarawan ng Kaarawan",
  "First Name": "Pangalan",
  "Last Name": "Huling pangalan",
  "Phone Number": "Numero ng telepono",
  Address: "Address",
  "Your comments": "Iyong komento",
  "How many guests?": "Ilan ang mga panauhin?",
  "Anything else we need to know?": "Ano pa ang kailangan nating malaman?",
  "Guests:": "Mga Panauhin:",
  Submit: "Ipasa",
  "Go to Calendar": "Pumunta sa kalendaryo",
  "Registration completed successfully!":
    "Matagumpay na nakumpleto ang pagpaparehistro!",
  "Please check your registered email address":
    "Mangyaring suriin ang iyong rehistradong email address",
  "Add to Calendar": "Idagdag sa kalendaryo",
  "Share this Event": "Ibahagi ang kaganapang ito",
  "Sorry something went wrong": "Pasensya, mayroong kamalian",
  "Back to registration": "Bumalik sa pagpaparehistro",
  "Date & Location": "Petsa at Lokasyon",
  "Date & Time": "Petsa at oras",
  home: "Home",
  "Header align": "Align ng header",
  Footer: "Footer",
  "Categories Filter": "Mga filter ng kategorya",
  "Show only upcoming": "Ipakita lamang ang paparating",
  "Card(s) in a row": "Ang mga (mga) card sa isang hilera",
  "Space between cards": "Puwang sa pagitan ng mga kard",
  "Shown events limit": "Ipinakita ang limitasyon ng mga kaganapan",
  "Style 1": "Estilo 1",
  "Style 2": "Estilo 2",
  "Style 3": "Estilo 3",
  "Style 4": "Estilo 4",
  "Buttons & Links": "Mga pindutan at Link",
  "Button corner radius": "Button Corner Radius",
  "Buttons font": "Mga pindutan ng font",
  "Buttons background": "Mga pindutan ng background",
  "Get notified by Email": "Ipaalam sa pamamagitan ng email",
  "Review events": "Suriin ang mga kaganapan",
  "Click on date": "Mag -click sa petsa",
  "Add Event button": "Magdagdag ng pindutan ng kaganapan",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Pinapayagan ka ng pag -sync ng kalendaryo na isama ang iyong mga kaganapan at sesyon sa iyong kalendaryo ng boom.",
  connect: "kumonekta",
  "Synchronized Calendars": "Mga naka -synchronize na kalendaryo",
  "Import events": "Mag -import ng mga kaganapan",
  Disconnect: "Idiskonekta",
  "Choose calendar": "Piliin ang Kalendaryo",
  "Monitor your Wix events through the sync feature":
    "Subaybayan ang iyong mga kaganapan sa Wix sa pamamagitan ng tampok na pag -sync",
  "Connect all your Boom calendars available on your website":
    "Ikonekta ang lahat ng iyong mga kalendaryo ng boom na magagamit sa iyong website",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Mag -iskedyul, sumali, at pamahalaan ang mga pagpupulong ng zoom mismo sa pamamagitan ng aming kalendaryo ng boom.",
  "Monitor your Event Brite events through the Event Brite sync feature..":
    "Subaybayan ang Iyong Kaganapan Brite Mga Kaganapan sa pamamagitan ng tampok na Event Brite Sync",
  Email: "Email",
  "Add-ons": "Mga add-on",
  "Receive notification emails as soon as users add events to your calendar.":
    "Makatanggap ng mga email sa abiso sa sandaling magdagdag ang mga gumagamit ng mga kaganapan sa iyong kalendaryo.",
  "Enable + button on the calendar header":
    "Paganahin ang + pindutan sa header ng kalendaryo",
  "Accept or decline events added by customers before making them public.":
    "Tanggapin o tanggihan ang mga kaganapan na idinagdag ng mga customer bago ipahayag ang mga ito.",
  "Switch Add Event": "Lumipat Magdagdag ng Kaganapan",
  "Enable your browser cookies to connect to your account.":
    "Paganahin ang iyong cookies ng browser upang kumonekta sa iyong account.",
  "Learn more": "Matuto nang higit pa",
  "Print Button": "I -print ang pindutan",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Pahintulutan ang iyong mga gumagamit upang i -print ang iyong kalendaryo ng boom event sa anumang saklaw ng petsa.",
  "Show Title on mobile": "Ipakita ang pamagat sa Mobile",
  "Show Skeleton on mobile": "Ipakita ang balangkas sa mobile",
  "Start 7-day Business trial": "Simulan ang 7-araw na pagsubok sa negosyo",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Tangkilikin ang lahat ng mga walang limitasyong tampok, tulad ng mga nagbebenta ng mga tiket, pagrehistro, mga add-on ng kaganapan sa bisita.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Mangyaring tandaan: Sa pagtatapos ng panahon ng pagsubok, ibabalik ka sa iyong umiiral na plano sa subscription.",
  "Not Now": "Hindi ngayon",
  "Start free trial": "Simulan ang libreng pagsubok",
  "Congrats!": "Congrats!",
  "Your 7-day Business trial has been successfully activated.":
    "Ang iyong 7-araw na pagsubok sa negosyo ay matagumpay na na-aktibo.",
  Done: "Tapos na",
  "Title font color": "Pamagat ng Kulay ng Pamagat",
  "Desciption font color": "Kulay ng font ng Desciption",
  "Section font color": "SEKSYON Kulay ng font",
  "Card Header": "Header ng card",
  Category: "Kategorya",
  "Display at the": "Ipakita sa",
  top: "tuktok",
  bottom: "ilalim",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Ipakita ang filter ng kategorya sa tuktok o sa ilalim ng kalendaryo. Ang mga setting ay nalalapat sa mga view ng agenda at card lamang",
  "Processing your events": "Pagproseso ng iyong mga kaganapan",
  "Search for events": "Maghanap para sa mga kaganapan",
  "There are no events added": "Walang mga kaganapan na idinagdag",
  "Location: To be determined": "Lokasyon: upang matukoy",
  "No events for selected date": "Walang mga kaganapan para sa napiling petsa",
  Uncategorized: "Walang kategorya",
  "Edit event": "I -edit ang kaganapan",
  "Edit original event": "I -edit ang orihinal na kaganapan",
  "Copy event": "Kopyahin ang kaganapan",
  "Copy as new event": "Kopyahin bilang bagong kaganapan",
  "Delete event": "Tanggalin ang kaganapan",
  "Stop repeating on this date": "Itigil ang pag -uulit sa petsang ito",
  "Exclude this date": "Ibukod ang petsang ito",
  "Location is going to be announced": "Ang lokasyon ay ibabalita",
  "Fill your personal information": "Punan ang iyong personal na impormasyon",
  "Check Box": "Kahon ng tseke",
  "Single Choice": "Solong pagpipilian",
  Option: "Pagpipilian",
  "Share Event": "Ibahagi ang kaganapan",
  "Oops! Something went wrong": "Oops! May mali",
  "We are sorry this event has already taken place":
    "Paumanhin na naganap na ang kaganapang ito",
  "Back to calendar": "Bumalik sa kalendaryo",
  "This field is required": "Kinakailangan ang patlang na ito",
  Phone: "Telepono",
  "Number field": "Numero ng patlang",
  "Please provide a valid email": "Mangyaring magbigay ng isang wastong email",
  "Select at least one option": "Pumili ng hindi bababa sa isang pagpipilian",
  "Choose tickets to see total value":
    "Pumili ng mga tiket upang makita ang kabuuang halaga",
  tickets: "Mga tiket",
  "Choose Tickets": "Pumili ng mga tiket",
  "Choose payment method": "Piliin ang Paraan ng Pagbabayad",
  Pay: "Magbayad",
  Total: "Kabuuan",
  Free: "Libre",
  "Buy tickets": "Bili ng tiket",
  "Sold Out": "Ubos na",
  "Tickets are available": "Magagamit ang mga tiket",
  "Sales End": "Pagtatapos ng benta",
  "Availible from": "Magagamit mula sa",
  "Go to Orders": "Pumunta sa mga order",
  "Go to Details": "Pumunta sa mga detalye",
  "Group ticket": "Ticket ng pangkat",
  Name: "Pangalan",
  Price: "Presyo",
  "Order by": "Iniutos ni",
  "Order ID": "Order id",
  Applied: "Inilapat",
  Fees: "Bayarin",
  "Enter promo code": "I-Enter ang promo code",
  Apply: "Mag -apply",
  "Promo Code": "Promo code",
  Cash: "Cash",
  "You can find your e-tickets attached to your email or download them":
    "Maaari mong mahanap ang iyong mga e-ticket na nakakabit sa iyong email o i-download ang mga ito",
  here: "dito",
  Time: "Oras",
  "Invalid promo code": "Di -wastong promo code",
  "Credit card": "Credit card",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Makakatanggap ka sa lalong madaling panahon ng isang mensahe ng kumpirmasyon ng matagumpay na pagrehistro sa iyong email address.",
  "You can also check your order details below.":
    "Maaari mo ring suriin ang iyong mga detalye ng order sa ibaba.",
  at: "sa",
  Buy: "Bilhin",
  Donation: "Donasyon",
  "Enter price": "Ipasok ang Presyo",
  Choose: "Piliin",
  Chosen: "Napili",
  "Choose your plan": "Piliin ang iyong plano",
  week: "Linggo",
  wk: "wk",
  "Choose plan cycle": "Piliin ang Cycle ng Plano",
  months: "buwan",
  years: "taon",
  weeks: "Linggo",
  "Copy Event Url": "Kopyahin ang URL ng Kaganapan",
  "You can find your e-tickets attached to your email or print them":
    "Maaari mong mahanap ang iyong mga e-ticket na nakakabit sa iyong email o i-print ang mga ito",
  "Guest Info": "Impormasyon sa panauhin",
  "Ticket Info": "Impormasyon sa tiket",
  "Ticket name": "Pangalan ng tiket",
  "Ticket price": "Presyo ng tiket",
  "Ticket ID": "Ticket ID",
  "If you have any questions contact to organizer":
    "Kung mayroon kang anumang mga katanungan na makipag -ugnay sa tagapag -ayos",
  "As soon as event ends": "Sa sandaling magtatapos ang kaganapan",
  "1 day after event ends": "1 araw matapos ang kaganapan",
  "7 days after event ends": "7 araw matapos ang kaganapan",
  "14 days after event ends": "14 na araw pagkatapos ng kaganapan",
  "30 days after event ends": "30 araw matapos ang kaganapan",
  Menu: "Menu",
  "No event for selected date": "Walang kaganapan para sa napiling petsa",
  view: "tingnan",
  List: "Ilista",
  Year: "Taon",
  Yearly: "Taun -taon",
  "Year view header": "Header ng view ng taon",
  "Yearly Style": "Taunang Estilo",
  "There are no events": "Walang mga kaganapan",
  Autotranslation: "Autotranslation",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Kapag pinagana, ang iyong widget ng kalendaryo ay isasalin batay sa wika ng website. *Tandaan na hangga't ang pamagat ng kalendaryo, at ang mga paglalarawan ay inputted na mga teksto na hindi nila mai -translate.",
  "Note on mobile": "Tandaan sa mobile",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Patayin o baguhin ang teksto ng walang mga kaganapan bar sa mobile na bersyon ng kalendaryo",
  Autodeletion: "Autodeletion",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Ang pagpapagana ng pagpipilian, ay awtomatikong aalisin ang iyong mga nakaraang kaganapan mula sa kalendaryo.",
  "This does not apply to repeating events!":
    "Hindi ito nalalapat sa paulit -ulit na mga kaganapan!",
  "Notify event creators about the guest":
    "Ipaalam ang mga tagalikha ng kaganapan tungkol sa panauhin",
  "Send event creators notification emails as soon as guests register for their events":
    "Magpadala ng mga Event Creators notification emails sa sandaling magrehistro ang mga bisita para sa kanilang mga kaganapan",
  "List View Type": "LIST VIEW TYPE",
  "Description font": "Paglalarawan Font",
  Connect: "Kumonekta",
  "You have no events": "Wala kang mga kaganapan",
  Synchronize: "Mag -synchronize",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Pinapayagan ka ng Google Calendar Sync na isama ang iyong mga kaganapan at sesyon sa iyong kalendaryo ng boom.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Pinapayagan ka ng Outlook Calendar Sync na isama ang iyong mga kaganapan at sesyon sa iyong kalendaryo ng boom.",
  "Your message has been sent successfully!":
    "Matagumpay na naipadala ang iyong mensahe!",
  "There are no synchronized calendars":
    "Walang mga naka -synchronize na kalendaryo",
  "to view more than 7 events": "Upang matingnan ang higit sa 7 mga kaganapan",
  "Mobile app": "Mobile app",
  "Admin Account": "Account ng Admin",
  Password: "Password",
  "Second User": "Pangalawang gumagamit",
  Edit: "I -edit",
  "Guest limit": "Limitasyon ng panauhin",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Ang lahat ng mga lokal na setting ay (awtomatiko) batay sa iyong wika. Kung ang iyong wika ay nasa listahan, hindi na kailangang ipasadya ang seksyong ito.",
  available: "magagamit",
  next: "Susunod",
  Tickets: "Mga tiket",
  Quantity: "Dami",
  "Promo code": "Promo code",
  "Select a payment method": "Pumili ng isang paraan ng pagbabayad",
  Fee: "Bayad",
  Book: "Libro",
  "All the tickets have been sold out": "Ang lahat ng mga tiket ay nabili",
  "Choose at least one ticket": "Pumili ng kahit isang tiket",
  "First choose ticket": "Piliin muna ang tiket",
  "Please fill out your personal information.":
    "Mangyaring punan ang iyong personal na impormasyon.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "Upang makagawa ng isang matagumpay na pagbili, mangyaring piliin ang iyong ginustong paraan ng pagbabayad at ipasok ang promo code para sa mga diskwento na tiket.",
  "Credit/Debit card": "Credit/debit card",
  "print here.": "I -print dito.",
  "QR code for all tickets": "QR code para sa lahat ng mga tiket",
  Duration: "Tagal",
  "Full Name": "Buong pangalan",
  "Ticket id": "Ticket ID",
  "Group id": "Group ID",
  "Choose your ticket.": "Piliin ang iyong tiket.",
  "Fill out your personal information.":
    "Punan ang iyong personal na impormasyon.",
  "Add the payment details.": "Idagdag ang mga detalye ng pagbabayad.",
  "To be determined": "Para malaman",
  "You can find your e-tickets attached to the email or":
    "Maaari mong mahanap ang iyong mga e-ticket na nakakabit sa email o",
  "print here": "I -print dito",
  "Full name": "Buong pangalan",
  "Group ID": "Group ID",
  "to Book": "upang mag -book",
  "Unfortunately, your card has been declined":
    "Sa kasamaang palad, ang iyong card ay tinanggihan",
  "Thank you for your purchase!": "Salamat sa iyong pagbili!",
  "Find your printable e-tickets attached to the confirmation email":
    "Hanapin ang iyong mai-print na e-ticket na nakakabit sa email ng kumpirmasyon",
  Confirm: "Kumpirmahin",
  Events: "Mga kaganapan",
  "Event details": "Mga Detalye ng Kaganapan",
  Registration: "Pagpaparehistro",
  "Guests list": "Listahan ng mga bisita",
  Ticket: "Tiket",
  "Customize the general settings of your event":
    "Ipasadya ang pangkalahatang mga setting ng iyong kaganapan",
  Cross: "Krus",
  Timeline: "Timeline",
  "Repeating event": "Paulit -ulit na kaganapan",
  Image: "Imahe",
  "Add your events to color categories and let your users classify them easily":
    "Idagdag ang iyong mga kaganapan sa mga kategorya ng kulay at hayaan ang iyong mga gumagamit na madaling pag -uri -uriin ang mga ito",
  "Category name": "Pangalan ng kategorya",
  "e.g. Birthdays": "hal. Kaarawan",
  "Where the event takes place": "Kung saan naganap ang kaganapan",
  "Person who makes the event": "Taong gumagawa ng kaganapan",
  Cancel: "Kanselahin",
  Import: "Angkat",
  Past: "Nakaraan",
  All: "Lahat",
  Upcoming: "Paparating",
  "Date Ascending": "Petsa ng pag -akyat",
  "Date Descending": "Petsa ng pagbaba",
  "Title by A-Z": "Pamagat ni A-Z",
  "Title by Z-A": "Pamagat ni Z-A",
  "There are no events for this period":
    "Walang mga kaganapan para sa panahong ito",
  "Auto-Convert Date & Time": "Auto-Convert Petsa at Oras",
  TimeZone: "Timezone",
  "Layout Settings": "Mga Setting ng Layout",
  "Yeatly view": "Yeatly view",
  "Monthly view header": "Buwanang header ng view",
  "Weekly/Daily view header": "Lingguhan/Pang -araw -araw na Header ng View",
  Acendings: "Acendings",
  Descending: "Pababang",
  Standart: "Standart",
  "List view header": "Listahan ng header ng View",
  "Side by Side View": "Magkatabi",
  "Customize Proportions": "Ipasadya ang mga proporsyon",
  "Card Margins": "Mga margin ng card",
  "Image opacity (%)": "Opacity ng Larawan (%)",
  "Side by Side Header": "Sa tabi -tabi header",
  "Text Align": "Text Align",
  "Timeline View": "View ng Timeline",
  "Line color": "Kulay ng linya",
  "Date Font color": "Petsa ng kulay ng font",
  "Daily events background": "Pang -araw -araw na mga kaganapan sa background",
  Alignment: "Pag -align",
  "Vertical Alignment": "Pahalang na linya",
  Right: "Tama",
  Center: "Gitna",
  "Horizontal Alignment": "Pahalang na pagkakahanay",
  Top: "Tuktok",
  Bottom: "Ilalim",
  "Dates Circle Design": "Disenyo ng Circle Circle",
  "Next To The Circle": "Sa tabi ng bilog",
  "In The Circle": "Sa bilog",
  "Timeline Header": "Header ng timeline",
  "Timeline Event Limit": "Limitasyon ng Kaganapan sa Timeline",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Payagan ang bisita na ibahagi ang iyong kaganapan sa Facebook, LinkedIn, Twitter at iba pa.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Magdagdag ng isang pagpipilian sa paghahanap sa iyong kalendaryo upang hayaan ang mga tao na maghanap sa iyong mga kaganapan sa pamamagitan ng pamagat, lugar, atbp.",
  "Click to apply a theme to Calendar":
    "Mag -click upang mag -apply ng isang tema sa kalendaryo",
  "Date container color": "Kulay ng lalagyan ng petsa",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Gamitin ang mga add-on upang mai-install ang mga advanced na tampok sa iyong mga kalendaryo, na ginagawang mas gumagana ang mga ito!",
  "Open Add-ons Store": "Buksan ang mga add-on store",
  "Yearly view": "Taunang pagtingin",
  Ascending: "Umakyat",
  "Show event time next to title":
    "Ipakita ang oras ng kaganapan sa tabi ng pamagat",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Ayusin ang petsa ng kaganapan at oras sa lokal na oras ng gumagamit batay sa kanilang time zone.",
  "Display the time zone alongside the event date.":
    "Ipakita ang time zone sa tabi ng petsa ng kaganapan.",
  "Show event time next to title":
    "Ipakita ang oras ng kaganapan sa tabi ng pamagat",
  "Show event time next to title":
    "Ipakita ang oras ng kaganapan sa tabi ng pamagat",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Ayusin ang petsa ng kaganapan at oras sa lokal na oras ng gumagamit batay sa kanilang time zone.",
  "Display the time zone alongside the event date.":
    "Ipakita ang time zone sa tabi ng petsa ng kaganapan.",
  "Show event time next to title":
    "Ipakita ang oras ng kaganapan sa tabi ng pamagat",
  "Time Zone": "Time zone",
  "Upload Image": "Mag -upload ng imahe",
  "Choose a Category": "Pumili ng isang kategorya",
  "Color you have chosen will not be shown as you choose category":
    "Ang kulay na napili mo ay hindi maipakita habang pinili mo ang kategorya",
  Website: "Website",
  Next: "Susunod",
  Save: "I -save",
  "Last Name": "Huling pangalan",
  "Personal Info": "Personal na impormasyon",
  Back: "Balik",
  "This field is required": "Kinakailangan ang patlang na ito",
  "Your event has been submitted": "Ang iyong kaganapan ay isinumite",
  "Enter a location": "Magpasok ng isang lokasyon",
  "Display the time zone alongside the event date.":
    "Ipakita ang time zone sa tabi ng petsa ng kaganapan.",
  Home: "Home",
  "Side By Side Event Limit": "Sa tabi -tabi ng limitasyon ng kaganapan",
  "Mobille App": "MOBILLE app",
  category: "kategorya",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Madaling subaybayan ang iyong iskedyul sa pamamagitan ng pag-import ng iyong mga kaganapan sa Facebook sa iyong kalendaryo.",
  "Synchronized Pages": "Naka-synchronize na Mga Pahina",
  "There are no synchronized pages": "Walang mga naka-synchronize na pahina",
  "Choose page": "Pumili ng pahina",
  "You have no events": "Wala kang mga kaganapan",
};
export default tl;
