let uk = {
  Categories: "Категорії",
  "Share this event": "Поділіться цією подією",
  Language: "Мова",
  "Show Time Zone": "Показати часовий пояс",
  "Custom Local Settings": "Спеціальні локальні налаштування",
  "Add and showcase events on your site using a beautiful calendar.":
    "Додайте та демонструйте події на своєму сайті за допомогою прекрасного календаря . ",
  "Week Days": "Дні тижня",
  "Manage Events": "Керуйте подіями",
  General: "Загальні",
  "Layout Picker": "Вибір макета",
  Month: "Місяць",
  Monthly: "Щомісяця",
  Week: "Тиждень",
  Weekly: "Щотижня",
  Day: "День",
  Daily: "Щодня",
  Agenda: "Порядок денний",
  "Navigation Buttons": "Кнопки навігації",
  "Week numbers": "Номери тижнів",
  "Include Weekends": "Включити вихідні дні",
  "All-day": "Весь день",
  "All Day": "Весь день",
  Label: "Мітка",
  "Fit to Height": "Підходить до висоти",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Щоб встановити пропорції програми, ручним чином відключіть цю опцію та змініть розмір календаря в редакторі. ",
  "Default Layout": "Макет за замовчуванням",
  "Monthly view": "Щомісячний перегляд",
  "Weekly and Daily view": "Щотижневий і щоденний перегляд",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Ви можете надати відвідувачам більш послідовний досвід, показуючи однакову кількість тижнів ( 6) за один раз.",
  "Fixed Weekly Layout": "Фіксований тижневий макет",
  back: " назад ",
  Row: "Рядок",
  "Hours in Weekly View": "Години в тижневому перегляді",
  "Hours in Daily View": "Години в щоденному перегляді",
  Start: "Почати",
  End: "Кінець",
  "At This Hour": "У цю годину",
  Button: "Кнопка",
  Buttons: "Кнопки",
  Sunday: "Неділя",
  Monday: "Понеділок",
  Tuesday: "Вівторок",
  Wednesday: "Середа",
  Thursday: " Четвер ",
  Friday: "П'ятниця",
  Saturday: "Субота",
  "Default Date": "Дата за замовчуванням",
  year: " рік ",
  month: " місяць ",
  mo: " місяць ",
  days: " днів ",
  ago: " тому ",
  ahead: " вперед ",
  Yesterday: "Вчора",
  Today: "Сьогодні",
  Tomorrow: "Завтра",
  Custom: "Спеціальні",
  "Set Daily Rows Limit": "Встановити обмеження щоденних рядків",
  "Set Proportions": "Встановити пропорції",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Дозволити відвідувачу додавати подію до місцевих Calnedars , Google, Yahoo, Outlook, ICalendar . ",
  Container: "Контейнер",
  Background: "Фон",
  "Container Background": "Фон контейнера",
  "Container Borders": "Межі контейнерів",
  Calendar: "Календар",
  "Event Info Tooltip": "Підказка про інформацію про подію",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Коли люди наведіть курсор на подію, вони побачать всю інформацію про неї в підказці. ",
  "Event Info Window": "Вікно інформації про подію",
  "This is the full information window that opens when someone clicks on the event.":
    "Це повне інформаційне вікно, яке відкриється, коли хтось натискає на подію. ",
  "Use Gradient": "Використовувати градієнт",
  Vertical: "Вертикальна",
  Horizontal: "Горизонтальний",
  First: "Спочатку",
  Second: "Друге",
  diagonal: " діагональ ",
  Radial: "Радіальні",
  "Select option": "Вибрати варіант",
  Solid: "Суцільний",
  Dotted: "Пунктирними",
  Dashed: "Збито",
  Double: "Подвійний",
  "Border Radius": "Прикордонний радіус",
  Padding: "Набивання",
  "Date Header": "Заголовок дати",
  "Event Default Color": "Колір події за замовчуванням",
  "Days of Week": "Дні тижня",
  "Days of Week Background": "Фон днів тижня",
  Date: "Дата",
  "Event Title": "Назва події",
  "Highlight today": "Виділіть сьогодні",
  "Highlight Color": "Колір виділення",
  Hide: "Сховати",
  "Calendar Border Color": "Колір рамки календаря",
  "Calendar Border Width": "Ширина межі календаря",
  "Calendar Border Style": "Стиль межі календаря",
  "Font Color": "Колір шрифту",
  "Event Background": "Фон події",
  "Card Date Color": "Колір дати картки",
  "Title Font": "Шрифт заголовка",
  "Date Font": "Шрифт дати",
  "Description Font": "Опис шрифту",
  "Button Background": "Фон кнопки",
  "Button Text": "Текст кнопки",
  "Border Color": "Колір межі",
  "Border Width": "Ширина кордону",
  "Border Type": "Тип кордону",
  Title: "Назва",
  Description: "Опис",
  "Background Color": "Колір фону",
  Divider: "Дільник",
  "Event Details Font": "Шрифт деталей події",
  "Website Link Color": "Колір посилання на веб-сайт",
  "Developer Info": "Інформація для розробника",
  "User Guide": "Керівництво користувача",
  "Support e-mail": "Підтримка електронної пошти",
  "Our Website": "Наш веб-сайт",
  "App Review": "Огляд додатків",
  "Enjoying App? Leave us a review in the App Market.":
    "Насолоджується додатком? Залиште нам відгук на ринку додатків. ",
  "Review Us": "Перегляньте нас",
  "Connect With Us": "Зв'яжіться з нами",
  "What's your email?": "Який ваш електронний лист? ",
  "Invalid email address!": "Недійсна адреса електронної пошти! ",
  Comments: "Коментарі",
  "We'd love to hear from you. Send us a message.":
    "Ми хотіли б почутись від вас. Надішліть нам повідомлення. ",
  "Message must be at least 5 characters long":
    "Повідомлення має бути не менше 5 символів",
  Send: "Надіслати",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Якщо ви хочете дозволити користувачу перемикатися між переглядами календаря, увімкніть цю опцію та виберіть представлення, яке ви хочете показати. ",
  Main: "Основна",
  Localize: "Локалізувати",
  Settings: "Налаштування",
  Layouts: "Макети",
  Advanced: "Розширений",
  Design: "Дизайн",
  Support: "Підтримка",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Усі локальні налаштування (автоматично) базуються на вашій мові. Якщо ваша мова є у списку, не потрібно налаштовувати цей розділ.",
  "Date Format": "Формат дати",
  "Time Format": "Формат часу",
  "Text Direction": "Напрямок тексту",
  "Left to Right": "Зліва направо",
  "Right to Left": "Право наліво",
  "Week Starts On": "Починається тиждень",
  "Agenda Style": "Стиль порядку денного",
  Classic: "Класичний",
  Modern: "Сучасна",
  "Agenda Header": "Заголовок порядку денного",
  "Upcoming Events": "Майбутні події",
  "Agenda Event Limit": "Ліміт події порядку денного",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Оновіть зараз і отримайте набагато більше функцій та насолоджуйтесь своїм додатком повністю!",
  "Upgrade Now": "Оновити зараз",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Хостинг подій, які тривають цілий день? Це дозволяє показувати їх у своєму календарі.",
  "24 hours": "24 години",
  Sat: "Суб",
  Sun: "Нед",
  Mon: "Пон",
  Default: "За замовчуванням",
  "Select custom design style for your calendar.":
    "Виберіть власний стиль дизайну для вашого календаря.",
  Style: "Стиль",
  "Styles and Colors": "Стилі та кольори",
  "Calendar Name": "Назва календаря",
  "Write your Calendar name here": "Напишіть тут своє ім’я календаря",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Це не видно користувачам. Встановіть імена для розмежування ваших календарів під час використання функції синхронізації календаря Boom.",
  "General Info": "Загальна інформація",
  Venue: "Місце проведення",
  Organizer: "Організатор",
  Search: "Пошук",
  "Add to": "Додати до",
  calendar: "календар",
  "Copy event URL": "Скопіювати URL-адресу події",
  "Copied!": "Скопійовано!",
  "Add & Share": "Додати та поділитися",
  Map: "Карта",
  "Calendar view": "Вигляд календаря",
  "Add Event": "Додати подію",
  Uncategorised: "Без категорії",
  More: "Більше",
  Less: "Менше",
  Register: "Зареєструйтесь",
  Card: "Картка",
  Guests: "Гості",
  unlimited: "необмежений",
  "Show more": "Показати більше",
  "Enable Search": "Увімкнути пошук",
  "+ Add Event": "+ Додати подію",
  "Manage and Sync": "Керування та синхронізація",
  "Show event details as...": "Показати деталі події як ...",
  Tooltip: "Підказка",
  Popup: "Інформаційне поле",
  None: "Жоден",
  "Show Category": "Показати категорію",
  "Header Align": "Вирівнювання заголовка",
  "Show Time": "Показати час",
  "Hours in Weekly/Daily View": "Години в тижневому / щоденному перегляді",
  "Share Events": "Поділитися подіями",
  Shadow: "Тінь",
  "Inner Padding": "Внутрішня оббивка",
  Text: "Текст",
  "Active Button Border": "Активний кордон кнопок",
  "Light Mode": "Режим світла",
  "Event Text Color": "Колір тексту події",
  Dates: "Дати",
  Skeleton: "Скелет",
  "Skeleton Color": "Колір скелета",
  Width: "Ширина",
  "Skeleton Style": "Стиль скелета",
  Color: "Колір",
  "Section Titles": "Заголовки розділу",
  "Section Content": "Зміст розділу",
  Header: "Заголовок",
  Standard: "Стандартний",
  Retro: "Ретро",
  Silver: "Срібло",
  Night: "Ніч",
  Dark: "Темний",
  Aubergine: "Баклажан",
  "Map Header": "Заголовок карти",
  "Show Title in mobile": "Показати заголовок у мобільному телефоні",
  "Card View": "Перегляд картки",
  "Card background color": "Колір фону картки",
  "Title font": "Шрифт заголовка",
  "Desciption font": "Шрифт опису",
  "Section font": "Розділ шрифтів",
  "Section divider color": "Колір дільника розділу",
  "Add event": "Додати подію",
  "All Day Event": "Подія на весь день",
  Location: "Місцезнаходження",
  "Choose a category": "Виберіть категорію",
  "Venue name": "Назва місця проведення",
  "Venue phone": "Телефон телефону",
  "Venue email": "Електронна адреса місця проведення",
  "Venue website": "Веб-сайт місця проведення",
  "Organizer name": "Назва організатора",
  "Organizer phone": "Телефон організатора",
  "Organizer email": "Електронна адреса організатора",
  "Organizer website": "Веб-сайт організатора",
  "Personal info": "Особиста інформація",
  "First name": "Імя",
  "Last name": "Прізвище",
  "Email Address": "Електронна адреса",
  "Additional Notes": "Додаткові нотатки",
  Back: "Назад",
  Save: "Зберегти",
  Next: "Далі",
  "Your event has been submitted": "Ваша подія подана",
  "Event submittion has been failed": "Помилка подання події",
  "e.g. Birthday Party": "наприклад Вечірка на честь дня народження",
  "First Name": "Ім'я",
  "Last Name": "Прізвище",
  "Phone Number": "Номер телефону",
  Address: "Адреса",
  "Your comments": "Ваші коментарі",
  "How many guests?": "Скільки гостей?",
  "Anything else we need to know?": "Щось ще, що ми повинні знати?",
  "Guests:": "Гості:",
  Submit: "Подати",
  "Go to Calendar": "Перейдіть до календаря",
  "Registration completed successfully!": "Реєстрація успішно завершена!",
  "Please check your registered email address":
    "Будь ласка, перевірте свою зареєстровану електронну адресу",
  "Add to Calendar": "Додати в календар",
  "Share this Event": "Поділіться цією подією",
  "Sorry something went wrong": "Вибачте, щось пішло не так",
  "Back to registration": "Повернутися до реєстрації",
  "Date & Location": "Дата та місцеположення",
  "Date & Time": "Дата, час",
  home: "додому",
  "Header align": "Вирівнювання заголовка",
  Footer: "Нижній колонтитул",
  "Categories Filter": "категорії Фільтр",
  "Show only upcoming": "Показати лише майбутні",
  "Card(s) in a row": "Картки в ряд",
  "Space between cards": "Простір між картками",
  "Shown events limit": "Показаний ліміт подій",
  "Style 1": "Стиль 1",
  "Style 2": "Стиль 2",
  "Style 3": "Стиль 3",
  "Style 4": "Стиль 4",
  "Buttons & Links": "Кнопки та посилання",
  "Button corner radius": "Радіус кута кнопки",
  "Buttons font": "Кнопки шрифту",
  "Buttons background": "Кнопки фону",
  "Get notified by Email": "Отримуйте повідомлення електронною поштою",
  "Review events": "Огляд подій",
  "Click on date": "Натисніть на дату",
  "Add Event button": "Кнопка Додати подію",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Синхронізація календаря дозволяє інтегрувати ваші події та сеанси з календарем Boom.",
  connect: "підключити",
  "Synchronized Calendars": "Синхронізовані календарі",
  "Import events": "Імпорт подій",
  Disconnect: "Від'єднати",
  "Choose calendar": "Виберіть календар",
  "Monitor your Wix events through the sync feature":
    "Відстежуйте свої події Wix за допомогою функції синхронізації",
  "Connect all your Boom calendars available on your website":
    "З’єднайте всі свої календарі Boom, доступні на вашому веб-сайті",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Розклад, Приєднання та керування Зустріч масштабування прямо через наш календар Boom.",
  "Monitor your Event Brite events through the Event Brite sync feature..":
    "Відстежуйте події Event Brite за допомогою функції синхронізації Event Brite",
  Email: "Електронна пошта",
  "Add-ons": "Додатки",
  "Receive notification emails as soon as users add events to your calendar.":
    "Отримайте повідомлення електронної пошти, як тільки користувачі додають події до вашого календаря.",
  "Enable + button on the calendar header":
    "Увімкніть + кнопку на заголовку календаря",
  "Accept or decline events added by customers before making them public.":
    "Прийняти або відхилити події, додані клієнтами, перш ніж робити їх громадськість.",
  "Switch Add Event": "Перемикач Додати подію",
  "Enable your browser cookies to connect to your account.":
    "Увімкніть файли cookie браузера для підключення до вашого облікового запису.",
  "Learn more": "Вивчайте більше",
  "Print Button": "Кнопка друку",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Дозвольте своїм користувачам надрукувати календар події Boom у будь-якому діапазоні дат.",
  "Show Title on mobile": "Показати назву на мобільному телефоні",
  "Show Skeleton on mobile": "Показати скелет на мобільний",
  "Start 7-day Business trial": "Почніть 7-денний бізнес-випробування",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Насолоджуйтесь усіма необмеженими функціями, такими як продаж квитків, реєстрації, надбудови подій відвідувача.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Будь ласка, зверніть увагу: наприкінці випробувального періоду ви будете повернуті до існуючого плану підписки.",
  "Not Now": "Не зараз",
  "Start free trial": "Почніть безкоштовну пробну версію",
  "Congrats!": "Вітаю!",
  "Your 7-day Business trial has been successfully activated.":
    "Ваша 7-денна ділова випробування успішно активовано.",
  Done: "Зроблений",
  "Title font color": "Назва шрифту кольору",
  "Desciption font color": "Опис кольору шрифту",
  "Section font color": "Колір шрифту",
  "Card Header": "Заголовок картки",
  Category: "Категорія",
  "Display at the": "Дисплей на",
  top: "вершина",
  bottom: "дно",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Продемонструйте фільтр категорії у верхній або в нижній частині календаря.Налаштування стосується лише порядку денного та картки",
  "Processing your events": "Обробка ваших подій",
  "Search for events": "Пошук подій",
  "There are no events added": "Додано події",
  "Location: To be determined": "Розташування: визначити",
  "No events for selected date": "Немає подій для вибраної дати",
  Uncategorized: "Без категорії",
  "Edit event": "Редагувати подію",
  "Edit original event": "Відредагуйте оригінальну подію",
  "Copy event": "Копіювати подію",
  "Copy as new event": "Копіювати як нову подію",
  "Delete event": "Видалити подію",
  "Stop repeating on this date": "Перестань повторювати на цій даті",
  "Exclude this date": "Виключити цю дату",
  "Location is going to be announced": "Місце розташування буде оголошено",
  "Fill your personal information": "Заповніть свою особисту інформацію",
  "Check Box": "Прапорець",
  "Single Choice": "Єдиний вибір",
  Option: "Опція",
  "Share Event": "Поділитися подією",
  "Oops! Something went wrong": "На жаль!Щось пішло не так",
  "We are sorry this event has already taken place":
    "На жаль, ця подія вже відбулася",
  "Back to calendar": "Повернутися до календаря",
  "This field is required": "Це поле є обов'язковим",
  Phone: "Телефон",
  "Number field": "Поле число",
  "Please provide a valid email": "Будь ласка, надайте дійсну електронну пошту",
  "Select at least one option": "Виберіть принаймні один варіант",
  "Choose tickets to see total value":
    "Виберіть квитки, щоб побачити загальну вартість",
  tickets: "квитки",
  "Choose Tickets": "Виберіть квитки",
  "Choose payment method": "Виберіть спосіб оплати",
  Pay: "Платити",
  Total: "Загальний",
  Free: "Вільний",
  "Buy tickets": "Придбати квитки",
  "Sold Out": "Продано",
  "Tickets are available": "Квитки доступні",
  "Sales End": "Кінець продажів",
  "Availible from": "доступний з",
  "Go to Orders": "Перейдіть на замовлення",
  "Go to Details": "Перейдіть до деталей",
  "Group ticket": "Груповий квиток",
  Name: "Назва",
  Price: "Ціна",
  "Order by": "Сортувати за",
  "Order ID": "Ідентифікатор замовлення",
  Applied: "Застосований",
  Fees: "Збори",
  "Enter promo code": "Введіть промо -код",
  Apply: "Застосовувати",
  "Promo Code": "Промо-код",
  Cash: "Готівка",
  "You can find your e-tickets attached to your email or download them":
    "Ви можете знайти свої електронні квитки, додані до вашої електронної пошти або завантажити їх",
  here: "ось",
  Time: "Час",
  "Invalid promo code": "Недійсний промо -код",
  "Credit card": "Кредитна карта",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Незабаром ви отримаєте повідомлення про підтвердження успішної реєстрації на свою електронну адресу.",
  "You can also check your order details below.":
    "Ви також можете перевірити деталі свого замовлення нижче.",
  at: "в",
  Buy: "Купувати",
  Donation: "Пожертва",
  "Enter price": "Підприємство",
  Choose: "Вибирати",
  Chosen: "Обраний",
  "Choose your plan": "Виберіть свій план",
  week: "тиждень",
  wk: "тиждень",
  "Choose plan cycle": "Виберіть цикл плану",
  months: "місяці",
  years: "роки",
  weeks: "тиждень",
  "Copy Event Url": "Скопіюйте URL -адресу події",
  "You can find your e-tickets attached to your email or print them":
    "Ви можете знайти свої електронні квитки, додані до вашої електронної пошти або надрукувати їх",
  "Guest Info": "Інформація про гості",
  "Ticket Info": "Інформація про квитки",
  "Ticket name": "Назва квитка",
  "Ticket price": "Ціна квитка",
  "Ticket ID": "Ідентифікатор квитка",
  "If you have any questions contact to organizer":
    "Якщо у вас є якісь питання, контактуйте з організатором",
  "As soon as event ends": "Як тільки подія закінчиться",
  "1 day after event ends": "1 день після закінчення події",
  "7 days after event ends": "7 днів після закінчення події",
  "14 days after event ends": "Через 14 днів після закінчення події",
  "30 days after event ends": "Через 30 днів після закінчення події",
  Menu: "Меню",
  "No event for selected date": "Немає події для вибраної дати",
  view: "переглянути",
  List: "Список",
  Year: "Рік",
  Yearly: "Щорічно",
  "Year view header": "Рік перегляду заголовок",
  "Yearly Style": "Щорічний стиль",
  "There are no events": "Події відсутні",
  Autotranslation: "Автотрансляція",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Після включення віджет календаря буде перекладено на основі мови веб-сайту.* Зверніть увагу, що до тих пір, як назва календаря, а описи вводяться тексти, вони не можуть бути перекладені.",
  "Note on mobile": "Примітка на мобільному телефоні",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Вимкніть або змініть текст панелі 'Немає подій' на мобільній версії календаря",
  Autodeletion: "Автоделеція",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Увімкнення опції автоматично видаляє ваші минулі події з календаря.",
  "This does not apply to repeating events!":
    "Це не стосується повторень подій!",
  "Notify event creators about the guest": "Повідомляти користувачів про гостя",
  "Send event creators notification emails as soon as guests register for their events":
    "Надсилайте сповіщення творцям подій електронною поштою, як тільки гості зареєструються на їхні події",
  "List View Type": "Тип перегляду списку",
  "Description font": "Шрифт опису",
  Connect: "підключити",
  "You have no events": "У вас немає подій",
  Synchronize: "Синхронізувати",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Синхронізація Google Calendar дозволяє інтегрувати свої події та сеанси з календарю вашого буму.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Синхронізація календаря Outlook дозволяє інтегрувати свої події та сеанси з календарю вашого буму.",
  "Your message has been sent successfully!":
    "Ваше повідомлення успішно надіслано!",
  "There are no synchronized calendars": "Немає синхронізованих календарів",
  "to view more than 7 events": "Для перегляду більше 7 подій",
  "Mobile app": "Мобільний додаток",
  "Admin Account": "Обліковий запис адміністратора",
  Password: "Пароль",
  "Second User": "Другий користувач",
  Edit: "Редагувати",
  "Guest limit": "Гість",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Всі локальні налаштування (автоматично) на основі вашої мови.Якщо ваша мова перебуває у списку, немає необхідності налаштувати цей розділ.",
  available: "доступний",
  next: "наступний",
  Tickets: "Квитки",
  Quantity: "Кількість",
  "Promo code": "Промо-код",
  "Select a payment method": "Виберіть спосіб оплати",
  Fee: "Плата",
  Book: "Книга",
  "All the tickets have been sold out": "Всі квитки були продані",
  "Choose at least one ticket": "Виберіть принаймні один квиток",
  "First choose ticket": "Спочатку виберіть квиток",
  "Please fill out your personal information.":
    "Будь ласка, заповніть свою особисту інформацію.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "Щоб зробити успішну покупку, виберіть бажаний спосіб оплати та введіть промо-код для знижених квитків.",
  "Credit/Debit card": "Кредитна / дебетова картка",
  "print here.": "Друк тут.",
  "QR code for all tickets": "QR-код для всіх квитків",
  Duration: "Тривалість",
  "Full Name": "Повне ім'я",
  "Ticket id": "ID квитка",
  "Group id": "Ідентифікатор групи",
  "Choose your ticket.": "Виберіть квиток.",
  "Fill out your personal information.": "Заповніть свою особисту інформацію.",
  "Add the payment details.": "Додайте деталі платежу.",
  "To be determined": "Бути визначеним",
  "You can find your e-tickets attached to the email or":
    "Ви можете знайти свої ек-квитки, прикріплені до електронної пошти або",
  "print here": "друк тут",
  "Full name": "Повне ім'я",
  "Group ID": "Ідентифікатор групи",
  "to Book": "забронювати",
  "Unfortunately, your card has been declined":
    "На жаль, ваша картка була відхилена",
  "Thank you for your purchase!": "Дякуємо за покупку!",
  "Find your printable e-tickets attached to the confirmation email":
    "Знайдіть свої електронні квитки, додані до електронної пошти підтвердження",
  Confirm: "Підтверджувати",

  "Add event": "Додати подію",
  Events: "Події",
  "Event details": "Деталі події",
  Registration: "Реєстрація",
  "Guests list": "Список гостей",
  Ticket: "Квиток",
  "General Info": "Загальна інформація",
  "Customize the general settings of your event":
    "Налаштуйте загальні налаштування вашої події",
  "Event Title": "Назва події",
  "e.g. Birthday Party": "напр. Вечірка на День народження",
  "All Day Event": "Цілий день події",
  Cross: "Перехрестя",
  Timeline: "Хронологія",
  "Repeating event": "Повторювальна подія",
  Location: "Місцезнаходження",
  "Venue name": "Назва місця проведення",
  Description: "Опис",
  Image: "Зображення",
  Color: "Забарвлення",
  Category: "Категорія",
  "Add your events to color categories and let your users classify them easily":
    "Додайте свої події до кольорових категорій та дозвольте вашим користувачам класифікувати їх легко",
  "Category name": "Назва категорії",
  "e.g. Birthdays": "напр. Дні народження",
  Venue: "Місце",
  "Where the event takes place": "Де відбувається подія",
  "Venue name": "Назва місця проведення",
  "Venue phone": "Телефон проведення",
  "Venue email": "Електронна пошта місця проведення",
  "Venue website": "Веб -сайт місця проведення",
  Organizer: "Організатор",
  "Person who makes the event": "Людина, яка робить захід",
  "Organizer name": "Назва організатора",
  "Organizer phone": "Організатор телефон",
  "Organizer email": "Електронна пошта організатора",
  "Organizer website": "Веб -сайт організатора",
  Save: "Заощадити",
  Cancel: "Скасувати",
  Import: "Імпорт",
  Past: "Минулий",
  All: "Все",
  Upcoming: "Майбутній",
  Uncategorised: "Без категорії",
  "Date Ascending": "Дата висхідної",
  "Date Descending": "Дата спуск",
  "Title by A-Z": "Назва A-Z",
  "Title by Z-A": "Назва Z-a",
  "There are no events for this period": "Події за цей період немає",

  "Auto-Convert Date & Time": "Дата та час автоконверту",
  TimeZone: "Часовий пояс",
  Autodeletion: "Автоодерна",
  "Layout Settings": "Налаштування макета",
  "Yeatly view": "Помірний вигляд",
  "Monthly view header": "Щомісячний заголовок перегляду",
  "Weekly/Daily view header": "Заголовок щотижневого/щоденного перегляду",
  Acendings: "Вчинки",
  Descending: "Низхідний",
  Standart: "Сторонній",
  Silver: "Срібний",
  Retro: "Ретро",
  Dark: "Темний",
  Night: "Нічний",
  Aubergine: "Баклажан",
  "List view header": "Переглянути заголовок перегляду",
  "Side by Side View": "ПІСЛАД",
  "Customize Proportions": "Налаштуйте пропорції",
  "Card Margins": "Маржа картки",
  "Image opacity (%)": "Непрозорість зображення (%)",
  "Side by Side Header": "Пліч -о -пліч заголовок",
  "Text Align": "Текстовий вирівнювання",
  "Timeline View": "Перегляд хронології",
  "Title font color": "Титульний шрифт кольору",
  "Desciption font color": "Колір шрифту Desciption",
  "Line color": "Лінійний колір",
  "Date Font color": "Дата кольору шрифту",
  "Daily events background": "Щоденний фон подій",
  Alignment: "Вирівнювання",
  Vertical: "Вертикальний",
  Horizontal: "Горизонтальний",
  "Vertical Alignment": "Вертикальне вирівнювання",
  Right: "Право",
  Center: "Центр",
  "Horizontal Alignment": "Горизонтальне вирівнювання",
  Top: "Топ",
  Center: "Центр",
  Bottom: "Дно",
  "Dates Circle Design": "Дати дизайн кола",
  "Next To The Circle": "Поруч з колом",
  "In The Circle": "У колі",
  "Timeline Header": "Заголовок часової шкали",
  Timeline: "Шкала",
  "Show only upcoming": "Показати лише майбутнє",
  "Order by": "Сортувати за",
  "Timeline Event Limit": "Обмеження події часової шкали",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Дозвольте відвідувачам додавати подію до місцевих Calnedars: Google, Yahoo, Outlook, Iclendar.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Дозвольте відвідувачам поділитися своєю подією з Facebook, LinkedIn, Twitter та тощо.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Додайте опцію пошуку у своєму календарі, щоб люди могли шукати ваші події за заголовком, місцем проведення тощо.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Дозвольте своїм користувачам друкувати календар подій Boom у будь -якому діапазоні дат.",
  "Click to apply a theme to Calendar":
    "Клацніть, щоб застосувати тему до календаря",
  "Date container color": "Колір контейнера дати",
  "Daily events background": "Щоденний фон подій",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Використовуйте додатки для встановлення розширених функцій на своїх календарях, роблячи їх більш функціональними!",
  "Open Add-ons Store": "Відкрийте магазин додатків",
  Monday: "Понеділок",
  Tuesday: "У вівторок",
  Wednesday: "Середа",
  Thursday: "Четвер",
  Friday: "П’ятниця",
  Saturday: "Субота",
  Sunday: "Неділя",
  "Yearly view": "Щорічний перегляд",
  Ascending: "Висхід",
  "Show event time next to title": "Показати час події поруч із назвою",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Відрегулюйте дату та час події до місцевого часу користувача на основі їх часового поясу.",
  "Display the time zone alongside the event date.":
    "Відобразити часовий пояс поряд з датою події.",
  "Show event time next to title": "Показати час події поруч із назвою",
  "Time Zone": "Часовий пояс",
  "Upload Image": "Завантажити зображення",
  "Choose a Category": "Виберіть категорію",
  "Color you have chosen will not be shown as you choose category":
    "Вибраний вами колір не буде показаний, коли ви вибрали категорію",
  Website: "Веб -сайт",
  Next: "Наступний",
  Save: "Заощадити",
  "Last Name": "Прізвище",
  "Personal Info": "Особиста інформація",
  Back: "Спинка",
  "This field is required": "Це поле є обов'язковим",
  "Your event has been submitted": "Ваша подія подано",
  "Enter a location": "Введіть місце розташування",
  "Display the time zone alongside the event date.":
    "Відобразити часовий пояс поряд з датою події.",
  Home: "Домашній",
  "Side By Side Event Limit": "Порядна межа події",
  "Mobille App": "Додаток Mobille",
  category: "категорія",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Легко стежте за своїм розкладом, імпортувавши події з Facebook у свій календар.",
  "Synchronized Pages": "Синхронізовані сторінки",
  "There are no synchronized pages": "Немає синхронізованих сторінок",
  "Choose page": "Виберіть сторінку",
  "You have no events": "У вас немає подій",
};
export default uk;
