let vi = {
  Language: "Ngôn ngữ",
  "Show Time Zone": "Hiển thị múi giờ",
  "Custom Local Settings": "Cài đặt cục bộ tùy chỉnh",
  "Add and showcase events on your site using a beautiful calendar.":
    "Thêm và giới thiệu các sự kiện trên trang web của bạn bằng cách sử dụng lịch đẹp.",
  "Week Days": "Ngày trong tuần",
  "Manage Events": "Quản lý sự kiện",
  General: "Tổng quan",
  "Layout Picker": "Bộ chọn bố cục",
  Month: "Tháng",
  Monthly: "Hàng tháng",
  Week: "Tuần",
  Weekly: "Hàng tuần",
  Day: "Ngày",
  Daily: "hằng ngày",
  Agenda: "Chương trình nghị sự",
  "Navigation Buttons": "Nút điều hướng",
  "Week numbers": "Số tuần",
  "Include Weekends": "Bao gồm các ngày cuối tuần",
  "All-day": "Cả ngày",
  "All Day": "Cả ngày",
  Label: "Nhãn mác",
  "Fit to Height": "Vừa với chiều cao",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Để đặt Tỷ lệ ứng dụng theo cách thủ công, hãy tắt tùy chọn này và thay đổi kích thước Lịch trong Trình chỉnh sửa theo cách thủ công.",
  "Default Layout": "Bố cục mặc định",
  "Monthly view": "Xem hàng tháng",
  "Weekly and Daily view": "Chế độ xem hàng tuần và hàng ngày",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Bạn có thể mang đến cho khách truy cập trải nghiệm nhất quán hơn bằng cách hiển thị cùng một số tuần (6) tại một thời điểm.",
  "Fixed Weekly Layout": "Bố cục hàng tuần cố định",
  back: "trở lại",
  Row: "Chèo thuyền",
  "Hours in Weekly View": "Giờ trong Chế độ xem hàng tuần",
  "Hours in Daily View": "Giờ trong Chế độ xem hàng ngày",
  Start: "Khởi đầu",
  End: "Chấm dứt",
  "At This Hour": "Vào giờ này",
  "Add to": "Thêm vào",
  Button: "Cái nút",
  Buttons: "nút",
  Sunday: "chủ nhật",
  Monday: "thứ hai",
  Tuesday: "thứ ba",
  Wednesday: "Thứ Tư",
  Thursday: "Thứ năm",
  Friday: "Thứ sáu",
  Saturday: "thứ bảy",
  "Default Date": "Ngày mặc định",
  year: "năm",
  month: "tháng",
  mo: "tháng",
  days: "ngày",
  ago: "trước kia",
  ahead: "phía trước",
  Yesterday: "Hôm qua",
  Today: "Hôm nay",
  Tomorrow: "Ngày mai",
  Custom: "Tập quán",
  "Set Daily Rows Limit": "Đặt giới hạn hàng ngày",
  "Set Proportions": "Đặt tỷ lệ",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Cho phép khách truy cập thêm sự kiện vào Lịch cục bộ: Google, Yahoo, Outlook, ICalendar.",
  Container: "Thùng đựng hàng",
  Background: "Lý lịch",
  "Container Background": "Nền vùng chứa",
  "Container Borders": "Biên giới vùng chứa",
  Calendar: "Lịch",
  "Event Info Tooltip": "Chú giải công cụ / cửa sổ bật lên thông tin sự kiện",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Khi mọi người di chuột qua một sự kiện, họ sẽ thấy tất cả thông tin về sự kiện đó trong chú giải công cụ.",
  "Event Info Window": "Cửa sổ thông tin sự kiện",
  "This is the full information window that opens when someone clicks on the event.":
    "Đây là cửa sổ thông tin đầy đủ sẽ mở ra khi ai đó nhấp vào sự kiện.",
  "Use Gradient": "Sử dụng Gradient",
  Vertical: "Thẳng đứng",
  Horizontal: "Nằm ngang",
  First: "Ngày thứ nhất",
  Second: "Thứ hai",
  diagonal: "đường chéo",
  Radial: "Xuyên tâm",
  "Select option": "Chọn tùy chọn",
  Solid: "Cứng",
  Dotted: "Say mê",
  Dashed: "Tiêu tan",
  Double: "Gấp đôi",
  "Border Radius": "Bán kính đường viền",
  Padding: "Đệm lót",
  "Date Header": "Tiêu đề ngày",
  "Event Default Color": "Màu mặc định của sự kiện",
  "Days of Week": "Ngày trong tuần",
  "Days of Week Background": "Nền các ngày trong tuần",
  Date: "Ngày",
  "Event Title": "Tiêu đề sự kiện",
  "Highlight today": "Đánh dấu ngày hôm nay",
  "Highlight Color": "Màu nổi bật",
  Hide: "Giấu",
  "Calendar Border Color": "Màu viền lịch",
  "Calendar Border Width": "Chiều rộng đường viền lịch",
  "Calendar Border Style": "Lịch kiểu viền",
  "Section Titles": "Tiêu đề phần",
  "Section Content": "Nội dung phần",
  "Event Background": "Nền sự kiện",
  "Card Date Color": "Màu ngày thẻ",
  "Title Font": "Phông chữ tiêu đề",
  "Date Font": "Phông chữ ngày tháng",
  "Description Font": "Phông chữ mô tả",
  "Button Background": "Nền nút",
  "Button Text": "Nút văn bản",
  "Border Color": "Màu viền",
  "Border Width": "Chiều rộng biên giới",
  "Border Type": "Loại đường viền",
  Title: "Chức vụ",
  Description: "Sự miêu tả",
  "Background Color": "Màu nền",
  Divider: "Dải phân cách",
  "Event Details Font": "Phông chữ chi tiết sự kiện",
  "Website Link Color": "Màu sắc liên kết",
  "Developer Info": "Thông tin nhà phát triển",
  "User Guide": "Hướng dẫn & Trò chuyện",
  "Support e-mail": "Hỗ trợ e-mail",
  "Our Website": "Website của chúng tôi",
  "App Review": "Đánh giá ứng dụng",
  "Enjoying App? Leave us a review in the App Market.":
    "Bạn thích ứng dụng? Để lại cho chúng tôi một đánh giá trong Thị trường ứng dụng.",
  "Review Us": "Đánh giá chúng tôi",
  "Connect With Us": "Kết nối với chúng tôi",
  "What's your email?": "Email của bạn là gì?",
  "Invalid email address!": "Địa chỉ email không hợp lệ!",
  Comments: "Bình luận",
  "We'd love to hear from you. Send us a message.":
    "Chúng tôi rất muốn nghe từ bạn. Gửi tin nhắn cho chúng tôi.",
  "Message must be at least 5 characters long":
    "Tin nhắn phải dài ít nhất 5 ký tự",
  Send: "Gửi",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Nếu bạn muốn cho phép người dùng chuyển đổi giữa các chế độ xem lịch, hãy bật tùy chọn này và chọn các chế độ xem bạn muốn hiển thị.",
  Main: "Chủ yếu",
  Localize: "Bản địa hóa",
  Settings: "Cài đặt",
  Layouts: "Bố cục",
  Advanced: "Trình độ cao",
  Design: "Thiết kế",
  Support: "Hỗ trợ",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Tất cả các cài đặt cục bộ đều (tự động) dựa trên ngôn ngữ của bạn. Nếu ngôn ngữ của bạn có trong danh sách, không cần phải tùy chỉnh phần này.",
  "Date Format": "Định dạng ngày tháng",
  "Time Format": "Định dạng thời gian",
  "Text Direction": "Văn bản chỉ đạo",
  "Left to Right": "Trái sang phải",
  "Right to Left": "Phải sang trái",
  "Week Starts On": "Tuần bắt đầu vào",
  "Agenda Style": "Phong cách chương trình nghị sự",
  Classic: "Kinh điển",
  Modern: "Hiện đại",
  "Agenda Header": "Tiêu đề chương trình làm việc",
  "Upcoming Events": "sự kiện sắp tới",
  "Agenda Event Limit": "Giới hạn sự kiện trong chương trình làm việc",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Nâng cấp ngay bây giờ và nhận được nhiều tính năng hơn và tận hưởng APP của bạn một cách trọn vẹn!",
  "Upgrade Now": "Nâng cấp ngay bây giờ",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Tổ chức các sự kiện kéo dài cả ngày? Điều này cho phép bạn hiển thị chúng trên lịch của mình.",
  "24 hours": "24 tiếng",
  Sun: "mặt trời",
  Mon: "Thứ hai",
  Sat: "Đã ngồi",
  Default: "Vỡ nợ",
  Style: "Phong cách",
  "Calendar Name": "Tên lịch",
  "Write your Calendar name here": "Viết tên Lịch của bạn ở đây",
  "Enable Search": "Bật tìm kiếm",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Điều này không hiển thị cho người dùng của bạn. Đặt tên để phân biệt các lịch của bạn khi sử dụng chức năng Boom Calendar Sync.",
  "+ Add Event": "+ Thêm sự kiện",
  "Manage and Sync": "Quản lý và đồng bộ hóa",
  "Show event details as...": "Hiển thị chi tiết sự kiện dưới dạng ...",
  Tooltip: "Chú giải công cụ",
  Popup: "Cửa sổ bật lên",
  None: "Không có",
  "Show Category": "Hiển thị danh mục",
  "Header Align": "Căn chỉnh tiêu đề",
  "Show Time": "Hiển thị thời gian",
  "Hours in Weekly/Daily View": "Giờ trong Chế độ xem hàng tuần / hàng ngày",
  "Share Events": "Chia sẻ sự kiện",
  Shadow: "Bong tôi",
  "Inner Padding": "Đệm bên trong",
  Text: "Chữ",
  "Active Button Border": "Đường viền nút hoạt động",
  "Light Mode": "Chế độ sáng",
  "Event Text Color": "Màu văn bản sự kiện",
  Dates: "ngày",
  Skeleton: "Bộ xương",
  "Skeleton Color": "Màu da",
  Width: "Chiều rộng",
  "Skeleton Style": "Phong cách Skeleton",
  Color: "Màu sắc",
  Header: "Tiêu đề",
  Map: "Bản đồ",
  Standard: "Tiêu chuẩn",
  Retro: "Cổ điển",
  Silver: "Màu bạc",
  Night: "Đêm",
  Dark: "Tối tăm",
  Aubergine: "Aubergine",
  "Map Header": "Tiêu đề bản đồ",
  "Show Title in mobile": "Hiển thị Tiêu đề trong điện thoại di động",
  Card: "Thẻ",
  "Card View": "Xem thẻ",
  "Card background color": "Màu nền thẻ",
  "Title font": "Phông chữ tiêu đề",
  "Desciption font": "Phông chữ mô tả",
  "Section font": "Phần phông chữ",
  "Section divider color": "Màu của dải phân cách",
  "Font Color": "Màu phông chữ",
  "General Info": "Thông tin chung",
  Venue: "Địa điểm",
  Organizer: "Người tổ chức",
  Search: "Tìm kiếm",
  calendar: "lịch",
  "Share this event": "Chia sẻ sự kiện này",
  "Copy event URL": "Sao chép URL sự kiện",
  "Copied!": "Đã sao chép!",
  "Add & Share": "Thêm & Chia sẻ",
  "Calendar view": "Chế độ xem lịch",
  "Add Event": "Thêm sự kiện",
  Uncategorised: "Chưa được phân loại",
  Categories: "Thể loại",
  More: "Hơn",
  Less: "Ít hơn",
  Register: "Đăng ký",
  Guests: "Khách",
  unlimited: "vô hạn",
  "Show more": "Cho xem nhiều hơn",
  "Add event": "Thêm sự kiện",
  "All Day Event": "Sự kiện cả ngày",
  Location: "Địa điểm",
  "Choose a category": "Chọn một danh mục",
  "Venue name": "Tên địa điểm",
  "Venue phone": "Điện thoại địa điểm",
  "Venue email": "Địa chỉ email",
  "Venue website": "Trang web địa điểm",
  "Organizer name": "Tên người tổ chức",
  "Organizer phone": "Điện thoại của người tổ chức",
  "Organizer email": "Email của người tổ chức",
  "Organizer website": "Trang web của nhà tổ chức",
  "Personal info": "Thông tin cá nhân",
  "First name": "Họ",
  "Last name": "Họ",
  "Email Address": "Địa chỉ email",
  "Additional Notes": "Ghi chú bổ sung",
  Back: "Trở lại",
  Save: "Cứu",
  Next: "Kế tiếp",
  "Your event has been submitted": "Sự kiện của bạn đã được gửi",
  "Event submittion has been failed": "Gửi sự kiện không thành công",
  "e.g. Birthday Party": "ví dụ. Tiệc sinh nhật",
  "First Name": "Họ",
  "Last Name": "Họ",
  "Phone Number": "Số điện thoại",
  Address: "Địa chỉ nhà",
  "Your comments": "Bình luận của bạn",
  "How many guests?": "Có bao nhiêu vị khách?",
  "Anything else we need to know?": "Còn điều gì khác chúng ta cần biết không?",
  "Guests: ": "Khách:",
  Submit: "Nộp",
  "Go to Calendar": "Đi tới Lịch",
  "Registration completed successfully!": "Đăng ký đã hoàn tất thành công!",
  "Please check your registered email address":
    "Vui lòng kiểm tra địa chỉ email đã đăng ký của bạn",
  "Add to Calendar": "Thêm vào Lịch",
  "Share this Event": "Chia sẻ sự kiện này",
  "Sorry something went wrong": "Xin lỗi, có lỗi xảy ra",
  "Back to registration": "Quay lại đăng ký",
  "Date & Location": "Ngày & Vị trí",
  "Date & Time": "Ngày giờ",
  home: "Trang Chủ",
  "Header align": "Căn chỉnh tiêu đề",
  Footer: "Chân trang",
  "Categories Filter": "Bộ lọc danh mục",
  "Show only upcoming": "Chỉ hiển thị sắp tới",
  "Card(s) in a row": "(Các) thẻ liên tiếp",
  "Space between cards": "Khoảng cách giữa các thẻ",
  "Shown events limit": "Giới hạn sự kiện được hiển thị",
  "Style 1": "Phong cách 1",
  "Style 2": "Phong cách 2",
  "Style 3": "Phong cách 3",
  "Style 4": "Phong cách 4",
  "Buttons & Links": "Các nút và liên kết",
  "Button corner radius": "Bán kính góc nút",
  "Buttons font": "Phông chữ các nút",
  "Buttons background": "Các nút nền",
  "Get notified by Email": "Nhận thông báo qua Email",
  "Review events": "Xem lại các sự kiện",
  "Click on date": "Bấm vào ngày",
  "Add Event button": "Thêm nút Sự kiện",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Đồng bộ hóa lịch cho phép bạn tích hợp các sự kiện và phiên của mình với Lịch bùng nổ.",
  connect: "liên kết",
  "Synchronized Calendars": "Lịch được đồng bộ hóa",
  "Import events": "Nhập sự kiện",
  Disconnect: "Ngắt kết nối",
  "Choose calendar": "Chọn lịch",
  "Monitor your Wix events through the sync feature":
    "Giám sát các sự kiện Wix của bạn thông qua tính năng đồng bộ hóa",
  "Connect all your Boom calendars available on your website":
    "Kết nối tất cả các lịch Boom có ​​sẵn trên trang web của bạn",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Lên lịch, tham gia và quản lý các cuộc họp Zoom ngay thông qua Lịch Boom của chúng tôi.",
  "Monitor your Event Brite events through the Event Brite sync feature..":
    "Theo dõi các sự kiện Event Brite của bạn thông qua tính năng đồng bộ hóa Event Brite",
  Email: "E-mail",
  "Add-ons": "Tiện ích bổ sung",
  "Switch Add Event": "Chuyển đổi Thêm sự kiện",
  "Enable your browser cookies to connect to your account.":
    "Bật cookie của trình duyệt để kết nối với tài khoản của bạn.",
  "Learn more": "Tìm hiểu thêm",
  "Print Button": "Nút in",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Cho phép người dùng in Lịch sự kiện bùng nổ của bạn trong bất kỳ phạm vi ngày nào.",
  "Show Title on mobile": "Hiển thị Tiêu đề trên điện thoại di động",
  "Show Skeleton on mobile": "Hiển thị Skeleton trên thiết bị di động",
  "Start 7-day Business trial": "Bắt đầu dùng thử 7 ngày dành cho Doanh nghiệp",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Tận hưởng tất cả các tính năng Unlimiited, chẳng hạn như Bán vé, Đăng ký, Tiện ích sự kiện của khách truy cập.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Xin lưu ý: Khi kết thúc giai đoạn dùng thử, bạn sẽ được quay lại gói đăng ký hiện có của mình.",
  "Not Now": "Không phải bây giờ",
  "Start free trial": "Dùng thử miễn phí",
  "Congrats!": "Chúc mừng!",
  "Your 7-day Business trial has been successfully activated.":
    "Bản dùng thử 7 ngày dành cho Doanh nghiệp của bạn đã được kích hoạt thành công.",
  Done: "Làm xong",
  "Title font color": "Màu phông chữ tiêu đề",
  "Desciption font color": "Màu phông chữ mô tả",
  "Section font color": "Màu phông chữ phần",
  "Card Header": "Tiêu đề thẻ",
  Category: "Loại",
  "Display at the": "Hiển thị tại",
  top: "đứng đầu",
  bottom: "đáy",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Hiển thị bộ lọc danh mục ở đầu hoặc cuối lịch. Cài đặt chỉ áp dụng cho các chế độ xem Chương trình làm việc và Thẻ",
  "Processing your events": "Xử lý các sự kiện của bạn",
  "Search for events": "Tìm kiếm sự kiện",
  "There are no events added": "Không có sự kiện nào được thêm vào",
  "Location: To be determined": "Vị trí: Được xác định",
  "No events for selected date": "Không có sự kiện nào cho ngày đã chọn",
  Uncategorized: "Chưa được phân loại",
  "Edit event": "Chỉnh sửa sự kiện",
  "Edit original event": "Chỉnh sửa sự kiện ban đầu",
  "Copy event": "Sao chép sự kiện",
  "Copy as new event": "Sao chép làm sự kiện mới",
  "Delete event": "Xóa sự kiện",
  "Stop repeating on this date": "Ngừng lặp lại vào ngày này",
  "Exclude this date": "Loại trừ ngày này",
  "Location is going to be announced": "Vị trí sẽ được công bố",
  "Fill your personal information": "Điền thông tin cá nhân của bạn",
  "Check Box": "Hộp kiểm",
  "Single Choice": "Sự lựa chọn đơn lẻ",
  Option: "Quyền mua",
  "Share Event": "Chia sẻ sự kiện",
  "Oops! Something went wrong": "Ối!Có gì đó đã sai",
  "We are sorry this event has already taken place":
    "Chúng tôi xin lỗi sự kiện này đã diễn ra",
  "Back to calendar": "Quay lại lịch",
  "This field is required": "Trường này được yêu cầu",
  Phone: "Điện thoại",
  "Number field": "Trường số",
  "Please provide a valid email": "Vui lòng cung cấp một email hợp lệ",
  "Select at least one option": "Chọn ít nhất một tùy chọn",
  "Choose tickets to see total value": "Chọn vé để xem tổng giá trị",
  tickets: "vé",
  "Choose Tickets": "Chọn vé",
  "Choose payment method": "Lựa chọn hình thức thanh toán",
  Pay: "Trả tiền",
  Total: "Tổng cộng",
  Free: "Tự do",
  "Buy tickets": "Mua vé",
  "Sold Out": "Bán hết",
  "Tickets are available": "Vé có sẵn",
  "Sales End": "Kết thúc bán hàng",
  "Availible from": "Có sẵn từ",
  "Go to Orders": "Đi đến đơn đặt hàng",
  "Go to Details": "Đi đến chi tiết",
  "Group ticket": "Vé nhóm",
  Name: "Tên",
  Price: "Giá bán",
  "Order by": "Đặt bởi",
  "Order ID": "ID đặt hàng",
  Applied: "Áp dụng",
  Fees: "Lệ phí",
  "Enter promo code": "Nhập mã khuyến mãi",
  Apply: "Ứng dụng",
  "Promo Code": "Mã khuyến mại",
  Cash: "Tiền mặt",
  "You can find your e-tickets attached to your email or download them":
    "Bạn có thể tìm thấy vé điện tử của mình được đính kèm vào email của bạn hoặc tải xuống chúng",
  here: "nơi đây",
  Time: "Thời gian",
  "Invalid promo code": "Mã khuyến mại không hợp lệ",
  "Credit card": "Thẻ tín dụng",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Bạn sẽ sớm nhận được tin nhắn xác nhận đăng ký thành công vào địa chỉ email của bạn.",
  "You can also check your order details below.":
    "Bạn cũng có thể kiểm tra chi tiết đơn đặt hàng của bạn dưới đây.",
  at: "tại",
  Buy: "Mua",
  Donation: "Quyên góp",
  "Enter price": "Doanh nghiệp",
  Choose: "Chọn",
  Chosen: "Chọn",
  "Choose your plan": "Chọn kế hoạch của bạn",
  week: "tuần",
  wk: "tuần",
  "Choose plan cycle": "Chọn Chu kỳ kế hoạch",
  months: "tháng",
  years: "năm",
  weeks: "tuần",
  "Copy Event Url": "Sao chép URL sự kiện",
  "You can find your e-tickets attached to your email or print them":
    "Bạn có thể tìm thấy vé điện tử của mình được đính kèm vào email của bạn hoặc in chúng",
  "Guest Info": "Thông tin khách",
  "Ticket Info": "Thông tin vé",
  "Ticket name": "Tên vé",
  "Ticket price": "Giá vé",
  "Ticket ID": "ID vé",
  "If you have any questions contact to organizer":
    "Nếu bạn có bất kỳ câu hỏi nào liên hệ với người tổ chức",
  "As soon as event ends": "Ngay khi sự kiện kết thúc",
  "1 day after event ends": "1 ngày sau khi sự kiện kết thúc",
  "7 days after event ends": "7 ngày sau khi sự kiện kết thúc",
  "14 days after event ends": "14 ngày sau khi sự kiện kết thúc",
  "30 days after event ends": "30 ngày sau khi sự kiện kết thúc",
  Menu: "Thực đơn",
  "No event for selected date": "Không có sự kiện nào cho ngày được chọn",
  view: "xem",
  List: "Danh sách",
  Year: "Năm",
  Yearly: "Hàng năm",
  "Year view header": "Tiêu đề xem năm",
  "Yearly Style": "Phong cách hàng năm",
  Autotranslation: "Autotranslation.",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Sau khi bật, tiện ích lịch của bạn sẽ được dịch dựa trên ngôn ngữ của trang web.* Lưu ý rằng miễn là tiêu đề lịch, và các mô tả được nhập các văn bản mà chúng không thể được dịch.",
  "Note on mobile": "Lưu ý trên điện thoại di động",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Tắt hoặc thay đổi văn bản của thanh 'Không có sự kiện' trên phiên bản Lịch di động",
  Autodeletion: "TỰ ĐỘNG",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Kích hoạt tùy chọn, sẽ tự động xóa các sự kiện trước đây của bạn khỏi lịch.",
  "This does not apply to repeating events!":
    "Điều này không áp dụng cho các sự kiện lặp lại!",
  "Notify event creators about the guest": "Thông báo cho người dùng về khách",
  "Send event creators notification emails as soon as guests register for their events":
    "Gửi email thông báo cho người tạo sự kiện ngay khi khách đăng ký sự kiện của họ",
  "List View Type": "Loại xem danh sách",

  "Add event": "Thêm sự kiện",
  Events: "Sự kiện",
  "Event details": "Chi tiết sự kiện",
  Registration: "Sự đăng ký",
  "Guests list": "Danh sách khách",
  Ticket: "Vé",
  "General Info": "Thông tin chung",
  "Customize the general settings of your event":
    "Tùy chỉnh các cài đặt chung của sự kiện của bạn",
  "Event Title": "Tiêu đề sự kiện",
  "e.g. Birthday Party": "ví dụ. Tiệc sinh nhật",
  "All Day Event": "Sự kiện cả ngày",
  Cross: "Đi qua",
  Timeline: "Mốc thời gian",
  "Repeating event": "Lặp lại sự kiện",
  Location: "Vị trí",
  "Venue name": "Tên địa điểm",
  Description: "Sự miêu tả",
  Image: "Hình ảnh",
  Color: "Màu sắc",
  Category: "Loại",
  "Add your events to color categories and let your users classify them easily":
    "Thêm các sự kiện của bạn vào các danh mục màu và để người dùng của bạn dễ dàng phân loại chúng",
  "Category name": "Tên danh mục",
  "e.g. Birthdays": "ví dụ. Sinh nhật",
  Venue: "Địa điểm",
  "Where the event takes place": "Nơi sự kiện diễn ra",
  "Venue name": "Tên địa điểm",
  "Venue phone": "Điện thoại địa điểm",
  "Venue email": "Email địa điểm",
  "Venue website": "Trang web địa điểm",
  Organizer: "Người tổ chức",
  "Person who makes the event": "Người tạo ra sự kiện",
  "Organizer name": "Tên người tổ chức",
  "Organizer phone": "Điện thoại tổ chức",
  "Organizer email": "Email nhà tổ chức",
  "Organizer website": "Trang web tổ chức",
  Save: "Cứu",
  Cancel: "Hủy bỏ",
  Import: "Nhập khẩu",
  Past: "Quá khứ",
  All: "Tất cả",
  Upcoming: "Sắp tới",
  Uncategorised: "Chưa được phân loại",
  "Date Ascending": "Ngày tăng dần",
  "Date Descending": "Ngày giảm dần",
  "Title by A-Z": "Tiêu đề của A-Z",
  "Title by Z-A": "Tiêu đề của Z-A",
  "There are no events for this period":
    "Không có sự kiện nào cho giai đoạn này",

  "Auto-Convert Date & Time": "Ngày & giờ tự động chuyển đổi",
  TimeZone: "Múi giờ",
  Autodeletion: "TỰ ĐỘNG",
  "Layout Settings": "Cài đặt Giao diện",
  "Yeatly view": "Nhìn thấy",
  "Monthly view header": "Tiêu đề xem hàng tháng",
  "Weekly/Daily view header": "Tiêu đề xem hàng tuần/hàng ngày",
  Acendings: "Acendings",
  Descending: "Giảm dần",
  Standart: "Đứng",
  Silver: "Bạc",
  Retro: "Retro",
  Dark: "Tối tăm",
  Night: "Đêm",
  Aubergine: "Aubergine",
  "List view header": "Danh sách xem tiêu đề",
  "Side by Side View": "Chế độ xem bên cạnh",
  "Customize Proportions": "Tùy chỉnh tỷ lệ",
  "Card Margins": "Lợi nhuận thẻ",
  "Image opacity (%)": "Độ mờ hình ảnh (%)",
  "Side by Side Header": "Tiêu đề cạnh nhau",
  "Text Align": "Văn bản căn chỉnh",
  "Timeline View": "Chế độ xem dòng thời gian",
  "Title font color": "Tiêu đề màu sắc phông chữ",
  "Desciption font color": "Màu phông chữ Desciption",
  "Line color": "Màu đường kẻ",
  "Date Font color": "Ngày màu sắc phông chữ",
  "Daily events background": "Bối cảnh sự kiện hàng ngày",
  Alignment: "Liên kết",
  Vertical: "Thẳng đứng",
  Horizontal: "Nằm ngang",
  "Vertical Alignment": "Liên kết dọc",
  Right: "Phải",
  Center: "Trung tâm",
  "Horizontal Alignment": "Liên kết ngang",
  Top: "Đứng đầu",
  Center: "Trung tâm",
  Bottom: "Đáy",
  "Dates Circle Design": "Thiết kế vòng tròn ngày",
  "Next To The Circle": "Bên cạnh vòng tròn",
  "In The Circle": "Trong vòng tròn",
  "Timeline Header": "Tiêu đề dòng thời gian",
  Timeline: "Mốc thời gian",
  "Show only upcoming": "Chỉ hiển thị sắp tới",
  "Order by": "Đặt bởi",
  "Timeline Event Limit": "Giới hạn sự kiện dòng thời gian",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Cho phép khách truy cập thêm sự kiện vào các calnedar địa phương: Google, Yahoo, Outlook, Icalendar.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Cho phép khách truy cập chia sẻ sự kiện của bạn với Facebook, LinkedIn, Twitter và v.v.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Thêm tùy chọn tìm kiếm trên lịch của bạn để cho phép mọi người tìm kiếm sự kiện của bạn theo tiêu đề, địa điểm, v.v.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Cho phép người dùng của bạn in lịch sự kiện bùng nổ của bạn trong bất kỳ phạm vi ngày nào.",
  "Click to apply a theme to Calendar": "Bấm để áp dụng một chủ đề vào lịch",
  "Date container color": "Ngày container màu",
  "Daily events background": "Bối cảnh sự kiện hàng ngày",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Sử dụng các tiện ích bổ sung để cài đặt các tính năng nâng cao trên lịch của bạn, làm cho chúng hoạt động nhiều hơn!",
  "Open Add-ons Store": "Mở cửa hàng tiện ích bổ sung",
  Monday: "Thứ hai",
  Tuesday: "Thứ ba",
  Wednesday: "Thứ Tư",
  Thursday: "Thứ năm",
  Friday: "Thứ sáu",
  Saturday: "Thứ bảy",
  Sunday: "Chủ nhật",
  "Yearly view": "Xem hàng năm",
  Ascending: "Tăng dần",
  "Show event time next to title":
    "Hiển thị thời gian sự kiện bên cạnh tiêu đề",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Điều chỉnh ngày và thời gian sự kiện theo thời gian địa phương của người dùng dựa trên múi giờ của họ.",
  "Display the time zone alongside the event date.":
    "Hiển thị múi giờ cùng với ngày sự kiện.",
  "Show event time next to title":
    "Hiển thị thời gian sự kiện bên cạnh tiêu đề",
  "Time Zone": "Múi giờ",
  "Upload Image": "Tải lên hình ảnh",
  "Choose a Category": "Chọn một danh mục",
  "Color you have chosen will not be shown as you choose category":
    "Màu sắc bạn đã chọn sẽ không được hiển thị khi bạn chọn danh mục",
  Website: "Trang mạng",
  Next: "Kế tiếp",
  Save: "Cứu",
  "Last Name": "Họ",
  "Personal Info": "Thông tin cá nhân",
  Back: "Mặt sau",
  "This field is required": "Trường này được yêu cầu",
  "Your event has been submitted": "Sự kiện của bạn đã được gửi",
  "Enter a location": "Nhập địa điểm",
  "Display the time zone alongside the event date.":
    "Hiển thị múi giờ cùng với ngày sự kiện.",
  Home: "Trang chủ",
  "Side By Side Event Limit": "Giới hạn sự kiện cạnh nhau",
  "Mobille App": "Ứng dụng Mobille",
  category: "loại",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Theo dõi lịch biểu của bạn một cách dễ dàng bằng cách nhập các sự kiện trên Facebook vào lịch của bạn.",
  "Synchronized Pages": "Các trang được đồng bộ hóa",
  "There are no synchronized pages": "Không có trang nào được đồng bộ hóa",
  "Choose page": "Chọn trang",
  "You have no events": "Bạn không có sự kiện",
};
export default vi;
